### ISSUE TITLE
Pull down reload reopens add funds modal

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1001]
## Description 
Pull down reload reopens add funds modal

## Steps to Reproduce 

   1. Enable rewards
   2. Open add funds modal
   3. Close the add funds modal and pull down reload the page, modal shows up again

## Actual result: 
https://youtu.be/m1eNQMVJttg

## Expected result:
Closing the modal should auto update the url from `chrome://rewards/#add-funds` to `chrome://rewards` so that pull down reload doesn't bring back the add funds modal

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Fixed via https://github.com/brave/browser-android-tabs/commit/f6bfc54fa8e9deec1346b2b1739c925971dcaa37

cc: @anthonypkeane @SergeyZhukovsky
