### ISSUE TITLE
Disable rewards still shows view details for Ads and A-C

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1002]
## Description 
Disable rewards still shows view details for Ads and A-C

## Steps to Reproduce 

   1. Enable rewards
   2. Enable ads
   3. Disable rewards, Ads and a-c lists shows `View details` which lists sub level details like a-c list and settings

## Actual result: 
![screenshot_20190121-073554](https://user-images.githubusercontent.com/17010094/51448898-78ee0f00-1d4f-11e9-85ea-f12f9b1afd92.png)

## Expected result:
Similar to desktop everything should be disabled and only wallet summary should be visible

## Issue happens on: 
   - Current Playstore version? No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): All
   - Android Version: All
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @ryanml @SergeyZhukovsky

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/b9301ab42400cffc217b3e93b083b4bfe7aaa2fa

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-21-43-06](https://user-images.githubusercontent.com/38657976/53504839-bbd29d80-3ad8-11e9-9b65-74bb79496481.png)
