### ISSUE TITLE
Browser closes when using hardware back button on view details page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1003]
## Description 
Browser closes when using hardware back button on view details page

## Steps to Reproduce 

   1. Enable rewards
   2. Open `View details` for a-c list
   3. Press the hardware back button to go back to rewards page, instead it backgrounds the app

## Actual result: 
Browser closes when using hardware back button on view details page

## Expected result:
Should navigate back to rewards home page

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build?Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): All
   - Android Version: All
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
That is a dup of https://github.com/brave/browser-android-tabs/issues/905
