### ISSUE TITLE
Landscape mode modal issues

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1004]
## Description 
Landscape mode modal issues

## Steps to Reproduce 

   1. Enable rewards
   2. Change device orientation to landscape
   3. Struggle to go back when you go into a-c details if the back button is on settings
   4. All popup modals are not visible completely. Usability in landscape is difficult on modals 

## Actual result: 
![screenshot_20190121-120304](https://user-images.githubusercontent.com/17010094/51456811-0abc4300-1d75-11e9-95f8-bb96a08e6e77.png)
----
![screenshot_20190121-120348](https://user-images.githubusercontent.com/17010094/51456812-0abc4300-1d75-11e9-8f50-fe952e6f9014.png)
----
![screenshot_20190121-120134](https://user-images.githubusercontent.com/17010094/51456813-0b54d980-1d75-11e9-8e8e-0ffdb5af9fc5.png)

## Expected result:
Should be easy to use rewards popup modals/screen in landscape mode

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone only Tablet has pretty decent real estate in landscape mode
   - Android Version: All
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @ryanml

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74

![1004](https://user-images.githubusercontent.com/34715963/51506903-d84f2c00-1dee-11e9-8221-4002ac52c179.jpg)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/384ffc25ff73898bc6d62695e043a2e4ea488f12
