### ISSUE TITLE
[Tab Specific] Rewards page opens in background and most of the times is blank

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1005]
## Description 
Rewards page opens in background and most of the times is blank

## Steps to Reproduce 

   1. Install rewards build on Android Tab and enable it
   2. Keep rewards page open in a tab
   3. Open a new tab and visit a site
   4. Click on the BR panel and click on settings from the tab on step 3
   5. Rewards page opens in background, switch to it 99% the page is blank, pull down reload doesn't load the page

## Actual result: 
Rewards page opens in background and most of the times is blank

## Expected result:
Rewards page should always load correctly and should be focused when open from BR panel

## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? YES

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Tablet 
   - Android Version:8.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @samartnik

**Comment by SergeyZhukovsky** [comment]
@srirambv could you please verify that?
