### ISSUE TITLE
Incognito mode/Private Mode UI needs more work on Beta Release(Brave Rewards Release)

### ISSUE THREAD

**Issue by thanuj10** [brave/browser-android-tabs#1006]
## Description 
Incognito mode on Brave rewards release need more work. The URL bar stays white and the text is not visible. New tab button on the bottom is not visible but clickable. Clicking on it, open a new tab but not in incognito mode.

## Steps to Reproduce 

   1. Open Brave.
   2. Tap 3 dot menu to open private mode.
   3. See te UI

## Actual result:
Private mode has several mismatches of color and the UI is not legible.

## Expected result:
The UI must be legible and have an even grey colored scheme.

## Issue reproduces how often: 
Everytime Private mode is opened.

## Issue happens on: 
   - Current Playstore version? No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): Arm64
   - Device(Phone, Tablet, Phablet): Phone(Gionee F103 Pro), Phone (Nokia 6.1 Plus)
   - Android Version: Android Marshmallow 6.0.1
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by srirambv** [comment]
This is a Phone specific issue. Screenshot available in #1008 . Tablets work just fine.

**Comment by kjozwiak** [comment]
Reproducible the issue mentioned above on the Pixel 1 running `android 9`. Entering a URL into the field is also difficult to see as the background is also white.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/1272
