### ISSUE TITLE
BR panel shouldn't be active on Private tabs similar to desktop

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1007]
## Description 
BR panel shouldn't be active on Private tabs similar to desktop

## Steps to Reproduce 

   1. Enable rewards 
   2. Open a new private tab
   3. Tap on BR panel shows wallet summary

## Actual result: 
![image from ios](https://user-images.githubusercontent.com/17010094/51466710-da829d80-1d90-11e9-972b-96589c15af4f.jpg)

## Expected result:
BR panel shouldn't be shown on private tabs

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): All
   - Android Version: All
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @samartnik @ryanml

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/1033

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible with build `1.0.83`

**Comment by srirambv** [comment]
This is still an issue on 1.0.86

**Comment by samartnik** [comment]
Re-applied fix here https://github.com/brave/browser-android-tabs/pull/1295
