### ISSUE TITLE
Rewards ON/OFF state is not same on multiple Rewards tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1011]
## Description 
Rewards ON/OFF state is not same on multiple Rewards tabs

## Steps to Reproduce 

   1.  Enable Rewards
   2.  Open multiple Rewards tabs
   3.  Set Rewards to OFF state in one tab
   4. Navigate to other opened Rewards tabs are see Rewards state

## Actual result: 
Rewards state in other opened tabs is ON
## Expected result:
Rewards OFF state should reflect same (OFF) in all othe opened Rewards tabs
## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsumg Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.74
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
This should be fixed with the recent upstream pulldown

cc: @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
