### ISSUE TITLE
Sites visited in Private tabs are added into a-c with attention

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1012]
## Description 
Sites visited in Private tabs are added into a-c with attention

## Steps to Reproduce 

   1. Clean install 1.0.74
   2. Enable rewards
   3. Open a private tab and visit a site and stay on it for 10 secs
   4. Open rewards setting from private tab
   5. Rewards page open in normal tab 
   6. Open `View details` for auto-contribute, site visited in private tab is added into a-c list

## Actual result: 
Sites visited in Private tabs are added into a-c with attention

## Expected result:
Sites visited in private tab should not be considered for a-c 

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#1007
@NejcZdovc @ryanml @SergeyZhukovsky @samartnik

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74

The pages opened in private tabs are added to a-c table.

**Comment by gdregalo** [comment]
Fixed in:
https://github.com/brave/browser-android-tabs/commit/60b8769277a8cb50bb4dd14019692098cc2d0788

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
