### ISSUE TITLE
Multiple page reload on Brave Rewards page is Enabling Rewards even though Rewards is set to OFF

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1013]
## Description 
Multiple page reload on Brave Rewards page is Enabling Rewards even though Rewards is set to OFF

## Steps to Reproduce 

   1. Enable Rewards by clicking on `JOIN REWARDS`
   2. Click on `Settings` and open multiple rewards tabs ( for my test 2 rewards tabs were opened)
   3. Open 1st Rewards tab and set Rewards to OFF state
   4. Open 2nd Rewards tab and make sure Rewards is set ON
   5. Open 1st Rewards tab and do multiple page reload ( I have done page reload twice)
   6. Observe that Rewards is turned ON automatically on 1st Rewards tab

## Actual result: 
On 1st Rewards tab - Rewards is turned ON automatically after multiple page reload

## Expected result:
Rewards switch shouldn't get altered untill user makes the switch ON/OFF manually.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy j3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74

Reproduced on the first try. After reload the rewards was switched on.

**Comment by ryanml** [comment]
This one should be fixed with recently merged upstream changes

cc: @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
