### ISSUE TITLE
`Claim` button is shown always even after accepting grants

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1014]
## Description 
`Claim` button is shown always even after accepting grants

## Steps to Reproduce 

   1. Enable grants by clicking on `JOIN REWARDS`
   2. Click on `Settings` and accept the grants by clicking on `Claim` button
   3. Reload Brave://rewards page 

## Actual result: 
`Claim` button is shown even after accepting grants.

## Expected result:
`Claim` button should not be shown to user after accepting UGP grants.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
@ryanml I verified everything on c++ side. There are two calls. So that one is done from HTML when the page is appeared
`web_ui()->RegisterMessageCallback("brave_rewards.getGrant",
                                    base::BindRepeating(&RewardsDOMHandler::GetGrant,
                                                        base::Unretained(this)));`
After that we call a callback `void RewardsDOMHandler::OnGrant` which calls that web_ui function
`newGrant.SetInteger("status", result);
    newGrant.SetString("promotionId", grant.promotionId);

    web_ui()->CallJavascriptFunctionUnsafe("brave_rewards.grant", newGrant);`

The result when there are no grants is 13 which means that `GRANT_NOT_FOUND = 13`.
But the claim grant button appears in any case.

**Comment by SergeyZhukovsky** [comment]
I guess you need to look on that place in `grant_reducer.ts`:
`case types.ON_GRANT:
      state = { ...state }
      // TODO NZ check why enum can't be used inside Rewards namespace
      if (action.payload.properties.status === 1) {
        state.grant = undefined
        break
      }

      state.grant = {
        promotionId: action.payload.properties.promotionId,
        expiryTime: 0,
        probi: ''
      }
      break`

**Comment by ryanml** [comment]
@SergeyZhukovsky thanks for investigating, looks like then that the status code `13` just needed handling. We don't check for this particular status code in Desktop, so explains why this wasn't picked in.

https://github.com/brave/browser-android-tabs/commit/6116d67f6b13a4b2e11b6db0dd82d4cf58048c7c

This commit should resolve the issue, I am unable to do a full build at the moment but the web-ui built just fine.

**Comment by SergeyZhukovsky** [comment]
It works as expected. Thanks @ryanml!

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
