### ISSUE TITLE
`Monthly Payment` USD  conversion name is not shown completely

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1017]
## Description 
`Monthly Payment` USD  conversion name is not shown completely

## Steps to Reproduce 

   1. Enable Rewards
   2. Click on `View Details` in Auto- Contribution rewards panel
   3.  Verify the `Monthly Payment` BAT and USD values

## Actual result: 
Only `U` is shown on the UI, `S` and `D` are missing.

Screen Size:
Size | 5.0 inches, 68.9 cm2 (~68.2% screen-to-body ratio)

![screenshot_2019-01-21-17-35-19](https://user-images.githubusercontent.com/38657976/51474161-710c8a00-1da4-11e9-9d31-221bd933a156.png)

## Expected result:
USD should be shown completely

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3 (2016)
   - Android Version: 5.1
   
## Brave version:

1.0.74
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74
![1017](https://user-images.githubusercontent.com/34715963/51507283-83acb080-1df0-11e9-8f82-f064c40e22dc.jpg)

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/commit/43a533b951fdc142fec32be71bd7d2698e522a8c

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-19-56-52](https://user-images.githubusercontent.com/38657976/53497671-b2423900-3aca-11e9-9867-9d80548502b6.png)
