### ISSUE TITLE
[Tab Specific] Monthly budget values flow outside the modal size

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1018]
## Description 
Monthly budget values flow outside the modal size

## Steps to Reproduce 

   1. Install 1.0.74
   2. Enable rewards and change monthly budget values
   3. Modal size is small and value overflows from the modal

## Actual result: 
![screenshot_20190119-051421_brave](https://user-images.githubusercontent.com/17010094/51474794-6a7f1200-1da6-11e9-88bb-dc469a7bca97.jpg)

## Expected result:
Values should be contained within the modal

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Tab
   - Android Version: 8.0   

## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/384ffc25ff73898bc6d62695e043a2e4ea488f12
