### ISSUE TITLE
Min time and min page visit settings are not respected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1019]
## Description 
Custom min page time and min page visits settings are not adding sites to a-c table even after min page time and visit criteria is met

## Steps to Reproduce 

   1. Enable Rewards
   2. Click on `View Details` on Auto-Contribution panel
   3. Click on `Settings`
   4. In `Auto-Contribution Settings` panel, set min page time and visits ( For my test i have set 5secs and 
        5 visits)
   5. Visit a site 5 times and stay on site for 5 secs in induvidual visit ( In order to meet the criteria you set)

## Actual result: 

Site is not getting added to a-c table even after the criteria is met

## Expected result:

Sites should get added to a-c table if the min page time and visit criterai is met
## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?Yes

## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet):Android - Samsumg Galaxy J3
   - Android Version: 1.0.74
   
## Brave version:

1.0.74
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by srirambv** [comment]
I think there is a delay in adding sites to the a-c list in general. Sometimes you have to close the rewards page and reopen for the site to list or need to pull-down reload couple of times for it to show up.

**Comment by ryanml** [comment]
@SergeyZhukovsky this one should have been fixed with your recent upstream update

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
