### ISSUE TITLE
Can we remove :: android:permission="android.permission.INSTALL_PACKAGES

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1021]
In line 146, it looks like we are limiting the application to receive the referrer broadcast event only from apps that have the permission INSTALL_PACKAGES granted. 

Can this requirement be removed? 

Link to Code: https://github.com/brave/browser-android-tabs/blob/8e965e627acf097396ae7e7e270fdbb08b8c56f3/chrome/android/java/AndroidManifest.xml

![Untitled.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/a7b0d364-f5ff-47de-a091-fc0c54f874f0)

**Comment by AlexeyBarabash** [comment]
Hey, @anthonypkeane , Brave browser for Android does not have INSTALL_PACKAGES permission.
The thing you have pointed means:
Brave wants to receive the notification of type `com.android.vending.INSTALL_REFERRER` only from those apps who have `android.permission.INSTALL_PACKAGES` permission, including Google Play app.

Maybe we will change that to `android.permission.CLEAR_APP_CACHE`.

**Comment by diracdeltas** [comment]
Note: this issue is currently not approved by security team. Please do not change the permissions without getting approval from me, thanks. Feel free to DM me for more info

**Comment by diracdeltas** [comment]
I think this is no longer needed as of the updated spec https://docs.google.com/document/d/1hJVuqmrNo7eDoEzCpKS_PXb33n2o6g1JLjUaJTJ-CtU/edit
