### ISSUE TITLE
Tipped site and tip amount is not displayed under Tip panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1024]
## Description 
Tipped site and tip amount is not displayed under Tips panel

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim UGP grants
   4. Tip a verified publisher

## Actual result: 
Tipped site and tip amount is not displayed under Tip panel

## Expected result:
Tipped site and tip amount should get displayed under Tips panel

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.74
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
I verified that. There is a section in `chrome://rewards` called Tips. We don't have the current tip and website in the list there. But we have the amount of tips in the panel, we don't show website name in the panel though. @ryanml could you take a look what is missed in HTML page. We do that call in the panel to retrieve that info `GetCurrentBalanceReport`, however I don't see it in brave_rewards_ui.

**Comment by ryanml** [comment]
@SergeyZhukovsky missing client side logic added here: https://github.com/brave/browser-android-tabs/commit/96d8224fceae8b07e414c55f3e90b3b24f28d6fd

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-19-56-52](https://user-images.githubusercontent.com/38657976/53497520-5972a080-3aca-11e9-9201-57f87fc54640.png)
