### ISSUE TITLE
Recurring monthly tip is not displayed under Tips Panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1025]
## Description 
Recurring monthly tip is not displayed under Tips Panel

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim grants
   4. Open a verified publisher and send recurring monthly tip for it

## Actual result: 
Recurring monthly tip is not displayed under Tips Panel

## Expected result:
Recurring monthly tip should be displayed under Tips Panel

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version:5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
It's the same problem as in that issue https://github.com/brave/browser-android-tabs/issues/1024

**Comment by ryanml** [comment]
Logic for this added here: https://github.com/brave/browser-android-tabs/commit/96d8224fceae8b07e414c55f3e90b3b24f28d6fd

cc: @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-19-56-52](https://user-images.githubusercontent.com/38657976/53497343-f719a000-3ac9-11e9-885b-09301790538b.png)
