### ISSUE TITLE
Incorrect sites count displayed in the Auto- Contribution notification message

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1026]
## Description 
Incorrect sites count displayed in the Auto- Contribution notification message
## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim UGP grants (Currently, we cannot claim grants. But, after clicking on BAT logo notification
      shows up 30 BAT total balance in wallet)
   4. Open a verified publisher and stay on site for min page time ( 8sec)
   5. Make sure site gets added to a-c table

## Actual result: 
1. After sometime auto contribution notification message is shown
2. Auto-contribution went through
3. Total wallet balance gone down 
4. Message says  `Contributed 20 BAT to 20 sites` which is wrong 

![screenshot_2019-01-23-17-16-48](https://user-images.githubusercontent.com/38657976/51604409-b8c11c00-1f32-11e9-8bb6-873d52904fa2.png)

## Expected result:
There was only one site added in a-c table for auto contribution. Auto contribution message needs to refined.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version:5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74
a-c table was showing 1 site.

![screenshot_20190124-020030_brave 1](https://user-images.githubusercontent.com/34715963/51647197-162d8b00-1f7c-11e9-958b-38267e59d0b7.jpg)

**Comment by SergeyZhukovsky** [comment]
The message has been changed in upstream sources. We don't show websites count anymore.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`


![screenshot_2019-02-27-20-17-26](https://user-images.githubusercontent.com/38657976/53590598-2575a900-3bb8-11e9-84f6-0790ff65ae14.png)
