### ISSUE TITLE
Auto-contribution is considering incorrect Monthly payment value.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1027]
## Description 
Auto-contribution is considering incorrect Monthly payment value.

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim UGP grants (Currently, we cannot claim grants. But, after clicking on BAT logo notification
    shows up 30 BAT total balance in wallet)
   4. Click on `View Details` in Auto contribution panel
   5. Verify `Monthly Payment` is displayed as `10.0 BAT`
   6. Open a verified publisher and stay on site for min time ( 8secs)

## Actual result: 
- After auto contribution, total wallet balance is `10.0 BAT` instead of `20.0 BAT`
- Auto contributed amount is 20 BAT instead on 10 BAT

UI:
![screenshot_2019-01-23-17-32-59](https://user-images.githubusercontent.com/38657976/51605361-ea3ae700-1f34-11e9-91f3-17caa9826d81.png)

Auto- contribution:

![screenshot_2019-01-23-17-16-48](https://user-images.githubusercontent.com/38657976/51605367-ee670480-1f34-11e9-985f-5e1dc2583f2b.png)

## Expected result:
Monthly Payment displayed in the auto contribution panel should be considered for auto-contribution

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version:5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by btlechowski** [comment]
I set 15 BAT and the contribution was made for 15 BAT.
After contribution I checked Monthly payment and it was shown 10 BAT.

Tested on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/commit/60817dc62380296ca89a0c947782aa74c9324c4a

cc: @anthonypkeane @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
![screenshot_2019-02-27-21-07-54](https://user-images.githubusercontent.com/38657976/53502326-d9513880-3ad3-11e9-8078-b55e2f75b3a3.png)
