### ISSUE TITLE
Unable to tip a site even though wallet has sufficient funds

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1028]
## Description 
Unable to tip a site even though wallet has sufficient funds

## Steps to Reproduce 

  1. Clean profile 1.0.74
  2. Enable Rewards
  3. Claim UGP grants (Currently, we cannot claim grants. But, after clicking on BAT logo notification
    shows up 30 BAT total balance in wallet)
  4. Add a verified publisher to a-c table ( I have added DDG)
  5. Wait for auto-contribution ( after auto-contribution, my wallet balance was 10 BAT)
  6. After auto contribution, Tip DDG  ( I have tipped 5 BAT)
  7. Open a DDG and tip 5BAT ( DDG site is kept open in step 4, same site is used for tipping in step 6 
     and 7)

## Actual result: 
Getting message as not enough funds

![screenshot_2019-01-23-17-49-44](https://user-images.githubusercontent.com/38657976/51606735-b5309380-1f38-11e9-90a2-bb7ca262a2e8.png)

## Expected result:
It should allow to tip 5 BAT as wallet balance is 5 BAT

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/5400f4505a4b53e35021d6ded9c0baebf59d7840

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
