### ISSUE TITLE
BR panel doesn't show 'SEND A TIP` option always.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1029]
## Description 
BR panel doesn't show 'SEND A TIP` option for sites, need to open BR panel multiple times inorder to tip a site.

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim UGP grants (Currently, we cannot claim grants. But, after clicking on BAT logo notification
    shows up 30 BAT total balance in wallet)
   4. Open a site and click on BR panel

## Actual result: 
BR panel shows up the Rewards Summary, It doesn't show `SEND A TIP` option even after multiple page reload.

## Expected result:
`SEND A TIP` option should be shown in BR panel always.

## Issue reproduces how often: 
Intermittent issue

## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya do you have any website example for that?

**Comment by GeetaSarvadnya** [comment]
@SergeyZhukovsky @gdregalo : I am able to reproduce the issue in one instace, where i have DDG site opened and i have sent tips (1 BAT, 5 BAT) to it. After sending tips, if i click on BR Panel (BAT logo) for DDG, I am seeing summary page, it doesn't shows up `Send a Tip` option untill i reload the DDG page.

Recorded file is uploaded here.
https://drive.google.com/open?id=1ptcGjEGokRB0qCfp72Rwb9GejXzZ99tv

**Comment by SergeyZhukovsky** [comment]
That is fixed here https://github.com/brave/browser-android-tabs/commit/1c1b4316328323a0819e6995d3672f9f2e4f5321
