### ISSUE TITLE
Recurring monthly tip is not shown in Rewards summary

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1030]
## Description 
Recurring monthly tip is not shown in Rewards summary

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim UGP grants (Currently, we cannot claim grants. But, after clicking on BAT logo notification
    shows up 30 BAT total balance in wallet)
   4. Open a verified publisher 
   5. Send a monthly recurring tip 5 BAT
   6. Open Rewards summary

## Actual result: 
Recurring tip is not shown in Rewards Summary

## Expected result:
Recurring tip should be shown in Rewards Summary

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya did it appear in a minute or so? Their is a random delay on tipping from 1 to 60 seconds. I cannot reproduce that.

**Comment by SergeyZhukovsky** [comment]
Sorry @GeetaSarvadnya  I checked not a recurring tip. However when I did with a monthly tip, I saw that we process recurring tips on a contribution date, and they appear in the summary after that.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-20-17-45](https://user-images.githubusercontent.com/38657976/53498828-2251be80-3acd-11e9-821d-b7bbf8be9cdc.png)
