### ISSUE TITLE
Auto-Contribution is successful even though Rewards is off

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1031]
## Description 
Auto-Contribution is successful even though Rewards is off

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim grants (Click on notification on BAT logo shows up 30 BAT in wallet)
   4. Verify `Monthly Payment` is displayed as 10 BAT
   5. Add a verified publisher to a-c table
   6. Turn off the Rewards 

## Actual result: 
After sometimes, auto contribution went through. Wallet balance gone down and a-c table is cleared.

## Expected result:
If we turn off the rewards during auto-contribution, contribution should not go through

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?Yes

## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version:
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
@SergeyZhukovsky I fixed this one upstream, added label

**Comment by SergeyZhukovsky** [comment]
Thanks @ryanml! I checked it and we don't do contributions currently when the switch is off.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
