### ISSUE TITLE
For non verified pubs Reserved BAT message is not shown in Rewards summary

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1035]
## Description 
For non verified pubs Reserved BAT message is not shown in Rewards summary

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewrads
   3.  Claim grants
   4.  Add few non verified pubs to a-c table
   5. Wait for auto-contribution

## Actual result: 
Auto-contribution is successful. Total a-c balance gone down. There is no reserved BAT message displayed in Rewards summary.

## Expected result:
Should be same as desktop.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/a2fc4fde6d772a101de349dbd7dd6fe47bb02ce3

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-11-52-29](https://user-images.githubusercontent.com/38657976/53496858-ec124000-3ac8-11e9-83fb-29625711adc9.png)
