### ISSUE TITLE
Tipping non-verified pubs go through and wallet balance reduces

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1036]
## Description 
Tipping non-verified pubs go through and wallet balance reduces

## Steps to Reproduce 

   1. Clean profile 1.0.74
   2. Enable Rewards
   3. Claim grants
   4. Tip non verified pubs

## Actual result: 
Tipping non-verified pubs go through and wallet balance reduces

## Expected result:
Should be same as desktop

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsumg Galaxy J3
   - Android Version: 5.1
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
Fixed in upstream changes.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
