### ISSUE TITLE
AC list is not populated on first time when `chrome://rewards` page is opened

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#1039]
A user can browse a lot before she decided to look into  AC list in `chrome://rewards` page.
The AC list is not populated on first time it is opened. The browsing history is properly stored in `publisher_info_db` though. So that the AC list is loaded, a user has to open it second time.

## Steps to Reproduce 

   1. 
   2. 
   3. 

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version:
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
@gdregalo fixed via: https://github.com/brave/browser-android-tabs/commit/99edd5ed5d86ef11b86cf6edb676e0d8ede670f9
