### ISSUE TITLE
Sync: devices are duplicated when app is swiped out from carousel

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#1042]
## Description 
Devices are duplicated in sync chain list when app is swiped out from application carousel.

## Steps to Reproduce 

   1. Get clean profile on brave-core
   2. Create sync chain on brave-core
   3. Connect Android device to the sync chain with QR
   4. Wait for sync chain established
   (pt 5-6 are just to show the normal flow)
   5. Exit browser with back button
   6. Launch browser again and then App menu->Settings->Sync
   7. Exit browser by swiping out from the application carousel
   8. Launch browser again then App menu->Settings->Sync, and wait for device list to load

## Actual result: 
   9. Current device will be duplicated. The screenshot is below.

## Expected result:
   9. No duplicated devices

## Issue reproduces how often: 
Easily

## Issue happens on: 
   - Current Playstore version? No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1.2 
   
## Brave version:
1.0.72(sync1)

### Additional Information

![screenshot_20190125-011937](https://user-images.githubusercontent.com/24739341/51715440-615da180-2041-11e9-8528-52c907c86d0c.png)

**Comment by kjozwiak** [comment]
Went through the test case outlined under https://github.com/brave/browser-android-tabs/issues/1042#issue-402942913 several times and couldn't reproduce the issue using `1.0.82, CR: 72.0.3626.105`.
