### ISSUE TITLE
[Intermittent Issue] Incorrect favicons shown in BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1048]
## Description 
Incorrect favicons shown in BR panel

## Steps to Reproduce 

   1. Enable rewards
   2. Visit google.com and keep that as active tab
   3. Remove app from memory and relaunch and open BR panel, might show incorrect favicon

Note: Steps may not be accurate. I encountered issue with that but there might be some specific steps missing there

## Actual result: 
![screenshot_20190128-124556](https://user-images.githubusercontent.com/17010094/51820176-ee7f4f80-22fa-11e9-8eb1-be0faf9511f9.png)

## Expected result:
Should show correct favicon

## Issue reproduces how often: 
Intermittent issue. Seen this for the first time. So steps might be accurate

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Assigned @gdregalo as this is a panel issue cc: @srirambv

**Comment by gdregalo** [comment]
Fixed in:
https://github.com/brave/browser-android-tabs/commit/23175f66aed1bd9fed68b5e8746d10555247b0b0
