### ISSUE TITLE
Claim grant notification shows 0BAT but wallet updates with grant value

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1049]
## Description 
Claim grant notification shows 0BAT but wallet updates with grant value 

## Steps to Reproduce 

   1. Clean install rewards build
   2. Enable rewards from BR panel
   3. Open rewards settings via BR panel
   4. Claim grant, notification shows 0BAT, close notification and wait for 2 secs wallet updates to 30BAT

## Actual result: 
Claim grant notification shows 0BAT but wallet updates with grant  value

## Expected result:
Grant notification should show the grant value as well

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
![screenshot_20190204-114206](https://user-images.githubusercontent.com/12011303/52222686-1843f380-2872-11e9-9bc2-72800c27bc36.png)
@ryanml it is on that screen ^ inside settings. There is a delay of couple seconds till the grants appear. It's expected as there is a network call. Could we do a kind of endless spinner there till the grant appears or what else could be done @srirambv ?

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/9983768dea04fe5b70f8653e58821e395147b359

cc: @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-03-01-01-34-31](https://user-images.githubusercontent.com/38657976/53595022-34f9ef80-3bc2-11e9-854a-1e3504d423b2.png)
