### ISSUE TITLE
Hide BR UI for failed SafetyNet Check

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1062]
If a users device fails the SafetyNet check, we should hide certain parts of the BR UI.

The areas to be hidden are: (any area where a user can earn BAT)

Grants
Ads

Full spec TDB

**Comment by jamesmudgett** [comment]
@anthonypkeane What do you think about this: disable Brave Rewards and hide icon in address bar?

**Comment by anthonypkeane** [comment]
Confirmed @jamesmudgett 

Hide the Brave Rewards icon in the address bar
Hide the Brave Rewards menu item

**Comment by srirambv** [comment]
@aekeus can this be closed as beta1 is out or is it still being worked on for beta 2 release?

**Comment by anthonypkeane** [comment]
Note: I will create a spec for this

**Comment by anthonypkeane** [comment]
Spec: https://docs.google.com/document/d/1sBWHtB4F3zT5YTJBvYmtupSDKOKHq4UWkxxCcW76100/edit

**Comment by btlechowski** [comment]
This feature fails. I reported a follow up issue: https://github.com/brave/browser-android-tabs/issues/1455.
