### ISSUE TITLE
Device is listed twice after closing Brave during sync chain creation

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#1065]
Follow up from https://github.com/brave/browser-android-tabs/issues/854

## Steps to Reproduce 

   1. Start `Start a new sync chain` on Android device
   2. Set a name for the device
   3. Tap `Add a Computer`
4. Copy the code words
5. Force close Brave
6. Sync a Desktop device using the codes from 4.
7. Open Brave on Android device
8. Check Sync

## Actual result: 
The android device is listed twice.

![image](https://user-images.githubusercontent.com/34715963/52017993-49769980-24e9-11e9-9e77-41d97f09a49f.png)

Note: On desktop the sync list is OK.

## Expected result:
The android device is listed once.

## Issue reproduces how often: 
Easily reproduced

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung s7
   - Android Version: 8..0.0
   
## Brave version:
1.0.75

cc @brave/legacy_qa @samartnik

**Comment by srirambv** [comment]
I think there is a delay in removing the device from sync chain. While verifying #864 encountered this issue. But removing the app from memory a second time and loading sync shows its reset. So this might not be an issue but just a delay in removing the device from chain.

cc: @AlexeyBarabash @darkdh

**Comment by AlexeyBarabash** [comment]
This is quire similar to  https://github.com/brave/browser-android-tabs/issues/1042 .
For now I know that last_fetch_time is not saved right after initial fetch, so after force close and restart the browser acts like on the first fetch: sends add itself with a new object_id, which causes duplication in devices list and resends all bookmarks.

**Comment by srirambv** [comment]
I was able to reproduce this issue with the following steps
1. Create sync chain on device 1 (Pixel 3XL)
2. Join device 2(Samsung tab) using QR code
3. Leave sync chain on device 2 by remove this device 
4. Leave sync chain on device 1 by remove this device
5. Create a new sync chain on device 2, scan device 1 to join sync chain
6. Device 2 lists the name of the device twice as this device, device 1 also shows device 2 name twice

Device 1:![screenshot_20190212-162400](https://user-images.githubusercontent.com/17010094/52630888-68126280-2ee3-11e9-9977-8cde43d58373.png)
Device 2:![screenshot_20190212-055830_brave](https://user-images.githubusercontent.com/17010094/52630866-5df06400-2ee3-11e9-801a-3490913e9f45.jpg)

**Comment by kjozwiak** [comment]
Went through both https://github.com/brave/browser-android-tabs/issues/1065#issue-405000192 and https://github.com/brave/browser-android-tabs/issues/1065#issuecomment-462715441 several times and couldn't reproduce the issue using `1.0.82, CR: 72.0.3626.105`.
