### ISSUE TITLE
Sync: crash when switching languages

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#1069]
## Description 
Brave browser crashes when sync is enabled and do switching of languages in Android system settings.

## Steps to Reproduce 

   1. Connect browser to the sync chain. I used brave-core as the first device, but it should not be a matter.  Wait for sync to complete.
   2. Go to the system settings => Languages , switch to another language.
   3. Switch to Brave browser.

## Actual result: 
   4. Once it had crashed.

## Expected result:
   4. Should not be crash.

## Issue reproduces how often: 
I have seen it once. Done several attempts to reproduce, but without luck.

## Issue happens on: 
   - Current Playstore version? no 
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): phone
   - Android Version: 7.1.2
   
## Brave version:
1.0.76

### Additional Information

Fortunately I had Android Device Monitor Attached and could get stack:
```
01-31 19:18:06.164: A/chromium(25919): [FATAL:thread_restrictions.cc(32)] Check failed: !g_blocking_disallowed.Get().Get(). Function marked as blocking was called from a scope that disallows blocking! If this task is running inside the TaskScheduler, it needs to have MayBlock() in its TaskTraits. Otherwise, consider making this blocking work asynchronous or, as a last resort, you may use ScopedAllowBlocking (see its documentation for best practices).

Stack Trace:
  RELADDR   FUNCTION
  03169bbf  logging::LogMessage::~LogMessage()
  031a9339  base::AssertBlockingAllowed()
  031a6b3b  base::ScopedBlockingCall::ScopedBlockingCall(base::BlockingType)
  031c019f  base::File::Close()
  03161ddd  base::File::~File()
  03b0d4ab  leveldb_env::(anonymous namespace)::ChromiumFileLock::~ChromiumFileLock()
  03b0d4c1  leveldb_env::(anonymous namespace)::ChromiumFileLock::~ChromiumFileLock()
  v------>  std::__ndk1::default_delete<leveldb_env::(anonymous namespace)::ChromiumFileLock>::operator()(leveldb_env::(anonymous namespace)::ChromiumFileLock*) const
  v------>  std::__ndk1::unique_ptr<leveldb_env::(anonymous namespace)::ChromiumFileLock, std::__ndk1::default_delete<leveldb_env::(anonymous namespace)::ChromiumFileLock> >::reset(leveldb_env::(anonymous
  v------>  std::__ndk1::unique_ptr<leveldb_env::(anonymous namespace)::ChromiumFileLock, std::__ndk1::default_delete<leveldb_env::(anonymous namespace)::ChromiumFileLock> >::~unique_ptr()
  03b0bceb  leveldb_env::ChromiumEnv::UnlockFile(leveldb::FileLock*)
  03b0ef87  leveldb::DBImpl::~DBImpl()
  03b0f089  leveldb::DBImpl::~DBImpl()
  v------>  brave_sync_storage::JNI_BraveSyncWorker_Clear(_JNIEnv*, base::android::JavaParamRef<_jobject*> const&)
  02f84aad  Java_org_chromium_chrome_browser_BraveSyncWorker_nativeClear
```
in some condition file operation of close level_db happens in a not-permitted thread.

**Comment by samartnik** [comment]
Fixed here https://github.com/brave/browser-android-tabs/commit/ef9068bea43a92df180c8bdde43550c36a72b32e
