### ISSUE TITLE
Desktop is not removed from sync chain , when sync is reset on sync chain creator device

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1071]
## Description 
Desktop is not removed from sync chain , when sync is reset on sync chain creator device

##Devices
Device1: Desktop windows 10 (Brave 0.59.34) - Sync chain creator
Device2: Linux Mint (VM) Brave 0.59.34
Device3: Android Samsung Galaxy J3 - 1.0.76

## Steps to Reproduce 

   1. Setup sync chain between Windows and Linux
   2. Open QR code on windows and add Android to sync chain by scanning QR code
   3. Make sure all the three devices are in sync chain
   4. Delete sync chain creator windows10 from windows 10 machine/device
   5. Verify that winowds 10 is removed from sync chain on Linux mint
   6. Verify that windows 10 is NOT removed from android

## Actual result: 
Windows 10 is not removed from sync chain on Android ( able to see all the three devices on sync chain).

Waited for almost 16 minutes

## Expected result:
Windows 10 should be removed from sync chain on android

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? na
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.76

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa @AlexeyBarabash

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you reproduce this every single time or is this intermittent? I tried reproducing the above five times but couldn't reproduce the issue. I went through the following:

* started a sync chain on Win 10 x64 (using `0.60.26 Chromium: 72.0.3626.96`)
* added a Mint 19.1 x64 VM desktop to the sync chain (using `0.60.26 Chromium: 72.0.3626.96`)
* added a Pixel XL (using `1.0.80 CR: 72.0.3626.96`)

Once all three devices appeared under the device section under `brave://settings`, I did the following:

* removed the Win 10 x64 machine via `Leave Sync Chain` under `brave://settings`
* removed the Win 10 x64 machine via the `X` on the Win 10 x64 machine
* removed the Win 10 x64 machine using Mint 19.1 x64
* removed the Win 10 x64 machine using the Pixel XL

Every time I removed the Win 10 x64 machine, the device list was correctly updated. @GeetaSarvadnya if you can't reproduce this again, let's label it as `Intermittent` for now and see if anyone else runs into the above.

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Looks like issue is fixed. I am not able to reproduce the issue now.

**Comment by kjozwiak** [comment]
Thanks for double checking @GeetaSarvadnya 👍
