### ISSUE TITLE
Long press not working, open in new tab not working

### ISSUE THREAD

**Issue by BlackRabbit22** [brave/browser-android-tabs#1082]
When long pressing on an image or file, the option for saving the file or image doesn't appear.

When long pressing on a hyperlink, it doesn't display "open in new tab". It only displays copy link/copy text.

**Comment by srirambv** [comment]
Context menu open in new tab is fixed as part of #1074. Should be available in the next build. 

Closing the issue for now. Lets reopen if the issue still persist for images in the new build

**Comment by simonsmith** [comment]
Which build should we see the fix applied? It's still present for me in 1.0.77
