### ISSUE TITLE
Rewards panel content message is not same as Brave core

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1089]
## Description 
Rewards panel content message is not same as Brave core

## Steps to Reproduce 

   1. 
   2. 
   3. 

## Actual result: 
![screenshot_2019-02-08-15-18-41](https://user-images.githubusercontent.com/38657976/52471113-15206e80-2bb6-11e9-80a3-729b2b1a36b3.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/52471132-21a4c700-2bb6-11e9-88af-292cecccb10e.png)

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett @anthonypkeane what should we use?

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-21-59-57](https://user-images.githubusercontent.com/38657976/53429120-03422680-3a12-11e9-8685-b0ca263f3fe0.png)
