### ISSUE TITLE
Back arrow is not aligned with `Auto-Contribute` and `Tips` panels texts

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1090]
## Description 
Back arrow is not aligned with `Auto-Contribute` and `Tips` panels texts

## Steps to Reproduce 

   1. Open Brave 1.0.78
   2. Enable Rewards
   3. Click on `View Details` for Auto-Contribute and Tips panels

## Actual result: 
![image](https://user-images.githubusercontent.com/38657976/52471867-ec997400-2bb7-11e9-979c-a4e3b0744ff9.png)
![image](https://user-images.githubusercontent.com/38657976/52471899-05098e80-2bb8-11e9-81bd-099c45c0bac9.png)

## Expected result:
Back arrow should be aligned with text

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/08353cd068335b537ae3345cadcd27cc16b4cb01

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-21-53-12](https://user-images.githubusercontent.com/38657976/53428568-08eb3c80-3a11-11e9-95bb-4626d2d6e0d2.png)
![screenshot_2019-02-26-21-53-18](https://user-images.githubusercontent.com/38657976/53428569-08eb3c80-3a11-11e9-8ccc-a8ca526fdddf.png)
