### ISSUE TITLE
Translations missing and instead placeholder text is shown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1091]
## Description 
Translations missing and instead placeholder text is shown

## Steps to Reproduce 

   1. Open brave 1.0.78
   2. Enable Rewards
   3. Accept the grants, click on your wallet
   4. Observe UI issues

## Actual result: 
1. `Missing` placeholder is shown
2. `tokenGrantClaimed ` is displayed instead of  `Token Grants Claimed`- there is no space between texts and also `s` is missing after Grant, `t` should be caps
3. 30.0 BAT is not alinged with `Token Grants Claimed`

![screenshot_2019-02-08-15-48-16](https://user-images.githubusercontent.com/38657976/52474478-9aa81c80-2bbe-11e9-9b66-54d998c5ce5f.png)

## Expected result:
same as desktop

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
We have this translation in brave-core, so maybe just need a resync

**Comment by SergeyZhukovsky** [comment]
yup, I'm going to work on that next week.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-20-26-22](https://user-images.githubusercontent.com/38657976/53499307-15819a80-3ace-11e9-9a18-6345177cc78d.png)
