### ISSUE TITLE
Insufficient funds notification is shown as soon as we enable rewards on clean install

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1092]
## Description 
Insufficient funds notification is shown as soon as we enable rewards on clean install

## Steps to Reproduce 

   1. Clean install 1.0.78
   2. Click on `JOIN REWARDS`
   3. Insufficient funds notification is shown

## Actual result: 
Insufficient funds notification is shown on each clean install
![screenshot_2019-02-08-17-00-12](https://user-images.githubusercontent.com/38657976/52475951-1e640800-2bc3-11e9-9bc4-d3efa8fe794f.png)

## Expected result:
Insufficient funds notification should not be shown as soon as we enable rewards on clean install

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet):Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.78
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
@NejcZdovc how does it work on desktop? We have it right away after enabling rewards first time. Do you disable it very first time?

**Comment by NejcZdovc** [comment]
we show this notification 3 days before your reconcile date is up and you don't enough funds for it

**Comment by NejcZdovc** [comment]
https://github.com/brave/brave-browser/issues/1479

**Comment by NejcZdovc** [comment]
this is expected, because afaik you hardcode 10min reconcile interval for testing purposes. And because that is 3 days or less we show this notification. Same things happens on desktop.

**Comment by SergeyZhukovsky** [comment]
Closing it as not an issue. I verified that we don't have it if contribution date is set on default value.
