### ISSUE TITLE
min page time and visit settings are missing from `Auto-Contribution` panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1093]
## Description 
min page time and visit settings are missing from `Auto-Contribution` panel

## Steps to Reproduce 

   1. Clean install 1.0.78
   2.  Enable rewards
   3. Click on `View Details` in Auto-Contribution panel
   4. Click on `Settings` under view details section

## Actual result: 
1. min page time and visit settings are missing from `Auto-Contribution` panel
2. what should be allowed check boxes are also missing

![screenshot_2019-02-08-18-06-24](https://user-images.githubusercontent.com/38657976/52478907-e3ff6880-2bcc-11e9-9daf-a1ee5df07f8f.png)

## Expected result:
min page time and visit settings should be displayed
![screenshot_2019-02-08-18-04-59](https://user-images.githubusercontent.com/38657976/52478895-dc3fc400-2bcc-11e9-9ece-069016b71400.png)

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM 
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version:
   
## Brave version:

1.0.78
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
@GeetaSarvadnya can you post a screenshot of this?

**Comment by GeetaSarvadnya** [comment]
@ryanml Here is the screen shot - Auto- Contribution settings missing in 1.0.78
![screenshot_2019-02-08-18-06-24](https://user-images.githubusercontent.com/38657976/52478832-8c60fd00-2bcc-11e9-8364-4948c77d3371.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/08353cd068335b537ae3345cadcd27cc16b4cb01

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-21-45-22](https://user-images.githubusercontent.com/38657976/53427926-d4c34c00-3a0f-11e9-899e-7418ddb64edf.png)
