### ISSUE TITLE
content message cuts off the screen when we expand Auto-Contribution and Tips panels

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1094]
## Description 
content message cuts off the screen when we expand Auto-Contribution and Tips panels

## Steps to Reproduce 

   1. Clean install 1.0.78
   2. Enable Rewards
   3. Click on `View Details` for Tips and Auto-Contribution panel
   4. Verify that the content message is not displayed completely, even after scroll up/down the content is not shown completely

## Actual result: 
![image](https://user-images.githubusercontent.com/38657976/52479470-badfd780-2bce-11e9-9b4a-9328ba94506b.png)

![image](https://user-images.githubusercontent.com/38657976/52479422-8ec45680-2bce-11e9-9398-6d49264b0f7e.png)

## Expected result:
Content message should be displayed completely.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version:
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by srirambv** [comment]
Not reproducible on Pixel 3xl. Issue on smaller screen size only.

**Comment by ryanml** [comment]
Thanks guys, will be fixed with: https://github.com/brave/brave-ui/pull/371

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/08353cd068335b537ae3345cadcd27cc16b4cb01

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
