### ISSUE TITLE
Alignmnet issue in Rewards Summary

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1095]
## Description 
Alignmnet issue in Rewards Summary

## Steps to Reproduce 

   1. Clean install `1.0.78`
   2. Enable Rewards
   3.  Claim grants
   4. Add few sites to a-c table ( verified + non verified)
   5. Tip a verified pubs
   6. Send a recurring monthly tip to a pubs
   7. Wait for auto-contribution
   

## Actual result: 
Auto cotribution, Monthly recurring tip, One time tip amount is not aligned in Rewards summary

![image](https://user-images.githubusercontent.com/38657976/52480361-799cf700-2bd1-11e9-8dd4-a173edff270b.png)

## Expected result:
Auto cotribution, Monthly recurring tip and Tip amount shoulb be aligned

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by srirambv** [comment]
Not an issue on pixel 3xl. Issue with smaller screensize

**Comment by thanuj10** [comment]
Yes, Phone specific as it is not repo on Nokia 6.1 Plus (19:9, 2280x1080) Screen Resolution,

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/ffa6ce86d27d42313ff017acc0d07fa631355841

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
