### ISSUE TITLE
Can't remove monthly recurring tip from Tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1097]
## Description 

Can't remove monthly recurring tip from Tips panel
## Steps to Reproduce 

   1. Clean profile 1.0.78
   2. Enable rewards and claim grants
   3. Send a recurring tip to verified pubs
   4. Verify that recuring monthly tip got added in Tips panel
   5. Remove recurring tip from Tips panel

## Actual result: 
Can't remove monthly recurring tip

## Expected result:
Should be able to remove monthly recurring tip

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.78
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/bfe43aee792b12ec1d46cac6f6272ccf01cc6e9b

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
