### ISSUE TITLE
`Monthly Payment` USD conversion name is missing in Auto-Contribution Settings->`Settings` page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1098]
## Description 

Follow up of #1017 

`Monthly Payment` USD conversion name is missing in Auto-Contribution Settings->`Settings` page

## Steps to Reproduce 

   1. Clean profile 1.0.78
   2. Enable Rewards
   3. Click on `View Details` in auto-contribution panel
   4. Click on `Settings`
   5. Verify USD conversion name

## Actual result: 

Pixel 3xl - `Auto-Contribution Settings`->`Settings` page
![screenshot_20190208-190620](https://user-images.githubusercontent.com/38657976/52483238-55451880-2bd9-11e9-8488-12bb6d6c7416.png)

Samsung Galaxy J3 - 5.1 - `Auto-Contribution Settings`->`Settings` page

![image](https://user-images.githubusercontent.com/38657976/52482882-71948580-2bd8-11e9-98bf-d14299545866.png)

## Expected result:
USD should be shown completely

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/08353cd068335b537ae3345cadcd27cc16b4cb01

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-21-14-29](https://user-images.githubusercontent.com/38657976/53425751-9d52a080-3a0b-11e9-8872-91e84c678ec7.png)
