### ISSUE TITLE
Rewards summary cuts off the screen, reserved BAT message is not displayed in rewards summary

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1099]
## Description 
Rewards summary cuts off the screen, reserved BAT message is not displayed in rewards summary

## Steps to Reproduce 

1. Clean install 1.0.78
2. Enable REwards and claim the grants
3. Add few sites to a-c table (verified + non verified)
4. Send a tip to verified pubs ( for my test i have tipped 1 BAT)
5. Send a tip to non verified pubs
6.  Send a monthly recurring tip to verified pubs ( for my test i have tipped 10 BAT)
7. Wait for Auto -Contribution
8. Click on Your wallet in Rewards page

## Actual result: 
Rewards summary cuts off the screen, reserved BAT message is not shown. scoll up/down doesn't help

![screenshot_2019-02-08-18-00-29](https://user-images.githubusercontent.com/38657976/52498937-327a2a80-2c00-11e9-9ef7-712e7b02fd61.png)

## Expected result:
Reserved BAT message should be shown in Rewards summary popup

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/a619d79ce950c2a0703680f920320e9f1bb59bc5

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-11-28-25](https://user-images.githubusercontent.com/38657976/53423455-61b5d780-3a07-11e9-837e-d12e5bb20553.png)

- Logged an alignment issue for rewards summary #1193
