### ISSUE TITLE
Alignment issues in Tips settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1100]
## Description 
Alignment issues in Tips settings page

## Steps to Reproduce 

   1.  Clean profile 1.0.78
   2.  Enable rewards and claim grants
   3.  Send a tip to a verified pubs
   4. Send a monthly recurring tip to a verified pubs
   5. Click on `View Details` in Tips panel
   6. Click on `Settings` in view details section

## Actual result: 

![screenshot_2019-02-08-20-03-03](https://user-images.githubusercontent.com/38657976/52500202-6e62bf00-2c03-11e9-8055-98c8e035f40b.png)

## Expected result:
 
text and other details should be aligned properly

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.78

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
This one will be fixed along with: https://github.com/brave/browser-android-tabs/issues/1093

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/08353cd068335b537ae3345cadcd27cc16b4cb01
