### ISSUE TITLE
CR upgrade shows Google Assistant options in settings 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1109]
## Description 
CR upgrade shows Google Assistant options in settings 

## Steps to Reproduce 

   1. Install/upgrade to 1.0.79
   2. Open settings page
   3. Shows `Google Assistant in Brave` option which needs to be removed

## Actual result: 
![screenshot_20190211-163246](https://user-images.githubusercontent.com/17010094/52559382-261de980-2e1b-11e9-8c2b-2102246656a8.png)

## Expected result:
No unnecessary options should be shown on the UI

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? 
No
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9
   
## Brave version:
1.0.79

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel XL` using `1.0.80 CR: 72.0.3626.96`. I don't see the `Google Assistant in Brave` menu under settings anymore. Example:

![screenshot_20190211-202451](https://user-images.githubusercontent.com/2602313/52605112-75741200-2e3b-11e9-8ecb-91d06dc22237.png)
