### ISSUE TITLE
Clean up Default search engines settings

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#1115]
Description is inside desktop browser repo https://github.com/brave/brave-browser/issues/3316

**Comment by AlexeyBarabash** [comment]
@samartnik 
Also need to check the situation when user before update was with the search engine removed after update. The user should still have the old search engine. cc @kjozwiak

**Comment by samartnik** [comment]
QA steps:

1.1 Install new version, there should be predefined set of search engines in settings.

2.1 Install old version.
2.2 Set some standard search engine other than predefined.
2.3 Install new version.
2.4 Make sure that there are predefined set of search engines + selected in the old version.
2.5 Repeat tests with private search engine and both.

**Comment by srirambv** [comment]
Verification passed on Samsung tab.
* Verified clean install only has default search engines for Canada, Russia
* Verified search engine not part of default list is retained for both normal and private tabs post upgrade
* Verified search engine list reduced to default list on upgrade, when default was set on previous version
