### ISSUE TITLE
usually Brave crashes when selecting 'Open in Brave' from custom tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1119]
## Description 
I'm seeing a fairly consistent crash when selecting 'Open in Brave' from a custom tab. 

## Steps to Reproduce 

   1. Clean install of 1.0.80RC2 or upgrade to 1.0.80RC2 from 1.0.77.
   2. Close Brave.
   3. Open Slack app.
   4. Go to a channel with a lot of links.
   5. Tap on a link. Link opens in Custom tab.
   6. Tap on 3 dots.
   7. Select Open in Brave.

## Actual result: 
Usually get a message that 'Unfortunately Brave has stopped'

## Expected result:
Link opens in Brave.

## Issue reproduces how often: 
Fairly easily after tapping on this link in slack:
https://github.com/brave/browser-android-tabs/labels/feature%2FBR
But it was seen with other links as well. 

## Issue happens on: 
   - Current Playstore version? no, current play store version 1.0.77 is missing this option.
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): I experienced on x86, @srirambv saw on ARM
   - Device(Phone, Tablet, Phablet): phone
   - Android Version: x86 has 6.0
   
## Brave version:
1.0.80(RC2)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
On ARM it usually doesn't crash when opening via custom links. But once it crashes its pretty intermittent crashing going forward.

**Comment by samartnik** [comment]
Issue related to sync instance being stopped in CustomTabActivity and tried to be used in ChromeTabActivity after that
https://github.com/brave/browser-android-tabs/commit/2e1e386d43903db76967797bf90fc3a4bf5b2d92

**Comment by srirambv** [comment]
Still not fixed. Can consistently reproduce with the following steps
1. Install 1.0.77
2. Enable Sync on the device
3. Upgrade to 1.0.80
4. Check sync is enabled or not
5. Open link from slack, opens in custom tab
6. Open in brave, browser crashes after a couple of seconds

**Comment by srirambv** [comment]
Able to reproduce the issue on clean install of 1.0.80 (RC3) as well. 
1. Clean install 1.0.80 (RC3)
2. Start sync chain, add device name, tap on mobile/computer
3. Navigate back before the code words/qr code shows up
4. Loading devices is shown, go out of sync screen
5. Open Slack and open a link in custom tab
6. Open in Brave from hamburger menu, wait for 2 seconds, browser crashes
7. Relaunch Brave and open sync, This device shows up twice
8. Tab opened in step 6 is lost so browser launches with a new tab

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/8cdf75a9cd158ef09eceeb5218d29d7abf2ed815

**Comment by LaurenWags** [comment]
Tested the following on x86: 
Scenario 1
enable sync on 1.0.77
upgrade to 1.0.80 rc4
open link in custom tab from slack
open in browser, no crash (tried several links)
quick check of sync - verified able to send/receive bookmarks
- ran this scenario 2x
Scenario 2
install 1.0.80
open link in custom tab from slack
open in browser, no crash (tried several links)
enable sync
quick check of sync - verified able to send/receive bookmarks
open link in custom tab from slack
open in browser, no crash (tried several links)
- ran this scenario 2x

**Comment by srirambv** [comment]
Forgot to add verification notes. Basically checked the same [test scenarios ](https://github.com/brave/browser-android-tabs/issues/1119#issuecomment-464076336)on ARM as well
