### ISSUE TITLE
\Enter a Sync Chain Code\ instead of "Enter a Sync Chain Code" on code words screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1120]
## Description 
\Enter a Sync Chain Code\ instead of "Enter a Sync Chain Code" on code words screen

## Actual result: 
![screenshot_20190214-101417](https://user-images.githubusercontent.com/17010094/52764262-4d57ff00-3045-11e9-98fc-e23a8ef65702.png)

## Expected result:
Playstore build (1.0.77)
![screenshot_20190214-103700](https://user-images.githubusercontent.com/17010094/52764260-4a5d0e80-3045-11e9-87a1-212c2fa51a30.png)

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone 
   - Android Version:9
   
## Brave version:
1.0.80 (RC3) build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Minor UI issue so not blocking on 1.0.80

**Comment by jtj9817** [comment]
Mind if I take a look of this Issue?

**Comment by samartnik** [comment]
@jtj9817 even though it is problem only on en-GB localization, it requires revising of our translation process. So I would rather do it myself.

**Comment by btlechowski** [comment]
Verification passed on Samsung s7 (ARM), Brave v1.0.84-rc.2.

Tested on locales: en-GB, en-US, PL.
en-GB:
![screenshot_20190304-223320_brave](https://user-images.githubusercontent.com/34715963/53764532-e1431b00-3ecd-11e9-84de-eb802f82dfd8.jpg)
