### ISSUE TITLE
 Shouldn't be toggable

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1123]
When you are on system page (when we don't display publisher info) we shouldn't display summary toggle.

![screenshot_20190219-082931](https://user-images.githubusercontent.com/9574457/52997999-66d0c080-3422-11e9-81a7-6b7ade6b0ced.png)

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/05b83f2126600d19507a8d20f68ac75a1e39ebd5

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on 1.0.83

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya could you please paste an image? I cannot replicate it. Are you sure that you tried it while you are on settings page?
