### ISSUE TITLE
We should display disabled state when rewards are off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1124]
Android when rewards are disabled
![screenshot_20190219-082915](https://user-images.githubusercontent.com/9574457/52997926-2a04c980-3422-11e9-9c7e-3dbe0ead9abf.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52997955-44d73e00-3422-11e9-9c21-b596338b8af6.png)

**Comment by SergeyZhukovsky** [comment]
We haven't implemented that yet. But that how it should be following a design layout we have for Android
<img width="364" alt="screen shot 2019-02-19 at 3 26 07 pm" src="https://user-images.githubusercontent.com/12011303/53045144-dfec0a00-345a-11e9-98e0-217bb5256c9f.png">
@jamesmudgett @anthonypkeane please comment which one is correct.

**Comment by NejcZdovc** [comment]
cc @jenn-rhim as well

**Comment by jamesmudgett** [comment]
Correct

**Comment by anthonypkeane** [comment]
If rewards are disabled we should show the welcome screen 
_-> confirmed on Slack with Jenn and James_

**Comment by NejcZdovc** [comment]
@anthonypkeane what do you mean welcome screen? Can you paste screen of it please?

**Comment by SergeyZhukovsky** [comment]
@NejcZdovc the one that I posted above

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/b6f74804598dcd1401bde3959e505e70b67fc0d3
