### ISSUE TITLE
Publisher banner

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1127]
1. no close button
2. logo is not position correctly
3. shadow is missing
4. image is missing

![screenshot_20190219-083143](https://user-images.githubusercontent.com/9574457/52998280-32a9cf80-3423-11e9-9534-dacb9964a5ab.png)

Expected:
![image](https://user-images.githubusercontent.com/9574457/52998297-3dfcfb00-3423-11e9-8fd7-ea7e77496b2f.png)

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett @anthonypkeane should be there a close button #1? I don't see it in our layout.

**Comment by NejcZdovc** [comment]
how ca user close it?

**Comment by SergeyZhukovsky** [comment]
@NejcZdovc device's back button is a common way on Android to close any window.

**Comment by srirambv** [comment]
I don't think we need a close button like @SergeyZhukovsky mentioned device back button is used for navigating back. 

But this might change once [Android Q](https://www.neowin.net/news/google-might-be-getting-rid-of-the-back-button-in-android-q) comes up as there is rumour that Google might drop back button https://www.youtube.com/watch?v=PCM2SR5pDn4

>The key difference is that the back button, a staple of Android since its early days, is gone, swapped out for a new gesture on the pill button. Now, swiping to the left will bring you back, while swiping to the right will still allow you to switch between apps.

**Comment by jamesmudgett** [comment]
Close button isn't needed on Android but all other feedback here is valid. cc: @SergeyZhukovsky @anthonypkeane
