### ISSUE TITLE
Toggle for monthly is lagging

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1128]
When I try to toggle `Make this monthly` nothing happens. I need to switch amount and then sometimes it works.

![screenshot_20190219-083143](https://user-images.githubusercontent.com/9574457/52998358-6553c800-3423-11e9-89d4-4900983c9534.png)

**Comment by SergeyZhukovsky** [comment]
We need to increase a tap radius there.

**Comment by gdregalo** [comment]
Fixed in:
https://github.com/brave/browser-android-tabs/commit/ca4b2c61062715b6c84ed54262faed0de8c16c13
