### ISSUE TITLE
Toggle should change button

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1129]
When you toggle `Make this monthly` button at the bottom should change.

![screenshot_20190219-083143](https://user-images.githubusercontent.com/9574457/52998400-85838700-3423-11e9-8f1f-d96f799f9e78.png)

Desktop:

![image](https://user-images.githubusercontent.com/9574457/52998427-9207df80-3423-11e9-86d4-abb61ba081b7.png)

![image](https://user-images.githubusercontent.com/9574457/52998432-9502d000-3423-11e9-9487-1680f977500f.png)

**Comment by SergeyZhukovsky** [comment]
I don't think that should be so according to material design. @jamesmudgett correct me if I'm wrong.

**Comment by NejcZdovc** [comment]
@SergeyZhukovsky we need to change text when you toggle `Make this monthly` as action is different

**Comment by SergeyZhukovsky** [comment]
@NejcZdovc ah I got it. I thought you are talking that we should remove a square when the button is checked off.

**Comment by gdregalo** [comment]
Fixed in:
https://github.com/brave/browser-android-tabs/commit/3b6dc2f30e2e6ab80ace94ca2c5b3f855dca5d71
