### ISSUE TITLE
Tip sent transition

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1130]
We display tip sent transition which should be speed up.
![screenshot_20190219-083334](https://user-images.githubusercontent.com/9574457/52998506-bf548d80-3423-11e9-805e-7e949bde8bd4.png)

**Comment by SergeyZhukovsky** [comment]
Should it be? cc @jamesmudgett @anthonypkeane @srirambv

**Comment by srirambv** [comment]
@SergeyZhukovsky yes this was also brought up long back itself https://bravesoftware.slack.com/archives/C0816QH3R/p1548662189118900

This is what @jamesmudgett  mentioned in the thread
>Yes, this is a first run. Recently the animation was killed an updated to just the recipient’s favicon/avatar and “Thank you!“.
>The animation is native

**Comment by SergeyZhukovsky** [comment]
Ok, we will speed it up a bit.

**Comment by btlechowski** [comment]
Verified on  on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.3 staging
