### ISSUE TITLE
Amount selection spacing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1133]
Box selection should have the same spacing at the top as it has at the bottom. Now you don't have any at the bottom.

![screenshot_20190219-090055](https://user-images.githubusercontent.com/9574457/52999156-566e1500-3425-11e9-8e0b-1ee4aa07b173.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/a83d49266efe7d1d10c104943b8017ff13a50c4c

(Note: we are now using the actual <select> element, so we will get the mobile devices native options selector. This is so that it displays well everywhere)
