### ISSUE TITLE
Hide settings in tips

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1134]
We need to hide settings option in tips box

![screenshot_20190219-090135](https://user-images.githubusercontent.com/9574457/52999215-7dc4e200-3425-11e9-9a6b-754dc62af485.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/ffa6ce86d27d42313ff017acc0d07fa631355841

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Brave version `1.0.83`

`Settings` is removed from Tips section now

![image](https://user-images.githubusercontent.com/38657976/53393587-c733a500-39c2-11e9-993c-87243533950b.png)
