### ISSUE TITLE
Spacing at the bottom of the dialog

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1136]
Spacing at the bottom of the dialog should be the same at the top. Black space around the dialog should be the same as well.

![screenshot_20190219-090728](https://user-images.githubusercontent.com/9574457/52999418-f75cd000-3425-11e9-8c72-ae5c969ce7e7.png)

**Comment by ryanml** [comment]
@NejcZdovc this one is tricky, as the android navigation clips over the bottom of the web page, there's not really a way for modal to be aware of that. Best we can do for small devices is to just scale back the height of the modal.

**Comment by NejcZdovc** [comment]
that sounds good

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/384ffc25ff73898bc6d62695e043a2e4ea488f12
