### ISSUE TITLE
Background for the line in ac box

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1137]
I think we should remove background for supported site. It looks like disabled now. I know this was by design.

![screenshot_20190219-090923](https://user-images.githubusercontent.com/9574457/52999482-3be86b80-3426-11e9-99bc-945eb2333ea0.png)

cc @jenn-rhim

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/04d9a09f5952b3dc9bd797411601447055909db9
