### ISSUE TITLE
Hide ac options when ac is off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1138]
When ac is off we should hide attention and include in ac in the panel

![screenshot_20190219-091202](https://user-images.githubusercontent.com/9574457/52999590-79e58f80-3426-11e9-9ec0-83af70d4b208.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52999639-9681c780-3426-11e9-957d-20556248c771.png)

**Comment by gdregalo** [comment]
Fixed in: 
https://github.com/brave/browser-android-tabs/commit/43852bc48d5d9cdc0f7d5c0ce4751894c2750c6d
