### ISSUE TITLE
Open in a new tab feature

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#114]
Can you please add the ability to open a new tab to the front immediately instead of in the back? When I open a link in a new tab.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/tabs-section-missing-in-brave-1-0-49/24073/

**Comment by J-Reis** [comment]
+1 The ability to configure this (either foreground or background opening) would be a very desirable quality of life improvement for Brave. Options for both in the context menu for hyperlinks would be even better.

**Comment by anthonypkeane** [comment]
Issue moved to [brave/brave-browser #7349](https://github.com/brave/brave-browser/issues/7349) via [**ZenHub**](https://www.zenhub.com/)
