### ISSUE TITLE
Titles are not aligned

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1140]
Titles should be aligned.

![screenshot_20190219-091544](https://user-images.githubusercontent.com/9574457/52999821-1314a600-3427-11e9-90da-8df680d8f8ea.png)

Expected:
![image](https://user-images.githubusercontent.com/9574457/52999835-1c9e0e00-3427-11e9-8e01-7d506d8928b6.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/ffa6ce86d27d42313ff017acc0d07fa631355841

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
![screenshot_2019-02-26-13-48-12](https://user-images.githubusercontent.com/38657976/53397507-4b8b2580-39cd-11e9-92e2-833f7893150e.png)
