### ISSUE TITLE
Monthly payment not reflected

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1141]
Go to ac settings and try to select monthly payment. You can select it but amount is always 10 BAT. If you close ac settings you can see that monthly was saved. So I think problem is with UI not displaying correct amount.

![screenshot_20190219-092050](https://user-images.githubusercontent.com/9574457/53000049-b4036100-3427-11e9-9000-2926efec5599.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/0ed43295738dda5643594cb1f4cdefe468177c5b

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on 1.0.83

**Comment by LaurenWags** [comment]
Issue reproduces with 1.0.85 also.
