### ISSUE TITLE
Tips box next date is off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1142]
Should be aligned with total tips.
![screenshot_20190219-092454](https://user-images.githubusercontent.com/9574457/53000294-53285880-3428-11e9-970a-7811fdb37334.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/2d2377919d07df66b0cc5e9f6b44267c165f8827

**Comment by GeetaSarvadnya** [comment]
Depending on #1191. Will be tested once issue 1191 is fixed.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86

- Verified the description mentioned in the issue
  
![Screenshot_2019-03-11-23-06-53](https://user-images.githubusercontent.com/38657976/54145129-55903800-4453-11e9-8888-64258a3c15e4.png)
