### ISSUE TITLE
Remove change ac settings from the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1143]
Change ac settings should be removed. Also text needs to be updated to match desktop version.

![screenshot_20190219-092706](https://user-images.githubusercontent.com/9574457/53000435-abf7f100-3428-11e9-84fc-24d71542f2eb.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/53000446-b4502c00-3428-11e9-9be3-630b12b6e02f.png)

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/6342fc8a3df84032af56871de1d428cdbb1f1f6c

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-26-20-54-39](https://user-images.githubusercontent.com/38657976/53424304-fa992280-3a08-11e9-9cfa-1cb28bd7d56a.png)
