### ISSUE TITLE
Pending contributions are not shown on settings wallet

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1144]
We need to display pending contributions like we display it in the panel.

In the panel (which is ok):
![screenshot_20190219-093035](https://user-images.githubusercontent.com/9574457/53000623-1b6de080-3429-11e9-8e7a-c1c6bcc27172.png)

In the settings page (is missing):
![screenshot_20190219-093028](https://user-images.githubusercontent.com/9574457/53000665-2fb1dd80-3429-11e9-8bca-e9c309734eda.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/a619d79ce950c2a0703680f920320e9f1bb59bc5

**Comment by GeetaSarvadnya** [comment]
Cannot test the issue as Rewards Summary is not displayed in `Your wallet` page currently, Dependant on #1213
