### ISSUE TITLE
Alert close is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1145]
If I try to close this alert nothing happens
![screenshot_20190219-093246](https://user-images.githubusercontent.com/9574457/53000784-6daf0180-3429-11e9-8f7c-2b69fd78f840.png)

**Comment by srirambv** [comment]
The tap radius is at the very top of the `X` button. It doesn't always close if the tap radius is a little off

**Comment by SergeyZhukovsky** [comment]
We will add a bigger tap radius.

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/944419d345f05d71c45b5f4a3a209af2f5e62d44
