### ISSUE TITLE
Button has strange border around it

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1147]
Yes I am ready on rewards page has strange border around it
![screenshot_20190219-093701](https://user-images.githubusercontent.com/9574457/53001146-43117880-342a-11e9-98bf-72ab70e765c7.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/53001167-5290c180-342a-11e9-97fb-5b4523401f3f.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/384ffc25ff73898bc6d62695e043a2e4ea488f12
