### ISSUE TITLE
Claim process (Settings Page)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1148]
When I click on claim button in settings page nothing happens for a 5-15s then I get success message. I think we need to show overlay saying we are checking if you are human, please wait. Currently it seams that click was not recorded and users will probably click on it multiple times

cc @jenn-rhim

**Comment by SergeyZhukovsky** [comment]
We have the same situation in panel as well btw. cc @mandar-brave @jamesmudgett @anthonypkeane

**Comment by mandar-brave** [comment]
@jamesmudgett can we please take up the key network call topics today on Android and get past them using a loading button - this will reduce design overhead. cc @anthonypkeane

**Comment by jamesmudgett** [comment]
Let’s replace the  “Claim” text for the indeterminate progress spinner.

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/commit/b36c645578439f51ba3f0363e4978d61c196fbb8
