### ISSUE TITLE
YouTube videos in the background

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#115]
Can you add the ability for your browser to continue playing YouTube videos audio even when minimized and the screen is off, just like Firefox can?

**Comment by fasterthan** [comment]
+1

**Comment by JGH1000** [comment]
One of the biggest missing features in Brave atm. Would be great to have it, as an option if such default is not desirable.

**Comment by impatronic** [comment]
+1

**Comment by gfb-47** [comment]
+1

**Comment by srirambv** [comment]
Closing as background media play is implemented now
