### ISSUE TITLE
Text shouldn't be capitalised 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1150]
![screenshot_20190219-095948](https://user-images.githubusercontent.com/9574457/53002531-2b87bf00-342d-11e9-9365-67df5f71e02e.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/53002548-33476380-342d-11e9-837a-db78f6da4358.png)

**Comment by SergeyZhukovsky** [comment]
Any button in Chromium on Android has capitalised style. I don't think rewards panel should be an exception.
