### ISSUE TITLE
Color of USD should be lighter

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1151]
Color for USD amount should match desktop
![screenshot_20190219-095948](https://user-images.githubusercontent.com/9574457/53002603-55d97c80-342d-11e9-80ec-e79667ac5ac8.png)

Desktop
![image](https://user-images.githubusercontent.com/9574457/53002626-5ffb7b00-342d-11e9-946c-fdc5540586ac.png)

**Comment by deeppandya** [comment]
Thanks @NejcZdovc i will update it

**Comment by kjozwiak** [comment]
Looks like this is only partially completed as the value is still not using `#ffffffa6` as per https://github.com/brave/browser-android-tabs/issues/1151#issuecomment-531110268. Looks like the `USD` part is using the correct colour but not the amount. Example:

<img width="520" alt="Screen Shot 2019-11-05 at 1 10 49 AM" src="https://user-images.githubusercontent.com/2602313/68183207-b122af00-ff69-11e9-8ee3-f3910954d188.png">

* used https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0 on `Pixel 2 XL Android 10`

@NejcZdovc both the value and the currency type should be the same colour correct? If that's the case, I'll create a new issue which can be addressed in the next release.

CCing @aekeus @srirambv

**Comment by NejcZdovc** [comment]
@kjozwiak that is correct

**Comment by kjozwiak** [comment]
Thanks @NejcZdovc. Created #2258 as a follow for the remaining work to be completed/fixed.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0.
