### ISSUE TITLE
We should only show amount > then 0

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1152]
We currently show all items in the summary, where we should only show ones that are higher then 0.
![screenshot_20190219-101052](https://user-images.githubusercontent.com/9574457/53003260-dfd61500-342e-11e9-919a-6fc1efd703cc.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/53003218-c3d27380-342e-11e9-8abc-4cd6cbbe6f42.png)

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/c6c51e32df7b010f50c9886ba91a58b793cead4e
