### ISSUE TITLE
Line is missing after successful ac

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1153]
Line is missing in rewards summary

![screenshot_20190219-101052](https://user-images.githubusercontent.com/9574457/53003359-1744c180-342f-11e9-88b0-706673130920.png)

**Comment by SergeyZhukovsky** [comment]
That was fixed in the context of https://github.com/brave/browser-android-tabs/commit/8f4901e0db8126ab1b226bed9c5a79c04149a37c
