### ISSUE TITLE
Elements are not aligned to the middle

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1154]
- BAT amount
- USD amount
- grant button

are not aligned to the middle of the box

![screenshot_20190219-095948](https://user-images.githubusercontent.com/9574457/53003727-eca73880-342f-11e9-8d0e-cbec7055c0aa.png)

Desktop
![image](https://user-images.githubusercontent.com/9574457/53003752-fb8deb00-342f-11e9-8f8c-6404e75badfe.png)

**Comment by SergeyZhukovsky** [comment]
@NejcZdovc I don't see what's not aligned here.

**Comment by NejcZdovc** [comment]
You can see on the image that all items has more spacing on the left then on the right
![53003727-eca73880-342f-11e9-8d0e-cbec7055c0aa](https://user-images.githubusercontent.com/9574457/53043589-16d91480-3489-11e9-9afb-bf55115d197f.png)

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/5757cb99f3329813507845a7ce48e67c87b3a10f
