### ISSUE TITLE
BAT logo underlined

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1155]
Currently we always show rewards logo underlined. As far as I remember that should be only underlined in some particular scenario, otherwise it should be without line at the bottom. @jenn-rhim which scenario was that?

As first step I think we just need to remove that line and add it back when we define that scenario.

![screenshot_20190219-095948](https://user-images.githubusercontent.com/9574457/53004336-41977e80-3431-11e9-85e8-c485761a9fdf.png)

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett @anthonypkeane how should it look like?

**Comment by SergeyZhukovsky** [comment]
Just make it without underline for now.

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/ed2e849e2eecdd4b68cb87668a898ec161bcb249

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Brave version `1.0.83`
![screenshot_2019-02-26-13-29-04](https://user-images.githubusercontent.com/38657976/53396492-92c3e700-39ca-11e9-9a88-1c1945e8e5cc.png)
