### ISSUE TITLE
White space at the bottom of the page

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1156]
White space marked on the image should be removed

![screenshot_20190219-104138](https://user-images.githubusercontent.com/9574457/53005248-23cb1900-3433-11e9-880e-113c5f33b1d0.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/0d7fc66260f4baedae30e0882c36485d3a3ef16d

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86

- Verified the description mentioned in the issue, now there is not white space in brave://rewards page when rewards switch is set to OFF.

![Screenshot_2019-03-11-17-16-20](https://user-images.githubusercontent.com/38657976/54121920-aab35600-4421-11e9-9cf6-8ad0ca9a3c78.png)
