### ISSUE TITLE
Deleted publisher doesn't add again after revisiting

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1157]
## Description 
Deleted publisher doesn't add again after revisiting

## Steps to Reproduce 

   1. Enable rewards
   2. Visit a site to add to a-c list
   3. Delete the site from a-c list
   4. Revisit the site in a new tab, never gets added to the list

## Actual result: 
Deleted publisher doesn't add again after revisiting

## Expected result:
Should re-add the site once its visited again

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version? N/A
   - Beta build? Rewards build

**Comment by SergeyZhukovsky** [comment]
Shouldn't it be deleted forever unless we restore it via option that missed and described in https://github.com/brave/browser-android-tabs/issues/1132? cc @NejcZdovc

**Comment by NejcZdovc** [comment]
@srirambv site should be deleted for ever until user restore it

**Comment by SergeyZhukovsky** [comment]
We will handle it here https://github.com/brave/browser-android-tabs/issues/1132
