### ISSUE TITLE
After sending a recurring monthly tip to verified pubs, Make this monthly checkbox is still available in BR panel for the same pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1159]
## Description 
After sending a recurring monthly tip to verified pubs, Make this monthly checkbox is still available in BR panel for the same pubs

## Steps to Reproduce 

   1. Open brave 1.0.81
   2. Enable rewards and claim grants
   3. Open DDG verified pub
   4. Send a monthly recurring tip to verified pub DDG
   5. Verify monthly recurring tip is displayed in Tips section
   6. Click on Send tip for DDG.
 

## Actual result: 
`Make this monthly` checkbox is still available in BR panel

## Expected result:
Should be same as desktop - After sending monthly recurring tip to verified pubs,  The `Make this monthly` checkbox should not be available for the same pubs.

## Issue reproduces how often: 
Always
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/d3be2a858b340d9b25a796c992374df3aaabacb7

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
