### ISSUE TITLE
YouTube video problem

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#116]
Here is the link on problem video
https://m.youtube.com/watch?v=FVMf98Gnh9g

**Comment by SergeyZhukovsky** [comment]
There is a problem with video on that website also http://m.appledaily.com.tw/actionnews/

**Comment by lukemulks** [comment]
@SergeyZhukovsky we just received another report here in Community. 

https://community.brave.com/t/youtube-videos-not-playing/1791

Do we know specifically which codecs are the issue here? I am down to take a deeper look into this, just am not sure if we were provided a more vague/generic note about the codecs, or if Google has listed the codecs in question specifically somewhere.

**Comment by SergeyZhukovsky** [comment]
@lukemulks I haven't looked on it much, but it is related to HTML5 video.

**Comment by freebrowser1** [comment]
Try the desktop version: https://www.youtube.com/watch?v=FVMf98Gnh9g .
A WAP site version might cause the problem.

**Comment by lukemulks** [comment]
Also reported here: http://www.heerlijkerwijs.nl/kopje-chocolade/

YT player debug info: 
```
luke.mulks [11:26 PM] 
Your browser does not currently recognize any of the video formats available.
Click here to visit our frequently asked questions about HTML5 video.
[x]
Video ID:lPkexfxd6lQ
Dimensions:320 x 210 * 3
Resolution:0 x 0
Volume:100%
Stream Host:
Stream Type:https
CPN:T_dYj2H8ku7mkKNv
Mime Type:
DASH:no
Color:
Connection Speed:1016 Kbps
Buffer Health:0.0 s
Network Activity:0 KB
Dropped Frames:-
```

```
 "ns": "yt",
 "el": "embedded",
 "cpn": "T_dYj2H8ku7mkKNv",
 "docid": "lPkexfxd6lQ",
 "ver": 2,
 "referrer": "https://www.youtube.com/embed/lPkexfxd6lQ?rel=0&showinfo=0&iv_load_policy=3",
 "cmt": "0",
 "plid": "AAVMANi_6inTYIj0",
 "ei": "2_XdWKvKJNet_AP25qSgAw",
 "fs": "0",
 "rt": "21.87",
 "of": "GC6OCn1lTVgpgJyrp2hYjw",
 "euri": "http://www.heerlijkerwijs.nl/kopje-chocolade/",
 "lact": 12,
 "cl": "151729545",
 "mos": 0,
 "state": "80",
 "vm": "CAEQAA",
 "volume": 100,
 "c": "WEB",
 "cver": "1.20170330",
 "cplayer": "UNIPLAYER",
 "cbr": "Chrome Mobile",
 "cbrver": "57.0.2987.108",
 "cos": "Android",
 "cosver": "6.0.1",
 "hl": "en_US",
 "cr": "US",
 "len": "79",
 "fexp": "9422596,9428398,9431012,9433221,9434046,9434289,9446054,9446364,9449243,9453897,9456640,9457141,9458231,9458576,9460160,9463496,9463594,9463965,9465533,9466793,9466795,9468483,9469224",
 "size": "210:320:3",
 "inview": "1",
 "conn": "7",
 "vct": "0.000",
 "vd": "NaN",
 "vpl": "",
 "vbu": "",
 "vpa": true,
 "vsk": false,
 "ven": false,
 "vpr": 1,
 "vrs": 0,
 "vns": 0,
 "vec": null,
 "vvol": 1,
 "debug_error": {
   "errorCode": "fmt.noneavailable",
   "errorDetail": "nosupported.1;f18.1;f43.1",
   "message": "This video format is not supported.",
   "messageKey": "YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK"
 },
 "ismb": 1430000,
 "relative_loudness": "2.721",
 "debug_videoId": "lPkexfxd6lQ",
 "0sz": false,
 "op": "",
 "yof": false,
 "dis": "",
 "gpu": "Adreno_(TM)_330",
 "cgr": true,
 "debug_playbackQuality": "unknown",
 "debug_date": "Thu Mar 30 2017 23:23:44 GMT-0700 (PDT)"
}
```
@SergeyZhukovsky I did a little digging from the FAQ page. 
Do you know if we have WebM video format compatibility? We may have that, but I wanted to double check.

**Comment by SergeyZhukovsky** [comment]
@lukemulks yep, we do. Btw, you can check what formats do we support on html5test.com in Video section.

**Comment by kiwidragonfly** [comment]
I have the same problem on my Galaxy S5 Android 6.0.1 phone running, Brave 1.0.23 on most new youtube videos. I find older youtube videos tend to work fine.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/video-playback-issue/4077

**Comment by Parsnip** [comment]
If you go to https://www.youtube.com/html5 and check, MSE & H.264 are red on Brave. Is that related?

**Comment by johnlm1** [comment]
I encountered this issue on my Android phone — I thought I'd share the relevant links here instead of on the brave forums, where a few threads addressing this issue have been closed.

https://m.youtube.com/watch?v=etwwvISxXCM
https://m.youtube.com/watch?v=BBH2_kqA-C4

Both located in this article if that matters:
https://www.buzzfeed.com/spenceralthouse/everyone-loves-a-good-cumback-story?bffbmain&ref=bffbmain&utm_term=.ne97e3Aw9#.tjYqVvweZ

Brave 1.0.24
Android 7.0

**Comment by SergeyZhukovsky** [comment]
What I found, Youtube shows that we don't support MSE & H.264
https://www.youtube.com/html5. Also it is good to check the problems on that website https://demo.castlabs.com/

**Comment by Klaasvaak** [comment]
We also have problems playing embedded youtube videos on our website.

An example: https://www.youtube.com/embed/voM6dieAqYg?autoplay=1&controls=1&modestbranding=1&cc_load_policy=1&rel=0&enablejsapi=1&origin=https%3A%2F%2Fwww.withlocals.com&widgetid=2

This video does not play on Brave for Android. It does play on Firefox and Chrome for Android. It also plays on iOS safari.

URL the video is embedded: https://www.withlocals.com/experience/roman-food-tour-the-10-tastings-a1c875e0/

**Comment by LaurenWags** [comment]
+1 from twitter, user mentions problems playing videos embedded in forums: https://twitter.com/SalvaCanas/status/898270406628462592

**Comment by iSasFTW** [comment]
+1 Having this on nearly every site with embedded YouTube videos, as well as the mobile YouTube site itself. I've noticed that sometimes it works (no idea what circumstances caused it to), but most of the time it gives out that same error about HTML5 playback. Adjusting shield settings makes no difference.

**Comment by AnotherLife** [comment]
This must be related to that "MSE & H.264" missing support that Youtube page points to. Even my tablet's super-old integrated web browser has full green checkmarks on that YT page and plays the videos just fine.

Missing codec or something? Please fix it.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/youtube-and-html5/11488?u=eljuno

**Comment by fredgolightly** [comment]
Updated Android brave today, still does not work, ie http://thehill.com/video/technology/364914-watch-live-fcc-votes-to-repeal-net-neutrality-protections

**Comment by informationeagle** [comment]
I cannot play Youtube TV at all on Brave, it's fine on Chrome.

**Comment by Vincent449** [comment]
This is currently still an issie for me as well.

Here is one video example:

https://m.youtube.com/watch?v=_LOh8sBqD0g

Swapping to the Desktop version allows me to watch the video.

**Comment by akaleeroy** [comment]
If **MSE & H.264** are not present due to licensing or privacy issues this will never be fixed. 
Devs, please confirm if this is the case.

**Comment by Brblol** [comment]
How can Brave browser be taken seriously if it can't even play YouTube videos

**Comment by YisroelAdler** [comment]
Are you still experiencing the issue? I've checked now (with the videos I had it in the past as well videos mentioned above) and it seems to be working!

**Comment by YisroelAdler** [comment]
There was an update today. Perhaps it fixed it?

**Comment by Brblol** [comment]
No, I didn't update between when it didn't work and when it did

**Comment by Vincent449** [comment]
There is still an issue. I started just going through videos to find one.

This for instance:
https://m.youtube.com/watch?v=iMsk8WD5m84

**Comment by akaleeroy** [comment]
I updated today but issue persists, some YouTube videos work others don't. Here is [a playlist](https://reddit.musicplayer.io/r/leeroysjams) with plenty of broken ones.

**Comment by StephenBass** [comment]
+1 from BAT Reddit regarding YouTube Android playback.
https://www.reddit.com/r/BATProject/comments/7z52fe/does_the_referral_program_work_with_androidios/duldhv9/

**Comment by Tomatoshadow2** [comment]
You can play any video, that says its not supported, by switching to Desktop mode.

**Comment by Vincent449** [comment]
Tomato, that works in some instances, but not all of them.

**Comment by powdernose** [comment]
Looking at html5test.com results versus other browsers that do play the videos, I see the difference under 'streaming' - > 'codecs'.
There's no support for the mp4 wrapper, whereas other browsers can play h264 and aac in mp4.

**Comment by Tomatoshadow2** [comment]
@Vincent449 Ahh I see, thanks for pointing that out, my apologies.

**Comment by Vincent449** [comment]
An update on this:

This video here:

https://m.youtube.com/watch?t=1s&v=ESDY4TbZaMg

When you hit the menu button for Brave, then click "Desktop Site" and try to play the video, it instead prompts you to open it with Video Player (Android 7.0).

When you hit video player it plays fine. Seems weird to me though, it doesn't want to play it through Brave, but instead a different video app.

Hopefully this helps, the HTML5 bug pops up more and more each day.

**Comment by Tomatoshadow2** [comment]
@Vincent449 What build did you reproduce this with? I can't reproduce nor do I get the prompt to open it with video player.

**Comment by Vincent449** [comment]
@TomatoShadow - I was up to dat when that happened, but there was an update today as well. It still occurs with the current (fully updated) build.

Let me know of anything I can do to help you out. I'll look into recording a video tonight when I get a second.

**Comment by kilara1988** [comment]
This is the only problem i have with this browser.It is perfect in any other way for me.
Can't they just use the free OpenH264 codec from Cisco?
It seems Firefox is using it,but is slower than Chrome/Brave.

**Comment by akaleeroy** [comment]
@kilara1988 It can't be a missing codec, since [standalone .MP4 files work](#issuecomment-364728763)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/can-html5-video-be-included/18973?u=eljuno

**Comment by kilara1988** [comment]
So is there any progress on this issue? It has been more than an year since the issue was opened and i haven't seen any comments as to what the actual problem is.It just keeps getting marked for a later and later milestones.

So my question is: Is this issue being investigated and worked on?

**Comment by SergeyZhukovsky** [comment]
We are working on that. The resolution should come up soon. Thank you for your patience.

**Comment by samartnik** [comment]
Support of these videos will be added in 1.0.44 version.
Links for QA for testing (YouTube links should be opened in mobile version):
https://demo.castlabs.com
https://m.youtube.com/watch?v=iMsk8WD5m84
https://m.youtube.com/watch?t=1s&v=ESDY4TbZaMg
