### ISSUE TITLE
BR panel doesn't show pubs info always instead it shows up `JOIN REWARDS`BR panel even though rewards is enabled

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1160]
## Description 
BR panel doesn't show pubs info always instead it shows up `JOIN REWARDS`BR panel even after enabling rewards

## Steps to Reproduce 

STR 1:
   1. Open brave 1.0.81
   2. Enable rewards and claim grants
   3. Open DDG
   4. Click on BAT Logo/ BR panel
   5. Incorrect popup displayed

STR 2:
   1. Open brave 1.0.81
   2. Enable rewards and claim grants
   3. Open DDG and add it to a-c table
   4. Wait for auto-contribution
   5. After auto-contribution, in Brave rewards page, click on notification icon on BAT logo, `JOIN REWARDS` popup displayed instead rewards summary

STR 3:
   1. Open brave 1.0.81
   2. Enable rewards and claim grants
   3. Open DDG and send a tip to it
   4. Go to rewards page, click on BAT logo, `JOIN REWARDS` popup displayed instead rewards summary

## Actual result: 
JOIN REWARDS panel is displayed instead of pubs info 

https://drive.google.com/open?id=1AXErLds8AU3hjaUuUBVrDngZJNs3Gcoh

## Expected result:
Click on BR panel on any pub should display publishers info in BR panel

## Issue reproduces how often: 
Always
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
That has been fixed https://github.com/brave/browser-android-tabs/commit/1c1b4316328323a0819e6995d3672f9f2e4f5321

**Comment by GeetaSarvadnya** [comment]
The issue still persists on 1.0.85
