### ISSUE TITLE
When Rewards is OFF, Tips panel should be hidden and it should not be accessible

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1163]
## Description 
When Rewards is OFF, Tips panel should be hidden and it should not be accessible

## Steps to Reproduce 

   1. Open brave 1.0.81
   2. Enable rewards
   3. Turn off `Auto-Contribute`
   4. Verify auto contribute details are hidden
   5. Verify Tips panel

## Actual result: 
Tips panel is still accessible, user can click on `View Deatils` in Tips section

https://drive.google.com/open?id=1JSoruFlxfAnviCBO9b49KYOXum0_MsVm

## Expected result:
Same as desktop - Tips section should be hidden

## Issue reproduces how often: 
Always

## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: Android 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Don't think this is a valid bug. Tips panel is still shown on desktop when a-c is disabled. You should still be able to tip and see the one time/recurring tips when a-c is disabled.
![screenshot_20190220-084711](https://user-images.githubusercontent.com/17010094/53064115-9ba94a00-34ec-11e9-9a73-1e7acdf8c8d1.png)

But the title says `Rewards is OFF` which is confusing from the actual steps. If rewards is off, it disables all of them Ads/A-C/Tips as expected 
![screenshot_20190220-084639](https://user-images.githubusercontent.com/17010094/53064119-9e0ba400-34ec-11e9-9365-b5b4212f86b1.png)

**Comment by GeetaSarvadnya** [comment]
@srirambv Updated the steps and subject. Thanks for correcting!
