### ISSUE TITLE
Onboarding flow

### ISSUE THREAD

**Issue by mandar-brave** [brave/browser-android-tabs#1167]
On-boarding flow for existing and new users needs to be defined.

- Existing users can discover BR via the bat logo and settings. The experience should drive the user through a small tour of a-c and tips (very much like the desktop page) before user opting in
- New user should get a welcome screen as part of the on-boarding experience or some guide to turn Brave Rewards ON. This experience should not block user at first install and user can always opt in via the BAT logo and/or settings.

@jamesmudgett please drive the design. Assigning issue to you to update before engineering can pick it up.

cc @anthonypkeane @SergeyZhukovsky

**Comment by anthonypkeane** [comment]
James

I think this onboarding should be one and the same as the overall Android onboarding

Having two will be confusing. 

Lmk what you think?

**Comment by jamesmudgett** [comment]
Entry points: 

- BAT logo
- "Brave Rewards" menu item.

I agree that it would be a good idea to introduce BR to new users in a more obvious way. Let's plan on having a popup callout Brave Rewards on first-run. I'll work on a design to add here.

**Comment by jamesmudgett** [comment]
@anthonypkeane full on-boarding would be great to explore as we are doing on iOS. This could be part of the Android design refresh.

**Comment by jamesmudgett** [comment]
![screen shot 2019-02-27 at 10 20 25 am](https://user-images.githubusercontent.com/318119/53589716-f114d500-3b44-11e9-9c02-a600a0f74f20.png)

**Comment by anthonypkeane** [comment]
pop up should display on first- run 

i.e. user upgrades to the version of the app with BR
When they open the browser, the pop up shows

**Comment by jamesmudgett** [comment]
[br_banner.zip](https://github.com/brave/browser-android-tabs/files/2916648/br_banner.zip)

**Comment by mandar-brave** [comment]
Can we do a link to BR FAQ as learn more in the text --> https://brave.com/faq/#what-is-brave-rewards.

@anthonypkeane @jamesmudgett

**Comment by anthonypkeane** [comment]
@SergeyZhukovsky, from James design, instead of "continue" pls use "Start here"

_some of this copy may change as we get feedback_

**Comment by anthonypkeane** [comment]
Assigned to James to confirm design

**Comment by jamesmudgett** [comment]
Based on discussion we will use a local notification instead of popup.

Notification title should be "Brave Rewards is now live."

**Comment by gdregalo** [comment]
@jamesmudgett @SergeyZhukovsky 
The notification has 2 forms: collapsed and expanded.The expanded one has 2 buttons.
The proposed "Continue" or "Start here" assumes to bring a user to UI where she can start working with Rewards.  I think, the button which points a user to a web resource where she can only learn about the feature should be named something like "Learn more".
![rewards_notification_collapsed](https://user-images.githubusercontent.com/37560650/55268664-4c300980-5262-11e9-9b09-f74b4a4edb22.png)
![rewards_notification_expanded](https://user-images.githubusercontent.com/37560650/55268665-4c300980-5262-11e9-89fb-192c07c777be.png)

**Comment by anthonypkeane** [comment]
@gdregalo 

Looking at this please update the text slightly to: 

Brave Rewards is here
Support the sites you love. 

Buttons are
Get started
Dismiss

Tapping Get started opens Brave and ideally opens the BR panel

If the 2 lines of text are too long you can shorten it to "Brave Rewards is here"

----

For devices on <21 (if you are supporting them) have the following text:

Brave Rewards is here. 
Open Brave to get started and support the sites you love.

If that is too long use

Brave Rewards is here. 
Open Brave to get started.

**Comment by jamesmudgett** [comment]
Get started button should land on brave://rewards welcome page

**Comment by SergeyZhukovsky** [comment]
That's done!

**Comment by srirambv** [comment]
@anthonypkeane On tablets I see the same onboarding notification. Is this expected or should tablets have the longer text onboarding message? 
![image](https://user-images.githubusercontent.com/17010094/55748296-4c6f9800-5a0c-11e9-9d2d-4f263d7cc6d3.png)

**Comment by anthonypkeane** [comment]
> @anthonypkeane On tablets I see the same onboarding notification. Is this expected or should tablets have the longer text onboarding message?
> ![image](https://user-images.githubusercontent.com/17010094/55748296-4c6f9800-5a0c-11e9-9d2d-4f263d7cc6d3.png)

It is as expected @srirambv

**Comment by LaurenWags** [comment]
Verified passed with 1.0.90rc3 on Asus Zenfone (x86). Saw and logged issue #1450 while testing.
