### ISSUE TITLE
Support desktop wallet recovery (tracking for launch)

### ISSUE THREAD

**Issue by mandar-brave** [brave/browser-android-tabs#1168]
Adding this for tracking purposes.

We should allow desktop users to be able to restore their desktop wallets here allowing them to have a cross device view for Brave Rewards.

@NejcZdovc @SergeyZhukovsky

**Comment by brianddk** [comment]
I assume that the intent is bidirectional.  

1. Allow Desktop wallets to be restored on Android
2. Allow Android wallets to be restored on Desktop.

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/bklsk9/sync_mobile_and_desktop_wallet/
