### ISSUE TITLE
Turn off BR for non safetynet users; mask Add Funds link

### ISSUE THREAD

**Issue by mandar-brave** [brave/browser-android-tabs#1169]
For the March 13th launch, if users do not clear safetynet, do not let them turn on Brave Rewards.
Add funds needs to be masked out as well.

Since there is no way for the user to get funds and/or add funds, it is not clear what value Brave Rewards brings to such users.

Till we get to parity for supporting user wallets, we should keep BR functionality off for non safetynet users.

cc @anthonypkeane @davidtemkin @NejcZdovc

**Comment by SergeyZhukovsky** [comment]
That is duplicated https://github.com/brave/browser-android-tabs/issues/1062
