### ISSUE TITLE
Ads not blocked on WebMD [hackerone #498087]

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#1171]
https://hackerone.com/reports/498087

A HackerOne researcher reports that they see ads on WebMD. I was able to reproduce easily, with Shields up. Shields shows a huge number of ads and trackers blocked, but all ads on the page still seem to be visible.

**Comment by samartnik** [comment]
This will be fixed when Android is moved on brave-core base

**Comment by anthonypkeane** [comment]
fix on brave core
