### ISSUE TITLE
"Insufficient Funds" immediately on first open

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#1176]
Using [this test build](https://github.com/brave/browser-android-tabs/releases/tag/1.0.81(BR_3)), as soon as I enable Brave Rewards, I'm notified that I have insufficient funds.
![screenshot_20190222-143747](https://user-images.githubusercontent.com/639937/53275588-76fdcf80-36b0-11e9-822d-00e56cbe9a31.png)

**Comment by tomlowenthal** [comment]
Tapping "OK" on this shows me a grant notification, but the "Insufficient Funds" notice is on top.

**Comment by SergeyZhukovsky** [comment]
We show that notification in 3 days before an auto contribution process that is once in 30 days. The test build that is pointing on staging is set to every 10 minutes auto contributions just to test how does the process go. We have that message in 3 days before on a real build.
