### ISSUE TITLE
Black/grey border around Rewards panel

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#1177]
Using [this test build](https://github.com/brave/browser-android-tabs/releases/tag/1.0.81(BR_3)).
![screenshot_20190222-143747](https://user-images.githubusercontent.com/639937/53275622-97c62500-36b0-11e9-928c-614beaa8d52a.png)

**Comment by SergeyZhukovsky** [comment]
What colour should it be?

**Comment by NejcZdovc** [comment]
closing as dupe of https://github.com/brave/browser-android-tabs/issues/928

**Comment by tomlowenthal** [comment]
@SergeyZhukovsky I know this is a dupe, but I don't think there should be a border at all.
