### ISSUE TITLE
No status indicator on Ads

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#1178]
The ads section at the top of the Brave Rewards settings page doesn't have any controls or an indicator whether it's on or off. If it's on, there needs to be a control to turn it off. If it's disabled and not actually available, that needs to be clearly-communicated.

Using [this test build](https://github.com/brave/browser-android-tabs/releases/tag/1.0.81(BR_3)).

![screenshot_20190222-144809](https://user-images.githubusercontent.com/639937/53275714-fc817f80-36b0-11e9-97a7-fd36d53d718f.png)

**Comment by anthonypkeane** [comment]
Closing as this is fixed
