### ISSUE TITLE
Request/Suggestion: Implement toggle for "when last tab is closed" behavior on Android

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#1180]
## Description 
As it is, when closing the last tab on Android : 

1. If `Home Button` option is enabled, Brave will close immediately after last tab is closed.
2. If `Home Button` option is disabled, Brave will  remains open and blank (0 tabs).
_☝️ Note that option 1 is the _default_ behavior as `Home button` is disabled by default._

I have received an **overwhelming** number of complaints regarding this behavior. Many users wish to have the browser stay open after closing the last tab. Many users also assume that this feature is something we (Brave) implemented intentionally (IIRC, we inherited this behavior from chromium).

## Suggestion
**Insert an option to toggle between these two behaviors ("exit after last tab closed" vs "remain open after last tab closed") so that it is no longer dependent on the home button setting.** 

While the options (home button and last tab closing action) are related to some extent, they should not be anchored to one another.

**Additional consideration** - If users elect (via this option) to keep Brave open when all tabs are closed, default behavior should be to leave blank app "window" open, but we could also allow users to:
- Input desired URL/web page to open automatically when last tab is closed
- Open New Tab Page when last tab is closed (as opposed to clicking options --> new tab in empty window)

**Alternative Solution** - Spitballing here, but we could also set the app **to open a new tab to their Home Page URL when last tab is closed.** I say this because it works around the need to add new UI elements, but still makes this option "toggle-able" to some extent. Again, I don't think these two features/behaviors should be linked to one another - but if they already are, this may be a quick fix to consider in the interim.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/browser-closing-with-last-tab-closed/44178?u=eljuno

**Comment by GeetaSarvadnya** [comment]
+1 from community https://community.brave.com/t/closing-a-tab-minimizes-brave-mobile-app/46138/2

**Comment by Brave-Matt** [comment]
@jamesmudgett

**Comment by Brave-Matt** [comment]
+1 (Zendesk)
![image](https://user-images.githubusercontent.com/3299098/54647797-3308ab00-4a61-11e9-969e-21a7293e5d16.png)

**Comment by Brave-Matt** [comment]
+1 Play stor:
![image](https://user-images.githubusercontent.com/3299098/54647834-516ea680-4a61-11e9-996d-64e3eda0c2d8.png)

**Comment by Brave-Matt** [comment]
+1 Play store:
![image](https://user-images.githubusercontent.com/3299098/54647877-706d3880-4a61-11e9-84c4-e4392d8024eb.png)
Translated: After the update, the browser began to collapse when closing the tab.

**Comment by Brave-Matt** [comment]
+1 Play store:
![image](https://user-images.githubusercontent.com/3299098/54647894-80851800-4a61-11e9-99f4-3b0897b52caf.png)

**Comment by Brave-Matt** [comment]
+1 Play Store:
![image](https://user-images.githubusercontent.com/3299098/54647945-a7434e80-4a61-11e9-8743-95cc7ecc966f.png)
Translated:
> Since the last update, closing the last tab closes the application! Whereas before that was not the case.

**Comment by Brave-Matt** [comment]
+1 Play store:
![image](https://user-images.githubusercontent.com/3299098/54647960-b5916a80-4a61-11e9-85aa-076ca0d3fe21.png)

**Comment by anthonypkeane** [comment]
https://twitter.com/bravesampson/status/1139407102592421894?s=12

**Comment by EyanGoldman** [comment]
Closing as this issue is now identical to #1716 and will most likely get included in 1.2.0
