### ISSUE TITLE
unable to claim grants when the network is re-enabled

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1183]
## Description 
unable to claim grants when the network is re-enabled

## Steps to Reproduce 

   1. Clean profile 1.0.81
   2. Enable rewards by clicking on `JOIN REWARDS`
   3. Disconnect the VPN/wifi
   4. Click on `claim`
   5. Click on `Settings`
   6. Turn ON VPN/wifi
   7. Reload rewards page
   8. Click on `Claim` on the rewards page - can't claim grants
   9. Click on `claim` on rewards panel - can't claim grants
   

## Actual result: 
unable to claim grants when the network is re-enabled

https://drive.google.com/open?id=1X1CaUz-wa2-jm7CvMJkfjDcJYUbefShn

## Expected result:
Should be able to claim the grants when n/w is turned ON

## Issue reproduces how often: 

Always
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
It is probably related to that issue https://github.com/brave/browser-android-tabs/issues/1184

**Comment by SergeyZhukovsky** [comment]
I could not replicate that on a new brave-core version, but the Claim button never appeared to me at all after reenabling network

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/6107799f93e594ed90fec57a439dad8fbd1184c4

cc: @SergeyZhukovsky
