### ISSUE TITLE
Claim button isn't removed even after grant is claimed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1184]
## Description 
Claim button isn't removed even after grant is claimed

## Steps to Reproduce 

   1. Enable rewards
   2. Disconnect device from network
   3. Tap on Claim button nothing happens
   4. Connect device to network again and open a new rewards page
   5. Claim grant via rewards page, claim button is still shown on the rewards page

## Actual result: 
![screenshot_20190225-124917](https://user-images.githubusercontent.com/17010094/53320502-df8cbc80-38fb-11e9-8408-3634d13e1561.png)

## Expected result:
Once grant is claimed, claim button should be hidden

## Issue reproduces how often: 
Fairly easy

## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): PHone
   - Android Version: 9.0
   
## Brave version:
1.0.81 (rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
@srirambv - by step 5, are two rewards pages open at this point? Is the first one still showing grant claim button while second one is not? Or did I misread and this all happens on the same page

**Comment by LaurenWags** [comment]
@ryanml I can reproduce consistently with these steps:
1. Clean install 1.0.85 (BR_5)
2. Tap on BAT logo
3. Tap on Learn More link
4. chrome://rewards opens in a new tab
5. Tap on Yes I'm Ready --> get creating wallet spinner
6. Once wallet is created, tap on 'Claim' on the banner.
7. Close the "overlay" (which displays grant amount, expiration date, etc) via the x in upper right corner.
8. You will see the banner to claim a grant is still displayed.
9. Refresh page, still displayed.
10. Close chrome://rewards.
11. Open chrome://rewards in a new tab. 
12. Banner is still displayed.
In this screenshot you can see I have a balance of 30 BAT (from a grant) but still see the claim grant banner.
![1184-android](https://user-images.githubusercontent.com/28145373/53767463-ea1ef700-3ea3-11e9-908f-ccff4ba0c54b.jpg)

Using Asus Zenfone with Android 6.0 and 1.0.85 (BR_5)

**Comment by ryanml** [comment]
@laurenwags can you try something for me? Can you do all these steps exactly the same, but in Step 7 can you click the orange Ok button at the bottom of the overlay rather than the X, and report your findings?

**Comment by LaurenWags** [comment]
@ryanml closing via the orange OK button in step 7 makes the claim banner go away for me.

Should I log https://github.com/brave/browser-android-tabs/issues/1184#issuecomment-469450093 as a separate issue?

**Comment by ryanml** [comment]
@laurenwags perfect that was my hunch, fix should be easy. Yes plz if you can log and assign it to me, thanks!

**Comment by LaurenWags** [comment]
Thanks! logged https://github.com/brave/browser-android-tabs/issues/1243 for my above comment.

**Comment by SergeyZhukovsky** [comment]
I have a weird state of settings page after an upstream update of brave-core when I do original steps. After step #3 the whole page becomes white and it doesn't recover even when I turn on the Internet again and even when I restart a browser. @ryanml could you please check that?

**Comment by ryanml** [comment]
Closing this issue in favor of: https://github.com/brave/browser-android-tabs/issues/1183 as it describes the networking issue at hand.
