### ISSUE TITLE
Tip for unverified pubs keeps increasing over time

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1185]
## Description 
Tip for unverified pubs keeps increasing over time

## Steps to Reproduce (Not reliable)

   1. Enable Rewards and claim grant
   2. Visit 3 unverified pubs and tip them 1 BAT each, verify 3 BAT is shown for unverified pubs message
   3. Keep the phone aside and take a nap
   4. Getup after a while and see the tips summary is more than 3 BAT. (I saw it to be 42 BAT) 

## Actual result: 
Tip for unverified pubs keeps increasing over time

## Expected result:
Shouldn't self contribute BAT to unverified publishers

## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.81(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
@srirambv I checked all of that, it's not a bug at all. The thing that happens is auto-contribution that is set to 30 minutes in the test build and it distributes your balance when you hit it, the default value is 20 BAT.
