### ISSUE TITLE
Tips section is hidden when settings is opened and navigated back

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1186]
## Description 
Tips section is hidden when settings is opened and navigated back

## Steps to Reproduce 

   1. Enable rewards
   2. Open Tips view details section and tap on settings
   3. Navigate back, tips section is hidden, tap back button again shows up 

## Actual result: 
![2019_02_25_15_37_58](https://user-images.githubusercontent.com/17010094/53330307-2b4b6000-3914-11e9-9923-149dc7b3016f.gif)

## Expected result:
Should not hide any section when navigating back

## Issue reproduces how often: 
Easy 

## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.81(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closing as this will not be an issue anymore as we removed settings for tips https://github.com/brave/browser-android-tabs/issues/1134

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Brave version `1.0.83`
`Settings` is removed from Tips section now
![image](https://user-images.githubusercontent.com/38657976/53393466-7459ed80-39c2-11e9-82aa-3f658c3f096d.png)
