### ISSUE TITLE
Page without favicons uses domain letter for favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1187]
## Description 
Page without favicons uses domain letter for favicon

## Steps to Reproduce 

   1. Enable rewards
   2. Visit srirambv.github.io
   3. Open rewards panels, shows favicon of domain name

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/53333129-027a9900-391b-11e9-9887-87cdac507366.png)
![image](https://user-images.githubusercontent.com/17010094/53333150-132b0f00-391b-11e9-916a-6f6e1fef2233.png)

## Expected result:
Similar to desktop 
![image](https://user-images.githubusercontent.com/17010094/53333296-761ca600-391b-11e9-92ea-d93bff48f439.png)

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
no
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.81(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
That's a normal behaviour. We use a common mechanism as Chromium does to shows icons for websites without icons. cc @jamesmudgett
