### ISSUE TITLE
Wallet creation goes into infinite loop when device is offline

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1188]
## Description 
Wallet creation goes into infinite loop when device is offline

## Steps to Reproduce 

   1. Put device on offline mode
   2. Enable Rewards from BR panel, shows `Please try again later` message
   3. Try enabling rewards from rewards page, goes into infinite loop, have to restart browser after device goes online for rewards to be enabled

## Actual result: 
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/17010094/53335025-65bafa00-3920-11e9-9bb9-f8f7f899bb07.gif)

## Expected result:
Should not go into infinite loop when device is offline and shouldn't require to restart browser to enable rewards when device comes online

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.81(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
@ryanml could we show `Please try again later` message in that case as well?

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/6107799f93e594ed90fec57a439dad8fbd1184c4

cc: @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) 1.0.88 rc2
