### ISSUE TITLE
Translation missing for Contribution date under tips

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1191]
## Description 
Translation missing for Contribution date under tips

## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards
   3. Claim UGP grants
   4. Open DDG in a new tab
   5. Send a monthly recurring tip to DDG
   6. Verify Tips panel on the Rewards page

## Actual result: 
![image 1](https://user-images.githubusercontent.com/38657976/53388596-bfb7d000-39b1-11e9-82f8-141886f9da1b.png)

## Expected result:
same as desktop
![image](https://user-images.githubusercontent.com/38657976/53388647-ed047e00-39b1-11e9-9c37-4fe49aeb9360.png)

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/85268b9f82efdeeec177bf1dbca8dfb136993492

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
