### ISSUE TITLE
Tip table header needs to renamed to `TYPE` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1192]
## Description 
Tip table header needs to renamed to `TYPE` 

## Steps to Reproduce 

   1. Open brave 1.0.83
   2. Enable rewards
   3. Click on `View Details` in Tips section
   4. Verify tips table headers

## Actual result: 
![image](https://user-images.githubusercontent.com/38657976/53389505-913bf400-39b5-11e9-919a-cf2602d4f11f.png)

## Expected result:

Same as desktop
![image](https://user-images.githubusercontent.com/38657976/53389448-605bbf00-39b5-11e9-9b34-4e372e15217d.png)

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
This one is up to date in core, will be fixed on next translation pull:

https://github.com/brave/brave-core/blob/master/components/resources/brave_components_strings.grd#L436
