### ISSUE TITLE
Rewards summary alignment is not same on all the tabs. 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1193]
## Description 
Rewards summary alignment is not same on all the tabs. 
## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable Rewards 
   3. Claim UGP grants
   4. Add a few pubs to a-c table (Verified + unverified)
   5. Wait for auto-contribution to complete
   6. After auto-contribution, verify Rewards summary on diff tabs

Note: Sometimes, the page reloads auto-correct the alignment issues.

## Actual result: 
![image](https://user-images.githubusercontent.com/38657976/53391832-9735d300-39bd-11e9-8a95-62f4141e8303.png)
![image](https://user-images.githubusercontent.com/38657976/53391886-c0eefa00-39bd-11e9-9d79-2504949ae849.png)
https://drive.google.com/open?id=1-SEvZCCZgrTvl_uveCLau0Dm_UiYII1K

## Expected result:
Should be same on all tabs

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
That's a dup of https://github.com/brave/browser-android-tabs/issues/1153
