### ISSUE TITLE
BR panel doesn't update attention % unless rewards page is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1194]
## Description 
BR panel doesn't update attention % unless rewards page is opened

## Steps to Reproduce 

   1. Enable rewards 
   2. Visit a site and spend min time on it
   3. Open rewards panel, attention shows 0%
   4. Open rewards page, site attention shows 100% in a-c list
   5. Switch back to site and open rewards panel, shows 100%
   6. Repeat steps 2-5 on a different site, same behaviour, % value gets adjusted based on time 

## Actual result: 
BR panel doesn't update attention % unless rewards page is opened

## Expected result:
Should not require you to navigate to rewards page for the panel to show the correct % calcualted

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.83(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
@srirambv it is not a rewards(or settings page) related at all. You should understand how the % counts. There is an event on every single page `onHide` or `onClose`. The % gets recalculated only when we receive that event. That been said, we cannot say and calculate % for you if you stay active on that page, the page should be hidden or closed to be able to recalculate it. It is the same on desktop btw. Closing that issue as NA.

**Comment by srirambv** [comment]
Thanks for the explanation @SergeyZhukovsky 👍
