### ISSUE TITLE
Site already listed gets removed when a new site is added after changing the monthly budget

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1195]
## Description 
Site already listed gets removed when a new site is added after changing the monthly budget

## Steps to Reproduce 

   1. Enable rewards and claim grant
   2. Set monthly budget to 100 BAT
   3. Visit duckduckgo.com and neowin.net and ensure both gets added to the a-c list
   4. Wait for 30 mins, no reconcile happens and no insufficient funds message is shown
   5. Delete duckduckgo.com from a-c list and set monthly budget to 10 BAT
   6. Visit theverge.com and spend min time there
   7. Go back to rewards page, neowin.net is removed and only shows theverge.com with 100%
   8. No reduction in balance as contribution didn't go through on step 4 

## Actual result: 
Site already listed gets removed when a new site is added to the a-c list

## Expected result:
Should not remove existing site from the list when a new site is added after changing the monthly budget

## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.83(rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
@srirambv could you re verify that and reopen if it is still a problem. It works as expected to me.
