### ISSUE TITLE
Total tips reset to Zero after browser restart

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1196]
## Description 
Total tips reset to Zero after browser restart

## Steps to Reproduce 

   1.  Clean profile 1.0.83
   2. Enable rewards
   3. Claim UGP grants
   4. Open DDG and send one-time tips to it
   5. Verify total tip is shown as 1 and one-time tip for DDG is displayed under Tips table
   6. Click on `Exit` in the Hamburger menu
   7. Restart the browser

## Actual result: 
Total Tips for the month is reset to zero

![image](https://user-images.githubusercontent.com/38657976/53403091-ff45e280-39d8-11e9-83d5-9d0efb9f0c2f.png)

## Expected result:
Browser restart should not alter the total tip amount

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.83
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/77d469d7c55b49e5bb64efb9f975a1497f1eecd0

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
