### ISSUE TITLE
Shields and Rewards button show in URL bar when tabs container is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1197]
## Description 
Shields and Rewards buttion show in URL bar when tabs container is opened

## Actual result: 
![screenshot_20190226-145120](https://user-images.githubusercontent.com/17010094/53403558-eb4eb080-39d9-11e9-8adb-5c985a2db456.png)

## Expected result:
Should not have URL bar overlay on Shields and Rewards buttons

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.83 (rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/0222e998fd62bf774719257ded23ac9aafb13af2

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
