### ISSUE TITLE
User can send Zero monthly recurring tips

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1198]
## Description 
User can send Zero monthly recurring tips

## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards
   3. Claim grants
   4. Open DDG 
   5. Open BR panel, by default 5 BAT is selected unselect it by tapping on it
   6. Without selecting any tip amount select `Make this monthly` checkbox
   7. Click on `SEND MY DONATION`

## Actual result: 
Without selecting tip amount user can send zero monthly recurring tips

![image](https://user-images.githubusercontent.com/38657976/53404352-809e7480-39db-11e9-8ce5-5b0dbae9c28d.png)

https://drive.google.com/open?id=1ReNBEzHEkvyJdI7zp0soU-PXjpL7X0Hv

## Expected result:
Same as desktop
 `SEND MY DONATION` should be in the disabled state if the user tries to send monthly recurring tip without selecting a tip amount

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.83
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
That is done https://github.com/brave/browser-android-tabs/commit/8f4901e0db8126ab1b226bed9c5a79c04149a37c

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
