### ISSUE TITLE
Brave Crashes when `JOIN REWARDS` goes into infinite loop

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1199]
## Description 
Brave Crashes when `JOIN REWARDS` goes into infinite loop. Right now I don't have exact steps to reproduce the issue. I have managed to record the steps partially, which has crash issue recorded. I have seen this issue trice while testing Rewards. 

## Steps to Reproduce (  STR may not be Reliable - Just mentioned the steps when I came across with the issue) 

   1. Clean profile 1.0.83
   2. Enable rewards
   3. Claim grants
   4. Open DDG
   5. Send zero monthly recurring tips to DDG ( Refer #1198 )
   6. Click on `Exit` in the Hamburger menu
   7. Restart the browser
   8. Send a one-time tip to DDG
   9. Repeat steps 6 and 7
  10. Open BR panel for DDG ( see `JOIN REWARDS` panel display instead of tips panel)
  11. Multiple clicks on BR panel shows `JOIN REWARDS` panel only
  12. In between, I have restarted the browser
  13. Repeated step 11, at one point Tips panel displayed with `Please try again` message and then the browser crashed
  
  

## Actual result: 
Steps 10 to 13 are recorded in video.

https://drive.google.com/open?id=1OrATLadUtdkq21aZpKIj3qoMz7-TPMuT

Recorded file is really too long, skip after few secs as I have repeated steps 10 to 13 multiple times. Brave crashes exactly at `00:02:36`

## Expected result:
Should not be any crash

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy
   - Android Version: 5.1
   
## Brave version:

1.0.83
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya I tried it 30 times, I had 30 BAT as grants and made a tip 1 BAT each time and restarted browser and etc. An issue with 0 tips is fixed. The loop you see is because we cannot get any result from ledger till the tips go through fully. The tips are executed on next start in most of times as you exit browser right away. It should go away soon when we fix our internal issue with synchronous service(@NejcZdovc @yrliou do we have an issue to track that, I want to set a dependency?).

**Comment by yrliou** [comment]
@SergeyZhukovsky https://github.com/brave/brave-browser/issues/3393

**Comment by SergeyZhukovsky** [comment]
It's done in that update https://github.com/brave/browser-android-tabs/commit/d62da87fd113c1d6afeb87d882c93185cfd626d4
