### ISSUE TITLE
`SEND MY DONATION` button needs to disabled when tip amount is not selected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1200]
## Description 
`SEND MY DONATION` button needs to disabled when tip amount is not selected

## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable Rewards
   3. Claim grants
   4. Open DDG, unselect default selection 5 BAT
   5. Click on `SEND MY DONATION` without selecting any tip amount
   

## Actual result: 
`Sent Tip` message is displayed. After clicking on BR panel message displayed as `There was a problem processing your tip, please try again`

https://drive.google.com/open?id=1ozcO329Yo21uXX-qIlVqbzY4dSAiI6VH

## Expected result:
`SEND MY DONATION` button needs to disabled when tip amount is not selected

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by gdregalo** [comment]
There is always a selected button with an amount to tip.
Fixed in:
https://github.com/brave/browser-android-tabs/commit/8f4901e0db8126ab1b226bed9c5a79c04149a37c

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.85
