### ISSUE TITLE
Removed site cannot be added to a-c table once the auto-contribution settings are changed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1201]
## Description 
The removed site cannot be added to a-c table once the auto-contribution settings are changed

## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards and claim grants
   3. Add DDG to a-c table
   4. Uncheck `Allow contribution to non-verified sites` checkbox in auto-contribution settings
   5. Remove DDG from a-c table 
   6. Close all the tabs one by one ( browser gets closed)
   7. Open the browser again
   8. Open DDG in new a tab, spend min page time on DDG ( I spent more than 15 secs)
   9. Verify a-c table in auto contribution panel
   

## Actual result: 
The removed site is not added to a-c table once the auto-contribution settings are changed

https://drive.google.com/open?id=1KseJa_YtYTxQczde7M21RZc12zyEmtu9

## Expected result:
Should be able to add removed sites to a-c table

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
It will be handled here https://github.com/brave/browser-android-tabs/issues/1132
