### ISSUE TITLE
Unable to select `Monthly Payment` options in single click

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1202]
## Description 
Unable to select `Monthly Payment` options in single click
## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards
   3. Open `Auto-Contribution Settings` page
   4. Select monthly payment options one by one from the drop down

## Actual result: 
Single click on radio button will not allow monthly payment selection, needs to click on the radio button twice.

## Expected result:
Should be able to select the Monthly payment in the single click
## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
I cannot replicate that, @GeetaSarvadnya could you make a video please?

**Comment by srirambv** [comment]
I have experienced this as well. Havent seen this happen on the last build though but definitely on the older builds.

**Comment by srirambv** [comment]
@SergeyZhukovsky  here's a recording of the issue. Please watch the video in 0.25x speed so that its easy to see the issue happening. Also noticed that even when a value is selected it still defaults to the default 10BAT and then a second selection changes it to the new value

https://youtu.be/c_dK1JGhUcs

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/a83d49266efe7d1d10c104943b8017ff13a50c4c

(Note: we are now using the actual <select> element, so we will get the mobile devices native options selector. This is so that it displays well everywhere)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86

- Verified the STR mentioned in the description
- Verified that changed Monthly budget is same on `Auto-Contribution` and `Auto-Contribution settings` page
- Verified that changed `Auto-Contribution settings` retained after browser restart
- Verified that changed `Auto-Contribution settings` retained after Turn OFF/ON brave rewards
- Verified that changed `Auto-Contribution settings` retained after navigating away from auto contribution panel
