### ISSUE TITLE
Add the ability to reset Brave Rewards to pre-opt in state on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1204]
Linked to: https://github.com/brave/brave-browser/issues/1192

## Description
For various reasons, users may want to reset Brave Rewards to a pre-opt in state
We need to provide users with a mechanism so they can do this. At the simplest level this may just be a "reset button" with BR Settings. 

## ToDo
1) @jamesmudgett and @anthonypkeane to design a flow and UI
The goal for v1 of this is to minimize engineering effort.

2) @anthonypkeane to get sign off of the flow from @mandar-brave

At this point the ticket should be updated with the design and assigned to Dev

**Comment by anthonypkeane** [comment]
@jamesmudgett Can you provide a design for this one? Need to follow Desktop

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane I think we decided to make it after. We can add that functionality in any moment and tell users with problems that it's coming.

**Comment by anthonypkeane** [comment]
Desktop have this is setting, not BR settings.

**Comment by anthonypkeane** [comment]
Please place the option is a new section in settings. 

Section: Brave Rewards
Place it under Appearance (from #978)


Reset Brave Rewards
This will delete your Brave wallet and reset all of your Brave Rewards data. 
Cancel | Confirm


If there is an error resetting BR, use the following text

Reset Error
There was an error resetting Brave Rewards. Please relaunch Brave and try again. 
Relaunch

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/1433

**Comment by LaurenWags** [comment]
@anthonypkeane @jamesmudgett Looks like this setting is under 'Advanced' instead of 'Appearance' (per https://github.com/brave/browser-android-tabs/issues/1204#issuecomment-479078669) - please confirm if this is expected/ OK.

**Comment by btlechowski** [comment]
Verified on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.3

The Reset function works as expected.
I see the same as @LaurenWags. The setting is under `Advanced` instead of 'Appearance'.
