### ISSUE TITLE
UI error in "lion menu"

### ISSUE THREAD

**Issue by KommX** [brave/browser-android-tabs#121]
Brave 1.0.12, Chromium 55.0.2883.91

I have some problems describing the bug. So I add two screenshots to visualize it:
![screenshot_20170127-213637](https://cloud.githubusercontent.com/assets/7859245/22387696/2c8238aa-e4dd-11e6-9140-84438cd1ef3f.png)
![screenshot_20170127-213651](https://cloud.githubusercontent.com/assets/7859245/22387697/2c86a49e-e4dd-11e6-9171-06b527bc76df.png)

Steps to reproduce:

1. Load http://m.faz.net
2. **While** Brave is loading the page touch the lion for the "lion menu".
3. Still **While** loading scroll the lion menu down and up.
4. The numbers for "HTTPS Upgrades" is counting up to a 3-digit number.
5. When scrolling down the number slips to "Scripts Blocked".

For steps 4 and 5 see the attached screenshots.

**Comment by anthonypkeane** [comment]
Will be fixed in the new shield design
