### ISSUE TITLE
Update Default Browser notification text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1210]
The notification text to alert the user to set Brave as the default browser should be

Make Brave your default web browser 
Save battery and load websites faster without ads
Yes | No

Pls see: https://docs.google.com/document/d/1QlfBbG4uQXGHOJgI34V6J1ywWfZuXnzOPf2TGCIpC7I/edit?ts=5c07fb63#

Currently it shows as

![screenshot_20190226-151959](https://user-images.githubusercontent.com/7606853/53529984-384a8980-3aa3-11e9-88ce-a9e6890d15a0.jpg)

**Comment by samartnik** [comment]
@anthonypkeane currently we have `Settings` button (instead of `Yes` and `No`) when this condition is true
`supportsDefault() && !isBraveSetAsDefaultBrowser() && hasAlternateDefaultBrowser()`
Should it be the same `Yes` and `No` for buttons?

**Comment by samartnik** [comment]
This is done in this branch https://github.com/brave/browser-android-tabs/tree/default_browser_selection
