### ISSUE TITLE
Follow up of #1019- Min time and min page visit settings are not respected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1214]
## Description 

Found while testing #1019 
Min time and min page visit settings are not respected

## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards
   3. Change default auto-contribution settings
   4. Set min page time and min visits to 5 seconds 5 visit respectively
   5. Add a or two sites to a-c table 
   6. Verify that sites got added to a-c table ( sites added to a-c table met the min page time and visit criteria)
   7. Set min page time and min visits to 1 minute 1 visit respectively
   8. Verify that sites which are added in step 5 are disappeared from a-c table - Which is as expected as 
      the criteria set in step7 doesn't match
   9. Add a site to a-c table 
 10. Verify that site which is added in step 9 is visible in a-c table - Which is as expected
 11. Change min page time and min visits back to 5 seconds 5 visit respectively
 12. a-c table becomes empty - Which is not expected, sites which are added in step 5 should get reflected in a-c table as they met the criteria which is set in step11
 
      

## Actual result: 
a-c table is empty even though Min time and min page visit are met for the visited websites

## Expected result:
Based on criteria, sites should get reflect in  a-c table

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:

1.0.83
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by SergeyZhukovsky** [comment]
That is working on my end. @GeetaSarvadnya could you please verify it on the newest version and open if it appears again. Thanks!

**Comment by GeetaSarvadnya** [comment]
@SergeyZhukovsky I am able to reproduce the issue on the latest version 1.0.88 rc2. Step 8 is failing After, I set new criteria 1 min and 1 Visit (step7), the sites which are added in step 5 should not appear in a-c table.

**Comment by srirambv** [comment]
Moving to beta 2

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya I cannot replicate it, I think in your last comment it could be that total time of websites was hit 1 minute and that's why they were retained.

**Comment by srirambv** [comment]
Verified the issue on Samsung Tab. Here's my observation

- Clean install from playstore
- Enable rewards
- Change min time to 5sec
- Visit 2-3 sites, got listed in a-c list after 5sec of min visit
- Changed min time to 1min, sites added before is removed
- Visit 2-3 sites in a new tab and stay on the page for >1min, none of them got listed in the a-c list

**Comment by SergeyZhukovsky** [comment]
We can move to a next roadmap as not an issue really, it counts correctly just page isn't get refreshed.

**Comment by srirambv** [comment]
Verified on playstore build. Works as expected. Chaning min time back to 5 sec lists all the sites. Closing as working.
