### ISSUE TITLE
Sites added to the a-c list disappear when new tab is opened 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1226]
## Description 
Sites added to the a-c list disappear when new tab is opened 

## Steps to Reproduce 

   1. Add a few sites to the a-c list 
   2. Open a new tab with rewards page as active tab
   3. Newly added site is removed from the a-c table (UI only)
   4. Open rewards page again site gets added back

## Actual result: 
https://youtu.be/R2OPYO2bkwA (play the video is 0.5x mode to see the effect)

## Expected result:
Should not remove

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

May be same as  #1195

**Comment by SergeyZhukovsky** [comment]
I don't see an issue with the latest brave-core. In any case I don't it's P1, P2 as the website doesn't disappear really it just disappears on tab switches, some draw effect, but doesn't break a functionality at all

**Comment by anthonypkeane** [comment]
Fixed on core
