### ISSUE TITLE
Reconcile fails even with sufficient funds

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1231]
## Description 
Reconcile fails even with sufficient funds

## Steps to Reproduce 

   1. Enable rewards and claim grant
   2. Add a few verified and non-verified pubs including media pubs to a-c list
   3. Wait for 30 mins, Error shows up saying process failed due to insufficient funds even though wallet has 30 BAT from grant however a-c list is removed completely 

## Actual result: 
Reconcile fails even with sufficient funds

## Expected result:
Funds should go to verified pubs when processing is completed

## Issue reproduces how often: 
Easy

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
cc @srirambv

**Comment by srirambv** [comment]
Unable to reproduce the issue. Looks to be working. Got auto contribute success message once reconcile was completed. Closing the issue for now. Will reopen if run into it again
