### ISSUE TITLE
Enable rewards via BR panel still shows rewards off 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1232]
## Description 
Enable rewards via BR panel still shows rewards off 

## Steps to Reproduce 

   1. Enable rewards and disable 
   2. Close the rewards page 
   3. Enable rewards via BR panel in a new tab
   4. Open settings page from rewards panel
   5. Rewards page shows rewards state as OFF
   6. Pull down reload page, state doesnt change but BR panel shows enabled state
   7. Turn on rewards on rewards page, rewards welcome message shows up, pull down reload page removes it (#1228)

## Actual result: 
https://youtu.be/b5dSWNSuwkQ

## Expected result:
State should be consistent when enabled/disabled via page or panel

## Issue reproduces how often: 
Easy 

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#1228

**Comment by LaurenWags** [comment]
Reproduced on Asus Zenfone with Android 6.0 and 1.0.85 (BR_5)

**Comment by SergeyZhukovsky** [comment]
@ryanml I investigated that I believe you have to call `GetRewardsMainEnabled` on settings page open.

**Comment by ryanml** [comment]
@SergeyZhukovsky issue is there is no webui method set up for getting rewards main enabled. (No `brave_rewards.getRewardsEnabled` in core)

How is Rewards being enabled via the panel? What calls does it pass through? It should trigger an observer when Rewards is disabled/enabled (OnRewardsMainEnabled gets called) then the settings page listens for the change and updates appropriately. This flow on core works fine

**Comment by NejcZdovc** [comment]
in core we don't allow user to enable from the panel, that's why it's not working on android. @mandar-brave @davidtemkin @jenn-rhim do we want to have parity here? 

desktop:
![image](https://user-images.githubusercontent.com/9574457/53861122-7c79e480-3fe3-11e9-88fe-c3966265e838.png)

mobile:
![image](https://user-images.githubusercontent.com/9574457/53861199-c236ad00-3fe3-11e9-9968-4e8a82124260.png)

**Comment by NejcZdovc** [comment]
ok we want parity, so I created https://github.com/brave/brave-browser/issues/3597 to change it in desktop as well

**Comment by ryanml** [comment]
Reopening (got auto-closed by mistake)

This was fixed partially upstream here: https://github.com/brave/brave-core/pull/1864

Once brave-core is updated in Android I can finish the fix cc: @SergeyZhukovsky

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/4b8f9fafa5910e305f0ee27b00c729b71fd3b6a9

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87

- Verified the STR mentioned in the description ( In all the below 3 conditions issue is working fine)
- Verified enabling rewards from BR panel and then followed STR.
- Verified enabling rewards from brave://rewards page and followed STR
- Verified enabling rewards from Hamburger menu and followed STR
