### ISSUE TITLE
Advance settings options go beyond visual elements in landscape mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1234]
## Description 
Advance settings options go beyond visual elements in landscape mode

## Steps to Reproduce 

   1. Open a-c advance settings 
   2. Change device orientation to landscape
   3. Dropdown items go beyond the element visually (see video for more understanding)

## Actual result: 
https://youtu.be/ADFXUcrOcrs. This would probably be even worse on smaller screen devices. This issue is recorded on Pixel 3Xl which is a bigger screen phone

## Expected result:
Should include all elements within visual elements when in landscape mode

## Issue reproduces how often: 
Easy

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/a83d49266efe7d1d10c104943b8017ff13a50c4c

(Note: we are now using the actual <select> element, so we will get the mobile devices native options selector. This is so that it displays well everywhere)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87
