### ISSUE TITLE
Loading site from top tiles clears existing entries in a-c list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1235]
## Description 
Loading site from top tiles clears existing entries in a-c list

## Steps to Reproduce 

   1. Visit a few sites to ensure all of them are listed in a-c list 
   2. Open a new tab and load a top tile site and stay on it for min time
   3. Open rewards page, existing entries from step 1 is lost and only contains the site from step 2

## Actual result: 
Loading site from top tiles clears existing entries in a-c list

## Expected result:
Should retain all the sites 

## Issue reproduces how often: 
Intermittent issue. Was able to reproduce only once 

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@srirambv did maybe contribution happened between step 2 and 3?

**Comment by srirambv** [comment]
No there was no contribution in progress or completed. This was well within the contribution time frame

**Comment by SergeyZhukovsky** [comment]
@srirambv everything works as expected on my end. I have all websites listed at the end. More than that there are no special cases and we don't distinguish top tile websites from websites user types in URL bar. Mostly likely a contribution process happened as @NejcZdovc mentioned as early builds had it set on 10 minutes. Could you please re verify that and re open an issue if it happens again?
