### ISSUE TITLE
Displaying favicon for non verified Pubs

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1236]
## Description 
This one came up before, but as I understand, we shouldn't show the favicon of a website, unless that website is verified. 

@mandar-brave to confirm?

![Displaying Facicon.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/2b4bd08a-e75c-4f21-a82a-d1a911901f94)

## Steps to Reproduce 

   1. Open a non verified website and open the panel

**Comment by NejcZdovc** [comment]
@anthonypkeane favicons for regular sites are ok, we shouldn't show favicon for media publishers that we need to fetch from the page/api.

**Comment by anthonypkeane** [comment]
On this site, on Desktop we have a placeholder icon, not the favicon 

@mandar-brave what is the correct behaviour? Cheers

<img width="556" alt="screen shot 2019-03-04 at 9 07 17 am" src="https://user-images.githubusercontent.com/7606853/53749748-ee73f180-3e5c-11e9-82b7-55c82f43e193.png">

**Comment by NejcZdovc** [comment]
@anthonypkeane we don't have placeholder. You need to wait for site to load until you see favicon. For example if you open panel again you should see favicon

**Comment by NejcZdovc** [comment]
Also we have problem if you visit site as www, then we don't show faivcon as url is by default without www

**Comment by NejcZdovc** [comment]
![image](https://user-images.githubusercontent.com/9574457/53750010-feb1be00-3ea8-11e9-81bd-eb19b2e9bf5c.png)
