### ISSUE TITLE
metamask.io

### ISSUE THREAD

**Issue by ekankyesme** [brave/browser-android-tabs#1237]
## Steps to Reproduce 

   1. 
   2. 
   3. 

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version:
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Please add details and reopen the issue
