### ISSUE TITLE
user can send infinite tips to verified pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1238]
## Description 
The user can send infinite tips to verified pubs

## Steps to Reproduce 

   1.  Clean profile 1.0.85
   2.  Enable Rewards and claim UGP grants ( 30 BAT
   3.  Open DDG in a new tab
   4. Open the BR panel and keep sending  10 BAT (one-time tips) one after the other ( don't close BR panel on each tip send)
  

## Actual result: 
After sending tips, the a-c balance did not go down in BR panel, due to which user can send tips infinitely 

## Expected result:
Should be same as desktop.

After sending tips, a-c balance should get updated immediately without BR panel refresh. 

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
That is fixed https://github.com/brave/browser-android-tabs/commit/d62da87fd113c1d6afeb87d882c93185cfd626d4

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86
