### ISSUE TITLE
Beta Flag for BR

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1239]
## Description
To enable BR for Beta, users can enter chrome://flags and enable BR.

**Settings Text**

Header: Brave Rewards (beta)
Text: Enable Brave Rewards (beta) on your device.

Options
Default (which = off)
Enabled
Disabled

Placement
Where ever is easier, perhaps on the top of the chrome://flags page

![Brave Rewards Flag.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/b9823c79-d2ae-414a-a427-e4e0fb2b0ea0)

![Brave Rewards Flag - Toggle.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/5e7b1422-4216-4414-b57d-055c8aca4587)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86

- Verified that `Brave Rewards (beta)` displayed under `Chrome://flags`

![Screenshot_2019-03-11-16-53-25](https://user-images.githubusercontent.com/38657976/54120705-6a060d80-441e-11e9-9537-1ad8c36969e6.png)
