### ISSUE TITLE
Request desktop website always option

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#124]
# Test plan
https://github.com/brave/browser-android-tabs/issues/124#issuecomment-335487951

We need an option to use desktop site version everywhere.

**Comment by LaurenWags** [comment]
+1 google play store

**Comment by AlexeyBarabash** [comment]
There is a pull request for the issue https://github.com/brave/browser-android-tabs/pull/391 .

**Comment by LaurenWags** [comment]
Closing after discussion with @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Reopening as I found a scenario where I am not getting the Desktop version of a tab:
Change the setting for Desktop Mode to be on.
Open a new tab, go to a site like google.com. You will get the desktop version as expected. (if you tap on the 3 dots menu, you see 'Request desktop site' is checked.
Reuse that same tab to go to a different site such as github.com. You will get the mobile version. (if you tap on the 3 dots menu, you see that 'Request desktop site' is no longer checked'.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/option-for-permanent-desktop-mode/8142?u=eljuno

>If I check the box “Desktop Mode”, it should remain enabled until I disable it. Not force us back into mobile mode upon opening the next link. We should have options, not be forced.

**Comment by AlexeyBarabash** [comment]
Thanks, Lauren, Eljuno, working on fix.

**Comment by AlexeyBarabash** [comment]
There is a build (arm) for the fix, https://github.com/brave/browser-android-tabs/releases/tag/1.0.34(beta1) . Thanks.

**Comment by LaurenWags** [comment]
Tests Ran for Global Desktop Mode
1. Verify option not enabled by default
2. Verify still able to toggle this option on individual tabs
3. Enable option
  a. Verify when open a new (normal or incognito) tab and navigate to a site the Desktop version of the site is displayed
  b. Reuse the tab by typing a new URL in URL bar. Verify Desktop Mode remains enabled for new site. Navigate back to previous page. Verify previous page still displays Desktop Mode.
  c. Long press on a link to open in a new tab. Verify Desktop Mode remains enabled for new tab that is opened.
  d. Long press on a link to open in incognito tab. Verify Desktop Mode remains enabled for new incognito tab that is opened.
  e. Long press on text and search. Verify search is opened in a new tab with Desktop Mode enabled.
  f. Open new tab and navigate to a bookmark. Verify Desktop Mode is enabled.
4. Disable option
  a. verify when open a new tab and navigate to a site the mobile version of the site is displayed.
  b. Reuse the tab by typing a new URL in URL bar. Verify mobile version of site is displayed. Navigate back to previous page. Verify previous page still displays mobile version of site.
  c. Long press on a link to open in a new tab. Verify mobile version of site is displayed in new tab.
  d. Long press on a link to open in incognito tab. Verify mobile version of site is displayed in the new incognito tab that is opened.
  e. Long press on text and search. Verify search is opened in a new tab with mobile version of site.
  f. Navigate to a bookmark. Verify mobile version of bookmark site is displayed.

**Comment by srirambv** [comment]
3b, 3c & 3d steps fails. Rest all works fine

**Comment by srirambv** [comment]
Works as expected when global desktop mode is enabled for step 3. Closing issue as working as expected

**Comment by AlexeyBarabash** [comment]
Here is a n additional proposition for test, which I used when implemented. If you find it useful, you may include it in a list.

5. Global option is enabled, per-tab option is then disabled.
a. Enable global option (Site settings -> Desktop Mode). Navigate to a page. Ensure the page is a Desktop version.
b. Press three-dots tab menu, uncheck "Request desktop site". Ensure the page is a Mobile version.
c. Navigate through the links, verify pages are opened as a Mobile version of site.
d. Long press on a link, then open link in a new tab or new incognito tab. A new tab should be a Desktop version. [because it is a new tab and user agent is inherited from a global settings; the similar behavior is in original Chromium, enabled per-page desktop mode is not inherited in a new or incognito tab].

**Comment by LaurenWags** [comment]
Thanks @AlexeyBarabash - I included your scenario in https://github.com/brave/browser-android-tabs/issues/124#issuecomment-335487951
