### ISSUE TITLE
Claim grant banner not removed when closing success overlay via X

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1243]
## Description 
Logging from https://github.com/brave/browser-android-tabs/issues/1184#issuecomment-469450093

If you claim a grant from chrome://rewards and close the success overlay via the X, the claim grant banner doesn't go away.

## Steps to Reproduce 
1. Clean install 1.0.85 (BR_5)
2. Tap on BAT logo
3. Tap on Learn More link
4. chrome://rewards opens in a new tab
5. Tap on Yes I'm Ready --> get creating wallet spinner
6. Once wallet is created, tap on 'Claim' on the banner.
7. Close the "overlay" (which displays grant amount, expiration date, etc) via the x in upper right corner.
8. You will see the banner to claim a grant is still displayed.
9. Refresh page, still displayed.
10. Close chrome://rewards.
11. Open chrome://rewards in a new tab. 
12. Banner is still displayed.
In this screenshot you can see I have a balance of 30 BAT (from a grant) but still see the claim grant banner.

## Actual result: 
Note - balance is displayed as 30 BAT (amount of grant), but claim banner still remains. Tapping on it just results in a spinner on the banner.
![1184-android](https://user-images.githubusercontent.com/28145373/53768930-4d128d00-3ea8-11e9-9620-06b59f748c8c.jpg)

## Expected result:
Banner shouldn't be displayed, grant was claimed.

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? n/a
   - Beta build? yes, Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/766c85d4fc14091b83569214ac7bd9c79eb4a249

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87
