### ISSUE TITLE
line items displayed on BR panel / BR panel parity with b-c

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1244]
## Description 
After claiming a grant, BR panel shows line items for Auto Contribute, One time tips, monthly tips, etc. However, these items are 0 BAT, in b-c the line items don't display until they are greater than zero.

## Steps to Reproduce 

   1. Clean install 1.0.85 (BR_5)
   2. Enable Rewards.
   3. On chrome://rewards tap on wallet balance (it is 0BAT to start). Note that there are no line items.
   4. Tap on BAT logo. Note that there are no line items displayed.
   5. Close panel. Claim grant.
   6. On chrome://rewards tap on wallet balance (it is 0BAT to start). 
   7. You will see a single non-zero line item for the grant you accepted.
   8. Tap on BAT logo. 

## Actual result: 
All possible line items displayed, most with 0 BAT amounts.
![brpanel-android](https://user-images.githubusercontent.com/28145373/53772394-42f68b80-3eb4-11e9-9070-e9773e59049a.jpg)

## Expected result:
Only one line item should be displayed, the one for the token grant claimed. Line items should only display as they occur (with non-zero BAT amounts). This is how it works on b-c.
![brpage-android](https://user-images.githubusercontent.com/28145373/53772399-45f17c00-3eb4-11e9-871a-d718586108d5.jpg)

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? n/a
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for guidance on milestone

**Comment by srirambv** [comment]
* Verification passed on Pixel 3XL. Only entries for each item which has a positive value shows up in the panel
