### ISSUE TITLE
Ads panel will need  “coming soon”  text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1246]
## Description 
Ads won't be live when we launch BR on Android, so please add "coming soon" to that area in Settings

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/4a92abc932e2935a1a05e37834dfb0ee68b50a3e

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86
![Screenshot_2019-03-11-00-36-52](https://user-images.githubusercontent.com/38657976/54090042-e6084300-4395-11e9-85b7-67d50e38f381.png)
