### ISSUE TITLE
Cleanup SE part 2

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1249]
To maintain parity between iOS and Android

Search engines to support:

- Google
- DDG
- DDG Lite
- Qwant
- StartPage
- Yandex 

Any pre-set search engines should be retained on upgrade

- Infogalactic will be completely dropped regardless of user's set engine in either mode.

**Comment by anthonypkeane** [comment]
We have these now @srirambv pls re-open if not
