### ISSUE TITLE
claim banner still displayed even after grant claimed from panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1251]
## Description 
Once the claim banner is displayed on chrome://rewards, if you claim the grant from the panel the claim banner doesn't go away.

## Steps to Reproduce 

1. Install 1.0.85 (BR_5)
2. Tap on BAT logo
3. Tap on Join Rewards
4. Before notifications display on panel, tap on Settings to be navigated to chrome://rewards page
5. Once claim banner is displayed on chrome://rewards page, tap on BAT logo again
6. Dismiss Insufficient funds notification
7. Tap on Claim on token grant notification
8. Wait 15s or whatever amount of time to get grant
9. Tap on chrome://rewards page to dismiss panel
10. Notice claim banner still displayed.
11. Refresh page, claim banner still displayed.
12. Close tab, open a new one and navigate to chrome://rewards.
13. Claim banner still displayed.

## Actual result: 
Claim banner doesn't go away after grant is claimed from panel.

## Expected result:
Claim banner should go away.

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced by @srirambv

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone guidance

**Comment by ryanml** [comment]
@SergeyZhukovsky is `OnGrantFinish` being called when you claim a grant via the panel?

**Comment by srirambv** [comment]
Reproduced with different steps(https://github.com/brave/browser-android-tabs/issues/1285) on the new build but end result seems to be same banner is shown even after claiming grant and trying to claim again puts it in an infinite loop

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on 1.0.87 - Android 5.1 - Samsung Galaxy J3

In one more scenario, the `CLAIM` button is shown in brave://rewards page even after accepting grants from BR panel.  Steps are mentioned below:
1. Clean profile 1.0.87
2. Enable rewards through Hamburger menu
3. Click on BAT logo, click on grants notification and accept the grants from BR panel
4. Click on Settings
5. Brave://rewards page displayed
6. `CLAIM` is shown on brave rewards page even after accepting grants from BR panel

**Comment by srirambv** [comment]
Marking P1 as this one needs to be fixed for beta2 release

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/536023c33e078061fe713bc8d13c98692c834931 this should cover the numerous steps to reproduce this one.

cc: @SergeyZhukovsky @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90
