### ISSUE TITLE
monthly payment in ac table and ac settings should match

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1254]
## Description 
On a clean install, the Monthly Payment values on the Auto-Contribute table (chrome://rewards/contribute) and Auto-Contribute Settings (chrome://rewards/contribute-settings) do not match. On Brave-Core these values are the same on clean install.

## Steps to Reproduce 

   1. Clean install 1.0.85 (BR_5)
   2. Enable Rewards (I used panel), tap on Settings
   3. From chrome://rewards tap on 'View Details' under Auto-Contribute.
   4. On chrome://rewards/contribute, view Monthly Payment value, it's 20 BAT.
   5. Tap on Settings.

## Actual result: 
View Monthly Payment value, it shows 10 BAT.

![contrib-settings-10bat](https://user-images.githubusercontent.com/28145373/53913296-0304e500-4029-11e9-93e4-d64535e59306.jpg)

![contrib-20bat](https://user-images.githubusercontent.com/28145373/53913298-05673f00-4029-11e9-9000-eaf767af589f.jpg)

## Expected result:
Expected both values to match. Unsure which one is expected.

## Issue happens on: 
   - Current Playstore version? n/a
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone guidance

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/2f7dc38ef696fd18b2dc95e69a21bce3bb7a772f (they should both default to 20)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86
