### ISSUE TITLE
Grey out Add Funds button

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1255]
## Description 
We won't offer the ability to add funds initially, therefore the Add Funds button on the Panel and Settings page needs to be greyed out.

**Comment by SergeyZhukovsky** [comment]
@ryanml I disabled it on native panel https://github.com/brave/browser-android-tabs/commit/3c6393397aa9a3075bfca767f27e1005fb2a91d2. Could you please disable inside settings page and close the issue when done? Thanks.

**Comment by ryanml** [comment]
Removed from settings page here: https://github.com/brave/browser-android-tabs/commit/732fb6e2f82fc93f51ee762abaed0527371065d3

**Comment by LaurenWags** [comment]
@ryanml does this also remove it from the Tipping banner? We also have the scenario where you go to tip a site, tap on amount, and then tap on Send my Tip. If you don't have enough BAT in your wallet, you get a message prompting you to Add Funds, with a link which opens up the Add Funds modal in a different tab.
![1255](https://user-images.githubusercontent.com/28145373/54034507-07461500-4185-11e9-9225-f323a789b8d7.png)

**Comment by SergeyZhukovsky** [comment]
@LaurenWags, @ryanml is responsible for Settings page only. We blocked funding as well on site banner. I didn't grey it as it looks ugly, it just does nothing when we click on it.

**Comment by srirambv** [comment]
@SergeyZhukovsky Could that text be replaced as `Not enough tokens. Please wait for next available grant ` ? So that its more appropriate message for the platform?

**Comment by SergeyZhukovsky** [comment]
@srirambv it could be replaced to anything you want but keep in mind that every string change involves extra translation to 52 languages we have on Android. I would rather keep it unchanged.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86
 - Verified that `ADD FUNDS` button in BR panel does nothing when we click on it
- Verified that  `ADD FUNDS` button is removed from `Your wallet`
- Verified that  `ADD FUNDS` button is removed from tipping banner
![Screenshot_2019-03-11-16-30-43](https://user-images.githubusercontent.com/38657976/54119469-6ae97000-441b-11e9-81b7-922e1a20170a.png)
