### ISSUE TITLE
Hide Backup & Restore Option

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1256]
## Description 
Please hide the Backup & Restore option on Android

CC @mandar-brave to confirm

**Comment by ryanml** [comment]
This is a bit of an unusual request, as I had fixed quite a few bugs for this feature. It is functional at this time, and it seems critical to be able to backup and restore a wallet even for Beta. Thoughts @anthonypkeane?

**Comment by ryanml** [comment]
Removed via: https://github.com/brave/browser-android-tabs/commit/b8bccf4aa5360c48fe90df2585b75f6b5c71dfbf

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.86
