### ISSUE TITLE
add note that wallets are managed by Uphold

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1262]
## Description 
On bc below the wallet panel on brave://rewards, it is noted that the wallets are managed by Uphold. Android should have similar messaging since currently there's no mention in the UI that the wallets are managed by Uphold.

## Steps to Reproduce 

   1. Navigate to chrome://rewards
   2. Enable, if not already enabled.
   3. Look on page, no mention.
   4. Tap on the wallet section (Your wallet which shows balance)
   5. No mention there either.

## Actual result: 
No mention of Uphold

## Expected result:
Should mention Uphold somewhere. This is what b-c looks like:
![screen shot 2019-03-07 at 5 18 57 pm](https://user-images.githubusercontent.com/28145373/53993342-21d4ab80-40fd-11e9-9b7d-a7f36b4e70be.png)

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? n/a
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone guidance

**Comment by ryanml** [comment]
Added via: https://github.com/brave/browser-android-tabs/commit/2f7dc38ef696fd18b2dc95e69a21bce3bb7a772f

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87

![Screenshot_2019-03-12-19-26-26](https://user-images.githubusercontent.com/38657976/54205677-cc354000-44fc-11e9-98e6-e8f16dd4cbf0.png)
