### ISSUE TITLE
add copy button for copying wallet addresses in Add Funds

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1264]
## Description 
On Android it's very likely that you won't have the entire wallet address displayed in Add Funds. Sometimes this is obvious, sometimes (a letter is cut off at the end of the display), sometimes it's not obvious. It would be good to have a copy button so users don't have to worry about whether they got the entire address or not.

## Steps to Reproduce 

   1. Enable rewards.
   2. Tap on panel.
   3.  Tap on Add Funds

## Actual result: 
No copy button for wallet addresses. In this case If I look closely I can see that a letter is cut off, but it doesn't always appear that way.
![1264](https://user-images.githubusercontent.com/28145373/53994824-4d599500-4101-11e9-8657-8695be014f6e.png)

## Expected result:
A copy button would be nice

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone guidance

**Comment by anthonypkeane** [comment]
Not relevant currently
