### ISSUE TITLE
Improve onboarding v0.1

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1265]
## Description 

Right now we drop users into a blank screen, we need to make this better. 

![Onboarding.gif](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/b79ef15e-3474-4d0b-ab39-412a652faa79)

@jamesmudgett can we figure out a quick solution for this before implementing a full onboarding

**Comment by jamesmudgett** [comment]
Could we inject some defaults similar to iOS?

**Comment by anthonypkeane** [comment]
@karenkliu can you come up with some ideas for this first (browsing) screen

**Comment by anthonypkeane** [comment]
closing because of NTP image
