### ISSUE TITLE
unable to see full message about how to fill wallet with tokens on small screen

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1266]
## Description 
On a smallish screen (Nexus 5) I'm unable to see the full message about how to fill my wallet. The most important part (at the moment - about getting grants) is what is hidden. 

## Steps to Reproduce 

   1. On an Android with a small screen, enable Rewards
   2. Navigate to chrome://rewards page
   3. Tap on Your Wallet section (where balance is displayed)
   4. It looks like additional text is available towards the bottom, so try to scroll.

## Actual result: 
Only able to scroll so far, even then, entire message isn't displayed. 
This is as far as I can see with scrolling:
![scroll-nexus](https://user-images.githubusercontent.com/28145373/53995391-ea68fd80-4102-11e9-8716-a0d94ddb7ff5.png)

## Expected result:
This is how this area looks on Pixel 3:
![pixel](https://user-images.githubusercontent.com/28145373/53995404-f2c13880-4102-11e9-98cc-258f634bd512.png)

This is how it looks on bc:
![screen shot 2019-03-07 at 5 18 57 pm](https://user-images.githubusercontent.com/28145373/53995414-f94fb000-4102-11e9-9c2c-67d9b30b6130.png)

## Issue reproduces how often: 
easily if phone is small

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): phone
   - Android Version: all
   
## Brave version:
1.0.85(BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone guidance

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/2f7dc38ef696fd18b2dc95e69a21bce3bb7a772f

On small devices the summary should fit with in the viewport, and you should be able to scroll all the way down.
