### ISSUE TITLE
tip banner does not display site name

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1267]
## Description 
Tip banner should display site name whether publisher is verified or not (however if a verified publisher has a custom banner, that falls under https://github.com/brave/browser-android-tabs/issues/1258). On b-c the tip banner displays site/publisher name.

## Steps to Reproduce 

   1. Enable Rewards.
   2. Visit a site (verified or not)
   3. Tap on BAT logo
   4. Tap on Send a Tip

## Actual result: 
Tip banner displays, but doesn't display site name. Here are some examples:
Google (unverified)
![google-banner](https://user-images.githubusercontent.com/28145373/53997138-0ff90580-4109-11e9-8d65-62d59ffc2dea.png)

Sampson on YT (Verified but no custom banner set up)
![sampson-banner](https://user-images.githubusercontent.com/28145373/53997132-0bcce800-4109-11e9-8fd9-024bd3b5e333.png)

## Expected result:
Site name should be displayed. 
Here's some screenshots from b-c

Google
![screen shot 2019-03-07 at 6 20 38 pm](https://user-images.githubusercontent.com/28145373/53997160-230bd580-4109-11e9-9537-ac7cb5f872ef.png)

Sampson on YT
![screen shot 2019-03-07 at 6 45 24 pm](https://user-images.githubusercontent.com/28145373/53997180-36b73c00-4109-11e9-8559-6a4ae578e246.png)

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @anthonypkeane for milestone

**Comment by gdregalo** [comment]
Long publisher name can overlap the site banner's header and doesn't look nice.

**Comment by LaurenWags** [comment]
Verified passed with 1.0.92rc1 with LG Nexus 5 on Android 5.1
- Verified that non-verified sites and YT channels display name on tip banner
![1267-nonverifiedsite](https://user-images.githubusercontent.com/28145373/56764021-bf4d7280-6771-11e9-814e-b8d79f7608c8.png)

- Verified that verified sites and YT channels display name on tip banner
![1267-verifiedYTsite](https://user-images.githubusercontent.com/28145373/56764035-c4aabd00-6771-11e9-9320-267676d7f7e6.png)

- Verified that long site names truncate nicely on tip banner
![1267-longname](https://user-images.githubusercontent.com/28145373/56764042-ca080780-6771-11e9-94b3-4012e100c43e.png)

- Unable to verify twitch due to existing issue https://github.com/brave/browser-android-tabs/issues/1301
