### ISSUE TITLE
Default browser notification doesn't dismiss even after enabling the setting

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1274]
## Description 
Default browser notification doesn't dismiss even after enabling the setting

## Steps to Reproduce 

   1. Update to 1.0.86
   2. See notification to set default browser
   3. Select Yes from notification
   4. Select Brave and select always
   5. Notification is still shown in notification area

## Actual result: 
Default browser notification doesn't dismiss even after enabling the setting

## Expected result:
Notification should be removed once user selects Brave to be default browser

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
N/A
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87
