### ISSUE TITLE
Set as Default browser should be grayed out if browser is already set

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1275]
## Description 
Set as Default browser should be grayed out if browser is already set

## Steps to Reproduce 

   1. Install 1.0.86 build
   2. Set browser as default from notification prompt
   3. Open kabob menu, `Set as default browser` option is still enabled, Clicking it show message its already set as default

## Actual result: 
Set as Default browser shows as an enabled option even when browser is made default

## Expected result:
Set as Default browser should be grayed out if browser is already set

## Issue reproduces how often: 
Easy 
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87

![Screenshot_2019-03-12-21-31-49](https://user-images.githubusercontent.com/38657976/54215721-69e53b00-450e-11e9-82c5-e417cb4d56e0.png)

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/54316310-c2701300-45b6-11e9-962a-279333035e48.png)
