### ISSUE TITLE
`ADD FUNDS` isn't functioning 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1281]
## Description 
`ADD FUNDS` isn't functioning, If its intentional hide or grayed out the button

## Steps to Reproduce 

   1. Clean profile 1.0.86
   2. Enable rewards and claim grants
   3. Click on BAT logo/BR panel in URL bar
   4. Click on `ADD FUNDS` in BR panel 

## Actual result: 
 `ADD FUNDS` button is enabled if we click the button it doesn't display anything.

![Screenshot_2019-03-11-00-41-35](https://user-images.githubusercontent.com/38657976/54090098-9d9d5500-4396-11e9-9a08-40312c1f25e2.png)

## Expected result:

ADD FUNDS popup should be displayed

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

 Please note this was working fine in 1.0.85.

**Comment by srirambv** [comment]
This is expected behaviour as part of https://github.com/brave/browser-android-tabs/issues/1255
