### ISSUE TITLE
`Insufficient funds` notification is not shown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1282]
## Description 
`Insufficient funds` notification is not shown

## Steps to Reproduce 

   1. Clean profile 1.0.86
   2. Click on BR panel
   3.  Click on 'JOIN REWARDS`
   
 
## Actual result: 
`Insufficient funds` notification is not shown

## Expected result:
`Insufficient funds` notification should be shown

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

Please note this was working fine in 1.0.85

**Comment by srirambv** [comment]
1.0.86 is set to 30 days reconcile. Hence no notification of insufficient funds. It should be visible before reconcile
