### ISSUE TITLE
once the grants notification is dismissed, user can't claim grants from Brave Rewards page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1283]
## Description 
once the grants notification is dismissed, user can't claim grants from Brave Rewards page

## Steps to Reproduce 

   1. Clean profile 1.0.86
   2. Enable rewards by clicking on `JOIN REWARDS`
   3. Dismiss the grants notification by clicking on the `x` icon
   4. Click on `Settings`

## Actual result: 
`CLAIM` button will not be shown on brave rewards page, even after multiple page reload, the button won't be shown.
https://drive.google.com/open?id=1ZEP4zpedDJQDkDmCDtPQvf7HbRtI4OYL

## Expected result:
`CLAIM` button should be available on brave rewards page and the user should be able to claim grants from BR page.

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

Please note this was working fine in 1.0.85 build.

**Comment by LaurenWags** [comment]
Reproduced with Asus Zenfone (Android 6.0) running 1.0.86 (BR_6)

**Comment by SergeyZhukovsky** [comment]
I could replicate it either. @ryanml do we need to make an extra call probably there. Or will it just appear after some time?

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/6107799f93e594ed90fec57a439dad8fbd1184c4

cc: @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) using 1.0.88 rc1
