### ISSUE TITLE
remove 'Backup your wallet' notification

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1287]
## Description 
Core has a 'Backup your wallet' notification (https://github.com/brave/brave-browser/issues/1164) that was implemented. This notification should show up 1 week after you enable BR and haven't backed up your wallet. 

Since the backup/restore functionality was removed from Android (https://github.com/brave/browser-android-tabs/issues/1256) we should remove this notification (at least for the time being) as well, it will be confusing to users otherwise. Also, since there's no way to backup their wallet, they will continually get this notification every week which will be quite frustrating.

**Comment by LaurenWags** [comment]
cc @anthonypkeane

**Comment by LaurenWags** [comment]
Received wallet backup notification with 1.0.88 on Asus Zenfone (x86)

**Comment by SergeyZhukovsky** [comment]
Fixed it here https://github.com/brave/browser-android-tabs/commit/cb593e5875fd1f513a5817e34c4f78c4f728a409
