### ISSUE TITLE
Recurring tip shows `not a date` as the date of tipping

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1289]
## Description 
Recurring tip shows `not a date` as the date of tipping

## Steps to Reproduce 

   1. Enable rewards
   2. Visit any site, send tip from br panel
   3. Set tip as monthly value
   4. Recurring monthly date is set as `not a date` 

## Actual result: 
![Screenshot_20190410-110744_Brave](https://user-images.githubusercontent.com/17010094/54135181-b9811500-43ef-11e9-844a-6a34a0becb3a.jpg)

## Expected result:
Should show proper date or mention `<date> of every month` 

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes

@anthonypkeane to prioritise the issue and assign milestone

**Comment by GeetaSarvadnya** [comment]
This is already logged. Dup of #1279
