### ISSUE TITLE
Empty banner shown when reconcile occurs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1290]
## Description 
Empty banner shown when reconcile occurs

## Steps to Reproduce 

   1. Enable rewards and claim grant
   2. Populate a-c table
   3. Wait for reconcile to happen
   4. BR panel shows an notification empty notification before showing the contribution success notification 

## Actual result: 
![Screenshot_20190415-110439_Brave](https://user-images.githubusercontent.com/17010094/54135648-9014b900-43f0-11e9-98c1-b8f1e24818d5.jpg)

## Expected result:
Should only show contribution success notification

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Tab A
   - Android Version: 8.0
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) using 1.0.88 rc1
