### ISSUE TITLE
User-Agent reveals too much information

### ISSUE THREAD

**Issue by vabole** [brave/browser-android-tabs#130]
Brave's User-Agent reveals:
* Android version, 
* phone model
* phone build 

For a privacy respecting browser that is way too much. Most of the time, those three pieces of information, combined with the IP address are enough to accurately fingerprint a user.

For comparison, Firefox for Android only reveals Android version, Orfox reveals none of the above.

I believe that a privacy respecting browser should only reveal the information necessary to render pages correctly and nothing more.

**Comment by freebrowser1** [comment]
Use agent should be configurable so the user (him|her)self can determine it.

**Comment by nexx512** [comment]
Making it fully configurable might lead to an issue that you need to update the browser version in the UA string manually on every browser update. But removing the android version and especially the system build would dramatically reduce the uniqueness for fingerprinting.

**Comment by srirambv** [comment]
+1 on Configure UA and language preferences 
https://community.brave.com/t/spoofing-user-agent-and-language-preferences/4272

**Comment by e3b** [comment]
I'm curious: Why isn't this a higher priority? Not only does this make fingerprinting easy; it also reveals which known security holes I'm vulnerable to (like those that have been disclosed and patched in the latest Android release, but not on my outdated version, or that are unique to my phone model).

Is there any way someone without coding skills can contribute to this getting fixed?

**Comment by niij** [comment]
I agree with the previous posters. Setting the UA on Android to the phone's Model+Build is just too unique. There are thousands of Android devices, so if you're not using a common one then you're leaving a pretty unique fingerprint. I vote to have the "fingerprint protection" enable a UA that respects privacy, at least while still being usable. Sending Android+Browser Version vendor seems like a good  compromise on security to me.

There's no practical reason for a privacy respecting browser to be sending my phone's model number+build in the UA string, especially when finger printing protection is turned on. 

Thank you!

**Comment by Exagone313** [comment]
I looked a bit in the code how to do it.

The `android.webkit.WebSettings` object has a method `setUserAgentString(String userAgent)` to set the *full* User-Agent as it seems.

Unfortunately I can't submit a PR because WebSettings is used at multiple places in Java, and I don't know if the C++ code would have something to do too.

Also, I don't know if the `navigator.userAgent` JavaScript object property would have to be modified as well (probably not, but do test this please).

**Comment by AnotherLife** [comment]
"Making it fully configurable might lead to an issue that you need to update the browser version in the UA string manually on every browser update."

That's a non-issue. Especially on a browser that can't play most YT embedded videos, reddit's embedded gifs, Twitter's embedded videos ...

**Comment by misaka00251** [comment]
I'm wondering too... Why isn't this a higher priority?
And why these developers don't care about that?

**Comment by Lululalu** [comment]
+1. This should be a high priority.

**Comment by flamsmark** [comment]
At the privacy meeting today, we agreed the following.

Short term: change the version/model/build to a fixed string on all devices. That continues to let us look like Chrome without revealing anything about the user device.

Medium term, if we get user reports of this breaking sites, we'll re-evaluate. @too4words & @snyderp will run some simulated tests to see if they notice anything which could indicate broken sites. If we don't see evidence of things breaking, we'll just keep incrementally updating the version strings to keep pace with a current template.

The version string we picked was an up-to-date Pixel 2, so the string should be `Mozilla/5.0 (Linux; Android 8.1.0; Pixel 2 Build/OPM1.171019.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36` — though the Chrome version should track our equivalent Chrome version.

**Comment by niij** [comment]
@flamsmark thank you!

**Comment by Lululalu** [comment]
@flamsmark Why do you need to mention a device at all? It could be like Firefox or Firefox Focus, or Orbit, no mention to device at all.

**Comment by Exagone313** [comment]
To have a User-Agent close to Chrome's one? This is just for those (bad) websites that use buggy filters based on User-Agent, don't overthink it. Using Brave will probably still be a way to fingerprint you.

**Comment by flamsmark** [comment]
@Lululalu Right now, we're trying not to look too different from Chrome. The Brave userbase is still small enough that we think being distinctively Brave makes someone stand out too much. If we didn't include anything in those parts of the UA, we'd be obviously not Chrome. Fixing that string lets us blend in with Chrome users, but without revealing any additional info or making Brave users more distinguishable from each other.

**Comment by Lululalu** [comment]
@flamsmark thank you for the explanation.

**Comment by melizeche** [comment]
@flamsmark Finally! Thank you guys for your hard work!

**Comment by MegaArthur** [comment]
So I guess we've been finally heard. Thank you.

**Comment by my-github-login** [comment]
This is great news, I resisted commenting too much on this but it's a great addition to the Android version for the reasons mentioned above. I for one have a unique phone / brave combo that on all finger printing tests I'm always the only version which isn't ideal. 

Any ideas which version this will appear in? I thought I am up to date but panopticlick is still seeing my actual phone in the user agent rather than a nexus.

**Comment by wiedzmins** [comment]
Thank you so much for reaction! I waited so long for any change in this matter that I completely forgot my Github credentials :P 
It is the critical feature for privacy. Finally! Oh :dancing_men: :dancing_women:

**Comment by Clouted** [comment]
Not only is the user agent updated for mobile, it also leaks  audiocontext here https://audiofingerprint.openwpm.com/

Despite fingerprinting protection on both in settings and as a shield. Sucks, could have been a possible solution for me if those two things were rectified.

**Comment by samartnik** [comment]
This will be fixed in https://github.com/brave/browser-android-tabs/issues/712

**Comment by MegaArthur** [comment]
How so? Amiunique.org still shows my device model and android version

**Comment by tomlowenthal** [comment]
The canonical issue for this is now #712 .
