### ISSUE TITLE
twitch.tv crashes when trying to view Desktop Site

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1300]
## Description 
When I go to twitch.tv and try to select 'Desktop Site' from hamburger menu, Brave crashes.

## Steps to Reproduce 

   1. Install 1.0.86 (BR_6)
   2. Navigate to twitch.tv, page loads
   3. Tap on hamburger menu
   4. Select Desktop site.

## Actual result: 
Get message which says 
'Unfortunately, Brave has stopped.'

## Expected result:
No crash, desktop site should open.

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no, does not reproduce on 1.0.84
   - Beta build? Yes, Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.86 (BR_6)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? no

### Additional Information
Have only experienced on the Rewards build so far, but do not need to enable Rewards to experience the crash.

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/84ae70042b74e266ec23f70ee0e877cbae27b05d

**Comment by LaurenWags** [comment]
Verified passed with 1.0.87 (BR_7) on Asus Zenfone (x86)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Android ARM - Samsung Galaxy J3 - version 5.1 - Brave version 1.0.87
