### ISSUE TITLE
Can't play videos, since few versions ago

### ISSUE THREAD

**Issue by ruiumbelino** [brave/browser-android-tabs#1304]
## Description 
Since few versions ago, I can't play videos on Brave Android.
For example, on youtube, when I open a link the video starts, but if I "TAP TO UNMUTE" the video stops and can't play anymore.
Others sites that has videos, the video can't start from the beginning.
It seems that any video with sound doesn't work.

## Steps to Reproduce 

   1. Open https://m.youtube.com/watch?v=BDWLSv2bdUA
   2. Click on "TAP TO UNMUTE"

## Actual result: 
The video stops

## Expected result:
See and listen the video

## Issue happens on: 
   - Current Playstore version? yes

## Device Details:
   - Install Type(ARM, x86): arm64
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 8.1.0
   
## Brave version:
1.0.84

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by ruiumbelino** [comment]
Some help, please.

**Comment by ruiumbelino** [comment]
I uninstall it and install it again and now works.

Thanks!

**Comment by HennyBro** [comment]
Then close this issue, please.
