### ISSUE TITLE
date format on monthly tip thank you banner

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1309]
## Description 
Date format on monthly tip thank you banner should be like that on b-c. However it is only using dd/mm/yyyy format. 

On b-c the date format matches that of your locale. So for US, the thank you tip banner uses mm/dd/yyyy format where as if you change your locale to French, you will see dd/mm/yyyy format.

## Steps to Reproduce 

   1. Be sure your language/region is set to US.
   2. Install 1.0.87 (BR_7), enable Rewards thru flag. Restart.
   3. Join Rewards. Claim grant.
   4. Navigate to a site (I used DDG).
   5. Set up a monthly recurring tip.

## Actual result: 
Thank you tip banner displays date in dd/mm/yyyy format:
![1131-monthly](https://user-images.githubusercontent.com/28145373/54237251-e4e92a00-44eb-11e9-83d9-3d572cb1490e.jpg)

## Expected result:
Date should be in format of locale, as it is on b-c. Here's how the banner displays on b-c for US:
![Screen Shot 2019-03-12 at 3 32 45 PM](https://user-images.githubusercontent.com/28145373/54237281-f7fbfa00-44eb-11e9-9291-f70adf8d3045.png)

## Issue reproduces how often: 
Easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.87 (BR_7)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
When retesting, we should check other locales to verify format matches b-c. For example, here's how the tip banner is displaying when France is used as the locale (dd/mm/yyyy format):
![Screen Shot 2019-03-12 at 15 37 23](https://user-images.githubusercontent.com/28145373/54237358-24177b00-44ec-11e9-8f45-934b01567f45.png)

**Comment by LaurenWags** [comment]
cc @anthonypkeane

**Comment by deeppandya** [comment]
@anthonypkeane @LaurenWags i would suggest to use date as **1 september, 2019** or **1 sept, 2019**. this way we can avoid date formatting specific to the region and locale. What are your thoughts ?

**Comment by anthonypkeane** [comment]
Can we not match the local @deeppandya ?

**Comment by deeppandya** [comment]
@anthonypkeane yes we can match the locale. i suggested it to keep the same date format for all regions. i checked gmail, calendar app and they show dates like it so i thought of using it. i will update this according to the region and locale.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

#### `Canada` using `YYYY/MM/DD`

![Screenshot_20191105-013302](https://user-images.githubusercontent.com/2602313/68184847-255f5180-ff6e-11e9-88b9-43ed8bb44d25.png)

#### `USA` using `MM/DD/YY`

![Screenshot_20191105-013533](https://user-images.githubusercontent.com/2602313/68184888-3f009900-ff6e-11e9-97fd-00e29049a5e5.png)

#### `France` using `DD/MM/YYYY`

![Screenshot_20191105-014106](https://user-images.githubusercontent.com/2602313/68184991-75d6af00-ff6e-11e9-812e-1b945cc18147.png)
