### ISSUE TITLE
Translation missing for reserved amount after contribution goes through

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1314]
## Description 
Translation missing for reserved amount after contribution goes through

## Steps to Reproduce 

1. Add sites to a-c list set budget to 100 BAT
2. Add a bunch of non verified pubs and verified pubs to a-c list and send tips to non verified pubs
3. Wait for reconcile to go through 
4. Wait for it to clear ac table
5. Open a site and open br panel shows "MISSING: reservedAmountText" and "MISSING:reservedMoreLink"
## Actual result: 
![Screenshot_20190411-170914](https://user-images.githubusercontent.com/17010094/54282042-76e74600-4571-11e9-879a-220507d2981c.png)

## Expected result:
Should have translations 

cc: @anthonypkeane to change milestone if required

**Comment by srirambv** [comment]
Unable to reproduce the issue. Closing for now. Will reopen if reencounter it

**Comment by srirambv** [comment]
Reopening the issue as @jamesmudgett was able to reproduce it

**Comment by SergeyZhukovsky** [comment]
Unable to reproduce it also, but that commit should fix it https://github.com/brave/browser-android-tabs/commit/757fa76dba936b033880b97f9ea8f89c79751518

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) with 1.0.88 rc2
