### ISSUE TITLE
Back button should close the wallet summary modal

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1319]
## Description 
Back button should close the wallet summary modal. Currently the modal is always shown but pages navigate back in background.

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/f213ea253887cc1d487a28b954ce8277e29f0814

The wallet summary modal is now tied to `chrome://rewards#rewards-summary`, so it can also be linked to

cc: @anthonypkeane @SergeyZhukovsky

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2

Back Button always closes Rewards Panel.
