### ISSUE TITLE
`Learn more` button hitbox in Brave Panel is too big

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#1329]
## Steps to Reproduce 

1. Enable rewards
2. Go to an unverified publisher
3. Open Brave Panel
4. Tap next to `Learn more` button

## Actual result: 
`Learn more` button hitbox extends to the width of Brave Panel

![image](https://user-images.githubusercontent.com/34715963/54313531-de38e080-45d9-11e9-90d4-de027daa8988.png)

## Expected result:
`Learn more` button hitbox is contained to `Learn more` text

## Issue reproduces how often: 
Easily reproduced

## Issue happens on: 
   - Current Playstore version? No 
   - Beta build? 1.0.88-rc.2

## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet): Samsung s7
   - Android Version: 8.0.0
   
## Brave version:
1.0.88-rc.2

cc @brave/legacy_qa @SergeyZhukovsky 

Related to https://github.com/brave/browser-android-tabs/issues/1327

**Comment by btlechowski** [comment]
Same issue on `Rewards Summery` page in Brave Panel.

Tipping an unverified publisher is needed to show that message

![image](https://user-images.githubusercontent.com/34715963/54314456-00cbf900-45dc-11e9-8ecf-28eb7e242d12.png)

**Comment by gdregalo** [comment]
Fixed
