### ISSUE TITLE
Brave 1.0.88 ruins one-handed navigation

### ISSUE THREAD

**Issue by nejsimon** [brave/browser-android-tabs#1331]
## Description 

In older versions when enabling the "duet" feature you'd have a bottom toolbar with everything needed to navigate. Brave 1.0.88 changes this toolbar and removes the button that would focus the url bar hence making one-handed, thumb, navigation impossible because reaching for the url bar with the thumb is hard with todays huge phones. It's replaced by a "new tab" button but there is a button to manage the tabs to the right so I don't see how it's useful to add another one. It's interesting that the releases notes on google play talks about "thumb only browsing is easy ..." while the release actually does the opposite.

## Steps to Reproduce 

   1. Upgrade to 1.0.88
   2. Attempt to use with one hand.

## Actual result: 
One handed navigation is difficult

## Expected result:
It would work as it did in 1.0.84 and earlier versions

## Issue reproduces how often: 
Every time until downgrading.

## Issue happens on: 
   - Current Playstore version? yes
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: Pie
   
## Brave version:
1.0.88

![brave](https://user-images.githubusercontent.com/770893/54354827-dddf2a80-4657-11e9-9257-e1f89738ee52.png)

**Comment by srirambv** [comment]
There is still some discussion being done on #1252 for having search or new tab button or have both.  You can probably add a +1 for search button there.

**Comment by miladmaz12** [comment]
I favor search and new tab button. Remove bookmarks because its easy to find and only needs 2 taps - Three dot menu ---> Bookmarks

**Comment by Brave-Matt** [comment]
@miladmaz12,
Two taps yes but both taps happen at the top of the screen which is the #1 reason users request bottom address bar to begin with (big screens). Having bms btn at the bottom makes sense to me. A simple flip/swap of new tab and search depending on state is likely the best solution

**Comment by srirambv** [comment]
Closing in favour of #1252. Lets keep all discussion on bottom bar/search button/bookmarks on the same thread
