### ISSUE TITLE
No retry logic for failed `Claim grant` process.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#1338]
## Description 
If `Claim grant` process failed by some of the technical  reasons like network connection problem, a user doesn't have a chance to retry.

## Steps to Reproduce 

   1. 
   2. 
   3. 

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version:
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Done

**Comment by srirambv** [comment]
@gdregalo @SergeyZhukovsky is there a test plan for this or just https://github.com/brave/browser-android-tabs/issues/1338#issuecomment-480466789 is sufficient? Any way to simulate the error check ?

**Comment by gdregalo** [comment]
@srirambv
There are 2 cases when:
1.  user dismiss grant notification by pressing "close" button on the panel;
2.  there was a technical problem (like network connection loss) during "Grant claiming" process.
The expected behaviour is:  a grant availability is checked every 24 hours, so in any of two cases above, the grant notification should show up on the panel again.

Testing scenario:
1. Once grant notification is visible on the panel:  close grant notification or simulate the network connection failure by turning off wifi on your device.
2.  For the second case: observe message about network connection problem on the panel.
3. Close the app.
4. Set time  >24 hours forward on your device.
5. Start application and observe grant notification is on the panel and settings page.
6. Claim grant and observe the wallet amount is topped up.

**Comment by srirambv** [comment]
* Verification passed on both scenarios. 
  - Dismissed grant notification in panel and was still able to claim via chrome://rewards
  - 24hrs check worked fine
