### ISSUE TITLE
Support accessibility labels on new bottom toolbar.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#1339]
Support long-press accessibility labels on bottom toolbar buttons. Eg. Long-press tab tray icon.

**Comment by jamesmudgett** [comment]
Should display the titles:

"Home"
"Bookmarks"
"Search"
"All Tabs"

**Comment by anthonypkeane** [comment]
Exact list TDB

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane @jamesmudgett let me know an exact list of string that be there. Right now I made such:

**Comment by anthonypkeane** [comment]
Perfect @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90-rc.2
