### ISSUE TITLE
Add chrome://rewards-internals to assist with support

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1341]
To follow Desktop: 
https://github.com/brave/brave-core/pull/1139
and also 
https://github.com/brave/brave-browser/issues/1174

**Comment by anthonypkeane** [comment]
@samartnik potentially use chrome://device-log/ to display these logs

**Comment by EyanGoldman** [comment]
Is this ticket redundant to #1341 ? If so, I'll remove one of them...

**Comment by gdregalo** [comment]
This feature is being implemented in `brave-core`. The implementation is expected to be compatible with both `desktop` and `browser-android-tabs`. Let's wait until `brave-core` implementation is merged, see how it looks on Android and then apply necessary changes if necessary.

**Comment by gdregalo** [comment]
The feature has been implemented by:
https://github.com/brave/browser-android-tabs/pull/1930 (merged into branch `base-76.0.3809.80`) and 
https://github.com/brave/brave-core/pull/3100 (merged into branch `android_76v2`).

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus 5 on Android 5.1 using 1.2.0 rc2 BraveModernarm.apk.
   - Verified when navigating to chrome://rewards-internals when Rewards was enabled shows wallet specific data similar to desktop.
   - Verified the paymentId displayed is assigned to the wallet addresses.
   - Verified when navigating to chrome://rewards-internals when Rewards are not enabled shows below screen:
![1341](https://user-images.githubusercontent.com/28145373/62950777-c054ef00-bdb6-11e9-9be8-492ca4adf886.png)
