### ISSUE TITLE
Add 2nd confirmation for destroying actions

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1342]
## Description 
Actions that destroy data should have a 2nd confirmations. 

Example, a user reports that they hit the trash icon and all their tabs disappeared. 

**Example**: https://old.reddit.com/r/brave_browser/comments/b11vfe/i_accidently_clicked_the_trash_icon_while/

**Comment by kjozwiak** [comment]
+1 from me. This screwed me a few times and accidentally removed ~100 tabs that I had opened. I needed to go through a huge cache of history to get back the important tabs that I still wanted to read/look at.

**Comment by SergeyZhukovsky** [comment]
We decided to remove it at all.

**Comment by srirambv** [comment]
* Verification passed on Pixel 3, No trash bin icon shown when tabs container is opened
