### ISSUE TITLE
Please provide an OPTION to enable/disable the new split top/bottom tool-navigation bar.

### ISSUE THREAD

**Issue by jtbrown3** [brave/browser-android-tabs#1345]
This is a significant usability departure from both prior versions and from the default Chrome mobile behavior. While I can understand that this new layout may be desirable for some users - other users like myself do not like it forced upon us.

IMHO, there should be an OPTION (in Settings->Basics ?) to turn this either ON or OFF.

**Comment by dc2629** [comment]
The biggest problem for me is that as a Samsung phone user (S8+), I typically hide the navigation buttons and they only appear when I click somewhere near the bottom. This change interferes with the navigation bar and really ruins the browsing experience.

**Comment by cryptoy** [comment]
Having both a top and bottom bar when pages load really takes a way from the browsing experience. With all these bars (I have four total bars when a page loads, 2 android and 2 brave), I am losing real-estate! I feel like I am in prison with all these bars. Please give us the option to go back to how things were.

**Comment by joseph-peace** [comment]
just came here to say that i completely agree with it being an OPTION

**Comment by Mhowser** [comment]
Please make it an option!

**Comment by bullwinkle2045** [comment]
I'd like to vote for having the location of the navigation bar being an option. I'm not a fan of having it forced to the bottom.

**Comment by benlc** [comment]
Pretty much a deal breaker for me as well. Will find a different browser until this is fixed.

**Comment by Mhowser** [comment]
You can downgrade to 1.0.84 if you want to wait out the new UI changes,
look in releases and download the modernarm.apk

**Comment by ericdunbar** [comment]
I'm with @benlc: the bottom location and the home and bookmarks buttons are almost deal breakers for me.

They really detract from the overall experience.

**Comment by lhorace** [comment]
It a lot better to bring to devs attention is by voting with the thumbs up on the OPs post.  And wait for when someone takes on the tasks.

**Comment by samueldravis** [comment]
I agree - this should be optional, or rolled back.

Usability issues: When I want to open a new tab, I want to be next to the URL bar so I can start typing to search. As it stands, I had to just figure out how the thing worked (which admittedly took a while since it is absolutely counterintuitive - Android settings are at the top) and then now have to move my hand across the entire length of my screen, which is a large screen, do to an extremely basic task. This is a really bad usability change from my perspective.

In addition, this loses another band of screen real estate, and hides the UI at the bottom of the screen until you scroll up - it is not intuitive design.

Lastly, the Brave icon is left at the top of the screen, which I have had absolutely zero reason to interact with since there is almost no reason to adjust the blocking settings on any webpage. Why is it given premium real estate when commonly used functions could be placed there?

**Comment by Riotous** [comment]
I want 3 options. This will please everybody. 

- Classic (pre-1.88)

- Bottom bar with URL bar on top (1.88) 

- Everything on the bottom, nothing on top. (for huge screens)

**Comment by heldav** [comment]
The new toolbar at the bottom of the screen is horrible. Totally support the request to make it optional. In the meantime, I'm off to find an alternative browser on Android.

**Comment by bjg222** [comment]
I think that the top/bottom distinction should be a user selectable option. There are certainly people who like nav at the bottom, especially for large screens, but it is very controversial for others, who just feel like it is a waste of screen real estate. The currently implemented solution, having the address bar at the top and menu at the bottom, feels like the worst possible compromise, because you lose both top and bottom space. For those who want the bar at the bottom, let users select to move the whole bar to the bottom. No matter what the solution, it should absolutely be optional, because the best way to alienate users is to tell them they don't have any control over the way their apps look.

Additionally, the new bottom bar doesn't obey the coloring provided by websites like the top bar does. For instance, Ars Technica colors the address bar black to match their black page (or at least, the browser colors the bar to match the page). The bottom bar ignores this, remaining a stark white color, which is really incongruous and a bit of an eye sore. Please ensure that whatever the final solution, the coloring is consistent!

![Screenshot_20190317-140926](https://user-images.githubusercontent.com/11563394/54496018-af17bd00-48c0-11e9-8e8d-9a9f4d55655b.png)

**Comment by tuomastiainen** [comment]
Please add the option and don't force the bottom bar. It is really a horrible choice. It takes up space and is prone to missclicks.

**Comment by tclaybor** [comment]
This is causing me to be unable to download files, as the "keep anyway?" prompt spawns behind the toolbar and when the toolbar hides, that prompt floats with it, meaning the buttons are still hidden.

Will be rolling back to a previous version until this can be sorted. I don't mind the bottom bar, but I need to be able to download things.

**Comment by TG-KK** [comment]
Back to using `Firefox Focus` until this setting is made optional

**Comment by Francwa** [comment]
Same request here ... and **please**, in the future, do **not** force your design choices to your users. We're in 2019, any UI/UX designer should have learned it by now.

**Comment by tclaybor** [comment]
Man, people are really upset about this.. you guys might have to refund all the money and hard work your users put into Brave... 

oh wait

**Comment by blurayne** [comment]
Another upset one. Please make this an optional feature. The feature currently does not default for Chrome or Chrome Beta. It's really counter intuitive in Brave (e.g. cannot click on when overlay from pocket does display, cannot simply add new page without first having to scroll down or switch to other pages).

At the moment this is a basic ideas.

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/dont-ruin-this-browser-please/48951/14

**Comment by jakeg** [comment]
Have reluctantly switched away from Brave. If this gets fixed I'll come straight back.

**Comment by yachtcaptain23** [comment]
@jakeg Fix is in the works per https://github.com/brave/browser-android-tabs/issues/1375

**Comment by WinstonSmithEightyFour** [comment]
This new UI is bad. Please make it optional to change back. I read this is supposed to be "better" for larger 6in screens. I have a galaxy s6 which does not have a 6in screen and my hands are suitably large to use the old way that I've been conditioned over years of use.  

Seriously considering not using chrome or other Google products

**Comment by benlc** [comment]
Thanks for the fix! Replacing the *new tab* with *search* as well as giving
the option to turn it off altogether was a good move.

**Comment by yachtcaptain23** [comment]
Option "Disable bottom toolbar" is available in the triple-dot settings to disable the browser as of 1.0.89. 

Closing.

**Comment by jtbrown3** [comment]
Thanks for listening and implementing the requested option! :)

**Comment by WulleBulle** [comment]
Chrome Version 75.0.3770.143:
There is NO option to disable anything in the settings or three dot menu. Even the disabling of the duet menu and labels in //flags doesn't change anything.

Hiow can I can rid of this stupidest chang ever in a software?

**Comment by jtbrown3** [comment]
From the settings menu, simply select appearance and then turn off the
'display bottom toolbar' toggle. This will end your frustration!

-JT   (sent from mobile device)

**Comment by bkdotcom** [comment]
@jtbrown3 

>  simply select 'Appearance' and then turn off the'Enable Bottom Toolbar' toggle. 

is there a setting to enable this Appearance option you speak of?

**Comment by WulleBulle** [comment]
@bkdotdcom
Thank u very much. I figured that if I disable both the bar will stay. I only disabled the "duet labels" and now the bar is gone. Thanks anyways.

**Comment by jtbrown3** [comment]
> @jtbrown3
> 
> > simply select 'Appearance' and then turn off the'Enable Bottom Toolbar' toggle.
> 
> is there a setting to enable this Appearance option you speak of?
> 
@bkdotcom | @WulleBulle 

Yes!  As stated previously, from any Brave browser page, tap the '**3-dot Menu**' on the top right, then tap '**Settings**', then tap '**Appearance**' (in the 'Display' section), and then you can toggle off/on the '**Enable Bottom Toolbar**' option.   it's DEAD easy!

**Comment by WulleBulle** [comment]
Thank you @jtbrown3 
Unfortunately there is no "Appearance" setting in the german version of Chrome Android, even not in german. There is no setting to disable the bottom bar at all. One have to use http://flags to disable it. This is a little unhandy but I figured to disable the flag "Duet labels" and it disabled the bottom bar for me.

**Comment by jtbrown3** [comment]
@WulleBulle 
I'm assuming that you mean Brave for Android (not Chrome).  All of my comments (and this thread) are specific to the Brave browser for Android (US version).  I'm glad you finally got rid of the annoying bottom bar.

**Comment by srirambv** [comment]
Language doesn't have to do anything with the setting. The option is available in all languages. If you are on a tablet the setting won't be available as its only for the small screen devices.

**Comment by WulleBulle** [comment]
@srirambv then I assume the setting isn't there because I am using a 6 inch smartphone.

**Comment by srirambv** [comment]
@WulleBulle  You should have an option. Please check for the setting in 
`Einstellungen -> Anzeige - Aussehen `
![Screenshot_20190723-092232](https://user-images.githubusercontent.com/17010094/61716514-543e1880-ad2d-11e9-9fa2-704ce782e34b.jpg)

Turn off that switch and relaunch to get the top bar navigation.

**Comment by WulleBulle** [comment]
Chrome Version 75.0.3770.143

Nope....no "Anzeige - Aussehen" in menu "Einstellungen".

**Comment by srirambv** [comment]
@WulleBulle You wont find this on Chrome browser. This is specific to Brave like @jtbrown3  pointed here https://github.com/brave/browser-android-tabs/issues/1345#issuecomment-514068163. 

This repo is specific for Brave Android and not Chrome Android. Please install Brave to have handy feature.

**Comment by WulleBulle** [comment]
Oh man, thank u....my fault...sry for bothering.

**Comment by bkdotcom** [comment]
heads up:  This is the page that shows up when attempting to google a solution for the Chrome browser

**Comment by Mhowser** [comment]
Could the thread title be changed to further indicate that this is about Brave, not Chrome?

**Comment by jtbrown3** [comment]
> heads up: This is the page that shows up when attempting to google a solution for the Chrome browser

Thx @Mhowser ! This explains why all of these 'off-topic' requests have been posted. I've just updated the post title to specify [Brave (for) Android].  Hopefully, Google will reindex this shortly.

**Comment by srirambv** [comment]
Well the repository is for Brave Browser on Android so its pretty much self explanatory that this is specific to Brave browser issue and not Chrome. But thanks for adding in Brave-Android in the title @jtbrown3  :+1:
