### ISSUE TITLE
Rewards GUI: please remove balloon from `Thank You` screen. Adjust  the `Site banner` header image to have nice rounded corners.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#1352]
## Description 
1. @james:  still seeing animation after tipping. Odd circle comes up from the bottom. Need to kill that entire animation, just simple fade in/out and the overlay should cover entire screen not be a circle. 
2. The header image on Site banner doesn't have rounded corners on high resolution devices. 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified with 1.0.89 on Asus Zenfone (x86). Verified on upgrade (rewards enabled prior to update) and clean installs.
![Screenshot_20190329-110710](https://user-images.githubusercontent.com/28145373/55243488-b9697d80-5215-11e9-9ac8-768c7590e51f.jpg)
![Screenshot_20190329-110717](https://user-images.githubusercontent.com/28145373/55243490-bbcbd780-5215-11e9-87e7-884fb49341b9.jpg)
