### ISSUE TITLE
bug in sync function between Desktop & Android, often Android device are removed from sync chain without any reason

### ISSUE THREAD

**Issue by sviluppoSoftware** [brave/browser-android-tabs#1354]
## Description 
from brave's Desktop version i have add an Android device to sync chain, randomly the Android device is remove from sync chain, sometimes it's removed after one day sometimes after 2 or more days

## Issue happens on 
   - Current Play Store version? 13.9.17
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet): Phone, Tablet, 
   - Android version: 8.1.0
   
## Brave version
1.0.88 and earlier

**Comment by srirambv** [comment]
Does the sync chain remain active on desktop?

**Comment by sviluppoSoftware** [comment]
yes the sync chain remain active on Desktop and i can see yet the removed android device in the list , i also tried to erase brave's cache in android setting and this no affect to the sync that remain active

**Comment by samartnik** [comment]
Steps to reproduce:
- Connect to or create Sync chain.
- Close Brave.
- Disconnect from network.
- Run Brave and go to Sync menu.

**Comment by btlechowski** [comment]
Verification passed with BraveModernarm v1.0.98-rc.1 on Samsung s7.
