### ISSUE TITLE
First Issue Test

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1361]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
LGTM 👍
