### ISSUE TITLE
Top toolbar updates.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#1369]
![Home Top Bar](https://user-images.githubusercontent.com/318119/54779941-835d4580-4be6-11e9-81c3-644c24f4ed29.png)

**Comment by jamesmudgett** [comment]
It's still important to fix the rounded corners on Android to be less round as shown above. Also, note how tabs and menu are outside of the input box.

**Comment by jamesmudgett** [comment]
Placeholder text will need to be changed to fit.

**Comment by SergeyZhukovsky** [comment]
Done

**Comment by LaurenWags** [comment]
Verified on 1.0.89 with Asus Zenfone (x86). 
![Screenshot_20190329-113034](https://user-images.githubusercontent.com/28145373/55243766-40b6f100-5216-11e9-9fcd-72b679b33707.jpg)
