### ISSUE TITLE
Tapping or adding bookmarks icon on toolbar crashes browser

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#1371]
## Description 
Users are reporting the bookmarks icon (on toolbar) sometimes causes the browser to crash or exit. Seems to be specific to the bookmarks icon on the toolbar as users have also reported being able to add bookmarks via the "more" options menu.

## Steps to reproduce 
   1. Launch Brave on Android
   2. Visit a site
   3. Tap "bookmark" icon on bottom toolbar

## Actual result 
Brave app disappears/crashes

## Expected result
Site should be added to the bookmarks list.

## Issue reproduces how often 
Easily for users, I personally am unable to reproduce the behavior.

## Issue happens on 
   - Current Play Store version? Yes v1.0.88

## Device details
   - Install type (ARM, x86): Several
   - Device (Phone, Tablet, Phablet): Several
   - Android version: Several
   
## Brave version
v1.0.88

### Additional information

User reports:
https://community.brave.com/t/cant-add-bookmarks-browser-just-closes-itself/49948
![image](https://user-images.githubusercontent.com/3299098/54785949-c7e7e180-4be4-11e9-8029-73e2ef756589.png)
![image](https://user-images.githubusercontent.com/3299098/54785989-e2ba5600-4be4-11e9-83b6-d7805a47214f.png)
![image](https://user-images.githubusercontent.com/3299098/54786015-f2d23580-4be4-11e9-9e84-59a8d7600dee.png)
![image](https://user-images.githubusercontent.com/3299098/54786045-05e50580-4be5-11e9-97da-7bff91c21028.png)

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/unfortunately-brave-has-stopped/50165?u=eljuno

**Comment by SergeyZhukovsky** [comment]
That should be fixed in the upcoming release

**Comment by LaurenWags** [comment]
Verified on Asus Zenfone (x86) - tapping bookmark icon bookmarked the page as expected, no crashes were observed.
