### ISSUE TITLE
Better organize Kabab menu

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1373]
## Description 
Following the changes to the toolbar, we have some redundancy on the main toolbar and the Kabab toolbar (bookmark icon). 
Also the Kabab menu is getting long and needs a spring clean

AK and James to finalize 

![Screenshot_20190322-135301.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/9e30f93b-5476-4bf5-9344-002668e38d83)

**Comment by anthonypkeane** [comment]
Dup of https://github.com/brave/browser-android-tabs/issues/1376

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 and OnePlus 6T running 1.1.0-6 x64 build. 
  - Bookmark icon is replaced with the share button 
  - Site info button is removed completely
  ![Screenshot_20190704-082016](https://user-images.githubusercontent.com/17010094/60683001-90cfd000-9e63-11e9-9128-d67749865081.jpg)

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 5.1.1 running BraveModernarm `v1.1.0-brave-ads-6` build
  - Verified that redundant `Bookmark` icon is removed from the kabab menu when the toolbar is set at 
    the bottom
![Screenshot_2019-07-05-00-36-40](https://user-images.githubusercontent.com/38657976/60685098-e7b6c300-9ebe-11e9-81d5-9068facac5ef.png)
  - Verified that Bookmark icon is available when the toolbar is set at the Top
![Screenshot_2019-07-05-00-38-48](https://user-images.githubusercontent.com/38657976/60685124-074deb80-9ebf-11e9-96ed-51ea03f40b59.png)
