### ISSUE TITLE
Default Browser modifications

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1374]
## Description 
Can we make the following modifications

1) Change the 15 min limit to 7 min
- this is the time when the notification first fires

2) If a user dismissed the notification (presses No), don't show it again

Make Brave your default web browser 
Save battery and load web pages faster
Yes | No

**Comment by aqeelparpia** [comment]
Hello, @anthonypkeane I would love to contribute to this issue. Could I get assigned to it?

**Comment by o-l-a-v** [comment]
Seems that Brave shows this notification every time a update is installed from Google Play. Even though I've said NO earlier, it's keeps coming. Please stop this annoying behaviour.

**Comment by EyanGoldman** [comment]
Closing as we are going in a different direction
