### ISSUE TITLE
Remove the Bookmark icon from the Kebab

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1376]
## Description 

If the bottom toolbar is enabled, the bookmark icon in the Kebab menu can be hidden and the other icons spaced out

![Screenshot_20190322-135301.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/c1a88b24-588b-4615-8cc9-cb97532c8349)

**Comment by srirambv** [comment]
Marking `QA/No` as its being verified in #1373
