### ISSUE TITLE
Organize Settings menu

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1377]
## Description 
Move "Disable/Enable bottom toolbar" into Settings under Display

Linked to: https://github.com/brave/browser-android-tabs/issues/978

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2

![Screenshot_20190408-175018_Brave](https://user-images.githubusercontent.com/34715963/55738412-6074c300-5a27-11e9-9696-84e114b81851.jpg)
