### ISSUE TITLE
Toolbar is reset to top on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1383]
## Description 
Toolbar is reset to top on upgrade

## Steps to reproduce 

   1. Install playstore build
   2. Upgrade to the 1.0.89
   3. Toolbar is on top. Default position has to be on the bottom 

## Actual result 
Toolbar is reset to top on upgrade

## Expected result
Toolbar should remain at bottom

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
No
   - Beta build?
Yes
## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 9.0
   
## Brave version
1.0.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Reproduced with Asus Zenfone (x86)

**Comment by btlechowski** [comment]
Verification passed on 1.0.89 RC2 using Samsung s7

**Comment by srirambv** [comment]
Verification passed on Pixel 3XL
