### ISSUE TITLE
Address bar polish

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#1384]
There are a couple of issues here. 

1. The address bar should have an 8px rounded corner vs a fully rounded corner. See:
![screen shot 2019-01-22 at 11 20 16 am](https://user-images.githubusercontent.com/318119/51553377-4ec44c00-1e38-11e9-923b-ed1b68533c85.png)

2. Button size (mdpi) 44x40 for both brave and bat logos. And we should add a 7px rounded corner to these.
3. The button should sit inside of the address bar and appear as shown: (selected):
![screen shot 2019-01-22 at 11 22 09 am](https://user-images.githubusercontent.com/318119/51553380-52f06980-1e38-11e9-8e80-f7372b154d38.png)

Side-by-side both buttons touch but do not overlap:
![screen shot 2019-01-22 at 11 25 23 am](https://user-images.githubusercontent.com/318119/51553425-6ef40b00-1e38-11e9-95aa-b850dd08cc6f.png)

_Originally posted by @jamesmudgett in https://github.com/brave/browser-android-tabs/issues/992#issuecomment-456486824_

**Comment by jamesmudgett** [comment]
![Screen Shot 2019-03-26 at 3 32 27 PM](https://user-images.githubusercontent.com/318119/55031681-19291400-4fdd-11e9-8f5d-c5318b071a68.png)

Sizing and alignment of icons

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc2
* Verified upgrading to 1.4.0, shields and rewards button is big and fill the URL bar completely
Playstore build:
![image](https://user-images.githubusercontent.com/17010094/65150627-83ea6380-d9f2-11e9-97dd-98c8bb2499e0.png)
Post Upgrade:
![image](https://user-images.githubusercontent.com/17010094/65151492-3838b980-d9f4-11e9-9e6b-51187f24a598.png)
* Logged follow up issue(#2076 2076) for rounded corners for button tap
