### ISSUE TITLE
Implement Cross-platform libraries

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1388]
## Description 

Implement Cross-platform libraries

https://docs.google.com/document/d/1QynlNXswjNfhxGeilooS9TjQsIPkYvgpZH8y9FJdRy4/edit#

**Comment by tmancey** [comment]
Implemented as part of https://app.zenhub.com/workspaces/browser-android-tabs-599e22723b1bbb5dc248dcc8/issues/brave/browser-android-tabs/1360 and https://app.zenhub.com/workspaces/browser-android-tabs-599e22723b1bbb5dc248dcc8/issues/brave/browser-android-tabs/1362

**Comment by srirambv** [comment]
Marking as `QA/No`. Please change if required
