### ISSUE TITLE
Reconcile doesn't reduce wallet balance

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1392]
## Description 
Reconcile doesn't reduce wallet balance

## Steps to reproduce 

   1. Enable rewards and claim grants
   2. Set budget below wallet balance
   3. Add a few verified and non verified pubs
   4. Wait for reconcile to go through 
   5. Auto contribute message shows how much BAT contributed but wallet balance remains same

## Actual result 
Reconcile doesn't reduce wallet balance

## Expected result
Wallet balance should go down

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.0.88

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Reproduced by @btlechowski 
cc: @anthonypkeane  Adding to prod milestone. Please change if required

**Comment by btlechowski** [comment]
Reproduced on Samsung s7. Brave 1.0.88.
![Screenshot_20190501-210510_Brave](https://user-images.githubusercontent.com/34715963/55190303-da8f8700-519f-11e9-85fa-232fd9f063a6.jpg)


Related issue: https://github.com/brave/browser-android-tabs/issues/1391

**Comment by srirambv** [comment]
Issue due to backend service needs to have a notification on UI to inform about the delay

cc: @mandar-brave @evq @anthonypkeane
