### ISSUE TITLE
BR Grant

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1399]
## Description 

When a user creates a BR Wallet, we currently display the below screen.

![Screenshot_20190328-124056](https://user-images.githubusercontent.com/7606853/55265843-3eb15a00-5237-11e9-8431-0e82a045963e.jpg)

This was fine when grants were made available immediately, but going forward, grants will now be provided at a delayed date.

Therefore we need to add the following:

1) where the "no activities yet this month" test it, temporary replace it with:
"Check back soon" -> exact text TDB, ping me before implementing this

This new text should show until the first grant has been made available. 
After that, that text and functionality can revert back to what is always is. 

2) When the grant is made available, the standard functionality is that a notification appears on the BAT icon. 
We might also send a push notification but @SergeyZhukovsky etc pls LMK if this is doable in a short timeframe?

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane I wouldn't touch notifications, they distract users, too much of them lately.

**Comment by anthonypkeane** [comment]
Confirmed with @mandar-brave 

![Screen](https://user-images.githubusercontent.com/7606853/55496245-70d60980-55f3-11e9-8355-3c053c2d0759.jpg)

text: Check back soon for a free token grant. 

Place the text as per the screen above.

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2

![Screenshot_20190408-174009_Brave](https://user-images.githubusercontent.com/34715963/55737494-92852580-5a25-11e9-85c3-e8c1ddcd30ba.jpg)
