### ISSUE TITLE
Some UX issues in Facebook Website while using from Brave

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-android-tabs#14]
Facebook has recently gave option to choose 5 types on like action for a post.
To choose any one among those 5 we have to hold like button for some moment and popup comes then we slightly move our thumb up and choose anyone among those 5.

In Chrome and Firefox when we move up, then Facebook Stream wont move but in Brave I feel it moves a little.

Android version (4.0, 5.0, ...?): 7.0 in Nexus 6p

Brave Version: 54.0.2795.0

**Comment by anthonypkeane** [comment]
pls check more recent build for this?
