### ISSUE TITLE
Add WebRTC block to fingerprinting protection

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#143]

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/disable-webrtc-option/1195/

**Comment by nbolt** [comment]
need this as well to be fully protected on android :+1:

**Comment by melizeche** [comment]
Just +1 here, This feature is really needed, thanks!

**Comment by samartnik** [comment]
Added
https://github.com/brave/browser-android-tabs/commit/b5c8e7b8f12257eb482283f45be72eca091727bf
