### ISSUE TITLE
Videos on msnbc.com are NOT being played

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1435]
## Description 
Videos on msnbc.com are NOT being played

## Steps to reproduce 

   1. Clean profile 1.0.90 rc1
   2. Open msnbc.com
   3. Play any video

## Actual result 

The video is not being played

https://drive.google.com/open?id=1yYhZBsTu7SjGabWM6l2MuiGjqPRh2WY6

## Expected result
Videos should play

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? no

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galxy J3
   - Android version: 5.1.1
   
## Brave version
1.0.90 rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

The issue is reported by the community
https://community.brave.com/t/videos-on-msnbc-com-not-playing-in-1-0-90/52359

**Comment by GeetaSarvadnya** [comment]
Videos are not being played on Instagram, Click on Play nothing happens, even with shield down videos doesn't play.

1+ https://community.brave.com/t/instagram-videos-do-not-play-new-issue-in-1-0-90/52273/6

**Comment by srirambv** [comment]
This is fixed in 1.0.90 RC2

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2
