### ISSUE TITLE
Get started with Rewards message shouldn't be shown if user has already opted into rewards

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1436]
## Description 
Get started with Rewards message shouldn't be shown if user has already opted into rewards

## Steps to reproduce 

   1. Install playstore build
   2. Enable rewards 
   3. Update to 1.0.91 RC build
   4. Shows message `Get started with rewards`

## Actual result 
![20190408_083334](https://user-images.githubusercontent.com/17010094/55724303-25e43980-59d9-11e9-9adb-61448e9034d6.jpg)

## Expected result
No optin or get started message if user is already opted in to rewards

## Issue reproduces how often 
Easy

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: Pixel 3XL
   
## Brave version
1.0.91

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Reproduced on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.2

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90-rc.3

**Comment by LaurenWags** [comment]
Issue still reproduces when going from 1.0.89 -> 1.0.90 rc3 for me. @btlechowski was able to repro as well. Logged follow up issue https://github.com/brave/browser-android-tabs/issues/1450
