### ISSUE TITLE
Reset Brave Rewards should be disabled if user hasn't opted into Rewards yet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1437]
## Description 
Reset Brave Rewards should be disabled if user hasn't opted into Rewards yet

## Steps to reproduce 

   1. Clean install 1.0.90
   2. Open Settings->Brave Rewards-> Reset Brave Rewards
   3. Asks to restart browser to reset rewards which is an unnecessary action as rewards isn't enabled

## Actual result 
Reset Brave Rewards should be disabled if user hasn't opted into Rewards yet

## Expected result
Only enable Brave Rewards option in settings if user has opted into rewards

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? 
N/A
   - Beta build?
Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone/Tablet
   - Android version: 8.0/9.0
   
## Brave version
1.0.90 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
I think we can close that one. As there can be some kind of rewards state when we detect is it enabled or not even wrong. That's why we have that hard reset functionality.
cc @anthonypkeane
