### ISSUE TITLE
Video codec issue

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1438]
Issue reported by @AlexeyBarabash 

Unable to play video on 
https://gif.d3.ru/kogda-ty-vegan-za-stolom-1766754/?sorting=rating

**Comment by srirambv** [comment]
Fixed in 1.0.90 RC2

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2
