### ISSUE TITLE
Auto-Contribute switch is OFF, when enable rewards from Hamburger menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1447]
## Description 
Auto-Contribution switch is OFF by default, when enable rewards from Hamburger menu

## Steps to reproduce 

   1. Clean profile 1.0.90 rc3
   2.  Enable Brave Rewards through Hamburger menu
   3.  Verify the `Auto-contribute` switch in brave://rewards page
   4.  `Auto-contribute` switch is in OFF state

## Actual result 
The `Auto-contribute` switch is in OFF state when Rewards is enabled from Hamburger menu 
## Expected result

The switch should be turned ON when Rewards is enabled from Hamburger menu or BR panel

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.0.90 rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @SergeyZhukovsky

**Comment by srirambv** [comment]
Restart browser(exit and relaunch)  fixes the issue. A-C is enabled after relaunch

**Comment by kjozwiak** [comment]
@srirambv are we going to get this fixed before enabling BR by default? Sounds like this is a regression that's currently not happening in the current release.

**Comment by srirambv** [comment]
Decision is upto @anthonypkeane and @SergeyZhukovsky . I wouldn't want to block on this as restart fixes it but would be nice to fix it.

**Comment by kjozwiak** [comment]
Only concern is that users on mobile don't tend to restart their applications that often and usually leave them running in the background for long periods of time. At least that's what I do. I don't think I've ever restarted Brave unless it crashed or I needed to restart the device.

@srirambv do moving the app in in the background for X amount of time fix this? Or is this only fixed via a restart?

**Comment by srirambv** [comment]
Leaving in background doesn't fix. It has to be a restart

**Comment by anthonypkeane** [comment]
![BR](https://user-images.githubusercontent.com/7606853/55982542-ff7b0400-5c4d-11e9-83f9-8f5898430e84.gif)

**Comment by ryanml** [comment]
This has been fixed via: https://github.com/brave/browser-android-tabs/commit/d1b402ee19a49ba09e1c23b683cf5f68f2008844

cc: @anthonypkeane @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90-rc4
