### ISSUE TITLE
Get started with Rewards message shouldn't be shown if user has already opted into rewards - follow up to 1436

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1450]
## Description 
Follow up to #1436 - issue still occurs as described

If you have Rewards enabled on playstore version (1.0.89) you should not get a notification that BR is here when updating to 1.0.90

## Steps to reproduce 

   1. Install playstore build
   2. Naivgate to chrome://flags and enable rewards
   3. Join Rewards
   4. Update to 1.0.90 RC3 build

## Actual result 
Get notification that 'Brave Rewards is here'

## Expected result
No notification, not only do you already have BR enabled, but you've opted in. Notification is unnecessary.

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.0.90 rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
Reproduced by @btlechowski

**Comment by LaurenWags** [comment]
cc @anthonypkeane @srirambv

**Comment by btlechowski** [comment]
Reproduced on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.3

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3,  BraveModernarmv1.0.90-rc.3

**Comment by samartnik** [comment]
`Rewards On` flag is set in current version from Play Store when panel is opened for 2 time. There is no way to fix it in current version. My fix will work on all the next updates.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90-rc4

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3, BraveModernarmv1.0.90-rc4

**Comment by btlechowski** [comment]
Still reproducible on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.4

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90-rc4
