### ISSUE TITLE
sometimes not prompted to Relaunch Brave to reset Rewards to pre-opt in state

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1451]
## Description 
Found while testing #1204 

If I have chrome://rewards page opened and I go to Settings > Advanced > Brave Rewards > select 'Reset Brave Rewards' - I am not always prompted to 'Relaunch Now' after confirming. 

## Steps to reproduce 

1. install 1.0.90rc3
2. Join rewards
3. populate AC table a bit
4. have chrome://rewards open in a tab
5. navigate to Settings > Advanced > Brave Rewards
6. Tap on 'Reset Brave Rewards'
7. Tap on confirm
8. You will not get a prompt notifying you that you need to restart for the changes to take effect.
9. Go to chrome://rewards page, Rewards is off, but not reset.

## Actual result 
Not prompted to Relaunch Brave

## Expected result
Prompted to Relaunch/Later.

## Issue reproduces how often 
Easily for me

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): phones
   - Android version: Reproduced on Android 5.1 and 6, but not with Android 9
   
## Brave version
1.0.90 rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
@brave/legacy_qa

**Comment by LaurenWags** [comment]
cc @anthonypkeane @srirambv

**Comment by LaurenWags** [comment]
Just to call out again separately from above - I couldn't reproduce on an ARM device running Android 9 (pixel 3 xl). I did reproduce several times (easily) on an ARM device running Android 5 and an x86 device running Android 6.

**Comment by btlechowski** [comment]
Not Reproducible on Samsung s7, Android 8.0.0 (ARM), BraveMonoarm v1.0.90-rc.3

**Comment by kjozwiak** [comment]
Sounds like it's affecting older versions of Android? I tried reproducing the above several times and got the same results as @btlechowski and @LaurenWags using Android 9. I tried the above ~15 times and got the relaunch modal every time.

**Comment by gdregalo** [comment]
There is a problem with this implementation.
If user reset BR (deleted all BR data on filesystem) and then continue without re-launching the app, then data kept in memory can be rewritten into files again or app can crash if it thinks that database or files are there but they don't exist anymore.
Solution is to re-start the app as a part of Reset action.
To do it politely we need to warn a user about it before starting the action.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/b87e5a86902b6037e3fb942af4ab0869df715892

**Comment by LaurenWags** [comment]
Verified passed with 1.0.91 on LG Nexus 5 with Android 5.1 
* Verified STR from description
* Verified when chrome://rewards page is active tab, inactive tab, or not opened in a tab at all. In each case I got the prompt to Relaunch Brave Now or Later.
