### ISSUE TITLE
Update Brave Rewards Ads Panel to show Ads is available in a given Country

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1457]
## Description 

and implement the functionality detailed in the Spec Doc re this feature. < Brave Rewards Ads Panel >

From: https://docs.google.com/document/d/1QynlNXswjNfhxGeilooS9TjQsIPkYvgpZH8y9FJdRy4/edit?ts=5c9e4b4a#heading=h.r40v0we62m2s

**Comment by jamesmudgett** [comment]
![Screen Shot 2019-05-16 at 10 29 14 AM](https://user-images.githubusercontent.com/318119/57866762-7c594a80-77c5-11e9-9b9b-6f69b1a3a8b2.png)

**Comment by anthonypkeane** [comment]
@tomlowenthal 
For devices that didn't pass SafetyNet, can the copy simply be:

> Brave Rewards and Ads are not available on your device at this time

It is simpler than the copy in the image above, which is confusing. 

Please confirm? Thanks

**Comment by tomlowenthal** [comment]
+1 on that text @anthonypkeane

**Comment by tmancey** [comment]
Closing issue as being resolved as part of #1519
