### ISSUE TITLE
Implement Ad Rewards and Claim

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1458]
## Description 
Link: https://docs.google.com/document/d/1QynlNXswjNfhxGeilooS9TjQsIPkYvgpZH8y9FJdRy4/edit?ts=5c9e4b4a#heading=h.ev516px5wv9m

@jamesmudgett Pls confirm if the panel needs any design input for this feature. 

If Yes, pls provide the design and assign the issue to the guys.

**Comment by jamesmudgett** [comment]
![Image from iOS](https://user-images.githubusercontent.com/318119/57405394-efe6d080-71a3-11e9-97dc-8cdc2c03326d.png)

Should resemble this from iOS

**Comment by NejcZdovc** [comment]
note that date shouldn't be displayed for ads grant

**Comment by tmancey** [comment]
^^^ @jamesmudgett

**Comment by jamesmudgett** [comment]
@tmancey yes remove date. Height should be the height of the rewards panel.

**Comment by jamesmudgett** [comment]
On the left we have grants, right is the new ads screen.
![Screen Shot 2019-05-16 at 10 24 28 AM](https://user-images.githubusercontent.com/318119/57866370-dd345300-77c4-11e9-81f6-ed8f3a92f35d.png)

**Comment by jamesmudgett** [comment]
![Screen Shot 2019-05-16 at 10 34 22 AM](https://user-images.githubusercontent.com/318119/57867408-b6771c00-77c6-11e9-9c74-b465ebd3cc04.png)

**Comment by jamesmudgett** [comment]
![Screen Shot 2019-05-16 at 10 38 46 AM](https://user-images.githubusercontent.com/318119/57867446-cd1d7300-77c6-11e9-8f41-3371e286209d.png)

**Comment by tmancey** [comment]
Closed ticket as create new tickets for each part of the workflow
