### ISSUE TITLE
Add SafetyNet check for Ads

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1459]
## Description 
From: https://docs.google.com/document/d/1QynlNXswjNfhxGeilooS9TjQsIPkYvgpZH8y9FJdRy4/edit?ts=5c9e4b4a#heading=h.qa2p0foauqqw

We may need to add a further Safetynet check for Ads - TBD

**Comment by tmancey** [comment]
After further investigation this ticket is no longer required as the work to detect SafetyNet status is already completed with `PrefServiceBridge.getInstance().isSafetynetCheckFailed()`
