### ISSUE TITLE
Remove the (beta) label from Sync

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1462]
## Description 
Linked to: https://github.com/brave/brave-ios/issues/1050

Please remove the (beta) label from Sync to somewhat line up with Desktop on May 14th

If https://github.com/brave/browser-android-tabs/issues/1461 is completed before hand, we can use this to notify users of Sync too

**Comment by trymeouteh** [comment]
Sync on Android does not work for me :(

I made a post on the brave forums. It works perfectly between desktops but I cannot get all my bookmarks to sync to my Android devices.

https://community.brave.com/t/sync-has-stopped-and-no-longer-syncs/49651

**Comment by HennyBro** [comment]
Sync also kinda broken for me and my Android device.

**Comment by IOI-655321** [comment]
Yeah dont remove the beta tag yet because Android sync is not working for me either.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.0.95RC2 x64 build
![Screenshot_20190520-175650](https://user-images.githubusercontent.com/17010094/58054551-e7d64b80-7b28-11e9-8613-e35f8e4548d1.jpg)![Screenshot_20190520-175733](https://user-images.githubusercontent.com/17010094/58054552-e7d64b80-7b28-11e9-8482-1de356150cea.jpg)![Screenshot_20190520-175558](https://user-images.githubusercontent.com/17010094/58054553-e86ee200-7b28-11e9-9af1-cc5f94fefac7.jpg)

**Comment by btlechowski** [comment]
Verified on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.95rc2. No sign of beta in polish.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.0.95 RC2
