### ISSUE TITLE
Welcome back message not shown on panel if rewards is enabled from chrome://rewards

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1464]
## Description 
Welcome back message not shown on panel if rewards is enabled from chrome://rewards

## Steps to reproduce 

   1. Clean install 1.0.90 rc4
   2. Enable rewards from chrome://rewards
   3. Turn off rewards
   4. Open BR panel, no welcome back message is shown

Scenario 2
   1. Clean install 1.0.90 rc4
   2. Enable rewards from BR panel
   3. Turn off rewards in chrome://rewards
   4. Open BR panel, welcome back message is shown

## Actual result 
No welcome back message on rewards panel

## Expected result
Should show welcome back message on rewards panel

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
No, On playstore build following scenario 1 , shows welcome back message after a short delay 
   - Beta build?
Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.0.90 RC4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Issue reproduced by @LaurenWags

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3 - 1.0.90 rc4

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/6ba5e48f467a57a87196f417f31d406fa3f70441

**Comment by btlechowski** [comment]
Verified on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.5. Tested both scenarios.
