### ISSUE TITLE
Insufficient funds shown immediately after ac is done

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1465]
## Description 
Insufficient funds shown immediately after ac is done

## Steps to reproduce 

   1. Set monthly budget to be below wallet balance
   2. Visit sites to add them to ac list
   3. Wait for ac to process
scenario 1: 
   4. If you are on rewards page, ac goes through no message about insufficient funds
scenario 2:
   5. If you have an active tab open when ac goes through, insufficient funds message is shown and closing that shows ac success message
scenario 3: 
   6. If you ac list page open, ac success message only shows up after you navigate back to rewards page

## Actual result 
Insufficient funds shown immediately after ac is done

## Expected result
Insufficient funds shown only be shown durin ac process when balance is below budget

## Issue reproduces how often 
Easy

cc: @SergeyZhukovsky

**Comment by fmarier** [comment]
I saw this on my phone yesterday:

![Screenshot_20190411-153806](https://user-images.githubusercontent.com/167821/56057533-dfae1380-5d13-11e9-8f88-445f217a6f44.png)

even though I have a balance:

![Screenshot_20190411-153818](https://user-images.githubusercontent.com/167821/56057561-f2c0e380-5d13-11e9-893f-590fff8b742f.png)

larger than my Auto-Contribute amount:

![Screenshot_20190411-153920](https://user-images.githubusercontent.com/167821/56057575-feaca580-5d13-11e9-87d5-194b8425a919.png)

Here's the version I'm running:

![Screenshot_20190411-174456](https://user-images.githubusercontent.com/167821/56057595-0c622b00-5d14-11e9-881e-097c90049977.png)

The other thing that's strange is that the message was shown to me yesterday even though my next auto-contribute date is tomorrow:

![Screenshot_20190411-153936](https://user-images.githubusercontent.com/167821/56057682-49c6b880-5d14-11e9-9f7c-e613700de315.png)

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/brave-core/commit/4cad8da6f744b67cdac1be37acf018e5a59e13df

**Comment by srirambv** [comment]
Verification passed on Samsung Tab running 1.0.91. Verifcation steps mentioned herehttps://bravesoftware.slack.com/archives/C0816QH3R/p1555338349189700?thread_ts=1555082213.041600&cid=C0816QH3R
