### ISSUE TITLE
Only allow grants to be claimed when rewards is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1466]
## Description 
Only allow grants to be claimed when rewards is enabled

## Steps to reproduce 

   1. Enable rewards
   2. Disable rewards
   3. Wait for grant to be available
   4. Open BR panel, ensure grant notification is shown
   5. Claim grant adds grant value in to wallet 

## Actual result 
Able to claim grant even when rewards is off

## Expected result
Should only show grant notification when rewards is off but claim only when rewards is enabled

## Issue reproduces how often 
Easy

**Comment by btlechowski** [comment]
Reproduced on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.5

**Comment by GeetaSarvadnya** [comment]
Verified passed with 1.0.92 (staging build) on Samsung Galaxy J3

**Comment by btlechowski** [comment]
I am unable to verify this issue on Samsung s7, BraveMonoarm v1.0.92(staging env).apk because the grant is immediately shown after enabling rewards(Step1). I am unable to disable rewards fast enough.

**Comment by srirambv** [comment]
* Verified on Pixel 3XL running 1.0.92(RC) build
