### ISSUE TITLE
High severity security vuln in Jinja dependency

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#1469]
From our Github security alerts:

```

Known high severity security vulnerability detected in Jinja2 < 2.10.1 defined in requirements.txt.
--
requirements.txt update suggested: Jinja2 ~> 2.10.1.

```

**Comment by diracdeltas** [comment]
More details: https://palletsprojects.com/blog/jinja-2-10-1-released/

**Comment by SergeyZhukovsky** [comment]
Fixed it here https://github.com/brave/browser-android-tabs/pull/1473

**Comment by anthonypkeane** [comment]
Closed by https://github.com/brave/browser-android-tabs/pull/1473/files
