### ISSUE TITLE
Sync should show warning not to share the code with anyone

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#1475]
Same issue as https://github.com/brave/brave-browser/issues/4132

**Comment by LaurenWags** [comment]
Be sure to check both code words and QR screens. Both screens should show the warning.

**Comment by deeppandya** [comment]
As per the discussion with @anthonypkeane, i am matching the sync text as we have in web browser. 
internal chat : https://bravesoftware.slack.com/archives/DKA4S8HPU/p1561405733002700

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 5.1.1 running BraveModernarm `v1.1.0-brave-ads-6`
  - Verified the STR from https://github.com/brave/brave-browser/issues/4132
  - Encountered #4490 and #4491
