### ISSUE TITLE
Backup notifications without backup functionality

### ISSUE THREAD

**Issue by bbondy** [brave/browser-android-tabs#1481]
## Description 

I keep getting notifications to backup my device, bu the backup option is disabled.
I think to fix it should be pretty straightforward, whatever #define or flag is gating the backup screen, we should also have it around the notification so that it's impossible for this to happen.

<img width="444" alt="Screen Shot 2019-04-18 at 10 17 00 AM" src="https://user-images.githubusercontent.com/831718/56367377-204dd700-61c3-11e9-96ff-046153916259.png">

## Steps to reproduce 

There are no consistent steps to reproduce, but I've had it happen about 6 times already on my production install. 

## Actual result 

Backup reminder is presented.

## Expected result

No backup notification since there is no functionality. 

## Issue reproduces how often 

Maybe once or twice a month?

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? No

Although it could be related to me having early builds.

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel3
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@samartnik could you suggest a test plan for this one?

**Comment by samartnik** [comment]
@LaurenWags there is no test plan for this. You just shouldn't ever receive `Backup Wallet` notification.

**Comment by LaurenWags** [comment]
ok, thanks @samartnik 

Verified did not see `Backup Wallet` notification while testing with 1.0.92 staging build.

**Comment by GeetaSarvadnya** [comment]
Verified on BraveModernarm 1.0.92 (RC1) staging build,  did not see `Backup Wallet` notification.- Tested on Samsung Galaxy J3 version 5.1.1

**Comment by srirambv** [comment]
Verification passed on Samsung Tab running 1.0.92 RC build. No backup wallet notification is shown
