### ISSUE TITLE
max ads per day of 12 on Android - follow up to brave-browser/issues/3849

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1485]
Tracker issue to test the change from https://github.com/brave/brave-browser/issues/3849

When Ads are implemented on Android we need to verify that there is a max ads per day of 12 on Android.

cc @anthonypkeane @mandar-brave - if this issue is not needed please close/label appropriately. Keep in mind, Android testing was not completed with https://github.com/brave/brave-browser/issues/3849

**Comment by LaurenWags** [comment]
Tested with 1.1.0 (https://github.com/brave/browser-android-tabs/releases/tag/v1.1.0) using LG Nexus 5. Verified I received 13 Ads instead of the expected 12. Possibly related to https://github.com/brave/brave-browser/issues/4207. General STR:
Clean install 1.1.0
Enable Rewards, set Ads to 5 per hour.
Browse normally.
After 12th Ad, I wasn't expecting any more but I got a 13th.
![Screenshot_2019-06-19-17-29-21](https://user-images.githubusercontent.com/28145373/59803089-7836b600-92b8-11e9-8866-91b3cce40148.png)

cc @tmancey @anthonypkeane

**Comment by tmancey** [comment]
@LaurenWags closing issue as this is a known issue in brave-browser and once resolved in cross platform code the fix will just appear in Android
