### ISSUE TITLE
removing "Set as default browser" from the settings menu

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#1495]
## Description 

When you already have Brave set as the default browser, you basically have a menu item that is greyed out that's completely useless and taking up space. When you view the settings menu while on a webpage, it's pretty large already, last thing we need is a menu item that is completely useless and taking up space. I personally think we should remove it from the settings page and add it somewhere within the `Settings` (not the menu).

## Steps to reproduce 

   1. Install `1.0.91 CR: 73.0.3683.90` and make Brave the default browser

## Actual result 

![Screenshot_20190422-223552_Brave](https://user-images.githubusercontent.com/2602313/56549247-428f7e00-6550-11e9-8827-a653638dd7ff.jpg)

## Expected result

We shouldn't be including a dead link/UI component in the settings menu.

## Issue reproduces how often 

100% reproducible using the STR mentioned above

## Issue happens on 
   - Current Play Store version? Yes, reproducible using `1.0.91 CR: 73.0.3683.90`
   - Beta build? N/A (haven't tried `beta` but assuming the issue is still present)

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): `Samsung S10+` & `Pixel 2 XL`
   - Android version: `Android 9`
   
## Brave version

Used `1.0.91 CR: 73.0.3683.90`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by SergeyZhukovsky** [comment]
It is done here https://github.com/brave/browser-android-tabs/pull/1734

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.0.99 x64 build
  - Verified setting Chrome as the default browser, shows the `Set default browser` option in the hamburger menu
  - Verified selecting the option from hamburger menu and setting Brave as the default browser, the option is removed from the hamburger menu
