### ISSUE TITLE
Add an action when all tabs are closed

### ISSUE THREAD

**Issue by IOI-655321** [brave/browser-android-tabs#1499]
Can we please add a default action when all tabs are closed please?

To my mind this should be to return to the homepage if setting is turned on or close brave if not.

Its annoying closing tabs and yet brave minimises but doesnt actually get closed so its still in recents.

**Comment by srirambv** [comment]
If you disable home button you can avoid this. This is only a workaround. More info here https://github.com/brave/browser-android-tabs/issues/1180
