### ISSUE TITLE
http://andro4all.com/ problem

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#15]
It doesn't work with Brave shields on.

**Comment by SergeyZhukovsky** [comment]
@garvankeeley it is a problem on iOS also. It works nice when ads and tracking switch is turned off. Also laptop works nice with that switch turned on and Android works nice when I request for a desktop version of the website. Something wrong with mobile version of the website. I am investigating it currently and let you know what rule causes it.

**Comment by garvankeeley** [comment]
Ok thanks, I'll watch this issue for updates

**Comment by SergeyZhukovsky** [comment]
On mobile version adblocker blocks that link http://b.marfeel.com/statics/marfeel/gardac.js. And after that it starts to reload the website again and again endless. Need to made some investigation in abp parser. Pending for now.
@garvankeeley

**Comment by AlexeyBarabash** [comment]
Works fine with 1.0.36 beta. Maybe filters had fixed the issue.

**Comment by SergeyZhukovsky** [comment]
We will reopen it if have problems.

**Comment by LaurenWags** [comment]
Test Plan
Navigate to http://andro4all.com/
Verify site can be viewed with shields on.
