### ISSUE TITLE
Import/Export bookmarks

### ISSUE THREAD

**Issue by Seferi** [brave/browser-android-tabs#150]
Is it possible to add an option to import and export bookmarks?

**Comment by rcpffm** [comment]
This I would like as well.
e.g.  from chrome under android to brave/android

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/export-bookmarks-android/4133/2

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/import-export-of-bookmarks-please/5232)

**Comment by lightstrong** [comment]
Please add this this feature (import / export bookmarks) to the mobile browser.

**Comment by LaurenWags** [comment]
Ability to import bookmarks from Chrome on Android is frequently requested on Google Play Store.

**Comment by MeiRos** [comment]
+1
Now it's 2nd time to me when this would be very handy feature.
Great browser anyway. :)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/cant-see-how-to-import-bookmarks/15025?u=eljuno

**Comment by JonHodgins** [comment]
+1 Would be super helpful

**Comment by dayfuaim** [comment]
Yes. :+1: (and emoji reaction).

**Comment by toddmo** [comment]
Can we have this in android as well please? Better yet, sync with pc

**Comment by LookingLost** [comment]
Same here, I just got the beta and it doesn't allow me to sync from chrome to brave, only from brave on my pc to brave on my phone or similar. I really need to transfer my hundreds of bookmarks from chrome to brave. Please implement this feature

**Comment by N8Thrasher** [comment]
One year ago still not implemented?

**Comment by laurencesmithever** [comment]
+1 for this

**Comment by LaurenWags** [comment]
+1 from community - https://community.brave.com/t/importing-bookmarks-from-dolphin-to-brave/18389

**Comment by KWottrich** [comment]
+1 for this

**Comment by chriswieman** [comment]
+1 as well. 
Having quickly searched these threads, is there currently a way to export Brave bookmarks from Android to PC, and then to one's new Android?

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/i-cannot-locate-the-import-bookmarks-button/19347?u=eljuno

**Comment by LaurenWags** [comment]
+1 from me

**Comment by maxammann** [comment]
+1

**Comment by dargor17** [comment]
+1 from me
not being able to import favourites from other browsers is really a barrier to start using this one

**Comment by Netherprovinc3** [comment]
Apparently, some people have imported bookmarks
https://www.reddit.com/r/BATProject/comments/828jfg/how_to_import_bookmarks_from_chrome_to_brave/

**Comment by eljuno** [comment]
@Netherprovinc3 that's I believe for desktop version. This issue is for Android version which have no import/export bookmarks feature. :smile:

**Comment by LaurenWags** [comment]
multiple +1s from google play store

**Comment by CyberScooby** [comment]
I am in the processing of upgrading my phone after using Brave on my old phone. Now I apparently have 4 years worth of bookmarks to export to my new phone & no way of doing that. Please we need this feature.

**Comment by fraserabrown** [comment]
+1 from me

**Comment by LaurenWags** [comment]
+1s from google play store

**Comment by sophieactual** [comment]
Phone to phone upgrade and copying bookmarks isn't a thing. Aw, c'mon guys.

**Comment by singhnp** [comment]
+1

This is invaluable, especially without desktop/mobile syncing

**Comment by neodada** [comment]
Maybe devs can look here for faster implementation?
https://github.com/bromite/bromite/blob/master/patches/BRM063_Add-bookmark-import-export-actions-in-bookmarks-activity-and-page.patch

**Comment by evdcush** [comment]
You can extract the bookmarks file yourself if you have a rooted device.

It's a json file located at:

`//data/data/com.brave.browser/app_chrome/Default/Bookmarks`


That worked for me.


You guys should also consider [Yuzu Browser](https://github.com/hazuki0x0/YuzuBrowser) or [Bromite](https://github.com/bromite/bromite), both can export and import bookmarks. I've used both and they're excellent. Bromite in particular would be a very easy switch for Brave users.

**Comment by crogs571** [comment]
Just sad in 2018 a simple think like the import/export of bookmarks is an issue. Read somewhere that it's Google putting a stranglehold on it which would make sense because they want you to use chrome. I just want a browser with tabs always showing like a desktop browser, and I'm pretty much forced to use Boat Browser which hasn't been updated in two years, and is no longer in the play store. 

@evdcush Bromite doesn't seem to let you import bookmarks. Just downloaded it, and clicking on the download icon only lets you export. Doesn't let you import. Don't think it has always showing tabs either like Dolphin or Boat. 

Guess I'm going back to sideloading Boat Browser.

**Comment by aurerua** [comment]
Until it is fully supported, is there at least a simple hacky way to do it on a non rooted Android device?
 
( I do not mInd doing it manually once in a while but it is very unpractical to not even having the option to export mobile bookmarks and import and use them in Brave on my desktop.)

**Comment by RockyJE** [comment]
> Until it is fully supported, is there at least a simple hacky way to do it on a non rooted Android device?
> 
> ( I do not mind doing it manually once in a while but it is very unpractical to not even have the option to export mobile bookmarks and import and use them in Brave on my desktop.)

I used to have a rooted device, and I would copy the (then, FireFox) SQL database and edit it using aSql Lite (from Play Store). Had to remove a bunch of fields and evenutually ended up with a simple HTML file. Not importable, but a fairly useful quick and clickable reference.

Can't remember if was able to do this with Chromium-based browsers, though. Might be worth a try...maybe 😉

**Comment by dansbandit** [comment]
Here's what I did:
used Keep and docs to export

- marked all bookmarks > move to a folder
- marked all bookmarks in the folder > open in new tab
- select the first tab
- Share... > Keep notes
- Save
- close tab
- Click the Keep icon next to Share
- Do this with all the bookmarks in the folder
- In Keep notes > Mark all the bookmarks > Copy to Google Docs
- Select open on the toast that comes up
- In Brave > delete bookmark folder

Now you got all your bookmarks with titles and urls, I did this with 40 bookmarks and it was tedious but you can press it as fast as the menus are predictable. If your android version supports it you can copy paste in a note app with the split screen function.

**Comment by diesachbearbeiter** [comment]
+1

**Comment by csagan5** [comment]
> Bromite doesn't seem to let you import bookmarks. Just downloaded it, and clicking on the download icon only lets you export. Doesn't let you import. Don't think it has always showing tabs either like Dolphin or Boat.

It supports both importing and exporting bookmarks.

**Comment by trymeouteh** [comment]
+5
Sync is buggy but in the meanwhile this can work. We have the ability to export and export our bookmarks on Brave Desktop but not on Mobile.

If this feature can get added I can simply export my bookmarks from device A, delete all the bookmarks on device B and then import my bookmarks on device B. I can use Syncthing to sync the bookmark file or even email the file to myself.

This will also be a good feature for those who travel often and want to backup their bookmarks to the cloud and are away from their desktop computer.

**Comment by srirambv** [comment]
Bumping the priority on this to P2 since there's a lot of requests and +1's on this. 

cc: @bbondy @anthonypkeane

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/browser-android-tabs/issues/150

**Comment by 1083** [comment]
Full history export would be preferable.

**Comment by osakanwolf** [comment]
Can we take Brave seriously as a mobile browser choice due to their complete disregard of this simple function available on web browsers since forever? I'm going to try Fennec.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/6378.

Any suggestions or feedback please add +1's in https://github.com/brave/brave-browser/issues/6378
