### ISSUE TITLE
Check on grants improvements

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#1503]
Add check on grants on rewards panel and settings page open event.

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/1c1044e5b6b3bd736adbffcc28a23c751f8abbce

**Comment by kjozwiak** [comment]
Verification **PASSED** using `Samsung S10+ with Android 9` using the following STR:

• clicked on the rewards panel and ensured that I received `[ RESPONSE - getGrantsCallback ]`
• clicked on `settings` within the rewards panel and ensured that I received `[ RESPONSE - getGrantsCallback ]`
• clicked on `Brave Rewards` within the hamburger menu and ensured that I received `[ RESPONSE - getGrantsCallback ]`
