### ISSUE TITLE
Google office Extension

### ISSUE THREAD

**Issue by fshuk1** [brave/browser-android-tabs#1505]
## Description 
Google Office extension doesn't work

## Steps to reproduce 

   1. Chrome Store
   2. search for Office extension
   3. Add to brave

## Actual result 
Selecting excel sheet or documents just produces a blank screen

## Expected result
An excel sheet style screen

I use

**Comment by srirambv** [comment]
Have you tried changing Fingerprint to `All device recognition allowed` in shields?

**Comment by srirambv** [comment]
This looks to be a desktop issue and not Android related. Closing in favour of https://github.com/brave/brave-browser/issues/4259
