### ISSUE TITLE
Implement IsForeground, OnForeground and OnBackground

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1512]
Implement `BackgroundHelper` for Android
Call `AdsServiceImpl::OnForeground` when the app becomes active (enters the foreground)
Call `AdsServiceImpl::OnBackground` when the app enters the background

See `ads_service_impl` class as already implemented for desktop

**Comment by srirambv** [comment]
Marking as `QA/No`. Please change if required
