### ISSUE TITLE
Implement LocaleHelper

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1513]
Implement `LocaleHelper` for Android to return the locale of the operating system, in any of the following formats `en-XX`, `en_XX` or `en_XX.UTF-8` where XX is the region, i.e. `US`, `GB`, `FR` etc.

See `locale_helper` classes.

**Comment by gdregalo** [comment]
Implemented at:
https://github.com/brave/brave-core/commit/584fdf3026a036f7e96289fbe903d2799d51536e
