### ISSUE TITLE
Implement IsNotificationsAvailable

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1518]
See `AdsServiceImpl::IsNotificationsAvailable` which currently always returns `true`, we should implement this using helper classes for each platform.

I am working on the `notification_helper` implementation in `brave-browser` under https://github.com/brave/brave-browser/issues/3651 so this ticket should be blocked until that work is complete and uplifted.

This issue is set as P3 as desktop implementation always returns `true` until the above work is completed.

**Comment by tmancey** [comment]
Test plan: Ad confirmations should not be rewarded if notifications are disabled

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.1.0-6 ads x64 build
