### ISSUE TITLE
Omnibar searches with Google return ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by dmvaldman** [brave/browser-android-tabs#152]
Switching to other search engines is fine. Entering a URL into the omnibar is fine, except if it's google.com.

![2017-02-17-125014-1](https://cloud.githubusercontent.com/assets/796394/23076752/a5cf3acc-f50f-11e6-8734-50df682d139a.png)

**Comment by 0xroy** [comment]
Same result here with two Android devices, LTE/Wifi/VPN.

Can't say since when as I don't usually use google.

**Comment by rbrewer123** [comment]
This seems to have started after the recent Brave update for me.  I see it on other websites in addition to google omnibar searches.  The problem seeme intermittent, but when it happens it does persist for a while.  Using an affected site with chrome shows no issue.

**Comment by dmvaldman** [comment]
As an update I notice this happens only when I'm on wifi and not cellular data.

**Comment by rbrewer123** [comment]
Wifi vs. cellular doesn't seem to make a difference for me.

**Comment by SergeyZhukovsky** [comment]
Thanks for letting us know, we are going to investigate that soon.

**Comment by slackerbob** [comment]
I can also confirm this on both LTE and Wi-Fi.

**Comment by bbondy** [comment]
We're working on a hotfix now.

**Comment by pjbarnoy** [comment]
Confirmed on any connection. I'm getting the same error on every Google site. Thanks for the quick response!

**Comment by SergeyZhukovsky** [comment]
Fixed it https://github.com/brave/browser-android-tabs/commit/5808e74a06595a9f82f1e38a1b177983b39a53f6

**Comment by dmvaldman** [comment]
Confirmed everything works for me on latest release (1.0.15). Thanks!

**Comment by rbrewer123** [comment]
I can also confirm the sites that were failing are now working again.
