### ISSUE TITLE
Implement Brave Ads have arrived! On-Boarding UI

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1523]
Notification Alert Tasks:

- [ ] Show notification alert in notification area for all new users or users that have never enabled Rewards
- [ ] "Brave Ads have arrived!" Copy should be used for the title
- [ ] "Get paid for viewing privacy-respecting ads." Copy should be used for the description
- [ ] Show modal (as highlighted) when the user taps the notification alert
- [ ] Should only be shown for supported regions, please see `auto is_supported_region = ads_service_->IsSupportedRegion();` in `RewardsDOMHandler::GetAdsData` on how this can be implemented

Modal Tasks:

- [x] Implement modal (We should re-use the Duck Duck Go modal as highlighted which is used when entering private mode)
- [x] "Brave Ads have arrived!" Copy should be used for the title
- [x] "Brave Rewards allows you to earn BAT via our privacy preserving Brave Ads. Try it out today!" Copy should be used for the description
- [ ] Close the modal when the user taps the "X" button
- [x] Remind the user again by showing the "Brave Ads has arrived!" notification alert after 20 opens of Brave and then again after a further 40 opens of Brave
- [x] Enable both Brave Rewards and Ads when the user taps the "Yes" button

![Screenshot 2019-05-23 at 16.12.16.png](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/a1f64a3d-7923-4842-89c9-451e4a909fb3)

Notes:

Specification available at https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit?usp=sharing

**Comment by jamesmudgett** [comment]
We should present a local notification to announce Ads release, similar to desktop. @mandar-brave @anthonypkeane could you provide the text for this?

**Comment by tmancey** [comment]
@mandar-brave @anthonypkeane desktop uses "Brave Ads has arrived!" but we will need a title and description based upon above from @jamesmudgett, could you provide asap please

**Comment by anthonypkeane** [comment]
Here is the details and copy on how we implement this notification

Link: https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit?usp=sharing


Also linked to https://github.com/brave/brave-browser/issues/4383 on Desktop

**Comment by anthonypkeane** [comment]
Hi @tmancey 
Following our call this morning, I checked the steps about and they all seem good to me, however, please take the copy from the Google Doc as the copy you have may not be up-to-date.

Re James's point re a local notification to alert that Ads have arrived, I don't think we need it as
1) We'll be placing a notification alert on the BAT icon
2) That notification needs to be disabled for users in #2 in the Google Doc

**Comment by jamesmudgett** [comment]
[https://app.zenhub.com/files/63174247/64a9d5c3-29a5-4935-bcb4-6b198f8dd726/download](https://app.zenhub.com/files/63174247/64a9d5c3-29a5-4935-bcb4-6b198f8dd726/download)

**Comment by yachtcaptain23** [comment]
Update: This should only apply for existing users who have Rewards enabled.

**Comment by anthonypkeane** [comment]
> Update: This should only apply for existing users who have Rewards enabled.

No, all users, new and existing

**Comment by yachtcaptain23** [comment]
Merged as part of https://github.com/brave/browser-android-tabs/pull/1607

**Comment by srirambv** [comment]
@yachtcaptain23 @anthonypkeane please add `QA/YES` or `QA/NO` label so that we can include it for testing

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.1.0-6 x64 ads build
  - Verified upgrading from a previous version shows in-app onboarding UI to enable rewards
  - Verified upgrading from a previous version with rewards enabled, shows in-app onboarding UI to enable ads
   ![image](https://user-images.githubusercontent.com/17010094/60621173-f318ca00-9daa-11e9-8ec7-9ce187db97e4.png)

   - Clean install without enabling ads, after min time passed, doesn't show enable ads in-app notification instead shows `Enable Brave Rewards` message (#1813 logged)

* Verification passed on Samsung Tab A running 1.1.0-6 x64 ads build
  - Verified upgrading from a previous version shows in-app onboarding UI to enable rewards
  - Verified upgrading from a previous version with rewards enabled, shows in-app onboarding UI to enable ads

* Verification passed on OnePlus 6T running 1.1.0-6 x64 ads build
  - Verified upgrading from a previous version shows in-app onboarding UI to enable rewards
  - Verified upgrading from a previous version with rewards enabled, shows in-app onboarding UI to enable ads
