### ISSUE TITLE
Build the browser with the Ads Lib

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1529]

**Comment by gdregalo** [comment]
I want to post steps provided by Terry (with minor amendments) on how to build Brave Ads in context of `browser-android-tabs`.
Today we are using branch `base-73.0.3683.90` and plan to switch to `base-74.0.3729.136-brave-ads`.

1. follow instructions at https://github.com/brave/browser-android-tabs on how to checkout and get 3rd parties libs.
2. mkdir brave/build/rustup && cd brave/build/rustup
3. wget https://s3-us-west-2.amazonaws.com/rust-pkg-brave-core/rust_deps_linux_0.1.1.gz
4. tar -zxvf rust_deps_linux_0.1.1.gz && rm rust_deps_linux_0.1.1.gz
5. cd src/third_party/android_ndk/build/tools
6. ./make_standalone_toolchain.py --arch arm --api 19  --install-dir ./arm-linux-androideabi
7. cd brave/build/rustup/0.1.1
8. "nano config" and enter the following information (change path to match your local):
`[target.arm-linux-androideabi]
linker = "/home/terrym/Documents/browser-android-tabs/src/third_party/android_ndk/build/tools/arm-linux-androideabi/bin/arm-linux-androideabi-clang"`
9.cd src/brave/build/rustup/0.1.1/bin/
10. ./rustup target add arm-linux-androideabi
11. Apply patches (attached):
- cd src && git apply src.pathc
- cd src/brave && git apply src-brave.patch
12. build:  `ninja -C out/Default chrome_public_apk`
13. It stills generates an error `Internal error occurred: Failed to find tool. Is arm-linux-androideabi-clang installed?`

The temporary solution is to add generated standalone toolchain path into the PATH env var.
export PATH=$PATH:/your path to browser-android-tabs/src/third_party/android_ndk/build/tools/arm-linux-androideabi/bin/

**Comment by srirambv** [comment]
@gdregalo @tmancey Please add `QA/Yes` or `QA/No` for the issue. If it requires some testing please add the mention the test plan
