### ISSUE TITLE
Implement OnBrowserSetLastActive and OnBrowserNoLongerActive

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1533]
See `AdsTabHelper::OnBrowserSetLastActive` and `AdsTabHelper::OnBrowserNoLongerActive` which informs Ads that a Tab has been updated.

**Comment by gdregalo** [comment]
Functions 
`OnBrowserSetLastActive and void OnBrowserNoLongerActive` are not available on Android build. 
The existing implementation of `src/brave/components/brave_ads/browser/ads_tab_helper.h/cc`relies on 
`DidFinishLoad, DidAttachInterstitialPage and OnVisibilityChanged` notifications from WebContents.
