### ISSUE TITLE
Shields get a white background when links are opened in private tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1536]
## Description 
Shields get a white background when links are opened in private tab

## Steps to reproduce 

   1. Upgrade to 1.0.93
   2. Open a link in new private tab via context menu
   3. Shields has a white background in private tab
   4. Close private tab and switch back to normal tab, shields has a gray background

## Actual result 
Shields get a white background when links are opened in private tab

## Expected result
Should not have odd background colour when switching between tabs

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? 
N/A
   - Beta build?
Yes
## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 8.0
   
## Brave version
1.0.93 RC2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional information

Step 4 is not consistently reproduced

**Comment by btlechowski** [comment]
Not reproducible on Samsung s7 (Android 8.0.0) after upgrade from PS build nor on clean profile.

**Comment by samartnik** [comment]
This is tablet specific issue, on phones it works fine

**Comment by LaurenWags** [comment]
Unable to reproduce on Asus Zenfone (x86) with 1.0.93 rc2 as well.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.0.93RC4
