### ISSUE TITLE
Append Brave/<MajorChromeVersion> to User Agent

### ISSUE THREAD

**Issue by bbondy** [brave/browser-android-tabs#1543]
So instead of:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`

We'd show:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 Brave/74`

Use the major version that is presented in the Chrome UA in the same string.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.0.95rc2(x64) build
![Screenshot_20190520-174905](https://user-images.githubusercontent.com/17010094/58054216-e48e9000-7b27-11e9-9987-2f850013c9b9.jpg)

* Verification passed on Samsung tab running 1.0.95rc2(x64) build
![Screenshot_20190520-175308_Brave](https://user-images.githubusercontent.com/17010094/58054304-2c151c00-7b28-11e9-81b4-09054003ad34.jpg)

**Comment by josozeg** [comment]
it is so bad , it is unique user agent and IP or server admin can detect our activities easily!

please back to general chrome user agent

you should delete mobile model from user agen for privacy .

if brave use unique user agent we should remove it

it is against respect privacy
