### ISSUE TITLE
Video background play options

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1544]
Currently users can enable Background video via: Settings --> Site Settings --> Media --> Background video

The setting is off by default 

This is a nice feature and is mostly hidden. Can we move this setting to" 

Settings --> Controls 
Background video playback 
Settings: On : Off slider as we have today
Default = off

Place "Controls" after "Display" in the menu 

@jamesmudgett Can we also look at adding some sort of alert box to notify the user on the feature. 

Internal Chat: https://bravesoftware.slack.com/archives/C0816QH3R/p1556631352406000
Twitter Chat: https://twitter.com/brendaneich/status/1123324213002162176?s=21

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T running 1.1.0-6 ads x64 build
![Screenshot_20190704-101836](https://user-images.githubusercontent.com/17010094/60673232-535c4a00-9e45-11e9-869f-7a8f11c01882.jpg)

**Comment by Cainuriel** [comment]
where is that in computer Browser? 
I have made a web page with a video in the background and it doesn't work in this browser

**Comment by srirambv** [comment]
>where is that in computer Browser? 

Desktop doesn't have this feature. It always supports background play. You have autoplay which stops the video from playing automatically unless its whitelisted.

**Comment by Cainuriel** [comment]
Hi Sriambv greetings from Mallorca

It is the first time that I try to develop a web page with the main browser brave. Perhaps my work is not reliable for brave, it would be logical. 
It is the only browser that does not activate the video autoplay.
works perfectly in all other browsers including Firefox

**Comment by Cainuriel** [comment]
Ok, 
the subject is being discussed:
https://github.com/brave/brave-browser/issues/3233
