### ISSUE TITLE
Crash on chrome://rewards/contribute

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#1548]
There is a crash on certain devices on that webpage when you have 5 and more websites

**Comment by GeetaSarvadnya** [comment]
- Added more than 20 sites to a-c table, verified that click on `show all sites` did not crash brave 
- Open `chrome://rewards/contribute` in both Normal tab and PT- did not crash brave
- Verified adding and deleting sites fro a-c table
- Right click on the added sites in a-c table and open them in PT tabs
- Verified changing Auto contribution settings ( added and removed sites)
- Verified enabling and disabling Auto contribution and Brave Rewards switch

Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.94-rc.1
