### ISSUE TITLE
Restore All option missing after sites have been excluded from AC

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1552]
## Description 
'Restore' link is missing from Auto Contribute panel in Rewards (clean profiles). Missing in 1.0.93 and 1.0.94. This was working in 1.0.92.

## Steps to reproduce 

   1. Install 1.0.94.
   2. Enable Rewards
   3. Add at least one site to ac table.
   4. Remove site from AC table.

## Actual result 
There is no link/option to Restore excluded sites.

## Expected result
If at least one site is excluded, there should be a link to Restore as there was in 1.0.92
![Screenshot_2019-05-16-10-00-55](https://user-images.githubusercontent.com/28145373/57859857-bfb1ba00-77c1-11e9-9c24-0cdf5fbefb0a.png)

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.0.94, 1.0.93

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
When this is resolved, QA should also check that Restore All works properly on upgrade profiles as well as clean.
Currently if you have an upgrade from 1.0.92 -> 1.0.93 -> 1.0.94, you will have the 'Restore All' link if you had excluded sites previously. But, if you exclude additional sites with 1.0.94, the count of excluded sites does not increase. If you select 'Restore All', the sites you excluded with 1.0.94 are not restored.

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3 - Brave version BraveModernarm.apk 1.0.94-rc1

**Comment by srirambv** [comment]
Reproduced on Samsung Tab as well

**Comment by btlechowski** [comment]
Reproduced on Samsung Galaxy s7, BraveModernarm.apk 1.0.94-rc1

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/c1ae7d75b2edbcb6bb82601ebf3d5502f41efb1e

Note that new behavior from brave-core is introduced via this issue: https://github.com/brave/brave-browser/issues/3459

Restore should work as expected on Android as it does on Desktop

cc: @anthonypkeane @SergeyZhukovsky @LaurenWags

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus 5 using 1.0.94 rc3. Verified:
* STR from description
* Verified when clicking on 'Restore All' site is not added back to table, revisiting site for min time adds it back to AC table
* Verified able to exclude/include via toggle on panel and site is removed or added to AC table appropriately
