### ISSUE TITLE
Remove the Brave Rewards (beta) flag

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1555]
The flag for Brave Rewards is no longer needed and can be removed.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/1492

**Comment by samartnik** [comment]
Incorrectly closed it

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 with Android 8.1.0 running 1.1.0-7 x64 ads build
  - Verified `Rewards` flag is not available on a clean install
  - Verified disabling rewards in 1.0.99 and upgrading shows `I'M IN!` in-app modal and enables rewards, and the flag is not available in chrome://rewards
