### ISSUE TITLE
Upgrading to new version `Restore all` is lost

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1556]
## Description 
Upgrading to new version `Restore all` is lost

## Steps to reproduce 

   1. Install playstore buid
   2. Visit a site and exclude it. Ensure `Restore all` button is shown in ac table 
   3. Upgrade to 1.0.94, `Restore all` is lost 
   4. Visit a new site and exclude it from list
   5. Restore all shows up with count 2
   6. Clicking restore all only restores site excluded from step 2 and not in step 4

## Actual result 
Upgrading to new version `Restore all` is lost

## Expected result
Should not lose the list of excluded sites during upgrade 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: Pixel 3XL
   
## Brave version
1.0.92 -> 1.0.93 rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @anthonypkeane to add the issue to a milestone
@ryanml @SergeyZhukovsky

**Comment by ryanml** [comment]
Fix: https://github.com/brave/browser-android-tabs/commit/e3a9623e4486b335945b91f21f4fc0af0df7eb7b

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3 - Brave version BraveModernarm 1.0.94-rc2

**Comment by LaurenWags** [comment]
@GeetaSarvadnya https://github.com/brave/browser-android-tabs/issues/1556#issuecomment-493293129 is expected afaik due to the change made with https://github.com/brave/brave-browser/issues/3459

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus 5 using 1.0.94 rc3. Verified:
* STR from description (note, encountered https://github.com/brave/brave-browser/issues/4473 as noted in https://github.com/brave/browser-android-tabs/issues/1556#issuecomment-493440999)
* Verified able to exclude/include via toggle on panel and site is removed from or added to AC table appropriately
