### ISSUE TITLE
Browser crash when trying to enable rewards

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1558]
## Description 
Browser crash when trying to enable rewards

## Steps to reproduce 

   1. Clean install 1.0.95
   2. Enable rewards either via panel/rewards page
   3. Browser crashes

## Actual result 
Browser crash when trying to enable rewards

## Expected result
Should not crash but just enable rewards

## Issue reproduces how often 
Easy on both x86 and x64 builds

## Issue happens on 
   - Current Play Store version?
N/A
   - Beta build?
Yes
## Device details
   - Install type (ARM, x86): ARM/ARM64
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1
   
## Brave version
1.0.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by samartnik** [comment]
Wrong lib was used during build. Created new proper build on Jenkins https://github.com/brave/browser-android-tabs/releases/tag/v1.0.95-rc.2

**Comment by btlechowski** [comment]
Verified on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.95rc2
