### ISSUE TITLE
Https text is cut off after viewing a page with insecure connection icon in URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#156]
How it looks when secure padlock icon is shown
![image](https://cloud.githubusercontent.com/assets/17010094/23204393/589b45c0-f8de-11e6-8133-65a257ddafcd.png)

How it looks when insecure connection icon is shown
![image](https://cloud.githubusercontent.com/assets/17010094/23204419/6fd39210-f8de-11e6-9d42-dd1d06ac17e8.png)

How secure connection looks after viewing insecure connection icon on a tab
![image](https://cloud.githubusercontent.com/assets/17010094/23204455/8c3ba640-f8de-11e6-8a54-7d3f5867fa31.png)

**Comment by freebrowser1** [comment]
These so-called 'insecure' sites should be able to be whitelisted, particularly when these point to local IP addresses (such as 127.0.0.1, 192.168.x.x, or legacy ::1, FE80:xxxx).

**Comment by srirambv** [comment]
This is fixed with new icon assets implemented. Closing the issue
