### ISSUE TITLE
Set Default browser option still shows up when Brave is already set as default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1560]
## Description 
Follow up to #1275 , Set Default browser option still shows up when Brave is already set as default. Its occupying unwanted space on the menu so it should be removed. Only show the option when Default browser is not set or a different app is set

## Steps to reproduce 

   1. Install Brave
   2. Set it as default browser
   3. Open menu, see grayed out entry occupying space in menu list

## Actual result 
![Screenshot_20190520-111502](https://user-images.githubusercontent.com/17010094/58032413-8eeac100-7af0-11e9-8edf-90d69e019956.jpg)

## Expected result
Only show the entry when default browser is not set or a different app is set. Remove entry when Brave is set as default browser

## Issue happens on 
   - Current Play Store version?
Yes
   - Beta build?
Yes
## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet):  All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
That is a dup of https://github.com/brave/browser-android-tabs/issues/1495

**Comment by srirambv** [comment]
Removing milestone as #1495 is already shipped.
