### ISSUE TITLE
(Techdebt) Investigate to see if OnClick specific for Android is appropriate

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/browser-android-tabs#1563]
## Description 
The Android implementation on ad_service_impl.cc introduces OnClick as a way to handle deep links rather than the current OpenSettings used by desktop. Goal is to figure out if this solution is correct.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Closing issue as will be picked up as part of code review
