### ISSUE TITLE
"Ads Settings" has incorrect Copy and does not set ads per hour

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1569]
Tasks:

- [ ] Change "adsPerHour" Copy to "Maximum number of ads displayed"
- [ ] Change "adsPerHour1" Copy to "1 ad per hour"
- [ ] Change "adsPerHour2" Copy to "2 ads per hour"
- [ ] Change "adsPerHour3" Copy to "3 ads per hour"
- [ ] Change "adsPerHour4" Copy to "4 ads per hour"
- [ ] Change "adsPerHour5" Copy to "5 ads per hour"
- [ ] `AdsServiceImpl::SetAdsPerHour` should be called upon Ads initialization passing the chosen ads per hour value
- [ ] `AdsServiceImpl::SetAdsPerHour` should be called when changing Ads Per Hour in the UI passing the chosen ads per hour value

Notes:

See `RewardsDOMHandler::SaveAdsSetting` for how to call `AdsServiceImpl::SetAdsPerHour`

![Screenshot 2019-05-23 at 09.22.27.png](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/78102807-6dfa-43cd-91f4-f1340f9b33e3)

**Comment by anthonypkeane** [comment]
This will be the same as on Desktop
Cc @mandar-brave  if you want something else here



<img width="357" alt="Screen Shot 2019-05-21 at 1 13 35 PM" src="https://user-images.githubusercontent.com/7606853/58127506-5e775580-7bca-11e9-9b79-9af2cd53f104.png">
