### ISSUE TITLE
3rd party cookie setting is not respected at site level

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#157]
- Steps to repro

1. Set app level setting to allow 3rd party cookie
2. Visit https://jsfiddle.net/7ke9r14a/9/
3. Verify local storage and session storage count is set to 0 (count =1)
4. Enabled Block 3rd party cookie at site level
5. Local and session storage count is set to 00 (count =2)

**Comment by SergeyZhukovsky** [comment]
Fixed it https://github.com/brave/browser-android-tabs/commit/88df3b2a2e85218fb2bbf6f314ac896083dada1c
