### ISSUE TITLE
When the device is asleep and Brave is running in the background, Ad got View confirmation even though the screen doesn't wake up (Android Lollipop)

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/browser-android-tabs#1570]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Once an Ad notification has been added to the notification list the Ad will be confirmed as a  View. I believe this is working as expected as when a user on Android then taps this Ad in the notification area then this would be confirmed as a Click.

@mandar-brave @anthonypkeane your thoughts please? If you agree we can just close this ticket as `Wont fix`

**Comment by tmancey** [comment]
Working as expected, closing ticket
