### ISSUE TITLE
Brave keeps crashing after updating to latest 1.0.14

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-android-tabs#158]
Brave keeps crashing after updating to latest 1.0.14. The app can't start at all. 
I've tried to uninstall and reinstall the app, it still has the same problem.

Phone: Moto X 2014 (2nd gen)
Android Version 6.0
Brave version 1.0.14

**Comment by felipeas** [comment]
1.0.15 Is live on play store for me, it fixed this issue.

Strangely i can't find the release on: https://github.com/brave/browser-android-tabs/releases

Maybe it was just a rollback?

**Comment by onmyouji** [comment]
Probably, the release date is Jan 19

https://github.com/brave/browser-android-tabs/releases/tag/v1.0.15

**Comment by SergeyZhukovsky** [comment]
@felipeas @onmyouji  yep it is a rollback https://github.com/brave/browser-android-tabs/releases/tag/v1.0.15
We are working on the new one that is not a rollback https://github.com/brave/browser-android-tabs/releases/tag/v1.0.16RC1. It will be live next week.
