### ISSUE TITLE
Rewards Settings: Implement Ads grants UI

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1582]
Tasks:

- [x] Implement "Ads earning (30 BAT) is available" UI (as highlighted)
- [x] Earnings should reflect claim
- [x] Allow user to claim grant protected by SafetyNet (please discuss with @gdregalo as he is working on the business logic for claiming an Ads reward)
- [x] Show an activity indicator while waiting for the server to process the claim
- [x] If the SafetyNet check succeeds show "Congrats!" popover

- [x] Implement "Congrats!" popover UI (as highlighted)
- [x] Ads rewards should reflect claim
- [ ] Rewards period should reflect payment period
- [x] Allow user to close popover by tapping the "OK" button

Notes:

See claiming of token grants and "It's your lucky day!" which have already been implemented

![57866370-dd345300-77c4-11e9-81f6-ed8f3a92f35d.png](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/ddbe0b56-a31a-4876-8075-d13e51e81ba1)

![57867408-b6771c00-77c6-11e9-9c74-b465ebd3cc04.png](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/6a2033b7-e2bd-4eec-96af-ace157a04d08)

**Comment by petemill** [comment]
TODO:
- [ ] missing strings (earningsClaimDefault)
- [ ] alternate grant text
- [ ] 'Rewards period' section
- [ ] Month in text
- [ ] Internationalize
