### ISSUE TITLE
Wallet balance should be limited to 1 decimal value

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1583]
## Description 
Wallet balance should be limited to 1 decimal values similar to desktop

## Actual result 
![20190523_083741](https://user-images.githubusercontent.com/17010094/58253669-f2fec680-7d36-11e9-92bf-bf22680c9c4e.jpg)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/58253722-0e69d180-7d37-11e9-85a6-8ca313944bbc.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
Yes
   - Beta build?
Yes
## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1
   
## Brave version
Playstore version 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @SergeyZhukovsky @ryanml

**Comment by GeetaSarvadnya** [comment]
Reproduced in BraveModernarm 1.0.96 - Samsung Galaxy J3

![Screenshot_2019-06-04-14-14-49](https://user-images.githubusercontent.com/38657976/58865447-31e83100-86d4-11e9-816d-6d68c6915e9c.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A and OnePlus 6T with Android 9.0 running 1.4.0 RC4 x64 build

**Comment by srirambv** [comment]
Dupe of #1964
