### ISSUE TITLE
Unable to enable ads on Android 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1584]
## Description 
Unable to enable ads on Android 

## Steps to reproduce 

   1. Install the ads build
   2. Ads is not auto enabled
   3. Try enabling manually, doesn't work

## Actual result 
Unable to enable ads on Android 

## Expected result
Ads should auto enable when rewards is enabled. Even if it doesn't user should be able to manually enable/disable ads

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone(Huawei P20)
   - Android version: 8.1.0
   
### Additional information

cc: @petemill @tmancey @anthonypkeane @SergeyZhukovsky

**Comment by tmancey** [comment]
@srirambv Ads is not ready for testing on Android, we will provide a build soon for testing to begin. Recommend to close this ticket, thanks
