### ISSUE TITLE
Turn off rewards shows coming soon text for ads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1585]
## Description 
Turn off rewards shows coming soon text for ads

## Steps to reproduce 

   1. Enable rewards on ads build
   2. Turn off rewards
   3. Ads shows `Coming soon` text instead of ads info text 

## Actual result 
Turn off rewards shows coming soon text for ads

## Expected result
Should show the ads info text when ads is turned off when its avialable

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone (Hauwei P20)
   - Android version: 8.1.0
   
## Brave version
Ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

cc: @petemill @ryanml @SergeyZhukovsky @samartnik @anthonypkeane

**Comment by tmancey** [comment]
Fixed and will be on next QA build

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 and One Plus 6T both running 1.1.0 x64 ads build 5
