### ISSUE TITLE
double paymentId in logs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1591]
## Description 
Observed that after enabling Rewards, a device will get a paymentId and then almost immediately get a second paymentId which results in different wallet addresses. If you send BAT to the first one, they are lost as you cannot recover that wallet.

## Steps to reproduce 
pre-req: make sure any previous logs are cleared out.
   1. Install 1.0.95 and monitor logs.
   2. Enable Rewards
   3. Search logs.

## Actual result 
You will have two different paymentIds

## Expected result
One paymentId

## Issue reproduces how often 
Consistently

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? probably

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.0.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Confirmed seeing the same in @GeetaSarvadnya logs she shared in channel.

@GeetaSarvadnya if you want to try again to confirm that would be great 😄

**Comment by LaurenWags** [comment]
reproduced by @kjozwiak on a newer device, so not limited to older ones as originally thought. Thanks!

**Comment by SergeyZhukovsky** [comment]
Fixed it here https://github.com/brave/brave-core/pull/2497

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Tested again, I am also seeing two payment ID's in the logs.

**Comment by srirambv** [comment]
QA Blocked on #1621

**Comment by GeetaSarvadnya** [comment]
Verification passed tested in Samsung galaxy J3 against the Android build BraveModernarn.apk - 1.0.96-beta.2
- Verified that there is only one payment id displayed in logs
- Verified that able to send funds to the wallet
