### ISSUE TITLE
Hide https:// or  http:// on Android URL bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1592]
## Description 
I'd like to hide https:// or  http:// in the URL bar as it takes up a lot of space.

Keep the lock icon to indicate https however. 

User Feedback: https://twitter.com/__jakub_g/status/1132018510782238720

@tomlowenthal LMK what you think?

**Comment by diracdeltas** [comment]
> I'd like to hide https:// or http:// in the URL bar as it takes up a lot of space.
> 
> Keep the lock icon to indicate https however.

this is what iOS Brave does right now btw

**Comment by tomlowenthal** [comment]
I think we're okay to swap the string `🔒https://` with just `🔒`. I think we should also do a similar warning/danger treatment for insecure HTTP connections, like substituting `http://` for `🔓⚠️`. But I think we should probably have a design pass at how angry and warning that visual can be. Lots of red for sure, though. [And we should have the same indicators on iOS and Android, if possible.]

**Comment by anthonypkeane** [comment]
> I think we're okay to swap the string `🔒https://` with just `🔒`. I think we should also do a similar warning/danger treatment for insecure HTTP connections, like substituting `http://` for `🔓⚠️`. But I think we should probably have a design pass at how angry and warning that visual can be. Lots of red for sure, though. [And we should have the same indicators on iOS and Android, if possible.]

We should just do the same as on iOS
Show a 🔒 for https
don't show anything for http

tapping on the URL shows the full URL with https or http

**Comment by srirambv** [comment]
We might want to consider adding the the title mode in addition to this. Muon had the title mode on desktop by default and could be turned off to have the full URL bar. This is especially helpful with small screen devices where user has enabled rewards. Having both shields and rewards button inside URL bar on a small screen is already a problem.  

Personal +1 for having red coloured unlock icon or entire URL in red  for http sites

cc: @jamesmudgett @bbondy

**Comment by tomlowenthal** [comment]
I think we need a separate discussion about our negative connection security UI.

**Comment by tomlowenthal** [comment]
For now, fine to match the Chrome/desktop behavior. We'll have an updated security indicator spec at some point, but not blocking this.

**Comment by jumde** [comment]
From internal discussion 4 indicators are neeeded:

1. good secure origin (HTTPS, valid cert)
2. non-secure origin
3. internal/settings
4. pin-failures, safebrowsing warning and cert errors

cc: @diracdeltas @tomlowenthal @anthonypkeane

**Comment by deeppandya** [comment]
@anthonypkeane @jumde @tomlowenthal Chromium is updated with just showing icons instead of http schemes with chromium-77 update. So i think for this issue, it make sense to update the icons for brave. can someone verify this ?

**Comment by diracdeltas** [comment]
@deeppandya i think the only thing to do here is to use Brave's icons instead of Chrome's. we are all onboard with not showing http/https in the URL bar.

**Comment by deeppandya** [comment]
Currently we use these icons. 



![omnibox_info](https://user-images.githubusercontent.com/5146988/67888933-fca51980-fb73-11e9-9813-7af3fd318723.png)
![omnibox_search](https://user-images.githubusercontent.com/5146988/67888934-fca51980-fb73-11e9-8403-fa4c1af3dceb.png)
![omnibox_https_valid](https://user-images.githubusercontent.com/5146988/67888935-fd3db000-fb73-11e9-9936-cef6d2cd31e3.png)
![omnibox_https_invalid](https://user-images.githubusercontent.com/5146988/67888937-fd3db000-fb73-11e9-88da-b61fcaf77642.png)

**Comment by tomlowenthal** [comment]
The unlock one should be red, and we should have a red ⚠️-style icon for HTTPS errors like `https://expired.badssl.com`.

**Comment by deeppandya** [comment]
@jamesmudgett would it be possible for you to provide me the icons @tomlowenthal is suggesting ? i will update it right away.

**Comment by anthonypkeane** [comment]
@jamesmudgett  ^^ ping

**Comment by jamesmudgett** [comment]
[address bar.zip](https://github.com/brave/browser-android-tabs/files/3805487/address.bar.zip)

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2248

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.0rc2 BraveModernx86.apk
![1592-1](https://user-images.githubusercontent.com/28145373/68396520-b0437600-013f-11ea-9b08-3c5e9f53f202.png)
![1592-2](https://user-images.githubusercontent.com/28145373/68396525-b174a300-013f-11ea-8d78-4c2f88795740.png)
![1592-3](https://user-images.githubusercontent.com/28145373/68396528-b33e6680-013f-11ea-8655-0719d4e5b269.png)

**Comment by szaimen** [comment]
Sry for beeing off-topic but I think for dark mode is the standard https icon a bit too dark.

**Comment by LaurenWags** [comment]
cc @jamesmudgett to address https://github.com/brave/browser-android-tabs/issues/1592#issuecomment-551101852

**Comment by tomlowenthal** [comment]
It looks like the warning sign and the open padlock are flipped. The warning sign is for broken HTTPS (pin failures, or `wrong.host`). The open padlock is for any regular HTTP site.

**Comment by kjozwiak** [comment]
> It looks like the warning sign and the open padlock are flipped. The warning sign is for broken HTTPS (pin failures, or `wrong.host`). The open padlock is for any regular HTTP site.

Can you please create a new issue as this one was already shipped via `1.5.0 CR: 78.0.3904.90`.

**Comment by srirambv** [comment]
@szaimen its not just an issue on darkmode its also on light theme. Please check #2287
