### ISSUE TITLE
Ad notifications are removed from the notification drawer after 2 minutes

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1608]
## Steps to reproduce 

   1. Enable Ads
   2. Visit www.brave.com
   3. Wait for 30 mins for an Ad notification to be shown (if settings are set to 2 ads per hour, see Additional Information on how to reduce the wait time)
   4. Wait a few minutes

## Actual result
Ad notification is removed from the notification drawer

## Expected result
Ad notification should not be removed from the notification drawer

## Issue reproduces how often
Easily reproducible

## Issue happens on 
   - Current Play Store version? No
   - Beta build? No

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel3 Phone
   - Android version: 9
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
You speed up Ad notifications you can temporarily change:
```
uint64_t start_timer_in =
    base::Time::kSecondsPerHour / ads_client_->GetAdsPerHour();
```

to

```
uint64_t start_timer_in = 30;  // Ad notification will be shown every 30 seconds
```

in `AdsImpl::StartDeliveringNotifications`

**Comment by LaurenWags** [comment]
Reproduced with Brave_ads2.apk except they're gone from notification try in seconds without me removing them. I see the notification, it minimizes to the tray, and then it disappears from the tray.

**Comment by GeetaSarvadnya** [comment]
The issue is Reproduced with `Brave_ads2.apk`. Notification is getting dismissed/removed from the notification tray after few seconds
