### ISSUE TITLE
Ads earning and ad view count momentarily flashes when pull down reload the ads setting page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1610]
## Description 
Ads earning and ad view count momentarily flashes when pull down reload the ads setting page

## Steps to reproduce 

   1. Enable rewards/ads on ads build
   2. Click on ad notificaion to visit the landing page
   3. Go to ads setting page, shows 0 ads viewed and 0.00 BAT as ad earning
   4. Pull down reload the page, momentarily ads viewed and earning flashes before resetting to 0

## Actual result 
![android_ads](https://user-images.githubusercontent.com/17010094/58650388-8a868b00-82dc-11e9-9e46-5779537f25bc.gif)

## Expected result
Should not show 0 when an ad is viewed

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab/Huawei P20
   - Android version: 8.1.0
   
## Brave version
Ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus running 1.1.0 ads-6 build (Android 6 - BraveModernARM.apk)
