### ISSUE TITLE
Update Play Store screenshots in Ad regions 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1618]
Update Play Store screenshots in Ad regions 

cc @jamesmudgett

**Comment by anthonypkeane** [comment]
We need to show how the Ad notification works

**Comment by karenkliu** [comment]
We currently have 5 screenshots prepared; the last one talks about Brave Rewards/ads:

![Slide 5](https://user-images.githubusercontent.com/2388823/58819553-7b664c80-85fe-11e9-9f01-957474b4f74e.jpg)

@anthonypkeane are you suggesting that we add a 6th one showing the actual notification in a screenshot?

**Comment by anthonypkeane** [comment]
Going to pause this for the moment until we revisit all the play store images

**Comment by anthonypkeane** [comment]
closing as onboarding will cover this
