### ISSUE TITLE
brave unique user agent can cause privacy leak

### ISSUE THREAD

**Issue by josozeg** [brave/browser-android-tabs#1619]
you have add brave on user agen ,

 it is so bad , it is **unique** user agent and ISP or server admin can detect our activities easily!

please back to general chrome user agent

you should delete mobile model from user agen for privacy also.

if brave use unique user agent we should remove it

it is against respect privacy

**Comment by Allespro** [comment]
Good idea to add swither, chrome or brave agent

**Comment by tomlowenthal** [comment]
Covered in #712
