### ISSUE TITLE
Unable to load: /src/third_party/inspector_protocol/inspector_protocol.gni

### ISSUE THREAD

**Issue by SheldonLaw** [brave/browser-android-tabs#162]
Hello，when I try building this project with the command "ninja -C out/Default chrome_public_apk"。

I get the error below. And I can't find /third_party/inspector_protocol/, how can I fixed that? thx.

FAILED: build.ninja 
/home/wade/browser-android-tabs/src/buildtools/linux64/gn --root=/home/wade/browser-android-tabs/src -q gen .
ERROR at //content/browser/devtools/BUILD.gn:6:1: Can't load input file.
import("//third_party/inspector_protocol/inspector_protocol.gni")
^---------------------------------------------------------------
Unable to load:
  /home/wade/browser-android-tabs/src/third_party/inspector_protocol/inspector_protocol.gni
I also checked in the secondary tree for:
  /home/wade/browser-android-tabs/src/build/secondary/third_party/inspector_protocol/inspector_protocol.gni
See //content/shell/BUILD.gn:449:13: which caused the file to be included.
  deps += [ "//content/browser/devtools:resources" ]
            ^-------------------------------------
ninja: error: rebuilding 'build.ninja': subcommand failed

**Comment by SergeyZhukovsky** [comment]
@CODE-FOR-INTEREST what OS do you use for the build? It support Linux only currently. Did you run getThirdParties.js script? It should grab all third parties on that command.

**Comment by CODE-FOR-INTEREST** [comment]
Ubuntu 16.04，I had built chromium successfully before. So OS is not the key point, I guess.

When I run the command in getThirdParties.js，it break when execute ‘gn args out/Default’

Waiting for editor on "/home/wade/browser-android-tabs/src/out/Default/args.gn"...
Generating files...
ERROR at //content/browser/devtools/BUILD.gn:6:1: Can't load input file.
import("//third_party/inspector_protocol/inspector_protocol.gni")
^---------------------------------------------------------------
Unable to load:
  /home/wade/browser-android-tabs/src/third_party/inspector_protocol/inspector_protocol.gni
I also checked in the secondary tree for:
  /home/wade/browser-android-tabs/src/build/secondary/third_party/inspector_protocol/inspector_protocol.gni
See //content/shell/BUILD.gn:449:13: which caused the file to be included.
  deps += [ "//content/browser/devtools:resources" ]
            ^-------------------------------------

**Comment by SheldonLaw** [comment]
@SergeyZhukovsky 
Has something to do with yarn?
I only install yarn and do nothing but run 'sh scripts/getThirdParties'

**Comment by SheldonLaw** [comment]
Hi @SergeyZhukovsky , I find [issues 109](https://github.com/brave/browser-android-tabs/issues/109) is similar to this issues, and I got your commit [Added needed files](https://github.com/brave/browser-android-tabs/commit/10cfe97fc587a824cad39d293b955d6d41245440).

Is this helpful to you? THX again.

**Comment by SergeyZhukovsky** [comment]
@SheldonLaw probably it is something that was added by Chromium on latest stable version. I attached the folder with it, could you please put it inside your third_party folder and try? 
[inspector_protocol.zip](https://github.com/brave/browser-android-tabs/files/821483/inspector_protocol.zip)

**Comment by SheldonLaw** [comment]
@SergeyZhukovsky thx, I will try tomorrow.

**Comment by SheldonLaw** [comment]
@SergeyZhukovsky THX, I built successfully after add your inspector_protocol files. May be you should add something to README or rm /third_party/inspector_protocol in .gitignore. 

Anyway, THX again.
