### ISSUE TITLE
Rewards page is blank on upgrade and clean install

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1621]
## Description 
Rewards page is blank on upgrade

## Steps to reproduce 

   1. Upgrade to 1.0.96
   2. Open rewards page
   3. Completely blank page, reload doesn't show anything

## Actual result 
![Screenshot_20190602-185511](https://user-images.githubusercontent.com/17010094/58768354-047e7480-8568-11e9-9c11-c744024ebbea.jpg)

## Expected result
Should show rewards page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20 
   - Android version: 8.1.0
   
## Brave version
1.0.96 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

### Additional information

Same result on upgrade or clean install

**Comment by btlechowski** [comment]
Reproduced on Samsung s7, BraveMonoarm v1.0.96-beta.1

I already experienced blank page before: https://github.com/brave/browser-android-tabs/issues/1468

**Comment by GeetaSarvadnya** [comment]
Verification passed on both upgraded and clean profile. Verified in Samsung galaxy J3 against the Android build BraveModernarn.apk - 1.0.96-beta.2
