### ISSUE TITLE
Enabling rewards shows please try again later message

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1622]
## Description 
Enabling rewards shows please try again later message

## Steps to reproduce 

   1. install playstore build
   2. enable rewards via panel
   3. `Please try again later` message flashes when wallet is created 

## Actual result 
![Screenshot_20190601-094500](https://user-images.githubusercontent.com/17010094/58768654-a86a1f00-856c-11e9-92a7-bb219a86c3a0.jpg)

## Expected result
Should not show any try again message 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20 
   - Android version: 8.1.0
   
## Brave version
1.0.95 Playstore build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Dont remember seeing this in previous build. could be server delays.

**Comment by samartnik** [comment]
I'm not able to reproduce this. @LaurenWags @btlechowski could you try to reproduce this?

**Comment by LaurenWags** [comment]
@samartnik was able to reproduce on LG Nexus 5 running Android 5.1 and 1.0.95, but only when enabling from panel. Not when enabling from chrome://rewards page.
![Screenshot_2019-06-03-11-41-06](https://user-images.githubusercontent.com/28145373/58815044-deeb7c80-85f4-11e9-9e0b-4b9cce52077a.png)

**Comment by samartnik** [comment]
@srirambv @LaurenWags @btlechowski could you check it on version 1.0.96. It should be fixed by this commit https://github.com/brave/brave-core/commit/8dce0d8f8b242f6303e11f5aaa390a0ffe1d211c

**Comment by btlechowski** [comment]
Reproduced on Samsung s7  (Android 8.0.0) on 1.0.95 when enabling rewards through Rewards Panel. 
The `Please try again later.` message is shown at the bottom of the screen.

![Screenshot_20190603-174829_Brave](https://user-images.githubusercontent.com/34715963/58815517-07409e80-8628-11e9-8275-9938c3c1db5c.jpg)

Not reproducible when enabling through `brave://rewards`.

**Comment by srirambv** [comment]
@samartnik yes i don't see the message when installing 1.0.96. Closing the issue as its related to #1591 with double payment id's.
