### ISSUE TITLE
Staging flag should set ads to staging as well. Follow upto #1540

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1626]
As a follow up to #1540 , setting rewards flag to staging should also make ads to point to staging server. This way we would avoid scenario where rewards is set to staging but ads is pointing to prod and we wont see any ads at all. 

cc: @SergeyZhukovsky @samartnik @tmancey 

@anthonypkeane  marking this to 1.0.97 as we need to have the capability of switching prod/staging for ads as well for testing.

**Comment by tmancey** [comment]
This issue is resolved in C75, however C75 is not ready for testing yet, I will let you know when it is.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.1.0 x64 ads 5 build
  - Verified switching between production and staging worked fine
  - Verified wallet on both production and staging is correct when switched to the corresponding environment

* Verification passed on OnePlus  running 1.1.0 x64 ads 5 build
  - Verified switching between production and staging worked fine
  - Verified wallet on both production and staging is correct when switched to the corresponding environment
