### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1631]
## Description 
Remove Brave UA for the short term, but ensure we keep any existing partner headers

QA, we need to double check existing partner headers to make sure they still work

https://github.com/brave/browser-android-tabs/issues/1543

cc @SergeyZhukovsky

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.0.96 RC. 
![Screenshot_20190605-123737_Brave](https://user-images.githubusercontent.com/17010094/58974006-5f45e500-878f-11e9-967c-d3f06beef393.jpg)
