### ISSUE TITLE
Switching between staging and prod causes panel to show Welcome back message

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1634]
## Description 
Switching between staging and prod causes panel to show Welcome back message

## Steps to reproduce 

   1. Clean install or upgrade to 1.0.96 beta
   2. Ensure you have wallet enabled on production
   3. Switch wallet to staging 
   4. Click rewards panel to join rewards
   5. Shows `Welcome back` message as though rewards was turned off
   6. Close panel and reopen, still shows the same message
   7. Close and reopen browser, shows correct join rewards message on panel

## Actual result 
Switching between staging and prod causes panel to show Welcome back message
https://drive.google.com/file/d/1oBdxRkJxlli0Re93S48sENyT9hu2yInk/view?usp=sharing

## Expected result
Should not show welcome back message when switching between staging/prod. Should always show the correct welcome/join rewards page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20
   - Android version: 8.1.0
   
## Brave version
1.0.96 Beta2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

@SergeyZhukovsky @anthonypkeane Would like to have this fixed in 1.0.96 if the fix is simple. Not sure how it will affect the wallet creation process when switching. Wouldn't want to block release on this but definitely needs to be fixed

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 using BraveModernarm v1.0.96-beta.2.

![Screenshot_20190605-031518_Brave](https://user-images.githubusercontent.com/34715963/58923559-7a3d3880-8740-11e9-9c0a-d09c11442768.jpg)

**Comment by GeetaSarvadnya** [comment]
- Verification PASSED on Samsung Galaxy J3 - Android ARM version 5.1.1 using 1.0.97
   - Verified on both clean and upgraded profile

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.0.97 RC3 
  * Verified on both clean install and upgrade from 1.0.95
