### ISSUE TITLE
Trash icon is overlapping on Remove text in Tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1636]
## Description 
The trash icon is overlapping on Remove text in Tips panel

## Steps to reproduce 

   1. Clean profile 1.0.96-beta.2
   2. Send monthly recurring tips to few verified and non verified sites
   3. Open Tips panel

## Actual result 
The trash icon is overlapping on Remove text in Tips panel

![Screenshot_2019-06-04-18-17-43](https://user-images.githubusercontent.com/38657976/58885521-fe230080-86ff-11e9-84a5-e4b3150e83a7.png)

## Expected result
Trash icon should not be overlapped on Remove text in Tips panel

## Issue reproduces how often 

Easy
## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.0.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @ryanml

**Comment by srirambv** [comment]
This is an issue only when you have Media publisher on tips. Here's one without media publisher no problem with long domain name
![Screenshot_20190604-101127](https://user-images.githubusercontent.com/17010094/58886176-744c4680-86b1-11e9-9b60-778bc8ff8387.jpg)

And here's one with media publisher which includes `on Youtube` . Will be a problem when Twitch pubs start getting as well
![Screenshot_20190604-101506](https://user-images.githubusercontent.com/17010094/58886325-b07fa700-86b1-11e9-828d-d1da9ce51d70.jpg)

**Comment by EyanGoldman** [comment]
Getting a different result when trying it on a MotoX... Double "On Youtube" in the text. 
![Screenshot_2019-07-17-12-44-00](https://user-images.githubusercontent.com/8962135/61406532-e4451380-a890-11e9-940a-aaa4de4a0954.png)

**Comment by LaurenWags** [comment]
@EyanGoldman that's logged under https://github.com/brave/browser-android-tabs/issues/1229

**Comment by EyanGoldman** [comment]
cc @ryanml @petemill

**Comment by anthonypkeane** [comment]
@ryanml would you be able to pick up this one also?

**Comment by anthonypkeane** [comment]
@ryanml would you be able to work on this one?

**Comment by GeetaSarvadnya** [comment]
For some unverified sites also the trash icon is overlapping on remove text in tips panel - Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.7.0-rc1

![image](https://user-images.githubusercontent.com/38657976/72524492-0fcca900-3888-11ea-955a-f35a2ffba1e1.png)

**Comment by srirambv** [comment]
@GeetaSarvadnya please test this on beta once native UI is done.
