### ISSUE TITLE
 Favicon is not displayed in BR panel for `youtubestock` verified pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1637]
## Description 
 Favicon is not displayed in BR panel for `youtube stock` verified pubs. Favicon is displayed properly in Tips panel and auto contribution table.

## Steps to reproduce 

   1. Clean profile 1.0.96-beta.1
   2.  Open https://www.youtubestock.com/
   3.  Open BR panel and verify favicon 

## Actual result 
 Favicon is not displayed in BR panel for `youtubestock` verified pubs

## Expected result
![Screenshot_2019-06-04-16-54-31](https://user-images.githubusercontent.com/38657976/58886465-91a90100-8701-11e9-88f4-77056cfcd671.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.0.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @SergeyZhukovsky

**Comment by gdregalo** [comment]
Often publishers have small favicons which don't scale well and don't look nice on high resolution devices. For example: `ctv.ca`. Please check the attached picture where 16*16 favicon is shown.
The `youtubestocks.com` have also favicon with size of 16*16 px, but it scales better then one from above.
![Screenshot_20190722-124028](https://user-images.githubusercontent.com/37560650/61650461-c9541400-ac81-11e9-8500-633a610156bc.jpg)
![Screenshot_20190722-124040](https://user-images.githubusercontent.com/37560650/61650462-c9541400-ac81-11e9-87d2-010b9b01f955.jpg)

It was decided to show only favicons which have size greater or equal then 64*64 pixels and use fallback icons when size is smaller.
Please comment if you have other ideas how to handle it right.

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane @EyanGoldman I think we are good with that ^. We don't show it as it is a low quality icon that looks blurred.

**Comment by EyanGoldman** [comment]
@SergeyZhukovsky will close in that case.
