### ISSUE TITLE
Sometimes swipe navigation causes multiple toolbar items to be highlighted

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1641]
## Description 
Sometimes swipe navigation causes multiple toolbar items to be highlighted

## Steps to reproduce 

   1. Open a bunch of tabs
   2. Swipe navigate between tabs on the toolbar
   3. Sometime when you swipe left/right, search and bookmark buttons gets highlighted 

## Actual result 
![Screenshot_20190604-181646](https://user-images.githubusercontent.com/17010094/58917775-bbf4c180-86f5-11e9-9f77-2adeb54f355a.jpg)

## Expected result
No buttons should get highlighted unless pressed

## Issue reproduces how often 
Some what easy

## Issue happens on 
   - Current Play Store version? No. Not reproduced on Pixel 3XL
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20
   - Android version: 8.1.0
   
## Brave version
1.0.96 Beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Found an easy way to reproduce this. Just tapping between home button and bookmark makes both bookmark and search button highlight. Here's the recording https://youtu.be/qb7jYPNEoYk

**Comment by GeetaSarvadnya** [comment]
Reproduce on Samsung Galaxy J3 version 5.1.1 - verified on Brave 1.0.97

![Screenshot_2019-06-07-23-03-14](https://user-images.githubusercontent.com/38657976/59122580-be1a8280-8978-11e9-82bd-cb23a75c4452.png)

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running
  - Verified tapping in between home button and bookmark button doesn't highlight the multiple toolbar items
  - Verified able to tap on home button and the tap is registered every single time

**Comment by samartnik** [comment]
Reopening as current fix removed highlights.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.0.97 RC3. Closing the issue as #1666 should have closed it
