### ISSUE TITLE
Crash after Ad Grant Claim

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1643]
## Description 
An Ads Grant was available, I accepted it and Brave crashed

## Steps to reproduce 

   1. Open the rewards panel
   2. Claim the grant (ads grant)
   3. enter settings
   4. tap the contribution screen

## Actual result 
Brave crashed

## Expected result
Contribution table should work and open

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 9
   
## Brave version
https://github.com/brave/browser-android-tabs/releases/tag/untagged-c1eb35c8a76bb3af9772

## Logs
[Log.txt](https://github.com/brave/browser-android-tabs/files/3258130/Log.txt)
![Crash](https://user-images.githubusercontent.com/7606853/58973979-23eaec80-8776-11e9-94b8-1b19fc24783d.gif)

**Comment by tmancey** [comment]
@anthonypkeane @mandar-brave speaking with @gdregalo grants have not been deployed to production servers, when we shortly move to C75 bump this will allow you to enable staging environment. George is checking code as it should be defensive and not crash but grants will not work on production until deployed.

**Comment by gdregalo** [comment]
Related: https://github.com/brave/browser-android-tabs/issues/1548
Fixed: https://github.com/brave/browser-android-tabs/commit/b44db76a5907952010bdf6be98ea1b63b4110d65

**Comment by tmancey** [comment]
@anthonypkeane @mandar-brave ^^^
