### ISSUE TITLE
Group notifications 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1644]
Group all ads notifications into one instead of many lions occupying the half of the notification bar.
(https://developer.android.com/training/notify-user/group)

Internal Chat
https://bravesoftware.slack.com/archives/CJVNBPK9P/p1559751775023800
https://bravesoftware.slack.com/archives/C0816QH3R/p1565210305041000

**Comment by yachtcaptain23** [comment]
Relevant PR: https://github.com/brave/browser-android-tabs/pull/1645

**Comment by tmancey** [comment]
@jenn-rhim @jamesmudgett @mandar-brave Your thoughts on grouping of Ad notifications on mobile?

**Comment by anthonypkeane** [comment]
Moving into the icebox for now.
Will judge feedback and adjust as needed

**Comment by EyanGoldman** [comment]
Closed as this is being replaced by #1932
