### ISSUE TITLE
Android *rooted* extracting open tabs

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [brave/browser-android-tabs#1650]
Hello, I'm trying to write a little script to extract the URL's from the files in the open tabs folder.

Now there is some random byte sequences I'm unable to identify, the actual url, and then the ref link. Now how would you extract just the url?
Or at least remove the parts of the file which is that unrecognizable byte stuff?

**Comment by hp8wvvvgnj6asjm7** [comment]
| "https://en.m.wikipedia.org/wiki/Transfer_entropy%1C%00%00%00T%00r%00a%00n%00s%00f%00e%00r"
-- | --


my extracted urls look like that, there is constantly this % stuff in it...

**Comment by hp8wvvvgnj6asjm7** [comment]
k—OÍ               ø  ô      D   https://en.m.wikipedia.org/wiki/Kendall_rank_correlation_coefficient0   K e n d a l l   r a n k   c o r r e l a t i o n   c o e f f i c i e n t   -   W i k i p e d i a Ì  È     À                              `       X               è               ð              è       Â7°Š Ã7°Š (      @                       D   h t t p s : / / e n . m . w i k i p e d i a . o r g / w i k i / K e n d a l l _ r a n k _ c o r r e l a t i o n _ c o e f f i c i e n t                             8      0       8           ~Ví?                                                  L                                                       B   https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient      ÷yŸÏè.     È            (     ÿÿÿÿÿÿÿÿ ÿêìð     (

**Comment by yachtcaptain23** [comment]
Not a relevant issue to Brave Android Browser. Closing.
