### ISSUE TITLE
Crash on opening Search engine settings

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#1653]

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `Pixel 2 XL` running `Android 9` using `1.0.97 CR: 75.0.3770.67`
  * ensured that tapping `Standard Tab` & `Private Tab` doesn't crash the browser in regular mode
  * ensured that tapping `Standard Tab` & `Private Tab` under PB doesn't crash the browser
  * ensured that changing the default search engines doesn't crash the browser
  * clicked through `Passwords`, `Payment methods`, `Addresses and more`, `Notifications`, `Homepage`, `Appearance`, `Privacy`, `Brave Rewards`, `Sync`, `Accessibility`, `Site Settings`, `Languages`, `Downloads`, `About Brave` and ensured that the browser doesn't crash
