### ISSUE TITLE
Bottom toolbar ignores some touch inputs 

### ISSUE THREAD

**Issue by mthomos** [brave/browser-android-tabs#1657]
## Description 
Using the latest brave (play version is free from this bug), when I press home or search from bottom toolbar, it many times it ignores the touches 

## Steps to reproduce 

   1. Open a website 
   2.  Press home or search 

## Device details
   - Install type (ARM, x86): Arm64
   - Device (Phone, Tablet, Phablet): Xperia XZ1
   - Android version: 9.0
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by srirambv** [comment]
Could be similar to #1641. 

cc: @samartnik

**Comment by LaurenWags** [comment]
+1 from https://community.brave.com/t/bug-on-brave-android-version-1-0-97-377007032/64255

**Comment by karkas20** [comment]
> +1 from https://community.brave.com/t/bug-on-brave-android-version-1-0-97-377007032/64255

My smartphone : Redmi note 7 Xiaomi

I install and test this version for my android : Version: 1.0.97 (377007032) 
arm64-v8a + armeabi-v7a

**Comment by LaurenWags** [comment]
thanks @karkas20  - I can reproduce easily with the home button on my device (Asus Zenfone) as well.

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3 version 5.1.1 - verified on brave 1.0.97

**Comment by LaurenWags** [comment]
Verified passed with 1.0.97rc2 on Asus Zenfone (x86).

**Comment by karkas20** [comment]
> Verified passed with 1.0.97rc2 on Asus Zenfone (x86).
> Verification passed with BraveModernarm v1.0.97-rc.2 on Samsung s7.
> 
> * Verification passed on Huawei P20 running 1.0.97 RC2
Hi 

When is the stable and fixed home icon touch  bottom toolbar version released?

I check google play store and see version 1.0.95 for install

**Comment by srirambv** [comment]
@karkas20  This is still not available on playstore. We are still testing the fix for it.

**Comment by btlechowski** [comment]
Verification passed with BraveModernarm v1.0.97-rc.3 on Samsung s7.
