### ISSUE TITLE
Chrome incognito icon inside private tab url

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1658]
## Description 
Chrome incognito icon inside private tab url

## Steps to reproduce 

   1. Install 1.0.96/97 build
   2. Open a private tab
   3. URL shows Chrome's incognito icon instead of info icon

## Actual result 
Chrome incognito icon inside private tab url

## Expected result
Should not show any chromium icons 

## Issue reproduces how often 
Easy 

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone only 
   - Android version: 8.1.0
   
## Brave version
1.0.97

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with 1.0.97rc2 on Asus Zenfone (x86).
