### ISSUE TITLE
Settings > Site settings issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1659]
## Description 
Gaps display in Settings > Site Settings. Also, `Desktop Mode` option is missing.

## Steps to reproduce 

   1. Navigate to Settings > Site Settings.
   2. Compare available Settings to those from 1.0.95.
   3. 

## Actual result 
Gaps in list, but only `Desktop Mode` appears to be missing. 
![Screenshot_20190607-095949](https://user-images.githubusercontent.com/28145373/59110436-22076180-890d-11e9-8d03-a1dfd22c7587.jpg)

![Screenshot_20190607-100000](https://user-images.githubusercontent.com/28145373/59110442-25025200-890d-11e9-951f-eb00112923ea.jpg)

## Expected result
No gaps in the list, all options from 1.0.95 should be available in 1.0.97.

This is what Settings > Site Settings looks like in 1.0.95:
![Screenshot_20190607-095703](https://user-images.githubusercontent.com/28145373/59110475-39dee580-890d-11e9-9861-775a1f6bab34.jpg)

![Screenshot_20190607-095709](https://user-images.githubusercontent.com/28145373/59110486-3d726c80-890d-11e9-9908-801a8cb33bb6.jpg)

## Issue reproduces how often 
Reproduces in 1.0.96 and 1.0.97.

## Issue happens on 
   - Current Play Store version? no, not in 1.0.95
   - Beta build? 

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.0.96, 1.0.97

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome?  No Gaps on Settings > Site Settings on Chrome 75.0.3770.75. However, Desktop Mode is not an option on either Chrome 74 or 75. Chrome 75 does have options in Settings > Site Settings that Chrome 74 does not have.

### Additional information
cc @brave/legacy_qa

**Comment by anthonypkeane** [comment]
Reproduced on my OnePlus Android 9

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.0.97 RC3

**Comment by GeetaSarvadnya** [comment]
Verification passed with BraveModernarm v1.0.97-rc.3 on Samsung Galaxy J3 version 5.1.1
