### ISSUE TITLE
Tap on buttons in bottom bar/kabab menu doesn't show visual indication of tap

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1664]
## Description 
Tap on buttons in bottom bar/kabab menu doesn't show visual indication of tap

## Steps to reproduce 

   1. Install 1.0.97 RC1 build
   2. Tap on any button in toolbar or kabab menu
   3. No tap indication shown. Kabab menu items have tap highlight only when you tap and hold 

## Actual result 
Tap on buttons in bottom bar/kabab menu doesn't show visual indication of tap

## Expected result
Should show visual feedback of any button that is tapped

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20
   - Android version: 8.1.0
   
## Brave version
1.0.97 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed with BraveModernarm v1.0.97-rc.3 on Samsung Galaxy J3 version 5.1.1
