### ISSUE TITLE
Disable  Motion Sensors by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1669]
## Description 
Disable  Motion Sensors by default

## Steps to reproduce 

   1. Upgrade to 1.0.96/97
   2. Open site settings
   3. Motion Sensors is enabled by default

## Actual result 
Motion Sensors enabled by default

## Expected result
Motion sensors disabled by default

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1.0
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `Samsung S10+ using Android 9` using `1.0.97 RC4 CR: 75.0.3770.67`
   * ensured that `Motion sensor` under `Site settings` is `Blocked` by default
