### ISSUE TITLE
Google account access request with every boot

### ISSUE THREAD

**Issue by Seferi** [brave/browser-android-tabs#167]
Brave requests a Permission to access the google account after every boot.. Even tho i denied it a several times. Is it possible to make the decision stick?

**Comment by SergeyZhukovsky** [comment]
@Seferi unfortunately we cannot replicate that. Could you please tell us what device do you use?

**Comment by Seferi** [comment]
Oneplus 2 , Android 7.1.1, LineageOS

**Comment by SubhrajyotiSen** [comment]
I am facing the same issue too. On OnePlus X running 7.1.1

**Comment by r0peburn** [comment]
Same here. Nexus 5X, 32 GB, Android 7.1.1, stock OS (unrooted), Nova Launcher Prime

**Comment by Seferi** [comment]
Looks like its a 7.1.1 specific issue..

**Comment by pjobson** [comment]
Same issue here, I'm on 7.1.2 Nexus 5X using stock ROM.  I have two accounts on my phone, Brave always wants access to both of them.

**Comment by srchulo** [comment]
Same issue here on Google Pixel.

**Comment by ckempo** [comment]
Same here, Nexus 7 2013 on Lineage (7.1.2), Nexus 5X stock (7.1.2) and a Wileyfox Swift 2 Plus stock (7.1.1). Have always denied the request, partly because there's absolutely no justification for why access is being asked for (some comments here suggest the devs don't even know that Brave is asking though).

**Comment by SourceBoy** [comment]
It seems to be coming from the identity permission when auth token is requested from Android's Account Manager? I'm more interested in knowing why Brave is requesting it, how/what it's used for, and where the data is transmitted to if collected.

**Comment by lobstaj** [comment]
Any news on this? Happens for me on every boot on Android 7.1.1 .

Why is it mentioned that this is "Discussed at Brave Community"? There's not much to discuss, brave asks for permissions and nobody knows why :-D It sounds like it just needs to be fixed...

**Comment by nickbudi** [comment]
I have this issue as well on the Google Pixel.

Could it be that Google sync integration isn't completely removed? I see the option to sign into my Google account when `chrome://flags/#enable-chrome-home` is enabled

**Comment by SourceBoy** [comment]
@lobstaj It's being discussed so the developers can have more information to identify the cause and eventually fix it. Development works by 1. Reporting issues. 2. Identifying cause(s) of issue(s). 3. Fixing the issue(s)

@nickbudi My guess is it's coming from the identify permission via getAuthToken() in the source code, which triggers the Account Manager to prompt the "access request" notification/screen.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/96e11eef5eed4d5da6aa9559bfb7cd7f59bd7858

**Comment by SubhrajyotiSen** [comment]
Finally!!!

**Comment by SourceBoy** [comment]
one-liner.
