### ISSUE TITLE
Disable auto-contribute doesn't hide the separators in BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1671]
## Description 
Disable auto-contribute doesn't hid the separators in BR panel

## Steps to reproduce 

   1. Enable rewards 
   2. Turn off auto contribute
   3. Open any site and click on BR panel
   4. Shows send tip button
   5. Click on send tip and set a monthly recurring tip 
   6. Open rewards panel again, shows two separators which should ideally be hidden where the a-c details are shown

## Actual result 
![Screenshot_20190610-152224_Brave](https://user-images.githubusercontent.com/17010094/59223113-2182fb00-8b99-11e9-8528-d77d0ce18263.jpg)

## Expected result
No separators should be shown if ac is diabled

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes, @kjozwiak confirmed it
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1.0/ 8.0
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

 cc: @ryanml @anthonypkeane added to 1.0.99 please move it if required

**Comment by kjozwiak** [comment]
> Current Play Store version? Yes, @kjozwiak confirmed it

Example of the issue occurring on `1.0.95 CR: 74.0.3729.157` using `Samsung S10+ with Android 9`:

![Screenshot_20190610-160241_Brave](https://user-images.githubusercontent.com/2602313/59223738-b803ec00-8b9a-11e9-903a-63e4ed26aac6.jpg)

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.0.97-rc.3 on Samsung s7.

![Screenshot_20190610-221433_Brave](https://user-images.githubusercontent.com/34715963/59223846-41341680-8bcd-11e9-8c91-3f10a7be41cc.jpg)

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.1.0-6 x64 ads build.
  - Verified steps from the original issue description

* Verification passed on Huawei P20 running 1.1.0-6 x64 ads build.
  - Verified steps from the original issue description

* Verification passed on OnePlus 6T running 1.1.0-6 x64 ads build.
  - Verified steps from the original issue description
