### ISSUE TITLE
Port chrome://rewards-internals/ from desktop to Android and add ads logging

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1676]
Port the functionality from chrome://rewards-internals/ to android

Put logging in that page to help diagnose ad issues. 

What ad data will be logged needs to be defined. 
cc @alexwykoff for this part.

**Comment by alexwykoff** [comment]
Related issue from desktop : https://github.com/brave/brave-browser/issues/3538

**Comment by jsecretan** [comment]
We want this to be a 1000 line circular buffer of what would normally come along with `--vmodule=brave_ads=3` on command line logging.  And it should also log region whether or not supported as that is relevant to debug.

**Comment by anthonypkeane** [comment]
This issue can be split into 2

1) Terry outputs the logs into a txt file
2) Perhaps @samartnik take the info in the text file and display it on chrome://rewards-internals/
No design needed, just display the contents of the file

**Comment by anthonypkeane** [comment]
@tmancey,  @samartnik will do part 2 once you let him know the file location

**Comment by anthonypkeane** [comment]
Desktop: https://github.com/brave/brave-browser/issues/3538#issuecomment-508738402

**Comment by EyanGoldman** [comment]
Redundant to #1341

**Comment by srirambv** [comment]
Moving to 1.4.0 as #1341 is marked for that

**Comment by srirambv** [comment]
Marking as QA/No and moving out of milestone as its already implemented in 1.2.0. Ads logging info needs to be logged in future. @samartnik confirmed the code is 1:1 from the desktop so once it's done on the desktop should be available in Android as well.
