### ISSUE TITLE
Default Browser Notification Adjustment

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1677]
Send Notification If: user has not already set Brave to be the default Browser. 
When: 11:22 AM, local time the day of/after install
Title: ⚡Brave is Lightning Fast⚡
Body: Make Brave your default browser!
Response: No |  I'm in! 
Note: https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat

Keep existing flow for "I'm in!" click

**Comment by EyanGoldman** [comment]
#1417 Should also be fixed with this update

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.1.0 x64 ads 5 build
  - Verified notification text based on https://github.com/brave/browser-android-tabs/issues/1742#issuecomment-504211684
  ![Screenshot_20190704-093733_Brave](https://user-images.githubusercontent.com/17010094/60596912-f050b180-9d77-11e9-94ab-d4bde7a41c08.jpg)
