### ISSUE TITLE
Brave Rewards are Here Notification Removal

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1678]
Remove "Brave Rewards are Here" heads-up notification

**Comment by srirambv** [comment]
@tmancey @anthonypkeane please add `QA/Yes` or `QA/No` to the issue.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.1.0 x64 ads 5 build
  - Verified on a clean install 
  - Verified on an upgrade from an older build only showed Enable Rewards in-app notification 
  - Verified upgrade on an older build without rewards and with rewards but not enabled

* Verification passed on OnePlus 6T running 1.1.0 x64 ads 5 build
  - Verified on a clean install 
  - Verified on an upgrade from an older build only showed Enable Rewards in-app notification 
  - Verified upgrade on an older build without rewards and with rewards but not enabled
