### ISSUE TITLE
Update timings on Brave Ads here modal for new users

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1679]
I want to tie our notifications together to they work in tandem. 

Pls change the timing on the:
2) New users (new installs) and existing users that never enabled Rewards

from 
 -> instant on upgrade or install 

to
-> 24 hours after the default notification alert

Note: min time will be 24 hours after the default notification alert, but on first open after that time. 

Spec: https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit?usp=sharing
Linked to: https://github.com/brave/browser-android-tabs/issues/1523
Default Browser Issue: https://github.com/brave/browser-android-tabs/issues/1677

**Comment by anthonypkeane** [comment]
closing as https://github.com/brave/browser-android-tabs/issues/1689 is more up to date

**Comment by srirambv** [comment]
* Verification passed notes added here https://github.com/brave/browser-android-tabs/issues/1689#issuecomment-508525457
