### ISSUE TITLE
Nav and URL bar not immediately displaying on new tab

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1685]
## Description 
Sometimes when the new tab button is pressed, the nav and url bar are heavily delayed from displaying (5-10) seconds. 

![Screenshot_20190613-102851.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/6d516336-7846-4e89-a2ca-8c3edd37cd47)

## Steps to reproduce 
Can't guarantee; however, I am able to reproduce it when I press the new tab button as the "Closed  [insert tab name here]" notification pops up at the bottom of the screen. 

## Issue reproduces how often 
Intermittent issue

## Issue happens on 
   - Beta build
Beta

## Device details
   - Install type (ARM, x86):
ModernArm
   - Device (Phone, Tablet, Phablet):
Pixel 3 XL
   - Android version:
   9
## Brave version
1.0.98

### Website problems only
- Is the issue reproducible on the latest version of Chrome? 
No (at least I cannot)

### Additional information

May need multiple tabs open before closing one of them

**Comment by anthonypkeane** [comment]
Closing
