### ISSUE TITLE
Badge notification isn't removed even after user opts into Brave Ads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1687]
## Description 
Badge notification isn't removed even after user opts into Brave Ads

## Steps to reproduce 

   1. Enable Rewards on your existing install
   2. Upgrade to 1.0.98
   3. Shows badge notification 
   4. Tap on BR panel, shows Enable Ads notification
   5. Tap on `I'M IN` or close the notification, badge doesn't go away. It is only removed after you tap on BR panel again

## Actual result 
Badge notification isn't removed even after user opts into Brave Ads

## Expected result
Should remove badge when notification is dismissed

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone/Tablet
   - Android version: 8.1.0
   
## Brave version
1.0.98 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yachtcaptain23** [comment]
This should have been fixed since we no longer update the badge count. Please re-open if this still occurs.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm `v1.1.0-brave-ads-5`
