### ISSUE TITLE
Brave rewards/ads modals

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1689]
For existing rewards users: "Brave ads are here" modal should only launch when existing rewards users open the app after install, not when they press the BAT icon. When they press the BAT icon, the normal rewards menu should drop down. 

For new users: "Brave rewards are here" modal should show, on open, after a minimum of 24 hours have past from the user's first time opening Brave. 

Please reference the following: https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit

**Comment by yachtcaptain23** [comment]
Done as part of https://github.com/brave/browser-android-tabs/pull/1686.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 and OnePlus 6T running 1.1.0-6 x64 ads build
  - Upgrade from playstore build with rewards enabled shows `Brave Ads are here` in-app modal upon upgrade 
   ![image](https://user-images.githubusercontent.com/17010094/60677908-d33be180-9e50-11e9-958f-3983baa0ce4e.png)
  - Clean install past 24 hours without enabling rewards shows `Enable Bave Rewards` in-app modal
  - Playstore build without rewards enabled and upon upgrade shows `Enable Brave rewards` in-app modal 
  ![image](https://user-images.githubusercontent.com/17010094/60677943-e9e23880-9e50-11e9-9287-6ccdb9b71c84.png)

* Verification passed on Samsung Tab A running 1.1.0-6 x64 ads build
  - Clean install past 24 hours without enabling rewards shows `Enable Bave Rewards` in-app modal
  - Playstore build without rewards enabled and upon upgrade shows `Enable Brave rewards` in-app modal 
  ![image](https://user-images.githubusercontent.com/17010094/60678148-8f95a780-9e51-11e9-942c-daa684b49ff4.png)
  - Upgrade from playstore build with rewards enabled shows `Brave Ads are here` in-app modal upon upgrade
  ![image](https://user-images.githubusercontent.com/17010094/60678207-c23fa000-9e51-11e9-8ce5-ac4be322c4b2.png)

**Comment by EyanGoldman** [comment]
@deeppandya these are the modals I was referring to
