### ISSUE TITLE
Brave Ads Education Notification

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1690]
2.5 seconds after the user opts in to Brave Ads we need to send a notification to show them what a Brave Ad looks like. 

Send notification when: 2.5 seconds after user enables Brave Ads
Notification Title: This is a sample ad from Brave
Notification Body: This is what an ad will look like.
Notification takes you to (if needed): https://www.brave.com/my-first-ad
Buttons: None needed
For clarification: No BAT should be given to the user for this

**Comment by srirambv** [comment]
Do we need the 2.5 sec delay? We could as well show the sample message when user enables ads in rewards page. Reason being if you enable and then switch to a site tab, it might show up on the webpage and might be confusing that the website is showing a test ad. Should probably show the notification instantly on the rewards page when its enabled.

**Comment by anthonypkeane** [comment]
Sorry for the last min change
Text Update:

from
Notification Title: This is a sample ad from Brave
Notification Body: This is what an ad will look like.

to
Notification Title: This is your first Brave Ad
Notification Body: Tap here to learn more

Tapping on the notification sends the user to: URL: https://www.brave.com/my-first-ad

CC @tmancey

**Comment by GeetaSarvadnya** [comment]
@anthonypkeane The ads sample link is redirecting to 404 error page. Are we tracking this somewhere?

**Comment by GeetaSarvadnya** [comment]
The link `https://www.brave.com/my-first-ad` . Looks like which is expected. 

![Screenshot_2019-07-02-16-52-10](https://user-images.githubusercontent.com/38657976/60509105-c94b9e80-9ce9-11e9-8d5b-b060a85612b9.png)

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.1.0 x64 ads 5 build
  - Verified after enabling rewards with 2.5 sec gap sample ads notification is shown
  - Tap on the sample notification loads the landing page https://brave.com/my-first-ad/
  - Verified no log is added for the sample notification
  - Verified no log for landing page until page reload 

* Verification passed on Huawei P20 running 1.1.0 x64 ads 5 build
  - Verified after enabling rewards with 2.5 sec gap sample ads notification is shown
  - Tap on the sample notification loads the landing page https://brave.com/my-first-ad/
  - Verified no log is added for the sample notification
  - Verified no log for landing page until page reload 

* Verification passed on OnePlus running 1.1.0 x64 ads 5 build
  - Verified after enabling rewards with 2.5 sec gap sample ads notification is shown
  - Tap on the sample notification loads the landing page https://brave.com/my-first-ad/
  - Verified no log is added for the sample notification
  - Verified no log for landing page until page reload
