### ISSUE TITLE
Remove vibrate on ad notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1696]
Remove vibrate on ad notification

Internal Chat: https://bravesoftware.slack.com/archives/CJVNBPK9P/p1559948692056300?thread_ts=1559948595.055100&cid=CJVNBPK9P

**Comment by anthonypkeane** [comment]
closing as I should think about this a bit more

**Comment by anthonypkeane** [comment]
Can't reproduce @srirambv

**Comment by srirambv** [comment]
Vibration can be disabled at device level for notifications. Most devices enable vibration by default for any notification.
