### ISSUE TITLE
Red icon around Trash icon

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1697]
## Description 
There is a red box around the trash icon in reward settings

![Screenshot_20190613-125814.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/f977d0e2-1b2d-4347-aa7b-c33e75bc9d3d)

**Comment by EyanGoldman** [comment]
@anthonypkeane can't replicate this. Anything I need to do to get that? If not will close.

**Comment by EyanGoldman** [comment]
cc @petemill @ryanml

**Comment by anthonypkeane** [comment]
@ryanml would you be able to work on this one?
