### ISSUE TITLE
Inconsistent usage of words for joining rewards

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1699]
## Description 
With new onboarding flow the wording is not consistent on buttons which are used to enable rewards. 

## Actual result 

Onboarding flow uses `I'M IN!`. 
![Screenshot_20190614-075413](https://user-images.githubusercontent.com/17010094/59507681-bf1c4a00-8e79-11e9-8923-cf921e10aaee.jpg)

BR Panel uses `Join rewards`:
![Screenshot_20190614-075420](https://user-images.githubusercontent.com/17010094/59507696-c9d6df00-8e79-11e9-9361-8041df2c69b3.jpg)

Rewards page uses `YES I'M IN!`
![Screenshot_20190614-075429](https://user-images.githubusercontent.com/17010094/59507707-d52a0a80-8e79-11e9-90ca-43606cb4f358.jpg)

## Expected result
Should be consistent wording on all buttons that enable rewards 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1.0
   
## Brave version
1.0.98 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
@alexwykoff can you please make a call on this one? 
I'm happy with I'm in as it is a better CTA for this modal

**Comment by tmancey** [comment]
This behaviour is correct and matches the spec, closing issue.
