### ISSUE TITLE
I'M IN on upgrade doesn't enable rewards 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1700]
## Description 
I'M IN on upgrade doesn't enable rewards 

## Steps to reproduce 

   1. Install older version 1.0.95
   2. **Do not enable rewards**
   3. Upgrade to ads rewards build
   4. Click on BR panel, On boarding flow shows `Brave ads are here` (wrong message) 
   5. Click `I'M IN!` to join rewards
   6. Open rewards panel again, wallet isn't created, you need to join rewards manually

## Actual result 
[Upgrade Not joined.zip](https://github.com/brave/browser-android-tabs/files/3290536/Upgrade.Not.joined.zip)

## Expected result
Should enable rewards when clicked on `I'M IN!`

## Issue reproduces how often 
Easy

## Issue happens on  
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1.0
   
## Brave version
1.0.98 Ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Unable to reproduce on BraveModernarm v1.1.0-brave-ads on Samsung s7. After step 3 I see `Creating wallet...` in Rewards Panel.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung galaxy version 5.1.1 running v1.1.0-brave-ads-5
