### ISSUE TITLE
Newly added bookmarks are not synced after the device comes online - follow up of #1354

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1702]
## Description 
Follow up to #1354 
Newly added bookmarks are not synced after the device comes online

##Devices

Device1: Android Samsung Galaxy J3 5.1.1
Device2: Desktop bc 0.66.87 
Device3: Android Gionee s5

## Steps to reproduce 

1. Create a sync chain b/n device2 and device1 ( in the device1, scan the QR code from the desktop)
2. Add few bookmarks in device1 and device 2 ( I have added 5 bookmarks in each device)
3. Make sure bookmarks are synced in both devices
4. Exit the browser from the hamburger menu
5. Disconnect the network in device1 and wait for 10 to 15 secs
6. Open the browser and make sure the sync chain is not broken and sync data is not lost
7. Enable the network again in device 1
8. Add few bookmarks in both devices (1 and 2)
9. Verify that bookmarks added in step 5 are not synced
10. Add the 3rd device to the device1 through QR code
11. Device 3 is not getting synced in device 1 

## Actual result 
Newly added bookmarks are not synced after the device comes online and the new device is not getting added to device1 sync chain

## Expected result
Newly added bookmarks should be synced after the device comes online and the new device should get added to sync chain in device1

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Sync chain is broken when the device1 was offline (step6 from STR)
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3 and Gionee
   - Android version: 1.0.98
   
## Brave version

1.0.98
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @AlexeyBarabash @SergeyZhukovsky 

In the play store version, the sync chain is broken when device 1 is offline - above STR step 6
cc @anthonypkeane Please add this issue to appropriate milestone

**Comment by srirambv** [comment]
I couldn't reproduce the issue completely my self. Did the following
1. Create sync chain on Desktop
2. Add Android to sync chain
3. Add bookmarks on both desktop and mobile and wait for sync
4. Exit browser on Android and disconnect from network
5. Reconnect to network and launch browser
6. Add new bookmarks on both devices, 
7. Desktop didn't get the bookmark added on Android but Android received new bookmark added on desktop

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.0.98 RC2  x64 build
  * Verified steps from https://github.com/brave/browser-android-tabs/issues/1702#issue-456335340
  * Verified all bookmarks from all devices are sync'd across when either of the device is disconnected from network and reconnected
  * Verified bookmarks added on a device is sync'd to all devices when all of them are online

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine. Verified on Samsung Galaxy J3 version running on `BraveModernarm 1.0.98-rc.2`
