### ISSUE TITLE
Blue checkmarks on top of BAT icon for verified creators

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1708]
Currently on Dev for Desktop, on the BAT icon in the URL bar, verified creators will have a blue checkmark icon appear on top of the BAT icon. To keep the experience consistent, mobile should also have this implemented. 
Add blue checkmarks for verified creators (like Desktop Dev version).

![Screen Shot 2019-06-17 at 9 03 51 AM](https://user-images.githubusercontent.com/8962135/59619341-2be44e00-90df-11e9-94f7-591758633d72.png)

**Comment by anthonypkeane** [comment]
Design Spec: https://app.goabstract.com/projects/1ba67860-79bb-11e8-8738-c75a805f73cf/branches/master/commits/8b16b0c024db89f45d908b6e915345b0b2987b68/files/C26ACA3E-7AC8-440E-9975-6ECD4BDB1B0F/layers/F1AF0090-8825-4744-B32A-AC859E28470A?commentId=f0e11b22-16aa-42e4-be49-5842424f0554

**Comment by gdregalo** [comment]
@anthonypkeane @jamesmudgett 
The spec above doesn't have a  design for `blue checkmarks for verified creators` for both bright and dark themes. What if a user has new pending notifications (red circle with numbers)?  Which one has a higher priority and should be posted on the top?

**Comment by deeppandya** [comment]
@gdregalo it was added here https://github.com/brave/browser-android-tabs/issues/2201#issuecomment-547525621

**Comment by deeppandya** [comment]
@gdregalo icons are here https://github.com/brave/browser-android-tabs/issues/2201#issuecomment-547536257

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.6.0 x64 build
* On dark theme
![image](https://user-images.githubusercontent.com/17010094/69831900-7e32aa80-11f9-11ea-8b80-967b716941e9.png)
* On light theme
![image](https://user-images.githubusercontent.com/17010094/69831906-868ae580-11f9-11ea-8265-f1a2da46c6a3.png)
