### ISSUE TITLE
Notification Time Stamps

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1712]
For all notifications, switch the time stamping from time the notification was sent to:

If notification was sent: <10 seconds ago:
"Now"

If notification was sent >= 10 seconds and < 1 minute ago
"[however many seconds ago]s"

If notification was sent >= 1 minute and < 1 hour ago:
"[however many minutes ago]m"

If notification was sent >= 1 hour and < 1 day ago:
"[however many hours ago]h"

If notification was sent >= 1 day:
"[however many days ago]d"

Reference:
![img](https://user-images.githubusercontent.com/8962135/59623975-70c1b200-90ea-11e9-9b51-527805d128ee.png)

**Comment by anthonypkeane** [comment]
closing as we no longer show time stamps
