### ISSUE TITLE
Delete Download History

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1715]
When a user clears their history, we currently provide no option for them to clear their download history. The proposal is to add the ability to clear download history when a user clears their history. 

https://bravesoftware.slack.com/archives/C0816QH3R/p1560612176131900

**Comment by EyanGoldman** [comment]
As per the above slack post, this should be located in the "ADVANCED" section of "Clear browsing data" under "Site settings".

**Comment by jamesmudgett** [comment]
Let's use the download Icon from Chrome.

**Comment by EyanGoldman** [comment]
Clear browsing data is under: "Settings" > "Privacy" > "Clear browsing data"

**Comment by deeppandya** [comment]
@EyanGoldman i believe **Delete download history** option should follow the dropdown we have for the time. correct me if i am wrong.

**Comment by EyanGoldman** [comment]
It should be in the "Advanced" section as a check box under "Cached images and files"

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 RC1 x64 build
* Verified `Clear browsing data` has an entry for Download history
* Verified clearing data clear Download data without having to restart the browser
[DownloadHistory.zip](https://github.com/brave/browser-android-tabs/files/3617721/DownloadHistory.zip)
