### ISSUE TITLE
closing all tabs closes browser (default switch)

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1716]
When a user closes all of their tabs, the browser should not (by default) close as well. 
Current Default: [three dots] > Settings > Home page > Switch =  on
New Default: [three dots] > Settings > Home page > Switch = off

**Comment by EyanGoldman** [comment]
#490 
#1180

**Comment by srirambv** [comment]
related to #1707

**Comment by kjozwiak** [comment]
Moved this back into https://github.com/brave/browser-android-tabs/milestone/82 as it was revertedd from `1.1.1 CR 75.0.3770.101`. The above fix was reverting the Homepage to `disabled` for all users, which also removed homepage URL's.

**Comment by SergeyZhukovsky** [comment]
We cannot just change default behaviour. What it caused is that existing users get it off after an update even though they explicitly set to open some webpage on Home button click

**Comment by EyanGoldman** [comment]
We are going to change this a bit.
1. Decouple closing all tabs closes the browser from the homepage functionality and adding its own switch.
- Under "Home page" in basics, add an additional category "Closing all tabs closes Brave". 
- When off, closing all tabs will result in a blank tab tray. 
- When on, closing all tabs will close the browser and when it is reopened user will land on a new tab page (current behavior when home page is on)
- The home page switch will then just control whether the home page button is enabled or disabled
2. For existing users, on update, the state of the "Closing all tabs closes Brave" switch should match the current state of the "home page" switch. Afterwords, these can move independently. 
3. For new users, home page should be turned on and closing tabs closes Brave should be turned off.

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta-x64 
Clean Install: 
  * Verified when `Close all tabs closes browser` option is turned on, the browser closes when the last tab is closed
  * Verified when `Close all tabs closes browser` option is turned off, browser retains empty tab tray when the last tab is closed
  * Verified `Home Page` option state doesn't affect working on `Close all tabs closes browser` option
  * Verified with multiple tabs opened, `Close all tabs` option from tab tray closes all tabs and retains the tab tray when `Close all tabs closes browser` option is turned off
  * Verified with multiple tabs opened, `Close all tabs` option from tab tray closes all tabs and exits the browser when `Close all tabs closes browser` option is turned on
Upgrade Scenario:
  * Verified `Home page` settings are retained on upgrade
  * Verified `Close all tabs closes browser` option is enabled by default upon upgrade to match existing functionality
  * Verified disabling `Home Page` settings doesn't affect `Close all tabs closes browser` setting 
  * Logged issue #1976 for setting not retained when launched

**Comment by srirambv** [comment]
QA Blocked on Tabet because of #1981

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta-x64 
Clean Install: 
  * Verified when `Close all tabs closes browser` option is turned on, the browser closes when the last tab is closed
  * Verified when `Close all tabs closes browser` option is turned off, browser retains empty tab tray when the last tab is closed
  * Verified `Home Page` option state doesn't affect working on `Close all tabs closes browser` option

Upgrade Scenario:
  * Verified `Home page` settings are retained on upgrade
  * Verified `Close all tabs closes browser` option is enabled by default upon upgrade to match the existing functionality
  * Verified disabling `Home Page` settings doesn't affect `Close all tabs closes browser` setting
