### ISSUE TITLE
Fix dark mode / make more accessible

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1717]
Add a switch in settings to turn "Android Chrome UI Dark Mode" on

When the switch is enabled, all of the UI should go dark (shields, URL bar, nav bar, menus, etc.) All of the aforementioned currently do not. Additionally, button colors should be adjusted so they are still visible when their respective backgrounds go dark

**Comment by EyanGoldman** [comment]
#81

**Comment by jonathansampson** [comment]
One of our users on Twitter was kind enough to provide the following example as one issue in particular that needs to be improved for better a11y (not enough contrast between foreground and background colors):

![image](https://user-images.githubusercontent.com/815158/64547746-e8bb0500-d2f2-11e9-9d44-eb9baa8058bd.png)

**Comment by Hamburger6** [comment]
I'm hoping for a brave dark mode soon since I have yesterday added the theme switch arm to my browser on my phone. The chrome flag dark ui is reversed alot. I'm on android 7.0.1.

**Comment by deeppandya** [comment]
@jonathansampson it's fixed and planning to add in the next release.

**Comment by szaimen** [comment]
Isn't this issue already done?

**Comment by anthonypkeane** [comment]
fixed
