### ISSUE TITLE
Three button menu changes

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1718]
1. Remove the ["i" in circle] button from the menu as its functionality is duplicated by clicking on the lock icon next to the URL. Replace with an icon for share page. Remove "Share..." button from menu as we will now have its functionality built into an icon. 
2. Remove "Set as default browser button" once Brave is set as the default browser (instead of greying button out)

**Comment by EyanGoldman** [comment]
#1495

**Comment by jamesmudgett** [comment]
[share_icon.zip](https://github.com/brave/browser-android-tabs/files/3303336/share_icon.zip)

**Comment by anthonypkeane** [comment]
Linked to: https://github.com/brave/browser-android-tabs/issues/1560

**Comment by EyanGoldman** [comment]
Update: To allow the users who frequently use the "Share..." button, we will transition into using the visual button by having both buttons available initially. Updated instructions are as follows:

- Remove the ["i" in circle] button from the menu as its functionality is duplicated by clicking on the lock icon next to the URL. Replace with an icon for share page.
- Remove "Set as default browser button" once Brave is set as the default browser (instead of greying button out)

**Comment by srirambv** [comment]
> Remove "Set as default browser button" once Brave is set as the default browser (instead of greying button out)
 
this is already fixed and shipped as part of 1.0.99 (#1495)

**Comment by anthonypkeane** [comment]
@jamesmudgett 
How about using the Android Share icon

![download](https://user-images.githubusercontent.com/7606853/60116629-49dc2f00-972d-11e9-9bc8-dd8742b7b7c1.png)

**Comment by deeppandya** [comment]
@jamesmudgett we should use the icon @anthonypkeane has shared as it's the standard android share icon.

**Comment by deeppandya** [comment]
@anthonypkeane what should be the text when user long press on the share button in the menu ?

**Comment by anthonypkeane** [comment]
> @anthonypkeane what should be the text when user long press on the share button in the menu ?

Yes, @deeppandya 

Text for all should be:

Forward icon: Page Forward
Bookmark icon: Bookmark
Download Icon: Download
Share Icon: Share
Reload Icon: Refresh

**Comment by deeppandya** [comment]
@jamesmudgett can i use android image assets for share icon ? or you will provide new icon? i can export share icon from android asset library.

**Comment by jamesmudgett** [comment]
[share_icon.zip](https://github.com/brave/browser-android-tabs/files/3331495/share_icon.zip)
@deeppandya new share icon^

**Comment by deeppandya** [comment]
Thanks @jamesmudgett i will update it.

**Comment by deeppandya** [comment]
As per the discussion with @anthonypkeane, ia m keeping the "Share" option in the menu for few releases.

internal chat : https://bravesoftware.slack.com/archives/DKA4S8HPU/p1561405893005100

**Comment by srirambv** [comment]
@EyanGoldman  so its just the share button replacing (i) button in kabob menu as part of this issue correct?

**Comment by anthonypkeane** [comment]
> @EyanGoldman so its just the share button replacing (i) button in kabob menu as part of this issue correct?

Yes @srirambv 

On Android Q there is a bug however and the share screen is not opening. We don't need to support Android Q right now however.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.1.0-6 ads x64 build 
* Verification passed on OnePlus 6T running 1.1.0-6 ads x64 build 
![Screenshot_20190706-170505](https://user-images.githubusercontent.com/17010094/60625136-ed27e680-9db4-11e9-9fa5-b9b1ce78577c.jpg)
