### ISSUE TITLE
BAT red notification badge for new users

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1724]
## Description 
Currently, on a clean install, there is no red dot on the BAT icon which alerts users to opt in to Brave Rewards / Ads. We want to change this to make it easier for new users to find Brave Ads / Rewards once installed. 
On a clean install, add a notification badge (red dot) to the BAT icon so users can find where the opt-in to Brave Rewards / Ads is located. Once the BAT icon is clicked the first time, the red badge should disappear.  If the user opts-in, no more notifications should be sent regarding rewards. Otherwise, continue with the opt in notification flow.

## Steps to reproduce 

   1.  Clean install of Brave
   2.  No red dot on BAT icon

## Expected result
   1.  Clean install of Brave
   2.  red dot visible on BAT icon
   3. Once BAT icon is clicked, red dot should disappear and normal behavior for clicking the BAT icon should follow. 
   4. If user chooses to not opt in, the red dot should re-appear following the current specification

**Comment by yachtcaptain23** [comment]
We keep flip-flopping on this or the message isn't clear. Please punt this to 1.2. I reverted my change because it was requested: https://github.com/brave/browser-android-tabs/pull/1698/files

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.1.0 ads2 x64 build. Found #1775 while verifying the expected behaviour from the spec
