### ISSUE TITLE
Incorrect `Next Payment Date` display in Ads panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1725]
## Description 
Incorrect `Next Payment Date` display in Ads panel

## Steps to reproduce 

   1. Install 1.0.95
   2. Don't enable brave rewards
   3. Upgrade to Ads build
   4. Click on I'M IN in `Brave Ads here` popup ( rewards is not getting enabled)
   5. Click on BR panel and enable rewards
   6. Click on View Details in Ads panel
  

## Actual result 
`Next Payment Date` is displayed as `Aug 5` in Ads panel

![image](https://user-images.githubusercontent.com/38657976/59716068-da4cd800-9232-11e9-9841-3f84fe071828.png)

## Expected result
`Next Payment Date` should be displayed as Jul5

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @tmancey

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.1.0-brave-ads on Samsung s7.
Also reproduced when rewards are enabled in 1.0.95.

**Comment by srirambv** [comment]
The incorrect date is shown for auto contribution as well and not just on Ads payout

**Comment by tmancey** [comment]
> The incorrect date is shown for auto contribution as well and not just on Ads payout

Can you create a separate ticket for auto contribution as unrelated, thanks

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.1.0 ads2 x64 build. Expected behaviour to show in `MMM DD` format
![Screenshot_20190626-123047_Brave](https://user-images.githubusercontent.com/17010094/60115970-21f8c580-9745-11e9-856b-1b44e471e3bc.jpg)
