### ISSUE TITLE
`Next Payment Date` field is empty, delay in fetching the date field

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1727]
## Description 
`Next Payment Date` field is empty, delay in fetching the date field

## Steps to reproduce 

   1. Install 1.0.95
   2. Don't enable brave rewards
   3. Upgrade to Ads build
   4. Click on I'M IN in `Brave Ads here` popup ( rewards is not getting enabled)
   5. Click on BR panel and enable rewards
   6. Click on View Details in Ads panel
   7. Verify `Next Payment Date` field

## Actual result 
`Next Payment Date` field is empty, delay in fetching the date field

![image](https://user-images.githubusercontent.com/38657976/59716867-67446100-9234-11e9-8f9f-45e9f6fcc681.png)

## Expected result
`Next Payment Date` field should load the date field immediately.

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @tmancey

**Comment by btlechowski** [comment]
Unable to reproduce on BraveModernarm v1.1.0-brave-ads on Samsung s7. 
After step 4, I see `Creating wallet...` in Rewards Panel. When I check ads rewards page everything looks fine.

**Comment by kjozwiak** [comment]
@tmancey should we have @GeetaSarvadnya double check to make sure this doesn't fall through the cracks? Maybe the above happens in certain conditions that @btlechowski didn't hit?

**Comment by LaurenWags** [comment]
Tried several times on LG Nexus running Android 5.1 using STR from description and was unable to reproduce.  Note, in step 4 Rewards are getting enabled, so this is a slight difference.

@GeetaSarvadnya could you try as well?

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the build BraveModernarm `v1.1.0-brave-ads-5` -Still, I am able to reproduce the issue. An empty date filed is displayed for ~7 secs after that expected date displayed in date filed. 
step 4: Click on `I'M IN` enables the rewards now.
