### ISSUE TITLE
Sorry! Ads not supported message is displayed in brave://rewards page for ads supported region

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1728]
## Description 

Sorry! Ads not supported message is displayed in brave://rewards page for ads supported region

## Steps to reproduce 

**Pre-requisites**: Proton VPN is connected and set to US Region, device language is set to English (US)
   1. Clean profile 1.0.95 ( downloaded from GH)
   2. Enable Rewards through the hamburger menu
   3. Upgrade to latest Ads build
   4. `Brave Ads are here` popup is displayed
   5. Sorry! Ads not supported message is displayed in brave://rewards page behind the `Brave 
      Ads are here` popup.

**Note**: Click on I'M IN in `Brave Ads are here` popup disappears the message

## Actual result 
Sorry! Ads not supported message is displayed in brave://rewards page for ads supported region

![image](https://user-images.githubusercontent.com/38657976/59717450-a2935f80-9235-11e9-9f4f-904fac8defa3.png)

## Expected result
Sorry! Ads not supported message is should not be displayed in brave://rewards page for ads supported region

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
@GeetaSarvadnya I cannot reproduce. Can you test on next build please which we will send out tomorrow.

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.1.0-6 x64 ads build
  - Verified no message is shown for supported regions
  - Verified sorry message is only shown for unsupported region

* Verification passed on OnePlus 6T running 1.1.0-6 x64 ads build
  - Verified no message is shown for supported regions
  - Verified sorry message is only shown for unsupported region

* Verification passed on Samsung Tab A running 1.1.0-6 x64 ads build
  - Verified no message is shown for supported regions
  - Verified sorry message is only shown for unsupported region
