### ISSUE TITLE
Next payment date for ads should be `Monthly 5th`

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1731]
## Description 
Next payment date for ads should be `Monthly 5th` to keep in line with desktop wording.

## Actual result 
Desktop:
![image](https://user-images.githubusercontent.com/17010094/59774892-3ab53700-927e-11e9-8aa5-de8fc70d7b91.png)
Mobile: 
![Screenshot_20190619-200818](https://user-images.githubusercontent.com/17010094/59775007-6a643f00-927e-11e9-9dc1-4b6af278af5b.jpg)

## Expected result
Should be similar to desktop

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ALL
   - Device (Phone, Tablet, Phablet): ALL
   - Android version: ALL
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
@srirambv Desktop nightly has been changed to show 5 Jan etc. this is not an issue, can you please close the ticket
