### ISSUE TITLE
Inconsistent DD/MM/YYYY format in auto contribute settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1732]
## Description 
Inconsistent DD/MM/YYYY format in auto contribute settings

## Actual result 
Desktop using DD/MM/YYYY
![image](https://user-images.githubusercontent.com/17010094/59775396-24f44180-927f-11e9-9018-2cdadcec2290.png)
Mobile GPS version 1.0.97 using DD/MM/YYYY
![Screenshot_20190619-104200](https://user-images.githubusercontent.com/17010094/59775482-4d7c3b80-927f-11e9-983f-2251406d3664.png)
Ads build using MM/DD/YYYY
![Screenshot_20190619-201224](https://user-images.githubusercontent.com/17010094/59775504-579e3a00-927f-11e9-8aa3-c864e81496ab.jpg)

## Expected result
Should use the same format on ads build

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): ALL
   - Android version: ALL
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
@sri this logic matches desktop. A change request has been raised on desktop and I will cherry-pick this to android once changed.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung galaxy version 5.1.1 running v1.1.0-brave-ads-5. Verified Desktop nightly Vs  Android ad build, The contribution and ads date are of the same format:

Desktop - Ads panel `Date` format:

![image](https://user-images.githubusercontent.com/38657976/60251313-f06b3000-98e5-11e9-964f-b65744c9ef69.png)

Android - Ads panel `Date` format:

![Screenshot_2019-06-27-14-15-31](https://user-images.githubusercontent.com/38657976/60251604-75564980-98e6-11e9-9561-63e6f8bf5b77.png)

Desktop - Auto contribution `Date` format:

![image](https://user-images.githubusercontent.com/38657976/60251479-3aecac80-98e6-11e9-9ace-6521c2c2abe2.png)

Android - Auto contribution `Date` format:

![Screenshot_2019-06-27-14-15-58](https://user-images.githubusercontent.com/38657976/60251622-7f784800-98e6-11e9-8abc-90f4f776a91a.png)
