### ISSUE TITLE
Ads count isn't updated immediately after notification is done

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1736]
## Description 
Ads count isn't updated immediately after notification is done

## Steps to reproduce 

   1. Clean install 1.1.0 and enable ads
   2. Visit a site to trigger ad
   3. Ensure you get ad notification even if the device is locked
   4. Check how many ads is shown in notification center
   5. Open rewards page and go to ads details, ads viewed count shows 1 less than the number of ads in notification center
[adslog.zip](https://github.com/brave/browser-android-tabs/files/3307849/adslog.zip)

## Actual result 
https://youtu.be/EWBBL3SaYn0

## Expected result
Should show the correct ads view count

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No 
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P20
   - Android version: 8.1.0
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @tmancey @yachtcaptain23

**Comment by tmancey** [comment]
@srirambv server failed for some confirmations, which are in the retry queue. Can you please leave running for 1 hour then resend me the log

see `Failed to redeem token with 91a6fec8-b00e-496e-9bbb-a979dec54a79 creative instance id for view` in the log as an example

**Comment by srirambv** [comment]
- Verification passed on Samsung Tab A with Android 8.1.0 running 1.1.0-6 x64 build 
  - Verified no failed confirmations in log 
  - Verified ad count matched with the number of notification shown in the tray
- Verification passed on Huawei P20 with Android 8.1.0 running 1.1.0-6 x64 build 
  - Verified no failed confirmations in log 
  - Verified ad count matched with the number of notification shown in the tray
- Verification passed on OnePlus 6T with Android 9.0 running 1.1.0-6 x64 build 
  - Verified no failed confirmations in log 
  - Verified ad count matched with the number of notification shown in the tray
