### ISSUE TITLE
Disabling ads doesn't prevent "Brave Ads are here!" modal from re-appearing

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/browser-android-tabs#1738]
## Description 
The OOBE "Join Ads" dialog can appear even if the user enables and then disables ads. We should stop asking this after the first time.

## Steps to reproduce 
Join Rewards & join ads. Then after disabling ads, the OOBE "Join Ads" dialog will continue appearing based on the view count.

## Expected result
If the user disables ads, stop asking permanently.

## Issue reproduces how often
100%

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm `1.1.0-brave-ads-8` build
