### ISSUE TITLE
Default Browser Notification Text Changes

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1742]
## Description 

Currently the set Brave as your default browser notification reads as follows:

Title: ⚡Brave is Lightning Fast⚡
Body: Make Brave your default browser!
Buttons: I'M IN! | NO

The changes will make the notification read as follows:

Title: ⚡Brave is lightning fast⚡
Body: Make Brave your default browser!
Buttons: NO | YES

To summarize changes:
- Title is going from everything uppercase to first word capitalized
- The "I'M IN" button is being replaced for a "YES" button
- The ordering for the two buttons are being swapped

**Comment by samartnik** [comment]
Standard google messages have positive button first. Is there any reason why we want to swap it for this specific message?

**Comment by anthonypkeane** [comment]
@samartnik 

Title: ⚡Brave is lightning fast⚡
Body: Make Brave your default browser!
Buttons: NO | MAKE DEFAULT

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/b6ee530d6fcc32244979a8fd90795dd9d2bbf3f9

**Comment by samartnik** [comment]
Additional fix https://github.com/brave/browser-android-tabs/commit/c659e37b52a5cab50b5e3d061e489b38a2862bf3

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab running 1.1.0 ads2 x64 build
![image](https://user-images.githubusercontent.com/17010094/60136246-ac571e80-9771-11e9-9da2-5160f2700e7d.png)

**Comment by GeetaSarvadnya** [comment]
Even after pull down the notification tray, I am not seeing `NO` and `Make Default` buttons in the notification. Click on the notification does nothing. 

Verified on Samsung Galaxy J3 version 5.1.1 running BraveModernarm `v1.1.0-brave-ads-5`

![Screenshot_2019-07-03-19-36-18](https://user-images.githubusercontent.com/38657976/60521388-ce6a1700-9d04-11e9-89fc-917a2c92bfb3.png)

**Comment by anthonypkeane** [comment]
That functionality is not available on API <21, I.e 5.1 and lower

**Comment by srirambv** [comment]
@EyanGoldman  can we have these documented in a wiki somewhere? Would help in guiding users to the wiki

**Comment by anthonypkeane** [comment]
It is detailed in the original spec for this feature

**Comment by LaurenWags** [comment]
What is described in https://github.com/brave/browser-android-tabs/issues/1742#issuecomment-507705736 also happens on my Android 6.0 device (Asus Zenfone x86) and Android 5.1 device as @GeetaSarvadnya noted (LG Nexus ARM)

**Comment by anthonypkeane** [comment]
This should help

If >= Android 5.0, API 21:
    At 11:22, notification should either present buttons automatically, or after a one finger pull down, present buttons


If < Android 5.0, API 21 and >= Android 4.0, API 14:
    At 11:22, notification should show without buttons 


If < Android 4.0, API 14:
    Nothing should display

**Comment by samartnik** [comment]
@anthonypkeane here we have API 24 (Android 7.0) as a threshold

**Comment by anthonypkeane** [comment]
Updating

If >= Android 7.0, API 24:
At 11:22, notification should either present buttons automatically, or after a one finger pull down, present buttons

If < Android 7.0, API 24 
At 11:22, notification should show without buttons
