### ISSUE TITLE
Brave as a privacy browser must remove the mobile model from the user agent

### ISSUE THREAD

**Issue by pagogi** [brave/browser-android-tabs#1743]
## Description 

The display of the mobile model on the user agent makes it easier to identify users.
As you can see, Firefox does not show the mobile model,
Brave as a privacy browser must remove the mobile model from the user agent

## Expected result

remove mobile model number from user agent

## Brave version
1.0.98

## Actual result 

![Screenshot_2019-06-20_221321](https://user-images.githubusercontent.com/52048256/59870409-bf04d880-93aa-11e9-996c-503ed85b33d9.jpg)
![Screenshot_2019-06-20_221222](https://user-images.githubusercontent.com/52048256/59870410-bf04d880-93aa-11e9-88a0-4ea96fa35e3b.jpg)

**Comment by srirambv** [comment]
cc: @tomlowenthal to decide if this goes in the ads build or the next one

**Comment by tomlowenthal** [comment]
This is in #712 .
