### ISSUE TITLE
Ads notifications are received when the network is disconnected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1753]
## Description 
Ads notifications are received when the network is disconnected

## Steps to reproduce 

 Pre-requisites: Proton VPN is connected to US region and device language is English (US) 

   1. Install ads build during the non-ads receive period
   2. Enable rewards, set 5 Ads per hour in Ads panel 
   3. Make sure ads are not received
   4. Disconnect the network in the device
   5. Lock the device and keep it idle for around 9 hours
   6. Unlock the device starts receiving notifications one after the other

## Actual result 

Ads notifications are received when the network is disconnected
![Screenshot_2019-06-21-10-40-17](https://user-images.githubusercontent.com/38657976/59920621-b4991c00-9448-11e9-838f-8669f0d1e5cc.png)

## Expected result
Ads notifications should not be received when the network is disconnected

## Issue reproduces how often 

Easy ( It reproduce once for me)

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3 
   - Android version: 5.1.1
   
## Brave version

1.1.0
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @tmancey

**Comment by srirambv** [comment]
Closing as this is more of a Chromium limitation and is already logged in desktop: https://github.com/brave/brave-browser/issues/3700
