### ISSUE TITLE
Ads switch should fire sample notification

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/browser-android-tabs#1754]
## Description 
Sample notification should fire if the Ads switch gets flipped.

## Steps to reproduce 

   1. Go to Ads-rewards panel
   2. Tap the Ads switch button
   3. Expect the notification to fire

**Comment by Mikko031014** [comment]
Sent from Yahoo Mail on Android 
 
  On Fri, Jun 21, 2019 at 11:16 PM, Albert Wang<notifications@github.com> wrote:   
Description 

Sample notification should fire if the Ads switch gets flipped.

Steps to reproduce 
   
   - Go to Ads-rewards panel
   - Tap the Ads switch button
   - Expect the notification to fire

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung galaxy version 5.1.1 running v1.1.0-brave-ads-5
Logged issue https://github.com/brave/browser-android-tabs/issues/1787
