### ISSUE TITLE
Click on Rewards settings is causing the brave crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1763]
## Description 
Click on Rewards ->setttings causing brave crash

## Steps to reproduce 

   1. Clean profile 1.1.0  (brave Ads - 2)
   2. Click on BR panel in the URL bar
   3. Click on Join Rewards
   4. Click on `Settings`
   

## Actual result 
Click on Rewards settings is causing the brave crash

https://drive.google.com/open?id=1HCTwSY6soOaLkTDYn8JVDJDJKQgkFM7L
## Expected result
Should not be any crash

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
BraveModernarm 1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @SergeyZhukovsky

**Comment by srirambv** [comment]
Can't reproduce this issue on Huawei P20 with a clean install of ads2 build

**Comment by anthonypkeane** [comment]
Confirmed

once I get the crash I can't open the app, crash loop

![Bug](https://user-images.githubusercontent.com/7606853/60038673-d32a2d80-9669-11e9-887d-869de149d0f3.gif)

**Comment by LaurenWags** [comment]
Reproduces on my LG Nexus 5 running Android 5.1

**Comment by GeetaSarvadnya** [comment]
Verified on Samsung Galaxy J3 version 5.1.1 running BraveModernarm `v1.1.0-brave-ads-5` - Issue is fixed and working fine.
