### ISSUE TITLE
Red dot icon display on BAT logo

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1764]
## Description 
Red dot icon display on BAT logo

## Steps to reproduce 

   1. Clean profile 1.1.0 (brave-ads-2)
   2. Verify red dot icon on BAT logo
   
   

## Actual result 
Red dot icon display on BAT logo

![image](https://user-images.githubusercontent.com/38657976/59979477-15218800-9606-11e9-9163-3a4e1ac1e652.png)

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
BraveModernarm 1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @SergeyZhukovsky

**Comment by srirambv** [comment]
Expected behaviour. #1724
