### ISSUE TITLE
FLIF images (using polyfill) not showing

### ISSUE THREAD

**Issue by benepo** [brave/browser-android-tabs#177]
[FLIF](http://flif.info/) images (using [polyfill](https://github.com/UprootLabs/poly-flif)) not showing.  Go to their [demo page](https://uprootlabs.github.io/poly-flif/polyflif-sample.html) to verify.

**Comment by JeremyWW** [comment]
They work perfectly well for me, but if you have 'Block Scripts' or 'Fingerprinting Protection' on they won't show. There is a slight delay in loading these images and I guess your phone and/or bandwidth may have some effect on that.

**Comment by benepo** [comment]
Interesting.  Disabling '[Fingerprinting Protection](https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode)' did the trick.  Thanks!
