### ISSUE TITLE
Sample ads notification opens https://brave.com/faq-rewards/#unclaimed-funds

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1774]
## Description 
Sample ads notification opens https://brave.com/faq-rewards/#unclaimed-funds

## Steps to reproduce 

   1. Clean install 1.1.0_ads build2
   2. Enable rewards to trigger sample ad notification
   3. Tap on the sample ad notification, loads https://brave.com/faq-rewards/#unclaimed-funds

## Actual result 
Sample ads notification opens https://brave.com/faq-rewards/#unclaimed-funds

## Expected result
Maybe open ads reward page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab
   - Android version: 8.1.0
   
## Brave version
1.1.0_ads 2 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @anthonypkeane @EyanGoldman @ter

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung galaxy version 5.1.1 running v1.1.0-brave-ads-5
 - Tap on sample ad should redirect to `https://www.brave.com/my-first-ad` as per https://github.com/brave/browser-android-tabs/issues/1690#issuecomment-505649345
- Sample link redirects to 404 pages ( page is not live yet) asked clarification in https://github.com/brave/browser-android-tabs/issues/1690#issuecomment-506229403
