### ISSUE TITLE
Red dot icon isn't removed when the user opts into rewards followup to #1724

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1775]
## Description 
Red dot icon isn't removed if the user opts into rewards

## Steps to reproduce 

   1. Clean profile on 1.1.0 ads 2 build
   2. Do not open rewards panel after launch so that red dot is retained on BR panel
   3. Wait for the second notification to appear
   4. Tap on `I'M IN!`, red dot is still retained on BR panel

## Actual result 
Red dot icon isn't removed when the user opts into rewards

## Expected result
If the user opts in via the second notification, then the red dot needs to be removed 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NO
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: 8.1.0
   
## Brave version
1.1.0 Ads2 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @yachtcaptain23 @tmancey @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
Step3: Second notification (`I'M IN!`) did not appear. Tested on v1.1.0-brave-ads-5

**Comment by yachtcaptain23** [comment]
@GeetaSarvadnya after 20 new app opens?

**Comment by yachtcaptain23** [comment]
We had a discussion yesterday, marking this as Won't Fix. Please re-open if you think this is something that should be addressed in this upcoming version.

**Comment by tmancey** [comment]
This was deferred to a future version so re-opening
