### ISSUE TITLE
Credit Card autofill dropdown contains Chromium Autofill 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#178]
![image](https://cloud.githubusercontent.com/assets/17010094/24202499/19d4d6a6-0f0b-11e7-9aa5-84536994815f.png)

Similar to #45 should show Brave Auto-fill settings

**Comment by SergeyZhukovsky** [comment]
Fixed it https://github.com/brave/browser-android-tabs/commit/f72cc55d446bc84fd7351a78a5549902d4d46e21
