### ISSUE TITLE
`Make Default` doesn't close notification tray and focus on setting browser as default 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1782]
## Description 
`Make Default` doesn't close notification tray and focus on setting browser as default 

## Steps to reproduce 

   1. Clean install 1.1.0
   2. Wait for the default browser notification to show up
   3. Pull down the notification tray and click on `Make Default`, tray remains open but action sheet is shown behind. you need to manually close the tray to set Brave as default

## Actual result 
![Screenshot_20190626-171331_Android System](https://user-images.githubusercontent.com/17010094/60137047-dd385300-9773-11e9-9513-dbe56839a8a1.jpg)
 default browser 

## Expected result
When `Make Default` button is clicked on the notification, notification tray should automatically close and focus on the default browser action sheet

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone/Tablet
   - Android version: 8.1.0/9.0
   
## Brave version
1.0.99 and 1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Not exactly like #1417 but somewhat similar
#1677 should have fixed this

**Comment by deeppandya** [comment]
@srirambv i verified this issue in pixel3xl  with android Q and samsung s8 plus with android 9. and it seems to be working. can you please confirm ?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc2 x64 build
* Verified clicking on the notification closes the notification tray and brings focus to default browser selection window
