### ISSUE TITLE
The sample ad notification is NOT fired if rewards is enabled from the hamburger menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1787]
## Description 
Follow up of #1754
The sample ad notification is NOT fired if rewards is enabled from the hamburger menu

## Steps to reproduce 

STR1

   1. Clean profile 1.0.95
   2. Upgrade to ads build (v1.1.0-brave-ads-5)
   3. Cancel the `Enable Brave Rewards` I M IN popup
   4. Enable rewards through the hamburger menu     
   5. Enable Ads switch in Brave Rewards panel

STR2:

   1. Clean profile v1.1.0-brave-ads-5
   2. Enable rewards through the hamburger menu
   3.  Enable Ads switch in Brave Rewards panel
   

## Actual result 
The sample ad notification is NOT fired if rewards is enabled from the hamburger menu

## Expected result
The sample ad notification should be fired

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version:5.1.1
   
## Brave version
v1.1.0-brave-ads-5)
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @aekeus @tmancey @yachtcaptain23 

Please close the issue if it's expected. Thanks!

**Comment by yachtcaptain23** [comment]
Resolved by https://github.com/brave/brave-core/pull/2774

**Comment by yachtcaptain23** [comment]
@GeetaSarvadnya, "Join Rewards" enables Ads only if the app is a new install. 

This is from `BraveRewardsPanelPopup.java`

```
        if (btJoinRewards != null) {
          btJoinRewards.setOnClickListener((new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mBraveRewardsNativeWorker != null && false == mWalletCreateInProcess) {
                    mBraveRewardsNativeWorker.CreateWallet();
                    mWalletCreateInProcess = true;
                    startJoinRewardsAnimation();
                    if (PackageUtils.isFirstInstall(context)) {
                        BraveAdsNativeHelper.nativeSetAdsEnabled(Profile.getLastUsedProfile());
                    }
                }
            }
          }));
        }
```

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm `v1.1.0-brave-ads-6`
  - Verified the description, the sample as notification is fired in both the conditions (STR1, STR2)
  - Encountered https://github.com/brave/browser-android-tabs/issues/1808
