### ISSUE TITLE
Android Onboarding

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1794]
# Test Plan
See https://github.com/brave/browser-android-tabs/issues/1794#issuecomment-514405807
# 

 ## Description
Make a new onboarding experience for Android, covering new users in and out of ad regions.
Product spec: https://docs.google.com/document/d/10VABhLEq2CxJO12OP85H5tfK_hQLRhuTQZWOpu-eW_o/edit?usp=sharing

## Designs
![android 1](https://user-images.githubusercontent.com/2388823/60923597-17b1ed80-a254-11e9-94a5-93230663c450.png)
![android 2](https://user-images.githubusercontent.com/2388823/60374215-1e20a980-99b8-11e9-9c58-6399ed5efad4.png)
![android 3](https://user-images.githubusercontent.com/2388823/60374022-41972480-99b7-11e9-98c7-085ed93de0f1.png)
![android 3 - terms 1](https://user-images.githubusercontent.com/2388823/60374059-64c1d400-99b7-11e9-8e32-d6cd7969b8ae.png)

The user must tap on the checkbox for the 'AGREE' button to become enabled:

![android 3 - terms 2](https://user-images.githubusercontent.com/2388823/60374079-77d4a400-99b7-11e9-8095-bf9091ee8efb.png)

Terms of Use link takes the user to a webview popover:

![android 3 - terms 3](https://user-images.githubusercontent.com/2388823/60374090-84f19300-99b7-11e9-93c7-36f0226f017e.png)

There is a 3-second timer on the next screen. The gradient countdown timer makes one full rotation in 3 seconds.

![android 4](https://user-images.githubusercontent.com/2388823/60374123-b10d1400-99b7-11e9-926a-af16dfec8e65.png)

Show system notification when timer hits 0.

![android 5](https://user-images.githubusercontent.com/2388823/60374159-ddc12b80-99b7-11e9-9971-e55f48c9982b.png)

There is a 1-second delay before the content from the next screen fades in:

![android 6](https://user-images.githubusercontent.com/2388823/60374177-f03b6500-99b7-11e9-817c-fe052c3ef925.png)

"I didn't see an ad" link takes the user to here:

![android 7](https://user-images.githubusercontent.com/2388823/60374190-ff221780-99b7-11e9-8f87-aae051f36f9c.png)

Tapping "Start browsing" takes the user to the new tab page.

The transition between slides is 0.3s fade out+fade in.

### In ad region
Show search engine selection, Brave Shields explanation, Brave Rewards opt-in with Terms of Service, and ad onboarding.

![user flow - android onboarding ads available](https://user-images.githubusercontent.com/2388823/60930225-8cdbed80-a269-11e9-9f74-55e6cf1634a2.png)

### Out of ad region
Show search engine selection, Brave Shields explanation, and Brave Rewards opt-in with Terms of Service.

![user flow - android onboarding ads unavailable](https://user-images.githubusercontent.com/2388823/60930232-91a0a180-a269-11e9-9b43-be8c4f07c1ee.png)

For this user segment, the text on the Brave Rewards should not mention ads: 

> Support your favorite websites and creators based on your attention.

![ads unavailabe](https://user-images.githubusercontent.com/2388823/60374287-912a2000-99b8-11e9-8948-76ae62cfbade.png)

Grab the assets: 
[svg assets.zip](https://github.com/brave/browser-android-tabs/files/3341038/svg.assets.zip)
[png assets.zip](https://github.com/brave/browser-android-tabs/files/3375172/png.assets.zip)

Abstract link for more CSS and plain text: https://share.goabstract.com/8e89e48d-805f-4808-aaad-86311b339e21

**Comment by karenkliu** [comment]
@deeppandya added design specs for you!

**Comment by karenkliu** [comment]
@EyanGoldman @anthonypkeane the user flows here still say for existing users we should "show this user flow again after X period of time if the user skipped it previously"; any thoughts on what that period of time should be?

**Comment by EyanGoldman** [comment]
@karenkliu this spec/ticket is just new user onboarding. Will write up an additional one for existing users.

**Comment by deeppandya** [comment]
@karenkliu can you share the color codes used in on boarding ?

**Comment by karenkliu** [comment]
Removed info about existing users.

**Comment by karenkliu** [comment]
Hi @deeppandya , thanks for your updates. Based on your feedback, let's remove the custom knob on the timer element for now, and only keep the gradient:

![android 4](https://user-images.githubusercontent.com/2388823/60542941-f38d6400-9cc9-11e9-919f-b12e857d47be.png)
We can implement the custom knob on the timer at a later point.

Gradient values:
start #4F30AB
middle #FF1893
end #FA7250

Also, here are the SVG assets for the search engines:
[search engines.zip](https://github.com/brave/browser-android-tabs/files/3352222/search.engines.zip)

**Comment by deeppandya** [comment]
@karenkliu thank you for the update. i will update the UI.

**Comment by karenkliu** [comment]
Hi @deeppandya -

1. There's a small copy change needed due to the new copy on the Google Play Store screenshots. Can you update the text on Brave Rewards to say _"Earn tokens for seeing privacy-respecting ads. Use them to support your favorite sites and creators."_

![android 3](https://user-images.githubusercontent.com/2388823/60834910-a51f1000-a176-11e9-98ad-814f504daf38.png)

2. Based on your feedback on the Android app configuration and its inability to support SVGs, here are PNGs suitable for 3 different device ranges in case we can't update the app in time: 
[png assets.zip](https://github.com/brave/browser-android-tabs/files/3369841/png.assets.zip)

3. Below is a prototype of the desired transition between slides in the onboarding flow:

![slide transition](https://user-images.githubusercontent.com/2388823/60836057-9128dd80-a179-11e9-8d05-1696cf4eb80a.gif)
higher res video version:
[slide transition.mp4.zip](https://github.com/brave/browser-android-tabs/files/3369875/slide.transition.mp4.zip)

During the transition: the content in the white panel fades out, the white bg resizes to the appropriate height for the next screen, and the new content fades in.
Please see if we can use this kind of smooth animated transition for the onboarding flow.

**Comment by karenkliu** [comment]
Hi @deeppandya, thanks for sharing your latest prototype. Here's the aggregated feedback as well as some additional design feedback (some of this you may have already heard via Slack and addressed):

![onboarding QA 1](https://user-images.githubusercontent.com/2388823/60915011-a0725e80-a23f-11e9-8bee-4d337789f0b9.png)

**Comment by karenkliu** [comment]
@deeppandya  FYI, I updated the search engine screen with new layout specs and added the Brave logo to the PNG assets zipped folder.

**Comment by deeppandya** [comment]
@karenkliu can share right arrow icons for next button ? both active and inactive icons

**Comment by deeppandya** [comment]
@karenkliu if we specify static height for bottom panel, it would look weird on larger screen size. what do you think ?

**Comment by karenkliu** [comment]
@deeppandya  The right arrow icon is the default Android one...is that not available?

Re: static heights for the bottom panel - sure, we can try using percentages instead.

**Comment by deeppandya** [comment]
@karenkliu  yes the right arrow icon is available from android assets but i have to export it. do you want me to do it ? or you can provide the icons.

**Comment by karenkliu** [comment]
@deeppandya Updated zipped PNG folder with right arrow icon asset.

**Comment by EyanGoldman** [comment]
Testing Plan (Applies to #1794, #1797, #1848 and #1847):

New Ads Regions = Ireland, New Zealand, Australia
Previous Ads Regions = USA, UK, Canada, France, Germany
All Ads Regions =  Ireland, New Zealand, Australia, USA, UK, Canada, France, Germany

**Scenarios and Expected Behavior:**

Existing User New Ads Region:
Rewards Previously On:
- #1797 flow with "Brave Ads is Here!" card. 

Rewards Previously Off:
- #1797 flow with "Brave Rewards" card.

Existing User Previous Ads Region:
- Open app as if nothing changed (no onboarding)

Existing User Everywhere else:
- Open app as if nothing changed (no onboarding)

New User All Ads Region:
Ads Available:
- Contains Rewards/Ads Flow

New User Everywhere Else:
- Contains Rewards Flow (no ads or countdown timer)

**Comment by EyanGoldman** [comment]
Testing Plan for Welcome Tour:
As mentioned in the spec, the user can repeat the onboarding process via the settings menu. The button lives in "Settings" > "Basics" > "Welcome Tour". On press, a modal reading:
"Relaunching the Welcome Tour will not affect any system settings"
"Cancel" | "Continue"

"Cancel" will close modal, "Continue" will relaunch the onboarding which coordinates with the user's regions with the following changes:

SE Page: Nothing will be alterable as relaunching welcome tour is for educational purposes not to change system settings. 

Shields Page: No changes

Brave Rewards: Buttons will read "SKIP" and "NEXT", no TOS page as they either already agreed and can't re-agree or did not agree and need to join BR through the panel or settings. 

Ads Staging: No changes.

**Comment by srirambv** [comment]
@EyanGoldman @anthonypkeane 

```
Existing User Previous Ads Region:
Open app as if nothing changed (no onboarding)

Existing User Everywhere else:
Open app as if nothing changed (no onboarding)
```

For these two scenarios are we not going to consider showing the rewards card after 60/120 days of an upgrade depending on the state of rewards? 

Also for new ads regions, does the 60/120 days period work in conjunction with any new releases that will happen in that time frame and still continue to prompt the user after 60/120days have passed?

**Comment by EyanGoldman** [comment]
@srirambv 
Scenario 1: Nothing should happen

Scenario 2: Should launch the modals as scheduled regardless of whether we update the app or not.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build

Existing Ads locale (US/Canada)
```
Scenario 1:
- Install Playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding flow is shown
- Relaunch welcome tour, shows previously set SE as default, no ToS and join rewards is shown, shows sample ad notification at the end of the welcome tour

Scenario 2: 
- Install Playstore build, do not enable rewards
- Upgrade to 1.3.0, no onboarding flow is shown 
- Relaunch welcome tour, shows previously set SE as default, not ToS and join rewards is shown, shows sample ad notification at the end of the welcome tour

Scenario 3: 
- Clean install 1.3.0
- Change SE and join rewards, sample ad shown and updates SE for both normal/private tab
- Launch welcome tour, shows changed SE as default and doesn't show ToS and join rewards, shows sample ad at the end of the welcome tour

Scenario 4: 
- Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained, sample ad notification is shown at the end of the welcome tour
```
New Ads supported regions (Australia/Ireland/NZ)
```
Scenario 1:
- Install playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding is shown as its ads is enabled now
- Relaunch welcome tour, shows already set SE as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour 

Scenario 2:
- Install playstore build, do not enable rewards
- Upgrade to 1.3.0, only rewards onboarding is shown 
- Enable rewards on onboarding shows sample ad notification
- Relaunch welcome tour, existing SE is set as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is enabled and opted in now

Scenario 3:
- Clean install 1.3.0
- Change default SE and opt-into rewards via onboarding, SE changes are set for both normal/private tab and rewards is enabled
- Relaunch welcome tour, custom SE is shown as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 4:
 - Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained, sample ad notification shown at the end of the welcome tour
```
Ads unsupported regions (India/SA)
```
Scenario 1:
- Install playstore build, do not enable rewards
- Upgrade to 1.3.0, in-app enable rewards modal is shown as expected, no sample ad notification shown when opted in
- Relaunch welcome tour, existing SE is set as default, no ToS and Join rewards message shown, no sample ad notification is shown

Scenario 2:
- Install Playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding shown as expected
- Relaunch welcome tour, existing SE is shown as default, no ToS and Join rewards shown, no sample ad notification is shown

Scenario 3:
- Clean install 1.3.0
- Change default SE and opt-into rewards via onboarding, SE changes are set for both normal/private tab and rewards is enabled, no sample ad is shown
- Relaunch welcome tour, custom SE is shown as default, no ToS and Join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 4:
 - Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, no sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained no sample ad shown at the end of the welcome tour
```
Qwant Regions(France/Germany)
```
- All scenarios fo existing region worked
- Default SE was Qwant on clean install for both normal and private tab
- Upgrade scenarios retained previously set custom SE
- Sample ad notification open translated landing page accordingly to region 
```

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build

Existing Ads locale (US/Canada)
```
Scenario 1:
- Install Playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding flow is shown
- Relaunch welcome tour, shows previously set SE as default, no ToS and join rewards is shown, shows sample ad notification at the end of the welcome tour

Scenario 2: 
- Install Playstore build, do not enable rewards
- Upgrade to 1.3.0, no onboarding flow is shown 
- Relaunch welcome tour, shows previously set SE as default, not ToS and join rewards is shown, shows sample ad notification at the end of the welcome tour

Scenario 3: 
- Clean install 1.3.0
- Change SE and join rewards, sample ad shown and updates SE for both normal/private tab
- Launch welcome tour, shows changed SE as default and doesn't show ToS and join rewards, shows sample ad at the end of the welcome tour

Scenario 4: 
- Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained, sample ad notification is shown at the end of the welcome tour
```
New Ads supported regions (Australia/Ireland/NZ)
```
Scenario 1:
- Install playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding is shown as its ads is enabled now
- Relaunch welcome tour, shows already set SE as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour 

Scenario 2:
- Install playstore build, do not enable rewards
- Upgrade to 1.3.0, only rewards onboarding is shown 
- Enable rewards on onboarding shows sample ad notification
- Relaunch welcome tour, existing SE is set as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is enabled and opted in now

Scenario 3:
- Clean install 1.3.0
- Change default SE and opt-into rewards via onboarding, SE changes are set for both normal/private tab and rewards is enabled
- Relaunch welcome tour, custom SE is shown as default, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 4:
 - Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained, sample ad notification shown at the end of the welcome tour
```
Ads unsupported regions (India/SA)
```
Scenario 1:
- Install playstore build, do not enable rewards
- Upgrade to 1.3.0, in-app enable rewards modal is shown as expected, no sample ad notification shown when opted in
- Relaunch welcome tour, existing SE is set as default, no ToS and Join rewards message shown, no sample ad notification is shown

Scenario 2:
- Install Playstore build, enable rewards
- Upgrade to 1.3.0, no onboarding shown as expected
- Relaunch welcome tour, existing SE is shown as default, no ToS and Join rewards shown, no sample ad notification is shown

Scenario 3:
- Clean install 1.3.0
- Change default SE and opt-into rewards via onboarding, SE changes are set for both normal/private tab and rewards is enabled, no sample ad is shown
- Relaunch welcome tour, custom SE is shown as default, no ToS and Join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 4:
 - Clean install 1.3.0
- Select a different SE and skip on the SE onboarding page
- No custom SE is set, rewards isn't enabled no sample ad is shown
- Relaunch welcome tour, default SE is shown, no ToS and Join rewards is shown, no sample ad notification is shown at the end of the welcome tour. Rewards is not enabled as expected

Scenario 5:
- Clean install 1.3.0
- Select a custom SE and tap Next
- Skip the onboarding flow
- Rewards isn't enabled, Custom SE is set for both normal and private tab
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 6: 
- Clean install 1.3.0
- Select a custom SE and tap Next
- Continue to ToS and Join Rewards page
- Select "Do not agree" and select "No Thanks"
- Custom SE is set, Rewards isn't enabled 
- Relaunch welcome tour, custom SE is shown as default, not ToS and join rewards is shown, no sample ad notification is shown at the end of the welcome tour

Scenario 7:
- Clean install 1.3.0
- Select `Qwant` as SE and finish onboarding
- Open New Private tab and select DDG as default for Private tab
- Normal tab retains Qwant as SE and DDG for Private
- Relaunch Welcome tour, custom SE for both normal(Qwant) and Private(DDG) are retained no sample ad shown at the end of the welcome tour
```
Qwant Regions(France/Germany)
```
- All scenarios fo existing region worked
- Default SE was Qwant on clean install for both normal and private tab
- Upgrade scenarios retained previously set custom SE
- Sample ad notification open translated landing page accordingly to region 
```

**Comment by GeetaSarvadnya** [comment]
Verification above scenarios in Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.3.0-rc1	
- For Qwant Regions(France/Germany) - Scenarios 3, 6 and 7 are failing unable to Join rewards through onboarding (https://github.com/brave/browser-android-tabs/issues/1991)
- Rest other regions work fine for all 7 scenarios.
