### ISSUE TITLE
Dark Mode / Light Mode / Private

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#1798]
This issue was created to track styling relating to 
![Screen Shot 2019-07-01 at 12 16 27 PM](https://user-images.githubusercontent.com/318119/60454779-60d1c400-9bfa-11e9-825a-6ef3403d1289.png)
Dark/Light/Private modes.

**Comment by jamesmudgett** [comment]
Dark mode shields panel styling
![Screen Shot 2019-07-01 at 12 19 08 PM](https://user-images.githubusercontent.com/318119/60454813-78a94800-9bfa-11e9-9023-da3442a356d9.png)

**Comment by miladmaz12** [comment]
related to #81

**Comment by karenkliu** [comment]
@deeppandya Please include minor adjustments to onboarding for dark mode:

![dark mode 1](https://user-images.githubusercontent.com/2388823/61981220-da689200-afad-11e9-8cf1-572afc10f148.png)
![dark mode 2](https://user-images.githubusercontent.com/2388823/61981226-dccaec00-afad-11e9-8293-613366416b27.png)
![dark mode 3](https://user-images.githubusercontent.com/2388823/61981229-df2d4600-afad-11e9-86fd-8e6faafbf6a5.png)
![dark mode 4](https://user-images.githubusercontent.com/2388823/61981234-e18fa000-afad-11e9-95cc-571312a23f51.png)
![dark mode 5](https://user-images.githubusercontent.com/2388823/61981236-e3f1fa00-afad-11e9-9218-3f09e7148530.png)

**Comment by deeppandya** [comment]
@karenkliu we don't have indicators at bottom. so do you want to add it for **dark mode** ?

**Comment by karenkliu** [comment]
@deeppandya Oh - you're completely right! Please ignore the indicator; that's a leftover design element that should've been removed. I removed the screen from my previous comment as well.

**Comment by EyanGoldman** [comment]
>= Android Q:
- "Settings" > "Appearance" add a new dropdown menu titled "Theme" with three options: "Dark", "Light", "System" (default). "Dark" sets browser to always dark mode, light sets browser to always light mode and system has it follow the corresponding android theme.
< Android Q:
- In the kebab menu add a toggle titled "Dark Mode" (default off) which when toggled on turns the browser dark and when off turns the browser light. It should be below "Brave Rewards"

**Comment by EyanGoldman** [comment]
**Menu and toggle behavior:**
All Versions:
Add a dropdown box in "Settings" > "Appearance" titled "Theme" (options will vary w/ Android Version, see below)
Android Q++:
- In the kebab menu, above "Brave Rewards" add a item called "Theme" with a light icon, dark icon and a right arrow
- Dark icon makes the browser go to dark mode
- Light icon makes the browser go to light mode
- Arrow will take user to "Settings" > "Appearance". In the dropdown box will be "Dark", "Light", "System" (default). If System is selected, the browser will follow OS theme, if "Dark" selected browser goes to Dark Mode, if "Light" selected browser will go to Light Mode. The icons in kebab menu will parity dark/light selections even when in "System". 

< Android Q:
Same as above but without a "System" selection in the dropdown box as only Android Q supports this functionality

@karenkliu can provide correct icons and mocks if needed

**Comment by deeppandya** [comment]
@karenkliu can you please provide mocks and icons for this ?

**Comment by karenkliu** [comment]
@deeppandya 
![dark menu 1](https://user-images.githubusercontent.com/2388823/62667616-51524300-b93d-11e9-8c7f-2777fce051a3.png)

Tapping "Color theme..." shows a system dialog with theme options

![dark menu Q++](https://user-images.githubusercontent.com/2388823/62667617-51ead980-b93d-11e9-997e-8d85f0840e40.png)

**Comment by EyanGoldman** [comment]
Updated Menu and toggle behavior:
**All Versions:**
Add a kebab menu item title "Themes" in the kebab menu under Brave Rewards
**Android Q++:**
Three modal options "Light theme", "Dark theme", "System default"
Dark icon makes the browser go to dark mode
Light icon makes the browser go to light mode
System default icon makes the browser follow OS theme
**< Android Q:**

Same as above but without a "System default" option in the modal as only Android Q supports this functionality

**Comment by srirambv** [comment]
> Add a kebab menu item title "Themes" in the kebab menu under Brave Rewards

I think its better if this goes under `Display` instead of under `Advanced`. Theme can be the second entry under `Appearance`

**Comment by EyanGoldman** [comment]
@srirambv are you saying instead of having it in the kebab menu? With the way @karenkliu designed it, we wouldn't even need a page on the settings menu

**Comment by deeppandya** [comment]
@EyanGoldman @jamesmudgett @karenkliu what should we do if night mode experiment is enabled for the device ? in that case, we already show **Themes** after `Home page` in settings.

**Comment by EyanGoldman** [comment]
We should just add a second instance of the above modal built into the settings page where "Themes" currently is. (regardless of if night mode experiment is on or off) which will parity the configuration of the above modal. Wasn't aware that we already had a "Themes" page built into the browser.

**Comment by srirambv** [comment]
>@srirambv are you saying instead of having it in the kebab menu? With the way @karenkliu designed it, we wouldn't even need a page on the settings menu 

yup my bad. I misunderstood that this was an entry in the settings menu. @karenkliu design looks good :+1:

**Comment by deeppandya** [comment]
@EyanGoldman what should be the default option for devices < android Q ? for > android Q devices i believe it should be **system default**\

**Comment by EyanGoldman** [comment]
@deeppandya light mode

**Comment by deeppandya** [comment]
@EyanGoldman @karenkliu we should keep the text for different theme options same as we have in settings. in settings for **Light mode**, it's **Light** and for dark mode it's **Dark**

**Comment by karenkliu** [comment]
@deeppandya Yes, follow text and order in Settings. I wasn't aware of the settings design.

**Comment by deeppandya** [comment]
And one last thing, @karenkliu for default dialog in android, we don't have title in centre, **Cancel** button has the same color as **Done** and radiobuttons doesn't have icons. if we need to modify any of above things, we need to have a custom dialog. and i wouldn't recommend it.

**Comment by karenkliu** [comment]
@deeppandya Aw, no icons? Alright..

**Comment by EyanGoldman** [comment]
One more thing. I think without the icons "Follow system" would be clearer than "System default"

**Comment by deeppandya** [comment]
@EyanGoldman i am trying keep it as we have in settings and in settings we use `System defaults`

**Comment by deeppandya** [comment]
@EyanGoldman after spending time on night mode experiment on android O, i believe we should have all 3 options in the dialog. i checked the theme settings for night mode experiment enabled device on android O and it shows all 3 options and **System defaults** is the selected option by default.

**Comment by EyanGoldman** [comment]
@deeppandya 
For < Android Q is light mode as system default isn't an option, right?
For >= Android Q we should do system default.

**Comment by deeppandya** [comment]
> @deeppandya
> For < Android Q light mode. As system default isn't an option, right?
> For >= Android Q we should do system default.

@EyanGoldman i have samsung S8 plus and i can see and activate **Light mode** for chrome and brave browser.

**Comment by EyanGoldman** [comment]
Update: We will no longer need the modal in the kebab menu.

**Comment by deeppandya** [comment]
@jamesmudgett can you provide me the color codes for brave shield panel ?

**Comment by szaimen** [comment]
Any update on this?

**Comment by deeppandya** [comment]
@srirambv private mode theme is not in the scope of this ticket.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified able to switch between light/dark mode via option in settings
* Verified Shields update to dark when browser theme is set to dark
* Verified Shields is light when browser theme is set to light
* Verified dark mode doesn't affect rewards panel notifications (Verified here https://github.com/brave/browser-android-tabs/issues/2081#issuecomment-535031857)
* Verified there is no private theme when a private tab is opened
* Verified context menu's respect the browser theme and inherits the theme (verified here https://github.com/brave/browser-android-tabs/issues/2073#issuecomment-534086272)
* Verified browser theme updates instantly when theme is changed via settings
* Verified Sync pages are dark-themed when browser theme is dark (Verified here https://github.com/brave/browser-android-tabs/issues/2075#issuecomment-534091523)
*Verified rewards page and internal pages are not affected by browser theme (out of scope)
