### ISSUE TITLE
Cannot show desktop version of website permanently

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-android-tabs#180]
Mobile websites are very limited in use are just like WAP sites in the early days of mobile browsers. 
Modern Android (and iOS) browsers, including Brave, run on modern devices are well capable to show full desktop sites.
However, the 'Show Desktop' checkbox in the settings of Brave is used only once, so reopening the same website opens the mobile site again. Many people don't like this.
Can there be a generic user agent setting, e.g. 'mobile / desktop / customizable' where you can fill in the UA in the latter case (like Dolphin) ?
Or at least a setting on a per-website basis ?

**Comment by SergeyZhukovsky** [comment]
We have to add that option in Settings.

**Comment by SergeyZhukovsky** [comment]
That is duplicated https://github.com/brave/browser-android-tabs/issues/124
