### ISSUE TITLE
New share button not clickable

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1806]
## Description 
The share icon on the three dot button is not clickable. 

## Steps to reproduce 

   1. Navigate to website
   2. Tap on three dot button
   3. Share greyed out

## Actual result 
Share is greyed out and not clickable

## Expected result
Share should be not greyed out and clickable

## Issue reproduces how often 
Everytime

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel 3 XL
   - Android version: 10
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
Is this on Android Q?

**Comment by EyanGoldman** [comment]
Yes

**Comment by EyanGoldman** [comment]
Replicated on Samsung Galaxy S10 running Android 9
![Screenshot_20190709-094934_Brave](https://user-images.githubusercontent.com/8962135/60907734-1de1a300-a22f-11e9-9ce1-ff69161df71f.jpg)

**Comment by samartnik** [comment]
@EyanGoldman it doesn't look greyed out in the picture. Is it just not clickable on Samsung Galaxy S10?

**Comment by EyanGoldman** [comment]
Just realized I was looking at the forward button as we originally discussed using an arrow for the Share button. Sorry about that! Closing this ticket.
