### ISSUE TITLE
onboarding modal displayed on x86 devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1807]
## Description 
When upgrading from 1.0.99 to 1.1.0 ads-6 build, the modal to enable BR is displayed (even if BR is not enabled via flags).

Additionally, on a clean install for 1.1.0 ads-6 build the modal is displayed after 24 hours (even if BR is not enabled via flags).

## Steps to reproduce 
Scenario 1
   1. Clean install 1.1.0 ads-6.
   2. Wait 24h.
   3. See modal to try BR.

Scenario 2:
1. Install 1.0.99
2. Upgrade to 1.1.0 ads-6.
3. See modal to try BR.

## Actual result 
Modal is displayed
![Screenshot_20190703-134229](https://user-images.githubusercontent.com/28145373/60614157-61a15c00-9d9a-11e9-8c4f-e57d792af7e3.jpg)

## Expected result
No modal.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? 1.1.0 ads-6

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.1.0 ads-6

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
also to consider, unsure what should happen in this scenario:
1. Install 1.0.99 on x86
2. Enable BR
3. Upgrade to 1.1.0 ads-6
---> currently getting modal, unsure if I should be though

**Comment by anthonypkeane** [comment]
@samartnik is going to work on https://github.com/brave/browser-android-tabs/issues/1555 which will disable BR on x86

x86 devices should not get the modal.

**Comment by LaurenWags** [comment]
Scenario 1 - PASS
1. Clean install 1.1.0 ads-7.
2. Wait 24h.
3. Verified no modal to try BR.

Scenario 2 - PASS
1. Install 1.0.99
2. Upgrade to 1.1.0 ads-7.
3. Verified no modal to try BR.
4. Verified 24h later there is still no modal to try BR.

Verified with Asus Zenfone (Android 6) with 1.1.0 ads-7 BraveModernx86.apk
