### ISSUE TITLE
Enable rewards doesn't auto enable ads - Follow up of #1694 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1808]
# Test Plan
https://github.com/brave/browser-android-tabs/issues/1808#issuecomment-508873110

#
## Description 
Enable rewards doesn't auto-enable ads - Follow up of #1694 

## Steps to reproduce 

Scenario 1:

     1. Clean install latest ads build (v1.1.0-brave-ads-6)
     2. Enable rewards through the hamburger menu
     3. Ads switch is not enabled
     

Scenario 2:

     1. Clean install 1.0.95
     2. Upgrade to latest ads build (v1.1.0-brave-ads-6)
     3. Enable rewards through the hamburger menu
     4. Ads switch is not enabled

Scenario 3:

     1. Installed play store version `1.0.99` 
     2. Upgrade to latest ads build (v1.1.0-brave-ads-6)
     3. Cancel the `I'M IN` notification by clicking on `x` in the popup
     4. Enable rewards through BR panel
     5. Ads switch is not enabled

## Actual result 
Ads switch is NOT enabled automatically

## Expected result

After enabling rewards ads switch should get enable automatically.

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3 
   - Android version: 5.1.1
   
## Brave version
BraveModernarm `v1.1.0-brave-ads-6`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @tmancey

**Comment by srirambv** [comment]
Auto Enable Ads test plan:

Scenario 1:

     1. Clean install ads build 
     2. Enable rewards through the hamburger menu
     3. Ads switch should be auto-enabled and sample ad should trigger
     
Scenario 2:

     1. Clean install 1.0.95/GPS build
     2. Upgrade to ads build 
     3. Enable rewards through the hamburger menu
     4.  Ads switch should be auto-enabled and sample ad should trigger

Scenario 3:

     1. Installed GPS build
     2. Upgrade to ads build
     3. Cancel the `I'M IN!` notification by clicking on `x` in the popup
     4. Enable rewards through BR panel
     5. Ads switch should be auto-enabled and sample ad should trigger


Onboarding Notifications Test Plan:
Scenario 1: 

    1. Install GPS build on an unsupported region
    2. Do not enable rewards
    3. Upgrade to ads build
    4. Verify "Enable Brave Rewards" in-app notification is shown 

Scenario 2:
    
    1. Install GPS build on an unsupported region
    2. Enable rewards
    3. Upgrade to ads build
    4. Verify no in-app onboarding message is shown

Scenario 3: 
   
    1. Install GPS build on a supported region
    2. Enable rewards
    3. Upgrade to ads build
    4. Select `I'M IN!` and enable rewards
    5. Quit and relaunch the browser, ensure no in-app onboarding modal is shown

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm `1.1.0-brave-ads-8` build

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A with Android 8.1.0 running 1.1.0-8 x64 ads build
  - Verified all onboarding scenarios and it worked fine
  - Verified auto-enable ads scenarios worked
  - Logged #1832 for scenario 3 of auto-enable ads
* Verification passed on Huawei P20 on Android 8.1.0 running 1.1.0-8 x64 ads build
  - Verified all onboarding scenarios and it worked fine
  - Verified auto-enable ads scenarios worked
  - Encountered #1832 on mobile as well 
* Verification passed on OnePlus 6T on Android 9.0 running 1.1.0-8 x64 ads build
  - Verified all onboarding scenarios and it worked fine
  - Verified auto-enable ads scenarios worked
  - Encountered #1832 on mobile as well
