### ISSUE TITLE
Incorrect onboarding notification shown 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1813]
## Description 
Incorrect onboarding notification shown 

## Steps to reproduce 

   1. Clean install 1.1.0-6
   2. Enable rewards via hamburger menu, ads is off
   3. Relaunch app after min time, shows incorrect onboarding notification

## Actual result 
Shows `Enable Rewards` onboarding notification

## Expected result
Should show `Brave ads are here` onboarding notification

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 8.1.0
   
## Brave version
1.1.0-6 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Issue reproduced by @LaurenWags  
Should be fixed as part of  #1808

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on Samsung Galaxy J3 version 5.1.1

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm 1.1.0-brave-ads-8 build
