### ISSUE TITLE
Enable taking screenshots in both normal and private windows

### ISSUE THREAD

**Issue by karenkliu** [brave/browser-android-tabs#1814]
## Description
Currently, the screenshot function is disabled. Enable it so that the user can take screenshots in both normal and private windows.
(This function would also help immensely for internal use - preparing assets for the Google Play Store).

**Comment by srirambv** [comment]
Android blocks taking screenshots/screen recording on private windows. Not sure if we can override these at app level.

**Comment by deeppandya** [comment]
@karenkliu i have verified this and as @srirambv has mentioned it's not possible. so i think we should close this ticket.

**Comment by karenkliu** [comment]
@deeppandya Okay, thanks for the update.
