### ISSUE TITLE
Sample ads notification is shown for an unsupported region when rewards is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1816]
## Description 
Sample ads notification is shown for an unsupported region when rewards is enabled

## Steps to reproduce 

   1. Set the device to an unsupported region
   2. Clean install 1.1.0-6 ads build
   3. Enable Rewards, shows sample ads notification
   4. Open Rewards shows ads not available message

## Actual result 
Sample ads notification is shown for an unsupported region when rewards is enabled

## Expected result
Should not show ad notification if ads are not supported for a region

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 8.1.0
   
## Brave version
1.1.0-6 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Issue not reproducing in the following scenarios
- Upgrade from playstore build with rewards enabled
- Upgrade from playstore build without rewards enabled
- Clean install enable rewards via the hamburger menu

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 5.1.1 running BraveModernarm `1.1.0-brave-ads-7` build
  - Verified the STR from the description, verified there is no sample ad notification for ads not supported 
     region
  - Installed 1.0.99 and upgraded it to `1.1.0-brave-ads-7`, verified there is no sample ad notification for 
     ads not supported region
  - Installed 1.0.99, enabled rewards and upgraded it to `1.1.0-brave-ads-7`, verified there is no sample ad 
     notification for ads not supported region

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 5.1.1 running `1.1.0-brave-ads-7` build
 - Installed `1.1.0-brave-ads-7` build, enabled rewards and verified there is no sample ads notification for ads not supported region
