### ISSUE TITLE
Refactor warn message on for sync, followup to  #1475

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1819]
## Description 
Refactor warn message on for sync, followup to  #1475

## Steps to reproduce 

   1. Update/Clean install 1.1.0-6 x64 ads build
   2. Open sync window to add a new device
   3. Shows warn text which isn't quite clear as warning message

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/60688951-912d9280-9e86-11e9-8d73-cc22319bc644.png)

## Expected result
Warning message should be prominent to warn users

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.0-6

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by EyanGoldman** [comment]
@jamesmudgett  do we have the updated text for this?

**Comment by deeppandya** [comment]
Expected Behaviour : for QR code screen
![Screenshot_20190821-164041_Brave](https://user-images.githubusercontent.com/5146988/63467269-110dbd00-c433-11e9-8748-f2d8c33d7b7b.jpg)

and for code words screen
![Screenshot_20190821-164048_Brave](https://user-images.githubusercontent.com/5146988/63467295-2256c980-c433-11e9-92a2-949d93eeb8c8.jpg)

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta-x64 build
  * Verified code-words has the refactored warn message
  * Logged #1977 for missing refactored warn message on QR Code
