### ISSUE TITLE
Security reports option wording needs to be changed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#182]
![image](https://cloud.githubusercontent.com/assets/17010094/24247785/ff5d1e9a-0fc4-11e7-9587-099662eaa9e4.png)

**Comment by SergeyZhukovsky** [comment]
Removed that menu for now as we don't send any reports currently. The functionality was removed initially btw, it is just the menu appeared after the cr57 merge.
https://github.com/brave/browser-android-tabs/commit/67b9631907381ce9ecaf9e05f3a32ebf132db31a
