### ISSUE TITLE
Clicking on sample ad notification doesn't bring Brave in foreground

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1820]
## Description 
Clicking on sample ad notification doesn't bring Brave in foreground

## Steps to reproduce 

   1. Clean install 1.1.0-7 ads build
   2. Enable rewards via panel and wait for sample ad notification to show up
   3. Background the app 
   4. Tap on the sample ad notification from the tray
   5. Brave isn't brought into focus
   6. Open Brave again, landing page for sample ad is already opened and is the active tab

## Actual result 
[SampleAds.zip](https://github.com/brave/browser-android-tabs/files/3363784/SampleAds.zip)

## Expected result
Should bring app to focus when the sample ad is clicked 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 8.1.0/9.0
   
## Brave version
1.1.0-7 x64 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm `1.1.0-brave-ads-8`
