### ISSUE TITLE
Rename repo from 'browser-android-tabs' to 'brave-android'

### ISSUE THREAD

**Issue by jaredsburrows** [brave/browser-android-tabs#1827]
The iOS repo is 'brave-ios', can we make this similar by naming this 'brave-android'?

**Comment by srirambv** [comment]
@bbondy or @SergeyZhukovsky to confirm if once we move over to brave-core I think this repo would be deprecated as well.

**Comment by tomlowenthal** [comment]
Yes, but that's a way out, @srirambv. I think this rename makes sense in the short term.

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by srirambv** [comment]
@jaredsburrows as mentioned before this repo will be deprecated soon so no need to rename it. We are moving to Android-core based on brave-core so all related issues will be logged on https://github.com/brave/brave-browser/ repo going forward. You will be able to choose Android/Desktop when you try to log an issue on brave-browser repo. Going to close the issue as wont fix

**Comment by jaredsburrows** [comment]
Sounds good.
