### ISSUE TITLE
Ads not auto enabled when rewards is enabled post upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1832]
## Description 
Ads not auto-enabled when rewards is enabled post-upgrade

## Steps to reproduce 

   1. Install playstore build, do not enable rewards
   2. Upgrade to ads build
   3. Close onboarding notification
   4. Enable Rewards via Panel, ads is not auto-enabled

## Actual result 
Ads is not auto enabled when rewards is enabled after upgrade

## Expected result
Should auto-enable ads and trigger sample notification 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.0-8 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on Samsung Galaxy J3 version 5.1.1 running `1.1.0-brave-ads-7` and  `1.1.0-brave-ads-8` build

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus 5 with Android 5.1 running 1.1.0 rc2 BraveModernarm.apk
