### ISSUE TITLE
New Shields Design For Desktop Parity

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1837]
Refer to https://github.com/brave/brave-browser/issues/3589

**Comment by deeppandya** [comment]
@karenkliu can you add mock ups for this ?

**Comment by szaimen** [comment]
Any update on this?

**Comment by karenkliu** [comment]
@anthonypkeane I think we said we would close this.

**Comment by szaimen** [comment]
Why?

**Comment by anthonypkeane** [comment]
Closing
