### ISSUE TITLE
Use new adBlock rust library

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1838]
Desktop ticket: https://github.com/brave/brave-browser/issues/4793

**Comment by samartnik** [comment]
Done in this branch https://github.com/brave/browser-android-tabs/tree/base-76.0.3809.80

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) on Android 6.0 with 1.2.0rc2 BraveModernx86.apk
