### ISSUE TITLE
Crash on showing ads notification on Android 6, when our app is not launched

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#1839]

**Comment by samartnik** [comment]
Steps to reproduce:
- on device with Android 6 or lower install Brave.
- join rewards
- quit app before educational notification pops up (here will be crash)

**Comment by LaurenWags** [comment]
Verified passed on LG Nexus 5 Android 5.1 device with 1.1.1 rc1 running BraveModernarm.apk. Reproduced issue using steps from https://github.com/brave/browser-android-tabs/issues/1839#issuecomment-510163498 and verified same steps did not produce crash on 1.1.1 rc1 build.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm v1.1.1-rc.2
