### ISSUE TITLE
Turning on Brave Ads will cause some websites to display the “something went wrong” error message

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1844]
## Description 
Turning on Brave Ads will cause some websites to display the “something went wrong” error message when attempting to access the website

## Steps to reproduce 

   1. Turn on Brave Ads
   2. Access reddit.com, espn.com, pro.coinbase.com, tzscan.io, smtickets.com or animepahe.com

## Actual result 
Page failed to load

## Expected result
Page should successfully load

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

https://community.brave.com/t/brave-ads-break-reddit-on-brave-browser-android/69955

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm v1.1.1-rc.1`
 - Sites `reddit.com`, `espn.com`, `pro.coinbase.com`, `tzscan.io`, `smtickets.com` and `animepahe.com` loaded successfully on a clean profile when Ads enabled
- Sites `reddit.com`, `espn.com`, `pro.coinbase.com`, `tzscan.io`, `smtickets.com` and `animepahe.com` loaded successfully on the upgraded profile when Ads enabled

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone running Android 6 using Brave 1.1.1 rc1 BraveModernx86.apk. Even though x86 does not have rewards, verified the sites mentioned load as expected on x86 device.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm v1.1.1-rc.1

 - Sites reddit.com, espn.com, pro.coinbase.com, tzscan.io, smtickets.com and animepahe.com
   loaded successfully on a clean profile when Ads enabled
 - Sites reddit.com, espn.com, pro.coinbase.com, tzscan.io, smtickets.com and animepahe.com
   loaded successfully on the upgraded profile when Ads enabled
