### ISSUE TITLE
Remove Previous New User Onboarding Modals

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1847]
# Test Plan
See https://github.com/brave/browser-android-tabs/issues/1794#issuecomment-514405807
# 
Once the onboarding flow has been implemented (#1794), the previous onboarding modals should be removed as they are redundant. This refers specifically to "New users (new installs) and existing users with Rewards disabled" section of https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit#heading=h.gxq6nh68vaay
Which means the "Brave Rewards are Here" first notification and subsequent re-notifications

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build 
* Verified no in-app onboarding modals are shown for existing and new ads supported region

Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build
* Verified no in-app onboarding modals are shown for existing and new ads supported region
