### ISSUE TITLE
Remove Previous Existing User Onboarding Modals

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1848]
Once the existing user ads available onboarding flow has been implemented (#1797), the previous Brave Ads are Here modals should be removed as they are redundant. This refers specifically to "Existing users who have Rewards enabled, but Ads are not enabled" section of https://docs.google.com/document/d/19afFFrojwlzzD_f7t-AXyNKT8299_lZ2xA_suHtB4gE/edit#heading=h.gxq6nh68vaay
Which means the "Brave Ads are Here" first notification and subsequent re-notifications

**Comment by srirambv** [comment]
Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta1-x64 build
  * Verified no in-app onboarding modals shown for users in existing and new ads supported region
  * Verified in-app rewards onboarding is only shown of existing users from the non-ads supported region

 Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build
  * Verified no in-app onboarding modals shown for users in existing and new ads supported region
  * Verified in-app rewards onboarding is only shown of existing users from the non-ads supported region
