### ISSUE TITLE
Uprgade to Chromium 75.0.3770.143

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#1853]

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/tree/base-75.0.3770.143

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm v1.1.2-rc.1

![image](https://user-images.githubusercontent.com/38657976/61350950-e1452580-a886-11e9-8dfc-e2da80330f88.png)
