### ISSUE TITLE
Crash when toggling Ads switch off

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1855]
## Description 
Intermittent crash when toggling Ads switch off

## Steps to reproduce 

   1. Enable Ads
   2. Toggle Ads switch on/off

## Actual result 
App crashes

## Expected result
App should not crash

## Issue reproduces how often 
Intermittent issue

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
@tmancey is there anything QA can try in terms of test cases? Or basically toggle `Ads` on/off several times and make sure there's no intermittent crashes?

Was the crash easy to reproduce originally?

**Comment by tmancey** [comment]
Crash would happen when switching ads off. Tests should include switching ads back on, visiting a page such as www.brave.com and making sure ads are shown. When switching off ads, all state is removed.

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A running 1.3.0 x64
