### ISSUE TITLE
Have device check for ads available in region

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1856]
@mandar-brave will fill in details

**Comment by mandar-brave** [comment]
Please upgrade regional support for New Zealand, Australia, and Ireland for Android Ads based off. The client needs to manually add these locale for Android users in those regions to use ads.

**Comment by tmancey** [comment]
This is a `bat-native-ads` issue which has been closed and merged with `android_75`, there is no need to make any `browser-android-tabs` changes

**Comment by srirambv** [comment]
@tmancey ok to close this issue if its already part of library?

**Comment by tmancey** [comment]
@srirambv Sure we can close this issue, thanks

**Comment by srirambv** [comment]
Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta1-x64 build
* Verified clean install via playstore enabled ads for Australia/New Zealand/Ireland
* Verified clean install of 1.3.0-x64 build enabled ads for Australia/New Zealand/Ireland

Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build
* Verified clean install via playstore enabled ads for Australia/New Zealand/Ireland
* Verified clean install of 1.3.0-x64 build enabled ads for Australia/New Zealand/Ireland
