### ISSUE TITLE
Back navigation from Rewards deep settings does not work

### ISSUE THREAD

**Issue by ryanml** [brave/browser-android-tabs#1858]
Note this is also true for auto-contribute settings

## Description 
There is a logic error in how views are set, if you go as deep as you can in the Rewards views (to a specific feature's settings), going back one level does not work as expected

![Screenshot_20190716-184626_Brave](https://user-images.githubusercontent.com/8732757/61341325-aeede680-a7fa-11e9-9272-736052c5d0a5.jpg)

## Steps to reproduce 

   1. Navigate to `chrome://rewards`
   2. Under Ads, hit `View Details >`
   3. Navigate to settings (Url should now be `chrome://rewards/ads-settings`
   4. Push the back button

## Actual result 
Url changes to `chrome://rewards/ads` but settings page is still showing

## Expected result
Url should change to `chrome://rewards/ads`, settings page should go away and back to Ads detail view

## Issue reproduces how often 
100%

**Comment by EyanGoldman** [comment]
@ryanml should this ticket be closed?

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/pull/1877#pullrequestreview-265765953

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T running 1.3.0 x64 build
 ![image](https://user-images.githubusercontent.com/17010094/62481453-7e0d2b80-b780-11e9-9bce-e3a4818abaed.png)
![image](https://user-images.githubusercontent.com/17010094/62481523-a137db00-b780-11e9-94e2-9d28935005b3.png)
