### ISSUE TITLE
Outdated image for sync start screen

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1864]
Sync screen image for android should parity iOS. We are currently using the old image, this should be updated. Current (outdated) image below
![Screenshot_20190717-133703_Brave.jpg](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/f5aa0458-9a49-44f7-89c0-9f68b1e45315)

**Comment by EyanGoldman** [comment]
@jamesmudgett can you please attach new graphics?

**Comment by jamesmudgett** [comment]
[sync.zip](https://github.com/brave/browser-android-tabs/files/3526836/sync.zip)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified sync pages are updated to the new design
![sync_main_page](https://user-images.githubusercontent.com/17010094/65427956-76155380-dde1-11e9-876a-7232198f1087.jpg)
![add_device](https://user-images.githubusercontent.com/17010094/65427928-68f86480-dde1-11e9-938c-53449094f407.jpg)
