### ISSUE TITLE
Turn off haptics for Brave Ads Notifications

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1866]
Turn off any haptics for Brave Ads Notifications. Not worth blocking 1.2.0 on this issue, but would be good to squeeze it into the release if we have time.

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta1-x64 build
  * Verified ad notification doesn't use haptics
  * Verified other notification still uses haptics
