### ISSUE TITLE
Fork and Investigate extensions support patch

### ISSUE THREAD

**Issue by DI555** [brave/browser-android-tabs#1870]
## Description 

Since the kiwi extensions support patch is appeared, it would be great to fork it and investigate to goal of provide that patch be workable!!!

https://github.com/kiwibrowser/privacy_patches/blob/master/Add-support-for-extensions-on-Android.patch
And imo it should be developing more and polishing!
I grabed it here:
https://github.com/kiwibrowser/privacy_patches

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/7606
