### ISSUE TITLE
Brave Ads Education Notification Text Change

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1875]
# Test Plan
See https://github.com/brave/browser-android-tabs/issues/1794#issuecomment-514405807
# 

When turning on Brave Ads through either the BAT icon or the settings panel, a notification is sent. The text on that notification should be changed to:

Top line: “Brave Rewards”
Message: “This is your first Brave ad. Tap to learn more.”

This should cover any form of opting in: Rewards Panel, Settings Page or On-boarding

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T on Android 9 running 1.3.0-beta-x64 build
  * Verified sample ad notification shown when rewards enabled via onboarding has the new text
  * Verified sample ad notification shown when manually enabling rewards via rewards page has the new text
  * Verified sample ad notification shown on relaunching welcome tour has the new text
