### ISSUE TITLE
"DuckDuckGo Light" label in settings should be "DuckDuckGo Lite"

### ISSUE THREAD

**Issue by karenkliu** [brave/browser-android-tabs#1876]
## Description
Currently the label for "DuckDuckGo Light" search engine has a typo. Change the label to match the name of the website, "DuckDuckGo Lite".

**Comment by EyanGoldman** [comment]
This is reflected in Kebab > Settings > Search engine (both pages)

**Comment by EyanGoldman** [comment]
@deeppandya has fixed in on boarding slides, but needs to be fixed on the settings page

**Comment by anthonypkeane** [comment]
@samartnik would you be able to make this change in Settings?

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/31543496adf3dd57390abb36d81b7743ce3ddcea

**Comment by srirambv** [comment]
* Verification passed on Huawei P20 running 1.3.0 x64
* Verification passed on OnePlus 6T running 1.3.0 x64 
![Screenshot_20190802-220413](https://user-images.githubusercontent.com/17010094/62374392-e30b1c00-b509-11e9-920c-0ecd45084619.jpg)
* Verification passed on Samsung Tab A running 1.3.0 x64
![Screenshot_20190802-094534_Brave](https://user-images.githubusercontent.com/17010094/62374631-6298eb00-b50a-11e9-97b0-bc2971cd72b1.jpg)
