### ISSUE TITLE
Onboarding flow not shown for existing users who upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1885]
## Description 
Existing users in the supported region do not get an onboarding message when upgraded to 1.2.0

## Steps to reproduce 

   1. Set region to Germany
   2. Install 1.0.98 and do not enable rewards
   3. Upgrade to 1.2.0, no onboarding is shown. This was shown when upgraded to 1.1.2

## Actual result 
No onboarding flow shown for existing user when upgraded

## Expected result
Should show reduced onboarding flow based on rewards enabled/not enabled

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? no
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 8.1.0
   
## Brave version
1.2.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Not to be confused with #1797 which is specific for new regions

**Comment by tmancey** [comment]
@EyanGoldman This would be a change in brave-core migration code, I can point a dev in the right direction if they let me know when they start the ticket

**Comment by EyanGoldman** [comment]
@tmancey @deeppandya @srirambv 
The ideal behavior should be showing all ads available regions existing user onboarding if going from < 1.1.0 -> 1.2.0

**Comment by EyanGoldman** [comment]
If we can't detect what version they were coming from previously, then only show the new regions the existing user onboarding. Better to not upset a ton of users to show the new existing user onboarding to a small handful in those regions who aren't updated

**Comment by tmancey** [comment]
This change needs to occur on `brave-core` and then be cherry-picked to Android. Please see `AdsServiceImpl::MigratePrefsVersion2To3`. I would recommend changing the following code in this function from:

```
  // On-board users for newly supported regions
  std::vector<std::string> new_regions = {
    "AU",  // Australia
    "NZ",  // New Zealand
    "IE"   // Ireland
  };

  MayBeShowFirstLaunchNotificationForSupportedRegion(region, new_regions);
```

to:

```
#if !defined(OS_ANDROID)
  // On-board users for newly supported regions
  std::vector<std::string> regions = {
    "AU",  // Australia
    "NZ",  // New Zealand
    "IE"   // Ireland
  };
#else
  // On-board users for all supported regions
  std::vector<std::string> regions = {
    "US",  // United States of America
    "CA",  // Canada
    "GB",  // United Kingdom (Great Britain and Northern Ireland)
    "DE",  // Germany
    "FR",   // France
    "AU",  // Australia
    "NZ",  // New Zealand
    "IE"   // Ireland
  };
#endif

MayBeShowFirstLaunchNotificationForSupportedRegion(region, regions);
```

**Comment by EyanGoldman** [comment]
Closing as existing behavior is already ideal and @tmancey comments have been addressed.

**Comment by EyanGoldman** [comment]
Closing as existing behavior is already ideal and @tmancey comments have been addressed.

**Comment by srirambv** [comment]
@EyanGoldman so if the user is in supported region and we are not able to detect the previous version (which we should unless its a clean install), there is no onboarding to be shown ?

**Comment by EyanGoldman** [comment]
All existing users from NZ, IE, AU should be shown existing user on boarding, that's it.

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 
* Existing Ads supported region (US/Canada)
   * Installed playstore build, didn't enable rewards, upgrade to 1.3.0, no onboarding shown as expected
* New ads supported region (Australia/Ireland/NewZealand)
  * Installed Playstore build, didn't enable rewards, upgraded to 1.3.0, only showed rewards onboarding as expected
* Ads unsupported region (India/SouthAfrica)
  * Installed Playstore build, didn't enable rewards, upgraded to 1.3.0, in-app `Enable Rewards` modal is shown as expected
