### ISSUE TITLE
Rewards Head Up Notification Localization URLs

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1889]
For Germany and France, the notification should take them to a localized version of the Brave.com/my-first-ad page. @abcinteractive will provide the localized URLs once the pages are set up.

**Comment by abcinteractive** [comment]
I create 2 new pages duplicated from https://brave.com/my-first-ad/ page (Brave Rewards Introduction):

German translation:  https://brave.com/my-first-ad-de/
French translation:   https://brave.com/my-first-ad-fr/

**Comment by abcinteractive** [comment]
Some Notes:
The Footer is now updated for French and I don't have german footer translations yet. 
The translated menu cannot be implemented until we install our safe version of the language switching WP plugin Polylang.

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build
  * Verified for France locale, sample ad notification link opens a page that is translated to French
![image](https://user-images.githubusercontent.com/17010094/63482316-7038f500-c466-11e9-88c0-1eea695ea59e.png)
  * Verified for German locale, sample ad notification link opens a page that is translated to Deutsch 
![image](https://user-images.githubusercontent.com/17010094/63482304-6911e700-c466-11e9-8bd0-6e096eceb0d5.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build
*Verified for France locale, sample ad notification link opens a page that is translated to French
![image](https://user-images.githubusercontent.com/17010094/63546601-2f89bc00-c4f8-11e9-84f6-1c0dba232b7a.png)
* Verified for German locale, sample ad notification link opens a page that is translated to Deutsch
![image](https://user-images.githubusercontent.com/17010094/63546592-2a2c7180-c4f8-11e9-8e60-f341f2402bb0.png)
