### ISSUE TITLE
Remove NZ, AU, IE from new regions for existing user onboarding

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1893]
Remove NZ, AU, IE from new regions for existing user onboarding so they do not get double onboarded when they update the app.

**Comment by szaimen** [comment]
Any update on this?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified upgrading from playstore build doesn't relaunch onboarding

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified upgrade profile doesn't show onboarding for IE/AU/NZ
