### ISSUE TITLE
Update Behavior of New Tab Button for Toolbar

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1894]
We cut for time in 1.2.0 because we wanted to get most of the feature out, #1707 included the functionality for long press on a new tab button (NTB). The behavior should be as follows:

User currently in normal tab:
- Tap on NTB opens normal tab
- Long Press on NTB shows menu with "New Tab" and "New Private Tab"
- Tap anywhere outside menu to dismiss 

User currently in private tab:
- Tap on NTB opens private tab
- Long Press on NTB shows menu containing just "New Private Tab" option (similar to iOS)
- Tap anywhere outside menu to dismiss

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0rc3 x64 build
* Verified long press on new tab button on normal tab brings up context menu option for `New tab` and `New Private tab`
* Verified tap on new tab button on normal tab opens a new normal tab
* Verified long press on new tab button on private tab brings up context menu that only has `New private tab`
* Verified tap on new tab button on private tab opens a new private tab
* Verified long press on new tab button doesn't show any tool tip 
* Verified tap anywhere outside the context menu dismisses the context menu
