### ISSUE TITLE
Improve LastPass Integration

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#190]
> Just switched to Brave on Android (very fast). Only complaint so far is it has difficulty handing input from LastPass Fill Helper. Tried to login to website, LastPass prompts account, username appears in URL instead of form, LastPass says unable to auto-fill.

Source: https://twitter.com/andrewlively2/status/845999336777535494

Version Information:

Android 6.0.1
Brave 1.0.18
Chromium 57.0.2987.108

**Comment by srirambv** [comment]
Moving to 1.0.25 as the old milestone is closed

**Comment by SergeyZhukovsky** [comment]
That is duplicated https://github.com/brave/browser-android-tabs/issues/70
