### ISSUE TITLE
New section in settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1901]
## Description 
With c76 there's a new section in settings: Sync and Google services

This section contains some settings that look like they were previously in the Privacy section as well as new ones. Additionally, there is mentions of Google all over the place in this new section. It should be reviewed carefully.

## Steps to reproduce 

   1. Install c76 build
   2. Open Settings
   3. Look at the first item

## Actual result 

![Screenshot_20190730-181402](https://user-images.githubusercontent.com/28145373/62170423-5853d280-b2f9-11e9-9214-bf4e201a897c.jpg)

This is what's inside:
![Screenshot_20190730-181443](https://user-images.githubusercontent.com/28145373/62170437-643f9480-b2f9-11e9-9a60-efb0aba644ad.jpg)

![Screenshot_20190730-181447](https://user-images.githubusercontent.com/28145373/62170446-69044880-b2f9-11e9-97b0-04d29e2720df.jpg)

Additionally, here are screenshots of the 1.2.0 Privacy section. I think the item in Red is new (but could be renamed from previous version, I'm not sure):
![Screenshot_20190730-181538](https://user-images.githubusercontent.com/28145373/62170579-df08af80-b2f9-11e9-96ef-8cb2318ce4d7.jpg)

![Screenshot_20190730-181542](https://user-images.githubusercontent.com/28145373/62170585-e4fe9080-b2f9-11e9-86df-68364138aa1c.jpg)

## Expected result
No google section in settings.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 6
   
## Brave version
1.2.0 c76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? likely

### Additional information
Here are screenshots of 1.1.2 Privacy section for comparison. Looks like maybe the items in blue boxes were moved to the new section and maybe the items in green boxes got dropped altogether? I'm not sure, they could have been renamed/moved. Someone with more knowledge would need to confirm.

![Screenshot_20190730-181033](https://user-images.githubusercontent.com/28145373/62170495-90f3ac00-b2f9-11e9-9e59-067b26b0aef0.jpg)

![Screenshot_20190730-181038](https://user-images.githubusercontent.com/28145373/62170505-94873300-b2f9-11e9-988e-b719460a0953.jpg)

**Comment by anthonypkeane** [comment]
Remove/ Hide
**Sync and Google Services**
-> Make sure all the setting in that menu are off
_-> Move Autocomplete searches and URLs back to Privacy_

**In Privacy**
Add
Autocomplete Search and URLs 

Remove/ Hide
Navigation error suggestions
Tracking protection mode
User page predictions
Tap to Search


@tomlowenthal @jumde can you pls confirm is we are ok to keep **_Search and URL suggestions_**, it is currently in the GPS version


**To do in a later release:**
Add Safe Browsing (https://github.com/brave/browser-android-tabs/issues/454)

**Comment by tomlowenthal** [comment]
As long as everything we hide is _off_, sounds good to me.

**Comment by samartnik** [comment]
@anthonypkeane what about `Tap to Search` option? We currently have it and it is on by default.

**Comment by anthonypkeane** [comment]
> @anthonypkeane what about `Tap to Search` option? We currently have it and it is on by default.

ok, leave `Tap to Search` as-is

**Comment by tomlowenthal** [comment]
I think `Tap to Search` should be disabled. #1871

**Comment by srirambv** [comment]
@samartnik @tomlowenthal  @anthonypkeane as per https://github.com/brave/browser-android-tabs/issues/1901#issuecomment-517822249, 
* `Autocomplete Search and URLs` is to be added under privacy which I don't see
* `Preload pages for faster browsing and searching` is a new entry which isn't in playstore build nor mentioned in the above comment and is enabled by default. Is this expected?

Here's a screenshot of the current privacy section on a clean install. Could you please confirm the above? 
![Screenshot_20190808-221222](https://user-images.githubusercontent.com/17010094/62749225-a2d7fc00-ba29-11e9-9f3f-aef81b9d62af.jpg)

**Comment by samartnik** [comment]
`Search and URL suggestions` is the name in Chromium they use in `Privacy` settings for `Autocomplete Search and URLs`.
@anthonypkeane @tomlowenthal what are thoughts on `Preload pages for faster browsing and searching`? Should it be there? `on` or `off` by default?

**Comment by tomlowenthal** [comment]
It should be off.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm v1.2.0-rc.2`
 - Verified below items are Removed/Hide as per the comments https://github.com/brave/browser-android-tabs/issues/1901#issuecomment-517822249 
    - Navigation error suggestions - `Removed` in Privacy
    - Tracking protection mode - `Removed` in Privacy
    - User page predictions - `Removed` in Privacy
    - Tap to Search - still there mentioned in https://github.com/brave/browser-android-tabs/issues/1901#issuecomment-518297100
    - Preload pages for faster browsing and searching - Now this option is made OFF by default

**Comment by eljuno** [comment]
`Tap to search` setting is not available with Brave 1.4.2 installed from Play Store. Is this expected? Based on @GeetaSarvadnya screenshot, the option is still there.
