### ISSUE TITLE
global shield settings not set properly

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1904]
## Description 
If you change global shield settings and visit a page, the global shield settings should take effect. However, they are not. Seems to affect FP, Ad Blocking, and HTTPSE. Block Scripts works as expected and there isn't global setting for 3rd party cookie blocking.

## Steps to reproduce 
Scenario 1
   1. Clean profile
   2. Navigate to settings > Privacy.
   3. Enable Fingerprinting Protection.
   4. Navigate to https://browserleaks.com/webrtc
   5. Tap on shields. 
   6. Toggle for FP is on, but no blocked items.
   7. Toggle FP off/on. Now there are blocked items for FP listed.

Scenario 2
   1. Clean profile
   2. Navigate to settings > Privacy.
   3. Disable Adblock/Regional Adblock.
   4. Navigate to a site with ads. --> No ads are shown on the site.
   5. Tap on shields. 
   6. Toggle for Block Ads and Tracking is on, should be off.

Scenario 3
   1. Clean profile
   2. Navigate to settings > Privacy.
   3. Disable HTTPSE.
   4. Navigate to http://https-everywhere.badssl.com --> you are redirected to https://https-everywhere.badssl.com, site is green, indicates HTTPSE is working.
   5. Tap on shields. 
   6. Toggle for HTTPSE is off.
   7. Toggle HTTPSE on/off. Now site indicates that HTTPSE is not working.

Repeat tests for each shield setting.

## Actual result 
Global shield preferences are not being set correctly.

## Expected result
Global shield prefs should be set correctly.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.2.0 Chromium 76.0.3809.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
reproduced by @srirambv

**Comment by LaurenWags** [comment]
This scenario is currently working as expected with 1.2.0:
Scenario 4
   1. Clean profile
   2. Navigate to settings > Site settings > Javascript.
   3. Disable Javascript.
   4. Navigate to brianbondy.com. --> site doesn't load as expected.
   5. Tap on shields --> Toggle for Block Scripts is on as expected.

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9 running 1.20 x64 build
  * Verified disabling HTTPSE globally takes effect on newly visited sites
  * Verified enabling Fingerprint protection globally takes effect on newly visited sites and block 
  * Verified disabling Adblock/Regional adblock globally takes effect on newly visited sites and shows ads
  * Verified disabling Script blocking globally via site settings takes effect and block scripts on newly visited sites
