### ISSUE TITLE
Ads grant show up when wallet is created on staging

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1906]
## Description 
Ads grant show up when wallet is created on staging

## Steps to reproduce 

   1. Install 1.2.0
   2. Enable wallet on staging
   3. Ads grant show up instead of token grant

## Actual result 
![Screenshot_20190731-103530](https://user-images.githubusercontent.com/17010094/62221107-18cfc980-b37f-11e9-84f7-78e4b4706674.jpg)

## Expected result
Should show token grant 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel 3XL
   - Android version: 9.0
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.2.0-rc.2 on Huawei MediaPd M3 Lite 10. Regular tokens are now available.
