### ISSUE TITLE
Can this 'Make mobile friendly' nag screen be disabled ?

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-android-tabs#191]
When visiting websites in desktop mode (which I prefer strongly) I get a message 'Make this webpage mobile friendly ?' which appears every 10 minutes.
Can this be disabled ?

![screenshot_2017-03-26-19-01-46](https://cloud.githubusercontent.com/assets/26625141/24333782/b7dd5c0a-125e-11e7-9ab6-026a0810a0a8.png)

**Comment by SergeyZhukovsky** [comment]
Hi @freebrowser1, it is a reader mode proposal. You can disable it https://github.com/brave/browser-android-tabs/wiki/Frequently-Asked-Questions#how-do-i-enable-reader-mode. You just have to set Never in the dropdown.
