### ISSUE TITLE
Update Android Ads Policy

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1913]
Update Brave Ads delivery policy to as follows (assuming there is an ad match):

Subsequent Ads: x/60 mins (where x = 60 mins/# of ads per hour) must pass from previous ad notification + 1 min of browser usage.

**Comment by tmancey** [comment]
Commit hash`8c67b55b8970af2f46fdcd2262ad6684d41cd7c7` has been cherry-picked from `brave-core` to `android_75`, @SergeyZhukovsky and @samartnik and aware this needs to be in 1.3.0

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.3.0 x64 build
* Verified ads show up after specified amount of time based on ads/hr setting
* Verified subsequent ads respect the time setting for (60/x)+1min of browsing time
* Verified no logs for ads when the app is backgrounded 
* Verified when the app is relaunched ads show up after specified time when the app is active 
Complete log for all the above steps: [60_x+1.txt](https://github.com/brave/browser-android-tabs/files/3576624/60_x%2B1.txt)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+ with Android 9` using `1.3.2 CR: 76.0.3809.132`:

* Verified ads show up after specified amount of time based on ads/hr setting
* Verified subsequent ads respect the time setting for (60/x)+1min of browsing time
* Verified no logs for ads when the app is backgrounded 
* Verified when the app is relaunched ads show up after specified time when the app is active
