### ISSUE TITLE
Upgrade doesn't change DDG Light to DDG Lite

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1914]
## Description 
Upgrade doesn't change DDG Light to DDG Lite

## Steps to reproduce 

   1. Install playstore build
   2. Check SE list, Shows DDG Light
   3. Upgrade to 1.3.0, SE still shows DDG Light instead of DDG LIite

## Actual result 
DDG Light instead of DDG Lite on upgarde

## Expected result
DDG Lite on clean install or on upgrade

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.2->1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) Android 6.0 using 1.3.0-beta1 BraveModernx86.apk
 - Verified STR from description. 1.1.2 -> 1.3.0 upgrade shows updated DDG. Note, 1.2.0 already displays updated DDG.
