### ISSUE TITLE
onboarding flow allows opt in to Rewards for x86 devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1916]
## Description 
Onboarding flow should not allow opt in to Rewards for x86 devices since x86 has Rewards removed.

## Steps to reproduce 

   1. Clean install of onboarding build on x86 device.
   2. Go thru flow.
   3. At last step, join Rewards.

## Actual result 
Able to join Rewards.

## Expected result
Should not be offered Rewards since Rewards is not available on x86 devices.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by EyanGoldman** [comment]
After speaking with @srirambv and @anthonypkeane, it seems like a good idea to not show any onboarding to x86 devices to not give the appearance that the app is broken

**Comment by LaurenWags** [comment]
Ok, so no onboarding for x86 devices 👍 

However, I believe the issue as reported will also affect rooted ARM devices. Will those devices get onboarding flow or not?

**Comment by anthonypkeane** [comment]
Yes they will

**Comment by LaurenWags** [comment]
Verified passed with Asus Zenfone (x86) Android 6.0 using 1.3.0-beta1 BraveModernx86.apk
