### ISSUE TITLE
Changing SE in onboarding flow doesn't apply

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1917]
## Description 
Changing SE in onboarding flow doesn't apply

## Steps to reproduce 

   1. Clean install 1.3.0 build 
   2. Change SE in onboarding flow
   3. Go to settings, still has default Google as SE

## Actual result 
Changing SE in onboarding flow doesn't apply

## Expected result
Should change if user select different SE during onboarding

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Note: This was working on the 1.2.0 onboarding build but not working in 1.3.0
cc: @deeppandya

**Comment by srirambv** [comment]
This only happens if you skip the onboarding flow when rewards section is shown. If you just set the SE and skip it then it wont retain the changes which is a bug. SE changes should stick irrespective of user completes the onboarding flow or not.

**Comment by LaurenWags** [comment]
In my case, I set the SE, then went thru the flow until the Rewards page. At this point I said No to Rewards. I completed the flow, so my SE should be set, however it is not being set. As a user I would expect my SE selection to be honored because I completed the onboarding flow.

**Comment by srirambv** [comment]
Here's a screen recording of what's happening when you skip and complete the onboarding flow 
https://youtu.be/Ed_s8_3lbiE

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build
* Existing Ads supported region(US/Canada)
  * Clean install, change SE in onboarding, skip on SE onboarding page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained 
* New Ads supported region(Australia/NZ)
  * Clean install, change SE in onboarding, skip on SE onboarding  page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained 
* Ads not supported region (India/SA)
  * Clean install, change SE in onboarding, skip on SE onboarding  page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build
* Existing Ads supported region(US/Canada)
  * Clean install, change SE in onboarding, skip on SE onboarding page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained 
* New Ads supported region(Australia/NZ)
  * Clean install, change SE in onboarding, skip on SE onboarding  page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained 
* Ads not supported region (India/SA)
  * Clean install, change SE in onboarding, skip on SE onboarding  page, no changes to default SE
  * Clean install, change SE in onboarding, next to shields, skip onboarding, SE changes are retained
  * Clean install, change SE in onboarding, finish onboarding, SE changes are retained
  * Clean install, change SE in onboarding, Open PB, set DDG as default, SE for default and PB is retained
