### ISSUE TITLE
Ad banner not shown on Android 5.1 device, but Brave logo is in notification bar

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1918]
## Description 
When using an older Android device (5.1) and going thru the onboarding flow, when it came time to view an Ad, the Ad banner didn't display. However, the Brave icon was shown in the notification bar at the top of my phone. 

## Steps to reproduce 

   1. Clean install of 1.3.0 build on older Android device.
   2. Go thru the onboarding flow.
   3. At the end, accept the terms for rewards.
   4. Watch the counter go down. 
   5. Just before it hits 0, see the Brave logo display in notification bar.

## Actual result 
No Ad banner shows, just Brave logo in notification bar.
![Screenshot_2019-08-02-11-38-56](https://user-images.githubusercontent.com/28145373/62382972-b90f2500-b51c-11e9-80c8-25853658d595.png)

## Expected result
Ad banner to be shown (that's what the image on screen suggests).

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: older, like 5.1
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
@srirambv is not seeing this on his newer Android device.
cc @GeetaSarvadnya @anthonypkeane to try on their older Android devices.

**Comment by LaurenWags** [comment]
Video showing behavior: https://youtu.be/bVKSDYEdbmY

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in Android version 5.1.1 running `1.3.0`

**Comment by GeetaSarvadnya** [comment]
Ads banner is shown now - Verified in Samsung Galaxy J3 version 5.1.1 running `v1.3.0-beta.1`

![Screenshot_2019-08-02-22-10-24](https://user-images.githubusercontent.com/38657976/63504263-d10c1000-c4ee-11e9-830e-16ae139533c8.png)
