### ISSUE TITLE
Private Tab Default SE Choice

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1919]
The SE that the user chooses in onboarding should be the default for both normal and private tabs. If the user skips on boarding, the same applies (whatever the regional default is will be reflected in normal and private tabs)

Test Plan:
Finish Onboarding
- Start Onboarding
- Select SE (not google)
- Finish Onboarding
- Normal Tab should be selected SE, Private Tab should be selected SE

Skip Onboarding
- Start Onboarding
- Press "Skip"
- Normal Tab should be default SE, Private Tab should be default SE

**Comment by srirambv** [comment]
I would suggest having a checkbox that says `Set same SE for Private tab`. This way you can set to your choice and if it's different from DDG then we continue to show the DDG modal when the first private tab is opened. Gives user more control on setting default SE or leave it as it is

cc: @anthonypkeane @jamesmudgett

**Comment by EyanGoldman** [comment]
I don't think this will be necessary for now. We should definitely leave the modal (current behavior), but we don't have any data which suggests that users frequently use separate SEs for private and default, if we did I think I would be more open to this. Until then, I think we should stick with the above plans.

**Comment by srirambv** [comment]
At the very least we should add a note at the bottom that both normal and private tabs will have SE set.  Since we don't have enough data we should probably say things explicitly than assuming that it should be ok to set same SE for both.  No harm in adding a text at the bottom. Allowing it to customize can be done later

**Comment by kjozwiak** [comment]
Bit late as onboarding is basically already released, but this surprised me as well. Wasn't really expecting both SE to be changed to whatever I selected via the onboarding. A heads up that this choice will affect PB is probably a good idea.

@anthonypkeane should we create a new issue so we can at least consider/discuss what @srirambv recommended?

**Comment by anthonypkeane** [comment]
Eyan and I discussed it. Users see this screen when they first open private tabs. 

The balance is on not bloating onboarding and keeping it to a min. We will learn soon what folks think about it. 


![DDG on Provate Tab](https://user-images.githubusercontent.com/7606853/64198526-448e1580-ce3d-11e9-905f-72a584557a02.jpg)
