### ISSUE TITLE
Denying Notification Requests not working

### ISSUE THREAD

**Issue by markuspi** [brave/browser-android-tabs#1920]
## Description 
Tapping on 'Deny' in HTML5 Notification Requests results in Notifications not actually being denied. Looking in the Brave Site Settings as well as Android 9 Notification Settings, the website shows up as being allowed to show Notifications.

## Steps to reproduce 

1. Visit a website that uses the Notification API, such as [this one](https://web-push-book.gauntface.com/demos/notification-examples/)
2. The Notification Request Dialog appears. Press 'Block'
3. Reload the page
4. Go to Brave Site Settings and notice that notifications are allowed
5. Go to Android Settings > Notifications > Brave and also notice that notifications for the particular website are allowed
6. Let the website trigger a notification through JS and notice a notification appearing

## Actual result 
Notifications are not blocked when pressing 'Block'

## Expected result
Notifications are blocked when pressing 'Block'

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes (1.1.2)
   - Beta build? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone, Honor 10
   - Android version: Android 9
   
## Brave version
1.1.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
I cant reproduce this on the current release build. Here's a recording on a clean profile. https://youtu.be/K8_g5Fe4E8o

Could you do a screen record of the steps you are doing? Maybe I am missing something.

**Comment by markuspi** [comment]
Here you go: https://youtu.be/9jIR5wwc2QQ

**Comment by srirambv** [comment]
I see the notifications isn't blocked when you click on site info. Could you try clearing your browser cache once and check. Make sure you clear everything in advanced settings and select from all time so that it doesn't retain anything

**Comment by markuspi** [comment]
That’s what I did before I recorded the video. I cleared browsing data from all time making sure all checkboxes are ticked in the advanced tab. Right now I tried it again and even tried reinstalling the app from the play store. Still the same result

**Comment by srirambv** [comment]
Weird. I can't reproduce it. 

cc: @SergeyZhukovsky @samartnik

**Comment by markuspi** [comment]
I did some more testing and found a related yet slightly different issue in chrome 75.0.3770.143:

Denying notification requests in chrome for android first works normal, as expected. Looking in the site settings, notifications are marked as blocked, and JS is not able to trigger notifications, even after refreshing.

But as soon as I open the android settings entry for the particular website, it shows up as 'allowed'. From that point on, JS is able to send Notifications and the Chrome site settings also show Notifications being allowed.

To be clear: in Brave, JS is able to send Notifications immediately after reloading the page, without accessing any settings-pages.

Maybe it‘s related to Huawei‘s EMUi?
Let me know if I can do anything to help investigate

**Comment by markuspi** [comment]
Seems to be fixed now, either through Brave or EMUI Update
