### ISSUE TITLE
Rewards welcome page is retained for a long time when rewards is enabled via onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1924]
## Description 
Rewards welcome page is retained for a long time when rewards is enabled via onboarding

## Steps to reproduce 

   1. Clean install 1.3.0
   2. Enable rewards via onboarding
   3. Rewards panel shows the red dot 
   4. Open panel and tap on rewards settings to open rewards page
   5. Welcome page is retained for a good 5secs makes it look like the onboarding flow didn't enable rewards

## Actual result 
https://youtu.be/Xry1PsrJXu0

## Expected result
Welcome should not be shown when opened if onboarding enabled it

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 9.0
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

@anthonypkeane please add it to appropriate milestone based on priority 
cc: @SergeyZhukovsky @ryanml @deeppandya @EyanGoldman

**Comment by EyanGoldman** [comment]
@srirambv if you wait a significant amount of time between finishing onboarding and navigating to the rewards settings page, does it still delay? In other words, is it related to first time opening rewards or the amount of time between finishing onboarding and navigating to rewards settings? Thanks for noticing!

**Comment by deeppandya** [comment]
@EyanGoldman @srirambv i believe it has nothing to do with onboarding as enabling rewards takes time. and i think it would do the same thing for other scenarios. @srirambv can you confirm this ?

**Comment by srirambv** [comment]
@deeppandya This seems to be a lot better on the new 1.3.0 build. However on the previous build, if rewards were enabled via onboarding, the welcome page was sustained for a longer time as compared to enabling it via BR panel. 

I think we can close this for now and revisit if it starts to happen again.
