### ISSUE TITLE
Change Welcome Tour Modal

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1928]
The modal that launches when you access onboarding through the settings page should read: 

"Relaunching Welcome Tour will not affect any existing settings" 

Additionally, the modal needs to grow vertically to accommodate all the text on smaller devices.

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-beta1-x64 build 
![image](https://user-images.githubusercontent.com/17010094/63482952-b000dc00-c468-11e9-8c2a-ee8c73220acd.png)
