### ISSUE TITLE
Relaunching welcome tour after setting DDG as private tab SE resets default SE for all tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1933]
## Description 
Relaunching welcome tour after setting DDG as private tab SE resets default SE for all tabs

## Steps to reproduce 

   1. Clean install 1.3.0 onboarding build
   2. Select Bing as default SE. This sets it as default for both Normal and private tabs
   3. Open a new private tab, DDG modal shows up, select Yes and set DDG as default SE for private tabs
   4. Open settings, Normal tab should show Bing as default and DDG as default for private tab
   5. Relaunch welcome tour again
   6. DDG is shown as the default selected search engine. This should be Google as its just a walkthrough of the first welcome tour that is shown
   7. Finish the welcome tour and open settings, DDG is set as default SE for both normal and private tabs

## Actual result 
Relaunching welcome tour after setting DDG as private tab SE resets default SE for normal tabs as well

## Expected result
Setting DDG as default shouldn't reset default SE set to normal tab if welcome tour is launched again

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 9.0
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@EyanGoldman @srirambv when you open private tab with **DuckDuckGo** and as private tab would be the cutrrent tab in the case, current implementation would set **DuckDuckGo** as default search engine and after that when you open **welcome tour**, it reflects the change. so according to the @srirambv 's suggetsion i have updated the value.

**Comment by EyanGoldman** [comment]
@srirambv @deeppandya  I think I understand what is going on, but to confirm, no changes should occur to SE settings (normal or private tab) after relaunching the welcome tour.

**Comment by srirambv** [comment]
@EyanGoldman  yes. I see the welcome tour uses the default SE that is set meaning if you launch settings via private tab it shows the SE that is set in private tab as default and if you launch settings when on the normal tab it shows the SE that is set there. @deeppandya  gave a debug build that has the fix for this so redoing the welcome tour doesn't affect the changes anymore

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta1-x64 build 
* Existing ads enabled regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained 
* New ads enabled regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained
* Ads unsupported regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta1-x64 build 
* Existing ads enabled regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained 
* New ads enabled regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained
* Ads unsupported regions  
  * Verified setting DDG as default via the PB opt-in modal only sets it for PB 
  * Verified relaunching welcome tour on normal tab, shows default SE that is set for normal tab, both SE changes for normal and private tab is retained
  * Verified relaunching welcome tour on private tab, shows default SE that is set for private tab, both SE changes for normal and private tab is retained
