### ISSUE TITLE
Create wallet hangs on devices without Google Play Services

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#1936]

**Comment by srirambv** [comment]
@fmarier @iefremov  Would you be able to check this on your Lineage OS device?

**Comment by iefremov** [comment]
@srirambv sure thing, if you can point to an APK

**Comment by srirambv** [comment]
@iefremov you can download the build from https://github.com/brave/browser-android-tabs/releases/tag/v1.2.0-rc.1

**Comment by kjozwiak** [comment]
@iefremov mind going through the above verification? QA doesn't have any devices running LineageOS so there's not much we can do here in terms of verification. You can download the latest RC from https://github.com/brave/browser-android-tabs/releases/tag/v1.2.0-rc.2.

**Comment by iefremov** [comment]
After installation it showed a promo balloon asking about enabling rewards, I hit `Yes I'm in`, then there was a dialog saying "Sorry, it seems rewards are not available on your device`.  Now there is no rewards logo in the omnibox and elsewhere.

Does that mean that I won't be able to enable rewards even after moving away from SafeNet?

**Comment by SergeyZhukovsky** [comment]
Yep, it's how it works currently. They are not avail on devices without SafetyNet Google Play service.

**Comment by iefremov** [comment]
@SergeyZhukovsky When we switch from SafetyNet to something else, will I be able to enable rewards, or this possibility is gone now? :)

**Comment by kjozwiak** [comment]
@iefremov going to label this as `QA Pass - Android ARM` as the above behaviour is expected as per @SergeyZhukovsky comment. Looks like you were able to run through the wallet creation without running into the hanging issue.
