### ISSUE TITLE
Tabs lost upon upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1941]
## Description 
Tabs lost upon upgrade

## Steps to reproduce 

   1. Install playstore build
   2. Enable all checkboxes under privacy
   3. Upgrade to 1.20 RC1 build
   4. All tabs are lost after upgrade

## Actual result 
All tabs are lost upon upgrade

## Expected result
No tabs/sessions are lost. Smooth upgrade

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T 
   - Android version: 9.0
   
## Brave version
1.20

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @anthonypkeane @SergeyZhukovsky 
@LaurenWags  to check on x86

**Comment by SergeyZhukovsky** [comment]
@srirambv did you check `Close all tabs on exit` option as well? It is expected if yes.

**Comment by srirambv** [comment]
Yes. But the browser wasn't removed from memory just backgrounded so shouldn't have lost all tabs upon upgrade. If the app is backgrounded and not exit and then playstore autoupdates then all tabs are lost when you launch it next time.

**Comment by srirambv** [comment]
@SergeyZhukovsky  this is an existing problem. Just verified by installing 1.0.99, enable clear on exit and backgrounded the app. Let PlayStore auto-update Brave to the latest version and when relaunched all tabs are lost. 

Moving out of 1.20 as this is an existing problem that needs to be fixed.

**Comment by SergeyZhukovsky** [comment]
As I mentioned before it's not a bug at all. It's how the feature is implemented. Someone who checked off the feature expect app starts without tabs. It doesn't matter was app killed by OS, was phone restarted, it was upgraded or the app was swiped from recent apps.

**Comment by srirambv** [comment]
> It doesn't matter was app killed by OS, was phone restarted, it was upgraded or the app was swiped from recent apps.

But the scenario is the app is still running in the background. Does the app gets removed from memory when the upgrade happens (even if it was running in the background)? If so then this is an invalid bug. if not then its still a valid bug
