### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by zaoqi** [brave/browser-android-tabs#1942]
## Description 

Google is not available in mainland China, and Brave is not on FDroid, so I can only download it from github.

There are so many versions for arm:

Bravearm.apk
BraveModernarm.apk
BraveMonoarm.apk
BraveMonoarm64.apk

https://github.com/brave/browser-android-tabs/releases/tag/v1.1.2

Which version should I use?

**Comment by SS1113** [comment]
This is not a correct place to ask questions, you should use Brave community forums or email brave support.

Anyway here's the answer, If you have a 64-Bit CPU then you should use 'BraveMonoarm64.apk' and if you have a 32-bit CPU then you should use 'BraveMonoarm.apk.' 32-bit versions will install on a 64-bit version device but not vice-versa. To determine if you have a 64-bit or 32-bit CPU you can use any system information tool such as CPU-Z, DevCheck, AIDA64 etc...
