### ISSUE TITLE
Next Payment date is missing under Ads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1943]
## Description 
Next Payment date is missing under Ads

## Steps to reproduce 

   1. Clean install 1.20
   2. Enable rewards
   3. Go to view details under ads, `Next payment date` is missing

## Actual result 
![Screenshot_20190809-121316](https://user-images.githubusercontent.com/17010094/62793508-be7de980-ba9f-11e9-8d0d-5ebcc9d9ce16.jpg)

## Expected result
Should show correct date

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes only on clean install

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 9.0
   
## Brave version
1.20 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Upgrade retains correct date. Issue only happens on a clean install

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm v1.2.0-rc.2`
  - Verified Next payment date is displayed correctly in a clean and upgraded profile
