### ISSUE TITLE
Developer tools doesn't load

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1945]
## Description 
Developer tools doesn't load

## Steps to reproduce 

   1. Clean install 1.20
   2. Connect device to desktop
   3. Open brave://inspect#devices 
   4. Visit a site on Android
   5. Ensure the site lists on brave://inspect#devices
   6. Click on inspect under the device name in desktop
   7. Developer tool window launches but never loads 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/62810448-031f7a00-bacc-11e9-8227-3e210a5fafcf.png)

## Expected result
Should load developer tools correctly

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone 
   - Android version: 9.0
   
## Brave version
1.20

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Works for me from Chrome. Does it work for you from Chrome?

**Comment by samartnik** [comment]
From Brave it's not working with Chrome (76.0.3809.89) as well. I think problem is on Brave Browser side.

**Comment by Mikko031014** [comment]
Sent from Yahoo Mail on Android 
 
  On Sat, Aug 10, 2019 at 5:35 AM, Sriram<notifications@github.com> wrote:   
Description 

Developer tools doesn't load

Steps to reproduce 
   
   - Clean install 1.20
   - Connect device to desktop
   - Open brave://inspect#devices
   - Visit a site on Android
   - Ensure the site lists on brave://inspect#devices
   - Click on inspect under the device name in desktop
   - Developer tool window launches but never loads

Actual result 



Expected result

Should load developer tools correctly

Issue reproduces how often 

Easy

Issue happens on 
   
   - Current Play Store version? No
   - Beta build? Yes

Device details
   
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0

Brave version

1.20

Website problems only
   
   - Does the issue resolve itself when disabling Brave Shields?
   - Is the issue reproducible on the latest version of Chrome?

Additional information

**Comment by srirambv** [comment]
Works on `Chrome 76.0.3809.100`  but not on `Brave 0.67.124 Chromium 76.0.3809.100`

**Comment by samartnik** [comment]
problem is on brave browser side
