### ISSUE TITLE
The browser with ads service run in the background without UI

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#1946]
## Description 
The browser with ads service run in the background without UI delivering ads notifications and draining resources. 

## Steps to reproduce 

   1.  Run browser, enable ads and receive an ad notification.
   2. Close browser.
   3. Dismiss (swipe away) the notification.

## Actual result 
The browser is started in the background without UI.
Observe it with `adb shell ps | grep brave`.
After sometime an ad notification is shown.

## Expected result
The browser should handle `Notification dismissed` event and exit.

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.1.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Fixed by:
https://github.com/brave/brave-core/pull/3306
https://github.com/brave/browser-android-tabs/pull/2054

**Comment by gdregalo** [comment]
@srirambv 
Test plan:
1. run browser and receive an ad or two;
2. close browser and leave notifications in the tray;
3. dismiss (swipe away) notification;
4. run immediately `adb shell ps | grep brave` and observer the browser has been started in the background to process `Dismiss` event;
5. In 1 minute or so, run `adb shell ps | grep brave` again and observe the browser was closed and it's not running;
6. During the minute no notifications should be posted to the UI.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 RC3 x64 build
* Verified steps from https://github.com/brave/browser-android-tabs/issues/1946#issuecomment-535569638
* Verified no process was running after dismissing a notification from the notification tray
```
1|OnePlus6T:/ $ ps -A | grep com.brave.*
u0_a242      30625   630 1566024 174128 0                   0 S com.brave.browser
u0_i212      30671   630 1329792 116348 0                   0 S com.brave.browser:sandboxed_process0
u0_a242      30702   630 1301968 117220 0                   0 S com.brave.browser:privileged_process0
u0_i214      30745   630 1563308 226184 0                   0 S com.brave.browser:sandboxed_process1
u0_i216      30772   630 1350316 115380 0                   0 S com.brave.browser:sandboxed_process2
OnePlus6T:/ $ ps -A | grep com.brave.*
1|OnePlus6T:/ $ ps -A | grep com.brave.*
```
