### ISSUE TITLE
Issue with Ads Payments (August 5)

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#1950]

**Comment by samartnik** [comment]
@tmancey could you provide steps for QA on how they can check it?

**Comment by tmancey** [comment]
@samartnik QA have test cases for this feature on desktop. @LaurenWags @kjozwiak You will need to view the logcat due to not having access to the file system

**Comment by LaurenWags** [comment]
Verified passed on LG Nexus 5 with Android 5.1 running 1.2.0 rc3 BraveModernarm.apk

Test cases were adapted from https://github.com/brave/brave-browser/issues/5548

1. **PASS** Using 1.2.0 rc3, emulated some failed confirmations (using Charles Proxy). Without restarting Brave, verified that the failed confirmations were added to the queue and retried (verified this by viewing logcat, unable to view confirmations.json file). Verified `Estimated pending rewards` and `Ad notifications received this month` totals were updated (as applicable) as the failed confirmations succeeded.
2. **PASS** Verified that failed confirmations for `view`, `click`, `dismiss`, and `landed` were each retried and processed successfully.
3. **PASS** Verified that failed confirmations were retried every ~5 min (realistically, between 15s and almost 20 minutes) until the queue was empty. Additionally, if the retry failed, it was added back to the queue and retried again.
4. **PASS** Used Charles Proxy to emulate failed confirmations. Verified that when the failed confirmations were retried, no 400s were observed in the logs.
5. **PASS** Verified no 404s observed in logs when clicking to view ads notifications.
6. **PASS** Emulated failed confirmations on 1.1.2 (current release build) with Charles Proxy. Upgraded to 1.2.0 rc3. Verified The existing failed confirmations were retried. Additionally, `Estimated pending rewards` and `Ad notifications received this month` totals were updated as the failed confirmations succeeded (where applicable).
