### ISSUE TITLE
Polish on decimal points in Rewards

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1964]
## Description 
As per the Slack chat, please round all decimal points in Rewards to 1 point, and match desktop

Internal Chat: https://bravesoftware.slack.com/archives/CJVNBPK9P/p1565986324144600

![Untitled.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/b5017958-ec9d-47ac-b9ec-c74b96acf6ea)

If a concert list of places is needed where to round down please let me know

**Comment by anthonypkeane** [comment]
@tmancey to provide the info on the correct behavior on Desktop, Android to follow

**Comment by tmancey** [comment]
@anthonypkeane BAT should be displayed with 1 decimal place, i.e. "12.0". USD should be displayed with 2 decimal places, i.e. "23.12"

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
Rewards panel:
![image](https://user-images.githubusercontent.com/17010094/65609890-8282e300-df7e-11e9-920b-c5803fa136ef.png)
AC list
![image](https://user-images.githubusercontent.com/17010094/65609920-90386880-df7e-11e9-9a05-4c9d57a0cae4.png)
Tips Panel:
![image](https://user-images.githubusercontent.com/17010094/65609945-97f80d00-df7e-11e9-950f-8407df7b854d.png)
One time tip:
![image](https://user-images.githubusercontent.com/17010094/65609964-a0e8de80-df7e-11e9-9a9c-afc111787964.png)
Monthly tip:
![image](https://user-images.githubusercontent.com/17010094/65609978-a80fec80-df7e-11e9-8ebb-5edf8526eacd.png)
One time tip on Panel:
![image](https://user-images.githubusercontent.com/17010094/65610009-b1995480-df7e-11e9-8554-5d07cac56432.png)
Auto-Contribute/Monthly tips/Pending bat for non-verified pubs in panel
![Screenshot_20191025-101852](https://user-images.githubusercontent.com/17010094/65614319-68003800-df85-11e9-93db-5b93c245c527.jpg)
Tips list
![image](https://user-images.githubusercontent.com/17010094/65610082-d1307d00-df7e-11e9-839d-8eebe5039a3b.png)
Ads details
![image](https://user-images.githubusercontent.com/17010094/65610111-db527b80-df7e-11e9-9ebd-1aacf0f72c20.png)
Auto contribute message 
![Screenshot_20191025-101834](https://user-images.githubusercontent.com/17010094/65614223-43a45b80-df85-11e9-8aff-e7e583a07843.jpg)
Ads earning:
![image](https://user-images.githubusercontent.com/17010094/65613740-7568f280-df84-11e9-9d9d-469642065c87.png)
Ads earning in panel:
![image](https://user-images.githubusercontent.com/17010094/65613841-9598b180-df84-11e9-9644-5bd9d0d4c96a.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.4.0 RC4 x64
![image](https://user-images.githubusercontent.com/17010094/65885053-e97e0e80-e367-11e9-8c6b-57f6c1cc6e33.png)
![image](https://user-images.githubusercontent.com/17010094/65885077-f569d080-e367-11e9-85d6-d4a87a66ce93.png)
![image](https://user-images.githubusercontent.com/17010094/65885088-fa2e8480-e367-11e9-86c8-5823ca3db58f.png)
![image](https://user-images.githubusercontent.com/17010094/65885099-fe5aa200-e367-11e9-89aa-0f4773d04e29.png)
![image](https://user-images.githubusercontent.com/17010094/65885164-2518d880-e368-11e9-80ac-2c3f4b33e072.png)
