### ISSUE TITLE
Replay Welcome Tour back button

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1972]
Currently: The back button for Android during onboarding does nothing
Change To: Takes the user back one slide.

**Comment by deeppandya** [comment]
@EyanGoldman what should happen when user goes back to **Brave ads** page ?

**Comment by EyanGoldman** [comment]
Should replay the ad. Is this possible?

**Comment by srirambv** [comment]
Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-rc1-x64 build
* Verified relaunching welcome tour allows navigating back to the previous screen using the back button
* Verified during onboarding on a clean install, the back button doesn't allow to navigate back to the previous screen
