### ISSUE TITLE
Move "Close last tab closes Brave" in settings

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1973]
Currently: the close last tab closes Brave is located in "Basics"
Change to: Move it to the bottom of the list under "Controls"

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-rc1-x64 build
![image](https://user-images.githubusercontent.com/17010094/63614513-3f190b80-c5b1-11e9-8e9f-c447d09fe610.png)
