### ISSUE TITLE
Close all tabs settings gets changed when browser is relaunced

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1976]
## Description 
Close all tabs settings gets changed when browser is relaunced

## Steps to reproduce 

   1. Install playstore build and dont make any changes to home button
   2. Upgrade to 1.3.0
   3. Close last tab, browser closes as expected
   4. Turn off Home page option in settings, `Close all tabs closes Brave` option remains on as expected
   5. Close last tab, browser closes as expected
   6. Relaunch browser, `Close all tabs closes Brave` option is turned off

## Actual result 
Close all tabs settings gets changed when browser is relaunced

## Expected result
Setting should be retained between restarts

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 9.0
   
## Brave version
1.3.0beta 1 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Follow up for #1716

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.3.0-rc1
  - Verified the STR from the description
  - Verified `Close all tabs closes Brave` settings is not impacted by Turn off Home page option after upgrade
