### ISSUE TITLE
Sync QR code is missing warning text 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1977]
## Description 
#1830 was implemetned to add warning text for QR code as well which is in Release version. With #1819 refactor, QR code is missing the warning message that needs to be readded with same refactor done or code-words

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/63467990-b8d7ba80-c434-11e9-8dd7-5f7b576c146e.png)

## Expected result
Same but pretty version of it refactored
![image](https://user-images.githubusercontent.com/17010094/63468016-c2f9b900-c434-11e9-9429-c7372c2f0d29.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 9.0
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@diracdeltas is this warning message still relevant to iOS/Android? We had the warning message added in #1830 but it's removed in 1.3.0.

**Comment by diracdeltas** [comment]
@srirambv yes, the warning message is still crucial on all platforms. thanks!

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-rc1-x64 build
![image](https://user-images.githubusercontent.com/17010094/63614668-a2a33900-c5b1-11e9-876f-6798016313a6.png)
