### ISSUE TITLE
Verified icon and pub name needs padding in between

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1983]
## Description 
Verified icon and pub name needs padding in between

## Steps to reproduce 

   1. Clean install/upgrade to 1.3.0
   2. Enable rewards and visit a verified pub
   3. Open shields, no padding between verfied icon and publisher name

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/63545050-842b3800-c4f4-11e9-8f75-5ed6b293f7aa.png)

## Expected result
Similar to Desktop 
![image](https://user-images.githubusercontent.com/17010094/63545134-b9378a80-c4f4-11e9-90f8-b8694090daef.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.3.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Seeing the same issue in Samsung Galaxy J3 version 5.1.1 running `BraveModernarm v1.3.0-beta.1`

![Screenshot_2019-08-23-01-24-34](https://user-images.githubusercontent.com/38657976/63545569-5de1b880-c545-11e9-8ee1-9530c0642117.png)

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 9.0 running 1.3.0-rc1-x64 build
![image](https://user-images.githubusercontent.com/17010094/63613829-98803b00-c5af-11e9-89b8-b6941ec01251.png)
