### ISSUE TITLE
Remove "share..." from the setting menu

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2000]
## Description 
In a previous release we made a few changes to the bottom buttons on the menu (https://github.com/brave/browser-android-tabs/issues/1718)

As a follow on to this issue, please now remove "share..." from the setting menu

**Comment by srirambv** [comment]
Share button isn't removed but doesn't bring up the share sheet when pressed. Reopening the issue 
[sharebutton.zip](https://github.com/brave/browser-android-tabs/files/3618072/sharebutton.zip)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified no `Share...` entry in the menu 
* Verified its replaced with share button at the bottom of the list between `Download` and `Reload` buttons
* Verified copies the full URL when an app is selected via the share button 
* Verified the share button in URL edit mode also copies the entire URL into the app selected via the share button
