### ISSUE TITLE
Make DDG the default search engine in the following new countries

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2014]
## Description 

Please make DuckDuckGo (not DuckDuckGo lite) the default search engine in the following new countries:

- Germany
- Australia
- New Zealand
- Ireland

This is for NEW users only

Onboarding will need to be updated

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.0 rc3 BraveModernx86.apk

* For Germany, Australia, NZ, and Ireland, verified the following:
   * New install has DDG (not DDG lite) as the default SE for both normal and private tabs
   * Installed 1.3.2, left default SE. Upgraded to 1.4.0rc3 and verified that SE for both normal and private tabs remained unchanged from previous version.
   * Installed 1.3.2, changed default SE for both normal and private tabs. Upgraded to 1.4.0rc3 and verified that SE for both normal and private tabs remained unchanged from previous version.

* For other regions (US, GB), verified the following:
   * Clean install of 1.4.0rc3, verified SE was not DDG (normal and private tabs)
   * Installed 1.3.2, left default SE. Upgraded to 1.4.0rc3 and verified that SE for both normal and private tabs remained unchanged from previous version.
   * Installed 1.3.2, changed default SE for both normal and private tabs. Upgraded to 1.4.0rc3 and verified that SE for both normal and private tabs remained unchanged from previous version.

* Encountered #2097 once, but was unable to reproduce

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Clean install on Germany/Ireland/New Zealand/Australia
  * Clean install starts onboarding and has DDG selected as default SE
  * Skip onboarding retains DDG as default for normal and private tabs
  * Select a different SE during onboarding changes to the selected SE for both normal/private tabs
* Upgrade on Germany/Ireland/New Zealand/Australia
  * Verified custom SE from previous install is retained on upgrade 
  * Verified DDG popup modal shows up on upgrade when default SE is different via upgrade
  * Verified default SE from previous version is retained on upgrade
  * Verified DDG popup modal shows up on upgrade when default SE from onboarding is kept 
* Logged #2103 for DDG modal not showing up when a different SE is set during onboarding
