### ISSUE TITLE
Adblock doesn't work on Android 4.4

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2018]

**Comment by srirambv** [comment]
Marking QA/No as we don't currently have a physical device that's running this version

**Comment by SergeyZhukovsky** [comment]
It has been fixed in that commit https://github.com/brave/browser-android-tabs/commit/9ab34d0e9d6161a0b1f061a9f57f7cc28db4dba9
Basically the code is only executed on Android OS 5.0 and lower. Nothing is changed for higher versions.
