### ISSUE TITLE
yarn run couldn't find a package.json file while running getThirdParties.js

### ISSUE THREAD

**Issue by tungdx** [brave/browser-android-tabs#204]
Hello, I followed the guideline and run `sh scripts/getThirdParties.js` and then got this message 
![screenshot from 2017-04-05 15-09-05](https://cloud.githubusercontent.com/assets/1876051/24696238/fb43c360-1a12-11e7-8949-5e74f002eae3.png)

Could you tell me how to fix it? Thank you very much!

**Comment by SergeyZhukovsky** [comment]
Hi @tungdx, do you have braveSync folder inside your browser-android-tabs/src? I see that it says clone of brave/sync is failed to braveSync folder.
Could you please try to run that inside src folder
git submodule update --init braveSync
git submodule update braveSync

**Comment by tungdx** [comment]
Hi @SergeyZhukovsky, I think it's my mistake because I found that I didn't add depot_tools to PATH correctly, the terminal said gclient and gn not found.

This is my situation:
1) Initially (after cloning the project successfully)
I run `sh scripts/getThirdParties.js` without added depot_tools to PATH successfully and then I got the error as above. Next, I opened this issue.

2) Before your comment:
I added depot_tools to PATH successfully, then run `sh scripts/getThirdParties.js` again, and then I still got above error. However, I tried to run build script `ninja -C out/Default chrome_public_apk` even with above error. It took me many hours to run but finally, it's not success (I know it can not be success since the above error didn't resolve yet, but I just want to try)

3) After your comment:
I deleted the braveSync folder and clone it again as your suggestion (I did it inside src folder). I run `sh scripts/getThirdParties.js` again and got other error as below 
![screenshot from 2017-04-06 07-17-29](https://cloud.githubusercontent.com/assets/1876051/24732566/d402e1bc-1a9b-11e7-8895-9428cb092c6c.png)

Actually, it's my stupid mistake, so please help fix it without run everything again. I will appreciate it. Thank you so much!

**Comment by SergeyZhukovsky** [comment]
@tungdx you shouldn't run getThirdParties.js again as it installs yarn and etc again, that's why it gave you the error above about that. Could you please check do you have something inside src/braveSync? I suppose you do. Also check src/ad-block.
If yes, you should just do two things inside your src folder:
1. cd braveSync
yarn run build
2. Return to src folder from src/braveSync: cd..
sh scripts/copyAdBlockTPFiles.js

And after that you should be able to run ninja command for the build.

**Comment by tungdx** [comment]
@SergeyZhukovsky I am not lucky, I got other error
This is braveSync folder and src/ad-block
![screenshot from 2017-04-06 08-05-00](https://cloud.githubusercontent.com/assets/1876051/24733217/8f8e0f16-1aa0-11e7-8c40-69ea5da3dc05.png)

This is an error while running `yarn run build` without sudo
![screenshot from 2017-04-06 08-06-12](https://cloud.githubusercontent.com/assets/1876051/24733238/ad7edba4-1aa0-11e7-9f4c-64f335c7a45c.png)

I tried to run `yarn run build` with sudo and got this
![screenshot from 2017-04-06 08-08-41](https://cloud.githubusercontent.com/assets/1876051/24733254/cf3127a2-1aa0-11e7-89f2-5df6e8fa27ee.png)
![screenshot from 2017-04-06 08-08-56](https://cloud.githubusercontent.com/assets/1876051/24733260/d495b0a0-1aa0-11e7-8c86-d29720203001.png)

**Comment by SergeyZhukovsky** [comment]
@tungdx is there a file src/braveSync/bundles/bundle.js? If yes, then it is ok, I'll why does it want node as it shouldn't. So you can just run this if yes
sh scripts/copyAdBlockTPFiles.js
and ninja command.

**Comment by tungdx** [comment]
@SergeyZhukovsky bundles folder is empty :(
![screenshot from 2017-04-06 08-26-01](https://cloud.githubusercontent.com/assets/1876051/24733558/b349e932-1aa2-11e7-9023-7a266a136046.png)

**Comment by SergeyZhukovsky** [comment]
@tungdx Could you look do you have node installed? If not please install and try to build one more time https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by tungdx** [comment]
@SergeyZhukovsky Node is already installed. So I think I should try everything again because it's difficult to know where the problem is since the source code is so huge. I will let you know the result after cloning the code into other folder and do everything again. Again, thank you very much for your support. I appreciate it.

**Comment by SergeyZhukovsky** [comment]
@tungdx great. Let me know please if you have any problems:). I hope not.

**Comment by SergeyZhukovsky** [comment]
I can actually give that file and you'll be able to build with it, just unzip it. It'll save you lots of time.
[bundle.js.zip](https://github.com/brave/browser-android-tabs/files/901243/bundle.js.zip)

**Comment by tungdx** [comment]
@SergeyZhukovsky I just built it successfully using your file. You save my day. Thank you very much!

**Comment by SergeyZhukovsky** [comment]
@tungdx great!
