### ISSUE TITLE
Internal Issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2044]
https://github.com/brave/internal/issues/649

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.0 rc3 BraveModernx86.apk
* See notes on https://github.com/brave/browser-android-tabs/issues/2014#issuecomment-535134792
* Verified URL as per https://github.com/brave/internal/issues/649
