### ISSUE TITLE
Uplift some Core BR changes 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2045]
## Description 
Pls uplift https://github.com/brave/brave-core/pull/3296 into Android

**Comment by anthonypkeane** [comment]
This task has been completed as part of the core uplift

**Comment by srirambv** [comment]
Closing as this is part of core uplift that is already gone into cr78 rebase

**Comment by GeetaSarvadnya** [comment]
Verification passed on BraveModernarm 1.4.3-rc.1 running on Samsung Galaxy J3 version 5.1.1
 - Verified the test plan from https://github.com/brave/brave-core/pull/3296
 - Verified same ads are not shown more than once per hour on mobile
