### ISSUE TITLE
Ad notifications are not delivered on Android unless browser enters the background and then becomes active

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2046]
## Description 

Ad notifications are not delivered on Android unless browser enters the background and then becomes active

## Steps to Reproduce

   1. Launch browser
   2. Enable Brave ads
   2. Visit brave.com
   3. Wait 30 minutes

## Actual result:

An ad is not shown

## Expected result:
An ad should be shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.3.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

https://github.com/brave/brave-browser/issues/5879

**Comment by srirambv** [comment]
Fixed in https://github.com/brave/brave-core/commit/9944f561dcb4e8e347212f4aa117ffeea3883d7d

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.3.2 x64 build
* Verified on upgrade, ads showed up after 30 mins when app was kept in foreground
* Verified on a clean install, ads showed up after 30 mins when app was kept in foreground
Log for clean install with default ads setings:[Tablet_Ads_log.txt](https://github.com/brave/browser-android-tabs/files/3575661/Tablet_Ads_log.txt)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+ with Android 9` using `1.3.2 CR: 76.0.3809.132`:

* `x2` - Verified that an ad was displayed after `30mins` while Brave was in the foreground
   * Log 1 --> [Case1ForegroundClean.txt](https://github.com/brave/browser-android-tabs/files/3577647/Case1ForegroundClean.txt)
  * Log 2 --> [Case2ForegroundClean.txt](https://github.com/brave/browser-android-tabs/files/3577648/Case2ForegroundClean.txt)

* `x2` - Verified that an ad was displayed while `1.3.2 CR: 76.0.3809.132` was opened in the foreground for `30mins` after upgrading from `1.3.1 CR: 76.0.3809.132`
   * Log 1 --> [Case1UpdatedForgeground.txt](https://github.com/brave/browser-android-tabs/files/3577655/Case1UpdatedForgeground.txt)
  * Log 2 --> [Case2UpdatedForgeground.txt](https://github.com/brave/browser-android-tabs/files/3577657/Case2UpdatedForgeground.txt)

* `1x` - Verified that an ad wasn't being displayed after `30mins` while Brave was in the background
   * Log 1 --> [Case2Bacground.txt](https://github.com/brave/browser-android-tabs/files/3577672/Case2Bacground.txt)

* `1x` - Verified that an ad wasn't being displayed after `30mins` while the device was locked
   * Log 1 --> [Case1DeviceLocked.txt](https://github.com/brave/browser-android-tabs/files/3577665/Case1DeviceLocked.txt)
