### ISSUE TITLE
"Reset Brave Rewards" takes a while to reset the wallet after restart (tables not clearing in the meantime)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2052]
## Description 

When attempting to reset rewards via `Reset Brave Rewards`, you'll notice that it take a while for the entire wallet to actually release. The rewards panel mentioned `Welcome back!` but rewards still looks like they're enabled. Both the `tips` and `a-c` tables are not reset.

## Steps to reproduce 

   1. launch `1.3.1 (76.0.3809.132)` and enable rewards via the onboarding experience
   2. once enabled, visit a random video on YT so there's an entry in a-c
   3. select `Settings` -> `Brave Rewards` -> `Reset Brave Rewards`
   4. select `COFIRM` & `RELAUNCH NOW` via the modals (brave will restart)
   5. once brave restarts, tap on the Rewards panel and you'll see the `Welcome back!` message and the spinner next to `BAT`
   6. select `Settings` so `chrome://rewards` opens and you'll notice `Rewards` is still enabled
   7. tap on `View Details` under `Auto-Contribute` and you'll notice that the table hasn't been cleared
   8. disable and enable rewards via `chrome://rewards` and everything will be cleared

## Actual result 

`Brave Rewards` stays enabled and takes a while too actually "reset". Once in this state, the `a-c` and `tip` tables are not reset. Sometimes you'll get into the following state:

![Screenshot_20190905-211648_Brave](https://user-images.githubusercontent.com/2602313/64394259-47e2f600-d023-11e9-9471-0a3486e148f2.jpg)

## Expected result

Using `Reset Brave Rewards` should correctly reset the entire rewards wallet once the browser resets.

## Issue reproduces how often 

100% reproducible using the the above STR.

## Issue happens on 
   - Current Play Store version? Yes, reproducible using `1.3.1 (76.0.3809.132)`
   - Beta build? Yes, reproducible using `1.3.2 (76.0.3809.132)`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 9`
   
## Brave version

Reproduced under the following:

* `1.3.1 (76.0.3809.132)`
* `1.3.2 (76.0.3809.132)`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @SergeyZhukovsky @anthonypkeane @brave/legacy_qa

**Comment by anthonypkeane** [comment]
Anthony to ask @tmancey about this
