### ISSUE TITLE
Create setting to manually enable Dark Mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2065]
## Description 
Android 10 supports dark mode, but OS <10 do not natively support it. 

Therefore please create the following setting.

For Android 10

In Display > Appearance, under Enable bottom toolbar, add a sub heading for Theme and add the following 

System default
Light
Dark

Our Default: System default

For Android 9 and lower 

In Display > Appearance, under Enable bottom toolbar, add a sub heading for Theme and add the following 

Light
Dark

Our Default: Light

![Dark Mode Option.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/5a87d19f-9b75-49c5-80cf-b704b68b7660)

Add radio buttons like Android do

![Screenshot_20190913-172648.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/d063d0b3-9b43-4bd4-bb96-9d26a0df981a)

@deeppandya please investigate what OS's can support Dark mode, i.e Android 6 may not. If it doesn't don't show this option.

cc @SergeyZhukovsky for input on this one

**Comment by deeppandya** [comment]
@anthonypkeane We have **Theme** option in Settings as main menu option and it's same as chrome. Do we need to move **Theme** option to **Appearance** ?

**Comment by deeppandya** [comment]
@anthonypkeane @SergeyZhukovsky  Samsung and other manufactures provide **Night mode** option even for before android 10. So i think we should show **System default** for all options as if dark mode is not available, **System default** would be light mode. any thoughts ?

**Comment by SergeyZhukovsky** [comment]
sounds good to me.

**Comment by anthonypkeane** [comment]
@srirambv can you input on this one too? Thanks

**Comment by srirambv** [comment]
I think it is better to have `Themes` under `Appearance` so that it's more organised as we already have a very big main menu. 

We should have `System default` for all supported OS versions. All OS <10 will have light as default and Android 10 can have either dark/light as system default based on what is set on the device.

**Comment by jamesmudgett** [comment]
I agree

**Comment by deeppandya** [comment]
@anthonypkeane @srirambv @SergeyZhukovsky I think we should enable dark mode of the device has dark mode enabled for devices < android 10. Samsung devices has dark mode for <android 10 and we don't have dark mode enabled.

**Comment by srirambv** [comment]
@deeppandya  for < A10, Does system default always fallback to light or does is it possible to take the theme setting? Can we have system default set dark if theme is dark for other theme set it to light?

**Comment by anthonypkeane** [comment]
@deeppandya 
Please implement system default to equal the Android OS default, i.e. light or dark. 
Ignore manufacture defaults for this ticket.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 RC3 build 
* Verified setting Dark theme on Oxygen OS doesn't show `System default` option under themes
* Verified able to switch between light/dark mode independent of device-level theme setting
