### ISSUE TITLE
Increase max number of Brave ads from 12 to 20

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2068]
## Description 

Please increase max number of Brave ads from 12 to 20

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane I would move that to next milestone. Where is that number at all? Is it max 20 in 24 hour or what? As in settings we have 5 per hour.

**Comment by anthonypkeane** [comment]
Desktop: https://github.com/brave/brave-browser/issues/6362

**Comment by tmancey** [comment]
@SergeyZhukovsky This change has been made in `brave-core` under https://github.com/brave/brave-core/pull/3635 so will be part of next uplift of brave-core into Android

**Comment by samartnik** [comment]
This is done within `brave-core`

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.4.3 RC3 x64 build
* Verified max ads is changed from 12. Was able to get 14 ads(captured in logs)
[Ads log](https://github.com/brave/browser-android-tabs/files/3778939/20adslog.txt)
* @GeetaSarvadnya  confirmed that she was able to get 16 ads on her device
