### ISSUE TITLE
Context menu dark mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2073]
## Description 

Please add dark mode to this menu

![Screenshot_20190917-144044.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/a78e2df1-5bab-4ebe-82a4-66131dd5f7e2)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3
* Verified context menu on tab container is dark when browser theme is set to dark
* Verified switching theme to light makes the context menu also light
* Verified context menu on private tabs are also respecting the theme that is set
![image](https://user-images.githubusercontent.com/17010094/65427197-cf7c8300-dddf-11e9-9311-6c68d829e8e4.png)
