### ISSUE TITLE
`Android` grants are received but not confirmed: spinner on UI spins indefinitely.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2074]
## Steps to reproduce 

   1. Use debug/staging version.
   2. Set up VPN to ads-free region.
   3.  Receive and claim grant. 

## Actual result 
Spinner on UI spins indefinitely (both panel and settings page).

## Expected result
Grant is received and wallet is updated with new balance.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Fixed by:
https://github.com/brave/brave-core/commit/4c8e7a64f8fc51a6c41e7d7c3fd71f76aac3826a

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.4.1-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0). 
Verified STR from the description. Used Belgium as region.
![Screenshot_20191008-014141](https://user-images.githubusercontent.com/34715963/66356887-040a4600-e96d-11e9-8bc3-0a7265ce45cc.png)
