### ISSUE TITLE
Sync page text isn't visible when dark mode is set

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2075]
## Description 
Sync page text isn't visible when dark mode is set

## Steps to reproduce 

   1. Upgrade to 1.4.0
   2. Set theme to dark from settings
   3. Open sync page to add a new device
   4. Text is not visible 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65073341-afbd0900-d960-11e9-8ea5-729949d66541.png)
![image](https://user-images.githubusercontent.com/17010094/65073050-0e35b780-d960-11e9-9378-2909b26a6db9.png)
![image](https://user-images.githubusercontent.com/17010094/65073127-345b5780-d960-11e9-8a6a-4cd36c014685.png)
![image](https://user-images.githubusercontent.com/17010094/65073168-4d640880-d960-11e9-8d6c-c1bcef18c451.png)

## Expected result
Text should be visible on both Dark and light theme

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T 
   - Android version: 9.0
   
## Brave version
1.4.0 rc2 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Device is set to dark mode as well.

**Comment by anthonypkeane** [comment]
@karenkliu Do we have UI for Sync Dark Mode?

**Comment by srirambv** [comment]
@anthonypkeane this needs to be part of 1.4.0 because existing sync page text and code words are not visible when dark mode is set.

**Comment by anthonypkeane** [comment]
@deeppandya has this completed for full dark mode now

**Comment by deeppandya** [comment]
@anthonypkeane it's been fixed as iOS dark mode ui

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified all screens on Sync is inheriting the dark theme when browser theme is set to dark
![sync_main_page](https://user-images.githubusercontent.com/17010094/65427956-76155380-dde1-11e9-876a-7232198f1087.jpg)
![add_device_name1](https://user-images.githubusercontent.com/17010094/65427931-6990fb00-dde1-11e9-90d9-31c7f5689f8b.jpg)
![add_device](https://user-images.githubusercontent.com/17010094/65427928-68f86480-dde1-11e9-938c-53449094f407.jpg)
![scan_qr_code](https://user-images.githubusercontent.com/17010094/65427935-6a299180-dde1-11e9-8f10-2883bf1c5363.jpg)
![add_code_words](https://user-images.githubusercontent.com/17010094/65427927-68f86480-dde1-11e9-87cf-435027923d7f.jpg)
![add_device_name](https://user-images.githubusercontent.com/17010094/65427930-68f86480-dde1-11e9-9da9-39c8bae7af5b.jpg)
![add_qr_codes](https://user-images.githubusercontent.com/17010094/65427932-6990fb00-dde1-11e9-98c3-17caac725589.jpg)
![enter_code_words](https://user-images.githubusercontent.com/17010094/65427933-6990fb00-dde1-11e9-8539-86d0d457a297.jpg)
![remove_device](https://user-images.githubusercontent.com/17010094/65427934-6990fb00-dde1-11e9-992d-4e3257c3cbea.jpg)
