### ISSUE TITLE
Ads log info on rewards-internals 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2077]
Follow up to #1676 

* Put logging in that page to help diagnose ad issues.
* What ad data will be logged needs to be defined.
* We want this to be a 1000 line circular buffer of what would normally come along with `--vmodule=brave_ads=3` on command line logging. And it should also log region whether or not supported as that is relevant to debug.

cc: @anthonypkeane @jsecretan @tmancey @samartnik @SergeyZhukovsky @gdregalo

**Comment by anthonypkeane** [comment]
closing as @alexwykoff has a new spec for this
