### ISSUE TITLE
Private theme missing on 1.4.0

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2078]
## Description 
As part of #1798  private tabs supposed to have its own theme similar to desktop/iOS but is missing on Android build 1.4.0

## Steps to reproduce 

   1. Install 1.4.0
   2. Set theme to dark mode
   3. Open private tab, no theme changes 

## Actual result 
Private theme missing on 1.4.0

## Expected result
Private theme should be applied for private tabs

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Reproduced by @GeetaSarvadnya on her device as well.

**Comment by jamesmudgett** [comment]
Possible solution here - and needed for iOS as well - is a way to display private mode while remaining theme agnostic. For future we plan to allow users to change the theme of private mode, so it will be important to have a permanent indicator, similar to desktop.

![Screen Shot 2019-09-18 at 10 47 06 AM](https://user-images.githubusercontent.com/318119/65165113-bcdf0400-da03-11e9-9660-69dc8e118cd4.png)

I'm not sure where this would live but will need to be the solution, at least until android chromium supports multiple themes. Will update ticket with design when ready.

**Comment by kjozwiak** [comment]
Downloaded https://github.com/brave/browser-android-tabs/releases/tag/v1.4.0-rc.3 and reproduced the original issue mentioned via https://github.com/brave/browser-android-tabs/issues/2078#issue-495305772.

Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

* ensured that the PB theme was being used when using both `light` and `dark` themes.
