### ISSUE TITLE
The balance on the panel is rounded up which results in `not enough funds` message when tipping.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2079]
## Description 
The balance on the panel is rounded up which results in `not enough funds` when tipping

## Steps to reproduce 

   1.  Create  a wallet and make sure it has a real balance less then a tipping amount, e.g.: 
     0.996500. Check log output to find the exact number.
   2.  Observe that panel and site banner round the balance up and show 1.0 BAT.
   3. Tip a publisher with 1 BAT and get a message "Not enough funds".

## Actual result 
Tip a publisher with 1 BAT and get a message "Not enough funds".

## Expected result
The balance is rounded down and it is not  confusing why user see "Not enough funds" message.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Fixed by https://github.com/brave/browser-android-tabs/commit/845d6b8a3e47ca28b47a0817fa8bafe1eabaaf33

**Comment by gdregalo** [comment]
One more commit:
https://github.com/brave/browser-android-tabs/commit/622c48850f65148a84c4968ff40a46f6e5f22132

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.1 RC 1 x64 build 
* Verified wallet balance is not rounded out to full value
* Shows correct decimal value for wallet balance
![image](https://user-images.githubusercontent.com/17010094/66165004-cc646c80-e601-11e9-86fd-f143147b8703.png)
