### ISSUE TITLE
The Rewards panel report items are displayed under wrong categories

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2082]
## Description 
The Rewards panel report items are displayed under wrong categories.

## Steps to reproduce 

   1.  Do one-time tip or wait for AC to complete.
  

## Actual result 
  Observe that all items are displayed under wrong categories.
  One time tip is empty.

## Expected result
Every report value should match its category.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Fixed by:
https://github.com/brave/browser-android-tabs/commit/9cbb0549352f877e3570f219be31f919035b991f

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.1 rc2 x64 build. 
* Verified panel items are properly displayed for the category they belong to 
![image](https://user-images.githubusercontent.com/17010094/66415517-bbcd4100-e9c9-11e9-88c5-e6c445f9f887.png)
![Untitled](https://user-images.githubusercontent.com/17010094/66415805-6e050880-e9ca-11e9-8ab9-0220193faf12.png)
