### ISSUE TITLE
Recover AdBlock, tracking protection and HTTPSE after rebasing on Chromium 77

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2084]

**Comment by samartnik** [comment]
Fixed by this commit https://github.com/brave/browser-android-tabs/commit/e6c6c3541e553e499cdd3128b9dbea1078479649

**Comment by samartnik** [comment]
No test plan here. We need to check generally that AdBlock, tracking protection and HTTPSE work.

**Comment by samartnik** [comment]
+ check fingerprinting protection

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.1 rc2 BraveModernx86.apk.
* Verified `Bravery Settings` and `Fingerprint Tests` sections from manual pass on clean install and upgrade profiles.
* Exploratory testing in shields area.
* Verified NTP stats update on clean and upgrade profiles.
