### ISSUE TITLE
Recover partner headers after rebasing on Chromium 77

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2085]

**Comment by samartnik** [comment]
Fixed by this commit https://github.com/brave/browser-android-tabs/commit/e6c6c3541e553e499cdd3128b9dbea1078479649

**Comment by samartnik** [comment]
There is no particular test plan here. We just need to make sure that partner headers work as supposed to work on `barrons.com`, `marketwatch.com` etc.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.1 RC2 x64 build
* Verified `x-brave-partner:dowjones` is shown on both marketwatch and barrons page
Market Watch:
![image](https://user-images.githubusercontent.com/17010094/66341933-38064c80-e916-11e9-9088-d455dcd7d855.png)
Barrons:
![image](https://user-images.githubusercontent.com/17010094/66341965-4eaca380-e916-11e9-9001-f87fb2a0e059.png)
* Verified able to view premium content on Brave but not on Chrome prompted to install Brave to continue reading that article
