### ISSUE TITLE
Clear data button needs to have primary button colour

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2086]
## Description 
Clear data button needs to have primary button colour

## Steps to reproduce 

   1. Set theme to light
   2. Clear browsing data from privacy 
   3. Clear data button is in blue
   4. Set theme to dark
   5. Button colour just inverts 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65178454-bf9f2080-da26-11e9-969e-edbdd56b9ae4.png)

## Expected result
Should use primary button colour similar to desktop

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@anthonypkeane @srirambv @SergeyZhukovsky In the current app, we use blue color at many places in screens from settings. This blue color comes from chromium. we need to check All UI in settings to see what are the things we should update. @jamesmudgett can you take a look at this ?

**Comment by anthonypkeane** [comment]
@jamesmudgett to confirm but this issue can move to 1.5.0 if needed.

**Comment by srirambv** [comment]
@anthonypkeane sounds good. Since this is always been blue button moving it out to 1.5.0

**Comment by szaimen** [comment]
At least on my phone with Brave 1.4.3 is the button already orange.

**Comment by deeppandya** [comment]
@srirambv @SergeyZhukovsky it seems to be fixed on CR-78. so closing this issue.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.6.1 beta1 BraveModernx86.apk
![Screenshot_20191212-123544](https://user-images.githubusercontent.com/28145373/70735425-412be500-1cdc-11ea-9c43-702c01bb5f86.jpg)
![Screenshot_20191212-123600](https://user-images.githubusercontent.com/28145373/70735432-44bf6c00-1cdc-11ea-8e13-62e2dd6f1516.jpg)
