### ISSUE TITLE
Set default browser message remains white on dark theme

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2087]
## Description 
Set default browser message remains white on dark theme

## Steps to reproduce 

   1. Set theme to dark
   2. Select set default browser from menu
   3. Set browser message is shown in white

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65178619-215f8a80-da27-11e9-9ff3-c813bcfd7601.png)

## Expected result
Should be dark as the message is initiated from app

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified default browser notification is dark when browser theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/65430296-b080ef80-dde5-11e9-9180-41ce41aebfad.png)

**Comment by LaurenWags** [comment]
Unable to check on x86 as device has Android 6.0 (API level 23) and this feature is only available in newer versions (API level 27 and above).

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.4.0 RC4 x64 build
* Verified default browser notification is dark when browser theme is dark 
![image](https://user-images.githubusercontent.com/17010094/65884035-1df0cb00-e366-11e9-81b4-19c3e5f4b657.png)
