### ISSUE TITLE
Include in ac switch when turned off doesn't show button shadow in dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2088]
## Description 
Include in ac switch when turned off doesn't show button shadow in dark mode

## Steps to reproduce 

   1. Set device theme to dark
   2. Enable rewards and visit any site 
   3. Open panel and disable include in ac switch, button shadow isn't visible

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65269031-60a0e080-dae6-11e9-9f5e-0c363b0afb10.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/65269051-672f5800-dae6-11e9-9c50-fa35cf86e8d9.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.0 rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @jamesmudgett

**Comment by deeppandya** [comment]
@srirambv @jamesmudgett @anthonypkeane I have updated this issue. https://slack-files.com/T04PX1BU8-FN66K4WF4-afe2b147c7 https://slack-files.com/T04PX1BU8-FNJFM7KJQ-70fb22297f

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc3 x64 build
* Verified the switch when toggled to off state shows the button state even on dark mode
![image](https://user-images.githubusercontent.com/17010094/65430505-0f466900-dde6-11e9-9bb3-a72054e28553.png)
