### ISSUE TITLE
[hackerone] Clear-Site-Data crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#2090]
originally reported at https://hackerone.com/bugs?subject=brave&report_id=696714

for steps to reproduce see https://bravesoftware.slack.com/archives/C6R461GF4/p1568748723002200 (private since this is a security issue)

**Comment by gdregalo** [comment]
Fixed in branch `base-77.0.3865.73` by
https://chromium.googlesource.com/chromium/src.git/+/8e902a99db15dacea3d1ce4bdd68a4dba924923b

**Comment by samartnik** [comment]
I believe as a test paln we should just check it is not reproduced by these steps https://bravesoftware.slack.com/archives/C6R461GF4/p1568748723002200

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.1 rc1 BraveModernx86.apk
* Verified test plan specified in https://github.com/brave/browser-android-tabs/issues/2090#issuecomment-537940333
