### ISSUE TITLE
Update HTTPS count text colour to match Desktop/iOS

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2094]
## Description 
Update HTTPS count text colour to match Desktop/iOS

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65532183-5ce7d200-dec9-11e9-8308-21c8450d00ee.png)

## Expected result
Should match the colour on desktop/iOS

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
https://bravesoftware.slack.com/archives/C0816QH3R/p1569858452094600

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

#### `0.73.55 CR: 78.0.3904.87`

<img width="598" alt="Screen Shot 2019-11-05 at 2 31 22 AM" src="https://user-images.githubusercontent.com/2602313/68187417-9b66b700-ff74-11e9-80e1-ec45c6be2868.png">

#### `Brave 1.5.0 CR: 78.0.3904.90`

<img width="510" alt="Screen Shot 2019-11-05 at 2 32 23 AM" src="https://user-images.githubusercontent.com/2602313/68187390-8722ba00-ff74-11e9-8aff-a0d703c449f8.png">
