### ISSUE TITLE
Token grant message is not visible on dark theme

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2095]
## Description 
Token grant message is not visible on dark theme

## Steps to reproduce 

   1. Set browser theme to dark
   2. Claim grant
   3. Open panel, text is not visible for token grant

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65606132-519faf80-df78-11e9-80c5-a40c21a20a63.png)

## Expected result
Should be visible on all theme

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 9.0
   
## Brave version
1.4.0 RC3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@anthonypkeane this should be for 1.4.0 as i have already updated it and it was a similar change to other dark mode related changes.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc4 x64 build
![image](https://user-images.githubusercontent.com/17010094/65780379-9ca3f900-e117-11e9-9a4c-2613bde755f9.png)
