### ISSUE TITLE
Consider building apks with chrome_modern_public_apk  option

### ISSUE THREAD

**Issue by mthomos** [brave/browser-android-tabs#2101]
I saw that you build APKs using both monochrome and modern options. Should you consider using only modern option especially for 64bit versions to reduce APK size.

https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md#Multiple-Chrome-APK-Targets

**Comment by mthomos** [comment]
Can anyone take a look at this ?

**Comment by mthomos** [comment]
With current implementation 64bit binaries are useless because app uses 32bit binaries. This can be viewed in chrome://version. So 64bit devices don't load 64bit binaries and don't provide the performance uplift of 64bit binaries especially in JavaScript operations

**Comment by anthonypkeane** [comment]
Google bundles the apk's this way. Thanks

**Comment by mthomos** [comment]
Google doesn't provide 64bit binaries for Chrome Stable. Google only provides the 32bit version. Please consider this again because of the extra size without any perf benefit.
