### ISSUE TITLE
DDG modal doesn't show up when a different SE is set during onboarding for DE/IE/NZ/AU

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2103]
## Description 
DDG modal doesn't show up when a different SE is set during onboarding for DE/IE/NZ/AU

## Steps to reproduce 

   1. Set device to IE/DE/AU/NZ
   2. Clean install 1.4.0 
   3. Ensure DDG is selected as default SE in onboarding
   4. Change default SE to Qwant in onboarding 
   5. Ensure default SE is changed in Settings
   6. Open a new Private tab, no DDG modal is shown 

## Actual result 
DDG modal isn't shown on the first private tab opened. Also the DDG message is missing on private tab

## Expected result
Should show DDG modal when SE is different on first private tab that is opened. If user selects no then DDG message should be shown on private tab

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.4.0 RC3 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Reproduces on Asus Zenfone (x86) with Android 6.0 running 1.4.0 rc3 BraveModernx86.apk

STR:

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.4.0 RC4 x64 build
* Verified DDG modal and info message is shown on the first private tab when default SE is changed during onboarding

Verification passed on OnePlus 6T  with Android 9.0 running 1.4.0 RC4 x64 build
* Verified DDG modal and info message is shown on the first private tab when default SE is changed during onboarding
