### ISSUE TITLE
Other devices in sync chain is not visible when set to dark theme

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2107]
## Description 
Other devices in sync chain is not visible when set to dark theme

## Steps to reproduce 

   1. Set device theme to dark
   2. Create sync chain and add devices to the list
   3.  Devices other than the mobile is not visible 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/65721670-711e0180-e078-11e9-93a3-a86f44a2f584.png)

## Expected result
Visible device names 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.4.0 RC4 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.4.0-rc.4 on Huawei MediaPd M3 Lite 10 (Android 7.0).
![Screenshot_20190928-022625](https://user-images.githubusercontent.com/34715963/65808887-e3d1ce80-e197-11e9-8a5f-6420bcea402d.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5.1.1 BraveModernarm 1.4.0-rc4

![Screenshot_2019-09-30-21-23-40](https://user-images.githubusercontent.com/38657976/65895381-026adc00-e3c9-11e9-99e7-eed502942bbc.png)

**Comment by LaurenWags** [comment]
Reproduced with Asus Zenfone (x86) with Android 6.0 running 1.4.1 rc1 BraveModernx86.apk

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

![Screenshot_20191105-030732](https://user-images.githubusercontent.com/2602313/68189593-9fe19e80-ff79-11e9-828f-f3d81669aafb.png)
