### ISSUE TITLE
HTTPSE upgrade doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2119]
## Description 
Found while testing #2084, visiting a link that has https upgrade doesn't work

## Steps to reproduce 

   1. Visit http://https-everywhere.badssl.com
   2. Doesn't auto upgrade to https://https-everywhere.badssl.com

## Actual result 
HTTPSE doesn't work 

## Expected result
Should upgrade to https where available

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/f77f380ab1751d3a11805f0109c60879397937c5

**Comment by LaurenWags** [comment]
Verified passed on Asus Zenfone (x86) with Android 6.0 running 1.4.1 rc2 BraveModernx86.apk
* Verified with clean and upgrade profiles
* Verified toggle for HTTPSE works as expected
