### ISSUE TITLE
"Share" menu option not showing on Android tablets main menu

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#2121]
## Description 
On Android tablets, the "share" option is not appearing in the main menu. Note that the option still appears in address bar drop down. 

## Steps to reproduce 

   1. Update Brave on Android tablet to v1.4.0
   2. Visit a site and open main menu

## Actual result 
No share button appears.

## Expected result
Share button should be present in the main menu.

## Issue reproduces how often 
Always.

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Unclear

## Device details
   - Device (Phone, Tablet, Phablet): Android Tablet devices
   
## Brave version
v1.4.0

### Additional information

User reports:
https://community.brave.com/t/brave-1-4-0-for-android-missing-share-in-tablet-mode/85847/3

**Comment by Brave-Matt** [comment]
I have some users saying that it's also an issue on the Amazon Fire tablet:
https://community.brave.com/t/brave-1-4-0-for-android-missing-share-in-tablet-mode/85847

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.4.1 RC3 x64 build
* Verified `Share` menu item is listed on rc3 build
* Verified selecting `Share` copies the complete URL 
* Verified able to share the URL to a different application via the `Share` button 
![image](https://user-images.githubusercontent.com/17010094/66572361-d07f1580-eb3e-11e9-8310-7e875d4390cb.png)
