### ISSUE TITLE
Disable article download section from downloads page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2122]
## Description 
Disable article download section from downloads page

## Steps to reproduce 

   1. Upgrade to 1.4.1
   2. Download a file
   3. Open downloads page, has an option for listing articles downloaded via wifi

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/66167419-16e8e780-e608-11e9-8087-1482f14d0776.png)

## Expected result
No article downloads section

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by anthonypkeane** [comment]
Internal Chat: https://bravesoftware.slack.com/archives/C0816QH3R/p1570139649126200

**Comment by samartnik** [comment]
Disabled https://github.com/brave/browser-android-tabs/commit/31ab8fc5570312042e6ec9a71052cd95d8774cf6

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.1 rc2 BraveModernx86.apk
* Verified STR from description on both clean and upgrade profiles
![Screenshot_20191004-165442](https://user-images.githubusercontent.com/28145373/66239404-c6d15a00-e6c7-11e9-8bd2-55f3c65e09cc.jpg)
