### ISSUE TITLE
Crash when opening Brave Rewards from Settings

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2123]
We had this issue before: https://github.com/brave/browser-android-tabs/issues/1763

## Description 
Browser crashes when opening Brave Rewards through Hamburger Menu

## Steps to reproduce 

   1. Clean install
   2. Open Brave
   3. Open Hamburger Menu
   4. Tap `Settings`
   5. Tap `Brave Rewards`

## Actual result 
Crash
![Screenshot_20191004-150749_Brave](https://user-images.githubusercontent.com/34715963/66210132-63d8c680-e6b9-11e9-990b-72280fa2d85d.jpg)

## Expected result
No crash

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Samsung s7
   - Android version: 8.0
   
## Brave version
BraveModernarm v1.4.1-rc.1 on Samsung s7 (Android 8.0).
BraveModernarm v1.4.1-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0).

cc @brave/legacy_qa @SergeyZhukovsky

**Comment by samartnik** [comment]
Fixed here https://github.com/brave/browser-android-tabs/commit/1f6ac9ad9512461dc11f3b73c7d4108cc071897a

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.4.1-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0).

Verified that there is no crash.
![Screenshot_20191008-014736](https://user-images.githubusercontent.com/34715963/66357107-e8ec0600-e96d-11e9-9c32-968d00b68814.png)
