### ISSUE TITLE
Tips are not shown unless page is reloaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2130]
## Description 
While testing #2082 found that any tips that are done both one time and recurring are not displayed under `chrome://rewards/donation` unless you reload the page manually. Happens on both clean install and on upgrade

## Steps to reproduce 

   1. Clean install or upgrade to 1.4.1
   2. Visit any site and tip them
   3. Open `chrome://rewards/donation`, site is not listed
   4. Reload the page, tipped site shows up

## Actual result 
Tips are not shown unless page is reloaded

## Expected result
Should list the site that got tipped automatically

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.4.1 rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

### Additional information

cc; @gdregalo

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.4.1-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0).

**Comment by samartnik** [comment]
It never worked on Android. Will be fixed in future version.

**Comment by anthonypkeane** [comment]
Setting page re-write will be fix this.
