### ISSUE TITLE
Ads notification isn't limited to 3 in tray on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2133]
## Description 
Found the issue on Pixel device. Ads notification isn't limited to 3 in tray on upgrade

## Steps to reproduce 

   1. Install 1.3.2 and enable ads
   2. Upgrade to 1.4.0 
   3. Ads notification isn't limited to 3 in tray

## Actual result 
More than 3 ads are shown in notification area

## Expected result
Should limit to 3

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Fixed in
https://github.com/brave/brave-core/commit/b5fc476593003b23b5c597302cfefb4af9dafbdd

**Comment by gdregalo** [comment]
Test plan:
-Update  Brave browser from G Play  (or manually update the app with command `adb install -r Brave.apk` ) and observe the maximum number of notifications posted is 3.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.1 RC3 x64 build
* Verified on upgrade ads notification is limited to 3 in tray
First set of notifications
![image](https://user-images.githubusercontent.com/17010094/66590188-33cc7000-eb5e-11e9-9d87-96128d4de702.png)
Last notification removed from tray and is replaced with new one but still limiting to 3 
![image](https://user-images.githubusercontent.com/17010094/66590227-45ae1300-eb5e-11e9-8a3a-51e603ee0e96.png) 
[Full log for #2133.txt](https://github.com/brave/browser-android-tabs/files/3713727/2133.txt)
