### ISSUE TITLE
Implement sync changes to match Desktop folder mapping

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2135]
## Description 

Bookmark folder mapping across iOS, Android and Desktop is not consistent. As detailed in https://github.com/brave/brave-browser/issues/5158 we want to resolve this. 

On https://github.com/brave/brave-browser/issues/5158, Desktop will 

- Rename Bookmarks Bar to Bookmarks
- Hide Other Bookmarks 
- Migration the bookmarks that are inside “Other Bookmarks” to new folder called “Other Bookmarks” and nest it under the Bookmarks folder (i.e. Bookmarks > Other Bookmarks)

On Android this ticket should rename Mobile Bookmarks to Bookmarks so we have a clear mapping across  iOS, Android and Desktop

@srirambv @SergeyZhukovsky for input.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.0rc1 BraveModernx86.apk
   * Confirmed `Mobile Bookmarks` is renamed to `Bookmarks` on clean install of 1.5.0rc1
   * Confirmed `Mobile Bookmarks` is renamed to `Bookmarks` on upgrade from 1.4.3 where sync was not enabled.
   * Confirmed `Mobile Bookmarks` is renamed to `Bookmarks` on upgrade from 1.4.3 where sync was enabled.
