### ISSUE TITLE
Notifications wont open Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2138]
## Description 
Notifications wont open Brave. Reported via community 

## Steps to reproduce 

   1. Install 1.4.1
   2. Get notification from websites
   3. Long press on app in homescreen to bring up notification
   4. Click on notification, Brave doesn't open 

## Actual result 
[Link to video recording](https://community.brave.com/t/the-notification-does-not-open-in-brave/85958?u=sriram)

## Expected result
Should open Brave

## Issue reproduces how often 
Easy 

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.4.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

https://community.brave.com/t/the-notification-does-not-open-in-brave/85958?u=sriram

**Comment by Adrymate9** [comment]
the problem you lost today, with Brave 1.4.1 rc3 installed from github. 

The device is a Huawei mate 9 armx64.It works with Android 8.0.

**Comment by srirambv** [comment]
Moving out of 1.4.1 as its not a release blocker.

**Comment by Adrymate9** [comment]
@srirambv Do you suggest that you try version 1.4.0?

**Comment by Adrymate9** [comment]
I am testing it with the latest version of github installed and it still doesn't work.

This is the link that states that the problem persists

https://community.brave.com/t/the-notification-does-not-open-in-brave/85958/9?u=adrymate9

**Comment by SergeyZhukovsky** [comment]
@Adrymate9 the fix is marked for 1.5.0 version, the latest github version is 1.4.2

**Comment by srirambv** [comment]
@Adrymate9  the fix is not on any build that is on GH

**Comment by Adrymate9** [comment]
@SergeyZhukovsky @srirambv ok. Thanks for answering. I look forward to version 1.5.0. I don't speak English and sometimes I misunderstand. 

I am very happy that we are so close to the solution. It really is what I need to never leave Brave again!

Regards.

**Comment by Adrymate9** [comment]
@SergeyZhukovsky hello, I just installed version 1.5.0 of github and it still fails to open push notifications. Nothing has changed in this regard. 

You had commented on the implementation of the solution in this new update.

What happened?

**Comment by gdregalo** [comment]
hi @Adrymate9, we have tested web-notifications (including the one you posted) and they seem to work well in 1.5.0. Please describe the scenario you still have troubles with. Thanks.

**Comment by Adrymate9** [comment]
@gdregalo The same thing continues to happen as at the beginning. If I press on the notification on the backdrop of notifications deployed, the application never opens.

I send open thread link in Brave community where the demonstration video is seen.

I await comments. Thank you

**Comment by gdregalo** [comment]
@Adrymate9 
please try this resource to generate web notifications and let me know how it works:
(https://web-push-book.gauntface.com/demos/notification-examples).
Please make sure you're running 1.5.0 version.
1. Use "Open window" example to generate a web-notification.
 - Tap it while having your browser running. It supposed to open a new tab in your browser with example content. 
2. Use "Open window" again. Close browser. Tap notification. It supposed to start browser and open a new tab.

**Comment by Adrymate9** [comment]
@gdregalo I followed the steps as you requested. It's all the same, unfortunately. the notification of generates but when pressing on it in the curtain of notifications never goes to Brave.

Now I will upload a small video to the corresponding thread in Brave community for you to see.

I await your comment.

**Comment by kjozwiak** [comment]
@Adrymate9 I managed to reproduce the issue with FB notifications. I created a new QA account and send a few messages and wall posts between my personal account and the new QA account and couldn't tap on the notifications. I'll work with @gdregalo tomorrow so we can finally get this fixed 👍

**Comment by Adrymate9** [comment]
@kjozwiak okay. Brave has everything I need from a browser, it only affects this detail, which for me is very important. 

I will be here waiting for news that I hope will arrive soon. If you need me to perform a test, just let me know. In what I can help to solve this problem.

I appreciate your prompt response and attention to the problems that users present.

Keep in touch regards.

**Comment by SergeyZhukovsky** [comment]
Reopening as the issue is still there.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2271

**Comment by gdregalo** [comment]
@Adrymate9, it's fixed. Thank you for your help.

**Comment by Adrymate9** [comment]
@gdregalo Speak truth?!!! What good news! How fast! Good for Brave!💪.

Now tell me if I have to update to finally have the change or what are the steps to follow.

Thank you!

**Comment by kjozwiak** [comment]
> @gdregalo Speak truth?!!! What good news! How fast! Good for Brave!💪.
> 
> Now tell me if I have to update to finally have the change or what are the steps to follow.
> 
> Thank you!

@Adrymate9 should be fixed with https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3. Please let me know if this resolves your issue 👍

**Comment by kjozwiak** [comment]
Went through the following cases with FB:

* ensured that `FB Messenger` notifications can be opened via the Brave icon
* ensured that `FB Wall` notifications can be opened via the Brave icon
* ensured that you can swipe away notifications via the Brave icon
* ensured that `FB Messenger` notifications can be opened via the notification tray
* ensured that `FB Wall` notifications can be opened via the notification tray

@gdregalo I don't think these cases are working with https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3:

* ensured that notifications from https://web-push-book.gauntface.com/demos/notification-examples/ can be opened via the Brave icon
* ensured that notifications from https://web-push-book.gauntface.com/demos/notification-examples/ can be opened via the notification tray

I tried opening the notifications that were generated via `https://web-push-book.gauntface.com/demos/notification-examples` but nothing happens like before. The FB cases have been fixed though 👍 Mind taking a look?

**Comment by kjozwiak** [comment]
Talked to @gdregalo quickly and he mentioned that only `Open a Window` notifications will work under `Notification Common Practices`.

**Comment by Adrymate9** [comment]
For now I just checked it with Facebook and it seems to work correctly. 👍.

@kjozwiak What do you mean it will work only in common practices? 

On Twitter, instagram, will Brave Community work?

**Comment by kjozwiak** [comment]
> @kjozwiak What do you mean it will work only in common practices?
> 
> On Twitter, instagram, will Brave Community work?

Should work on those as well 👍

**Comment by btlechowski** [comment]
* Verification passed on BraveModernarm v1.5.0-rc.3 on Huawei MediaPad M3 Lite 10 (Android 7.0).
Verified STR from https://github.com/brave/browser-android-tabs/issues/2138#issuecomment-551437456. On `https://web-push-book.gauntface.com/demos/notification-examples` only `OPEN WINDOW` worked, which is expected.
