### ISSUE TITLE
HTTPSE Upgrade doesn't work

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2139]
## Description 
Same as issue #2119 

## Steps to reproduce 

   1. Visit http://https-everywhere.badssl.com
   2. Doesn't auto upgrade to https://https-everywhere.badssl.com

same for clean install of 1.4.1rc3 and upgrade profiles (1.4.0 -> 1.4.1 rc3)

## Actual result 
HTTPSE doesn't work

## Expected result
Should upgrade to https where available

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.4.1 rc3 (note, 1.4.1 rc2 does not have this issue)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
reproduced by @srirambv

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.4.1-rc.3 on Huawei MediaPad M3 Lite 10

**Comment by samartnik** [comment]
Issue was on server side. It is fixed, and shoudl be working. We need to double check it for our current 1.4.0 version.
We updated url for HTTPSE in 1.4.1 version, should be checked in rc4 build, when it is available.
https://github.com/brave/browser-android-tabs/commit/0a874ca65f6becdff41889db6765fc38702bb0c0

**Comment by srirambv** [comment]
Verified working on 1.4.0. Will check again on RC4 build

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.1 RC4 x64 build
* Verified HTTPS toggle works as expected
* Verified visiting http site automatically loads https when HTTPSE is available
