### ISSUE TITLE
How to config an IDE to add some new features to this app?

### ISSUE THREAD

**Issue by tungdx** [brave/browser-android-tabs#214]
I want to add some new features by myself into this app, so I followed [the link](https://www.chromium.org/developers/android-eclipse-dev) that was described in the Debugging section in the home page and did as the guideline for Android Studio. Unfortunately, I can not build this app from Android Studio because there are an error `ZipException duplicate entries.` it is as same as [this one ](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/PgZD7z8J9_E)

I just want to ask which IDE is used to develop this app? If it's Android Studio, have you guys encountered the issue above? If it's not Android Studio, could you guys possibly tell me what is it and how to config it to develop new features into this app?

I am truly sorry if this question is stupid, but I really hope to get some help. I will appreciate it.
Thank you!

**Comment by SergeyZhukovsky** [comment]
There is no fully supported IDE currently. As you read you can configure it to debug Java sources via Eclipse or Android Studio. I tried it with Eclipse only, but I built it via command line, I just attached to the process on Eclipse and could debug and etc only Java files.

**Comment by tungdx** [comment]
Hi @SergeyZhukovsky You mean you run this command `ninja -C out/Default chrome_public_apk` to build it after adding new features by Eclipse, right?

**Comment by SergeyZhukovsky** [comment]
@tungdx yep, that's correct.

**Comment by tungdx** [comment]
Thanks @SergeyZhukovsky
