### ISSUE TITLE
Implement Bat Points 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2144]
## Description 

Please search G-Drive for "BAT Points (Simple version)" for a Spec

Link in with @kylehickinson on how iOS will implement this too. 

Thanks

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravemodernarm 1.5.0`
- Logged #2235, #2236 and #2238
