### ISSUE TITLE
Change onboarding Rewards slide button title

### ISSUE THREAD

**Issue by karenkliu** [brave/browser-android-tabs#2145]
## Description

Currently, the Rewards slide in onboarding shows "Join" as the button text:

![android 3](https://user-images.githubusercontent.com/2388823/66680506-90df2900-ec25-11e9-9d36-f97ae4fa99bb.png)

Update the button text to "Switch On" so it looks like this:

![android 3](https://user-images.githubusercontent.com/2388823/66681101-d5b78f80-ec26-11e9-935c-52819424bf95.png)

**Comment by anthonypkeane** [comment]
Update: Use **Turn On**
not
_Switch On_

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

![Screenshot_20191105-041713](https://user-images.githubusercontent.com/2602313/68194872-ca385980-ff83-11e9-8056-11ab1e979bf0.png)

**Comment by kjozwiak** [comment]
> Update: Use **Turn On**
> not
> _Switch On_

@anthonypkeane just double checking, it should be **`TURN ON`** and NOT **`SWITCH ON`** correct?

**Comment by anthonypkeane** [comment]
> @anthonypkeane just double checking, it should be **`TURN ON`** and NOT **`SWITCH ON`** correct?

**`TURN ON`** is correct
