### ISSUE TITLE
Ads & Trackers Blocked text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2149]
## Description 

Update 
Ads and Trackers Blocked
to
Ads & Trackers Blocked

**Comment by anthonypkeane** [comment]
Android:
**Stats**
Font: Roboto Medium 32pt
Ads & Trackers: #FB542B
HTPPS Upgrades: #A0A5EB
Time Saved: #1E2029 / #FFFFFF
**Titles**
Font: Roboto Medium 10pt
Color: #8C9094

![Screen Shot 2019-10-14 at 4 08 17 PM](https://user-images.githubusercontent.com/7606853/66784649-f1719e80-ee8f-11e9-9d69-c4aeb3a8f95e.png)

cc @jamesmudgett

**Comment by deeppandya** [comment]
@jamesmudgett @anthonypkeane we should avoid using the text size less than 12pt in android.

**Comment by jamesmudgett** [comment]
@deeppandya the design above is on a screen size 360x640, 10px label should be ok, if we go larger we'll likely create line break issues in other languages.

**Comment by deeppandya** [comment]
@anthonypkeane this issues in conflict with https://github.com/brave/browser-android-tabs/issues/2094 for the **HTTPS upgrades** counter

**Comment by deeppandya** [comment]
> @deeppandya the design above is on a screen size 360x640, 10px label should be ok, if we go larger we'll likely create line break issues in other languages.

@jamesmudgett in android, it's recommended to use use text size at least of 12 px. it even gives a warning saying the same thing. And should we still keep 32px for counter text ? it would look too big for smaller devices.

**Comment by deeppandya** [comment]
@jamesmudgett i am keeping the same text size for counter and title.and updating Text color for **HTTPS Upgrades** based on this issue.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

![Screenshot_20191105-041158](https://user-images.githubusercontent.com/2602313/68194182-93157880-ff82-11e9-980f-9a895564ed43.png)
