### ISSUE TITLE
Remove Rewards ToS checkbox slide in onboarding

### ISSUE THREAD

**Issue by karenkliu** [brave/browser-android-tabs#2152]
## Description 
Currently, there is an additional step in the onboarding flow to check the Rewards Terms of Service checkbox:

![android 3 - terms 1](https://user-images.githubusercontent.com/2388823/66868481-3a8a2700-ef52-11e9-88b2-4435baf39cf9.png)

Remove the checkbox slide and add "By turning on Rewards, you agree to the Terms of Service." to the Rewards slide.

## Design
![android 3](https://user-images.githubusercontent.com/2388823/66868838-f6e3ed00-ef52-11e9-9079-705289cb6fbf.png)

### New user, In ad region
Show search engine selection, Brave Shields explanation, Brave Rewards, and ad onboarding.

![user flow - android onboarding ads available](https://user-images.githubusercontent.com/2388823/66868753-c9973f00-ef52-11e9-8a4a-202f9b4808e3.png)

### New user, Out of ad region
Show search engine selection, Brave Shields explanation, and Brave Rewards.

![user flow - android onboarding ads unavailable](https://user-images.githubusercontent.com/2388823/66868868-082cf980-ef53-11e9-923b-ac3dbfdf34f9.png)

![ads unavailable](https://user-images.githubusercontent.com/2388823/66870545-8c34b080-ef56-11e9-8a65-344ad8f55f4c.png)

### Existing user, Brave Rewards OFF
Show Brave Rewards and ad onboarding.

![user flow - android onboarding BR off, in ad region](https://user-images.githubusercontent.com/2388823/66869960-5216df00-ef55-11e9-941e-b31e32acf4b9.png)

### Existing user, Brave Rewards ON
Refer to https://github.com/brave/browser-android-tabs/issues/2153

**Comment by deeppandya** [comment]
@karenkliu @anthonypkeane we have statuc heights for the bottom white layout. if we add one more text we would have to remove static heights for the layout otherwise it would get cut off in smaller devices.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravemodernarm 1.5.0.rc1`
  Rewards slide update in Onboarding flow:
![Screenshot_2019-11-05-03-34-14](https://user-images.githubusercontent.com/38657976/68201721-53817780-ffe8-11e9-9cc3-03aec6b5adc3.png)
Rewards  slide update in the welcome tour
![Screenshot_2019-11-05-03-47-15](https://user-images.githubusercontent.com/38657976/68201786-7318a000-ffe8-11e9-83c6-84a381c845cf.png)
