### ISSUE TITLE
Turn on Ads by for all existing BR users

### ISSUE THREAD

**Issue by karenkliu** [brave/browser-android-tabs#2153]
## Description
Currently, when ads become available for existing BR users, we ask them to "Turn On" ads:

![android br on 1](https://user-images.githubusercontent.com/2388823/66872219-4d085e80-ef5a-11e9-84b4-fcf292a4a3ed.png)

![user flow - android onboarding BR on](https://user-images.githubusercontent.com/2388823/66872220-4d085e80-ef5a-11e9-8fec-c7e0ffff08f1.png)

Turn on ads by default for all existing users who have opted into Brave Rewards.

## Designs
Show ad onboarding for users who satisfy this criteria:

- Existing users who have opted into Brave Rewards
- They did not opt into Ads previously, and they are in a region where ads are available
- They previously were in a region where ads weren't available, and ads have just become available

![user flow - android onboarding BR on ads](https://user-images.githubusercontent.com/2388823/66877697-5948e780-ef6b-11e9-8fd6-a081ecde900e.png)

![android br on 1](https://user-images.githubusercontent.com/2388823/66877692-50581600-ef6b-11e9-84a3-cc240b43f9c3.png)

**Comment by anthonypkeane** [comment]
Putting this in the icebox for the moment

**Comment by anthonypkeane** [comment]
Ads are driven by the server and the client needs to know when regions are enabled. So we can't do this right now

**Comment by anthonypkeane** [comment]
@karenkliu I think we have this covered with existing onboarding, pls LMK if not.
