### ISSUE TITLE
Hide Rewards Icon in Private Mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2156]
## Description 
Please hide the Rewards icon when in private mode

**Comment by kjozwiak** [comment]
Downloaded https://github.com/brave/browser-android-tabs/releases/tag/v1.4.3-rc.4 and reproduced the original re: `Rewards` icon being visible (even though disabled) in PB mode.

Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

* ensured that the `Rewards` icon isn't visible under PB mode.
