### ISSUE TITLE
 `Desktop Mode` option missing in Setting->Site settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2164]
## Description 
 `Desktop Mode` option missing in Setting->Site settings

## Steps to reproduce 

   1. Clean OR upgraded profile 1.4.3 Chromium 78.0.3904.62
   2. Navigate to Settings->Site settings
   3. The desktop mode option is missing

## Actual result 

The desktop mode option is missing
![image](https://user-images.githubusercontent.com/38657976/67272547-653c2880-f4da-11e9-9b5f-c5cc346fe6ca.png)

## Expected result
 `Desktop Mode` option should be available

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy j3
   - Android version: 5.1.1
   
## Brave version

Brave 1.4.3 Chromium 78.0.3904.62

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? No. The desktop mode option is not available in the site settings

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
`Add to Home screen` option is also missing from the Hamburger menu

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/b2e83d4d2ff5d4b8eca3ae97f73ee7532b71c5b1

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.3 RC1 x64 build
* Verified on clean install desktop mode option is visible
* Verified on upgrade desktop mode option is visible
