### ISSUE TITLE
`Light` theme is NOT selected by default

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2165]
## Description 
`Light` theme is NOT selected by default

## Steps to reproduce 

   1. Clean OR upgraded profile 1.4.3 Chromium 78.0.3904.62
   2. Navigate to Settings->Appearance
   3. Click on `Theme`
   4. Light theme is NOT selected by default

## Actual result 
Light theme is NOT selected by default
![image](https://user-images.githubusercontent.com/38657976/67274750-b8b07580-f4de-11e9-8b56-4fe711c0fbf6.png)

## Expected result
The light theme should be selected by default

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy j3
   - Android version: 5.1.1
   
## Brave version

Brave 1.4.3 Chromium 78.0.3904.62
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? Not sure

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/6c6a05b5e82ab83d25bcf29f682754bba26a4f4b

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.3 RC1 x64 build
* Verified on clean install light theme is selected by default
* Verified on upgrade light theme is selected by default
* Verified changing theme to dark on GPS version and upgrade to 1.4.3 has the dark option selected by default
* Verified changing theme to dark and back to light on GPS version and upgrade to 1.4.3 still have the light theme selected by default
