### ISSUE TITLE
Internal Issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2170]
## Description 
Link: https://github.com/brave/internal/issues/667

**Comment by fmarier** [comment]
As a minimal fix for this, let's just add a new "Brave License" item to this menu:
![Screenshot_20191029-111853](https://user-images.githubusercontent.com/167821/67797151-8bb01580-fa3e-11e9-84b0-3403cb3c6c8d.png)

which includes a **bundled** copy (NOT linking to the web) of the [MPL](https://www.mozilla.org/en-US/MPL/2.0/).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

![Screenshot_20191105-031545](https://user-images.githubusercontent.com/2602313/68190081-c3591900-ff7a-11e9-9581-1dbf4fce11d6.png)

![Screenshot_20191105-031608](https://user-images.githubusercontent.com/2602313/68190080-c3591900-ff7a-11e9-95d7-24b5e3818f38.png)
