### ISSUE TITLE
3rd Party cookies are not set when the setting is disabled in shields 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2173]
## Description 
3rd Party cookies are not set when the setting is disabled in shields 

## Steps to reproduce 

   1. Visit https://jsfiddle.net/7ke9r14a/7/ 
   2. Disable 3rd Party cookies from shields
   3. Cookie is not set

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/67426114-69824780-f5a7-11e9-837c-8112dd3146b1.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/67426126-6dae6500-f5a7-11e9-9e30-5f46dc33d547.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T 
   - Android version: 9.0
   
## Brave version
1.4.1 RC1 x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

The issue happens on both upgrade and clean install

**Comment by LaurenWags** [comment]
Reproduced with Asus Zenfone (x86) with Android 6.0 running 1.4.3rc1 BraveModernx86.apk

**Comment by kjozwiak** [comment]
Reproduced using `Pixel XL 2` running `Android 10` with the following build:

* https://github.com/brave/browser-android-tabs/releases/tag/v1.4.3-rc.1

Also checked the following STR:

* launched `Brave 1.4.3 CR: 78.0.3904.62`
* load https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled

You'll notice that the website will mention that `3rd Party Cookies` are enabled even though `Block 3rd party cookies` is enabled via Brave Shields.

**Comment by srirambv** [comment]
Fixed by  #2179

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarn 1.4.3-rc.2
