### ISSUE TITLE
Implement NTP Images

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2176]
## Description 
Please implement the NTP image

Search GDocs for the Spec

**Comment by anthonypkeane** [comment]
https://github.com/brave/brave-browser/issues/6904 for images

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2322

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk` 1.6.0-rc1
   - Verified sponsored NTP image isn't shown when the app is launched 1st time with a clean install
   - Verified sponsored NTP image is shown at 2nd, 4th, 8th,12th, 16th NTP when the app is re-launched 2nd time
  - Encountered #2332 
  - Verified sponsored NTP image is shown at 4th, 8th,12th,16th NTP (after every 4 NTP's) when the app is re-launched 3rd time, 4th, 5th, 6th and so on
