### ISSUE TITLE
Enable new ads regions

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2177]
## Description 
Please enable the new ads onboarding for new regions 

--and order localizations if needed

**Comment by deeppandya** [comment]
@anthonypkeane i have added regions to the android code for 1.4.3 release. for this issue, i need to wait for the changes in the core side as @tmancey suggested.

**Comment by anthonypkeane** [comment]
Moving back to 1.4.3 following a chat with @jsecretan

**Comment by srirambv** [comment]
Fixed with #2200
