### ISSUE TITLE
Verified check icon is NOT displayed in AC table and Tips panel for verified pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2178]
## Description 
Verified check icon is NOT displayed in AC table and Tips panel for verified pubs (YT/Sites/Twitch)

## Steps to reproduce 

   1. Clean or Upgraded profile 1.4.3
   2. Enable rewards
   3. Add a verified pubs to AC table
   4. Send a monthly tip and one-time tip to verified pubs

## Actual result 
Verified check icon is NOT displayed in AC table and Tips panel for verified pubs

![Screenshot_2019-10-25-18-13-51](https://user-images.githubusercontent.com/38657976/67490712-49c74e00-f691-11e9-91f6-e61aec970b65.png)

![Screenshot_2019-10-25-18-15-37](https://user-images.githubusercontent.com/38657976/67490723-4f249880-f691-11e9-9a4f-537f5206b735.png)

## Expected result
Verified check icon should be displayed in AC table and Tips panel for verified pubs

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 5.1.1
   
## Brave version

Brave 1.4.3
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by srirambv** [comment]
Issue regressed in 1.4.1. Worked fine on 1.4.0

**Comment by srirambv** [comment]
Looks like iOS also regressed https://github.com/brave/brave-ios/issues/1783

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarn 1.4.3-rc.2
