### ISSUE TITLE
Page doesn't load web view crash for `hrf.org` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2181]
## Description 

Page doesn't load web view crash for `hrf.org` 
## Steps to reproduce 

   1. Clean profile 1.4.2
   2. Open `hrf.org` in a new tab
   3. Page doesn't load web view crash
   4. Click Reload doesn't help

## Actual result 
Page doesn't load web view crash for `hrf.org` 
![Screenshot_2019-10-25-13-03-15](https://user-images.githubusercontent.com/38657976/67553058-f7863b80-f729-11e9-8a01-37a8fccf0b37.png)

## Expected result

The page should load without any webview crash
## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.4.2
### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

 cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane 

The issue is reported by the community user
https://community.brave.com/t/page-loads-on-chrome-but-not-on-brave/89143

**Comment by srirambv** [comment]
Looks fixed on 1.4.3 RC2 x64 build. Verified on OnePlust 6T with Android 9.0 running 1.4.3 RC2 X64 build. Page loads fine and doesn't cause webview crash.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.4.3rc2 BraveModernx86.apk - no webview crash, page loads as expected
