### ISSUE TITLE
Ignore unhandled notifications

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2197]
## Description 
1. Ignore unhandled notifications. 
At the moment unexpected notification shows empty UI with "Claim" button. After user presses it, claim requests with wrong `promotion_id` is sent to Brave backend server.

The new types of notifications were added in brave-core but they are still not handled on Android side.
https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/rewards_notification_service.h#L39 

REWARDS_NOTIFICATION_TIPS_PROCESSED,
REWARDS_NOTIFICATION_ADS_ONBOARDING,
REWARDS_NOTIFICATION_VERIFIED_PUBLISHER,
REWARDS_NOTIFICATION_PENDING_NOT_ENOUGH_FUNDS,
REWARDS_NOTIFICATION_GENERAL_LEDGER

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment]
Is this a fix for this issue? https://community.brave.com/t/the-gift-is-coming-but-error-is-coming/90150?u=eljuno

I've seen many similar issue reported about this. Happens on my sister's phone too.

**Comment by gdregalo** [comment]
@eljuno Yes, this fixes the problem. We are working on handling the new notifications properly.

**Comment by GeetaSarvadnya** [comment]
@gdregalo Can you provide the test plan, please?

**Comment by btlechowski** [comment]
Setting to `QA/Blocked` based on above comment.

**Comment by kjozwiak** [comment]
Labeling as `QA/No` after talking to @SergeyZhukovsky. There's really no solid STR that QA can use here. I accepted several grants on both `staging` and `production` and never ran into the original issue.
