### ISSUE TITLE
Tipping panel needs to have same title as desktop

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2199]
## Description 
Tipping panel needs to have same title as desktop

## Steps to reproduce 

   1. Enable rewards
   2. Visit any site in a new tab and open tips panel
   3. Tip panel has the title `Thanks for stopping by!`

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/67712042-96fd3580-f999-11e9-9ac9-984b4a9e3aa0.png)

## Expected result
Use `Welcome!` similar to desktop and iOS

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Not a blocker or high priority for 1.5.0. If android-core gets these translations from desktop code then we could wait until android-core 
cc: @anthonypkeane

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using  `1.5.0 CR: 78.0.3904.90` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0:

![Screenshot_20191105-034821](https://user-images.githubusercontent.com/2602313/68192404-43817d80-ff7f-11e9-8a62-524dd59e8a38.png)

![Screenshot_20191105-034726](https://user-images.githubusercontent.com/2602313/68192405-43817d80-ff7f-11e9-863b-ae38899fdabd.png)
