### ISSUE TITLE
Keyboard doesn't auto hide when menu is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#22]
Tap on URL to activate the keyboard. Once keyboard is shown open menu and tap on Settings. Tapping on settings menu doesn't automatically hide the Keyboard. There is a significant lag in hiding the keyboard. On Chrome it auto hides keyboard the moment the menu is opened.

**Comment by anthonypkeane** [comment]
is this still an issue @srirambv 
If not, please close the issue. If Yes, please add it to milestone 1.0.94
Thank you

**Comment by srirambv** [comment]
Seems fixed on 1.0.93. Closing for now
