### ISSUE TITLE
 Verified publisher icon not shown on tips panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2201]
## Description 
Verified publisher icon not shown on tips panel

## Steps to reproduce 

   1. Enable rewards 
   2. Visit a verified site
   3. Open tipping panel, no verified checkmark for the publisher

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/67714405-38868600-f99e-11e9-862d-c53e79d50320.png)

## Expected result
Similar to desktop should have the verified checkmark on tips panel as well
![image](https://user-images.githubusercontent.com/17010094/67708386-741b5300-f992-11e9-84bf-5a84a603890b.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
Playstore build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jamesmudgett** [comment]
We also need verified check icon on address bar as seen here.
![image-(2)](https://user-images.githubusercontent.com/318119/67790268-7be70000-fa43-11e9-82f7-f92b7dae2998.png)

**Comment by jamesmudgett** [comment]
[verified icons.zip](https://github.com/brave/browser-android-tabs/files/3784888/verified.icons.zip)

**Comment by deeppandya** [comment]
Updating changes in BAT icon in toolbar in https://github.com/brave/browser-android-tabs/issues/1708. in this issues, i updated the verified icon in tipping page.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2249

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
![Screenshot_2019-11-07-16-44-02](https://user-images.githubusercontent.com/38657976/68384763-57df9900-017e-11ea-9b24-e69aa149863e.png)
![Screenshot_2019-11-07-16-44-30](https://user-images.githubusercontent.com/38657976/68384765-57df9900-017e-11ea-82f2-0b1f5b8c77ef.png)
![Screenshot_2019-11-07-16-45-15](https://user-images.githubusercontent.com/38657976/68384766-58782f80-017e-11ea-9a66-ba89ebdf74b6.png)
![Screenshot_2019-11-07-16-46-28](https://user-images.githubusercontent.com/38657976/68384767-58782f80-017e-11ea-9489-7017ed9d4645.png)
