### ISSUE TITLE
Keyboard not closed when navigating back from sync screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#221]
Keyboard is not closed when navigate back from Enter secret code screen. Keyboard remains on screen until the settings menu is closed.

**Comment by SergeyZhukovsky** [comment]
That is fixed in the latest alpha version.

**Comment by srirambv** [comment]
I still see this on the latest alpha.

**Comment by SergeyZhukovsky** [comment]
@sriram what do you do exactly? Click back button when you are on Enter words screen? That removes a keyboard to me on a first click and goes back on second click. Or you enter all words and it remains there after successful sync?

**Comment by srirambv** [comment]
@SergeyZhukovsky  here is the recording of what happens. 
https://www.dropbox.com/s/8mvjlqtmbxro2zg/221.mp4?dl=0

**Comment by SergeyZhukovsky** [comment]
Thanks for the video @srirambv. I managed to reproduce it.

**Comment by SergeyZhukovsky** [comment]
That is fixed in the latest beta

**Comment by srirambv** [comment]
Verified on latest beta. CLosing #221
