### ISSUE TITLE
BAT Points change

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2211]
## Description 
The updated requirement for BAT Points is:

- Anywhere we have "BAT", change it to "BAP"
   (This requires change the previous logic where in some cases we changed BAT to BAT Points.) 

- Anywhere we have "Tokens", change for "Points"

NOTE: This is for JAPAN region only 

Desktop Issue: https://github.com/brave/brave-browser/issues/6654

**Comment by anthonypkeane** [comment]
@ryanml @petemill can you one you please help with the BAT Points change on the settings pages on Android?

@deeppandya has the native work completed, but we need help on the react pages.

Thanks


![Screenshot_20191030-162317](https://user-images.githubusercontent.com/7606853/67906544-2dfcf580-fb32-11e9-94b1-def91d6f1105.jpg)
![Screenshot_20191030-162325](https://user-images.githubusercontent.com/7606853/67906545-2e958c00-fb32-11e9-8be3-6d6d948f5024.jpg)
![Screenshot_20191030-162335](https://user-images.githubusercontent.com/7606853/67906546-2e958c00-fb32-11e9-81fd-c08f452b23e6.jpg)
![Screenshot_20191030-162403](https://user-images.githubusercontent.com/7606853/67906547-2e958c00-fb32-11e9-9449-ccb3d3cdd336.jpg)
![Screenshot_20191030-162412](https://user-images.githubusercontent.com/7606853/67906548-2e958c00-fb32-11e9-8bcc-887089ebb88a.jpg)
![Screenshot_20191030-162426](https://user-images.githubusercontent.com/7606853/67906549-2e958c00-fb32-11e9-9415-29ad063400d8.jpg)
![Screenshot_20191030-162435](https://user-images.githubusercontent.com/7606853/67906550-2e958c00-fb32-11e9-851f-1229577693ec.jpg)
![Screenshot_20191030-162447](https://user-images.githubusercontent.com/7606853/67906551-2f2e2280-fb32-11e9-878b-022063acd758.jpg)

**Comment by deeppandya** [comment]
Need to reopen it as we are still missing react changes.

**Comment by SergeyZhukovsky** [comment]
Addressed in the current PR https://github.com/brave/browser-android-tabs/pull/2226

**Comment by GeetaSarvadnya** [comment]
This issue needs to retested when https://github.com/brave/browser-android-tabs/issues/2266 and https://github.com/brave/browser-android-tabs/issues/2262 are fixed.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3.

Created both https://github.com/brave/browser-android-tabs/issues/2272 & https://github.com/brave/browser-android-tabs/issues/2274 which will most likely be addressed in `1.5.1` which will include the `78.0.3904.96`.
