### ISSUE TITLE
Rewards Don't Work with Youtube Mobile Website

### ISSUE THREAD

**Issue by RossClelland** [brave/browser-android-tabs#2216]
## Description 
When visiting a verified publishers YouTube channel on the desktop I'm able to donate BAT. However, when visiting the same page using the mobile web version (m.youtube.com) they are not recognised as being verified.

The obvious workaround would be to use the "Desktop Site" option to request the desktop version however this still directs me to the mobile web version of YouTube (m.youtube.com). So, there's no workaround. 

(The fact that the Desktop Site option doesn't work may be a separate issue because when I use a Private tab and use the same option I'm redirected to the youtube.com site as expected. This isn't a workaround to the original issue because I can't donate in private tabs).

## Steps to reproduce 

   1. Visit a verified publishers m.youtube.com channel
   2. 
   3. 

## Actual result 
Channel isn't recognised as being verified 

## Expected result
Channel should be verified 

## Issue reproduces how often 
Every visit 

## Issue happens on 
   - Current Play Store version - latest
   - Beta build - no

## Device details
   - Install type (ARM, x86): don't know 
   - Device (Phone, Tablet, Phablet): s10
   - Android version: 9
   
## Brave version
Latest from android store

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Seems to work just fine. 
![image](https://user-images.githubusercontent.com/17010094/68681675-ce3f1b00-0531-11ea-8d3c-0452704625b5.png)

Could you may be add the publisher details in the issue so its easy to check?

**Comment by RossClelland** [comment]
Hello,

Yeah, should have thought about that! Here's the desktop version and mobile version. 
![20191113_183249](https://user-images.githubusercontent.com/34719071/68792904-34b45e00-0644-11ea-936a-f7811c149a27.jpg)
![Screenshot_20191113-183304_Brave](https://user-images.githubusercontent.com/34719071/68792929-3e3dc600-0644-11ea-81e7-5303bacdbb28.jpg)

I tried the channel in your screenshot and it works. So, doesn't seem to be a universal issue?

**Comment by RossClelland** [comment]
Fixed in latest build
