### ISSUE TITLE
After upgrading to 1.5.0 RC1 Rewards icon still in toolbar even if setting is to have it off

### ISSUE THREAD

**Issue by joejoejo** [brave/browser-android-tabs#2227]
Steps to reproduce:
   1. Update to 1.5.0 RC1

Actual result
Shows the rewards icon in toolbar even if the setting to hide rewards icon is on
![Screenshot_20191103-162416](https://user-images.githubusercontent.com/5640119/68092293-96f8ac00-fe57-11e9-9a5c-59c71b3b07a4.png)

Expected result
To not have the rewards icon in toolbar if setting is to have rewords icon hidden

Issue reproduces how often
It's always there on brave 1.5.0 RC1

Issue happens on
Not play store version
Brave 1.5.0 RC1

Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Pixel 3a XL
   - Android version: 10

**Comment by deeppandya** [comment]
@joejoejo thanks for noticing this. I will verify it.

**Comment by kjozwiak** [comment]
Reproduced this on my `Pixel 2 XL` with `Android 10` using `1.5.0 CR: 78.0.3904.90`. Couldn't reproduce using `1.4.3 CR: 78.0.3904.62`. Good catch @joejoejo 👍

**Comment by deeppandya** [comment]
@kjozwiak @joejoejo it's been fixed and would reflect this change in next RC.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2243

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
 - Verified on both clean and upgraded profiles
