### ISSUE TITLE
Follow up to #2152 - Some strings are not translated in onboarding flow

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2233]
Follow up to https://github.com/brave/browser-android-tabs/issues/2152. Some rewards strings are not translated in onboarding process and welcome tour

## Steps to reproduce 
   
   1. Change language to Polish (Polski)
   2. Clean install
   3. Go through onboarding process till rewards

 Another test case:
   1. Change language to Polish (Polski)
   2. Clean install
   3. Skip onboarding process
   4. Go to settings
   5. Open the welcome tour

## Actual result 
Some strings are not translated
Note: Languguage used in the screenshots: Polish(Polski)
onboarding process:
![Screenshot_20191105-142432](https://user-images.githubusercontent.com/34715963/68211978-eb776500-ffd8-11e9-9cea-f3df0ef904b9.png)
welcome tour:
![Screenshot_20191105-142925](https://user-images.githubusercontent.com/34715963/68212750-79078480-ffda-11e9-9e61-2bae9cab1b27.png)

## Expected result
All strings are translated

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet):Tablet
   - Android version: 7.0
   
## Brave version
BraveModernarm v1.5.0-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0).

cc @brave/legacy_qa @anthonypkeane @deeppandya

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/bf5bb06f337de22980d4feffae6878509a2ef989

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
![image](https://user-images.githubusercontent.com/38657976/68372262-8487b680-0166-11ea-9347-57266d80c172.png)
