### ISSUE TITLE
Follow up to #2149 - Ads & Trackers Blocked is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2234]
Follow up to #2149. `Ads & Trackers Blocked` is not translated

## Steps to reproduce 

   1. Change language to Polish (Polski)
   2. Open Brave
   3. Open NTP

## Actual result 
`Ads & Trackers Blocked` is not translated
![Screenshot_20191105-141939](https://user-images.githubusercontent.com/34715963/68211239-7a837d80-ffd7-11e9-9a03-dd76e7332f65.png)

## Expected result
`Ads & Trackers Blocked` is translated

## Device details
   - Install type (ARM, x86):Arm
   - Device (Phone, Tablet, Phablet):Tablet
   - Android version: 7.0
   
## Brave version
BraveModernarm v1.5.0-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0).

cc @brave/legacy_qa @anthonypkeane @deeppandya

**Comment by samartnik** [comment]
This build doesn't contain all the translations. We will need to recheck with rc2, where translations will be added.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/bf5bb06f337de22980d4feffae6878509a2ef989

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
![image](https://user-images.githubusercontent.com/38657976/68372440-dcbeb880-0166-11ea-97d2-4137b9227308.png)
