### ISSUE TITLE
BAT POINTS- `Your Balance` in Japanese locale is overlapping on wallet balance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2235]
## Description 
Found while testing https://github.com/brave/browser-android-tabs/issues/2144
`Your Balance` in Japanese locale is overlapping on wallet balance

## Steps to reproduce 

   1. Set device locale to Japan
   2. Clean profile 1.5.0
   3. Enable rewards
   4. `Your Balance` in Japanese locale is overlapping on wallet balance

## Actual result 
`Your Balance` in Japanese locale is overlapping on wallet balance
![image](https://user-images.githubusercontent.com/38657976/68214518-9e5cb880-0003-11ea-998c-36c71c4fe529.png)

## Expected result

`Your Balance` in Japanese locale should not be overlapping on wallet balance
## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
5.1.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @mattmcalister @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2256

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
![Screenshot_2019-11-07-17-10-57](https://user-images.githubusercontent.com/38657976/68386427-fc170f00-0181-11ea-93f0-cacdbd6c5f50.png)
![Screenshot_2019-11-07-17-11-19](https://user-images.githubusercontent.com/38657976/68386430-fc170f00-0181-11ea-9853-f4312362d122.png)
![Screenshot_2019-11-07-17-11-28](https://user-images.githubusercontent.com/38657976/68386431-fcafa580-0181-11ea-95e5-c56ad342ba16.png)
