### ISSUE TITLE
BAT POINTS is not displayed in wallet balance in the rewards settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2236]
## Description 
Found while testing #2144
BAT POINTS is not displayed in wallet balance in the rewards settings page
## Steps to reproduce 

   1. Set device locale to Japan
   2. Clean profile 1.5.0
   3. Enable rewards
   4. Navigate to the rewards settings page
   5. BAT POINTS is not displayed in wallet balance in the rewards settings page
  
## Actual result 
1. BAT POINTS is not displayed in wallet balance in the rewards settings page
![image](https://user-images.githubusercontent.com/38657976/68238501-55225e00-002f-11ea-81f3-4c4457d9f0fc.png)
2. Rewards- Auto Contribution pnel
![image](https://user-images.githubusercontent.com/38657976/68239046-5011de80-0030-11ea-8482-3e6f417fd9b9.png)
3. Monthly payment drop down values in rewards auto contribute panel
![image](https://user-images.githubusercontent.com/38657976/68239235-9ebf7880-0030-11ea-8fbc-7caed9b95cc8.png)
4. Advanced settings in rewards auto contribute panel
![image](https://user-images.githubusercontent.com/38657976/68239362-d6c6bb80-0030-11ea-8098-2c057e312536.png)

## Expected result
BAT POINTS should be displayed in wallet balance in the rewards settings page

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

5.1.0
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @mattmcalister @anthonypkeane @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2250

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
