### ISSUE TITLE
BAT icon is visible on x86 builds

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2237]
It should not be visible as it is not supported on x86 devices.

**Comment by LaurenWags** [comment]
Reproduces on my x86 device - Asus Zenfone running Android 6.0

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2243

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.0rc2 BraveModernx86.apk
* Confirmed BAT icon is not visible on upgrade (1.4.3 --> 1.5.0rc2)
* Confirmed BAT icon is not visible on clean install of 1.5.0rc2
