### ISSUE TITLE
BAT POINTS- Translation is missing for Japanese locale

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2238]
## Description 
Found while testing #2144
BAT POINTS- Translation is missing for Japanese locale
## Steps to reproduce 

   1. Set device locale to Japanese
   2. Clean install 1.5.0
   3. launch brave and enable rewards
   4. Navigate to the rewards settings page and open Tips panel
   5. The translation is missing for Tips content creators description
   6. Click on BAT logo and open rewards panel
   7. Translation is missing for `Your balance` label

## Actual result 
Translation is missing for Japanese locale

1. Tips panel content

![image](https://user-images.githubusercontent.com/38657976/68217295-5f7d3180-0008-11ea-9816-efa33adf9756.png)

2. Your balance in BR panel

![image](https://user-images.githubusercontent.com/38657976/68217339-715ed480-0008-11ea-81b4-e5d8a124950c.png)

## Expected result
Texts should be translated to japanese

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.5.0
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @mattmcalister @anthonypkeane @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Fixed in the context of that commit https://github.com/brave/brave-core/commit/f286e7c8b46b53271f87942f96c6e895003e5b09

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
![image](https://user-images.githubusercontent.com/38657976/68399437-650b8080-019c-11ea-9ccb-fdafbf559ede.png)
![image](https://user-images.githubusercontent.com/38657976/68399472-75236000-019c-11ea-922f-09d71ba44af5.png)
