### ISSUE TITLE
BAT POINTS- Tip amount is not changed to BAP in tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2239]
## Description 
Tip amount is not changed to BAP in tips panel

## Steps to reproduce 

   1. Set device locale to Japanese
   2. Clean profile 1.5.0
   3. Enable rewards and fund the wallet
   4. Send a monthly tip and one time tips to verified or non-verified pubs

## Actual result 

**Tips panel** -Tip amount is not changed to BAP 
![image](https://user-images.githubusercontent.com/38657976/68221283-37dd9780-000f-11ea-9508-312342b26e8c.png)

## Expected result
As mentioned in the Mobile Spec, Change Tip amounts from “BAT” to “BAP” (point 3 in mobile section)
Tip amount should be changed to BAP in tips panel
## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version:5.1.1
   
## Brave version
1.5.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @mattmcalister @anthonypkeane

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2250

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running BraveModernarm.apk 1.5.0-rc2
