### ISSUE TITLE
Phaser HTML5 game not registering touch / halting on touch

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-android-tabs#224]
I recently created a HTML5 game, using the popular Phaser HTML5 game framework (https://phaser.io/).

When testing I noticed that the touch events do not seem to trigger correctly in Brave for Android and seem to cause the game to halt, suggesting a JavaScript error has occurred. Unfortunately, I am unsure of how to debug further without developer tools available.

The issue occurs on 

* Android Brave version 1.0.19, on Android 7.1.2 (Nexus 6P).

The issue does not occur on:

* Android Google Chrome version 57.0.2987.132.
* Android Firefox version 53
* Desktop Brave version 0.15.0 rev 8e63cc0.

To recreate this issue:

1. Open the Android version of Brave.
2. Visit https://divineomega.github.io/ludum-dare-38/
3. Note the main character animating correctly (pulsing in and out).
4. Press anywhere on the game canvas as instructed.
5. Note that the game halts, as evident by the main character no longer animating and the game not advancing the next screen.

Toggling Brave shields seems to have no effect.

I'd like to help fix this issue. Is it possible to remotely attach Brave developers tools to the Android Brave browser at all?

**Comment by SergeyZhukovsky** [comment]
Yep it is possible, you need Chrome on your desktop/laptop PC and follow the instructions: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
What I see it cannot decode some audio. Probably Brave doesn't have that codec.

**Comment by DivineOmega** [comment]
Just remote debugged this.

You're right that Brave doesn't seem to be able to decode the audio, I assume because it lacks MP3 support.

The reason it halts on touch is simply because my code is attempt to directly access the audio object in order to modify it's pitch ('playbackRate'). Since Brave failed to load the MP3, this audio object is null, and I haven't put a check in place for that.

So, although it seemed like a issue with touch events not registering, it appeared to be completely unrelated.

**Comment by DivineOmega** [comment]
I've applied simple fix to gracefully degrade if the browser does not support MP3 decoding.

https://github.com/DivineOmega/ludum-dare-38/commit/ae0e111a35b7e191082f612b4ace0d0b6f7fd8fa

Thanks for your help regarding remote debugging. I incorrectly assumed this wouldn't be compatible with Brave.

I'll close this issue.
