### ISSUE TITLE
Restart browser is causing the brave crash after enabling rewards through onboarding modal

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2240]
## Description 
Restart browser is causing the brave crash after enabling rewards through onboarding modal

## Steps to reproduce 

   1. Clean profile 1.5.0
   2. Enable rewards through the onboarding flow
   3. After enabling rewards, click on `Start browsing`
   4. Exit the browser from the hamburger menu
   5. Restart the browser
   6. Brave crashed
   

## Actual result 
Restart browser is causing the brave crash after enabling rewards through onboarding modal

Crash Logs:
[Brave crash logs_Android 5.1.1.txt](https://github.com/brave/browser-android-tabs/files/3810653/Brave.crash.logs_Android.5.1.1.txt)

## Expected result
Should not be any crash

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @anthonypkeane @deeppandya @SergeyZhukovsky 

Please note issue is reproducible only in Android lower versions.

The issue isn't reproducible in Android 9.1 confirmed by @srirambv

**Comment by kjozwiak** [comment]
Possibly related to older devices/versions of android? Tried on the following devices and couldn't reproduce:

* `Pixel 2 XL` running `Android 10` - Couldn't reproduce
* `Samsung Galaxy S10+` running `Android 9` - Couldn't reproduce

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2247

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy j3 version 5.1.1 running `BraveModernarm.apk` 1.5.0-rc2
