### ISSUE TITLE
Brave Rewards are disabled even when there is network error on SafetyNet check. Needs to be fixed.

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2242]
We should disable rewards only when specifically receive the result that device is not eligible.

**Comment by samartnik** [comment]
https://github.com/brave/brave-core/commit/4a5f4d491173d4c32c64449d284e6cc1d038455d

**Comment by srirambv** [comment]
@samartnik can you please add appropriate labels and test plan if qa/yes?

**Comment by samartnik** [comment]
To test, on device without network try to join rewards. It should show try later toast, and Brave icon should be still available.

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.5.0rc2 BraveModernarm.apk
* reproduced issue on 1.4.3
* confirmed issue does not occur on 1.5.0rc2
