### ISSUE TITLE
Color of USD should be lighter - follow up to #1151

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2258]
## Description 

Looks like https://github.com/brave/browser-android-tabs/issues/1151 was only partially completed as the value amount is still not using `#ffffffa6` as per. Looks like the `USD` part is using the correct colour but not the value/amount.

## Actual result 

<img width="520" alt="Screen Shot 2019-11-05 at 1 10 49 AM" src="https://user-images.githubusercontent.com/2602313/68183207-b122af00-ff69-11e9-8ee3-f3910954d188.png">

## Expected result

![image](https://user-images.githubusercontent.com/9574457/53002626-5ffb7b00-342d-11e9-946c-fdc5540586ac.png)

## Issue reproduces how often 

100% reproducible using the above STR.

## Issue happens on 
   - Current Play Store version? `Yes, reproducible using 1.4.3 CR: 78.0.3904.62`
   - Beta build? `Yes, reproducible using 1.5.0 CR: 78.0.3904.90`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Pixel 2 XL`
   - Android version: `Android 10`
   
## Brave version

Reproduced on both `1.4.3 CR: 78.0.3904.62` & `1.5.0 CR: 78.0.3904.90`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @SergeyZhukovsky @anthonypkeane @brave/legacy_qa @NejcZdovc

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2259

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3.

![Screenshot_20191107-183512](https://user-images.githubusercontent.com/2602313/68437075-da238980-018d-11ea-96e8-3c009ea6909b.png)
