### ISSUE TITLE
Color of selected tab in tablet should follow private tab color

### ISSUE THREAD

**Issue by deeppandya** [brave/browser-android-tabs#2260]
## Steps to reproduce 

   1. Open private tab
   2. 
   3. 

## Actual result 
Selected Tab color for private mode is grey.

## Expected result
Selected Tab color for private mode should follow private mode theme.

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2261

**Comment by kjozwiak** [comment]
@deeppandya will add examples screenshots under `Expected result` so QA has an example of the expected UI/behaviour 👍

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.5.0-rc.3 on Huawei MediaPad M3 Lite 10 (Android 7.0).
