### ISSUE TITLE
Follow up of #2236 - BAT POINTS is not displayed in wallet balance and auto contribution panel and advanced settings popup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2262]
## Description 
Follow up of #2236 - BAT POINTS is not displayed in wallet balance and auto contribution panel and advanced settings popup

BAT points is displayed only in the BR panel. Wallet balance in brave://rewards setting page and auto contribution monthly payment dropdown and advanced settings page doesn't have BAT points or BAP as mentioned in the spec

## Steps to reproduce 

   1. Set device locale to Japan
   2. Clean profile 1.5.0-rc2
   3. Enable rewards
   4. Navigate to the rewards settings page

## Actual result 
1. BAT POINTS is not displayed in wallet balance in the rewards settings page
![image](https://user-images.githubusercontent.com/38657976/68388501-ce809480-0186-11ea-95b6-b5e401cbba64.png)

2. Rewards- Auto Contribution panel
![image](https://user-images.githubusercontent.com/38657976/68388566-f40d9e00-0186-11ea-993d-67d383fa615c.png)

3. Monthly payment dropdown values in rewards auto contribute a panel
![image](https://user-images.githubusercontent.com/38657976/68388638-21f2e280-0187-11ea-8ac6-bea2c131290a.png)

4. Advanced settings in rewards auto contribute a panel
![image](https://user-images.githubusercontent.com/38657976/68388730-4f3f9080-0187-11ea-9d89-56dfa44df64e.png)

## Expected result
BAT POINTS should be displayed in wallet balance in the rewards settings page and BAP should be displayed in place of BAT in other places

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.0-rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mattmcalister @SergeyZhukovsky @anthonypkeane @brave/legacy_qa

**Comment by SergeyZhukovsky** [comment]
Fixed here https://github.com/brave/browser-android-tabs/commit/2bc721a3e6e29301b64ed703c7085fc0c8c05d28 and https://github.com/brave/browser-android-tabs/commit/d0ef2615e6d3f5772755b486049382fe2c8d33f1

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3.

![Screenshot_20191107-220051](https://user-images.githubusercontent.com/2602313/68446800-cedf5680-01ab-11ea-88e9-a95a31b33afc.png)

![Screenshot_20191107-220116](https://user-images.githubusercontent.com/2602313/68446798-cedf5680-01ab-11ea-8b29-7bb29a770ef4.png)

![Screenshot_20191107-220220](https://user-images.githubusercontent.com/2602313/68446797-cedf5680-01ab-11ea-8ba4-752b67b22e8a.png)

![Screenshot_20191107-220124](https://user-images.githubusercontent.com/2602313/68446799-cedf5680-01ab-11ea-8463-f9a026d216ce.png)

![Screenshot_20191107-221533](https://user-images.githubusercontent.com/2602313/68447005-65ac1300-01ac-11ea-8f4c-fdda6d3c7091.png)

![Screenshot_20191107-221540](https://user-images.githubusercontent.com/2602313/68447004-65ac1300-01ac-11ea-9574-b0aafeb7c049.png)

![Screenshot_20191107-221602](https://user-images.githubusercontent.com/2602313/68447003-65ac1300-01ac-11ea-8ed3-c8a49e295662.png)

![Screenshot_20191107-221547](https://user-images.githubusercontent.com/2602313/68447002-65ac1300-01ac-11ea-9e70-1b380a304954.png)

**Comment by kjozwiak** [comment]
Created both https://github.com/brave/browser-android-tabs/issues/2272 & https://github.com/brave/browser-android-tabs/issues/2274 as follow ups.
