### ISSUE TITLE
Red triangle icon in URL bar on `chrome://` pages

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2263]
Red triangle with `i` inside in URL bar on new tab page. This icon suggests that the site is not safe.

## Steps to reproduce 

   1. Open Brave
   2. Open a `chrome://` page. (this includes new tab page)

## Actual result 
Red triangle icon in URL bar
![image](https://user-images.githubusercontent.com/34715963/68389328-f8c05b00-0162-11ea-9306-a8b44f755041.png)
![Screenshot_20191107-131605](https://user-images.githubusercontent.com/34715963/68389297-e514f480-0162-11ea-8b13-3f96595e9e66.png)

## Expected result
![Screenshot_20191107-133807](https://user-images.githubusercontent.com/34715963/68389924-67ea7f00-0164-11ea-9c75-4a0d75b60fa9.png)

## Issue reproduces how often 
Always

## Device details
   - Install type (ARM, x86): arm
   - Device (Phone, Tablet, Phablet):Tablet
   - Android version: 7.0
   
## Brave version
Reproducible on BraveModernarm v1.5.0-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0).
Not reproducible on PS build.
Not reproducible on BraveModernarm v1.5.0-rc.1.

cc @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by LaurenWags** [comment]
Does not reproduce on Asus Zenfone (x86) with Android 6.0 running 1.5.0rc2 BraveModernx86.apk in landscape or portrait mode.

**Comment by anthonypkeane** [comment]
Internal chat: https://bravesoftware.slack.com/archives/C0816QH3R/p1573130737309900

>  make an exception that for everything that starts with chrome://

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2270

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.5.0-rc.3 on Huawei MediaPad M3 Lite 10 (Android 7.0).
We don't show any icon in the URL bar
![Screenshot_20191108-085249](https://user-images.githubusercontent.com/34715963/68459695-59ed3a80-0206-11ea-8247-619fea4e7e2f.png)
![Screenshot_20191108-085256](https://user-images.githubusercontent.com/34715963/68459696-59ed3a80-0206-11ea-9292-55c2440bb5a4.png)

**Comment by bradleyrichter** [comment]
@btlechowski @SergeyZhukovsky 
> We don't show any icon in the URL bar

It's fine to not show an icon but PLEASE add some left margin for this case so the string is not touching the left edge of the URL box.
