### ISSUE TITLE
Follow up of #2239 - Tip amount is not changed to BAP in tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2266]
## Description 
Follow up of #2239 
Tip amount is not changed to BAP in tips panel

## Steps to reproduce 

   1. Set device locale to Japanese
   2. Clean profile 1.5.0-rc2
   3. Enable rewards and fund the wallet
   4. Send a monthly tip and one time tips to verified or non-verified pubs

## Actual result 
Tips panel -Tip amount is not changed to BAP

![image](https://user-images.githubusercontent.com/38657976/68397310-fda00180-0198-11ea-853e-125678e80e73.png)

## Expected result

As mentioned in the Mobile Spec, Change Tip amounts from “BAT” to “BAP” (point 3 in mobile section)
Tip amount should be changed to BAP in tips panel
## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 5.1.1
   
## Brave version

1.5.0-rc2
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mattmcalister @anthonypkeane @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Fixed here https://github.com/brave/browser-android-tabs/commit/2bc721a3e6e29301b64ed703c7085fc0c8c05d28 and https://github.com/brave/browser-android-tabs/commit/d0ef2615e6d3f5772755b486049382fe2c8d33f1

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3.

![Screenshot_20191107-200328](https://user-images.githubusercontent.com/2602313/68444364-9daf5800-01a4-11ea-819f-2a89544156fb.png)

![Screenshot_20191107-200435](https://user-images.githubusercontent.com/2602313/68444377-a30ca280-01a4-11ea-8381-98923cd353eb.png)

![Screenshot_20191107-211517](https://user-images.githubusercontent.com/2602313/68444370-a011b200-01a4-11ea-94dc-12d314ed5184.png)

![Screenshot_20191107-201221](https://user-images.githubusercontent.com/2602313/68444399-b28beb80-01a4-11ea-8f4e-fa50818642c3.png)

![Screenshot_20191107-202022](https://user-images.githubusercontent.com/2602313/68444401-b3248200-01a4-11ea-8f42-a85a371570a1.png)

![Screenshot_20191107-211424](https://user-images.githubusercontent.com/2602313/68444400-b3248200-01a4-11ea-83e0-88a16b4b3e71.png)
