### ISSUE TITLE
Brave crashes after trying to send a tip

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2269]
## Steps to reproduce 

   1. Clean install
   2. Run Brave 
   3. Enable rewards (enabled through onboarding)
   4. Open duckduckgo.com
   5. Wait for verified publishers list to be downloaded and applied
   6. Tap `SEND A TIP...` in Rewards Panel

![Screenshot_20191107-184806](https://user-images.githubusercontent.com/34715963/68414324-43a49780-0190-11ea-9175-bec210363083.png)

Note: I did not claimed and grants, there was 0.0 BAT in the wallet

## Actual result 
Crash

## Expected result
No Crash
Send tip modal is shown
![Screenshot_20191107-185419](https://user-images.githubusercontent.com/34715963/68414360-528b4a00-0190-11ea-93d9-9dd0f696f183.png)

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? yes

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet):Tablet
   - Android version: 7.0
   
## Brave version
BraveModernarm v1.5.0-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0).

Not reproducible in BraveModernarm v1.5.0-rc.1

### Additional information

cc @brave/legacy_qa @anthonypkeane @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2270

**Comment by kjozwiak** [comment]
Managed to reproduce this on my `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.2. You need to make sure the device is in *`landscape`* mode before you send a tip.

STR:

* launch https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.2
* once launched, switch over to the `staging` server via the `Developer` settings
* enable `Rewards` and accept the grant that's available on `staging`
* open `https://duckduckgo.com/` and switch to *`landscape`* mode
* send `https://duckduckgo.com/` a tip using the panel (Brave will crash)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.3.

* went through https://github.com/brave/browser-android-tabs/issues/2269#issuecomment-551319271 
* ensured that tipping worked using both landscape & portrait
* ensured that setting monthly contributions worked using both both landscape & portrait
* ensured that tipping after upgrading from `1.5.0 CR: 78.0.3904.90 RC2` --> `RC3` worked
