### ISSUE TITLE
BAP not being used under "brave://rewards/#rewards-summary"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2272]
## Description 

`BAT` is s till being used under `brave://rewards/#rewards-summary` rather than `BAP`

## Steps to reproduce 

   1. set the device locale to `Japanese`
   2. install `1.5.0 CR: 78.0.3904.90` and switch to `staging` (accept the grant)
   3. using the grant, tip `https://duckduckgo.com`
   4. go into `brave://rewards` and tap on `Your wallet` so it opens `brave://rewards/#rewards-summary`

## Actual result 

![Screenshot_20191107-220051](https://user-images.githubusercontent.com/2602313/68447365-ace6d380-01ad-11ea-84fb-e3ebd6b6413c.png)

![Screenshot_20191107-221533](https://user-images.githubusercontent.com/2602313/68447366-ace6d380-01ad-11ea-98b9-2f1976f3b056.png)

## Expected result

Should be using `BAP` instead of `BAT` as per the specification.

## Issue reproduces how often 

100% reproducible when going through the above STR.

## Issue happens on 

   - Current Play Store version? `N/A`
   - Beta build? `Yes, reproducible using `1.5.0 CR: 78.0.3904.90`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Pixel 2 XL`
   - Android version: `Android 10`
   
## Brave version

* `1.5.0 CR: 78.0.3904.90`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @anthonypkeane @SergeyZhukovsky @samartnik @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5..1.1 running Bravemodernarm 1.5.0-rc3

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.5.0-rc.3 on Huawei MediaPad M3 Lite 10 (Android 7.0).
![Screenshot_20191108-092740](https://user-images.githubusercontent.com/34715963/68461616-eac61500-020a-11ea-8f6c-dcb88ccb822b.png)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/2276

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.1-rc.1.

![Screenshot_20191112-015146](https://user-images.githubusercontent.com/2602313/68648873-6536b380-04ef-11ea-9107-a971534fbb56.png)
