### ISSUE TITLE
History shows up as chrome://history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#228]
![image](https://cloud.githubusercontent.com/assets/17010094/25473640/26b5d9ae-2b28-11e7-85c2-47bf39606acb.png)

**Comment by mario-d-s** [comment]
@srirambv What would you like it to show as instead?

**Comment by srirambv** [comment]
Should either be `brave://history` or `about:history`

cc: @samartnik @SergeyZhukovsky
