### ISSUE TITLE
Brave crashes in debug while entering non-ascii symbols into omnibox. 

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2280]
## Description 
Brave crashes in debug version while entering non-ascii symbols into omnibox. 

## Steps to reproduce 

   1. Run debug version of Brave.
   2. Enter any non-ascii symbol into url-bar
   3. Observe the app is crashing at
 TopSitesProvider::Start(AutocompleteInput const&, bool)                           
 ../../components/omnibox/browser/topsites_provider.cc:33:53

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Moving into `1.6.0` after discussing with @SergeyZhukovsky.

**Comment by srirambv** [comment]
Marking as QA/No since this is for debug builds. @gdregalo please update the label if QA needs to go through this during testing
