### ISSUE TITLE
URL bar icons are not clearly visible on dark/light themes

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2287]
## Description 
URL bar icons are not clearly visible on dark/light themes

## Steps to reproduce 

   1. Update to 1.5.0
   2. Set device theme to dark and visit any page that has dark page theme 
   3. Icons are not visible correctly 

## Actual result 
Mobile: Dark theme 
![image](https://user-images.githubusercontent.com/17010094/68691915-8ffe2780-0542-11ea-8e6b-5ceda01d936a.png)
Mobile: Light Theme
![image](https://user-images.githubusercontent.com/17010094/68691949-9be9e980-0542-11ea-8e18-3f33521cc820.png)
Tablet: Dark theme
![image](https://user-images.githubusercontent.com/17010094/68691990-b02de680-0542-11ea-851b-c85027157dd6.png)

## Expected result
Clearly visible icons

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @jamesmudgett @deeppandya

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2321

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL `Android 10` using `1.6.0 CR: 78.0.3904.108 RC1`:

* ensured that the icons looked correct as exampled below on both `Dark` & `Light` using a clean profile after installing `1.6.0 CR: 78.0.3904.108 RC1`
* ensured that the icons looked correct as exampled below on both `Dark` & `Light` when upgrading from `1.5.2 CR: 78.0.3904.108`--> `1.6.0 CR: 78.0.3904.108 RC1`

#### **`Dark Theme`**

<img width="531" alt="Screen Shot 2019-11-28 at 3 46 42 PM" src="https://user-images.githubusercontent.com/2602313/69831190-4e35d800-11f6-11ea-9d5f-ba8939267c20.png">

<img width="523" alt="Screen Shot 2019-11-28 at 3 46 33 PM" src="https://user-images.githubusercontent.com/2602313/69831191-4e35d800-11f6-11ea-9d85-34e800a2b631.png">

<img width="524" alt="Screen Shot 2019-11-28 at 3 48 32 PM" src="https://user-images.githubusercontent.com/2602313/69831242-905f1980-11f6-11ea-8d38-b64209da118f.png">

<img width="524" alt="Screen Shot 2019-11-28 at 3 48 24 PM" src="https://user-images.githubusercontent.com/2602313/69831243-905f1980-11f6-11ea-98a8-9dbecbad7a00.png">

#### **`Light Theme`**

<img width="521" alt="Screen Shot 2019-11-28 at 3 50 16 PM" src="https://user-images.githubusercontent.com/2602313/69831295-ca302000-11f6-11ea-8daa-00005f4b6572.png">

<img width="523" alt="Screen Shot 2019-11-28 at 3 46 33 PM" src="https://user-images.githubusercontent.com/2602313/69831191-4e35d800-11f6-11ea-9d85-34e800a2b631.png">

<img width="522" alt="Screen Shot 2019-11-28 at 3 51 32 PM" src="https://user-images.githubusercontent.com/2602313/69831341-f8adfb00-11f6-11ea-9ca3-4d49dff81671.png">

<img width="517" alt="Screen Shot 2019-11-28 at 3 51 25 PM" src="https://user-images.githubusercontent.com/2602313/69831343-f8adfb00-11f6-11ea-9c3c-3bed05dd5ea7.png">
