### ISSUE TITLE
BAP Change

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2293]
## Description 
Please change BAP so that BAT or BAP is set on installation (first open) based on locale and cannot be changed, regardless or whether the user changes their locale.

iOS Issue for reference: https://github.com/brave/brave-ios/issues/1949

**Comment by samartnik** [comment]
This is already implemented.

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.6.0-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0).
Verified  BAP/BAT Points is used.
- Verified that BAP is used based on installation locale and does not change after changing locale.
The screen shot shows Polish locale with BAP used.
![Screenshot_20191128-230520](https://user-images.githubusercontent.com/34715963/69833399-e0100600-1233-11ea-8d17-d3adc1ac3680.png)
- Verified that BAT is not changed to BAP/BAT Points
![Screenshot_20191128-231120](https://user-images.githubusercontent.com/34715963/69833515-9247cd80-1234-11ea-8b5e-330c03624ac0.png)
- Verified Brave Rewards Panel
![Screenshot_20191128-224405](https://user-images.githubusercontent.com/34715963/69833154-56ac0400-1232-11ea-8fe9-b44bec4e007f.png)
- Verified Tipping modal
![Screenshot_20191128-224421](https://user-images.githubusercontent.com/34715963/69833155-57449a80-1232-11ea-96c9-d1d9b6321cbc.png)
- Verified tipping `Thank you` modal for one time tip 
![Screenshot_20191128-224430](https://user-images.githubusercontent.com/34715963/69833156-57449a80-1232-11ea-8bda-2135da7e2bbc.png)
- Verified tipping `Thank you` modal for monthly tip
![Screenshot_20191128-224514](https://user-images.githubusercontent.com/34715963/69833157-57449a80-1232-11ea-8d8f-56c38ef6a639.png)
- Verified rewards summery in `chrome://rewards`
![Screenshot_20191128-224533](https://user-images.githubusercontent.com/34715963/69833158-57449a80-1232-11ea-82cd-784750896aed.png)
- Verified ads section in `chrome://rewards`
![Screenshot_20191128-224604](https://user-images.githubusercontent.com/34715963/69833159-57449a80-1232-11ea-9ac6-27fb76d9944f.png)
- Verified a-c section in `chrome://rewards`
![Screenshot_20191128-224616](https://user-images.githubusercontent.com/34715963/69833160-57dd3100-1232-11ea-96b7-0063bb5729ef.png)
- Verified tipping section in `chrome://rewards`
![Screenshot_20191128-224626](https://user-images.githubusercontent.com/34715963/69833161-57dd3100-1232-11ea-8535-5f40e544d6ea.png)
