### ISSUE TITLE
Swap warning icons for HTTP and broken-HTTPS sites

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#2296]
We got the warning icons backwards in #1592

- HTTP sites (like `http.badssl.com`) should get an open red padlock.
- Where there _should_ be an HTTPS connection but it's broken (like `wrong.host.badssl.com`) should get a red exclamation point in a triangle.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2321

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.6.0 
* Verified `open red padlock` is shown for `http.badssl.com`
![image](https://user-images.githubusercontent.com/17010094/69831735-c30a1180-11f8-11ea-9b17-d923fff2408d.png)
* Verified `red exclamation point in a triangle` for `wrong.host..badssl.com`
![image](https://user-images.githubusercontent.com/17010094/69831749-d2895a80-11f8-11ea-893b-62ae52f0999c.png)
