### ISSUE TITLE
Site settings set in incognito tab is retained in normal tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#231]
**Description:**
Site settings set in incognito tab is retained in normal tab

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Site settings set in incognito tab should not be retained in normal tab

- Device : Lenovo Yoga Tablet Android 5.0.1

- Brave Version:
v1.0.20 x86

- Steps to reproduce:
    1. Open a new incognito tab and visit http://brianbondy.com
    2. Enable block script and check the block count
    3. Close incognito tab and open http://brianbondy.com in a new tab
    4. Block script is enabled and shows 8 scripts blocked, but site is loaded properly

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25476892/86758744-2b33-11e7-9827-b429ee9fea2a.png)
![image](https://cloud.githubusercontent.com/assets/17010094/25476918/9b74b6e2-2b33-11e7-81ae-45922f4f8329.png)

- Any related issues:

**Comment by srirambv** [comment]
Still reproducible on latest RC. Moving to 1.0.25

**Comment by LaurenWags** [comment]
Experienced this while testing https://github.com/brave/browser-android-tabs/issues/429

**Comment by AlexeyBarabash** [comment]
Made PR for the issue https://github.com/brave/browser-android-tabs/pull/437 .
