### ISSUE TITLE
Brave BAT token rewards Auto contribute enable by itself

### ISSUE THREAD

**Issue by Mitsu091485** [brave/browser-android-tabs#2310]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Please edit the details and reopen the issue. Just title isn't helpful to understand the issue.
