### ISSUE TITLE
Panel doesn't handle properly Result::LEDGER_OK which results in message "Please try again"

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2317]
## Description 
If quickly open the panel after browser started then panel shows "Enable Brave Rewards" and "Please try again" message.

## Steps to reproduce 

   1.  Restart browser after wallet was created.
   2.  Immediately tap BAT button to open the panel.
   3.  Observe  "Enable Brave Rewards" and "Please try again message".

## Expected result
The panel should properly identify the Rewards status.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.6.0-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0). 
Verified the test plan from the description. Verified 10 times. Also checked when wallet was created through onboarding.
