### ISSUE TITLE
Stats text colour needs a better contrast to show properly on NTP images

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2325]
## Description 
Stats text colour needs a better contrast to show properly on NTP images 

## Steps to reproduce 

   1. Open new tab
   2. Reload to get new tab images
   3. Stats text gets blended in with background image making it hard to see/read

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/69830393-b5518d80-11f2-11ea-9f75-9ef924680ba6.png)
![image](https://user-images.githubusercontent.com/17010094/69830400-bbe00500-11f2-11ea-94f4-a0f0c42b1f0e.png)
![image](https://user-images.githubusercontent.com/17010094/69830404-c0a4b900-11f2-11ea-87e2-f41c1f3391ea.png)
![image](https://user-images.githubusercontent.com/17010094/69830408-c4d0d680-11f2-11ea-90e4-e6c84d29ee04.png)
![image](https://user-images.githubusercontent.com/17010094/69830413-c9958a80-11f2-11ea-83ed-687043c17ab7.png)
![image](https://user-images.githubusercontent.com/17010094/69830418-cdc1a800-11f2-11ea-940b-75cc63360a31.png)
![image](https://user-images.githubusercontent.com/17010094/69830421-d1552f00-11f2-11ea-94d2-c5986fbfbb5f.png)
![image](https://user-images.githubusercontent.com/17010094/69830426-d5814c80-11f2-11ea-8d80-e313410ae153.png)
![image](https://user-images.githubusercontent.com/17010094/69830434-ddd98780-11f2-11ea-9e34-899b1fa54f80.png)
![image](https://user-images.githubusercontent.com/17010094/69830437-e205a500-11f2-11ea-9a47-5e3a711af0ac.png)
![image](https://user-images.githubusercontent.com/17010094/69830447-e631c280-11f2-11ea-8e84-93c36cb0bdb5.png)

## Expected result
Text should be readable

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Issue happens on both dark/light theme

**Comment by SergeyZhukovsky** [comment]
cc @anthonypkeane @jamesmudgett for a design

**Comment by deeppandya** [comment]
Fixed by https://github.com/brave/browser-android-tabs/pull/2336

**Comment by kjozwiak** [comment]
Definitely looks a lot better compared to before 👍Verification **PASSED** on `Pixel 2 XL` on `Android 10` using `1.6.0 CR: 78.0.3904.10 RC2`

#### **`Examples`**:

![Screenshot_20191202-022559](https://user-images.githubusercontent.com/2602313/69938998-c4fbfb00-14ac-11ea-80b2-95ea9be79dcf.png)
![Screenshot_20191202-022621](https://user-images.githubusercontent.com/2602313/69938999-c4fbfb00-14ac-11ea-8109-3bae07ced890.png)
![Screenshot_20191202-022628](https://user-images.githubusercontent.com/2602313/69939000-c4fbfb00-14ac-11ea-8ee3-f38d89c09cc0.png)
![Screenshot_20191202-022640](https://user-images.githubusercontent.com/2602313/69939001-c4fbfb00-14ac-11ea-8c39-f309a31b1dd1.png)
![Screenshot_20191202-022646](https://user-images.githubusercontent.com/2602313/69939003-c5949180-14ac-11ea-9ee2-03b80543a332.png)
![Screenshot_20191202-022651](https://user-images.githubusercontent.com/2602313/69939004-c5949180-14ac-11ea-9383-7f72d433a436.png)
![Screenshot_20191202-022656](https://user-images.githubusercontent.com/2602313/69939005-c5949180-14ac-11ea-9e5d-635353e67f78.png)
![Screenshot_20191202-022706](https://user-images.githubusercontent.com/2602313/69939006-c5949180-14ac-11ea-91d9-7a63bcb448c1.png)
![Screenshot_20191202-022710](https://user-images.githubusercontent.com/2602313/69939007-c5949180-14ac-11ea-8c3f-2a4d4b07904d.png)
![Screenshot_20191202-022714](https://user-images.githubusercontent.com/2602313/69939008-c62d2800-14ac-11ea-9914-598762f3adc2.png)
![Screenshot_20191202-022719](https://user-images.githubusercontent.com/2602313/69939010-c62d2800-14ac-11ea-8f86-cc60b0107bb2.png)
![Screenshot_20191202-022723](https://user-images.githubusercontent.com/2602313/69939011-c62d2800-14ac-11ea-924f-83ace2c5b8ae.png)
![Screenshot_20191202-022729](https://user-images.githubusercontent.com/2602313/69939012-c62d2800-14ac-11ea-847d-d724b2d08967.png)
![Screenshot_20191202-022747](https://user-images.githubusercontent.com/2602313/69939013-c62d2800-14ac-11ea-9c66-859b2159d6ae.png)
![Screenshot_20191202-022811](https://user-images.githubusercontent.com/2602313/69939014-c62d2800-14ac-11ea-9360-1f2fe10b6950.png)

**Comment by kjozwiak** [comment]
I'll wait till @srirambv @GeetaSarvadnya @btlechowski take a look and see if it looks fine on their devices before adding the `QA Pass - Android ARM` label.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy version 5.1.1 running `BraveModernarm.apk` 1.6.0-rc2

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.6.0-rc.2 on Huawei MediaPad M3 Lite 10 (Android 7.0).

Examples on tablet:
![Screenshot_20191202-142945](https://user-images.githubusercontent.com/34715963/69965631-fad4ca00-1514-11ea-8c91-15463839a8ca.png)
![Screenshot_20191202-143707](https://user-images.githubusercontent.com/34715963/69965633-fb6d6080-1514-11ea-9141-b95c590e41cc.png)
![Screenshot_20191202-143729](https://user-images.githubusercontent.com/34715963/69965634-fb6d6080-1514-11ea-9f2a-0c5901ab0dc5.png)
![Screenshot_20191202-143920](https://user-images.githubusercontent.com/34715963/69965635-fc05f700-1514-11ea-93a9-22d806ba1f3c.png)
![Screenshot_20191202-143927](https://user-images.githubusercontent.com/34715963/69965637-fc05f700-1514-11ea-860a-9071faa1eeb6.png)
![Screenshot_20191202-143934](https://user-images.githubusercontent.com/34715963/69965639-fc9e8d80-1514-11ea-841b-d5f154c7e571.png)
![Screenshot_20191202-143940](https://user-images.githubusercontent.com/34715963/69965640-fc9e8d80-1514-11ea-8c69-edc7bd2dc4b8.png)
![Screenshot_20191202-143947](https://user-images.githubusercontent.com/34715963/69965641-fd372400-1514-11ea-8eee-10860259946f.png)

**Comment by srirambv** [comment]
Verified on OnePlust 6T with Android 9.0 running 1.6.0 x64 build.
* Verified stats are clearly visible on both dark and light theme 

Verified on Samsung Tab A with Android 9.0 running 1.6.0 x64 build.
* Verified stats are clearly visible on both dark and light theme
