### ISSUE TITLE
[Intermittent] Disable new tab image setting doesn't always prompt restart 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2326]
## Description 
Disable new tab image setting doesn't always prompt restart 

## Steps to reproduce 

   1. Install playstore build and use it for a while 
   2. Upgrade to 1.6.0 
   3. Open settings and disable NTP images
   4. Doesn't prompt to reluanch the browser
   5. Exit setting and go back to new tab, image is still shown
   6. Change theme setting, new tab image is removed now

## Actual result 
Disable new tab image setting doesn't always prompt restart 

## Expected result
Should always prompt to restart the browser after the setting is toggled

## Issue reproduces how often 
Intermittent issue

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet (Samsung Tab A)
   - Android version: 9.0
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @deeppandya

**Comment by deeppandya** [comment]
Fixed by https://github.com/brave/browser-android-tabs/pull/2336

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.6.0 rc3 x64 build
* Verified relaunch prompt is always shown when trying to disable NTP images

**Comment by kjozwiak** [comment]
@deeppandya out of curiosity, is the restart purely needed for older devices due to the memory issue we were running into? Seems like selecting `Later` basically has the same effect. Once you've disabled images on the NTP via the `New Tab Page --> Show Background Images` and selecting `Later`, creating new NTP will be blank as expected and vis versa when enabling images. Doesn't seem like a restart is needed. At least for newer devices.

**Comment by srirambv** [comment]
> creating new NTP will be blank as expected and vis versa when enabling images. Doesn't seem like a restart is needed. 

Restart is only required for existing new tabs that are already opened before setting is changed.
