### ISSUE TITLE
Image credit is missing on New Tab Images

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2327]
## Description 
Image credit is missing on New Tab Images

## Steps to reproduce 

   1. Open a new tab
   2. No image credits are shown
   3. Long press on new tab doesn't show any context menu with image credits similar to iOS

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/69830836-98b65500-11f4-11ea-9896-ab659e0ae728.png)

## Expected result
Image credit similar to Desktop

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: 9.0
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @deeppandya @brave/design

**Comment by deeppandya** [comment]
Fixed by this : https://github.com/brave/browser-android-tabs/pull/2337

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` on `Android 10` using `1.6.0 CR: 78.0.3904.10 RC2`. Went through the following cases:

* ensured that each image on the NTP has a `Photo by: Photographers Name` at the bottom
* ensured each `Photo by: Photographers Name` opens a new tab with the appropriate link
* ensured certain images under NTP don't display `Photo by: Photographers Name` 
* ensured that `Photo by: Photographers Name` is visible in both `Dark` & `Light` modes
* ensured that `Photo by: Photographers Name` is displayed correctly under `Portrait` & `Landscape`
