### ISSUE TITLE
Verified icon flashes when rewards panel is clicked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2328]
## Description 
Verified icon flashes when rewards panel is clicked

## Steps to reproduce 

   1. Update to 1.6.0
   2. Visit a verified publisher page
   3. Click on rewards panel, verified check mark flashes when panel is opened

## Actual result 
Verified icon flashes when rewards panel is clicked

## Expected result
Should not flash when panel is clicked

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: 9.0
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarn1.6.3-rc1.apk`
