### ISSUE TITLE
Brave is crashing when19th NTP is opened. Also, there is a web-view crash on the initial launch

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2332]
## Description 
Brave is crashing when19th NTP is opened. Also, there is a web-view crash on the initial launch. The issue is continuously reproducible for locales `India` and `Japan` didn't check other locales
## Steps to reproduce 

   1. Clean profile 1.6.0-rc1
   2. Verify that there is a webview crash before onboarding flow open
   3. Click on Skip in the onboarding flow
   4. Click on the hamburger menu and select `New tab` and open 19 NTP
   5. Brave is crashing when 19th NTP is opened

Note: the same crash issue occurs even if you open a new tab using `+` icon from bottom toolbar when 19th new tab is opened brave crashes

## Actual result 
Brave is crashing when19th NTP is opened. Also, there is a web-view crash on the initial launch
https://drive.google.com/open?id=1ZfO_Y33fQMNPV7ULpcIXk9mSX_FDOQIo
## Expected result
Should not be any crash 

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.6.0-rc1
### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @anthonypkeane @SergeyZhukovsky @deeppandya @brave/legacy_qa

**Comment by SergeyZhukovsky** [comment]
Not much we can do here. It looks like not enough memory on low end devices. What we can do probably on next releases is to disable background images on Android OS version <6.0.

**Comment by deeppandya** [comment]
Added a check for low end devices. Fixed by https://github.com/brave/browser-android-tabs/pull/2336

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.6.0-rc2
