### ISSUE TITLE
NTP images change when bringing the app into focus

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2334]
## Description 
NTP images change when bringing the app into focus

## Actual result 
https://bravesoftware.slack.com/archives/C0816QH3R/p1575033744462900

## Expected result
Image should not reload based on app state

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 9.0
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
Fixed by this : #2337

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm 1.6.0-rc2

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk` 1.6.0-rc2
