### ISSUE TITLE
Follow up of #2332 - Swipe between tabs removes images from tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2339]
## Description 
Follow up of #2332 - Swipe between tabs removes images from tabs

## Steps to reproduce 

   1. Clean profile 1.6.0-rc2
   2. Open 16 tabs 
   3. Swipe tabs from right to left from the bottom toolbar
   4. Images are removed from tabs (tab 1 to tab 13)

Note: Starting two swipes retains the images in tabs but subsequent swipes remove images from tabs
## Actual result 
Swipe between tabs removes images from tabs
https://drive.google.com/open?id=1GWlxJVf-xSIgUpKTDyGJHKfesCQ0qPNP

## Expected result

Swipe between tabs shouldn't remove images from tabs
## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Beta

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.6.0-rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane @deeppandya

**Comment by deeppandya** [comment]
Fixed by : https://github.com/brave/browser-android-tabs/pull/2340

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm.apk 1.6.0-rc3
