### ISSUE TITLE
NTP images cannot be toggled off for older Android versions

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2341]
## Description 
Toggling `Show Background Images` off and relaunching does not remove background images from NTP.

## Steps to reproduce 

   1. Have 1.6.0rc3 installed.
   2. Go to settings and toggle OFF `Show Background Images`. 
   3. Relaunch as prompted.
   4. NTP still shows background images.
   5. Manually remove app from memory and relaunch.
   6. NTP still shows background images.

## Actual result 
NTP background images shown when toggle is set to OFF

## Expected result
No background images on NTP when toggle is set to OFF

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: 5, 6
   
## Brave version
1.6.0rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
Reproduced on Android 5 by @GeetaSarvadnya

**Comment by deeppandya** [comment]
It was fixed in 1.6.0 RC4. @LaurenWags has verified it. @LaurenWags can you please confirm ?

**Comment by LaurenWags** [comment]
@deeppandya you are correct, this does not occur on 1.6.0. However, if we plan to show images on lower end devices in the future, this needs to be checked at that time. 
I'm not sure what the plan is though.

cc @srirambv

**Comment by srirambv** [comment]
Lets keep it open for now and if we decide to show images on Android 5/6 then we can verify it else close it once the decision is taken

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.4 rc1 BraveModernx86.apk
   - Verified STR from description on a clean profile
   - Verified STR from description on an upgraded profile (1.5.3 --> 1.5.4rc1)
