### ISSUE TITLE
Stats text is not visible and top tiles are overlapping on the tab image

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2342]
## Description 

Stats text is not visible and top tiles are overlapping on the tab image. Please note this issue affects only Android 5 and Android 6 versions.

## Steps to reproduce 

   1. Install 1.6.0 rc3
   2. Launch brave open one or two tabs
   3. Click on the hamburger menu, exit the browser and relaunch the browser
   4. Open 5 or 6 tabs and view tab image
   5. Navigate to settings and disable the `show background-image`
   6. Relaunch the browser
   7. Open 5 to 6 tabs
   8. Stats text is not visible and top tiles are overlapping on the tab image
   
   
## Actual result 
Stats text is not visible and top tiles are overlapping on the tab image
https://bravesoftware.slack.com/archives/C0816QH3R/p1575311771490400
## Expected result
Stats text should be visible and top tiles shouldn't overlap on the tab image

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.6.0-rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @SergeyZhukovsky @anthonypkeane

**Comment by deeppandya** [comment]
@anthonypkeane it was fixed in 1.6.0 RC4. @GeetaSarvadnya can you please comment on this ?

**Comment by samartnik** [comment]
Closing as it is already released

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.6.1 rc1 x64 build
- Verified steps from the issue and was able to view stats correctly on NTP with and without images
