### ISSUE TITLE
crash when switching between Light/Dark Themes on older Android devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2343]
## Description 
Crash when switching between Light/Dark theme in Brave

## Steps to reproduce 

1. STR: Clean install 1.6.0rc3 
2. Launch and open a second NTP
3. Go to Settings > Appearance > Themes
4. Change to Dark
5. Wait a sec, Brave crashes.

## Actual result 
Crash

## Expected result
No Crash

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): all
   - Android version: 5 and 6
   
## Brave version
1.6.0rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
Reproduced by @GeetaSarvadnya

**Comment by deeppandya** [comment]
@anthonypkeane it's irrelevant as we are not showing background images on low end devices. For release 1.6.0, I think @LaurenWags has verified it.

**Comment by LaurenWags** [comment]
@deeppandya you are correct, this does not occur on 1.6.0. However, if we plan to show images on lower end devices in the future, this needs to be checked at that time. 
I'm not sure what the plan is though.

cc @srirambv

**Comment by srirambv** [comment]
Yes this needs to be checked for crash if we decide to implement images on Android 5/6 devices. So better to keep this open and add it to the milestone where we plan to get the images in

**Comment by anthonypkeane** [comment]
Moving to 16.2 for re-checking once NTP is supported on Android 5/6

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 (ARM) with Android 5.1 running 1.5.4 BraveModernarm.apk
   - Verified switching from Light --> Dark and Dark --> Light themes did not crash the app
   - Ran thru STR from description 5x

**Comment by deeppandya** [comment]
Closing this issue as it's done in current RC

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6 running 1.5.4rc1 BraveModernx86.apk
   - Verified switching from Light --> Dark and Dark --> Light themes did not crash the app
   - Ran thru STR from description 5x
