### ISSUE TITLE
crash on older Android devices when opening new tab from tab tray - follow up to 2295

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2344]
## Description 
Found while testing #2295

Crash when selecting `+` icon to open a new tab in the tab tray after having closed all tabs.

## Steps to reproduce 

   1. Have several tabs open.
   2. Open tab tray.
   3. Tap on 3 dots > select 'Close all tabs'
   4. Tap on `+` to open a new tab

## Actual result 
Brave Crashes --> you get `Unfortunately, Brave has stopped.` message.

## Expected result
No Crash, new tab should open.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): all
   - Android version: 5 and 6
   
## Brave version
1.6.0 rc3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
reproduced by @GeetaSarvadnya

**Comment by deeppandya** [comment]
@anthonypkeane it's irrelevant as we are not showing background images on low end devices. For release 1.6.0, I think @LaurenWags has verified it.

**Comment by LaurenWags** [comment]
@deeppandya you are correct, this does not occur on 1.6.0. However, if we plan to show images on lower end devices in the future, this needs to be checked at that time. 
I'm not sure what the plan is though.

cc @srirambv

**Comment by srirambv** [comment]
Need to verify if it crashes when we decide to get images on Android 5/6 devices.

**Comment by c0s** [comment]
I am getting these crashes on Huawei MediaPad M5 (10.8 inches) running Android 9 CMR-W09
Brave's version is 1.6.0, Chroimium 78.0.3904.108

Every time I open a new tab when tablet is in "landscape" orientation, Brave crashes with a loud thud.  The only way to go around is to turn the device into portrait, reopen Brave and open new tab. If you try to rotate it back to landscape with an empty new tab open, it will crash again immediately. 

However, if any website is opened in this new tab and only then the tablet is rotated - everything will be working fine. The problem has started with last update when the images were added ;(

**Comment by c0s** [comment]
> @deeppandya you are correct, this does not occur on 1.6.0. However, if we plan to show images on lower end devices in the future, this needs to be checked at that time.
> I'm not sure what the plan is though.
> 
> cc @srirambv

Actually, it happens with 1.6.0 and it happens on high-end devices. See my comment above

**Comment by srirambv** [comment]
Cant reproduce this crash on Samsung Tab A. Either on new install or on upgrade. @btlechowski can you please check this on your Mediafpad device?

**Comment by Mikko031014** [comment]
Sent from Yahoo Mail on Android 
 
  On Sun, Dec 15, 2019 at 7:40 AM, Sriram<notifications@github.com> wrote:   
Cant reproduce this crash on Samsung Tab A. Either on new install or on upgrade. @btlechowski can you please check this on your Mediafpad device?

**Comment by btlechowski** [comment]
@srirambv My `Huawei MediaPad M3 Lite 10 (Android 7.0).` is in repair. 

I was unable to reproduce on Samsung s7 (Android 8.0), Brave 1.6.1.
I was unable to reproduce on Samsung Galaxy Tab S5e  (Android 9.0), Brave 1.6.0.

**Comment by srirambv** [comment]
@c0s  would you be able to record the crash on your device and update the issue?

**Comment by c0s** [comment]
> @c0s would you be able to record the crash on your device and update the issue?

@srirambv you mean like a screencast recording? I should be able to do so, yes... Please let me know if something else is needed.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.4rc1 BraveModernx86.apk
   a. When NTP background images are ON:
      - Verified when the option for `Closing all tabs closes Brave` is ON --> Brave closed as expected at step 3
      - Verified when the option for `Closing all tabs closes Brave` is OFF, used the STR from the description and no crash was observed.
   a. When NTP background images are OFF:
      - Verified when the option for `Closing all tabs closes Brave` is ON --> Brave closed as expected at step 3
      - Verified when the option for `Closing all tabs closes Brave` is OFF, used the STR from the description and no crash was observed.
