### ISSUE TITLE
Remove NTP images on Android 4/5/6

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2346]
## Description 
Remove NTP images on Android 4/5/6

## Steps to reproduce 

   1. Update to 1.6.0 on Android 4/5/6
   2. No NTP image should be shown
   3. No settings option as well

## Expected result
No NTP image or settings

cc: @GeetaSarvadnya @LaurenWags

**Comment by deeppandya** [comment]
Fixed by : https://github.com/brave/browser-android-tabs/pull/2345

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.6.0 rc4 BraveModernx86.apk
   - Verified no images on NTP using above build
   - Verified no setting to enable NTP images in Settings > Display
   - Verified crashes observed in #2343 and #2344 were not observed in this build
