### ISSUE TITLE
UI Glitch in Brave Ads settings

### ISSUE THREAD

**Issue by szaimen** [brave/browser-android-tabs#2352]
## Description 
UI Glitch in Brave Ads settings

## Steps to reproduce

   1. Open `chrome://rewards/ads-settings`
   2. Click on the dropdown menu for changing the Brave ads frequency

## Actual result 
UI Glitch:
![Screenshot_20191205-012445_Brave](https://user-images.githubusercontent.com/42591237/70193050-13ec9f00-16fe-11ea-88eb-03d1728fc852.png)

The glitch is, that it doesn't use the whole available space and I have to scroll down to see all options.

## Expected result
 The Glitch shoulsn't be there

## Issue reproduces how often

Easily reproduced

## Issue happens on 
1.6.0

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy S10e
   - Android version: Android 10
   
## Brave version
1.6.0  

### Additional information
Currently nothing

**Comment by srirambv** [comment]
This is not a glitch. This is as designed but yes could be improved with the native screen. The translated text causes it to overflow so it doesn't fit in the view.

**Comment by anthonypkeane** [comment]
Closing as this screen will be rebuilt
