### ISSUE TITLE
Image credit link should open in same tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2353]
## Description 
Image credit link should open in same tab

## Steps to reproduce 

   1. Open a new tab with image
   2. Click on the image credit
   3. A second tab is opened to load the landing page

## Actual result 
Image credit link opens in a second tab leaving new tab page as is

## Expected result
Should open the link in same tab similar to iOS

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: 7+
   
## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

More discussion here https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575513774228100

**Comment by anthonypkeane** [comment]
@jamesmudgett this isn't android behaviour as I understand. Can you pls comment on what you'd like here? Thanks

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.6.1 rc1 x64 build
- Verified clicking on image credit opens the landing page on the same tab
- Verified long-press on the image credit doesn't bring any context menu to open link a new tab
- Verified image credit is clickable on both landscape and portrait mode
- Verified image credit is shown on both enabled/disabled bottom bar and is clickable and opens the link in the same tab
-----
