### ISSUE TITLE
new tab page have EAFF E-1 ad，why?

### ISSUE THREAD

**Issue by ningsibuqu** [brave/browser-android-tabs#2361]
![0OX`$C~G@) D0VWS5$6UTT](https://user-images.githubusercontent.com/51028975/70623344-e3a28480-1c58-11ea-83f3-b884b342f0bf.png)

**Comment by kjozwiak** [comment]
@ningsibuqu you can some more info regarding the above via https://brave.com/brave-browser-selected-as-an-official-browser-for-the-2019-eaff-e-1-football-championship-in-south-korea.

If you want to disable the above, you can do so via the following:

* `Settings` -> `New Tab Page` and disable `Show Sponsored Images`
