### ISSUE TITLE
Implement Sponsored Images in New Tab Page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2363]
## Description 
Implement Sponsored Images in New Tab Page

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.4-rc1`
 - Verified NTP image and NTP-SI are shown as per the design
 - Verified different states of NTP-SI - All the states are working fine as mentioned in the design
 - Verified on clean install 2nd tab image is an NTP-SI, verified every 4th tab after that is an NTP-SI
 - Verified no crash when 10 empty tabs are opened in low-end devices
 - Verified no crash when switching theme when NTP-SI flag is enabled
 - Verified no NTP-SI are shown when show sponsored image switch is OFF
 - Verified `Turn On Rewards` modal notification is shown when rewards is OFF
 - Verified `Turn On Ads` modal notification is shown when rewards is OFF
 - Verified SI are not shown when `Hide SI` is clicked in NTP-SI banner
 - Verified all the above scenarios in clean and upgraded profile

**Comment by kjozwiak** [comment]
Going to label this as `QA Pass - Android Tab` as @srirambv basically went through the above as well. Thanks for the detailed verification @GeetaSarvadnya 👍 The entire QA team has gone through all the different states of NTP SI on several different devices throughout the last few days.
