### ISSUE TITLE
enabling sync crashes Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2369]
## Description 
Enabling Sync on 1.6.1 beta build shows 'Unfortunately, Brave has stopped' message.

## Steps to reproduce 

   1. Install 1.6.1 beta1 build
   2. Go to settings, navigate to sync, tap on Scan or enter sync code or Start a new sync chain.
   3. Brave crashes.

## Actual result 
![Screenshot_20191212-170437](https://user-images.githubusercontent.com/28145373/70752946-b0680000-1d01-11ea-96fc-f84e7e09065a.jpg)

## Expected result
No crash, should be able to join a sync chain.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.6.1 beta1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
cc @srirambv @btlechowski

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.6.1-beta.1 on Samsung s7 (Android 8.0).

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.6.1 rc1 x64 build
- Verified no crash when selecting sync option from menu
- Verified no crash when trying to join an existing a sync chain
- Verified no crash when trying to start a standalone sync chain
- Verified no crash after creating or joining a sync chain either 
- Verified no crash when bookmarks are sync'd between Desktop and Android
