### ISSUE TITLE
Open in new chrome tab ?

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-android-tabs#237]
Go-to settings -> about brave -> legal -> brave terms of service

A page will be load. Scroll down to see hyperlink. There will be one for Android hold it so can open in new tab (https://brave.com/android_privacy.html)
![screenshot_20170428-070917](https://cloud.githubusercontent.com/assets/3106852/25511020/ea1ac436-2be1-11e7-947e-c268c7b2f938.png)

You will see open in new chrome tab. May be we can change to open in tab of open in new brave tab.

**Comment by swarnava** [comment]
Couldn't reproduce anymore with latest Brave build 

![Brave latest](https://webcompat.com/uploads/2017/5/0bd286ca-e13a-4069-a5a0-dc825a6dea3b.jpg)
