### ISSUE TITLE
Browser crashes when trying to enable staging wallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2371]
## Description 
Browser crashes when trying to enable staging wallet

## Steps to reproduce 

   1. Clean install 1.6.1 
   2. Try to enable staging wallet
   3. Browser crashes and reloads to settings 

## Actual result 
Browser crashes when trying to enable staging wallet

## Expected result
No crash

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.6.1 beta 1 x64 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
This was fixed in the context of https://github.com/brave/browser-android-tabs/issues/2369

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.6.1 rc1 x64 build
- Verified enabling staging wallet doesn't cause any crash
- Verified able to create a staging wallet and able to claim grants
