### ISSUE TITLE
Unverified Channels Marked as Verified

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#2374]
## Description 
Some (at least one) channels that are not verified are displayed as verified. This is the case with twitter.com/btcandres and potentially others.

## Steps to reproduce 
1. Navigate to twitter.com/btcandres
2. Expand the Brave Rewards Shield

## Actual result 
![Screenshot_20191214-221739](https://user-images.githubusercontent.com/815158/70858099-8872cb00-1ec0-11ea-9e7f-29e945da8570.png)

## Expected result
The user states that they *are not* verified. Their account does not appear as verified on iOS or desktop.

## Issue reproduces how often 
Consistently

## Brave version
1.6.0

**Comment by srirambv** [comment]
@SergeyZhukovsky @anthonypkeane marking for 1.6.1 as this seems to be a serious bug based on the discussion in slack. Please move it out if you think otherwise

**Comment by SergeyZhukovsky** [comment]
I don't think we should block cr79 update as it's not a regression. More than that we should verify all of that not only on Twitter but on github and reddit as well. Probably Twitch should be included also.

**Comment by jonathansampson** [comment]
Another report on Twitter: https://twitter.com/LuisNil22/status/1208185877723254785

![image](https://user-images.githubusercontent.com/815158/71301288-d5dcb580-2362-11ea-902f-cfbdefd077d9.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarn1.6.3-rc1.apk
