### ISSUE TITLE
Chromium Incognito icon is shown on when a private tab is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2383]
## Description 
Chromium Incognito icon is shown on when a private tab is opened

## Steps to reproduce 

   1. Clean install 1.6.1 rc1 build
   2. Open a private tab
   3. Chromium icon is shown above tabs bar

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/71210476-f6c9db80-227a-11ea-89bb-520fa0fc3321.png)

## Expected result
Use Brave icon for private tab

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version:9.0 
   
## Brave version
1.6.1 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@srirambv it was suggested by @jamesmudgett to  show sunglass icon in private mode. @jamesmudgett can you verify this ?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A running 1.6.1 RC2 x64 build. 
- Verified no Chromium icon is used when a private tab is opened
