### ISSUE TITLE
Clicking on ad notification yields no action

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2388]
Clicking on ad notification yields not action

## Steps to reproduce 

   1. Trigger an ad (Example ad does not count)
   2. Tap on the ad notification

Note : The Brave example ad works as expected
Note: This is a regression introduced in 1.6.1
Note: Other notifications work.

## Actual result 
Nothing happens
Ad is not opened in Brave

## Expected result
Ad is opened in Brave

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 8.0.0
   
## Brave version
BraveModernarm v1.6.1-rc.2 on Samsung s7 (Android 8.0).

cc @brave/legacy_qa @SergeyZhukovsky @deeppandya @samartnik

**Comment by LaurenWags** [comment]
Reproduced on LG Nexus 5 with Android 5.1

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5.1.1 running bravemodernarm1.6.1.rc2.apk

**Comment by SergeyZhukovsky** [comment]
It is fixed here https://github.com/brave/brave-core/commit/27d507c583e8ae64650e2c2d7262f8b13849fa23

**Comment by srirambv** [comment]
Verificartion passed on Samsung Tab A with Android 9.0 running 1.6.1 RC3 x64 build
- Verified clicking an actual ad notification opens a new tab 
- Verified if browser is closed and notification is tapped, opens the browser and opens the landing page
- Verified in console that click and landed events are captured 
-----
