### ISSUE TITLE
Adding bottom adress bar

### ISSUE THREAD

**Issue by Morkowski** [brave/browser-android-tabs#2389]
## Description
I was using Windows Phone (and default mobile Edge browser) for really long time. It has cool feature I'm missing in other mobile browsers. Bottom adress bar. With bottom adress bar typing adresses with one hand was much easier. You don't need to move your thumb so far away to focus adress bar. I guess top adress bar works great in desktop browsers, but I don't understand why bottom adress bar is not a standard in all mobile browsers? Im not sure if any other mobile browser than mobile Edge/IE has bottom adress bar.

![Windows-phone-8 1](https://user-images.githubusercontent.com/12064267/71326191-d5c1ee80-24f7-11ea-94cb-f0a8874a5f35.jpg)

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/7511.
