### ISSUE TITLE
a-c notification shows 0.0 BAT 

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#2392]
## Steps to reproduce 

   1. Set staging env
   2. Enable rewards
   3. Claim grant
   4. Open `https://www.3zsistemi.si/` and wait till it is added to a-c table
   5. Trigger the a-c reconciliation.

## Actual result 
a-c notification shows 0.0 BAT
![Screenshot_20200131-224236_Brave](https://user-images.githubusercontent.com/34715963/71382845-0c703580-25da-11ea-9ee5-d5b676ca0448.jpg)

Note: The a-c goes through. The wallet balance was updated properly
![Screenshot_20200131-224329_Brave](https://user-images.githubusercontent.com/34715963/71382846-0c703580-25da-11ea-8353-ad3159c3c213.jpg)

## Expected result
a-c notification shows proper BAT

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version?not reproducible on 1.6.0, tested by @srirambv 
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):Phone
   - Android version: 8.0
   
## Brave version
BraveModernarm v1.6.1-rc.3 on Samsung s7 (Android 8.0).

cc @brave/legacy_qa @SergeyZhukovsky @deeppandya @samartnik

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/pull/2393

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm 1.6.1-rc4.apk
