### ISSUE TITLE
One-time tip amount is displayed as 0.0 BAT in Tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2394]
## Description 
One-time tip amount is displayed as 0.0 BAT in Tips panel

## Steps to reproduce 

   1. Staging environment
   2. Enable rewards and claim grants
   3. Send one-time tips to a verified pubs
   4. One-time tip amount is displayed as 0.0 BAT instead of 1.0 BAT in Tips panel
   5. Restart the browser and reload rewards page didn't fix the issue

Note: The issue is reproducible in both 1.6.1-rc2 and 1.6.1-rc3
## Actual result 
One-time tip amount is displayed as 0.0 BAT in Tips panel

![image](https://user-images.githubusercontent.com/38657976/71402045-ceaef380-2651-11ea-8647-74932ffd42dd.png)

## Expected result

![image](https://user-images.githubusercontent.com/38657976/71402010-b048f800-2651-11ea-9b23-f0544f99b9cf.png)

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3 
   - Android version: 5.1.1
   
## Brave version

1.6.1-rc3
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane @deeppandya

**Comment by SergeyZhukovsky** [comment]
done https://github.com/brave/browser-android-tabs/pull/2395

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm 1.6.1-rc4.apk
