### ISSUE TITLE
Translation missing for currency under reserved BAT text message

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2397]
## Description 
Translation missing for currency under reserved BAT text message

## Steps to reproduce 

   1. Clean profile staging env
   2. Join rewards and claim grants
   3. Send a one-time tip to unverified pubs
   4. Translation missing for currency in the rewards settings page

Note: The issue is reproducible in 1.6.1-rc2 and 1.6.1-rc3
## Actual result 
Translation missing for currency under reserved BAT text message

![image](https://user-images.githubusercontent.com/38657976/71416328-eef8a580-2685-11ea-8788-1fca989cbe2c.png)

## Expected result
![image](https://user-images.githubusercontent.com/38657976/71416472-907ff700-2686-11ea-97a8-8f7cfe437455.png)

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy j3
   - Android version: 5.1.1
   
## Brave version
1.6.1-rc4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky @deeppandya

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/pull/2398
https://github.com/brave/brave-ui/pull/553

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm 16.1-rc5.apk
