### ISSUE TITLE
Auto contributed value changed to `5000000000000000000.0` BAT in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2399]
## Description 
Auto contributed value changed to `5000000000000000000.0` BAT in an upgraded profile

## Steps to reproduce 

   1. Clean profile 1.6.0 staging env
   2. Perform auto contribution
   3. After auto contribution, verify that a-c value is displayed correctly in a-c notification in panel
   4. Don't close the a-c notification
   5. Upgrade profile to 1.6.1-rc5
   6. Click on a-c notification 

## Actual result 
Auto contributed value changed to `5000000000000000000.0` BAT in an upgraded profile

![image](https://user-images.githubusercontent.com/38657976/71424868-7bbe5600-26bc-11ea-84fe-2e48a8a2dc9d.png)

## Expected result
Auto contributed value shouldn't change after the upgrade

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.6.1-rc5
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky @deeppandya

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.6.1-rc5 on Samsung Galaxy Tab S5e (Android 9.0)

![Screenshot_20200130-220035_Brave](https://user-images.githubusercontent.com/34715963/71425066-1c028380-2699-11ea-97c3-47d20b2be41f.jpg)

**Comment by SergeyZhukovsky** [comment]
done https://github.com/brave/browser-android-tabs/pull/2400

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.6.1-rc6
