### ISSUE TITLE
Greek Language messed up after latest update.

### ISSUE THREAD

**Issue by giwrgosmant** [brave/browser-android-tabs#2404]
After latest update to version 1.6.1 Greek Language is messed up. Some words changed to English and some are on Greek.

![Screenshot_2019-12-31-00-44-44-412_com brave browser](https://user-images.githubusercontent.com/51835189/71603764-1d372300-2b67-11ea-9967-a7b72646a45c.jpg)
![Screenshot_2019-12-31-00-44-56-327_com brave browser](https://user-images.githubusercontent.com/51835189/71603776-24f6c780-2b67-11ea-98a8-e0249973a204.jpg)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/29d033556aba6ca97835c44867750f5175ba89ee

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm 1.6.2-rc1.apk
![Screenshot_2019-12-31-14-42-28](https://user-images.githubusercontent.com/38657976/71624194-51622080-2c07-11ea-93e9-ddca881f2f08.png)
![Screenshot_2019-12-31-14-42-48](https://user-images.githubusercontent.com/38657976/71624195-51622080-2c07-11ea-8b4c-24da6813ed69.png)
![Screenshot_2019-12-31-14-43-01](https://user-images.githubusercontent.com/38657976/71624197-51fab700-2c07-11ea-9abf-b46b8032c100.png)
![Screenshot_2019-12-31-14-43-28](https://user-images.githubusercontent.com/38657976/71624198-51fab700-2c07-11ea-9a4d-77b1de1050a7.png)
![Screenshot_2019-12-31-14-43-42](https://user-images.githubusercontent.com/38657976/71624199-51fab700-2c07-11ea-9e5f-880d38661079.png)
![Screenshot_2019-12-31-14-43-49](https://user-images.githubusercontent.com/38657976/71624201-52934d80-2c07-11ea-8d78-d8a279a19cbc.png)
![Screenshot_2019-12-31-14-44-50](https://user-images.githubusercontent.com/38657976/71624202-52934d80-2c07-11ea-8fea-cc48e491dc0d.png)
