### ISSUE TITLE
removing PWA, un-installs Brave

### ISSUE THREAD

**Issue by Bhupesh-V** [brave/browser-android-tabs#2416]
## Description 
Any PWA app while being uninstalled also uninstalls the whole Brave browser

## Steps to reproduce 

   1. Add any PWA to Home Screen (for e.g [https://v8.dev/](https://v8.dev/))
   2. Go to App Info of PWA
   3. Select Uninstall

## Actual result 
The whole browser gets uninstalled.

## Expected result
Only the PWA should be removed from the Home Screen.

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tenor G (by Amazon)
   - Android version: 8.1.0
   
## Brave version
1.6.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Would you be able to record the steps and share?

**Comment by Bhupesh-V** [comment]
Sorry for the late response, but I have recorded a [sample](https://drive.google.com/file/d/1iSUPoOKF3zfpvz0tNghkH0jfYwhtsj26/view?usp=sharing).
PS: ignore screen rotation :sweat_smile:

**Comment by mlhaufe** [comment]
I was bitten by this as well recently on a Galaxy S10. Notice from the context menu the confusion. One will uninstall the browser and one the PWA:

![Screenshot_20200316-141642_Microsoft Launcher](https://user-images.githubusercontent.com/826584/76792344-da154500-6790-11ea-9521-1b45a575f46e.jpg)

**Comment by szaimen** [comment]
I think this is the issue here: https://github.com/brave/brave-browser/issues/7357

**Comment by mlhaufe** [comment]
> I think this is the issue here: [brave/brave-browser#7357](https://github.com/brave/brave-browser/issues/7357)

Yes, that looks to me to be the underlying issue.
