### ISSUE TITLE
If sent from the background, the ads notifications should not make sound and pop up on the screen

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#2419]
Investigate is there a way to detect which app is in the foreground right now and don't show ads notification for navigation apps.

**Comment by anthonypkeane** [comment]
internal chat: https://bravesoftware.slack.com/archives/C43LW5U2H/p1578339801082100?thread_ts=1578333609.077400&cid=C43LW5U2H

**Comment by bbondy** [comment]
Thanks for linking the internal chat @anthonypkeane, it was helpful for context.

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.5.4rc2 BraveModernarm.apk
   - Enabled Rewards, browsed normally
   - put Brave in the background and opened up Google Maps
   - Brave Ad was served but no sound and ad did not show up on screen, it went right to notification tray
