### ISSUE TITLE
Tips not going through 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2420]
## Description 
Tips not going through as reported by multiple users in community https://community.brave.com/t/cant-send-tip-on-android/101036

## Steps to reproduce 
TBA

## Actual result 
Tips not going through

## Expected result
Tip successfully

## Issue reproduces how often 
:man_shrugging: 

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.6.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Desktop related issue https://github.com/brave/brave-browser/issues/7608
cc: @SergeyZhukovsky @gdregalo

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarn1.6.3-rc1.apk`
  - Verified in both clean and upgraded profile

**Comment by GeetaSarvadnya** [comment]
- Verification is in progress
**UGP Grants**
 - Verified one-time tips are processed successfully, able to see one-time tips in Tips panel, settings and in BR panel
- Verified monthly tips are processed successfully, able to see monthly tips in Tips panel, settings and BR panel.

**Ad Grants+UGP grants**

**Comment by gdregalo** [comment]
The resolution of the problem is based on the next PRs: 
https://github.com/brave/brave-browser/issues/6899;
https://github.com/brave/brave-core/pull/4342.
