### ISSUE TITLE
Support user profiles

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/browser-android-tabs#2422]

**Comment by srirambv** [comment]
Whats the use case for this on mobile?

**Comment by DaniellMesquita** [comment]
Same as in desktop.

As mobile have implemented multiwindow, this feature servers as a multi user space for web (your browsing data different than the data of your personal project).

**Comment by srirambv** [comment]
This probably is a good candidate for upstream. Don't think we will deviate from current behaviour. You can log an issue upstream for this at https://bugs.chromium.org/p/chromium/issues/list

Closing as won't fix. If upstream implements this we inherit it
