### ISSUE TITLE
Enable issues tab in Brave Core

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/browser-android-tabs#2424]

**Comment by srirambv** [comment]
Issue description is too vague. Please edit issue add details and reopen it

**Comment by DaniellMesquita** [comment]
Brave Core repo doesnt haves a issues tab.
Users cant refer to things which applies to both mobile and desktop versions.

**Comment by srirambv** [comment]
Brave core is only for PR's. Issues are to be logged in brave-browser(https://github.com/brave/brave-browser/issues) repo. For Desktop and Android use that repo to log issues but please add details while logging issue. Just title wont help. For iOS use https://github.com/brave/brave-ios/issues repo to log issues
