### ISSUE TITLE
(mobile/desktop) CryptoWallets import from MetaMask

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/browser-android-tabs#2426]
Not only manually (seed/key) but also automatically from extension data.

**Comment by srirambv** [comment]
Closing in favour of #2423

**Comment by DaniellMesquita** [comment]
They arent the same issue. Thats why I asked to enable issues tab in Brave Core.

My suggestion for Brave Desktop is to enable users to import MetaMask data directly from extension data.
