### ISSUE TITLE
Contribution flow is triggered multiple times. 

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2432]
This fix has been applied to brave-core's `master`  and cherry-picked into `android_79v2` for release 1.6.3. We need to test if the issue is resolved and works properly on Android browser.

Original issue: https://github.com/brave/brave-browser/issues/7201.
PR: https://github.com/brave/brave-core/pull/4132

Original issue: https://github.com/brave/brave-browser/issues/7579.
PR: https://github.com/brave/brave-core/pull/4303

Slack discussion: https://bravesoftware.slack.com/archives/C0816QH3R/p1578513878022000

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.6.3-rc1.apk`
   - Confirmed AC, One-time tip and monthly tips processed as expected in staging environment contributed as expected (wallet balance decreased accordingly, tips were recorded in wallet panel on brave://rewards)
