### ISSUE TITLE
Brave is not fit screen

### ISSUE THREAD

**Issue by BlackHat26** [brave/browser-android-tabs#244]
As U see, I have 2 screen, but browser is not fit when I full screen (the red part) . My resolution of 2 screen is 1920x1080.

![untitled](https://cloud.githubusercontent.com/assets/15937173/25779126/a2b74af2-32c5-11e7-8418-6fc7905b1d5f.png)

**Comment by SergeyZhukovsky** [comment]
@BlackHat26 it is a repository for Android browser only. Use that link https://github.com/brave/browser-laptop for a laptop version.
