### ISSUE TITLE
Do not force landscape in fullscreen

### ISSUE THREAD

**Issue by edouardmercier** [brave/browser-android-tabs#2441]
##  Description
When switching to fullscreen, the orientation is automatically switched to landscape mode, which is fine most of the time when it comes to watch a video, but is not the expected behavior when displaying in fullscreen a portrait image, for instance.

## Steps to reproduce

   1. Open a web page which contains a button on which a JavaScript callback is set ;
   2. Implement this callback function so as to open an HTML element in fullscreen via the `requestFullscreen()` method (https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen)
   
## Actual result
The browser actually switches to the fullscreen experience, but systematically in landscape orientation.

## Expected result
The browser should switch to fullscreen but in portrait mode, by default.

## Issue happens on
   - Current Play Store version? yes
   - Beta build? no

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Android OnePlus A5010
   - Android version: OxygenOS v9.0.9
   
## Brave version
v5.22.21.00051

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? yes
- Is the issue reproducible on the latest version of Chrome? no

### Additional information
The W3C behavior when switching to fullscreen is to keep the current device orientation.

**Comment by srirambv** [comment]
Do you have a sample link where you see this happen for images as mentioned in description? Also you mentioned it doesn't happen on Chrome so am curious to know what is changed. Btw are you sure about the Brave version? We don't have that version.

**Comment by edouardmercier** [comment]
Thank you for answering this bug report, @srirambv. I am deeply sorry and stupid to have reported a bug which is non existent, since I addressed it to the wrong Internet browser project. I wish you lots of energy for keeping up the development of Brave.
