### ISSUE TITLE
Fixes unable to get ad tokens if tokens are not ready :: Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2448]
## Description 
Desktop Issue: https://github.com/brave/brave-core/pull/4334

Please cherry pick the fix for this milestone

**Comment by kjozwiak** [comment]
Quick QA notes:

We'll need to make sure that ads are generally working. https://github.com/brave/brave-core/pull/4334#issuecomment-574262938 is an example of the cases that were used when checking the PR on Nightly before it was uplifted. QA will also go through the following manual passes which should basically cover this issue:

* Manual test run on Android ARM for 1.7.0 #2453 - https://github.com/brave/browser-android-tabs/issues/2453
* Manual test run on Android Tab for 1.7.0 #2455 - https://github.com/brave/browser-android-tabs/issues/2455
