### ISSUE TITLE
Improving history window

### ISSUE THREAD

**Issue by marcinwiacek** [brave/browser-android-tabs#2459]
Something what could be potentially interesting:

https://chromium-review.googlesource.com/c/chromium/src/+/1608741

Google didn't want it because of schedule, etc., but code is in fact ready and should have good quality. I will appreciate if you could mention my name in commit info, when will incorporate.

**Comment by srirambv** [comment]
Upstream implementations are auto inherited when we get the Chromium bumps. We don't explicitly pull specific changes that aren't in the code yet. We will wait for upstream changes to flow in during Chromium upgrades.
