### ISSUE TITLE
Site is wrongly reported "connection is not private"

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#2476]
Looks not equal, but somewhere around the https://github.com/brave/browser-android-tabs/issues/2126 .

## Description 
On Android 4.4  https://hotline.ua is reported as `Your connection is not private`. In the same time Chrome and Brave-core Android allows load it without any warning confirming certificate verification.

## Steps to reproduce 

   1. Take device with Android 4.4
   2. Open https://hotline.ua

## Actual result 
![Screenshot_2020-01-24-09-26-27](https://user-images.githubusercontent.com/24739341/73051734-08ab2980-3e8c-11ea-828b-8fb9a9c70fce.png)
![Screenshot_2020-01-24-09-31-27](https://user-images.githubusercontent.com/24739341/73051896-79eadc80-3e8c-11ea-95ee-a9a47f0da869.png)

## Expected result
How it looks on Brave-core Android or Chrome:
![Screenshot_2020-01-24-09-33-39](https://user-images.githubusercontent.com/24739341/73052025-c9c9a380-3e8c-11ea-8c80-5eacc1af46c3.png)

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 4.4.4
   
## Brave version
Brave version 1.5.3, Chromium 79.0.3945.136

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Closing as this is fixed on core. @jumde  please reopen the issue if this needs to be fixed on tabs right away?
