### ISSUE TITLE
Brand string Chromium in certificate information

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#2477]
Yes

Found when looked on https://github.com/brave/browser-android-tabs/issues/2476

## Description 
There is missed Chromium brand string instead of Brave

## Steps to reproduce 

   1. Open google.com
   2. Press the lock icon on the left of url bar
   3. Click details

## Actual result 
![Screenshot_2020-01-24-09-49-21](https://user-images.githubusercontent.com/24739341/73053000-49587200-3e8f-11ea-8479-fb2e224e01be.png)

## Expected result
How it looks in Brave-core Android
![Screenshot_2020-01-24-09-50-39](https://user-images.githubusercontent.com/24739341/73053022-56756100-3e8f-11ea-96d1-f09bdf564183.png)

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? No

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet/phone
   - Android version: 4.4.4/8.0
   
## Brave version
1.5.3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Closing as its fixed in core. We can open an issue on core if it breaks
