### ISSUE TITLE
Download manager enhancement

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#248]
1.add feature to see file size
2.speed of downloading files
3.add feature see how much downloaded
4.add feature to share link of the file

**Comment by Brave-Matt** [comment]
@jamesmudgett @anthonypkeane -- Is there any particular reason we're not allowing users to change the location of their downloaded files? The option to do so is there, but you can't actually change the location.

**Comment by deeppandya** [comment]
@Brave-Matt we have **Ask where to save files** option inside **Downloads** settings option. If user has enabled this option, it would ask you to confirm the download location. User can select different location when he/she tries to download something.

**Comment by anthonypkeane** [comment]
Closing as Chrome provide some of this right now.
