### ISSUE TITLE
Sponsored image onboarding modal should not be shown if NTP images are disabled before upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2483]
## Description 
Sponsored image onboarding modal should not be shown if NTP images are disabled before upgrade

## Steps to reproduce 

   1. Install older build and disable ntp images
   2. Upgrade to build with sponsored images
   3. Open a new tab, shows onboarding modal without background image

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73184973-4063dc80-40eb-11ea-9d5b-93f55301754a.png)
Sponsored image setting in NTP is enabled but greyed out because background images are disabled

## Expected result
No message if images are disabled

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.7.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Clicking learn more in the above modal shows this message
![image](https://user-images.githubusercontent.com/17010094/73187104-db11ea80-40ee-11ea-8fd8-7f6ab2f1648a.png)

**Comment by srirambv** [comment]
Scroll bar appears on the bottom left corner when the modal is closed 
![image](https://user-images.githubusercontent.com/17010094/73187411-5c697d00-40ef-11ea-8efc-7a1433e48ce0.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.4 build shared on slack
- Verified disabling NTP images on older build and updating to new build doesn't show onboarding modal 
- Verified no scroll bar is shown NTP without NTP images.

**Comment by GeetaSarvadnya** [comment]
Can't test as low-end device - Samsung Galaxy J3 version 5.1.1 don't have an NTP option in Display settings
