### ISSUE TITLE
Stats and top tiles should not be right aligned when images are disabled on landscape mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2485]
## Description 
Stats and top tiles should not be right aligned when images are disabled on landscape mode

## Steps to reproduce 

   1. Install 1.7.1
   2. Disable background images for NTP
   3. Change orientation to landscape

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73194381-1fef4e80-40fa-11ea-849c-f5c0c08fad27.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/73194589-6b096180-40fa-11ea-9375-57b1cdc30ee2.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.7.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by kjozwiak** [comment]
Looks like this one has been fixed by https://github.com/brave/browser-android-tabs/releases/tag/untagged-8d6ca0facd3e0f001d44.

**Comment by kjozwiak** [comment]
Verification **PASSED** on` Samsung S10+` using `Android 10` running `1.5.4 CR: 79.0.3945.136` using the build mentioned via https://github.com/brave/browser-android-tabs/releases/tag/untagged-8d6ca0facd3e0f001d44.

![Screenshot_20200130-012910_Brave](https://user-images.githubusercontent.com/2602313/73425687-61514b00-4300-11ea-8163-b0f25d97d97a.jpg)

![Screenshot_20200130-012933_Brave](https://user-images.githubusercontent.com/2602313/73425688-61514b00-4300-11ea-8eb4-b6c2a3993733.jpg)

Verification **PASSED** on` Pixel 2 XL` using `Android 10` running `1.5.4 CR: 79.0.3945.136` using the build mentioned via https://github.com/brave/browser-android-tabs/releases/tag/untagged-8d6ca0facd3e0f001d44.

![Screenshot_20200130-013548](https://user-images.githubusercontent.com/2602313/73425885-f2c0bd00-4300-11ea-902f-87ba2ffb99eb.png)

![Screenshot_20200130-013556](https://user-images.githubusercontent.com/2602313/73425886-f2c0bd00-4300-11ea-88b4-ef9c7b29890d.png)
