### ISSUE TITLE
sponsored images should appear on first launch rather than on the second run

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2489]
## Description 

Sponsored images on Android are only appearing on the second run rather than appearing once the user installs or updates Brave. We should follow the implementation that iOS is using in terms of showing SNTP without needing to restart Brave.

If a user updates/installs Brave, they won't see any sponsored images until they restart the application which might take a few days/weeks. Personally, I almost never restart my application and always leave it running in the background. In this case, I wouldn't see a sponsored images for months.

## Steps to reproduce 

   1. install the latest version of Android that supports SNTP
   2. once installed, notice that you'll never get a sponsored image to appear
   3. relaunch/restart Brave (2nd run)
   4. you'll notice that that you'll start seeing sponsored images

## Actual result 

Users require to run Brave the second time to start seeing sponsored images. This is problematic for users who always leave their browsers running in the background.

## Expected result

Users should see sponsored images once they've either updated or installed Brave without needing to restart the browser.

## Issue reproduces how often 

100% reproducible using the above STR.

## Issue happens on 

   - Current Play Store version? `N/A` (Sponsored images not released)
   - Beta build? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* latest build that includes SNTP

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @mandar-brave @deeppandya @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by kjozwiak** [comment]
This is still reproducible and still needs to be addressed. You'll need to restart Brave once installed/upgraded to see NTP SI images as per https://github.com/brave/browser-android-tabs/issues/2489#issue-556717353.

Using https://github.com/brave/browser-android-tabs/releases/tag/untagged-8d6ca0facd3e0f001d44 on a `Samsung S10+` running `Android 10`.

**Comment by srirambv** [comment]
Behaviour needs to be changed for clean installs. Or user should be informed via in-app dialog to manually restart. During upgrades playstore removes app from memory and relaunches so there is a quit and restart done behind the scenes. 

I'd suggest moving this over to brave-browser and implemented on Android-core

**Comment by LaurenWags** [comment]
Reproduces on Asus Zenfone (x86) with Android 6.0.

**Comment by GeetaSarvadnya** [comment]
Reproduced on Samsung Galaxy J3 version 5.1.1

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` using `Android 10` running `1.5.4 CR: 79.0.3945.136` via the `Brave_aligned.apk` from Slack.

* ensured that NTP SI assets are being displayed after updating from `1.5.3 CR:79.0.3945.136` to `1.5.4 CR: 79.0.3945.136` without needing to restart the application
  * ensured that the second tab opened after the upgrade is a NTP SI
  * ensured that NTP SI appears on every fourth tab
* ensured that NTP SI assets are being displayed after on a clean install without needed to restart
  * ensured that the second tab opened after the upgrade is a NTP SI
  * ensured that NTP SI appears on every fourth tab
