### ISSUE TITLE
Bookmarks under folder doesn't get synced

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#249]
Steps to reproduce

1.  Add a bookmark on Android device and move it under folder
2. Enable Sync on Laptop 
3. Sync Android with Laptop
4. Add a bookmark on laptop after enabling sync
5. Wait for the bookmark to be sync'd on Android and folder to laptop
6. Bookmark is missing under folder in Laptop, Android receives the bookmark added in step 4

**Comment by SergeyZhukovsky** [comment]
It works in the latest version.
