### ISSUE TITLE
`Turn on Rewards` notification modal is shown even though the reward is already enabled in the onboarding flow

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2495]
## Description 
`Turn on Rewards` notification modal is shown even though the reward is already enabled in the onboarding flow

## Steps to reproduce 

   1. Clean profile 1.5.4
   2. Enable rewards through the onboarding flow
   3. Exit the browser as soon as 1st tab is opened
   4. Relaunch the browser
   5. Open a new tab from the Hamburger menu until NTP-SI is shown
   6. `Turn on Rewards` notification modal is shown in the 1st NTP- SI 

## Actual result 
`Turn on Rewards` notification modal is shown even though the reward is already enabled in the onboarding flow

## Expected result
`Turn on Rewards` notification modal should not be shown

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @mandar-brave @anthonypkeane

**Comment by mandar-brave** [comment]
Ok to fix later release; not a blocker.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.4 build shared via slack
- Verified no rewards modal is shown on first NTP-SI or a normal tab after relaunch if rewards was enabled before exit
- Verified turn on rewards modal is shown after relaunch on NTP-SI if the app is quit before rewards is enabled via onboarding
