### ISSUE TITLE
`Turn on Brave Ads` modal notification is shown after enabling rewards from onboarding flow

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2496]
## Description 
`Turn on Brave Ads` modal notification is shown after enabling rewards from onboarding flow

## Steps to reproduce 

   1. Clean profile 1.5.4
   2. Enable rewards through the onboarding flow
   3. Exit the browser as soon as 1st tab is opened
   4. Relaunch the browser
   5. `Turn on Brave Ads` notification modal is shown in the 1st tab
   
## Actual result 

`Turn on Brave Ads` modal notification is shown after enabling rewards from onboarding flow
## Expected result
`Turn on Brave Ads` modal notification shouldn't be shown after enabling rewards from onboarding flow

## Issue reproduces how often 
80 % Reproducible

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @mandar-brave @anthonypkeane

**Comment by mandar-brave** [comment]
@anthonypkeane assume this is an onboarding flow flag issue? Unclear if related to NTP.

**Comment by kjozwiak** [comment]
@deeppandya I managed to reproduce this once on `1.5.4 CR: 79.0.3945.136 RC`. It's pretty hard to reproduce but still happening. Did this fix make it into https://github.com/brave/browser-android-tabs/releases/tag/v1.5.4-rc.1?

@GeetaSarvadnya can you still reproduce this with https://github.com/brave/browser-android-tabs/releases/tag/v1.5.4-rc.1?

**Comment by deeppandya** [comment]
@kjozwiak that's exactly what I would do. We just need to make sure if ads is enabled and if we still see the modal then it's an issue.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.4 build shared via slack
- Verified `Turn on Brave ads` modal is not shown on NTP if there is enough time given between quit and relaunch and ads is enabled in rewards page
- Verified `Turn on Brave ads` message is shown if ads is not enabled after relaunch which is expected
