### ISSUE TITLE
NTP backgrounds on older Android devices cause UI delays

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2497]
## Description 
When opening new tabs with background images (regular or sponsored) on an older Android device the following happens:

a. when opening new tab from `+`:
   - new tab opens with image, but URL bar isn't shown and bottom nav bar doesn't have buttons, after 1-1.5 s the URL bar is shown and the nav bar gets controls/buttons.

b. when opening new tab from hamburger menu:
   - white tab appears for 1-1.5s before background image displays

This doesn't provide the best user experience since the new tab doesn't appear smoothly, however, users still have the option to toggle background images off if they wish.

## Steps to reproduce 

   1. Have an older Android device
   2. Download build with background images
   3. Open new tabs from + or hamburger menu

## Actual result 
see UI delays - ask me for video

## Expected result
no UI delays

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): all
   - Android version: 5, 6
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

Per Sri/Deep discussion this is related to the bitmap being loaded on lower end devices.

cc @srirambv @anthonypkeane @mandar-brave @deeppandya @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in Samsung Galaxy J3 version 5.1.1

**Comment by srirambv** [comment]
I see similar behaviour on Samsung Tab A opening a new tab with SI and non-SI images there is a momentary hang. The transition isn't smooth as it should be

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.4rc1 BraveModernx86.apk
   - Still experiencing issue as described on this device, logged follow up issue #2512
