### ISSUE TITLE
NTP goes blank when reloading empty page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2498]
## Description 
NTP goes blank when reloading empty page

## Steps to reproduce 

   1. Install 1.5.4
   2.  Open a new tab wait for image to load
   3. Reload the page, image is removed and goes blank
   4. Change in tab focus or app focus or orientation change brings back the tab image

## Actual result 
NTP goes blank when reloading empty page

## Expected result
Image should not be removed if the page is loaded

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
When I refresh the empty tab, I am getting the below tab forever it won't show all the controls even after 10 mins.

![image](https://user-images.githubusercontent.com/38657976/73553749-7947dc80-4470-11ea-96e6-3fa61e157a28.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android` using `1.5.4 CR: 79.0.3945.136`:

* Verified the STR outline under https://github.com/brave/browser-android-tabs/issues/2498#issue-558191292
* Verified that refreshing several none-NTP SI tabs worked as expected (no blanking)
  * ensured that changing between `landscape` & `portrait` worked as expected (no blanking)
* Verified that refreshing several NTP SI tabs worked as expected (no blanking)
  * ensured that changing between `landscape` & `portrait` worked as expected (no blanking)
* Verified that refreshing `chrome://newtab` when `Show Background Images` is disabled didn't cause any issues
