### ISSUE TITLE
Brave crashes after tab 15 no matter tab is NTP or NTP-SI

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2499]
## Description 
Brave crashes after tab 15 no matter tab is NTP or NTP-SI

## Steps to reproduce 
Scenario 1: Brave crashes at tab 15
   1. Clean profile 1.5.4
   2. Enable rewards through the onboarding flow
   3. Exit the browser by selecting exit option from Hamburger menu
   4. Relaunch browser
   5. Open 15 tabs by clicking on `+` from the bottom toolbar
   6. Brave crashes when 15th tab is opened
   
Scenario 1: Brave crashes at tab 16
   1. Clean profile 1.5.4
   2. Enable rewards through the onboarding flow
   3. Exit the browser by selecting exit option from Hamburger menu
   4. Relaunch browser
   5. Open 16 tabs by selecting `New tab` from the hamburger menu
   6. Brave crashes when 16th tab is opened
   

## Actual result 
Brave crashes after tab 15 no matter tab is NTP or NTP-SI

## Expected result
Should not be any crash

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @mandar-brave @anthonypkeane

**Comment by anthonypkeane** [comment]
We talked about a possible solution @deeppandya on the triage call for this, auto focusing on any current open NTP and thereby limiting the number of NTP's to 1. 
Would this solve the issue?
cc @jamesmudgett

**Comment by mandar-brave** [comment]
Agreed this is a known issue and discussed.
Ok to fix further down the release cycle

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.4rc1 BraveModernx86.apk
Scenario 1:
   - Opened 10 new tabs (no sites, just the new tabs)
   - Confirmed no crashes and after 10 new tabs without sites I was not able to open any more new tabs (as expected)
Scenario 2:
   - Opened 10 different sites in 10 tabs
   - Opened 11th tab, it had a background image. Opened a site in this tab.
   - Opened 12th tab, no background image. Opened a site in this tab.
   - Additional new tabs do not have background image. Confirmed with @deeppandya that this is expected.
