### ISSUE TITLE
Optionally Allow Screenshots of Private Tabs

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#2501]
[`FLAG_SECURE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE) prevents screenshots of the application window (as well as broadcasting to a non-secure display). Sensibly, we use this flag for Private Tabs. That said, some users would like to take screenshots of private tabs.
https://github.com/brave/browser-android-tabs/blob/45d76ff5280dc7125d47d9e6461f283c47cb6db1/chrome/android/java/src/org/chromium/chrome/browser/incognito/IncognitoTabSnapshotController.java#L68-L84

We could, perhaps, offer the option to allow screenshots for the Private Browsing Session, clearing user-consent when the private tab closes (requiring them to consent again for the next tab).

**Comment by srirambv** [comment]
closing in favour of https://github.com/brave/brave-browser/issues/7485 which needs to be done on Android-core
