### ISSUE TITLE
Follow up of #2498 - NTP goes blank when reloading empty page on low end devices

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2510]
## Description 

NTP goes blank when reloading empty page
## Steps to reproduce 

  1. Install 1.5.4-rc1
  2. Open a new tab wait for image to load
  3. Reload the page, image is removed and goes blank
  4. Change in tab focus or app focus or orientation change brings back the tab image

**Note**: Please note this issue is happening only in low-end devices

## Actual result 
NTP goes blank when reloading empty page

## Expected result
The image should not be removed if the page is loaded

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4-rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @mandar-brave @deeppandya

**Comment by deeppandya** [comment]
Fixed

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running build which is shared via slack

**Comment by kjozwiak** [comment]
Wasn't checked on `Tablet` due to QA not having a low end tablet. Hence `QA Pass - Android Tab` not being added.
