### ISSUE TITLE
"Turn on Brave Ads" modal needs to be full width in portrait & text/strings should be aligned correctly

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2513]
## Description 

The current `Turn on Brave Ads` modal isn't full width while in portrait and the text/strings are not aligned correctly.

## Steps to reproduce 

   1.  download & install the latest `1.5.4 CR: 79.0.3945.136` (RC1 in this case)
   2. skip the onboarding process
   3. enable NTP SI so it's pointing to `Dev` (restart the browser)
   4. enable `Rewards` and ensure you disable `Ads` via the rewards panel
   5. open a NTP and you should see the `Turn on Brave Ads` NTP SI modal

## Actual result 

![Screenshot_20200205-163932_Brave](https://user-images.githubusercontent.com/2602313/73887460-9b0ede00-4839-11ea-908c-a2e5c569e0ac.jpg)

## Expected result

Current modal should look the same as the specification (full width/text aligned)

<img width="384" alt="Screen Shot 2020-02-05 at 5 05 19 PM" src="https://user-images.githubusercontent.com/2602313/73887520-b7ab1600-4839-11ea-91ca-0232960a1562.png">

## Issue reproduces how often 

100% reproducible using the above STR.

## Issue happens on 
 
   - Current Play Store version? `N/A` (feature not released)
   - Beta build? `Yes, reproducible using 1.5.4 CR: 79.0.3945.136`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* Using `1.5.4 CR: 79.0.3945.136`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @srirambv @deeppandya @anthonypkeane @mandar-brave

**Comment by deeppandya** [comment]
Fixed

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` using `Android 10` running `1.5.4 CR: 79.0.3945.136` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.4-rc.2.

* Verified the STR outlined via https://github.com/brave/browser-android-tabs/issues/2513#issue-560660109

![Screenshot_20200206-144510_Brave](https://user-images.githubusercontent.com/2602313/73972875-8b51d100-48ef-11ea-9a1d-1405b54717ec.jpg)
![Screenshot_20200206-144520_Brave](https://user-images.githubusercontent.com/2602313/73972881-8ee55800-48ef-11ea-9ccd-3f583160149f.jpg)
