### ISSUE TITLE
both "Brave Rewards" NTP SI modals need to be full width in portrait

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#2514]
## Description 

As per the specification, the `Brave Rewards` modal under NTP SI needs to be the entire width of the device while in portrait mode.

## Steps to reproduce 

   1.  download & install the latest `1.5.4 CR: 79.0.3945.136` (RC1 in this case)
   2. skip the onboarding process
   3. enable `NTP SI` so it's pointing to `Dev` (restart the browser)
   4. open three tabs for the next one lined up is a NTP SI
   4. enable `Rewards` on the third tab
   5. open a NTP and you should see the `Brave Rewards` NTP SI modal

## Actual result 

![Screenshot_20200205-200257_Brave](https://user-images.githubusercontent.com/2602313/73897242-73c50a80-4853-11ea-8395-470dc8710c07.jpg)

![Screenshot_20200205-174512_Brave](https://user-images.githubusercontent.com/2602313/73897249-76bffb00-4853-11ea-9335-f4fc68c86a5a.jpg)

## Expected result

<img width="467" alt="Screen Shot 2020-02-05 at 8 08 44 PM" src="https://user-images.githubusercontent.com/2602313/73897211-542de200-4853-11ea-8155-e18e11118978.png">

## Issue reproduces how often 

100% reproducible when using the above STR.

## Issue happens on 

   - Current Play Store version? `N/A` (feature not released)
   - Beta build? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* Using `1.5.4 CR: 79.0.3945.136 (RC1)`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @deeppandya @srirambv @anthonypkeane @mandar-brave

**Comment by deeppandya** [comment]
Fixed

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` using `Android 10` running `1.5.4 CR: 79.0.3945.136` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.4-rc.2.

* Verified the STR outlined via https://github.com/brave/browser-android-tabs/issues/2514#issue-560720208

![Screenshot_20200206-141920_Brave](https://user-images.githubusercontent.com/2602313/73971632-3ca33780-48ed-11ea-9f75-298d801ffcde.jpg)

![Screenshot_20200206-141928_Brave](https://user-images.githubusercontent.com/2602313/73971625-3a40dd80-48ed-11ea-8d86-08a74ffd4cc3.jpg)

![Screenshot_20200206-142939_Brave](https://user-images.githubusercontent.com/2602313/73971700-56dd1580-48ed-11ea-98c8-d4c157f7f682.jpg)
