### ISSUE TITLE
Enable ads modal popup is shown for Ads unsupported region 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2519]
## Description 
Enable ads modal popup is shown for Ads unsupported region 

## Steps to reproduce 

   1. Set device locale to ads not supported region e.g `Latvia` 
   2. Clean profile 1.5.4-rc1
   3. Enable rewards through the onboarding flow
   4. Navigate to Brave://rewards - `Sorry! ads not supported` message is shown in Ads panel
   5. Open a new tab
   6. Enable ads modal popup is shown for Ads unsupported region 

## Actual result 
Enable ads modal popup is shown for Ads unsupported region 

![Screenshot_2020-02-06-15-19-07](https://user-images.githubusercontent.com/38657976/73932560-9c570e00-4900-11ea-9188-9a984fd444af.png)

![Screenshot_2020-02-06-15-24-16](https://user-images.githubusercontent.com/38657976/73932563-9e20d180-4900-11ea-83d1-6a718498202d.png)

## Expected result
Enable ads modal popup shouldn't be shown for Ads unsupported region 

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4-rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mandar-brave @anthonypkeane @deeppandya

**Comment by deeppandya** [comment]
Fixed

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.4 local build shared on slack
- Verified ads message is not shown on NTP after upgrade 
- Verified ads message is not shown on clean install install
