### ISSUE TITLE
Renaming folder name on Android doesn't get sync'd on Laptop

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#252]
## Steps to reproduce

1. Enable Sync on Laptop and Sync an Android device
2. Import bookmark from a html file on Laptop
3. Wait for the folder to be sync'd on Android (Took six mins to sync 100 bookmarks within 6 folders)
4. Edit the mail folder name on Android device
5. Changes not sync'd on Laptop even after 30 mins

**Comment by SergeyZhukovsky** [comment]
That's fixed.
