### ISSUE TITLE
Old enable rewards modal popup is shown in an upgraded profile for ads unsupported region

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2520]
## Description 
Old enable rewards modal popup is shown in an upgraded profile for ads unsupported region

## Steps to reproduce 

   1. Set device language to ads unsupported region (e.g Latvia)
   2. Clean profile 1.5.3 (GPS version)
   3. Enable rewards via onboarding
   4. Upgrade to 1.5.4 
   5. Old enable rewards modal popup is shown

## Actual result 
Old enable rewards modal popup is shown in an upgraded profile for ads unsupported region
![Screenshot_2020-02-06-20-46-54](https://user-images.githubusercontent.com/38657976/73951114-139d9980-4923-11ea-98ec-f5f16d962a55.png)

## Expected result
Should not be any modal popups

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.5.4
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @mandar-brave @anthonypkeane @deeppandya

**Comment by deeppandya** [comment]
Fixed

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running 1.5.4 local build shared on slack

Verified old enable rewards modal popup is not shown on NTP after upgrade
Verified old enable rewards modal popup is not shown on clean install
