### ISSUE TITLE
Change the referrer API

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2528]
We need to change the referrer API, since current one will be deprecated on March 1.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.7.apk-RC4`
![image](https://user-images.githubusercontent.com/38657976/75375131-80d59680-58f3-11ea-8bcd-1d9ed8339772.png)
![image](https://user-images.githubusercontent.com/38657976/75375170-921ea300-58f3-11ea-85b0-1329cc275690.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.7 RC4 x64 build
- For non referrer landing pageshttps://bravesoftware.slack.com/archives/C0816QH3R/p1582739818036900?thread_ts=1582739295.035600&cid=C0816QH3R
- For referrer landing pagehttps://bravesoftware.slack.com/archives/C0816QH3R/p1582741331040000?thread_ts=1582739295.035600&cid=C0816QH3R
