### ISSUE TITLE
Hot fix for 1.5.5

### ISSUE THREAD

**Issue by deeppandya** [brave/browser-android-tabs#2533]
## Description 

- Add bottom gradient on NTP for better visibility of the sponsored logo
- Update size of the sponsored logo
- Update centerpoint for NTP images calculation
- Remove normal background images and sponsored images for devices lower than android 5.
- Remove settings option for New Tab Page for devices lower than android 5.

**Comment by kjozwiak** [comment]
@deeppandya can we get some examples of the new changes? It might be a bit hard for QA to double check any of these if they're subtle and hard to notice. Having some examples would be really helpful 👍

**Comment by deeppandya** [comment]
@kjozwiak  Test plan :
1. I have a bottom gradient so that the sponsored logo should look more clear. if you notice that it's not clear enough, you can create an issue.
2. In the previous build, we had sponsored logo with size 130X130. in this build it's updated to 170X170. so you can verify that. 
3. It's hard to verify as it's the change in calculation. if you notice anything weird in BG images, you should report that. 
4 & 5 we decided to remove background images and sponsored images from the devices lower than android 5. i have a an honour device with android 4.4.4 and i have verified that we don't have any bg images or sponsored images in the app on this device and also verified that the option for NewTabPage is not visible for this device.

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.5.5-rc1 on Samsung Galaxy Tab S5e (Android 9.0)
Verified Sponsored logo looks clear.
Verified Sponsored logo is bigger

Old logo size:
![Screenshot_20200211-224909_Brave](https://user-images.githubusercontent.com/34715963/74282810-0fa5b900-4d21-11ea-8a78-a8f6e7ef6cad.jpg)
New logo size:
![Screenshot_20200211-220415_Brave](https://user-images.githubusercontent.com/34715963/74282839-21875c00-4d21-11ea-927a-771e4ef86a6c.jpg)
