### ISSUE TITLE
Malformed rewards link

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2534]
From @jonathansampson we have malformed address listed for rewards

![Screenshot_20200206-220918.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/fac6dc3e-bc03-44cc-b279-e41920492cb8)

**Comment by srirambv** [comment]
fixed by  #2531

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` with `Android 10` using `1.5.5 CR: 79.0.3945.13` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.5-RC-1:

* ensured that `chrome://rewards` is being displayed under `chrome://about`
* ensured that clicking on `chrome://rewards` via `chrome://about` opens the `Rewards` page
* ensure using `chrome://rewards` via URL correct loads the `Rewards` page
* ensured that you can enable Rewards/Ads via the onboarding process
* ensured that you can enable Rewards/Ads via the `Rewards` panel
