### ISSUE TITLE
Reset and Resync doesn't show the device name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#254]
## Steps to reproduce

1. Setup sync on Laptop
2. Sync Android Device without providing a name and ensure the device name is shown on laptop
3. Reset Sync on Android
4. Sync again with the same laptop profile without providing a device name, Device gets listed by device name is not shown 
![image](https://cloud.githubusercontent.com/assets/17010094/26201626/d8a30692-3bcb-11e7-91d4-ac7d59e34af9.png)

**Comment by SergeyZhukovsky** [comment]
That is fixed in the latest beta

**Comment by srirambv** [comment]
Verified on latest beta. Closing #254
