### ISSUE TITLE
Update NTP image UI

### ISSUE THREAD

**Issue by deeppandya** [brave/browser-android-tabs#2541]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
![Screenshot_20200201-115437_Brave](https://user-images.githubusercontent.com/5146988/74304740-eec27f80-4d83-11ea-8a01-66d4a5769655.jpg)

## Expected result
![Screenshot_20200212-010228_Brave](https://user-images.githubusercontent.com/5146988/74304747-f2ee9d00-4d83-11ea-9e48-313c29991b8d.jpg)

## Issue reproduces how often 
often

## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
Fixed in https://github.com/brave/browser-android-tabs/pull/2540

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` on `Android` using `1.5.5 RC3 CR: 79.0.3945.136` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.5RC3: 

![Screenshot_20200212-214757_Brave](https://user-images.githubusercontent.com/2602313/74397232-2b24c880-4de2-11ea-942a-82883957fa63.jpg)

![Screenshot_20200212-214746_Brave](https://user-images.githubusercontent.com/2602313/74397227-27914180-4de2-11ea-96cc-3e95c08bc48b.jpg)

![Screenshot_20200212-214733_Brave](https://user-images.githubusercontent.com/2602313/74397213-2102ca00-4de2-11ea-845b-644590ae99ad.jpg)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.5 RC3 x64 build
![image](https://user-images.githubusercontent.com/17010094/74437863-e86cfa00-4e8e-11ea-98ed-a20483896385.png)
![image](https://user-images.githubusercontent.com/17010094/74437881-f0c53500-4e8e-11ea-952e-995c174ddf4a.png)
![image](https://user-images.githubusercontent.com/17010094/74437870-ec991780-4e8e-11ea-894e-d59564d7ebe2.png)
