### ISSUE TITLE
Reset and Resync doesn't transfer any bookmarks from mobile to laptop

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#255]
## Steps to reproduce

1. Setup Sync on laptop
2. Sync Android to Laptop without entering name, ensure device is listed as Android Device
3. Add bookmark/folder on Android, ensure it syncs with laptop
4. Add bookmaark/folder on laptop, ensure it syncs with Android
5. Reset sync on Android and resync without entering name, ensure device is listed on laptop but without any name (#254)
6. Reset sync a second time and resync and enter a device name this time
7. Add a bookmark on Laptop, not sync'd with Android
8. Add a bookmark on Android, not sync'd with laptop
9. Kill and restart Brave on Android, no sync, restart browser on laptop, no sync done with Android for new bookmarks

cc: @ayumi @diracdeltas

**Comment by SergeyZhukovsky** [comment]
That is fixed in the latest beta
