### ISSUE TITLE
certain settings cause a crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2550]
## Description 
Found while testing #2522 

Selecting certain settings causes Brave to crash.

## Steps to reproduce 

   1. install 1.5.6rc1
   2. Hamburger menu --> select Settings
   3. Tap on one of the following:
        - `Standard Tab` SE setting
        - `Private Tab SE` setting
        - `Appearance` setting
        - `New Tab Page` setting
        - `Background Video Playback` setting
        - `Closing all tabs closes Brave` setting
        - `Sync` setting

## Actual result 
![Screenshot_20200213-162551](https://user-images.githubusercontent.com/28145373/74479708-a4252e00-4e7d-11ea-8a27-132e5b2e0813.jpg)

## Expected result
Setting should open

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.6rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa @samartnik @SergeyZhukovsky

**Comment by btlechowski** [comment]
Reproduced on BraveModernarm v1.5.6-rc1 on Samsung Galaxy Tab S5e (Android 9.0)

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.6rc2 BraveModernx86.apk
   - Verified each of the settings identified in the description no longer crashes when accessed via hamburger menu --> settings
   - Verified able to open each of the settings and navigate around (toggle items, etc) without crashes
   - Verified on both clean and upgrade profiles
