### ISSUE TITLE
tab context menu is not available from + icon, now available from tab count icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2551]
## Description 
Using 1.5.5, 1.5.4, etc, when you entered the tab tray you could long press on the + icon to get a context menu where you could choose normal or private tab to open. 

With 1.5.6 this is no longer available, you can now just long press on the tab count icon to get a slightly different context menu.

Occurs in both normal and private tabs.

## Steps to reproduce 

   1. Install 1.5.6rc1
   2. Launch
   3. Tab on tab count icon to enter tab tray
   4. Long press on + icon

## Actual result 
nothing happens

## Expected result
![Screenshot_20200213-172309](https://user-images.githubusercontent.com/28145373/74484691-0df60580-4e87-11ea-9f4f-c4342d1cecb2.jpg)

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.6rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by samartnik** [comment]
This is expected inherited behavior from Chromium
