### ISSUE TITLE
long press on tab tray shows option for incognito tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2552]
## Description 
If you long press on tab tray you get an option for incognito tab.

Occurs in both normal and private tabs.

## Steps to reproduce 

   1. Install 1.5.6rc1
   2. Launch
   3. Long press on tab count icon.

## Actual result 
![Screenshot_20200213-171650](https://user-images.githubusercontent.com/28145373/74484524-bb1c4e00-4e86-11ea-9bf7-0fe4fa1ce5e8.jpg)

## Expected result
Should say private not incognito

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.6rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?  yes

### Additional information

cc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy 5.1.1 running Bravemodernarm 1.5.6-rc1
![Screenshot_2020-02-14-14-07-04](https://user-images.githubusercontent.com/38657976/74514842-6a166380-4f33-11ea-9fb0-1a54302bfcd2.png)

**Comment by srirambv** [comment]
Not a regression as we didnt have long press on tab tray till now

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.6rc2 BraveModernx86.apk
![Screenshot_20200214-135327](https://user-images.githubusercontent.com/28145373/74559088-94ffb800-4f31-11ea-93a5-713a36413c59.jpg)
