### ISSUE TITLE
Brave is crashing when clicking on Appearance and New Tab Page settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2555]
## Description 
Brave is crashing when clicking on Appearance and New Tab Page settings

## Steps to reproduce 
Scenario 1:
   1. clean profile 1.5.6-rc1
   2. open settings menu from the hamburger menu
   3. navigate to Display settings
   4. click on `Appearance`
   5. brave is crashing

Scenario 2:
   1. clean profile 1.5.6-rc1
   2. open settings menu from the hamburger menu
   3. navigate to Display settings
   4. click on `New Tab Page`
   5. brave is crashing

## Actual result 
Brave is crashing when clicking on Appearance and New Tab Page settings

## Expected result

Should not be any crash
## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device (Phone, Tablet, Phablet): Samsung Galaxy j3
   - Android version: 5.1.1
   
## Brave version
1.5.6-rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky @deeppandya @samartnik

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Can you please check this issue on x86?

**Comment by kjozwiak** [comment]
Reproduced on `Samsung S10+` running `Android` using the STR outlined via https://github.com/brave/browser-android-tabs/issues/2555#issue-565159009. Example:

![Screenshot_20200214-031851_Brave](https://user-images.githubusercontent.com/2602313/74513579-e3cd3380-4ed8-11ea-81f2-c4e49dc3f470.jpg)

**Comment by GeetaSarvadnya** [comment]
Brave is also crashing when I access the settings below:

1. Background video playback
2. Closing all tabs closes brave

**Comment by GeetaSarvadnya** [comment]
dup of https://github.com/brave/browser-android-tabs/issues/2550
