### ISSUE TITLE
Autoplay option is missing in site settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2556]
## Description 

Autoplay option is missing in site settings
## Steps to reproduce 

   1. Clean profile 1.5.6-rc1
   2. Open hamburger menu
   3. Navigate to settings
   4. Click on `Site settings`
   5. Autoplay option is missing 

## Actual result 
Autoplay option is missing in site settings
![Screenshot_2020-02-14-15-18-45](https://user-images.githubusercontent.com/38657976/74521775-f9c20f00-4f3f-11ea-92e1-8d84f3fa2cd9.png)
![Screenshot_2020-02-14-15-18-50](https://user-images.githubusercontent.com/38657976/74521780-faf33c00-4f3f-11ea-8ccf-63c710b8f796.png)
![Screenshot_2020-02-14-15-18-54](https://user-images.githubusercontent.com/38657976/74521782-fb8bd280-4f3f-11ea-9d2b-9b3117b700f3.png)

## Expected result
Autoplay option should be available in site settings

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.5.6-rc1
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky @samartnik

**Comment by srirambv** [comment]
Autoplay,Protected media and video playback in brave were under media but looks like Chrome removed grouping and put the options at root level

**Comment by samartnik** [comment]
They removed `Autoplay` option and moved `Protected content` to root. So we had to move our `Video playback in Brave` option as well.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy j3 version 5.1.1 running `Bravemodernarm.apk 1.5.6-rc4`
![Screenshot_2020-02-14-15-18-50](https://user-images.githubusercontent.com/38657976/74843362-ccb39900-5351-11ea-8733-27c67befd81b.png)
![Screenshot_2020-02-14-15-18-54](https://user-images.githubusercontent.com/38657976/74843420-e0f79600-5351-11ea-84cc-6896f64b4fa2.png)
