### ISSUE TITLE
Click on `QA Preference` is causing brave crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2557]
## Description 
Click on `QA Preference` is causing brave crash

## Steps to reproduce 

   1. Clean profile 1.5.6-rc1
   2. Enable staging flag
   3. Click on `QA Preference`
   4. Brave is crashing

## Actual result 
Click on `QA Preference` is causing brave crash

## Expected result
Should not be any crash

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.6-rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane @samartnik

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.6rc2 BraveModernx86.apk
   - Verified accessing QA Preferences doesn't cause crash
   - Verified able to toggle settings without crash
