### ISSUE TITLE
context menu on image/link says 'Incognito' instead of private

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2558]
## Description 
Long press on an image or link says 'Open in incognito tab' instead of 'Open in private tab'.

Not specific to C80, reproduces in C79 version of Brave from GPS store as well.

## Steps to reproduce 

   1. Navigate to a page with image/links
   2. Long press on an image or link.

## Actual result 
Context menu says `Open in incognito tab`
![Screenshot_20200214-131846](https://user-images.githubusercontent.com/28145373/74558006-67b20a80-4f2f-11ea-90ba-41e5487a15d2.jpg)
![Screenshot_20200214-132533](https://user-images.githubusercontent.com/28145373/74558018-713b7280-4f2f-11ea-8980-8e02a436a725.jpg)

## Expected result
Context menu says `Open in private tab`

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes, reproduces with 1.5.5
   - Beta build? yes, reproduces with 1.5.6 rc1

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.5, 1.5.6rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk.1.5.6-rc4`
 - Logged https://github.com/brave/browser-android-tabs/issues/2567
![Screenshot_2020-02-19-11-35-05](https://user-images.githubusercontent.com/38657976/74807326-2a25f680-530e-11ea-97ec-740ccec848a3.png)
![Screenshot_2020-02-19-11-46-56](https://user-images.githubusercontent.com/38657976/74807330-2eeaaa80-530e-11ea-8d21-7db9baafbb62.png)
