### ISSUE TITLE
notification for private tabs mentions 'incognito' 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2559]
## Description 
Open a site in private tab and background the app. In the notification tray there is a notification that mentions 'incognito tabs' instead of 'private tabs'.

Not specific to C80, reproduces in C79 version of Brave from GPS store as well.

## Steps to reproduce 

   1. Open site in private tab.
   2. Background the app.
   3. Open notification tray.

## Actual result 
Message references incognito tabs:
![Screenshot_20200214-132550](https://user-images.githubusercontent.com/28145373/74558245-eb6bf700-4f2f-11ea-8afc-df9fb858245e.jpg)

## Expected result
Message should reference private tabs

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes, reproduces with 1.5.5
   - Beta build? yes, reproduces with 1.5.6 rc1

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.5, 1.5.6rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.5.6-rc4`
![Screenshot_2020-02-19-20-00-22](https://user-images.githubusercontent.com/38657976/74843900-99bdd500-5352-11ea-9f22-4dbfbb583482.png)
