### ISSUE TITLE
global Fingerprinting Protection does not work 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2561]
## Description 
Fingerprinting Protection can be enabled in settings and shows as toggled ON when navigated to a site, but does not appear to be blocking anything.

If you toggle manually (not using the global setting) it appears to work.

Does not reproduce on C79/GPS version.

## Steps to reproduce 

   1. Navigate to Settings > Privacy
   2. Enable Fingerprinting Protection
   3. Close Settings
   4. Navigate to https://browserleaks.com/webrtc, Nothing is shown as blocked on the site
   5. Open shields, shields shows the FP toggle as on, but 0 items are blocked.
   6. Toggle FP off, and back on.
--> now the FP setting works.

same thing happens on both clean installs and upgrade profiles.

## Actual result 
Nothing is shown as blocked on the site, shields shows the FP toggle as on, but 0 items are blocked.

![Screenshot_20200214-170354](https://user-images.githubusercontent.com/28145373/74572411-13b61e80-4f4d-11ea-8bc0-0bfa4db8e666.jpg)

![Screenshot_20200214-170359](https://user-images.githubusercontent.com/28145373/74572418-17e23c00-4f4d-11ea-8886-5695a4e89a05.jpg)

## Expected result
Should work as it does in 1.5.5 (GPS version):
![Screenshot_20200214-170155](https://user-images.githubusercontent.com/28145373/74572455-2597c180-4f4d-11ea-9317-c2d3c1e92400.jpg)

![Screenshot_20200214-170159](https://user-images.githubusercontent.com/28145373/74572466-292b4880-4f4d-11ea-90fe-dfa2337c5b6d.jpg)

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.6rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa @samartnik

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.5.6-rc4`
![Screenshot_2020-02-19-20-15-32](https://user-images.githubusercontent.com/38657976/74845206-a80cf080-5354-11ea-9335-69193b6298da.png)
