### ISSUE TITLE
Old icon is used on mono builds

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2572]
Old icon is used on mono builds. Needs to be fixed.

**Comment by samartnik** [comment]
Discussion is here https://bravesoftware.slack.com/archives/C212VB0RG/p1582290000135200?thread_ts=1582224180.133000&cid=C212VB0RG

**Comment by samartnik** [comment]
To reproduce just install mono version of installer. App icon will be old in this case.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+`running `Android 10` using `Android 1.5.6 CR: 80.0.3987.99 RC5` as per https://github.com/brave/browser-android-tabs/releases/tag/v1.5.6-rc.5.

* Downloaded both `BraveMonoarm.apk` and `BraveMonoarm64.apk` and ensured that the latest Brave icon is being used. Example:

**`Before (using 1.5.6 CR: 80.0.3987.99 RC4:`**

<img width="102" alt="Screen Shot 2020-02-21 at 12 34 16 PM" src="https://user-images.githubusercontent.com/2602313/75057227-8b80cd80-54a6-11ea-9e64-505299eac906.png">

**`After (using 1.5.6 CR: 80.0.3987.99 RC5:`**

<img width="104" alt="Screen Shot 2020-02-21 at 12 34 30 PM" src="https://user-images.githubusercontent.com/2602313/75057234-8f145480-54a6-11ea-9bf9-7a270d20a9e8.png">
