### ISSUE TITLE
Can't download any file through Brave

### ISSUE THREAD

**Issue by iowbeoibewio** [brave/browser-android-tabs#2581]
## Description

If I try to download any file and any type, you just can't, it is only happening after install brave at the beginning, and after some time it's just fix be it self!!
I gived brave full permissions, and I try to untick "ask to download folder" in Brave

Sometimes it's download, but if you try to opend you just can't!!! And if you check download folder you find nothing!!!

This problem happens with all files extensions, even JPG.

SO I TRY TO LOOK UP WHERE IS IT AND FIND IT AT THIS LOCATION

Internel Storage/Android/data/com.brave.browser/files/Download

it is happened with me previous OnePlus 5, and then in my Galaxy S10, and yesterday after do factory reset it's again same problem!!!

## Steps to reproduce
Install Brave for the first time on your device, and try to download any file then try to run it.

## Actual result
Sometime it's download and if try to open it through brave give you message "can't open" and if you check download folder you will find nothing.

And sometimes it's just stuck at download location dialog!!

## Expected result
Download :)

## Issue reproduces how often
Always

## Device details and Brave version
![Screenshot_20200227-072310_Brave](https://user-images.githubusercontent.com/23007602/75412645-290b4f80-5934-11ea-9831-13487d02a6a2.jpg)

### Additional information
This dialog where I always stuck there and just can't download any file

![Screenshot_20200227-072833_Brave](https://user-images.githubusercontent.com/23007602/75412882-f4e45e80-5934-11ea-8988-6ef8ff52f417.jpg)

**Comment by iowbeoibewio** [comment]
Just to confirm, my devices are in English language and Non rooted

And I looked up at google, and there many people have same issue, thank you

**Comment by iowbeoibewio** [comment]
I fixed the problem that not linked directly to option I enabled

I turned ON "Allow from this source" and it's Now download all files extensions and install it, even APK

**Comment by vkhomenk** [comment]
Same issue

**Comment by naloder** [comment]
same problem

**Comment by xeroceph** [comment]
Experiencing this same issue

**Comment by Nikoleos** [comment]
Same issue for me on android 10

**Comment by k-kruglov** [comment]
Have the same issue, Xiaomi mi a2, Android 10, latest brave available. Brave keeps saying that sd card not found and it's strange because I don't have an sd card on my phone.

**Comment by iowbeoibewio** [comment]
Very weird !!
Any response from Brave Team?

By the way, even after the fix in my second comment, if you download any file you can't open it through notifications after finished, you need to do through Brave or through any file manager app, and you can't get the picture or documents etc... to share through other apps because is not showing there until few minutes!!!

This problem is so annoying!!!

Thanks

**Comment by iowbeoibewio** [comment]
Problem still present.
Version 1.5.9, Android 10

**Comment by CoVoCre** [comment]
Same problem... This is really a huge problem !!!

**Comment by CoVoCre** [comment]
The "install apps from unknown sources" when checked does fix the problem for me. Somewhat. Because the notification of download actually still says there was an error although it worked.

**Comment by huegelc** [comment]
Same issue here. Very annoying 
Android 10
Brave 1.5.9

**Comment by iowbeoibewio** [comment]
FYI
Brave Beta at Play Store doesn't have this problem at all 👍

Looks like problem solved 100%
waiting for fix to Brave releases channel 

Thanks

**Comment by SaleProperly** [comment]
Same.

Pixel 4.

If I do a fresh install, I can download files but not open them from brave. But I can open them from the file browser. And it doesn't use the download folder.

However! If I untick the ask where to download option, I can no longer download anything!!! It says sd card not found. Worse, that option cannot be changed back!?! If you try, it silently fails and if you check on it you will find it still selected.

Not being able to download files is a huge issue for me. It is forcing me to use other, actually functional, browsers.

I want to support you guys, but you have to have a working product.

**Comment by everonline** [comment]
> FYI
> Brave Beta at Play Store doesn't have this problem at all 👍
> 
> Looks like problem solved 100%
> waiting for fix to Brave releases channel
> 
> Thanks

Thanks, allowing to install apps from unknown sources fix it as mentioned above even if it gives the notification as error.

Brave seems a work in progress, at this point sync is also being totally rebuilt.

**Comment by iowbeoibewio** [comment]
Hi everyone

Brave Beta on Play Store is 1.5.116 had this problem too.

version 1.5.117 (Pre-release) fixes this problem, you can download it from here for Android (it will update through play store later if there is an updates)

https://github.com/brave/brave-browser/releases/tag/v1.5.117

I will close this issue after it's release on Play Store, Thanks to everyone.

#Bravearm.apk: Android 4.4
BraveModernarm.apk: Android 5.0 and above prior to Android 7.0
BraveMonoarm.apk: Android 7.0 and above

x86:
Barvex86.apk: Android 4.4
BraveModernx86.apk: Android 5.0 and above

**Comment by LeGaryGary** [comment]
I'm also getting this issue where it says `SD card not found` when I try to download files

**Comment by srirambv** [comment]
This will be fixed in the next release once we move to Android-Core. As this repo will be obsolete once the release goes out I'll be closing the issue. https://github.com/brave/brave-browser/issues/8737 which has the fix PR linked.
