### ISSUE TITLE
Application crashes when calculating the winning page classification category

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2583]
## Description 
Duplicate of: https://github.com/brave/brave-browser/issues/7866
Merge of https://github.com/brave/brave-core/pull/4770 into `android_80v2`.
Read above issue and original PR for details.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Cherry-picked:
https://github.com/brave/brave-core/commit/885ec1439b68f6e84366fe69b401e0e98d753b77

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Glaxy J3 version 5.1.1 running BraveModernarm.apk.1.5.8

- Verified the STR from https://github.com/brave/brave-browser/issues/7866
