### ISSUE TITLE
Fix message for offline page

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#2595]
As per discussion https://bravesoftware.slack.com/archives/C0YL5KMA8/p1583343534039700

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/b3500860009ab901983f5c4c381d716942b11f7f

**Comment by bsclifton** [comment]
Thanks for editing the issue to provide screen cap / more information, @kjozwiak 

@samartnik although we know the conversation took place on Slack- in the future can we please include enough information in the ticket to accurately describe the problem? (and steps that you'd like QA to run through to verify it's fixed). Many times users may encounter the issue too and it's helpful for them to be able to find it and track progress. Thanks! 😄

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 Version 5.1.1 running `Bravemodernarm 1.5.9`
![image](https://user-images.githubusercontent.com/38657976/75971601-04951180-5ef8-11ea-9a4b-c9aecf8a825d.png)
