### ISSUE TITLE
After updating bookmark title on mac, bookmark is no longer available on sync-ed Android devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#260]
- Did you search for similar issues before submitting this one? 
Yes

- Describe the issue you encountered:
When MacOS laptop has sync enabled and I update a bookmark title (bookmark is located in a folder), the bookmark is removed from Android devices.

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Laptop is Mac with 10.11.1 El Capitan
Android Devices are GalaxyS4 with KitKat (4.4.4) and Nexus 5 with Lollipop (5.1)

- Brave Version (revision SHA): 
v1.0.22(beta1)

- Steps to reproduce:
1. Laptop has bookmarks and sync enabled
2. Install beta (https://github.com/brave/browser-android-tabs/releases/tag/v1.0.22(beta1)) on two android devices: galaxyS4 w/ kitkat and nexus 5 w/ lollipop
3. Sync galaxys4 using words from laptop
4. Sync nexus 5 with QR code from laptop
5. Create bookmark on nexus 5 (under a folder such as Mobile Bookmarks > foldah). I used www.bobsclamhut.com as my link. 
6. The added bookmark syncs on laptop and other android device.
7. On the laptop, open Bookmarks Manager and navigate to the link in the folder.
9. Right click and rename bookmark title on laptop (changed from "Bob's Clam Hut" to "best seafood in Kittery")
10. Bookmark is removed from both android devices. 
    
- Actual result:
Bookmark is removed from both Android devices, but is retained on the laptop.

- Expected result:
Bookmark should be retained on both Android devices and the title should be updated on both devices.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
N/A

- Screenshot if needed:
![screen shot 2017-06-02 at 5 12 44 pm](https://cloud.githubusercontent.com/assets/28145373/26745190/65f4ac16-47b7-11e7-9992-5b5a9644d7e9.png)

![galaxys4ss-nobookmark](https://cloud.githubusercontent.com/assets/28145373/26745220/887cace8-47b7-11e7-86b2-9790d98f8a89.png)

![nexus5ss-nobookmark](https://cloud.githubusercontent.com/assets/28145373/26745233/a5bf8d02-47b7-11e7-9e2e-8c1ba40f6a9e.png)

- Any related issues:

**Comment by SergeyZhukovsky** [comment]
That is an issue in a sync library, created an issue there 
https://github.com/brave/sync/issues/95

**Comment by SergeyZhukovsky** [comment]
I found that bookmark on a top folder btw, it appears there because a sync lib sent me a zero parentFolder for it.

**Comment by SergeyZhukovsky** [comment]
It is fixed.
