### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by rig-hash** [brave/browser-android-tabs#2604]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as this is basically a blank issue. @rig-hash please create a new issue and add more information if you're experiencing an issue.
