### ISSUE TITLE
unable to download | sd card not found

### ISSUE THREAD

**Issue by ristein** [brave/browser-android-tabs#2606]
i cant download anything in latest version, only when i reinstall this version instead of updating to it.
might be related to android 10.
also found a thread on reddit: https://www.reddit.com/r/brave_browser/comments/ffkw0s/brave_android_app_latest_version/

## Steps to reproduce 

   1. uninstall brave
   2. install brave 1.5.9
   3. try to download anything

## Actual result  
 window popup saying "sd card not found" and asking where to save file.

## Expected result
just download or working selection of place to save

## Issue reproduces how often 
 easily (cant download at all)

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? dont know

## Device details
   - Install type (ARM, x86): arm i guess
   - Device (Phone, Tablet, Phablet): Oneplus 7 pro
   - Android version: 10 (custom rom)
   
## Brave version
1.5.9

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/8737
