### ISSUE TITLE
Brave not blocking 3rd party cookies

### ISSUE THREAD

**Issue by 67ghpidevocl45** [brave/browser-android-tabs#2609]
www.whatismybrowser.com/detect/are-third-party-cookies-enabled
https://alanhogan.github.io/web-experiments/3rd/third-party-cookies.html

Both of these sites report 3rd party cookies being enabled, despite the "block 3rd party cookies" shield being enabled

Brave Android Version: 1.5.9

**Comment by srirambv** [comment]
This is fixed on Android-core. Closing the issue as Android-core migration will be done in next release which will fix this issue.
![image](https://user-images.githubusercontent.com/17010094/77750820-7ae5e900-704a-11ea-9309-c93a35f4bc11.png)
![image](https://user-images.githubusercontent.com/17010094/77750832-80433380-704a-11ea-9602-31cef7d44ddb.png)
