### ISSUE TITLE
Cannot click bottom button after scrolling and hiding the bottom nav bar

### ISSUE THREAD

**Issue by antoinerousseau** [brave/browser-android-tabs#2612]
## Description 

The bottom toolbar hides when scrolling down, revealing a button that was just below the fold, but it still cannot be touched when we can't scroll enough

## Steps to reproduce 

   1. Go to https://5e89d2e60d6f500007abac17--whenwillyoucrack.netlify.com/
   2. Touch start, choose an option, touch Next: it works
   3. Question 2: choose an option, scroll down to reveal the Next button (only works with a device that's not too tall – I have a Redmi Note 7), try to touch it: nothing happens

## Actual result

The bottom button is not responding

## Expected result

The button should respond. It does in other browsers, including Chrome mobile

If you go to https://whenwillyoucrack.com I added some bottom padding so you can scroll more and touch the same button.

## Issue reproduces how often 

Always

## Issue happens on 
   - Current Play Store version: yes
   - Beta version: **no!**

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Redmi Note 7
   - Android version: 9 (MIUI 11)
   
## Brave version
Stable 1.5.9
Beta 1.5.116

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Seems to work on 1.5.120 which is the next release. Could you try updating to the new version and check?

**Comment by antoinerousseau** [comment]
@srirambv thanks, it's already working with 1.5.116 as stated. Maybe I shouldn't even open a ticket if it's fixed in the beta channel, sorry
