### ISSUE TITLE
Black bar shown on Galaxy S8+

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#264]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Black bar shown on Galaxy S8+. Reported on Community 
https://community.brave.com/t/brave-not-taking-advantage-of-the-galaxy-s8-screen/3555/2

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung S8 +
   - Android Version: 7.0
    
**Brave Version:**
1.0.21

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/26838002-d096dfe0-4ad6-11e7-9d73-7df0fb5f1a0c.png)

**Any related issues:**
#245

**Comment by SergeyZhukovsky** [comment]
That was fixed https://github.com/brave/browser-android-tabs/issues/242 and the fix will appear on the upcoming release.
