### ISSUE TITLE
Change Incognito naming to be Private to match laptop

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#265]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Change 'Incognito' naming to be 'Private' so that it matches laptop and iOS.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Galaxy S4, Nexus 5 
   - Android Version: Galaxy has KitKat 4.4.4, Nexus5 has Lollipop 5.1
    
**Brave Version:**
1.0.22

**Steps to reproduce:**
1. Open Brave, select 3 dots menu, 'New incognito tab' is listed.
2. On the tab you just opened, Incognito terminology is used.
3. On a regular (not incognito tab) navigate to a site (such as nytimes.com). 
4. Select and hold down a link so that you get the context menu. 'Open in incognito tab' is displayed.
5. When Brave has incognito tabs open, the 'banner' on the lock screen mentions incognito tabs.

**Actual Behavior**

**Expected Behavior**
Incognito terminology should be changed to Private to match with laptop and iOS.

**Is this an issue with Beta build?**
all

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior? - yes, the 'incognito' terminology is in chrome.

**Screenshot if needed:**
![incognito1](https://user-images.githubusercontent.com/28145373/26937475-77f418e8-4c3f-11e7-9fce-6075d735e8bb.png)

![incognito2](https://user-images.githubusercontent.com/28145373/26937490-815638ee-4c3f-11e7-823e-6d92369e79a9.png)

![incognito4](https://user-images.githubusercontent.com/28145373/26937503-8699e396-4c3f-11e7-901f-efd6d1198083.png)

![incognito5](https://user-images.githubusercontent.com/28145373/26937507-8b739a42-4c3f-11e7-961d-9d7e81328078.png)

**Any related issues:**

**Comment by srirambv** [comment]
@SergeyZhukovsky  Could the incognito icon be replaced with 
![image](https://user-images.githubusercontent.com/17010094/27038728-b84be820-4f83-11e7-8c0b-5c1ef325e173.png)

Also the private tab should contain the text similar to iOS 
![image](https://user-images.githubusercontent.com/17010094/27038914-45e0ce1c-4f84-11e7-86e8-4bfdc787ca01.png)

**Comment by samartnik** [comment]
Additional cases where Incognito pops up:
![screenshot from 2018-07-09 21-30-08](https://user-images.githubusercontent.com/30602739/42496788-d5d59062-842f-11e8-9274-851a7a8369e5.png)
![screenshot from 2018-07-09 21-33-12](https://user-images.githubusercontent.com/30602739/42496790-d5f4fb82-842f-11e8-9335-f5f00dc50b50.png)
![screenshot from 2018-07-10 10-26-57](https://user-images.githubusercontent.com/30602739/42496791-d63b1ba8-842f-11e8-94d1-5ac9e1d38b65.png)
![screenshot from 2018-07-10 10-46-44](https://user-images.githubusercontent.com/30602739/42496792-d65e609a-842f-11e8-97fb-49e6b7e42469.png)
![screenshot from 2018-07-10 10-49-53](https://user-images.githubusercontent.com/30602739/42496793-d67d46b8-842f-11e8-900f-eb369e231ab4.png)

**Comment by samartnik** [comment]
Fixed in https://github.com/brave/browser-android-tabs/pull/678

**Comment by srirambv** [comment]
Verified on Lenovo Yoga Tablet running x86

**Comment by samartnik** [comment]
That icons belongs another app (Gboard), so we can't change it.

**Comment by LaurenWags** [comment]
closed again per https://github.com/brave/browser-android-tabs/issues/265#issuecomment-410719911 and re-added labels.
