### ISSUE TITLE
Chrome logo still in the app

### ISSUE THREAD

**Issue by Skayo** [brave/browser-android-tabs#266]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
The original chrome logo is still in the app and should maybe be replaced with the brave logo.

**Device Details:**
   - Install Type(ARM, x86): IDK, but I think x86
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 6.0
    
**Brave Version:**
1.0.21

**Steps to reproduce:**
    1. Go into tabs view
    2. Swipe up 5 times
    3. 3D spinning animation with the chrome logo

**Actual Behavior**
Shows chrome logo

**Expected Behavior**
Shows brave logo

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Any related issues:**
No

**Comment by SergeyZhukovsky** [comment]
@Skayo thank you for reporting that. The fix is done and will appear in the upcoming release.
