### ISSUE TITLE
Change to Parent bookmark folder on Android is not sycned to laptop

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#279]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Changing the parent folder of a bookmarks folder does not sync to laptop, but does sync android-android.

Pyramid 0 is Mac Laptop
Pyramid 1 is Nexus 5
Pyramid 2 is Galaxy S4

**Device Details:**
   - Install Type(ARM, x86): Arm
   - Device(Phone, Tablet, Phablet): Mac Laptop, Nexus5, Galaxy S4
   - Android Version: Nexus 5 is 5.1, Galaxy S4 is 5.0.1
    
**Brave Version:**
Android version is 1.0.23beta
Laptop version is 0.17.2

**Steps to reproduce:**
0. Laptop and both Androids do not have any bookmarks (clean installs)
1. Create sync group on mac laptop
2. Join sync group - joined on Android devices 1&2 (nexus and galaxy respectively)
3. On device 1 (Nexus), create a bookmark at ‘Mobile Bookmarks’ level, create a folder which contains 2 different bookmarks.
4. Folder and all bookmarks are synced to laptop and android device 2
5. On device 1 (nexus), create a new folder as the parent folder for the folder created in step 3 (To do this - open bookmarks, tap on 3 dots on the folder, select edit, tap on mobile bookmarks, tap on new folder, put name, select checkmark in upper right corner, nav back to bookmarks).
6. Change is synced to laptop and android device 2
7. Back on device 1, change the parent bookmark. (to do this: open bookmarks again, tap on folder created in step 5, tap on 3 dots for the sub folder (this is the folder which was created in step 3). select edit. change the parent folder to be mobile bookmarks instead of the folder created in step 5. nav back to bookmarks.)
8. The parent folder change is synced to android device 2, but not to laptop.

**Actual Behavior**
Laptop still displays:
Folder from Step 5 > Folder from Step 3 > 2 bookmarks created in step 3.

**Expected Behavior**
Laptop should reflect the change in bookmark parent folder.

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. Repeat steps 2-8 with an iOS device. Parent folder change is not updated on iOS device either.
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
Laptop (incorrect folder structure):
<img width="843" alt="screen shot 2017-06-14 at 4 25 30 pm" src="https://user-images.githubusercontent.com/28145373/27153181-68eed8cc-511e-11e7-8e53-76480a247fa0.png">

Nexus 5 and Galaxy S4 (correct folder structure):
![screenshot_2017-06-14-16-25-15](https://user-images.githubusercontent.com/28145373/27153206-85c2ac62-511e-11e7-9e6f-f075ced7819f.png)

**Any related issues:**

**Comment by SergeyZhukovsky** [comment]
I created an issue in sync repo for that https://github.com/brave/sync/issues/100

**Comment by LaurenWags** [comment]
Moving issue to sync repo: https://github.com/brave/sync/issues/107
