### ISSUE TITLE
Fingerprint protection toggle is broken when enabled in Settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#287]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Reported by Community (https://community.brave.com/t/fingerprint-protection-toggle-is-broken-when-enabled-in-settings/4456/4)

When Fingerprinting Protection is enabled in Settings>Privacy, it does not turn off from Bravery icon. 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Nexus 5
   - Android Version: 5.1
    
**Brave Version:**
1.0.23 (released version), 1.0.24 (beta)

**Steps to reproduce:**
(start with clean install/default settings)
1. Navigate to settings > Privacy. Enable Fingerprinting Protection.
2. Open new tab (this is important, don’t try to re-use an existing one)
3. Navigate to site: https://medium.freecodecamp.org/the-art-of-computer-programming-by-donald-knuth-82e275c8764f
4. Note, images are not displayed.
5. Select shield icon. Toggle off Fingerprinting Protection. Note, images are not displayed. Site appears to reload, but nothing is changed. 

**Actual Behavior**
No change on site, Fingerprinting Protection does not appear to be turned off.

**Expected Behavior**
Fingerprinting should be able to be toggled on/off from shield.

**Is this an issue with Beta build?**
Issue exists in beta as well as released version.

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. Close tab with site from steps above.
    2. Navigate to Settings > Site Settings > All sites. Clear site settings.
    3. Navigate to Settings > Privacy > disable Fingerprinting Protection. Also, Clear browsing data from this area.
    4. Open a new tab and navigate to site above (https://medium.freecodecamp.org/the-art-of-computer-programming-by-donald-knuth-82e275c8764f)
    5. Note, images, etc are displayed on site.
    6. Select shield icon. Toggle off Fingerprinting Protection. Note, images, etc are no longer displayed.
    7. Select shield icon. Toggle on Fingerprinting Protection. Note, images, etc are displayed again.

**Website problems only:**
  - did you check with Brave Shields down? yes. Following STR (not Extra QA Steps) and turning Shields Off did not result in images being displayed on the site.
  - did you check in Chrome for same behavior? n/a

**Screenshot if needed:**

**Any related issues:**

**Comment by LaurenWags** [comment]
cc: @SergeyZhukovsky

**Comment by LaurenWags** [comment]
+1 Community https://community.brave.com/t/display-incorrectly-blocked-images/4685

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/720

**Comment by samartnik** [comment]
Link from steps to reproduce didn't show the problem, so we tested it on https://archive.org/details/OTRR_Dragnet_Singles
