### ISSUE TITLE
Make Home Button on URL Bar optional

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#292]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
1.0.24 removed the home button from URL bar by design, however some users want it back. We should make this an optional feature.

**Device Details:**
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version:  all
    
**Brave Version:**
1.0.24

**Steps to reproduce:**
    1. Open Brave
    2. User should have the option to display home button on URL Bar.

**Actual Behavior**
Home button no longer available (by design)

**Expected Behavior**
Home button display should be optional.

**Comment by LaurenWags** [comment]
Many Google Play Store reviewers are requesting the home button back.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/231b3d0d5fb0a1393208c787c80007ed5f5f5da9

**Comment by LaurenWags** [comment]
Unable to verify, none of my devices have the manufacturer home button.
