### ISSUE TITLE
Add ability to create sync group on Android 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#302]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Add ability to create a sync group on Android. Currently (in beta) Android only allows joining to a sync group, but should support ability to create a sync group like laptop and iOS.

**Steps to reproduce:**
    1. Open beta version (1.0.25).
    2. Navigate to Settings > Sync.
    3. Option to create sync group does not exist.

**Comment by arisAlexis** [comment]
This decreases adoption so much that it should become the first priority of the team

**Comment by teresaejunior** [comment]
Sorry for the off-topic, but I have just downloaded the latest beta, and I can't find the option to join an existing group... This is stopping me from switching, can someone help, please?

**Comment by samartnik** [comment]
This is already implemented

**Comment by liamaharon** [comment]
@samartnik how can we use this feature? I can't find any sync option in Brave for Android v1.0.72. Do we need to use a beta build?

**Comment by samartnik** [comment]
Sync hasn't been released yet. We expect to have Sync-beta in official release soon.
