### ISSUE TITLE
Brave Android Crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#311]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Brave on Android started crashing out of the blue, but started working out of the blue as well. Logs attached.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Nexus
   - Android Version:  5.1
    
**Brave Version:**
1.0.27(sync)

**Steps to reproduce:**
Just tried opening Brave, but kept getting the message 'Unfortunately Brave has stopped.'

**Actual Behavior**
Brave crashed

**Expected Behavior**
Brave should not crash.

**Can this issue be consistently reproduced?**
n/a

Logs from around the time of crash:
[logsfromaroundthetimeofcrash.txt](https://github.com/brave/browser-android-tabs/files/1166802/logsfromaroundthetimeofcrash.txt)

Additional logs - after crash stopped happening, opened Brave these are from about a minute after Brave was opened:
[additionallogs.txt](https://github.com/brave/browser-android-tabs/files/1166804/additionallogs.txt)

**Comment by SergeyZhukovsky** [comment]
Fixed https://github.com/brave/browser-android-tabs/commit/47ddadca5e340ee1cf8a0d6a16945787cdffe2bc.
