### ISSUE TITLE
Why does Brave need access to Google account?

### ISSUE THREAD

**Issue by uncertainquark** [brave/browser-android-tabs#313]
On rebooting the phone, a notification pops up from Brave, asking for the access to Google account. Why is this happening?  This should be removed.

![screenshot_2017_07_20_10_22_06 1](https://user-images.githubusercontent.com/22585732/28497358-b6e8e364-6f74-11e7-9eec-0825336848f1.png)

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone): Moto E2 LTE
   - Android Version: Android 7.1.2
    
**Brave Version:** 59

**Steps to reproduce:**
    1. Install Brave and start using it
    2. Restart phone
    3. A notification will appear leading to the said dialogue

**Comment by uncertainquark** [comment]
Is anyone ever going to reply?

**Comment by SergeyZhukovsky** [comment]
@uncertainquark we have that issue already https://github.com/brave/browser-android-tabs/issues/167. We are trying to replicate it, but still without any success.
