### ISSUE TITLE
Extensions support with WebExtensionsAPI

### ISSUE THREAD

**Issue by D0ve** [brave/browser-android-tabs#316]
The most awaited future imo is the WebExtension API support in mobile Brave!
Usual extensions of Chrome, Opera and new FF ...- in mobile Brave would be a miracle!

It may be useful how mobile Ya.Browser team was coming up with implementing this support to its propriatary browser:
https://habrahabr.ru/company/yandex/blog/309014/

Extensions support in mobile Brave would be the greatest future I've ever wish for the best opened mobile browser!

**Comment by avently** [comment]
@sergeyzhukovsky
Did you try to build with extensions enabled? 
Мне кажется, реализация этой фичи привлечет необходимое внимание к браузеру, которого он заслуживает. И, конечно же, это поставит остальные браузеры на колени. Может попробуем реализовать поддержку?

**Comment by SergeyZhukovsky** [comment]
@avently the enable_extensions flag does nothing on Android builds. There are no extensions support on Android currently. We are going to work on that in the future, but not now.

**Comment by D0ve** [comment]
New beta of Fennec supports WebExtension...
Sergey , please , it's needed very much to start investigating support WebExtension not in the future, but now!
Is it possible to have a look how it did in ChromiumMobile by Yandex(YandexBrowser)?.... and use it but another way in implementation... .

**Comment by D0ve** [comment]
@SergeyZhukovsky
I have an Idea! If sources of AndroidChromium isn't with WebExtensions support....,-
Could it be possible to port WebExtensions support code from new Fennec?

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/7606
