### ISSUE TITLE
Strange red frame

### ISSUE THREAD

**Issue by avently** [brave/browser-android-tabs#321]
Sometimes view of the screen shows red frame. It happens when i download a file. 

Пишу по русски, чтоб ты понял хорошо. Я собрал из исходников x86 версию и некоторые пользователи заявили, что при нажатии иконки меню по краям экрана моргает красная полоса. У меня на arm версии я эту ситуацию встречал во время загрузки файла через Brave. Моргает на полсекунды и пропадает. Не встречал такого?

**Comment by SergeyZhukovsky** [comment]
The behavior you described is called Strict Mode. You can can turn it off under you phone `Settings->Developer` options and under Monitoring section find `Strict mode enabled`. It is done for developers to flash when you have lots of things in the main UI thread in your app. Probably the customers have it enabled as well.

**Comment by avently** [comment]
@SergeyZhukovsky strict mode is disabled. I have android 7.1.2

**Comment by SergeyZhukovsky** [comment]
I never seen it with that option turned off. Feel free to post steps how to reproduce.

**Comment by avently** [comment]
@SergeyZhukovsky i can't. I does not have x86 device and i saw this frame on my arm device only once. And it happens only on my build (your builds is fine). I think something wrong with my build configuration. Take a look:

**Comment by SergeyZhukovsky** [comment]
Could you check it with that configuration for x86?
https://github.com/brave/browser-android-tabs/wiki/Sample-gn-file-for-x86-release
The one thing that you missed for sure is that
`fieldtrial_testing_like_official_build = true`
you should always build release versions with that flag.

To improve testing coverage, Chromium developer builds enable all experimental features by default, even some which are not ready to be shipped to end users. Unfortunately, many Chromium derivatives ship with the same settings, which can cause problems. Chromium packages and derivatives must set the following build flag for an end-user configuration:
`fieldtrial_testing_like_official_build=true`

**Comment by avently** [comment]
@SergeyZhukovsky ok, thank you. I will test and will tell you about results

**Comment by srirambv** [comment]
@avently is this red frame similar to the one shown in #23?

**Comment by avently** [comment]
@srirambv yes, it is!

**Comment by srirambv** [comment]
I have never seen this on the x86 tablet. @serg does the screen size have any relation to this issue?

**Comment by SergeyZhukovsky** [comment]
@srirambv @avently here is a link when you can read about that
http://www.droidviews.com/how-to-fix-the-red-frameborder-around-the-screen-of-android-devices/

**Comment by avently** [comment]
@SergeyZhukovsky it happens only in Brave. Strict mode disabled. I already told you about that.

**Comment by avently** [comment]
[ScreenRecord-2017-08-07-06-28-22.zip](https://github.com/brave/browser-android-tabs/files/1203810/ScreenRecord-2017-08-07-06-28-22.zip)
@SergeyZhukovsky here is what happens on arm build on arm64 device with flag suggested by you.

**Comment by avently** [comment]
Found the problem and a fix (not tested yet but i'm sure it will work).
For the future reference:
Look at this method https://github.com/brave/browser-android-tabs/blob/master/chrome/android/java/src/org/chromium/chrome/browser/ChromeStrictMode.java#L165

If this ChromeVersionInfo.isDevBuild() || ChromeVersionInfo.isLocalBuild() is true StrictMode will be enabled. 

It is about build channel:
https://github.com/brave/browser-android-tabs/blob/master/chrome/android/java/src/org/chromium/chrome/browser/ChromeVersionInfo.java#L28

So the fix is to add the line in gn args:
android_channel = "stable"

You can't leave it default.

**Comment by SergeyZhukovsky** [comment]
@avently did that flag fix the problem?

**Comment by avently** [comment]
@SergeyZhukovsky yes, it did. I haven't seen the red frame since build with that flag.
