### ISSUE TITLE
Webrtc leak for android

### ISSUE THREAD

**Issue by hrsyvg** [brave/browser-android-tabs#323]
Webrtc leaks even though the Android application has fingerprint protection turned on. The laptop is not like that, it seems to be working properly.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/brave-android-app-leaking-webrtc/5208

**Comment by samartnik** [comment]
Duplicated
https://github.com/brave/browser-android-tabs/issues/143
