### ISSUE TITLE
Bravery panel is tight

### ISSUE THREAD

**Issue by ayumi** [brave/browser-android-tabs#33]
App: 1.0
Device: LG Nexus 5X
Resolution: 1080x1920
OS: Android 7.0

> Ads and Trackers Blo...
> Slide toggles: Two of them span 2 lines

Should probably be less tight.

![screenshot_20161012-182234](https://cloud.githubusercontent.com/assets/521861/19333461/c973bfb2-90aa-11e6-8521-dccd1b669722.png)

**Comment by SergeyZhukovsky** [comment]
Fixed an original problem here
https://github.com/brave/chromium/commit/abc2fc572e22364972b49e1effdc658f2fbf75e2
I'm going to look on hiding the Brave Panel when we don't have an url bar panel.
