### ISSUE TITLE
Disabling 3rd Party Cookie also disabled Fingerprint protection

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#336]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Disabling 3rd Party Cookie also disabled Fingerprint protection

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Yoga Tablet
   - Android Version: 5.0.1
    
**Brave Version:**
1.0.28

**Steps to reproduce:**
    1. Clean install 1.0.28 build
    2. Enable Fingerprint protection from settings
    3. Visit any site and disable 3rd Party Cookie from sheilds
    4. Close and reopen shields Fingerprint protection is also disabled

**Actual Behavior**
See attachment

**Expected Behavior**
Should only disable 3rd Party cookies and not fingerprint protection

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes, same issue on play store build. Needs triage

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? N/A
  - did you check in Chrome for same behavior? N/A

**Screenshot if needed:**
[2017_08_08_08_58_15.zip](https://github.com/brave/browser-android-tabs/files/1207290/2017_08_08_08_58_15.zip)

**Any related issues:**

**Comment by srirambv** [comment]
Adding to current beta milestone. Please move to a new milestone if required
cc: @SergeyZhukovsky @samartnik

**Comment by LaurenWags** [comment]
reproduced on ARM build as well.

**Comment by samartnik** [comment]
Fixed
https://github.com/brave/browser-android-tabs/commit/4d88216e5798f0d90932fbec81847aad71188a19
