### ISSUE TITLE
New tab stats don't auto refresh

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#338]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
New tab stats don't auto refresh

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 5.0.1
    
**Brave Version:**
1.0.28(RC2)

**Steps to reproduce:**
    1. Clean install RC build
    2. Open a site in new tab
    3. Open a new tab, stats shows all 0's, refresh new tab, stat count change
    4. Open a new site which has lots of ads/trackers in them
    5. While the page is still loading, switch to new tab, stats don't change, refresh new tab, stats counter change

**Actual Behavior**
New tab stats don't auto refresh

**Expected Behavior**
Stats should auto refresh when pages are loaded in background tabs

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? N/A
  - did you check in Chrome for same behavior? N/A

**Screenshot if needed:**

**Any related issues:**

**Comment by samartnik** [comment]
Fixed https://github.com/brave/browser-android-tabs/pull/409

**Comment by srirambv** [comment]
@samartnik if the page is still loading, the ad counter doesn't update dynamically like how it does on iOS. New tab stats are auto updated if the page load is complete else again refresh causes it to update  Here's how it shows on iOS when new tab is loaded
[ios_newtab_stats.zip](https://github.com/brave/browser-android-tabs/files/1375320/ios_newtab_stats.zip)
