### ISSUE TITLE
"ViewPageSource" option

### ISSUE THREAD

**Issue by D0ve** [brave/browser-android-tabs#341]
Would like to see "ViewPageSource" option, that will get more power to Brave!

**Comment by SergeyZhukovsky** [comment]
You can use devtools for that https://github.com/brave/browser-android-tabs/wiki/How-to-use-dev-tools

**Comment by D0ve** [comment]
I just needed to grab some links to stream media ... using usb wire quite uncomfortable(((
So will wait for WebExtensions in Brave so much!!!
Sergey, could you please enforced this process?

I have an Idea! If sources of AndroidChromium isn't with WebExtensions support....,-
Could it be possible to port WebExtension support code from new Fennec?
