### ISSUE TITLE
Remove Google password manager link from settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#356]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Remove Google password manager link from settings

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version:  5.0.1
    
**Brave Version:**
1.0.29

**Steps to reproduce:**
    1. Menu -> Settings -> Save Password
    2. Shows link for `View and manage saved passwords at passwords.google.com`
    3.

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/29411499-00bf502c-834d-11e7-90b2-20b75db5788b.png)

**Any related issues:**

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/410
