### ISSUE TITLE
UI Cleanup (Brave Panel)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#365]
## Goals

Update Brave Shields on Android to align with iOS and Laptop styling.

Specs on this design can be viewed at https://zpl.io/bzZ9PAb 

## Brave shields

<img width="411" alt="screen shot 2017-08-23 at 4 52 41 pm" src="https://user-images.githubusercontent.com/318119/29644494-320f693e-883c-11e7-89c4-c501fb41124e.png">

**Comment by D0ve** [comment]
Where is 'Third-party cookies' in 'Individual Controls'???

And could I hope that just 'Cookies' will be there ?

**Comment by SergeyZhukovsky** [comment]
They renamed to Block Phishing

**Comment by SergeyZhukovsky** [comment]
That is done and merged https://github.com/brave/browser-android-tabs/commit/87c17b0e8973b791f1a1bd3381d28d8cef832bc5

**Comment by LaurenWags** [comment]
Test Plan:
Verify UI changes to shields as per image
Verify styling is applied to settings in toggle/checkboxes
Verify loading bar is orange
