### ISSUE TITLE
Music stops playing when app goes to background

### ISSUE THREAD

**Issue by avently** [brave/browser-android-tabs#367]
**Did you search for similar issues before submitting this one?**
Of course, yes

**Description:**
Music played in browser stops working when home button pressed or Brave went to background. I checked this behaviour in Chrome 59, 60, 62. Music keeps playing in Chrome. 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1.2
    
**Brave Version:**
1.0.30

**Steps to reproduce:**
    1. Go to https://www.tunefind.com/show/suits/season-7/50744
    2. Tap on play button
    3. Go to home screen

**Actual Behavior**
Music will be stopped

**Expected Behavior**
Music should keep playing

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes, even in old versions of Brave

**Can this issue be consistently reproduced?**
Yes

**Website problems only:** NO
  - did you check with Brave Shields down?
Yes
  - did you check in Chrome for same behavior?
Yes

**Comment by srirambv** [comment]
Is this the same behaviour on Chrome as well?

**Comment by avently** [comment]
@srirambv no, music in Chrome keeps playing when home button is pressed

**Comment by srirambv** [comment]
Thanks for confirmation. Added to feature request

**Comment by avently** [comment]
This problem exists even in Brave 1.0.17. I checked.

**Comment by D0ve** [comment]
Please, make it optional to swith on/off !!!!!

Sometimes it's very needed to freeze music when backgrounding browser.

Also l would suggest this option switch  for playing video also(in background) !!!
To turn it on sometimes!

**Comment by AlexeyBarabash** [comment]
It should be fixed in the next build.

**Comment by srirambv** [comment]
Audio stops when the app is backgrounded 
[367.zip](https://github.com/brave/browser-android-tabs/files/1441422/367.zip)

**Comment by LaurenWags** [comment]
I'm not experiencing this issue on the ARM build. When I use the link from the description and background the app, the music continues to play until it stops, then the audio icon disappears from the notification bar.

**Comment by kjozwiak** [comment]
Works on the Pixel XL as well.... Same behaviour @LaurenWags mentioned above.

* Build: `Brave 1.0.37, Chromium 62.0.3202.84`
* OS: android 8.0.0; Pixel XL Build/OPR3.170623.008`

**Comment by avently** [comment]
For me it works! Audio keeps playing when I go to home screen or change tabs.
Спасибо, @AlexeyBarabash !

**Comment by srirambv** [comment]
Same behaviour on Chrome as well. Audio stops when app is backgrounded. Closing as wontfix for x86

**Comment by srirambv** [comment]
Works as expected. Had to disable the  `Don't keep activities` from developer options. Thanks for providing the steps @AlexeyBarabash

**Comment by serafeimgr** [comment]
Does not seem to work on YouTube.
Tried the above link and it works as expected.
Any thoughts?

**Comment by LaurenWags** [comment]
@serafeimgr does it work if you try YouTube on Chrome?

**Comment by AlexeyBarabash** [comment]
@serafeimgr for now this is implemented only for websites with audio. 

For youtube there is an opened issue https://github.com/brave/browser-android-tabs/issues/160 and we are working on it.

**Comment by D0ve** [comment]
@AlexeyBarabash , please , could you make it switchable, at least in about:flags ?
