### ISSUE TITLE
Add DuckDuckGo Lite as search engine

### ISSUE THREAD

**Issue by namandixit** [brave/browser-android-tabs#373]
Will it be possible to add DuckDuckGo Lite (https://duckduckgo.com/lite) as one of the search engines? I sometimes have to deal with absymally bad internet speed and the "default" DuckDuckGo page takes a while to open due to being a bit on the heavy side (at least compared to the Lite version).

**Comment by AlexeyBarabash** [comment]
The changes for this issue has been merged. Should see it in the next release.

**Comment by LaurenWags** [comment]
STR:
Navigate to Settings > Search Engine.
Verify DuckDuckGo Lite is an option.
Set this as search engine.
Verify search engine is used.

**Comment by LaurenWags** [comment]
Using 1.0.35(beta4) this is not an option.
![screenshot_2017-10-11-09-57-37](https://user-images.githubusercontent.com/28145373/31444976-41ab62a8-ae6b-11e7-986a-143469198b82.png)

**Comment by AlexeyBarabash** [comment]
Lauren, thanks.
This should be fixed with a commit https://github.com/brave/browser-android-tabs/commit/7020d804b5215f68147f6e8f564ac3d69a3a2511 .
