### ISSUE TITLE
Embedded tweets problem

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#374]
We don't show them on that website
https://twitchy.com
Laptop and iOS both show them.
It looks like something is wrong in adblock+tp on Android.

**Comment by AlexeyBarabash** [comment]
Made a fix https://github.com/brave/browser-android-tabs/pull/439 .
Just put cdn.syndication.twimg.com into TP white list.

**Comment by LaurenWags** [comment]
Test Plan:
Navigate to https://twitchy.com
Open up an article from the page.
Verify embedded tweets display on the article.

cc @AlexeyBarabash
