### ISSUE TITLE
Chromium needs access to your location to share your location with this site

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#375]
Issue from community https://community.brave.com/t/how-to-stop-chromium-needs-access-to-your-location-to-share-your-location-with-this-site/6946

**Comment by xgirouxb** [comment]
I have the same issue on a oneplus one running lineage os

**Comment by Juan-Esteban1** [comment]
I've got a OPO with the same set-up having the same problems. Brave is the only browser I ha e had this problem with so I doubt it is the ROM

**Comment by timosillander** [comment]
Same here, on an LG G6.

**Comment by LaurenWags** [comment]
multiple +1s from Google Play Store

**Comment by chriswieman** [comment]
Having the same issue on Pixel XL, Android 8.0.0. 
Brave 1.0.31.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/full-screen-videos-plus-chromium/8568?u=eljuno

>constantly asking me to share my location, I keep saying no but it keeps coming back.

**Comment by dscish** [comment]
Same issue on:

Phone: HTC M8 One
Android: 6.0
Brave: 1.0.33, Chromium 61.0.3163.98

Mighty annoying, I like the browser, but I'm one step from un-installing it due to this silly issue as it happens every single time you google anything. Please fix this.

T.

**Comment by samartnik** [comment]
Fixed 278a7e8de5d77357cb65d7f75314704be13174d0

**Comment by dscish** [comment]
Thanks for finding a fix for this, when can an updated version of the app be expected?

T.

**Comment by SergeyZhukovsky** [comment]
@dscish hopefully next week.

**Comment by dscish** [comment]
Huge thanks, it was driving me nuts! Love the browser otherwise.

T.

**Comment by LaurenWags** [comment]
STR (not reproducible on every device)
navigate to google.com.
get message asking for your location.

**Comment by dscish** [comment]
Judging by the above it's being prerelease tested and hopefully released when?

T.

**Comment by LaurenWags** [comment]
@dscish release with fix is live on the Google Play Store or can be downloaded from our repo.
