### ISSUE TITLE
Fingerprint protection shows wrong count 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#378]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Fingerprint protection shows wrong count

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version:  5.0.1
    
**Brave Version:**
1.0.31

**Steps to reproduce:**
    1.     Enable Fingerprint protection from privacy settings
    2.     Visit https://jsfiddle.net/bkf50r8v/13/, see the count in shields shows as 1
    3.     Disable fingerprint protection, shows WebGL and WebRTC

**Actual Behavior**
Fingerprint protection shows count as 1 blocked

**Expected Behavior**
Should show fingerprint protection count as 2 for both WebGL and WebRTC

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by srirambv** [comment]
Also visiting browserleaks.com/canvas shows as count 1 but canvas is not blocked.

**Comment by samartnik** [comment]
1. As for this site  https://jsfiddle.net/bkf50r8v/13/. When we block WebRTC it doesn't go further to canvas and WebGL. So in this case there was used 1 fingerprinting method that blocked all 3 fingerprints. If we disable code for WebRTC, it will show  methods used.
2. As for this site browserleaks.com/canvas. I see canvas toDataUrl is blocked. Do you ave another result?

**Comment by samartnik** [comment]
Closing as it works as it's supposed to work.
