### ISSUE TITLE
HTTPS Everywhere fails when opening link in incognito mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#387]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
HTTPS Everywhere fails when opening link in incognito mode

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version:  5.0.1
    
**Brave Version:**
1.0.32 

**Steps to reproduce:**
    1. Open this [link](https://github.com/brave/browser-android-tabs/issues/386)
    2. Long press on https://https-everywhere.badssl.com/ and open in new incognito mode
    3. Shows HTTPS Everywhere is not working 

**Actual Behavior**
See screenshot

**Expected Behavior**
Should show HTTPSE as enabled

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/30419563-7263560c-9954-11e7-9581-10cfbf0c055b.png)

**Any related issues:**
#352

**Comment by AlexeyBarabash** [comment]
I have created a PR with a fix. Once this issue will be tested, could you please also check https://github.com/brave/browser-android-tabs/issues/352 , as it may be related.

**Comment by AlexeyBarabash** [comment]
Please find the apk with this fix in releases https://github.com/brave/browser-android-tabs/releases/tag/1.0.34(beta2) .

**Comment by LaurenWags** [comment]
Tests ran for HTTPS Everywhere fix for Incognito mode 
1. Verified steps in issue
2. Verified HTTPSE off and shields off both disable redirect in incognito tab
3. Verified HTTPSE works in normal tab as expected
4. Verified HTTPSE off and shields off both disable redirect in normal tab
