### ISSUE TITLE
build error on step 7-8 of "Preparing the Build Environment" in README.md 

### ISSUE THREAD

**Issue by lfxc** [brave/browser-android-tabs#388]
see ERROR line below.

if the error is an issue, please advise on how to correct it and what point should I restart the Environment Prep from.  thanks!

0> Downloading src/buildtools/android/doclava.tar.gz...
0> Extracting 7 entries from src/buildtools/android/doclava.tar.gz to src/buildtools/android/doclava
Success!
Downloading 1 files took 10.813820 second(s)
Hook '/usr/bin/python src/build/android/download_doclava.py' took 10.91 secs
Waiting for editor on "/home/lcanali/repos/browser-android-tabs/src/out/Default/args.gn"...
Generating files...
ERROR at //content/public/common/BUILD.gn:12:1: Can't load input file.
import("//third_party/webrtc/webrtc.gni")
^---------------------------------------
Unable to load:
  /home/user/repos/browser-android-tabs/src/third_party/webrtc/webrtc.gni
I also checked in the secondary tree for:
  /home/user/repos/browser-android-tabs/src/build/secondary/third_party/webrtc/webrtc.gni
See //chrome/test/BUILD.gn:145:5: which caused the file to be included.
    "//content/public/common",
    ^------------------------
Running as non-root user.
You might have to enter your password one or more times for 'sudo'.

**Comment by samartnik** [comment]
This is known issue. We will let you know when it's fixed.

**Comment by lfxc** [comment]
I reran the script on step 7, and noticed this error further upstream as well:

$ sh scripts/getThirdParties.js
Syncing projects:  95% (102/107) src/v8                                                     

src/third_party/webrtc (ERROR)
----------------------------------------
[0:00:17] Started.
[0:00:19] _____ src/third_party/webrtc : Attempting rebase onto f17e7774d7316fc4dda87c5e7d759ac33b20a52f...
[0:00:19] 
[0:00:19] Rebase produced error output:
fatal: Needed a single revision
Does not point to a valid commit: f17e7774d7316fc4dda87c5e7d759ac33b20a52f
----------------------------------------
Error: 91> Unrecognized error, please merge or rebase manually.
91> cd /home/user/repos/browser-android-tabs/src/third_party/webrtc && git rebase --onto f17e7774d7316fc4dda87c5e7d759ac33b20a52f refs/remotes/origin/master

**Comment by lfxc** [comment]
is there any work around in the mean time?  thanks

**Comment by SergeyZhukovsky** [comment]
@lfxc we are working on that. The problem that the commit with sha f17e7774d7316fc4dda87c5e7d759ac33b20a52f was removed from webrtc, that's why we cannot get the third_party. The same thing happens if you try to pull and build raw Chromium.

**Comment by samartnik** [comment]
@lfxc you may take the latest master. It is buildable now.

**Comment by lfxc** [comment]
thanks Sergey.  Still received some errors.  I actually started the build process from scratch to make sure:

1) Errors after running sh scripts/getThirdParties.js:

________ running '/usr/bin/python src/build/android/download_doclava.py' in '/home/user/repos/browser-android-tabs'
0> File src/buildtools/android/doclava.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.010931 second(s)
ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'run'


2) Decided to try debug build any way: `ninja -C out/Default chrome_public_apk`

ninja: Entering directory `out/Default'
[25/31] ACTION //chrome/android:chrome_public_apk__create__package(//build/toolchain/android:android_clang_arm)
FAILED: python ../../build/android/gyp/apkbuilder.py --depfile gen/chrome/android/chrome_public_apk__create__package.d --resource-apk=gen/chrome/android/chrome_public_apk/chrome_public_apk.apk_intermediates.ap_ --output-apk=gen/chrome/android/chrome_public_apk/chrome_public_apk.apk_intermediates.unfinished.apk --assets=@FileArg\(gen/chrome/android/chrome_public_apk.build_config:assets\) --uncompressed-assets=@FileArg\(gen/chrome/android/chrome_public_apk.build_config:uncompressed_assets\) --java-resources=@FileArg\(gen/chrome/android/chrome_public_apk.build_config:java_resources_jars\) --dex-file=gen/chrome/android/chrome_public_apk/classes.dex.zip --android-abi=armeabi-v7a --native-libs=\[\"libchromium_android_linker.so\"\] --native-libs=@FileArg\(gen/chrome/android/chrome_public_apk/packed-libs/filelist.json:files\)
Traceback (most recent call last):
  File "../../build/android/gyp/apkbuilder.py", line 320, in <module>
    main(sys.argv[1:])
  File "../../build/android/gyp/apkbuilder.py", line 316, in main
    depfile_deps=depfile_deps)
  File "/home/user/repos/browser-android-tabs/src/build/android/gyp/util/build_utils.py", line 595, in CallAndWriteDepfileIfStale
    pass_changes=True)
  File "/home/user/repos/browser-android-tabs/src/build/android/gyp/util/md5_check.py", line 63, in CallAndRecordIfStale
    new_metadata.AddFile(path, _Md5ForPath(path))
  File "/home/user/repos/browser-android-tabs/src/build/android/gyp/util/md5_check.py", line 381, in _Md5ForPath
    _UpdateMd5ForFile(md5, path)
  File "/home/user/repos/browser-android-tabs/src/build/android/gyp/util/md5_check.py", line 362, in _UpdateMd5ForFile
    with open(path, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'../../braveSync/bundles/bundle.js'
ninja: build stopped: subcommand failed.

**Comment by SergeyZhukovsky** [comment]
You have to pass the getThirdParties.js with success to build it. The error you have is because braveSync project wasn't built. The errors you have above `install` and `run` are probably came from those two commands
`yarn install`
`yarn run build`
Have you installed yarn https://yarnpkg.com/lang/en/docs/install/#linux-tab? We mentioned that in system requirements.

**Comment by lfxc** [comment]
Hi Serg.  started again with a fresh O/S build and fresh install of all dependencies.  On  getThirdParties.js getting this:

.
.
.
Checking connectivity... done.
Submodule path 'niceware': checked out '6d181f20196453da1c5c4f5a27d8be016582c56a'
yarn install v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "eslint-config-standard@6.2.1" has incorrect peer dependency "eslint@>=3.8.1".
warning "eslint-config-standard@6.2.1" has incorrect peer dependency "eslint-plugin-promise@>=3.3.0".
warning "eslint-config-standard@6.2.1" has incorrect peer dependency "eslint-plugin-standard@>=2.0.0".
warning "eslint-config-standard-jsx@3.2.0" has incorrect peer dependency "eslint@>=3.0.0".
warning "eslint-config-standard-jsx@3.2.0" has incorrect peer dependency "eslint-plugin-react@>=2.7.1".
warning "eslint-plugin-react@6.7.1" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
warning "eslint-plugin-standard@2.0.1" has incorrect peer dependency "eslint@>=3.0.0".
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning The case-insensitive file /home/user/repos/browser-android-tabs/src/braveSync/node_modules/browser-launcher/node_modules shouldn't be copied twice in one bulk copy
[4/4] Building fresh packages...
⠁ 
⠁ 




yarn run v1.0.2
$ yarn build-proto && browserify client/sync.js | uglifyjs - > bundles/bundle.js
error Couldn't find the binary yarn build-proto && browserify client/sync.js | uglifyjs - > bundles/bundle.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by samartnik** [comment]
You need to install Node for yarn https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
