### ISSUE TITLE
'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by theScrabi** [brave/browser-android-tabs#395]
I've tried to self build brave, but it seems I'm not able to.

I tried it exactly the way written in the README.me. However when I come to [this](https://github.com/brave/browser-android-tabs#debug) point where I run `ninja -C out/Default chrome_public_apk` I simply get this output:
```
ninja: Entering directory `out/Default'
ninja: error: loading 'build.ninja': No such file or directory
```

The same occurs for release.
I also tried it on different computers:
- Fedora 26., x64
- Mint 18.2 (Ubuntu 16.04), x64, node v8.5.0, yarn v1.0.2

Several things I've noticed running `sh scripts/getThirdParties.js`:
Somewhere in the middle of the log:
```
ERROR: The only supported distros are
 	Ubuntu 14.04 (trusty)
 	Ubuntu 16.04 (xenial)
 	Ubuntu 16.10 (yakkety)
 	Ubuntu 17.04 (zesty)
 	Debian 8 (jessie) or later
```

at the end of the log:
```
cp: Aufruf von stat für 'hashset-cpp/HashSet.cpp' nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: Aufruf von stat für 'hashset-cpp/HashSet.h' nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: Aufruf von stat für 'hashset-cpp/HashItem.h' nicht möglich: Datei oder Verzeichnis nicht gefunde
```
This means could not call cp on 'hashset-cpp/<filename>': File or Directory not found.

The full log can be found [here](https://pastebin.com/raw/DTWUJAx6).

**Comment by SergeyZhukovsky** [comment]
@theScrabi sorry for the long answer. We fixed it. You can try one more time.

**Comment by theScrabi** [comment]
Yep all right workt. But maybe you can help me with this to:
This command `$ ninja -C out/DefaultR chrome_public_apk`
results in this:
```
ninja: Entering directory `out/DefaultR'
[61/30729] ACTION //base:android_runtime_jni_headers__...i_Runtime(//build/toolchain/android:android_clang_arm)
FAILED: gen/android_runtime_jni_headers/base/jni/Runtime_jni.h 
python ../../base/android/jni_generator/jni_generator.py --depfile gen/base/android_runtime_jni_headers__jni_Runtime.d --jar_file ../../third_party/android_tools/sdk/platforms/android-26/android.jar --input_file java/lang/Runtime.class --ptr_type=long --output_dir gen/android_runtime_jni_headers/base/jni --includes ../../../../../../base/android/jni_generator/jni_generator_helper.h --native_exports_optional
Traceback (most recent call last):
  File "../../base/android/jni_generator/jni_generator.py", line 1428, in <module>
    sys.exit(main(sys.argv))
  File "../../base/android/jni_generator/jni_generator.py", line 1421, in main
    GenerateJNIHeader(input_file, output_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 1326, in GenerateJNIHeader
    jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 662, in CreateFromClass
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[70/30729] CC obj/base/third_party/libevent/libevent/buffer.o
ninja: build stopped: subcommand failed.
```

What should I do?

**Comment by SergeyZhukovsky** [comment]
I never seen such error? Are you trying to build on Ubuntu? It is recommended to use Ubuntu.

**Comment by theScrabi** [comment]
Linux mint. (sort of ubuntu).
I've tried on fedora as well, there I came a bit further, but not that much.
Anyway, I'll try to build on a digital ocean server maybe that works.

By the way is debian supported, because id like to write a buildscript for fdroid.

**Comment by SergeyZhukovsky** [comment]
The documentation says that 
The only supported distros are
 	Ubuntu 14.04 (trusty)
 	Ubuntu 16.04 (xenial)
 	Ubuntu 16.10 (yakkety)
 	Ubuntu 17.04 (zesty)
 	Debian 8 (jessie) or later
But I never tried on Debian.

**Comment by theScrabi** [comment]
I see.
Well, I just run the build think with root the first time, and I noticed the script installs several packages (which might be the reason it does not run on other platforms). Also might be the reason I was not able to successfully run the build so far :P
