### ISSUE TITLE
Unable to login at GitHub if 2FA with security key is enabled in GH account

### ISSUE THREAD

**Issue by ayharano** [brave/browser-android-tabs#403]
**Did you search for similar issues before submitting this one?**
Yes. I didn't find anything similar.

**Description:**
I have setup two factor authentication (2FA) in my GitHub account using a desktop browser (probably Chrome, but I don't recall now). I setup both code generation authentication and security key hardware authentication. My security key is a Yubico YubiKey, which uses only USB.

When I try to login into GitHub via Brave Android Play Store version, after providing my correct credentials, a screen pop up and then silently returns to login screen. It doesn't provide any kind of feedback to let the user know why it failed.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1.1
    
**Brave Version:**
1.0.33

**Steps to reproduce:**
    1. Using a compatible desktop browser, setup a GitHub account with two factor authentication enabled both for code generation AND security key hardware authentication.
    2. Using Brave Android Play Store build, login into GitHub providing correct credentials.
    3. It should appear a screen asking for Authentication code.
    4. After providing correct Authentication code, it should login into GitHub account.

**Actual Behavior**
Using Android Brave Play Store build, after providing my correct credentials in step 2, a screen pop up and then silently returns to login screen in step 3. It doesn't provide any kind of feedback to let the user know why it failed and returns to a blank filled login page.

**Expected Behavior**
Using Android Chrome browser, in step 3, Android pops up a system screen asking to the user to enable hardware two step authentication by using Bluetooth or NFC, which, wasn't any of my case. This screen lets the user go back and then Chrome shows a text box letting the user entry 2FA code and then login into GitHub account.

**Is this an issue with Beta build?**
I only tested on Play Store version. So I don't know if this isn't still an issue with Beta build.

**Is this an issue in the currently released version?**
Yes.

**Can this issue be consistently reproduced?**
I hadn't ask to anyone to reproduce this yet, so I cannot answer yet.

**Extra QA steps:**
N/A yet.
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? Not yet, but I don't think it applies to this issue.
  - did you check in Chrome for same behavior? Yes. Chrome shows a screen which appears to be system related. It asks if user wants to enable hardware two factor authentication by using Bluetooth or NFC, which, for my case, is invalid, given that my security key is enabled only via USB.

**Screenshot if needed:**
I had collected some, but I'll post them if needed.

**Any related issues:**
None that I'm aware of.

**Comment by samartnik** [comment]
Wasn't able to reproduce this on my devices. @ayharano could you provide more details (your device and localization)? Could you also check with turned off Brave Shields?

**Comment by ayharano** [comment]
Hello @samatnik.

Device model: ONEPLUS A3010
OxygenOS version: 4.5.0
RAM: 6GB
Storage: 128GB
Android version: 7.1.1
Security patch: August 1st 2017
Kernel version: 3.18.31-perf+ OnePlus@ubintu-64 #1 Sat Sep 23 18:58:09 CST 2017

Language: Portuguese (Brazil)

With Brave Shields turned off, GitHub yields an error message at https://github.com/session with this content: "What‽
Your browser did something unexpected. Please contact us if the problem persists.

Contact Support — GitHub Status — @githubstatus"

Strangely enough, after this error, I opened a new tab with Brave Shields turned on and now it didn't pop any system window, just showing Two-factor authentication input form. Very odd.

**Comment by samartnik** [comment]
Hi @ayharano.
So it's not reproduced anymore on your device? Could that problem be on github.com side at the moment you tried to log in?

**Comment by ayharano** [comment]
So it seems: now I can't reproduce this issue in my device. About it being github.com side of the problem I personally don't think so because in Chrome a system app was triggered. Given that during the issue in Brave Android browser the screen blinked blank, I think there is something related to github trying to trigger that browser/android mechanism and silently failing. Now it doesn't even blink in the screen, so I'm not sure how turning Brave Shield off and then on has a relation to this issue, but it seemed to solve this issue.

You or anyone of the project may close this, but it is interesting to keep just in case anyone has a 2FA hardware issue in the future.

**Comment by samartnik** [comment]
Closing it for now as we don't have enough info to reproduce the issue. Will re-open issue and do more investigation if it pops up again.

**Comment by Pilvinen** [comment]
I'm having this same issue on Brave Android on Huawei P20 Pro.

1) I have a hardware security dongle enabled as primary authentication method, but it doesn't support mobile phones and I only use it on desktop.

2) So when Github doesn't detect the dongle and tries to revert to using Google Authenticator - or other alternative methods - that's where Brave fails.

4) The authentication window pops up real quick and then closes without the option to use any alternative methods throwing me back on the login screen.

This works perfectly on Chrome.

I tried contacting Github customer service on this, but they just told me "Brave is not supported, have a nice day".

A workaround is choosing "Desktop website" from the web page AND selecting "Desktop website" from the Brave menu.

But it's a little bit annoying.

I haven't tested this with the hardware dongle option disabled, but Google Authenticator or other alternative 2FA enabled.
