### ISSUE TITLE
Improve MAU from different app install channels

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#415]

**Comment by AlexeyBarabash** [comment]
This just was merged to master. For now only "Installed from AdWords" event should be sent to MixPanel. Other messages we will enable when will ensure that "Installed from AdWords" works fine, I disabled them to avoid spoiling statistics.

**Comment by SergeyZhukovsky** [comment]
That could be closed. We will reaopen it if any problems.

**Comment by AlexeyBarabash** [comment]
Today I was able to see my closed beta in Google Play (1.0.34) and I found I see no com.android.vending.INSTALL_REFERRER event come from Google Play after the installation. We have to move it to the next milestone.

**Comment by AlexeyBarabash** [comment]
Now detection is enabled again. After the next release, we will see events in MixPanel.

**Comment by AlexeyBarabash** [comment]
This will be tested after release to Google Play. It is impossible to test it by download from github.
Test plan is to see proper events about installations in MixPanel.
At the current moment  no tests  required.
