### ISSUE TITLE
RollingStone.com: zergnet native ad units with shields up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-android-tabs#418]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Zergnet native ads ("around the web") displaying on rollingstone.com with shields up. 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): tablet (nexus9), phone (LG G6)
   - Android Version: 7.1.1 (tablet),  7.0 (phone)
    
**Brave Version:**
1.0.33

**Steps to reproduce:**
    1. Go to rollingstone.com on Android 
    2. Navigate to an article page
    3. Observe "around the web" native ad units served via Zergnet

**Actual Behavior**
![screenshot_20171008-080325](https://user-images.githubusercontent.com/8979240/31318056-cb9e9a92-ac00-11e7-87a3-f84116171cfd.png)
![screenshot_20171008-080619](https://user-images.githubusercontent.com/8979240/31318058-d1f3c0ca-ac00-11e7-8433-8c70dc50a941.png)
![screenshot_2017-10-08-08-56-41](https://user-images.githubusercontent.com/8979240/31318423-34de93b2-ac07-11e7-960f-d84b0d8b594e.png)

**Expected Behavior**
no Zergnet ads

**Is this an issue with Beta build?**
no

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
Yes. Do not recall seeing prior to 1.0.33, as recently as within the past 7 days (today: 10.08.17)

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? yes
  - did you check in Chrome for same behavior? yes

**Screenshot if needed:**

**Any related issues:**

**Comment by lukemulks** [comment]
Ran a quick capture on-device, this appears to be the request and header info: 
```
GET /output.js?id=56033&time=1507476028507&c=0&t=inf-multi&callback=json8301655 HTTP/1.1
Host: www.zergnet.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Nexus 9 Build/N4F27O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Safari/537.36
Accept: */*
Referer: https://www.rollingstone.com/culture/news/ralphie-may-last-comic-standing-comedian-dead-at-45-w507670
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
```
```
HTTP/1.1 200 OK
Date: Sun, 08 Oct 2017 15:20:29 GMT
Content-Type: application/javascript; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Set-Cookie: guid=1613065533; expires=Tue, 07-Nov-2017 15:20:29 GMT; Max-Age=2592000
Set-Cookie: seen_crc=%5B3211710206%2C627811737%2C2451248466%2C2826585553%2C3548575071%2C1061210680%5D; expires=Sun, 15-Oct-2017 15:20:29 GMT; Max-Age=604800; path=/
Set-Cookie: start_id_50=3; expires=Sun, 08-Oct-2017 16:20:29 GMT; Max-Age=3600
Set-Cookie: start_id_269=4; expires=Sun, 08-Oct-2017 16:20:29 GMT; Max-Age=3600
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
P3P: CP="ZergNet does not have a P3P policy. Learn why here: http://www.zergnet.com/p3p"
Content-Encoding: gzip
```

**Comment by lukemulks** [comment]
Confirming Android phone displays as well. 
Will investigate and add filter rule for calls.

**Comment by AlexeyBarabash** [comment]
We have found we need to add a new rule for AdBlocker for this issue.

**Comment by SergeyZhukovsky** [comment]
Pending with that. We will add new rule.
CC @lukemulks @bbondy

**Comment by Jacalz** [comment]
I have verified for iOS and the same thing happens there

**Comment by samartnik** [comment]
https://github.com/brave/adblock-lists/pull/29

**Comment by srirambv** [comment]
Still seeing this in RC2 build as well.

**Comment by samartnik** [comment]
I believe adblock-list is updated once in a day. So probably will need to check it tomorrow.
