### ISSUE TITLE
Some YouTube videos fails to load

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#419]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Reported by Prashant on Brave India Channel and confirmed by @iamVP7 , some YouTube videos fail to load 

**Device Details:**
   - Install Type(ARM, x86): ARM, x86
   - Device(Phone, Tablet, Phablet): Phone, Tablet
   - Android Version: 8.0
    
**Brave Version:**
1.0.30 & 1.0.33

**Steps to reproduce:**
    1. Visit this link https://www.youtube.com/watch?v=2iObySa91b0
    2. Complains of unsupported video format
    3. Open any other suggested video, loads correctly

**Actual Behavior**
Fails to load video 

**Expected Behavior**
Should load the video

**Is this an issue with Beta build?**
N/A

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:** Yes
  - did you check with Brave Shields down? Yes
  - did you check in Chrome for same behavior? Yes, works fine

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/31329702-4475b324-acd3-11e7-8e1f-a0263a890b12.png)

**Any related issues:**
cc: @AlexeyBarabash @samartnik

**Comment by iamVP7** [comment]
Adding @prasanthp96

**Comment by joobus** [comment]
This issue has become much more frequent lately.  YouTube is using a codec that Brace is obviously missing.

**Comment by Tomatoshadow2** [comment]
+1 https://www.reddit.com/r/BATProject/comments/7j2r2i/i_was_more_than_happy_to_delete_the_youtube_app/ User shows same message problem.

**Comment by whour** [comment]
I have the  same problem ,like this url
https://m.youtube.com/watch?feature=youtu.be&v=wrK8Q82X-7M
MSE & H.264 do not support

**Comment by joobus** [comment]
Another example: https://m.youtube.com/watch?v=d4qDdf-fX60

**Comment by eljuno** [comment]
same with #116?

**Comment by SergeyZhukovsky** [comment]
Fixed in https://github.com/brave/browser-android-tabs/issues/116
