### ISSUE TITLE
Don't block ads on a main frame

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#420]
When you search something in google and see an Ad there, we don't allow to open that link. We should allow as it comes from a main frame

**Comment by SergeyZhukovsky** [comment]
Fixed it
https://github.com/brave/browser-android-tabs/commit/806569a2f2e7a042d5ffbf91fa3c2d4dbda20d64

**Comment by LaurenWags** [comment]
STR:
Navigate to google.com
Search for something like pizza.
My first result is for Dominos, which is an Ad.
Attempt to open the Ad.
Get this:
![screenshot_2017-10-10-11-07-07](https://user-images.githubusercontent.com/28145373/31394066-613da754-adab-11e7-92e0-050b00923f8e.png)
