### ISSUE TITLE
Google blocked by Administrator 

### ISSUE THREAD

**Issue by rpeinl** [brave/browser-android-tabs#434]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
I get an ERR_BLOCKED_BY_ADMINISTRATOR every time I try to get from Google Shopping search to the shop that offers the goods. That happens only on Android.  In Windows is everything working as expected.

**Device Details:**
   - Install Type(ARM, x86): Arm
   - Device(Phone, Tablet, Phablet): Phone 
   - Android Version: 7.0
    
**Brave Version:**
latest 

**Steps to reproduce:**
    1. Search in Google Shopping 
    2. click a result 
    3. click the button "to the shop "

**Actual Behavior**
error displayed 

**Expected Behavior**
shopping site displayed 

**Is this an issue with Beta build?**
no

**Is this an issue in the currently released version?**
Yes 

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? yes, it is not enough to disable shield for Google, you have to do it for every shopping site. 
  - did you check in Chrome for same behavior?
yes
**Screenshot if needed:**

**Any related issues:**

**Comment by AlexeyBarabash** [comment]
Hello @rpeinl .
Thanks for the feedback. The issue you have posted is similar to https://github.com/brave/browser-android-tabs/issues/420 . It is fixed in https://github.com/brave/browser-android-tabs/releases/tag/v1.0.35(beta7) and will be pushed to Google Play soon.
