### ISSUE TITLE
home screen bookmarks lost between updates

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#436]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Reported via community, a couple of users have noted that their home screen bookmarks are being lost when updating to each new version, forcing them to recreate these bookmarks each time. Last seen when updating to 1.0.35 (latest release).

https://community.brave.com/t/last-2-android-updates-have-wiped-all-homescreen-bookmarks/8355

**Device Details:**
1. Android Nexus 7 2013 Lineage OS 7.1.2 and Nexus 5X 8.0.0 both using Nova launcher, but tried stock launcher and same happened.
2. Android Huawei P8 Lite 2017 phone running Android 7.0.0 Nougat.
    
**Brave Version:**
last couple of releases including 1.0.35, 1.0.33

**Steps to reproduce:**
    1. Have bookmarks 'added to home screen' from settings.
    2. Update to latest version.
    3. Home screen bookmarks disappear.

**Actual Behavior**
Home screen bookmarks are disappearing.

**Expected Behavior**
Home screen bookmarks should not disappear.

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
I have not reproduced yet, but has been consistently seen by those who have reported it.

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by LaurenWags** [comment]
Additional information provided by user: https://community.brave.com/t/last-2-android-updates-have-wiped-all-homescreen-bookmarks/8355/17

**Comment by anthonypkeane** [comment]
Closing, pls reopen if you see it again. Thanks
