### ISSUE TITLE
have option to remove 'Show all saved Passwords' from display

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#443]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
With cr62 in 1.0.36 (RC) you now get a 'Show all saved passwords' drop down when you tap into a password field. You get this even if 'Save passwords' in settings is off. It would be nice to have a way to turn this off, especially if you don't use the password manager and don't have any saved passwords.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): all
   - Android Version:  all
    
**Brave Version:**
1.0.36(RC)

**Steps to reproduce:**
    1. Navigate to a site like twitter.com, show login fields.
    2. Enter username.
    3. Tap in password field.

**Actual Behavior**
You are asked if you want to 'Show all saved passwords' in a drop down. Selecting this takes you to the password manager.

**Expected Behavior**
Should be a way to disable this option in case users don't want to see this (as of now, if you have save passwords off, you still get this drop down)

**Is this an issue with Beta build?**
RC build yes

**Is this an issue in the currently released version?**
no

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
![screenshot_2017-10-30-14-29-04](https://user-images.githubusercontent.com/28145373/32191463-90b9dee4-bd87-11e7-8c30-b9290b3c3ad5.png)

**Any related issues:**

**Comment by samartnik** [comment]
This is feature of new Chromium. It can be turned on/off via `chrome://flags`. There you can find `enable-manual-fallbacks-filling` flag.
I set it off by default in Brave.
