### ISSUE TITLE
fingerprinting protection bypass

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#444]
this fix needs to be ported to iOS/Android: https://github.com/brave/browser-laptop/issues/11683. i think you should be able to just pull app/extensions/brave/content/scripts/blockCanvasFingerprinting.js from browser-laptop master.

**Comment by SergeyZhukovsky** [comment]
Waiting for the details from @diracdeltas

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-ios/issues/1286#issuecomment-345809803

**Comment by samartnik** [comment]
Not applicable

**Comment by LaurenWags** [comment]
@samartnik if this is N/A, should we remove the milestone and mark as 'invalid'?
