### ISSUE TITLE
Make URL bar suggestions not use google suggest by default

### ISSUE THREAD

**Issue by bbondy** [brave/browser-android-tabs#445]
## Test Plan
https://github.com/brave/browser-android-tabs/issues/445#issuecomment-344993650

**Did you search for similar issues before submitting this one?**
Yes

**Description:**
I think currently it will use google autosuggest, we should disable this by default.

**Comment by SergeyZhukovsky** [comment]
Here is an explanation what does that ticket mean:
- we want an option to disable autosuggest on any search engine and it should be off by default for new installs;
- we have that option currently in `Privacy->Search and site suggestions` and it is on by default;
- show at least alexa top 100 sites to avoid an empty list when that option is off and we have nothing to show there https://github.com/brave/browser-laptop/blob/3597b81d3e60388c9a514ad77b1edbfb04239793/app/common/data/topSites.js

**Comment by LaurenWags** [comment]
Test Plan
Scenario 1 (update using default search engine, setting is on)
1. If not already set, use default search engine (google).
2. Navigate to Privacy > Search and site suggestions, verify this is checked.
3. Update to new build.
4. Navigate to Privacy > Search and site suggestions, verify this is still checked.
5. Open a new tab and type in URL Bar. Verify suggestions shown.

Scenario 2 (update using non-default search engine, setting is on)
1. If not already set, use non-default search engine (any one but google).
2. Navigate to Privacy > Search and site suggestions, verify this is checked.
3. Update to new build.
4. Navigate to Privacy > Search and site suggestions, verify this is still checked.
5. Open a new tab and type in URL Bar. Verify suggestions shown.

Scenario 3 (update using default search engine, setting is off)
1. If not already set, use default search engine (google).
2. Navigate to Privacy > Search and site suggestions, uncheck this option.
3. Update to new build.
4. Navigate to Privacy > Search and site suggestions, verify this is still unchecked.
5. Open a new tab and type in URL Bar. Verify suggestions shown from Alexa top list.

Scenario 4 (update using non-default search engine, setting is off)
1. If not already set, use non-default search engine (any one but google).
2. Navigate to Privacy > Search and site suggestions, uncheck this option.
3. Update to new build.
4. Navigate to Privacy > Search and site suggestions, verify this is still unchecked.
5. Open a new tab and type in URL Bar. Verify suggestions shown from Alexa top list.

Scenario 5 (clean install)
1. Clean install of new build.
2. Navigate to Privacy > Search and site suggestions, verify this is unchecked.
3. Open a new tab and type in URL Bar. Verify suggestions shown from Alexa top list.
4. Modify search engine to be something other than default.
5. Navigate to Privacy > Search and site suggestions, verify this is still unchecked.
6. Open a new tab and type in URL Bar. Verify suggestions shown from Alexa top list.

**Comment by srirambv** [comment]
Scenario 1 & 2 fails. Setting any search engine on the play store and upgrading to beta, Search and site suggestions is always unchecked.

**Comment by AlexeyBarabash** [comment]
There is an updated build https://github.com/brave/browser-android-tabs/releases/tag/v1.0.38(beta1) , it should fix issues 1&2 .

**Comment by srirambv** [comment]
Scenario 1 & 2 works on the new beta

**Comment by LaurenWags** [comment]
Verified scenarios on updated beta build.

**Comment by AlexeyBarabash** [comment]
Now it has been merged to master.

**Comment by AlexeyBarabash** [comment]
Need to test, how it will look if topsites url suggestions will always be turned on.

**Comment by AlexeyBarabash** [comment]
https://github.com/brave/browser-android-tabs/commit/18117cc27d4bf44c98515790b6217bdc5c6350e4
Changes are in master. 
Had to make top 500 relevance lower 100 from 800 to keep results from search higher than results from top 500 sites.

**Comment by LaurenWags** [comment]
@AlexeyBarabash do we only need to update any scenarios in the test plan? Maybe scenario 5? https://github.com/brave/browser-android-tabs/issues/445#issuecomment-344993650

**Comment by AlexeyBarabash** [comment]
Additional test steps for the change of 'keeping top 500 sites suggestions always on'
1. Ensure Privacy > Search and site suggestions is checked
2. Open a new tab
3. Type `ave.` . Expected result - you should see `brave.com` among other results.

**Comment by srirambv** [comment]
With default and custom search engine, the above steps works on x86 device

**Comment by LaurenWags** [comment]
Verified steps from https://github.com/brave/browser-android-tabs/issues/445#issuecomment-344993650 and https://github.com/brave/browser-android-tabs/issues/445#issuecomment-351070925
