### ISSUE TITLE
Autofill dropdown should not contain Chromium

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#45]
![image](https://cloud.githubusercontent.com/assets/17010094/19984944/5fd3202e-a208-11e6-9fc4-837824cd6e92.png)

Text should be `Autofill Settings` instead of `Chromium Autofill Settings`

**Comment by SergeyZhukovsky** [comment]
Fixed it here
https://github.com/brave/browser-android-tabs/commit/a0857a781c38a775f793116ee3b6df476263a27e
