### ISSUE TITLE
Facebook Notifications showing Chrome icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#455]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
Facebook notifications are displaying the Chrome icon on lock screen and notification bar

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): phone
   - Android Version: 5.1, 7.0
    
**Brave Version:**
1.0.36, 1.0.37RC

**Steps to reproduce:**
    1. Login to Facebook on Brave (not Facebook app)
    2. Allow notifications to be pushed.
    3. Continue to use other apps, etc as Brave is backgrounded (or set phone aside and wait for notifications to arrive)

**Actual Behavior**
Notifications are displayed, but use the Chrome icon, not Brave icon.
![chromeicon-a](https://user-images.githubusercontent.com/28145373/32384602-d4883992-c091-11e7-8482-1fb81670b992.png)
![chromeicon-b](https://user-images.githubusercontent.com/28145373/32384605-d771ecd4-c091-11e7-9142-3af0049c1f83.png)

**Expected Behavior**
Notification icons would be displayed using the Brave icon, not chrome icon.

**Is this an issue with Beta build?**
yes

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by AlexeyBarabash** [comment]
Created PR https://github.com/brave/browser-android-tabs/pull/471 .

**Comment by samartnik** [comment]
This is already in master

**Comment by LaurenWags** [comment]
Per discussion, opened https://github.com/brave/browser-android-tabs/issues/484 for update of icon.
