### ISSUE TITLE
Music is not playing on one website

### ISSUE THREAD

**Issue by avently** [brave/browser-android-tabs#456]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Music is not playing when i'm tapping on the play button here: https://datmusic.xyz/?q=Philip%20Glass
Maybe this problem exists with other websites too, i don't know. I checked Chrome from Play Store (61.0.3163.98) and it plays audio like it should. It even plays next audio when first audio ends.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1.2 (Lineage 14.1)
    
**Brave Version:**
1.0.37

**Steps to reproduce:**
    1. Go to https://datmusic.xyz/?q=Philip%20Glass
    2. Tap play button on any song
    3. You will see notification with a song title but with no sound

**Expected Behavior**
Music starts playing

**Is this an issue with Beta build?**
It is the issue with all builds

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Website problems only:**
  - did you check with Brave Shields down?
Yes
  - did you check in Chrome for same behavior?
Yes, Chrome works fine

**Comment by serafeimgr** [comment]
#367 
Also tried on YouTube as i mentioned in #367

**Comment by tbandixen** [comment]
Even if you dont move the app to the background, it does not playback the sound.
Tried it on http://skuizz.com/. The notification is there, but no playback through the speakers, bluetooth doesn't work as well.
