### ISSUE TITLE
Are some option missing?

### ISSUE THREAD

**Issue by xlollomanx** [brave/browser-android-tabs#458]
**Description:** when I open the shield option (clicking brave icon) seems like the are another option at the end because I can see some characters but I cannot scroll down more and see it all. Look the screenshot please.

**Device Details:**
   - Install Type(ARM, x86):arm
   - Device(Phone, Tablet, Phablet): phablet, Oneplus One
   - Android Version: 7.1.2
    
**Brave Version:**
1.0.37

**Steps to reproduce:**
    1.open any sites
    2.click on brave icon to open shield option
    3.scroll until the end and see there are some character that are not visible at all
**Actual Behavior**

**Expected Behavior**

**Is this an issue with Beta build?**
I don't know. I don't know how test it

**Is this an issue in the currently released version?**

**Can this issue be consistently reproduced?**

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
![screenshot_20171108-095729](https://user-images.githubusercontent.com/6764804/32543011-b661eb98-c474-11e7-8a60-3b8b00a40cb2.png)

**Any related issues:**

**Comment by srirambv** [comment]
Which language have you set on the device?

**Comment by samartnik** [comment]
I believe this is Italian. It's just very long translation for 'Fingerprinting Protection' that didn't fit in 2 lines.

**Comment by xlollomanx** [comment]
@srirambv yes it's Italian.

**Comment by samartnik** [comment]
Fixed translation https://github.com/brave/browser-android-tabs/commit/42bcd0929fb3f37936be409538e79281e97d8d62

**Comment by srirambv** [comment]
Works fine
![image](https://user-images.githubusercontent.com/17010094/33881794-d1fce0d2-df2d-11e7-80e4-45f69fc7239a.png)
