### ISSUE TITLE
Google Assistant doesn't always work with Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#459]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Some devices allow for Google Assistant to display its UI when Brave is active, others do not. 

**Device Details:**
   - Install Type(ARM, x86): tested with ARM
   - Device(Phone, Tablet, Phablet): tested with Phones
   - Android Version:  6.0 and above
    
**Brave Version:**
1.0.37

**Steps to reproduce:**
    1. Be sure you are using a device which has Google Assistant
    2. Open an app that is not Brave (slack, instagram, etc)
    3. Say 'OK Google' (if voice activation is enabled) or long press on home button/icon.
    4. Google Assistant UI is displayed.
    5. Exit this app and open Brave.
    6. Say 'OK Google' (if voice activation is enabled) or long press on home button/icon.

**Actual Behavior**
On some devices Google Assistant UI is displayed, on some it is not. Generally though, after performing step 6 while Brave is active, you can still ask voice questions of Google Assistant.

**Expected Behavior**
Google Assistant should open its UI as it does for other apps.

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
On a device where it doesn't work, yes.

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
This is the setting to enable voice activation:

![screenshot_20171108-103129](https://user-images.githubusercontent.com/28145373/32557744-02b3b62e-c471-11e7-95e6-c54fdf55dcdc.png)

**Any related issues:**

**Comment by tbak42** [comment]
On my Pixel 2 phone, the squeeze-to-activate-assistant feature does not work if Brave was the most recent app I used.

1. Go to brave app
2. Squeeze sides of phone
3. The phone vibrates but assistant does not open (incorrect behavior)

This also happens if the phone is locked while Brave was up.

**Comment by eljuno** [comment]
+3 from community https://community.brave.com/t/google-assistant-is-not-working-properly-in-brave/9671?u=eljuno

**Comment by BillTribble** [comment]
Same here on Pixel 2. Pretty annoying. 

This likely to get fixed?

If not, can anyone recommend another browser with adblock? Thanks

**Comment by albergh** [comment]
Just noticed this bug, is working saying OK Google but doesn't show the interface but only a notification. The squeeze is not working .

**Comment by Mixamus** [comment]
The Google Assistant does not pop up in brave on pixel 2 XL with squeezing or saying ok Google. Brave ruining on Android oreo may be the problem

**Comment by emerald210** [comment]
Turning off tracking protection mode in settings fixes the problem.

Settings -> Privacy -> Tracking Protection Mode

**Comment by emerald210** [comment]
Update: False alarm. Google assistant works as expected in the settings menu

**Comment by Ercman99** [comment]
Same problem here on a Verizon Pixel 2 XL.

Brave version 1.0.44

**Comment by fookitt** [comment]
Having the same issue here too with v1.0.52

**Comment by wrkettlitz** [comment]
Same problem here, other apps work fine.

**Comment by Brave-Matt** [comment]
+1 from Zendesk:
![image](https://user-images.githubusercontent.com/3299098/44818384-c6e65880-ab9d-11e8-8c1b-cc48967b55e8.png)

**Comment by mihaiplesa** [comment]
Still happens on 1.0.54, Pixel 2 with Android Pie when using Active Edge (squeeze) or Voice Match.

**Comment by Brave-Matt** [comment]
+1 from Zendesk: 
![image](https://user-images.githubusercontent.com/3299098/45236939-33461380-b292-11e8-855b-18789fcb7a09.png)

**Comment by danieltobey** [comment]
I can recreate this on my Pixel 3. Both the squeeze activate and the press-and-hold home button activate do not work when Brave is open.

**Comment by BillTribble** [comment]
Anyone from the Brave team reading this? Any chance of a fix? It's been
about a year... 🙄

**Comment by saltyzip** [comment]
Same issue here on Pixel XL running Pie, hold down home button on launcher to open assistant and nothing happens. Try with a different application like chrome browser and assistant opens fine.

**Comment by kkinder** [comment]
It's an issue in chromium. Kiwi has the same problem.

In terms of a fix from Brave, this has been an issue for years. It's been a problem with Google Voice Search before there even was a Google Assistant. Brave has ignored the issue for years now, so I wouldn't hold my breath on a fix soon.

**Comment by BillTribble** [comment]
It's weird how they don't seem to be bothered. Perhaps it's because Pixel
has a low market share. Still, you'd have thought they should care -
https://www.theverge.com/2018/10/16/17978244/google-pixel-iphone-xs-camera-best-phone-android-sales-market-share

**Comment by kkinder** [comment]
It did the same thing on my Nexus 6P and my Sony Z5c. It's not a Pixel issue.

**Comment by BillTribble** [comment]
Oh damn!

**Comment by saltyzip** [comment]
If it's an issue in chromium as suggested above, how come Chrome browser doesn't suffer the same problem?

**Comment by beevvy** [comment]
I don't think this is an issue with Chromium. On my Pixel 2 XL, Brave 1.0.72 suffers from this issue, while Chrome, Edge, and LastPass Browser work fine.

**Comment by kkinder** [comment]
I still suggest it's something *in* Chromium that Brave turns on. Chrome doesn't suffer the same issue, but other Chromium-based browsers do.

**Comment by HennyBro** [comment]
This seems to really be a Chromium issue.

**Comment by Samdvich** [comment]
Same problem on the Google Pixel XL

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/ci3a15/unable_to_use_google_assistant_while_brave_open/

@anthonypkeane @EyanGoldman Can we get this knocked off the list? It's been around since 2017 and it's likely that a lot more users are experiencing this even if they're not actively reporting it.

**Comment by benlc** [comment]
Same issue, Google assistant never launches when using brave.

**Comment by Brave-Matt** [comment]
+1
https://community.brave.com/t/unable-to-use-google-assistant-while-using-brave-browser/91203/2

**Comment by anthonypkeane** [comment]
Issue moved to [brave/brave-browser #7350](https://github.com/brave/brave-browser/issues/7350) via [**ZenHub**](https://www.zenhub.com/)
