### ISSUE TITLE
Need search engine bing for new brave android browser

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#46]
_From @netroby on November 3, 2016 8:22_

Please add bing to new brave android browser. There only Google, duckduckgo, baidu, sogou, 360. 

but we need bing. 
Thanks.

_Copied from original issue: brave/link-bubble#865_

**Comment by netroby** [comment]
If we using chinese for android system. the brave does not provide us bing as search engine. 
If we using english for android system. the brave provided bing as search engine. 
very strange problem

**Comment by srirambv** [comment]
+1 on Startpage from [support ](https://linkbubble.zendesk.com/agent/tickets/7075)

**Comment by SergeyZhukovsky** [comment]
Added bing for all locales here https://github.com/brave/browser-android-tabs/commit/392a3174cddcb0bf30960f69d01093fdae504046
