### ISSUE TITLE
String correction

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#463]
Tap and hold on brave icon for this. Note that it says chromium search. Pls brand to Brave.
![screenshot_20171115-224629](https://user-images.githubusercontent.com/12011303/32899321-a8d31cd2-cab8-11e7-9247-0f4927e71600.png)

**Comment by AlexeyBarabash** [comment]
Fixed with commit https://github.com/brave/browser-android-tabs/commit/e6e144afd2ff43e89cc23a4df10cbeb48ad3488f .

**Comment by AlexeyBarabash** [comment]
The steps to reproduce/check issue:
1. press Home phone button to hide all apps
2. long tap on free screen, to see Widgets button
3. There should be Brave bookmarks widget and Brave search widget.

**Comment by srirambv** [comment]
Unable to test this on Yoga Table with x86 version. 
cc: @LaurenWags @kjozwiak to verify on Mobile
