### ISSUE TITLE
Restart prompt should show browser instead of device

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#465]
**Description:**

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/32945890-14adf010-cb8d-11e7-85ed-abf21d0026a7.png)

**Any related issues:**

**Comment by AlexeyBarabash** [comment]
Thanks, this is fixed in 
https://github.com/brave/browser-android-tabs/pull/464/files#diff-543312251cada1b8ce4f9fb2b8a5cf1dR3430 .

**Comment by LaurenWags** [comment]
Test Plan:
Navigate to Settings > Site Settings > Media > Video in Background
Move toggle
Verify you are not instructed to restart Device
