### ISSUE TITLE
'Block phishing' shields setting is actually blocking 3rd party cookies?

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#476]
If so, it needs to say 'block 3rd party cookies' since phishing has nothing to do with 3rd party cookies. (The 'block phishing' setting on laptop controls safebrowsing.)

cc @jhreis if this is an issue also on iOS

**Comment by jamesmudgett** [comment]
Block Phishing based on safebrowsing https://github.com/brave/browser-ios/blob/development/brave/src/webfilters/UrlProtocol.swift (118 & 156)

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett I reopened the ticket as we need to fix that on Android.

**Comment by samartnik** [comment]
Reverted previous title https://github.com/brave/browser-android-tabs/commit/1a24d1cec02c1b6f4935e200ed3e574db015f35a

**Comment by AlexeyBarabash** [comment]
The steps to reproduce/test issue:
1. Launch Brave browser;
2. Press shields button;
3. You should see an item 'Block 3rd party cookies'.
