### ISSUE TITLE
update Brave icon for Facebook Notifications

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#484]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Brave now displays Brave icon for Facebook notifications, but the icon should be updated as it does not display well on older Androids. Below image is from Nexus 5 on 5.1:
![brave_icon](https://user-images.githubusercontent.com/28145373/33895899-8b2d8632-df2f-11e7-8a50-4ac9ed5993e4.png)

**Device Details:**
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version:  all
    
**Brave Version:**
1.0.38

**Steps to reproduce:**
1. Login to Facebook on Brave (not Facebook app)
2. Allow notifications to be pushed.
3. Continue to use other apps, etc as Brave is backgrounded (or set phone aside and wait for notifications to arrive)

**Actual Behavior**
Brave Icon displays with notification but not well.

**Expected Behavior**
Brave icon should look nicer.

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
no (1.0.37)

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? n/a
  - did you check in Chrome for same behavior? n/a

**Screenshot if needed:**
see above

**Any related issues:**
Originally reported and fixed in https://github.com/brave/browser-android-tabs/issues/455
cc @jamesmudgett

**Comment by bradleyrichter** [comment]
The brave outline icon version should be used on dark backgrounds when color is not possible.

![image](https://user-images.githubusercontent.com/13509546/34006078-edb666ec-e0b1-11e7-97af-11c6aaa1101d.png)

Here is an SVG file for the icon:


[brave_icon_outline_white.svg.zip](https://github.com/brave/browser-android-tabs/files/1560217/brave_icon_outline_white.svg.zip)

**Comment by LaurenWags** [comment]
ARM:
![484](https://user-images.githubusercontent.com/28145373/35640243-9defffd4-068a-11e8-93ad-f1dac4e739e0.png)
