### ISSUE TITLE
Home button disappeared

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#486]
Home button disappeared with 1.0.38 build

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/54ae86aa66728b30c50f4a6b336870f006a7002b

**Comment by LaurenWags** [comment]
@samartnik I'm guessing this is only for devices which have the manufacturer provided home button. I don't have a device to verify this, do you?

**Comment by LaurenWags** [comment]
Test Plan:
Verify home button is displayed.
Verify you have the ability to choose whether home button displays (or not) in Settings.

**Comment by LaurenWags** [comment]
Thanks @samartnik !
