### ISSUE TITLE
About in-app browser in Twitter 6.21.0

### ISSUE THREAD

**Issue by vikingkarwur** [brave/browser-android-tabs#49]
Android OS version: 5.0.2

After installing "**Brave Browser : Fast Adblock**", my friend reported that in condition in-app browser "_checked_" (settings => general => use in-app browser)  --- always show the link with Brave Browser.

**Comment by sturmen** [comment]
I'm still seeing this issue: on Android 7.1.1, the official Twitter app (6.35.0), enabling the in-app browser has different behavior between Chrome and Brave. With Chrome as the default browser, links open in a Chrome Custom Tab within the Twitter app. With Brave as the system default, clicking a link leaves Twitter and launches the Brave app in its own process/activity. Is there any way for Brave to copy the Chrome functionality, or is this a decision on Twitter's part?

**Comment by SergeyZhukovsky** [comment]
That one was fixed a while ago
