### ISSUE TITLE
Open YT links inside Brave

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#497]
Currently Android forces to open YouTube app on YouTube links. We want to always open them inside Brave.

**Comment by joobus** [comment]
If you disable/uninstall the YouTube app, then brave can open YT links.

**Comment by LaurenWags** [comment]
Test Plan:
Navigate to a site with a YouTube video (ex: https://www.neowin.net/news/unboxing-the-highly-anticipated-apple-iphone-x )
Play the video.
Tap on the share (arrow) icon and then tap on the URL displayed.
Verify site opens in a new tab, not YouTube app.

cc @SergeyZhukovsky @AlexeyBarabash for confirmation this is sufficient for testing.

**Comment by LaurenWags** [comment]
@srirambv removed x86 tag since test plan was modified
