### ISSUE TITLE
Sync v2: Add QR code generator API

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-android-tabs#498]
For Sync 2 changes, the . Android app must be able to generate a QR code from the sync chain code when one is created. The QR code allows other devices to quickly and easily connect to the creating device by scanning its sync chain code.

![image](https://user-images.githubusercontent.com/13509546/34396850-446c5910-eb25-11e7-8e53-3607d54d1150.png)

**Comment by samartnik** [comment]
This is already implemented
