### ISSUE TITLE
Sync v2: Add new device choice screen in Create Sync Chain flow

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-android-tabs#501]
The new flow on all platforms adds a new screen that offers the user a choice of adding a mobile device or a laptop. This step helps guide the user to use the most likely sync code input method for that device.

The user can still switch to the alternative input method if needed.

(ios screen shown below)
![brave 1 6 sync](https://user-images.githubusercontent.com/318119/34884729-4125c7b8-f783-11e7-887a-955dea483de2.png)

**Comment by samartnik** [comment]
Duplicate https://github.com/brave/browser-android-tabs/issues/499
