### ISSUE TITLE
Brand string Chromium

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#502]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
Somewhere Chromium is displayed instead of Brave

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1
    
**Brave Version:** 1.0.40

**Steps to reproduce:**
    1. Get clean installation of Brave
    2. Go to duckduckgo.com
    3. Long press on image => Download link
   

**Actual Behavior**
The message says `Chromium needs storage access to download files`.

**Expected Behavior**
The string `Brave needs storage access to download files`

**Can this issue be consistently reproduced?** yes

**Screenshot if needed:**
![screenshot_20171228-202127](https://user-images.githubusercontent.com/24739341/34419509-f511aa12-ec0c-11e7-9c38-e1cb4f809725.png)

**Comment by LaurenWags** [comment]
x86 device on 1.0.41
![screenshot_20180131-120932](https://user-images.githubusercontent.com/28145373/35637010-e49fb5e6-0680-11e8-8824-9bf861ce7839.jpg)

**Comment by LaurenWags** [comment]
ARM:
![screenshot_20180131-123336](https://user-images.githubusercontent.com/28145373/35637765-3909e910-0683-11e8-9c31-2572d803993f.png)
