### ISSUE TITLE
Clear Browsing Data doesn't clear data

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#51]
Clear Browsing Data doesn't clear data history still shows all the history

Device: Yoga Tablet 2 
Android: 5.0.1
Brave: 1.0.3

![brave_android](https://cloud.githubusercontent.com/assets/17010094/20099689/c48dd0ca-a5b1-11e6-93e9-86e6c06b4639.gif)

**Comment by SergeyZhukovsky** [comment]
@srirambv There is a drop down on the top of Clear browsing data menu. It says to clear for the past hour only. You can select past week for example and it'll clear.

**Comment by srirambv** [comment]
My bad. I didn't check that. Closing the issue
