### ISSUE TITLE
Some YT links don't play in background

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#511]
Here is an example of the video
https://www.youtube.com/watch?sns=tw&v=kVafBagmNg0&app=desktop

**Comment by AlexeyBarabash** [comment]
This should be fixed by https://github.com/brave/browser-android-tabs/pull/517 .

**Comment by LaurenWags** [comment]
Test Plan:
Ensure setting for playing media in background is enabled.
Navigate to YouTube link above and start video.
Navigate to another tab. Verify video still plays.
Background Brave. Verify video still plays.
Turn off screen. Verify video still plays.

cc @SergeyZhukovsky @AlexeyBarabash for confirmation this is sufficient for testing.

**Comment by srirambv** [comment]
Video stops playing when tab switches/app is backgrounded/screen locked when playing the video https://www.youtube.com/watch?sns=tw&v=kVafBagmNg0&app=desktop

Doesn't happen for other videos. 
Issue reproduced on ARM device by @LaurenWags

**Comment by LaurenWags** [comment]
I noticed that the page tells me 'We've redirected you to the desktop site'. If I tap on the 'mobile' link, I can play the video in background.

**Comment by AlexeyBarabash** [comment]
Yes, I tested the mobile version of the link.
But desktop version should also work. Thanks for finding @LaurenWags , I move this issue to the next roadmap, as it is not fixed completely.

**Comment by AlexeyBarabash** [comment]
New PR, should fix this issue with Desktop version of video.
https://github.com/brave/browser-android-tabs/pull/536 .

**Comment by srirambv** [comment]
Video playback works as expected but keeps showing the desktop URL detected message

**Comment by btlechowski** [comment]
Verified Samsung s7 1.0.42RC
