### ISSUE TITLE
[Feature Request] Add Round/Circular icon for Android 7.1+

### ISSUE THREAD

**Issue by rodrigoswz** [brave/browser-android-tabs#52]
Android 7.1 has a feature that an app can use a [circular icon to match all other icons](http://android-developers.blogspot.com.br/2016/10/android71-dev-preview-available.html).
So far this is an exclusivity of Google Pixel devices (or for any device running a 7.1 Custom ROM that supports this feature). But soon more devices will appear that use this functionality, [it depends only on the manufacturer](http://www.xda-developers.com/psa-android-7-1-circular-icon-support-is-determined-by-the-oem/).

I made a circular icon for Brave with Android Studio, it's using the same background color as Brave icon for iOS.
If you guys like it, you can use this, obviously. The download link of all sizes is at the bottom of this issue.

![ic_launcher-web](https://cloud.githubusercontent.com/assets/14058427/20102434/3f7bece0-a5ad-11e6-8762-bb2690f5d7fb.png)

Here the link for all sizes: https://drive.google.com/file/d/0BzkwxIh2-kkYb2FMSHdmVy15UFE/view?usp=sharing

**Comment by SergeyZhukovsky** [comment]
Thanks @rodrigoswz. @bradleyrichter what do you think about that?

**Comment by anthonypkeane** [comment]
Closing
