### ISSUE TITLE
Twitch videos autoplay muted

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#531]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When using 1.0.41, Twitch videos autoplay and you must tap on them to unmute. In 1.0.40 the videos did not autoplay, you had to tap on them to start the video.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): phone
   - Android Version: 5.0
    
**Brave Version:**
1.0.41

**Steps to reproduce:**
    1. Navigate to twitch.tv
    2. Tap on one of the channels listed on the main page.
    3. Tap on a video.

**Actual Behavior**
Video auto plays, but is muted.

**Expected Behavior**
In 1.0.40 video did not play until you tapped on the play icon.

**Is this an issue with Beta build?**

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by srirambv** [comment]
Also noticed the video remains blank but shows the video muted message

**Comment by LaurenWags** [comment]
Retested this with 1.0.40 again - some videos I see what I originally reported, I have to tap on the video to start it. Other videos I see same behavior as in 1.0.41 where the video plays automatically but is muted.

**Comment by samartnik** [comment]
This behavior comes from twitch itself. We have the same result on laptop browser, if we open mobile version of the website.

**Comment by LaurenWags** [comment]
@samartnik so this should be labelled `won't fix` with the instruction to use the desktop version of the tab?

**Comment by samartnik** [comment]
Yes, use desktop version or just tap to unmute.
