### ISSUE TITLE
Provide an option to exit from settings menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#532]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Provide an option to exit from settings menu

**Device Details:**
   - Install Type(ARM, x86): Both
   - Device(Phone, Tablet, Phablet): All
   - Android Version:  All
    
**Brave Version:**
1.0.41

**Steps to reproduce:**
    1. Go to media settings under site settings
    2. Its a long way tap back to app 
    3. 

**Actual Behavior**
https://youtu.be/AsMVmxQ8aDs

**Expected Behavior**
Having an exit button on the right corner of settings menu helps come out instead of tapping so many screens to exit settings

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by deeppandya** [comment]
@srirambv should we have **Close** button for only **Site settings** or for all settings options ? and if you press the close button, where it should go ? **New tab** or **Settings page** ?

**Comment by deeppandya** [comment]
@EyanGoldman what's your opinion on my above comment ?

**Comment by EyanGoldman** [comment]
1. Just what @srirambv showed (settings, not site settings).
2. Should take you back to the page that you opened the settings menu on

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 rc1
* Verified close button is shown on setting and nested settings page
* Verified tap on close button closes settings page and returns to the active tab
[exit button.zip](https://github.com/brave/browser-android-tabs/files/3617542/exit.button.zip)
