### ISSUE TITLE
Remove twitter lite hardcode

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#546]
Currently we do a shortcut to a twitter lite app when adding a twitter link to a homescreen. We need to add Brave's link in that case.
https://twitter.com/sil/status/959611443665690629

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/615

**Comment by samartnik** [comment]
To test it go to twitter.com and click `Add to Home screen`. Created shortcut should be opened in Brave.

**Comment by LaurenWags** [comment]
Note - if you had this shortcut added prior to 1.0.47, it will still open Twitter Lite. If you remove/re-add after installing 1.0.47, Twitter will open in Brave and not open Twitter Lite. Can you confirm if this is ok/expected? @SergeyZhukovsky @samartnik

**Comment by samartnik** [comment]
Yes, this is expected behavior.
