### ISSUE TITLE
Shields shows active colour when page is scrolled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#550]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Shields shows active colour when page is scrolled

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Mi Max 2 
   - Android Version: Android v7.1.1 Nougat with Miui 9.2.1 operating system 
    
**Brave Version:**
1.0.41

**Steps to reproduce:**
    1. Clean install Brave from app store
    2. Login to facebook.com and disable shields
    3. Scroll up, disabled shields icon momentarily changes to active shields icon

**Actual Behavior**
Shields shows active colour when page is scrolled

**Expected Behavior**
Shouldn't change colour of shields when page is scrolled

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by yachtcaptain23** [comment]
Just in case this gets revisited: I believe the solution is correctly addressed in https://github.com/yachtcaptain23/browser-android-tabs/pull/1

**Comment by samartnik** [comment]
Fix works on my devices. Created new PR. Thanks @yachtcaptain23

**Comment by SergeyZhukovsky** [comment]
thanks @yachtcaptain23 !

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/618
