### ISSUE TITLE
jsfiddle doesn't show output window with adblock enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#554]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
jsfiddle doesn't show output window with adblock enabled

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 5.0.1
    
**Brave Version:**
1.0.42 (Chromium .137)

**Steps to reproduce:**
    1. Clean install RC build
    2. Visit https://jsfiddle.net/7ke9r14a/7/
    3. Output window shows sad face, doesn't allow to check out put

**Actual Behavior**
jsfiddle doesn't show output window with adblock enabled

**Expected Behavior**
Adblock shouldn't block the output window

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/36147230-6d369742-10dd-11e8-80fb-4a0de722488f.png)
On playstore build
![image](https://user-images.githubusercontent.com/17010094/36147484-6e22ae92-10de-11e8-9d0e-215217cea5a2.png)

**Any related issues:**
Issue verified on ARM by @btlechowski

**Comment by samartnik** [comment]
Reverted commit that caused the problem

**Comment by btlechowski** [comment]
Verified 1.0.48RC2
Samsung s7
