### ISSUE TITLE
Bugged keyboard on google.com

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#555]
**Device Details:**
   - ARM
   - Phone
   - Android Version: 7.0.0
    
**Brave Version:**
1.0.42 (Chromium .137) RC

**Steps to reproduce:**
1. (If applicable) Uninstall Brave
2. Install Brave
3. Go to google.com
4. Type into google.com input field

**Actual Behavior**
The keyboard is bugged. Can not type. Keyboard does not hide on unfocus

**Expected Behavior**
Can type into the input field

**Can this issue be consistently reproduced?**
100%

**Notes**
Also reproducible on youtube.com

**Comment by srirambv** [comment]
Seeing this behaviour on upgrade from current build as well

**Comment by samartnik** [comment]
It was caused by proguard setting https://github.com/brave/browser-android-tabs/commit/9c9a2bec23244f824f205e2484fd217957185bee
Reverted it back

**Comment by btlechowski** [comment]
Verified 1.0.42(RC2) Samsung s7

**Comment by srirambv** [comment]
Verified working on RC on Lenovo Tablet
