### ISSUE TITLE
update to HTTPS Everywhere 6.0

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-android-tabs#558]
see https://github.com/brave/browser-ios/issues/1460 for details

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/2aa28ca9f039696227ba6b5829079b81210821d2

**Comment by LaurenWags** [comment]
Test Plan (from https://github.com/brave/browser-ios/issues/1460):

Go to http://www.haproxy.org/. It should be upgraded to HTTPS
Go to http://www.thompsonhotels.com/. Images should appear on the site.
Go to https://https-everywhere.badssl.com/. Under shields, it should show 1 HTTPS upgrade.
