### ISSUE TITLE
third party cookies won't stay enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#561]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
Enabling 'Allow third-party cookies' does not remain enabled if you close/relaunch Brave.

**Device Details:**
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
    
**Brave Version:**
1.0.42

**Steps to reproduce:**
1. Launch Brave for Android
2. Menu > Settings > Site Settings > Cookies
3. Turn on “Allow third-party cookies” checkbox.
4. Back, Back, Back
5. Menu > Exit
6. Launch Brave again and go back into the Cookies screen (i.e., repeat steps 1-2)

**Actual Behavior**
Note “Allow third-party cookies” checkbox is off.

**Expected Behavior**
“Allow third-party cookies” checkbox should be checked.

**Is this an issue with Beta build?**
no

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? n/a
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

cc @samartnik @AlexeyBarabash @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Reported fixed with 1.0.43(RC1) - https://community.brave.com/t/third-party-cookies-wont-stay-enabled-android/17128/3

Confirmed on ARM device. @srirambv could you try it on x86 when you get a chance?

**Comment by SergeyZhukovsky** [comment]
@LaurenWags @srirambv yep sorry, it looks like I forgot to include it to 1.0.43 milestone. I fixed it while I was redoing adblock lists update to execute every 2 hours.

**Comment by LaurenWags** [comment]
Thanks @srirambv for checking!

No problem @SergeyZhukovsky - the user who reported it fixed was happy 😄 I'm going to close this one out.
