### ISSUE TITLE
Ads and Tracker blocking stops working for a persiod of time

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#566]
**Description:**

Sometimes Brave gets into a state where it stops blocking ads even though the shield is enabled. When I got home from the Brave All-Hands, I noticed that every website that I visited was displaying ads. The shield was enabled, but Brave would show `0 Ads and Trackers` on every single website. I tried the following:

* disabling/enabling shields
* disabling/enabling `Ads and Trackers`
* closing/reopening websites
* refreshing the website several times
* closing/reopening brave
* disabling/enabling `Ads and Trackers` via settings

None of the above worked and Brave was still displaying ads. After ~30min or so, I noticed that the shields were finally blocking ads and updating the stats correctly.

FYI, all other components of the shield worked (Scripts) during this time.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Google Pixel 2 XL (Phone)
   - Android Version: 8.1.0
    
**Brave Version:**

Using `Brave 1.0.42, Chromium 64.0.3282.137`

**Steps to reproduce:**

N/A.. Still needs some investigation. I've only ran into this once.

**Actual Behavior**

Brave displaying ads on every single website even though shields are enabled. `Ads and Trackers` appearing as `0`.

**Expected Behavior**

Brave should be blocking all ads and updating the `Ads and Trackers` stats as expected.

**Is this an issue with Beta build?**

I'm not sure, I can't reproduce this consistently and personally only ran into it once.

**Is this an issue in the currently released version?**

Yes, reproduced using `Brave 1.0.42, Chromium 64.0.3282.137`

**Can this issue be consistently reproduced?**

Nope... I couldn't find any consistent STR.

**Screenshot if needed:**

Initially noticed that ads were being displayed, example:

![screenshot_20180308-153644](https://user-images.githubusercontent.com/2602313/37306984-dd22c93a-260f-11e8-8c5f-9c72df61a97a.png)

Shields enabled but Brave displays `0 Ads and Trackers`, example:

![screenshot_20180308-155949](https://user-images.githubusercontent.com/2602313/37307036-03bfe244-2610-11e8-9de7-78a6ff279f07.png)

After about ~30min or so, brave shield started to block `Ads and Trackers` once again, example:

![screenshot_20180308-162926](https://user-images.githubusercontent.com/2602313/37307087-2678d110-2610-11e8-8c72-c3317a5e0e6d.png)

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/ads-are-not-blocked-anymore/17627

**Comment by SergeyZhukovsky** [comment]
Perhaps it is related to the new easylist release. We do the recovery and new files download only on browser restart. I made a PR that checks on the update every 2 hours and makes the recovery in case of corrupted downloads faster https://github.com/brave/browser-android-tabs/pull/567

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/567

**Comment by kjozwiak** [comment]
As per earlier conversation with @bbondy and @SergeyZhukovsky, marking this `QA/no-qa-needed`.
