### ISSUE TITLE
Shields not working on Cr65 branch

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#573]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Shields not working on Cr65 branch

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Lenovo Yoga Tablet
   - Android Version: 5.1
    
**Brave Version:**
1.0.43 (CR 65.0.3325.109)

**Steps to reproduce:**
    1. Clean install brave
    2. Open any site, shields is disabled
    3. Tap on shield, doesn't work

**Actual Behavior**
https://youtu.be/cAKwBcFCcJ8

**Expected Behavior**
Shields should work

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by btlechowski** [comment]
Does not reproduce on Samsung s7(ARM)

**Comment by LaurenWags** [comment]
I was not able to reproduce this on my x86 device with https://github.com/brave/browser-android-tabs/releases/tag/v1.0.43(RC1)

**Comment by srirambv** [comment]
Seems to work now. Closing the issue
