### ISSUE TITLE
Twitch video quality settings are missing

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#575]
**Did you search for similar issues before submitting this one?**
Yes

**Device Details:**
Samsung s7 ARM
    
**Brave Version:**
v1.0.43(RC1)

**Steps to reproduce:**
    1. Play a twitch video
    2. Go to video settings->Quality

**Actual Behavior**
A list of video resolutions are missing
Only 'Auto' is shown.

**Expected Behavior**
Video quality settings are displayed, just like in Chrome

cc @srirambv @kjozwiak @LaurenWags @samartnik @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Reproduced on x86

**Comment by kjozwiak** [comment]
Seeing the same thing with Pixel 2 XL running 8.1.0. Also reproducible on `v1.0.42, CR: 64.0.3282.137`.

**Comment by btlechowski** [comment]
Not reproducible in v.1.0.44(RC1) Samsung s7
