### ISSUE TITLE
Brave gives permissions for Google by default.

### ISSUE THREAD

**Issue by Lululalu** [brave/browser-android-tabs#578]
Brave allows Google and other search engines to access location and notifications by default. 

IMO it's a privacy violation.
![screenshot_20180321-215224](https://user-images.githubusercontent.com/32398857/37745263-a7f0a698-2d52-11e8-8ffb-ddcdb88aaaf8.jpg)

**Comment by flamsmark** [comment]
Wasn't able to repro this. If the issue persists with a fresh install, please comment here again.

**Comment by Lululalu** [comment]
@flamsmark Yes, it still happens after a fresh installation. Brave gives these permissions for Google without asking my permission first. The same is not true for Samsung Internet for example.

**Comment by samartnik** [comment]
To test it go to `Settings > Search engine` and make sure that Location and notifications are not allowed for default search engine by default.

**Comment by LaurenWags** [comment]
Confirmed on ARM device by @kjozwiak (Pixel 2XL running 8.1.0) and myself (Nexus 5 running 5.1.0)

Note:
* clean install of 1.0.47 removes 'Locations and notifications' permissions
* update to 1.0.47 retains the 'Locations and notifications' permissions.
Confirmed these are expected with @samartnik
