### ISSUE TITLE
Question: System requirements

### ISSUE THREAD

**Issue by bn0785ac** [brave/browser-android-tabs#579]
What android version should i have for use https://github.com/brave/browser-android-tabs/releases/tag/v1.0.43(RC1)

?

**Comment by Tomatoshadow2** [comment]
I use the normal apk build.

**Comment by SergeyZhukovsky** [comment]
Bravearm.apk is for ARM CPU based devices, Bravex86.apk is for x86.

**Comment by bn0785ac** [comment]
@SergeyZhukovsky sorry if i've used a bad link.

but i've talking about android brave (for tablet, from googleplay)
