### ISSUE TITLE
ANR on launch when connected to WiFi w/o internet

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/browser-android-tabs#585]
I looked a bit for this and couldn't find any that seemed similar. Sorry if duplicating something obvious.

I had the ever fun experience today of waking up and finding out my internet was out. My phone had the "Connected, no internet" status -- connected to my WiFi network, but not able to make any outward connections. I tried to launch Brave from a clean state (no tabs), and the app hung indefinitely. Eventually I got the "App not responding" message from Android, and it closed. I was able to replicate this a number of times before leaving for work and (unfortunately) when I came home and my internet was still out. I believe at that point I *may* have had tabs open, but it was a cold launch again.

I'm not sure what would cause this unless there's some sort of phone home going on at launch. I haven't looked through the code yet to see where this might be happening, but hey -- with the frequency of issues here lately, I could probably reproducibly test this for you.

Device -- Nexus 5x, Android 8.1
Brave -- 1.0.43, Chromium 65.0.3325.109

**Comment by samartnik** [comment]
Not reproducible on our devices. @shortstuffsushi are you sure it didn't try to open some specific tabs? Can you try it on the latest version to see if it's still reproducible on your side?

**Comment by shortstuffsushi** [comment]
Hey @samartnik, sorry for the super long delay. I am no longer able to reproduce this issue, so I'll assume it was fixed in one of the versions since my logging this issue.
