### ISSUE TITLE
Shield: block cookies per site

### ISSUE THREAD

**Issue by D0ve** [brave/browser-android-tabs#589]
As we stand for strong privacy, we should have 'block cookies per site' switch in Shields!
Brave for Android doesn't have  'block cookies per site'  switch yet!
Shields in Android browser should be equal to Desktop version!

**Comment by flamsmark** [comment]
Please don't open duplicate issues just because someone closes the existing issue. If you think the closure was an error — as in this case — please just say so in the original issue.

**Comment by D0ve** [comment]
Firstly, I said about reopen the first issue, than I saw that you thought about block cookies globaly, that's already present, yes.
So this issue is not a duplicate!
