### ISSUE TITLE
Contains MixPanel tracker

### ISSUE THREAD

**Issue by Fregf** [brave/browser-android-tabs#602]
I installed the Exodus Privacy Android app, and I was surprised to see that it says that Brave contains the MixPanel tracking software: https://reports.exodus-privacy.eu.org/reports/7045/

I had expected a browser which uses privacy as a unique selling point, not to containing tracking software itself. Please remove it.

**Comment by SergeyZhukovsky** [comment]
@Fregf we don't use it. We disabled sending metrics a while ago. But we commented the pieces of code, we will investigate how does Exodus detect it.

**Comment by samartnik** [comment]
This will be removed starting from 1.0.45 version
