### ISSUE TITLE
Turn on regional ads block for all locales

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#622]

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/52ebccd448cefd1f7bb452c8cbc6648ed936d6ca

**Comment by samartnik** [comment]
To test it set French locale and make sure that 'Settings > Privacy > Regional Ad Block' is on.

**Comment by LaurenWags** [comment]
@samartnik I did a clean install (not update) on one of my devices (I didn't change the location/language) and Settings > Privacy > Regional Ad Block' is on. Is this expected?

**Comment by samartnik** [comment]
Yes, it should be on with clean install on any locale.

**Comment by srirambv** [comment]
Verified it on French, Portuguese and Chinese locale.

**Comment by LaurenWags** [comment]
Confirmed on ARM device by @kjozwiak (Pixel 2XL running 8.1.0) and myself (Nexus 5 running 5.1.0)
