### ISSUE TITLE
Test a few https redirects

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#626]
We had a regression in 1.0.47. There are crashes in HTTPSE redirect checks. No STR unfortunately. We fixed it via crash dumps.

**Comment by GeetaSarvadnya** [comment]
Tested few websites (twitter, cnet, nytimes, youtube and facebook) with http:
All the web sites are redirecting to secure site https. 

Tested on Android version 5.1

**Comment by LaurenWags** [comment]
Verified sites from https://github.com/brave/browser-android-tabs/issues/626#issuecomment-387160606 using 1.0.48 on ARM device as well.

**Comment by srirambv** [comment]
Verified the following sites
https://orimi.com - Shows insecure connection, proceeding shows forbidden message
https://pdf995.com - Shows connection is insecure but loads the page
http://github.com - auto redirects to https
http://m.twitch.tv - auto redirects to https
http://github.com - auto redirects to https
