### ISSUE TITLE
removing "passwords.google.com" from password settings

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#635]
**Description:**

When viewing saved passwords, you'll notice the following:

```
View and manage saved passwords at
passwords.google.com
```

We should remove this line from password settings.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 2 XL
   - Android Version: 8.1.0 (Sec Patch Level: May 5th)
    
**Brave Version:**

* `Brave 1.0.48, Chromium 66.0.3359.158`

**Steps to reproduce:**
    1. tap on the kabob and select `Settings`
    2. tap on `Passwords`

**Actual Behavior**

![screenshot_20180424-235119](https://user-images.githubusercontent.com/2602313/40275241-a1e3fd06-5bb8-11e8-970a-f09a77639236.png)

**Expected Behavior**

We shouldn't be displaying `passwords.google.com` under the Password settings as Brave doesn't use Google's services.

**Is this an issue with Beta build?**

Yes

**Is this an issue in the currently released version?**

Yes

**Can this issue be consistently reproduced?**

100% reproducible using the above STR.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/4549c8f2dd2e58de9d5242c7962ed15a6148fa91

**Comment by GeetaSarvadnya** [comment]
Verified on Android ARM with 
*  745155e
