### ISSUE TITLE
removing google support link from "details" under the green lock modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#636]
**Description:**

When a user taps on the green lock icon in the URL and selects `What do these mean?` under `Details`, they'll be taken to a Google Support page explaining what `secure connection` means. From my understanding, we should be pointing users to a Brave resource instead.

**Device Details:**
   - Install Type(ARM, x86): `ARM`
   - Device(Phone, Tablet, Phablet): `Pixel 2 XL`
   - Android Version: `8.1.0 (Sec Patch Level: May 5th)`
    
**Brave Version:**

* `Brave 1.0.48, CR 66.0.3359.158`

**Steps to reproduce:**

 1. Visit https://duckduckgo.com
 2. tap on the HTTPS green lock that appears next to the URL bar
 3. tap on `Details` -> `What do these mean?`
 4. you'll noticed that you'll be taken to a `https://support.google.com` page

**Actual Behavior**

Users that click on `What do these mean?` in the HTTPS modal when clicking on the lock will be forwarded to a Google support page.

**Expected Behavior**

Should take the user to a Brave resource rather than using Google's support pages.

**Is this an issue with Beta build?**

Yes

**Is this an issue in the currently released version?**

Yes

**Can this issue be consistently reproduced?**

100% reproducible using the above STR.

**Comment by flamsmark** [comment]
Do we have Brave resources on this, and is that something that we want to maintain long-term?

**Comment by kjozwiak** [comment]
@flamsmark I don't think we have any resources available in terms of explaining to users what a secure connection is and how it works.

Maybe this particular issue should be marked as `wontfix`. However, I do remember a few folks mentioning that we should be removing all Google branding/links/properties. This was a while back and I'm not sure if it includes support pages.

**Comment by flamsmark** [comment]
We should get a conclusion on that. IMO, we shouldn't add maintenance load with support materials. I understand the desire to remove Google branding &c. I also think that support pages provide useful information for the users who choose to access them. We should weigh those things together to work out what to do?

**Comment by samartnik** [comment]
Removed that link for now, will re-add it when/if have appropriate link to show.
https://github.com/brave/browser-android-tabs/issues/635

**Comment by GeetaSarvadnya** [comment]
Verified on Android ARM with 
*  745155e
