### ISSUE TITLE
Implement UI for DDG private search

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#651]

**Comment by samartnik** [comment]
Steps for QA:
1. Open `New private tab`.
2. DDG offer should pop up once, if DDG in not default search engine for Private tabs;
3. Next time when open `New private tab`. If DDG is not default search engine for Private tabs, there should be learn more link and DDG logo. When you click on link or logo DDG offer pops up. Otherwise there won't be DDG log and learn more link.
Additional things to check: there were added ability to set separate default search engine for private and standard tabs in settings. Make sure that each tab uses its search engine.

**Comment by srirambv** [comment]
Verified on Lenovo Yoga Tablet running x86 build
