### ISSUE TITLE
gn file not found

### ISSUE THREAD

**Issue by jaspreet1990** [brave/browser-android-tabs#668]
gn file not found

after executing this script
 
![brave-error](https://user-images.githubusercontent.com/4599180/41834151-c04782de-7870-11e8-83bf-7140b6ed4a25.png)

**Comment by samartnik** [comment]
`gn` is part of 'depot_tools'. Make sure you set proper path to it.

**Comment by jaspreet1990** [comment]
It is alreay set ,please see this
![brave1](https://user-images.githubusercontent.com/4599180/41839237-4d0d135a-7880-11e8-9ad5-3455f741ad07.png)

![brave2](https://user-images.githubusercontent.com/4599180/41839235-4cd363a8-7880-11e8-9f02-4ffe9197632b.png)

**Comment by samartnik** [comment]
For some reason it doesn't see it. Both `gclient` and `gn` are part of `depot_tools`. You can go inside of `depot_tools` folder and see them. How did you set path to `depot_tools`? Is it in `.bashrc` file? Did you restart bash after editing `.bashrc`?
