### ISSUE TITLE
removing "send google system information" from certificate errors

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#674]
**Description:**

When receiving a certificate error, you'll notice that following checkbox is being displayed along side the certificate error:

> Automatically send some system information and page content to Google to help detect dangerous apps and sites. Privacy Policy.

We should remove the entire text that states information will be sent back to Google when taping on the checkbox mentioned above.

**Device Details:**
   - Install Type(ARM, x86): `ARM`
   - Device(Phone, Tablet, Phablet): `Pixel 2 XL`
   - Android Version: `8.1.0 (Security Patch Level: June 5, 2018)`
    
**Brave Version:**

* `Brave 1.0.51, CR: 67.0.3396.87`

**Steps to reproduce:**
    1. open brave & load `expired.badssl.com`

**Actual Behavior**

![screenshot_20180613-112324](https://user-images.githubusercontent.com/2602313/41946251-62bcd190-797f-11e8-8e6f-2dc961271c10.png)

**Expected Behavior**

We shouldn't be displaying the above checkbox. Users on brave shouldn't be sending data back to Google.

**Is this an issue with Beta build?**

Yes, I'm assuming this is being displayed on all Brave versions.

**Is this an issue in the currently released version?**

Yes, currently reproducible on `Brave 1.0.51, CR: 67.0.3396.87`

**Can this issue be consistently reproduced?**

Yes, 100% reproducible using the above STR.

**Comment by Tomatoshadow2** [comment]
@kjozwiak I don't see the message listed, when I go to the link, using the latest beta build. Does it matter if the site was sent a request in a private tab?

**Comment by samartnik** [comment]
I also can't see that message on 1.0.52. @kjozwiak could you recheck if this issue still applicable on the latest version?

**Comment by kjozwiak** [comment]
> I also can't see that message on 1.0.52. @kjozwiak could you recheck if this issue still applicable on the latest version?

@samartnik, I can still see this message on a brand new installation. Just went through the following STR:

* downloaded & installed the latest Brave from GPS
* checked that `Brave 1.0.52 CR: 67.0.3396.87` was installed via the settings
* visited https://expired.badssl.com and noticed the same message.

I also checked `Brave 1.0.53 (alpha), CR: 67.0.3396.87` and managed to see the same message using the above STR. @samartnik let me know if there's anything else that I can provide!

**Comment by btlechowski** [comment]
Verified on Samsung s7 ARM, v1.0.54RC1
