### ISSUE TITLE
webm doesn't work?

### ISSUE THREAD

**Issue by canyoudev** [brave/browser-android-tabs#675]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
webm format videos doesn't play in browser.

**Device Details:**
   - Install Type(ARM, x86): 
   - Device(Phone, Tablet, Phablet): Moto G4
   - Android Version: 7.1.2
    
**Brave Version:**
1.0.51

**Steps to reproduce:**
    1. Go to http://boards.4chan.org/wsg/ (work safe)
    2. webm doesn't play

**Actual Behavior**
DOESNT PLAY

**Expected Behavior**
It should play

**Comment by samartnik** [comment]
Additionally, to be able to play video on that web site, ads blocking should be turned off.

**Comment by btlechowski** [comment]
Verified on Samsung s7 ARM.
