### ISSUE TITLE
IndexedDB not working in web worker.

### ISSUE THREAD

**Issue by ryanpcmcquen** [brave/browser-android-tabs#679]
Duplicate of: https://github.com/brave/browser-laptop/issues/12463 for mobile.

See: brave/muon#629

Description
IndexedDB can not be used in web workers. The call indexedDB.open() never returns. In the gui thread it works fine.
You can test it here: https://raananw.github.io/WebWorkers-IndexedDB/

Steps to Reproduce
Call `indexedDB.open("a")` in a worker context.

Actual result:
The call never returns.

Expected result:
The call returns.

Reproduces how often:
Always

Brave Version
Brave Android 1.0.52

Reproducible on current live release:
Yes

Will also resolve: https://github.com/tutao/tutanota/issues/207

**Comment by bbondy** [comment]
@bsclifton maybe link to your recent fix on muon?

**Comment by bbondy** [comment]
@ryanpcmcquen are you sure it is broken on android? It is surprising to me if so.

**Comment by ryanpcmcquen** [comment]
@bbondy, I know for certain that Tutanota will not launch, someone else had mentioned this was the culprit on desktop. Could be another issue?

**Comment by bsclifton** [comment]
@bbondy Muon PR linked to above in original post 😄

**Comment by ryanpcmcquen** [comment]
@bsclifton, yep, definitely tried with shields down.

**Comment by SergeyZhukovsky** [comment]
It's not an issue on Android
