### ISSUE TITLE
Live Radio Streams not playing in player UI; works fine on Chrome

### ISSUE THREAD

**Issue by Cormak** [brave/browser-android-tabs#692]
**Did you search for similar issues before submitting this one?**
Yes

**Description:** Streams from http://dir.xiph.org/by_format/Opus won't play using the UI player.

**Steps to reproduce:**
    1. Go to http://dir.xiph.org/by_format/Opus
    2. Try to play a stream using the player UIs that appear on the page.

**Actual Behavior**
Streams don't play

**Expected Behavior**
Streams should play when you press the play button in the player UI.

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Website problems only:**
  - did you check with Brave Shields down?
Yes
  - did you check in Chrome for same behavior?
Yes

**Comment by SergeyZhukovsky** [comment]
That was fixed here https://github.com/brave/browser-android-tabs/issues/675

**Comment by Cormak** [comment]
@SergeyZhukovsky Nope, it does not work on the latest 1.0.52. That issue is for static webms, not live audio streams. Try it yourself. Please reopen.

**Comment by SergeyZhukovsky** [comment]
The fix will appear in the upcoming release in couple days

**Comment by kjozwiak** [comment]
Added `QA/no-qa-needed` as this was checked via #675 as @SergeyZhukovsky mentioned above.
