### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#694]
Something is wrong with it, we have everything translated but some words are in English still
![screenshot_2018-08-05-14-03-50-684_com brave browser](https://user-images.githubusercontent.com/12011303/43795292-ec2aab92-9a4e-11e8-8cfd-91712d1fefdf.png)
![screenshot_2018-08-05-14-03-58-758_com brave browser](https://user-images.githubusercontent.com/12011303/43795295-edd6a9f0-9a4e-11e8-9ef3-77549f4c1c4b.png)

**Comment by samartnik** [comment]
Checked it on these locales
![screenshot from 2018-08-10 11-55-35](https://user-images.githubusercontent.com/30602739/44338852-04edc900-a488-11e8-87af-624acf0d6da8.png)
All those strings are translated in 1.0.54 version.
Will re-open issue if it pops up again.

**Comment by samartnik** [comment]
For QA: re-check that those strings are translated in mentioned locales.
