### ISSUE TITLE
Installer shows Brave logo on the side

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#700]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Installer shows Brave logo on the side

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Lenovo Yoga Tablet 2-830LC Build /LRX22C
   - Android Version: 5.0.1
    
**Brave Version:**
All

**Steps to reproduce:**
    1. Download the APK file from github
    2. Lock device orientation to portrait mode
    3. Open File explorer, orientation changes automatically to landscape
    4. Tap on downloaded AOK file, installs the setup, Once completed, splash screen has Brave logo on the left of the text (see screenshot)

**Actual Behavior**
![image](https://user-images.githubusercontent.com/17010094/43863292-45415204-9b2a-11e8-8e63-c1972b68b06e.png)

**Expected Behavior**
Should be similar to how it is on Mobile

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Any related issues:**

**Comment by samartnik** [comment]
We removed that screen
