### ISSUE TITLE
Fix UserAgent for DDG

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#706]
Currently we send Chrome's UA instead of Brave's.

**Comment by samartnik** [comment]
Steps for check:
1. Go to `duckduckgo.com`.
2. It should show `Add DuckDuckGo to Brave` message.

**Comment by LaurenWags** [comment]
User in community mentioned they're not seeing the change: https://community.brave.com/t/github-issue-706-not-fixed-in-1-0-55/30546

I have not reproduced, requested additional info from user.

**Comment by LaurenWags** [comment]
@samartnik @SergeyZhukovsky looks like if you use the Desktop view of DDG page you still see Chrome instead of Brave - is this expected?

https://community.brave.com/t/github-issue-706-not-fixed-in-1-0-55/30546/4

**Comment by samartnik** [comment]
I believe it's not expected. Reopening the issue.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/728
