### ISSUE TITLE
Implement "Block Phishing/Malware" security option for Android

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#710]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
I've had several Android users ask about additional privacy/security settings available on Desktop but not mobile, most of them concerning the **Block Phishing/Malware** Shields option to Android build.

This option should be available in both the Shields panel as well as "site settings".

**Comment by anthonypkeane** [comment]
We will get this soon :)
