### ISSUE TITLE
Archive.org Audio Playlist and Player Broken 

### ISSUE THREAD

**Issue by Riotous** [brave/browser-android-tabs#715]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When trying to play audio on links such as this one:

https://archive.org/details/OTRR_Dragnet_Singles

I get a broken player with the text "CanvasRenderingContext2D"

**Device Details:**
Nexus 7 Android 7.1,2
Mate 9 Android 8.1
Samsung Galaxy S5 7.1.2
Basically all devices

**Brave Version:**
1.0.54

**Steps to reproduce:**
    1. Go to https://archive.org/details/OTRR_Dragnet_Singles
    2. Try to play audio
    3. See that player and playlist do not display as intended.

**Actual Behavior**
Broken display showing text "CanvasRenderingContext2D"

**Expected Behavior**
Should have a player and playlist of all the tracks.

**Is this an issue with Beta build?**
No beta currently available

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes on all Archive.org pages with playlist audio, on all devices I use. 

**Website problems only:**
  - did you check with Brave Shields down?
Yes
  - did you check in Chrome for same behavior?
Yes

**Comment by SergeyZhukovsky** [comment]
We checked that on several devices and it works. Are you sure Chrome doesn't have the same behavior, it looks like you have global phone settings. @srirambv could you replicate that?

**Comment by Riotous** [comment]
![screenshot_20180821-192617](https://user-images.githubusercontent.com/42202207/44439592-224e9000-a579-11e8-999a-37fa48190a98.png)
![screenshot_20180821-192919](https://user-images.githubusercontent.com/42202207/44439599-28dd0780-a579-11e8-998d-9c08a71fad46.png)
![screenshot_20180821-193035](https://user-images.githubusercontent.com/42202207/44439602-2ed2e880-a579-11e8-8213-706be8eee104.png)
![screenshot_20180821-193126](https://user-images.githubusercontent.com/42202207/44439609-35f9f680-a579-11e8-9f88-4dcab0811b7b.png)

Here's the behavior on the same Huawei device, 1 of Brave 1.0.54 with Shields up, 1 of Brave 1.0.54 with Shields down, 1 with a fresh installation of latest Chrome, 1 with a fresh installation of latest Firefox.

**Comment by SergeyZhukovsky** [comment]
@Riotous could you please check do you have Fingerprinting protection enabled in Settings->Privacy. Toggle it off if yes and retry. Thanks.

**Comment by Riotous** [comment]
@SergeyZhukovsky I can now confirm that 1.0.55(RC1) fixes the issue I had. It looks like fingerprinting protection was on even if I had it disabled in the settings on 1.0.54.

**Comment by samartnik** [comment]
@Riotous thanks for confirmation
