### ISSUE TITLE
Hope to strengthen the function!

### ISSUE THREAD

**Issue by edentw** [brave/browser-android-tabs#716]
**Did you search for similar issues before submitting this one?**
Yes!

**Description:**
1.Need the "Automatically clear browsing data on exit" feature!
2.The adblock section requires a whitelist mechanism because it is necessary to use sites that do not need to be blocked!

**Device Details:**
   - Install Type(ARM, x86): ARM x64
   - Device(Phone, Tablet, Phablet): NO
   - Android Version: 7.0
    
**Brave Version:**
1.0.54

**Steps to reproduce:**
N?A

**Actual Behavior**
N/A

**Expected Behavior**
N/A

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes!

**Extra QA steps:**
N/A

**Website problems only:**
  - did you check with Brave Shields down?
Yes!
  - did you check in Chrome for same behavior?
Yes!

**Screenshot if needed:**
N/A

**Any related issues:**
N/A

**Comment by SergeyZhukovsky** [comment]
There is an open issue for 1. You can simply turn the shields down on a particular website and it will remain down all the time till you turn it on again.
