### ISSUE TITLE
All sites fail with ERR_NETWORK_CHANGED when on VPN, other browsers OK.

### ISSUE THREAD

**Issue by homotopycolimit** [brave/browser-android-tabs#73]
Brave browser on android CM 13.0.
Whenever VPN is active, Brave will not load any site, instead showing an error: ERR_NETWORK_CHANGED.
Other browsers and apps continue to function. 

This happens even when the network was not changed, i.e. when I was on VPN the entire time.

**Comment by SergeyZhukovsky** [comment]
Hi @homotopycolimit,

What VPN do you use?

**Comment by homotopycolimit** [comment]
torguard (using android app)

**Comment by SergeyZhukovsky** [comment]
that is fixed.
