### ISSUE TITLE
Cannot bookmark any website 

### ISSUE THREAD

**Issue by SS1113** [brave/browser-android-tabs#735]
Brave 1.0.54 fails to bookmark any website with an error 'Failed to add bookmark' 
I'm using Xiaomi Mi A1 on Android Oreo 8.1.0

**Comment by SergeyZhukovsky** [comment]
Do you exactly the same behavior on Chrome?

**Comment by SS1113** [comment]
No, I don't see such issues with Chrome

**Comment by SS1113** [comment]
Brave 1.0.59 still has the same issue.

**Comment by SS1113** [comment]
It's been solved.
