### ISSUE TITLE
64Bit version

### ISSUE THREAD

**Issue by MisterGlasses** [brave/browser-android-tabs#737]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
if there is a 64 bit version?The Brave I downloaded is 32 Bit version.

**Device Details:**
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet):Honor V8
   - Android Version: 8.0
    
**Brave Version:**
1.0.54

**Comment by SergeyZhukovsky** [comment]
No we don't have x64, Chromium doesn't provide it yet.

**Comment by MisterGlasses** [comment]
@SergeyZhukovsky 
![screenshot_20180920-074828](https://user-images.githubusercontent.com/27768847/45787873-08b66c00-bc3d-11e8-80fe-f3e6952c1447.jpg)
I find a browser with 64 bit version,how do they do?

**Comment by csagan5** [comment]
@MisterGlasses that is `ARM64` not `x64`

**Comment by MisterGlasses** [comment]
@csagan5 Sorry,I cannot distinguish it.So Does Brave have a ARM64 version?
