### ISSUE TITLE
Remove Google alert message that voice data is being sent to Google servers when using voice-search on search bar widget

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#741]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When using the voice-to-search feature on the Brave Search Bar widget, a message appears after Brave requests permission to use audio:
![image](https://user-images.githubusercontent.com/3299098/45507379-d2fa1a80-b746-11e8-91bd-798044ae6b28.png)
While we're not actually sending anything back to Google servers, we should still stop the message from being displayed to avoid any confusion or doubt from the users. 

**Device Details:**
All
    
**Brave Version:**
1.0.57

**Steps to reproduce:**
    1. Go to your homescreen on your Android device
    2. Long press (or whatever your preferred/required method is for your device) to reveal option to add widgets to the homescreen
    3. Add Brave "Search Bar" widget to homescreen
    4. Tap the microphone icon to initiate voice-to-text 

**Actual Behavior**
Brave initiates voice-to-text and informs user that their recording will be uploaded to Google servers

**Expected Behavior**
Brave initiates voice-to-text, no Google prompt shows

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

Additional Information:
Originally pointed out by a Reddit user: 
https://www.reddit.com/r/brave_browser/comments/9fjuli/android_home_screen_search_widget/

**Comment by RSCipher001** [comment]
It is not an issue, voice recognition functionality is provided by Google App. If you will disable Google app you won't be able to use voice search. It is standard Android behavior.

**Comment by SergeyZhukovsky** [comment]
Correct
