### ISSUE TITLE
Enable Background Play doesn't prompt for browser relaunch to enable feature

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#744]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Enable Background Play doesn't prompt for browser relaunch to enable feature

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Lenovo Yoga 2 Tablet
   - Android Version: Android 5.0.1
    
**Brave Version:**
1.0.58 (RC1)

**Steps to reproduce:**
    1. Upgrade/Clean install 1.9.58 RC1 build
    2. Enable Background play option
    3. No notification shown to restart browser for setting to work

**Actual Behavior**
No Notification shown when enable background play is set

**Expected Behavior**
Should show notification to restart browser to enable feature

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No, shows notification

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/84faab081eaaa7f5ecbe958ebf353bb045d9ddc8
