### ISSUE TITLE
'Block Scripts toggle' doesn't persist between tabs

### ISSUE THREAD

**Issue by PopeRigby** [brave/browser-android-tabs#746]
**Did you search for similar issues before submitting this one?**
Yes.

**Description:**
If you turn off scripts in the Brave menu and open another tab, the toggle will not be on in the new tab. 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.0
    
**Brave Version:** 1.0.57

**Steps to reproduce:**
    1. Turn on 'Block Scripts' in the Brave menu.
    2. Open a new tab.
    3. Observe the fact that 'Block Scripts' is now off.

**Actual Behavior**
'Block Scripts' does not persist between tabs.

**Expected Behavior**
'Block Scripts' persists between tabs.

**Is this an issue with Beta build?**
No.

**Is this an issue in the currently released version?**
Yes.

**Can this issue be consistently reproduced?**
Yes.

**Comment by srirambv** [comment]
Shields settings are specific to a site. If you set block script on `a.com` and visit `b.com` in a new tab it would not be set. There is no global shields settings on Android where you can set it for all sites. Do you see the shields setting not retained for the same website when visiting it a second tab?

**Comment by PopeRigby** [comment]
>Do you see the shields setting not retained >for the same website when visiting it a >second tab?
No. That's not a problem for me. Why is there not a global shield settings panel?

**Comment by SergeyZhukovsky** [comment]
There is, but it's not on the shields menu, you have to go to Settings->Site settings->JavaScript

**Comment by PopeRigby** [comment]
Ok. Thank you!
