### ISSUE TITLE
Add option to show only stats on new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#756]
**Did you search for similar issues before submitting this one?**

**Description:**
Which Chromium 69, new tab shows Downloads and Bookmarks that are added. Provide an option in settings to disable the flags enable-ntp-asset-download-suggestions & enable-ntp-bookmark-suggestions

**Device Details:**
   - Install Type(ARM, x86): All
   - Device(Phone, Tablet, Phablet): All
   - Android Version: All
    
**Brave Version:**
1.0.58

**Steps to reproduce:**
    1. Visit a site and add a bookmark 
    2. Download a file from a page
    3. Open new tab, shows details of bookmarks added and files downloaded making new tab look cluttered

**Comment by Vlad-M-1** [comment]
It would also be nice to provide an option to hide stats from new tab. While part of users may consider it nice, it also creates visual distractions and deteriorates focus on a current task a bit.
