### ISSUE TITLE
Update URL bar (BAT) and toolbar icons for android devices

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-android-tabs#768]
**Did you search for similar issues before submitting this one?**

**Description:**
1. BAT icon to be placed to the right of the Shields icon: 2 states (the 2nd is for publishers that provided their customized tip banner content)
2. bottom bar needs to be created to serve as the toolbar
3. Icon sets for xxxhdpi, xxhdpi, xhdpi, hdpi, and mdpi are zipped here.

[android-assets.zip](https://github.com/brave/browser-android-tabs/files/2471958/android-assets.zip)

cc @yachtcaptain23 @SergeyZhukovsky @anthonypkeane 

**Device Details:**
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version: 
    
**Brave Version:**

**Steps to reproduce:**
    1.
    2.
    3.

**Actual Behavior**

**Expected Behavior**

**Is this an issue with Beta build?**

**Is this an issue in the currently released version?**

**Can this issue be consistently reproduced?**

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by yachtcaptain23** [comment]
This has been done for awhile. Closing.
