### ISSUE TITLE
Default search sometimes changes between private and standard tabs

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#769]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
There are times where, if you have a separate default search for standard and private tabs, searching on private tab, closing it, then searching in the standard tab will **use the same search engine that is specified in the private tab, rather than what's set for standard**. 

**Device Details:**
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet): Pixel 2
   - Android Version: 
    
**Brave Version:**
v1.0.59

**Steps to reproduce:**
The user actually has pretty exact steps!
![image](https://user-images.githubusercontent.com/3299098/47039321-871d0580-d138-11e8-87fe-7811418c1312.png)
**Is this an issue with Beta build?**
N/A

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
N/A
**Website problems only:**
N/A
**Screenshot if needed:**

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/a9f5b45060a564d0db55da1cc8d838364d1ec4dc

**Comment by btlechowski** [comment]
Verified with 1.0.60 RC1 on Samsung s7
