### ISSUE TITLE
Clicking Add another device doesn't list device after sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#778]
**Did you search for similar issues before submitting this one?**

**Description:**
Clicking Add another device doesn't list device after sync

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 5.0.1
    
**Brave Version:**
Sync build

**Steps to reproduce:**
    1. Create sync chain on device A
    2. Click on Sync -> Scan or enter sync code -> Scan QR code to join the sync chain
    3. Click on `Add another device` button at the bottom of the screen on the devices modal
    4. Go back to previous screen
    5. Doesn't show the devices lists
    6. Quit and relaunch the app, still no device list shown. Gets stuck in `Loading Devices` message 

**Actual Behavior**
Clicking Add another device doesn't list device after sync

**Expected Behavior**
Should disable the button probably until the devices are listed. 

cc: @brave/legacy_qa

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by btlechowski** [comment]
Verified on Samsung s7, Brave 1.0.75.
