### ISSUE TITLE
Bookmark is not put into previously synced folder

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#783]
**Device Details:**
Device A: Samsung s7 
Device B: huawei honor 7x (Android 8.0.0)

**Steps to reproduce:**
1. Clean install both devices
2. Create a new sync chain on Android Device A
3. Sync an Android Device B to Device A using QR codes
4. On Device A bookmark `page 1` into `Test` folder
5. Wait for sync on Device B
6. On Device B bookmark `page 2` into `Test` folder
7. Wait for sync on Device A

**Actual Behavior**
On Device A, `page 2` is not in `Test` folder
On Device A:
![screenshot_20181022-222254_brave 1](https://user-images.githubusercontent.com/34715963/47317697-8c9fb180-d64a-11e8-9963-da48a0687c2a.jpg)

On Device B:
![screenshot_20181022-222331 1](https://user-images.githubusercontent.com/34715963/47317996-2a937c00-d64b-11e8-992f-f8343ac3a125.jpg)

**Expected Behavior**
On Device A, `page 2` is in `Test` folder

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851
