### ISSUE TITLE
Backslash(\) is appended to translated string

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#786]
**Did you search for similar issues before submitting this one?**

**Description:**
Backslash(\) is appended to translated string "empreinte". This issue is seen in two places in shield. Also, the translated word "empreinte" is not seen completely for - Protection contre les prises d\'empreinte

1.  Méthodes de prise d\'empreinte
2. Protection contre les prises d\'empreinte

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Gionee s5 and Samsung Galaxy J3
   - Android Version: Android 5.1.0
    
**Brave Version:**
1.0.60

**Steps to reproduce:**
    1. Mock the location and set it to "France" in Android
    2. Change the language to Francais (France)/Francais (Canada)
    3. Install Brave version 1.0.60
    4. Open any site e.g Amazon.com
    5. Click on Shield and verify the Translation for (Fingerprint Methods and Fingerprint Protection)
    6. Shield settings mentioned in step 5 should be translated to French (two options french translation mentioned in description)
    7. Observer that the translated word "empreinte" not seen completely for - Protection contre les prises d\'empreinte

**Actual Behavior**
![shield](https://user-images.githubusercontent.com/38657976/47432325-854be580-d7bb-11e8-98c9-0d499e7b19c1.png)

**Expected Behavior**
1. Méthodes de prise d'empreinte
2. Protection contre les prises d'empreinte

**Screenshot if needed:**

![shield](https://user-images.githubusercontent.com/38657976/47432153-1a9aaa00-d7bb-11e8-91d6-e92953f9d8af.png)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/fea08ad49677ae3cda566b961851e4bf32f28165

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/47435636-ff0bb100-d772-11e8-99fc-fb2d3f9649ee.png)
