### ISSUE TITLE
Default adblock preferences in hamburger menu are not applied

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#787]
**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung s7
   - Android Version: 9.0.0
    
**Brave Version:**
1.0.60 RC1

**Steps to reproduce:**
1. Clean install
2. Go to hamburger menu -> Preferences-> Privacy
3. Turn off adblock (regular and local)
4. Visit a site with ads and check shields

**Actual Behavior**
ads are blocked. 

**Expected Behavior**
ads are not blocked

**Is this an issue in the currently released version?**
TBD

cc @kjozwiak @GeetaSarvadnya @srirambv @LaurenWags

**Comment by srirambv** [comment]
Shields will still show blocked items as its a combination of Adblocker and Tracking protection. Need to disable both in settings for it to disable in Shields. 

cc: @samartnik @SergeyZhukovsky
