### ISSUE TITLE
Credential 400 error while trying to enable sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#788]
**Did you search for similar issues before submitting this one?**

**Description:**
Credential 400 error while trying to enable sync

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: Android 8.0
    
**Brave Version:**
Sync Build

**Steps to reproduce:**
    1. Install sync build
    2. Enable Sync from settings
    3. Choose `Start a sync chain`
    4. Choose `Add a mobile device`
    5. Wait for 5 secs for the QR code to be generated
    6. Error message shows up but you can still sync other devices using the QR code

**Actual Behavior**
![image](https://user-images.githubusercontent.com/17010094/47455323-9555cc00-d79f-11e8-9526-ebf8b873d072.png)

**Expected Behavior**
Should not show error message. Even if it shows should be self explanatory 

**Is this an issue with Beta build?**
 Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Right now reproduced consistently on the sync build

**Any related issues:**

**Comment by srirambv** [comment]
@samartnik this was on real device. Samsung Tab

**Comment by srirambv** [comment]
This error on sync is an old one which was there on the previous sync version as well. https://github.com/brave/sync/issues/212

**Comment by samartnik** [comment]
This issue is related to time diff between server and client more than 2 minutes. To fix that you need just set proper time on your device. @AlexeyBarabash will add proper message for this case later.

**Comment by srirambv** [comment]
- Verification passed on Samsung Tab(ARM) running 1.0.75
