### ISSUE TITLE
Bookmarks added in wrong folder after device comes online

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#790]
**Did you search for similar issues before submitting this one?**

**Description:**
Bookmarks added in wrong folder after device comes online

**Device Details:**
   - Device 1: Samsung Tab (ARM) - Android 8.0
   - Device 2: Lenovo Yoga Tablet (x86) - Android 5.0.1
    
**Brave Version:**
Sync build

**Steps to reproduce:**
    1. Install sync build on both device 1 and device 2
    2. Enable sync on device 1 and add device 2 to the sync chain using QR code
    3. Add a few bookmarks on device 1 while both are online, ensure everything syncs and stays same on both devices
    4. Put device 2 on airplane mode
    5. Add a few more bookmarks and a bookmark folder on device 1
    6. Bring device 2 back online and wait for it to sync
    7. New bookmarks gets sync'd on device 2 but is added into different folder than device 1

**Actual Behavior**
Device 1:
![image](https://user-images.githubusercontent.com/17010094/47458145-dbfaf480-d7a6-11e8-8430-fc841435a273.png)

Device 2:
![image](https://user-images.githubusercontent.com/17010094/47458181-ef0dc480-d7a6-11e8-9cdf-763322c2a0c8.png)

Device 1 with bookmarks inside folder
![image](https://user-images.githubusercontent.com/17010094/47458355-562b7900-d7a7-11e8-8e1d-7084f9a540df.png)

Device 2 with wrong bookmark inside a wrong folder
![image](https://user-images.githubusercontent.com/17010094/47458327-44e26c80-d7a7-11e8-8e33-7cd301859567.png)

Device 1 with actual bookmark
![image](https://user-images.githubusercontent.com/17010094/47458460-97238d80-d7a7-11e8-82f0-fdabdb4f6b27.png)

Device 2 with missing bookmark
![image](https://user-images.githubusercontent.com/17010094/47458403-75c2a180-d7a7-11e8-8501-2b0db03247c2.png)

**Expected Behavior**
Bookmarks should be in the same folder on both devices after its sync'd

**Any related issues:**
#783

**Comment by btlechowski** [comment]
After step 3, I got duplicated bookmarks on Device 1. 

Device 1 had initially 2 bookmarks.
Device 1 after sync:
![screenshot_20181025-001238](https://user-images.githubusercontent.com/34715963/47464862-e7700f00-d7ea-11e8-8f4a-459fb2689d7b.jpg)


Device 2 had initially 0 bookmarks
Device 2 after sync:
![screenshot_20181025-000317_brave 1](https://user-images.githubusercontent.com/34715963/47464568-e4285380-d7e9-11e8-8efd-c03d4608e0a1.jpg)

**Comment by GeetaSarvadnya** [comment]
This issue is happening on iOS to Android sync as well.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by btlechowski** [comment]
Verified on Samsung s7 (ARM), Brave 1.0.75.
