### ISSUE TITLE
Secret code not shown on device 1 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#791]
**Did you search for similar issues before submitting this one?**

**Description:**
Found this issue on device 1 after found https://github.com/brave/browser-android-tabs/issues/790 

**Device Details:**
   - Device 1: Samsung Tab (ARM) - Android 8.0
   - Device 2: Lenovo Yoga Tablet (x86) - Android 5.0.1

**Brave Version:**
Sync build

**Steps to reproduce:**
    1. Follow steps from #790 
    2. Keep Brave active on device 1 for a while
    3. Open Settings->Sync->Add a computer -> No secret code shown. Copy to clipboard shows successfully copied but clipboard is empty

**Actual Behavior**
![image](https://user-images.githubusercontent.com/17010094/47462292-ed48fe80-d7b0-11e8-86c1-edb9e9d5d55a.png)

**Expected Behavior**
Should show the secret code Device 2 contains the secret code 

**Can this issue be consistently reproduced?**
Need to try again

**Any related issues:**
cc: @btlechowski @GeetaSarvadnya to try reproducing the issue once

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by btlechowski** [comment]
Verified on Samsung s7 (ARM), Brave 1.0.75.
