### ISSUE TITLE
Sync chain gets created even when device is offline

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#792]
**Did you search for similar issues before submitting this one?**

**Description:**
Sync chain gets created even when device is offline

**Device Details:**
   - Install Type(ARM, x86): ARM/x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 8.0
    
**Brave Version:**
Sync build

**Steps to reproduce:**
    1. Put device on airplane mode
    2. Enable sync from settings
    3. Select Mobile/Computer, creates QR code and shows code words
    4. Scan QR code on second device, sync chain gets created
    5. Put device online, doesn't show the  list of devices until browser is removed from memory and relaunched

**Actual Behavior**
[OfflineSync.zip](https://github.com/brave/browser-android-tabs/files/2512777/OfflineSync.zip)

**Expected Behavior**
Should not create sync chain when device is offline

**Is this an issue with Beta build?**
yes

**Can this issue be consistently reproduced?**
Yes

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by btlechowski** [comment]
Verification passed on Samsung s7 (ARM), Brave 1.0.75.
