### ISSUE TITLE
After sync, the count of added sites is not same in Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#795]
**Did you search for similar issues before submitting this one?**

**Description:**
After sync, the count of added sites is not same in Android

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Iphone8/ios 12
   - Android Version: Android 5.1.1
    
**Brave Version:**
Sync build

**Steps to reproduce:**
    1. Sync Android and iOS using QR code
    2. Start creating BM's in ios
    3. Create folder A, open a site and add it to folder A multiple times
    4. Create folder B, open a site and add it to folder B multiple times

**Actual Behavior**

After sync, the count of added sites is not same in Android

Android:

![screenshot_2018-10-25-09-36-35](https://user-images.githubusercontent.com/38657976/47476202-eff13580-d83c-11e8-85e2-6f2d883a8f6f.png)
![screenshot_2018-10-25-09-36-52](https://user-images.githubusercontent.com/38657976/47476206-f41d5300-d83c-11e8-8fc1-74d0867c485c.png)

**Expected Behavior**
iOS
![img-20181025-wa0002](https://user-images.githubusercontent.com/38657976/47476236-13b47b80-d83d-11e8-88a0-fe98d5c4fbd7.jpg)
![img-20181025-wa0003](https://user-images.githubusercontent.com/38657976/47476241-17480280-d83d-11e8-8262-60ecae639c4f.jpg)

**Comment by srirambv** [comment]
@GeetaSarvadnya could you try the same with different sites being added? Using the same site isn't clear if one bookmark got duplicated several times or not

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by srirambv** [comment]
Verification passed on Samsung Tab(ARM) running 1.0.75
