### ISSUE TITLE
Deleted folder is synced again with newly synced folders on Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#796]
**Did you search for similar issues before submitting this one?**

**Description:**
Deleted folder is synced again with newly synced folders on Android

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): iPhone 8/ iOS 12
   - Android Version: Android 5.1.1
    
**Brave Version:**
Sync Build
**Steps to reproduce:**
    1. Sync Android and   Ios through QR code
    2. BM 6- 7 sites inside the folders, and few sites outside the folder on iOS device
    3. Make sure BM's are synced along with proper folder structure in Android
    4. Delete all the BM's along with folders from iOS
    5. Make sure BM's are deleted from iOS and Android
    6. Start fresh BM on ios, add few sites to folder A
    7. Add few sites to folder B
    8. Make sure New BM's are synced in Android

**Actual Behavior**
Deleted folder is synced again with newly synced folders on Android
![screenshot_2018-10-25-09-36-09](https://user-images.githubusercontent.com/38657976/47476630-05675f00-d83f-11e8-9e17-49884f322330.png)

**Expected Behavior**
Deleted folder should not sync along with new folders
![img-20181025-wa0001](https://user-images.githubusercontent.com/38657976/47476638-0dbf9a00-d83f-11e8-8c5e-c11d5f99218c.jpg)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by btlechowski** [comment]
Verified on Samsung s7 (ARM), Brave 1.0.75.
