### ISSUE TITLE
Few BM folders are not getting deleted forever

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#798]
**Did you search for similar issues before submitting this one?**

**Description:**
Few BM folders are not getting deleted from Android even after 10 mins

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): iPhone 8 / ios12
   - Android Version: Android 5.1.1
    
**Brave Version:**
Sync Build

**Steps to reproduce:**
    1. Sync Android and Ios through QR code
    2. Start creating BM on ios 
    3. Create folder A, open a site and add it to folder A multiple times
    4. Create folder B, open a site and add it to folder B multiple times
    5. Make sure BM's are synced in Android
    6. Delete all the BM's from ios
    7. Observe that all the BM's along with folders are deleted from ios
    8. Observe that only one folder is deleted from Android
    

**Actual Behavior**
Few BM folders are not getting deleted forever

**Expected Behavior**
Once the sync has been established, after deleting BM's from device 1, the BM's should be deleted from rest other synced devices.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/851

**Comment by srirambv** [comment]
- Verification passed on Samsung Tab (ARM) using 1.0.75
- Verification passed with sync with b-c and iOS using the issue description
