### ISSUE TITLE
Close tabs on exit option

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#80]

**Comment by SergeyZhukovsky** [comment]
We have probably implement that feature on app start, because Android OS could kill your app in any moment.

**Comment by LaurenWags** [comment]
I've seen several requests for this on the Google Play Store.

**Comment by samartnik** [comment]
So eventually we need to add new option `Close tabs on exit` in `Settings > Privacy`. It should be check box, similar to `HTTPS Everywhere`.
When we open app, if this option is set, we just don't open tabs from the last session.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/close-all-tabs-on-exit-android/18362

**Comment by LaurenWags** [comment]
@samartnik this is awesome, I've seen a lot of requests for this in google play store. could you provide a test plan for this issue? Also, will this clear cookies/history/etc as well?

**Comment by samartnik** [comment]
Test plan:
1. Open several tabs with websites.
2. Make sure option is off by default.
3. Close browser.
4. Open browser. All tabs should be recovered.
5. Turn the option on.
6. Make steps 1 and 3. When open browser it should start with default tab only.
This option is only for saved session tabs It doesn't include cookies/history etc.
