### ISSUE TITLE
Insufficient Contrast for Status Bar Icons

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#801]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Brave, at times, give insufficient contrast to the status bar icons.

**Device Details:**
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 
    
**Brave Version:**
TBD

**Steps to reproduce:**
TBD

**Actual Behavior**
Icons are difficult to perceive against background

**Expected Behavior**
Icons should be more easily visible.

**Is this an issue with Beta build?**
N/A

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
TBD

**Extra QA steps:**
TBD

**Screenshot if needed:**

![image](https://user-images.githubusercontent.com/815158/47572913-b9312300-d901-11e8-9f95-c5aead4fcff4.png)

Screenshot provided by [@ChrisPirillo](https://twitter.com/ChrisPirillo/status/1055825721946337280) on Twitter.

**Any related issues:**
TBD

**Comment by miladmaz12** [comment]
I have this as well (1.0.61)

Any updates of this?

**Comment by miladmaz12** [comment]
I still have this on 1.0.69

**Comment by miladmaz12** [comment]
@

**Comment by miladmaz12** [comment]
Bump, really want this to be fixed already

**Comment by jonathansampson** [comment]
This issue appears to no longer reproduce.
