### ISSUE TITLE
Welcome to Brave screen asks users to agree to Chrome's Terms of Service

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#810]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
After downloading and installing Brave, the 'Welcome to Brave' screen prompts users to agree to Chrome's Terms of Service and Privacy Notice, not Brave's.

**Device Details:**
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
    
**Brave Version:**
1.0.60 and 1.0.61

**Steps to reproduce:**
    1. If you have Brave installed on device, remove it.
    2. Go to GitHub and download apk.
    3. After download and install, launch Brave.

**Actual Behavior**
Welcome to Brave screen mentions Chrome:
![screenshot_20181101-091333](https://user-images.githubusercontent.com/28145373/47854178-749d0000-ddb7-11e8-8368-0d4157aeb20e.jpg)

**Expected Behavior**
Should say Brave instead of Chrome

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? n/a
  - did you check in Chrome for same behavior? n/a

**Screenshot if needed:**

**Any related issues:**
Reported via twitter: https://twitter.com/BBreyten/status/1056795691706732544

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/1307af3ae0bb4555099080490f20ffda0f37da32

**Comment by srirambv** [comment]
Verified on RC2 build. Text replaced.

**Comment by LaurenWags** [comment]
Verified text is replaced on RC2 ARM build. Verified by @kjozwiak as well.
