### ISSUE TITLE
Turn on TLS 1.3 by default

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#812]
It is under `chrome:\\flags` TLS 1.3 currently and it is off by default.
You can test on https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by AlexeyBarabash** [comment]
Tried with version `1.0.61`.
No matter what I choose in `chrome://flags` : `Default` or `Enabled (Final)` the test on cloudflare succeed.
![smartselect_20181114-123259_brave](https://user-images.githubusercontent.com/24739341/48477333-fe15ee80-e809-11e8-9e63-e41192325caf.jpg)

@SergeyZhukovsky could you please re-check also?

**Comment by AlexeyBarabash** [comment]
Found message from @kjozwiak 

```
`Brave 1.0.60, CR: 70.0.3538.64` - TLS 1.3 Disabled
```

rechecked on Android 8.0.0 device, security update October 2018, all chrome://flags TLS 1.3 are `Default`:
 - with 1.0.61 TLS 1.3 Enabled;
 - with 1.0.60 TLS 1.3 Enabled;
 - with 1.0.59 TLS 1.3 Enabled;

rechecked on Android 4.1.2 device:
 - with 1.0.61 TLS 1.3 Disabled, if chrome://flags TLS 1.3 `Default`;
 - with 1.0.61 TLS 1.3 Enabled, chrome://flags TLS 1.3 `Enabled (Final)`;

**Comment by kjozwiak** [comment]
Which milestone/release is this going into? It's currently set as `No milestone`.

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/48849019-7745b080-edcb-11e8-9a3f-bfd85e826349.png)

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/48849073-96444280-edcb-11e8-95c0-be13021b6234.png)
