### ISSUE TITLE
BAT Icon should be disabled when on chrome://rewards

### ISSUE THREAD

**Issue by ryanml** [brave/browser-android-tabs#826]
The BAT Icon in the URL bar should be disabled when the rewards page is the current active tab

**Comment by ryanml** [comment]
George we want to avoid the reproducible scenario pictured here:

We are just opening the summary on top of the `chrome://rewards` page. In this case we just want it to not open at all.

![screenshot_20181114-132920_brave](https://user-images.githubusercontent.com/8732757/48513825-b98e5100-e811-11e8-8707-dbbc8afe549e.jpg)

**Comment by gdregalo** [comment]
I see what you mean. You don't want to duplicate behavior already available at opened 'chrome://rewards' page: wallet details and 'Add funds' button.
What if 'chrome://rewards' page is opened on the other tab already which is not directly under the panel?

**Comment by SergeyZhukovsky** [comment]
N/A. We never disable it on desktop as well.
