### ISSUE TITLE
Check reconcile/batch contribution

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#834]
Please check below testing scenario.
Software: Android M, API 23.

1. The Rewards have been joined and wallet created.
2. 20 BAT sent to the wallet and received.
3. The monthly batch contribution amount was set to 10 BAT.
4. The value of _reconcile_default_interval  was set to 600 seconds.
(https://github.com/brave-intl/bat-native-ledger/blob/master/src/static_values.h#L93)
5. 3 websites were visited and the all appeared in 'Auto-contribute/supported sites ' list.
6. After 10 minutes the contribution process worked out and 20 BATs were withdrawn instead of 10.
7. After the process the call to `BatContribution::SetReconcileTimer()` (https://github.com/brave-intl/bat-native-ledger/blob/master/src/bat_contribution.cc#L1312) happened twice with 1 minute interval.

**Comment by gdregalo** [comment]
After more careful investigation of the problem, I found that:
1. the panel (`chrome:://rewards-panel`) doesn't reflect a real state of the wallet and rewards summary.
2. The Auto-contribute settings are not properly reflected. Changing the value of the `monthly payment` does change the value in `ledger_state` file but doesn't show it on the page.
The default contribution amount is 20 BAT.  And that's why 20 BAT were withdrawn as per initial problem description, nevertheless the `Monthly payment` showed only 10 BAT.
I didn't see the problem mentioned in (7) anymore.

**Comment by SergeyZhukovsky** [comment]
I checked and it works on latest version
