### ISSUE TITLE
Add startpage as a searchengine and quit brave option

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#84]
From [support ](https://linkbubble.zendesk.com/agent/tickets/7075)
>The Two Improvements that I would personally see would be to  have a Quit Button Option and perhaps add Startpage added as a Search Engine as it was created to search anonymously!

**Comment by SergeyZhukovsky** [comment]
StartPage engine is added here https://github.com/brave/browser-android-tabs/commit/392a3174cddcb0bf30960f69d01093fdae504046

**Comment by srirambv** [comment]
Closing #84. Already implemented
