### ISSUE TITLE
'chrome://rewards' : “Why Brave Rewards?” header doesn't look good 

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#840]
Please check the next test scenario:
1. Enable/disable rewards using switch in top right corner.
2. The “Why Brave Rewards?” shows up.
It's not clear when this header is necessary.  It's not properly formatted. It has missing string identifier "WhyBraveRewardsDesc3".

**Comment by ryanml** [comment]
String fixed via: https://github.com/brave/browser-android-tabs/commit/7b06a49b246a146e3527cd194f69b9617f69988b
