### ISSUE TITLE
“Rewards panel/Auto-contribute/Settings“ are not saved.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#842]
Changing values on “Rewards panel/Auto-contribute “or “Auto-contribute/Settings“ pages doesn’t save/restore values except "contribution to non-verified publishers"  and "contribution to videos".

**Comment by ryanml** [comment]
@gdregalo - it is a problem with the mobile select component not triggering a passed in `onChange event`, I have this fixed in a WIP pr for brave-ui

**Comment by ryanml** [comment]
Fixes auto-contribute panel include: https://github.com/brave/browser-android-tabs/commit/fca49852c55192860af4b0063001194777cc9276

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/63f5331713af51dbea9d6a4fbdb2577f10ac4d24
