### ISSUE TITLE
'chrome://rewards-panel' in wrong state if rewards were joined from 'chrome://rewards'.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#843]
The rewards can be initialized from both the 'chrome://rewards' page and the panel.
If it was initialized from `chrome://rewards` page, the panel still shows enabled ‘Join rewards’ button. Pressing it spins progress spinner infinitely.

**Comment by ryanml** [comment]
This has been fixed via: https://github.com/brave/browser-android-tabs/commit/a24d31ddedc35c5c356fc96ec6ec4cd7ba9590a3

You should now be able to create via `chrome://rewards` and see the expected state via the panel
