### ISSUE TITLE
The ‘Settings’ button with gear icon on “Your wallet” dialog is enabled but doesn’t work.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#844]
The ‘Settings’ button with gear icon on “Your wallet” dialog is enabled but doesn’t work. 
On Desktop browser it opens "Backup/restore your wallet" dialog.  
Also the gear icon usually represents settings page.

**Comment by ryanml** [comment]
@gdregalo the scope of this issue is covered by: https://github.com/brave/browser-android-tabs/issues/831
