### ISSUE TITLE
'chrome://rewards' crash scenario

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#846]
Please check the next test scenario:
1. open “Your wallet” dialog, then “Add funds”;
2. close the dialog with wallet addresses;
3. close “Your wallet” by pressing “X” closing button.
The page is crashed.
Discovered on Android M (API 23) device.

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/commit/a24d31ddedc35c5c356fc96ec6ec4cd7ba9590a3
