### ISSUE TITLE
VPN problems

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#85]
There are websites timeouts on OpenVPN Connect.

**Comment by briceb8e** [comment]
fyi, it does not only happen on OpenVPN Connect but also with PIA VPN. Brave is however working fine if the VPN is initiated on the gateway, rather than on the phone directly, as expected.

**Comment by SergeyZhukovsky** [comment]
Hi @briceb8e,
I tried that and it works fine to me. Do you have any exact websites with the problem? Or it just happens randomly from time to time?

**Comment by lttrest07** [comment]
Everytime I have express VPN on Brave browser on Android doesn't work.

**Comment by livingcolor** [comment]
Galaxy Note 5 Marshmallow.

Agreed, seems to be an issue when a VPN is active on Android (ExpressVPN currently). Browser will be either extremely slow or cannot resolve addresses. Can confirm browser works when a VPN is active on gateway/router.

**Comment by SergeyZhukovsky** [comment]
@lttrest07 @livingcolor could you tell me what server's locations do you use and what websites are slow? I tried several locations and I haven't seen any differences between browsing with ExpressVPN enabled and disabled. Thanks.

**Comment by lttrest07** [comment]
@SergeyZhukovsky  I was having issues on Miami, Argentina, Brazil.

**Comment by SergeyZhukovsky** [comment]
@lttrest07 @livingcolor well I see the slowness on Argentinian server, but the slowness not only in Brave, it is the same in Chrome and other web apps on the device. I think it is just a server with a slow response in general. However I never noticed websites timeouts. Do you have any particular problems with Brave only?

**Comment by cedmax** [comment]
I experienced unresponsiveness with ExpressVPN whie connected to servers in UK, Netherlands and France; meanwhile Chrome, some other browsers I tried and basically any other app (surely: Spotify, Play Store, Amazon to name a few) presented only a slight decline in speed, but absolutely acceptable

**Comment by lttrest07** [comment]
@SergeyZhukovsky I agree with @cedmax I see slightly slower load times on Chrome using VPN (expected, thats the tradeoff right), but time outs, unresponsiveness or extreme delay on Brave using VPN.

**Comment by SergeyZhukovsky** [comment]
@cedmax here is a response from one of our customer: "I contacted ExpressVPN, and they suggested using the TCP protocol (vice UDP) and that appears to have fixed the problem."

**Comment by cedmax** [comment]
@SergeyZhukovsky I tried it already (and again now, since you mentioned it) but without any luck: the issue doesn't seem to disappear. It's a shame since I really like brave, but for the moment it's really unusable on my side. I appreciate it's an edge case, so I wouldn't be disappointed too much if this won't be solved, but I hope the feedback helps anyway

**Comment by mideeks** [comment]
This happens with Google's "Wifi Assistant" VPN as well (https://support.google.com/nexus/answer/6327199?hl=en). They offer it free on Pixel/Nexus devices to protect you on open Wifi networks. I notice that Brave doesn't work at all when I get onto a coffee wifi for example. Nothing resolves/loads.

**Comment by mideeks** [comment]
More info:
- No sites load at all. I tried dozens. It just hangs with the loading bar forever.
- Chrome and other browsers/apps work while on VPN but Brave is the only one that does not
- I additionally tried with my two work VPNs (OpenVPN). One is a split VPN (10.x.x.x routing only) and the other is a full VPN (all traffic). 
    - Brave works fine with the split VPN on.
    - Brave does not work with the full VPN on.
- I am located in San Francisco (good networks) and have tried on multiple open Wifi networks (Philz coffee, Starbucks, Work guest Wifi, etc) and Brave works on none of them when a full VPN is on.
- I tried turning off all privacy settings in Brave but that did not seem to have an effect

Unfortunately it looks like can't use Brave to surf safe on open Wifi :( Let me know if you need more info. Eager to help :)

You might try https://www.tunnelbear.com/ for testing. I believe it is OpenVPN based and offers 500mb free per month.

**Comment by simonsmith** [comment]
Can confirm I'm having the same issue here. Using OpenVPN and Brave will hang on a request and timeout.

**Comment by mideeks** [comment]
Finally hooked it up to the debugger. Says it spent 12s doing a DNS lookup:
http://i.imgur.com/aMHkBtF.png

When off of VPN that does not happen.

**Comment by SergeyZhukovsky** [comment]
@mideeks thanks for the screenshot. I was able to reproduce it with news.ycombinator.com, tunnel Bear and Brazilian server. I'm investigating it.

**Comment by SergeyZhukovsky** [comment]
Fixed it https://github.com/brave/browser-android-tabs/commit/ebdb2c4814735276ae2035256484dbf61ec09f2e
Thanks everyone for your help with that issue. The fix will be available on the upcoming release.

**Comment by mideeks** [comment]
Confirmed fixed after upgrading today. Thanks!

**Comment by SergeyZhukovsky** [comment]
Great! Enjoy it guys over your VPN. Thank you all again for your help with that!
