### ISSUE TITLE
Display brave:// instead of chrome://

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#850]
Please check a similar desktop PR https://github.com/brave/brave-core/pull/584. Hopefully it will work well on Android as well.
https://github.com/brave/brave-core/commit/d67b21f665bc3eeb20a4f42d31de95fb1355adb1#diff-b5aa9c7aba8e1fd1c0035e1a303dd8b8

**Comment by AlexeyBarabash** [comment]
PR https://github.com/brave/browser-android-tabs/pull/878

**Comment by anthonypkeane** [comment]
We are still seeing  chrome://rewards not brave://rewards @SergeyZhukovsky

**Comment by lhorace** [comment]
Hello there,

Seems to me that PR hasn't been merged?

**Comment by bbondy** [comment]
@anthonypkeane we'll get brave:// scheme for free in the urlbar once we move to Brave Core.

**Comment by AlexeyBarabash** [comment]
This PR hasn't been merged.
In fact this PR is taken from two brave-core PRs plus some Android related minor changes.

**Comment by anthonypkeane** [comment]
Closing as this will come from core.
