### ISSUE TITLE
multiple instances of `chrome://rewards` pages are not synchronized. Why do we need multiple ones?

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#852]
Multiple instances of `chrome://rewards` pages are not synchronized. It's error-prone to allow multiple instances of the `chrome://rewards` pages.  Changes made on the one page are not visible on the other. 
If user requested explicitly `chrome://rewards` page, I think, it's more safe to show her a message "You have rewards tab opened. Close this one and re-focus?" Or make sure the pages are in sync. 
Let's discuss it.

**Comment by ryanml** [comment]
@gdregalo looks like current `brave-core` behavior allows for multiple rewards tabs, which are not in sync as far as their react app state. 

Personally I think we should auto-focus to an existing rewards tab in the case another is opened, but I'm guessing we'll want to mimic what is one brave-core.

cc: @anthonypkeane

**Comment by anthonypkeane** [comment]
We should re-open the existing chrome://rewards page and not have open multiple. 
@gdregalo is this doable?

**Comment by SergeyZhukovsky** [comment]
It's fixed by @gdregalo
