### ISSUE TITLE
Unable to install Brave on Acer tablet running Android 4.4.2

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#86]
From [Support ](https://linkbubble.zendesk.com/agent/tickets/7004)

User is unable to install Brave on Acer tablet running Android 4.4.2 even after enabling notifications

**Comment by SergeyZhukovsky** [comment]
Done it. We have to use gcc compiler there, because of isnanf function. 
In gcc builds, calls to isnanf are handled by __builtin_isnanf, which directly generates inline code for the function without needing any library support.
