### ISSUE TITLE
Welcome to Brave screen asks users to agree to Chrome's Terms of Service 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#874]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
After downloading and installing Brave, the 'Welcome to Brave' screen prompts users to agree to Chrome's Terms of Service and Privacy Notice, not Brave's.

**Device Details:**
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
    
**Brave Version:**
1.0.64

**Steps to reproduce:**
    1. If you have Brave installed on device, remove it.
    2. Go to GitHub and download modernapk.
    3. After download and install, launch Brave.

**Actual Behavior**
https://youtu.be/CZ8bm2UDyfY

**Expected Behavior**
Should say Brave instead of Chrome

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
no

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down? n/a
  - did you check in Chrome for same behavior? n/a

**Screenshot if needed:**

**Any related issues:**
Regression of #810

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/f98bfa849ce1b925fab70fd9261e5f03659fb02a

**Comment by srirambv** [comment]
Verified new build fixed the issue
