### ISSUE TITLE
HTTPS upgrade test fails

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#876]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
HTTPS upgrade test fails

**Device Details:**
   - Install Type(ARM, x86): x86
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 5.0.1
    
**Brave Version:**
1.0.64(RC2)

**Steps to reproduce:**
    1. Visit https://github.com/brave/browser-android-tabs/issues/873
    2. Scroll down to bravery section and open https://https-everywhere.badssl.com/ in a new tab
    3. HTTPS shows not working. Disable HTTPS setting from shields, page loads incorretly

**Actual Behavior**
HTTPS upgrade test fails

**Expected Behavior**
Should upgrade HTTPSE when available

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by srirambv** [comment]
This is happening only with the modern builds being installed on Tablet running Android 5.0.1. With regular apk files httpse works just fine

**Comment by samartnik** [comment]
This should be fixed in 1.0.65

**Comment by srirambv** [comment]
Verified  with both regular and modern apk for x86 and there is no httpse error on first launch. Works fine

**Comment by btlechowski** [comment]
Verification of 1.0.68 passed on Samsung s7 (ARM)
