### ISSUE TITLE
'Monthly payment' is not properly reflected on the 'Auto-contribute' dialog.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#880]
Changing 'Monthly payment' value on the 'Auto-contribute' dialog does change the value. 
But new value is not reflected on the UI.
There are 2 controls displaying the value: on main 'Auto-contribute' and 'Auto-contribute/Settings' dialogs.

**Comment by ryanml** [comment]
@gdregalo - this is the same thing that currently happens in brave-core. I am going to implement behavior there then I will do so on Android

**Comment by ryanml** [comment]
This one is now part of native panel

**Comment by SergeyZhukovsky** [comment]
@gdregalo is it still a problem? I don't understand is it related to old HTML based UI or should be good with native UI? Could you please re check it?

**Comment by gdregalo** [comment]
Yes, it is still not fixed.
![screenshot_2019-01-24-12-16-02](https://user-images.githubusercontent.com/37560650/51696032-7e0ec080-1fd2-11e9-951a-cc50aae75164.jpg)
![screenshot_2019-01-24-12-16-07](https://user-images.githubusercontent.com/37560650/51696037-82d37480-1fd2-11e9-8ab9-723ee91734de.jpg)

**Comment by ryanml** [comment]
@gdregalo @SergeyZhukovsky I thought this issue had to do with the panel at the time.

We already had two issues open for the problem in George's screenshot, both were closed last evening by a fix I pushed, thanks!

**Comment by gdregalo** [comment]
Updated screenshots:
![screenshot_2019-01-24-12-16-02](https://user-images.githubusercontent.com/37560650/51696131-c0d09880-1fd2-11e9-9983-1fbf73017d43.jpg)
![screenshot_2019-01-24-12-16-07](https://user-images.githubusercontent.com/37560650/51696132-c1692f00-1fd2-11e9-8903-51b8bdc4d174.jpg)

**Comment by Mikko031014** [comment]
On Jan 25, 2019 1:23 AM, Ryan Lanese <notifications@github.com> wrote:Closed #880.
