### ISSUE TITLE
Tipping a website doesn't work on `rewards-panel`

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#881]

**Comment by ryanml** [comment]
@gdregalo can you add some steps to reproduce? Is it all the time? Do you get any JS or C++ errors, or does nothing happen?

**Comment by gdregalo** [comment]
1.The panel doesn't reflect  the real amount of available funds and always shows 0 BAT.  
2.The 'Send a tip' button is enabled even when wallet shows 0 BAT. 
3.Pressing 'Send a tip' opens another window with buttons with tip amounts to select. 
4.'Send my tip' button is almost not visible and that's why I clicked the buttons mentioned in (3) and didn't see any reaction.

**Comment by gdregalo** [comment]
1. The funds of 20 BAT were transferred and indeed exist in the wallet. It's visible on `chrome://rewards` page.
2. The panel is opened above a web-site with 0 BAT funds.
3. Pressing 'Send a tip' opens another window with buttons with tip amounts to select.
4. '5 BAT' was selected and 'Send my tip' button was pressed.
5. "Thank you!" page was opened.
6. The `chrome://rewards` shows 15 BAT in the wallet, which means that 5 BATs were sent to a publisher (I hope).
7. Opening the tipping page above any other web-site shows  only "Thank you!" page.

**Comment by ryanml** [comment]
This is now a part of the native panel UI
