### ISSUE TITLE
orange dot appearing on the refresh button

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#885]
**Did you search for similar issues before submitting this one?**

Yes, this looks like a regression. It was originally fixed under https://github.com/brave/browser-android-tabs/issues/724 but appears to be back with the `1.0.68` build.

**Description:**

When refreshing the page under Brave, you'll notice an "orange" blob/dot on the refresh button.

**Device Details:**
   - Install Type(ARM, x86): `ARM`
   - Device(Phone, Tablet, Phablet): `Google Pixel XL`
   - Android Version: `android 9`
    
**Brave Version:**

* `1.0.68, CR: 70.0.3538.110`

**Steps to reproduce:**

    1. Visit a website and refresh by pulling down

**Actual Behavior**

![screenshot_20181123-114019](https://user-images.githubusercontent.com/2602313/48953965-a5370c00-ef15-11e8-9798-3895bba3c04d.png)

**Expected Behavior**

Shouldn't see an "orange" blob/dot on the refresh button

**Is this an issue with Beta build?**

Yes, currently reproducible with the current BETA that we're QAing

**Is this an issue in the currently released version?**

Nope, it was fixed under https://github.com/brave/browser-android-tabs/issues/724

**Can this issue be consistently reproduced?**

Yes, 100% reproducible using the above STR.

**Any related issues:**

* https://github.com/brave/browser-android-tabs/issues/724

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/73763ae6cd2e96984fc457076abec9143872e2df

**Comment by kjozwiak** [comment]
Verified that the issue as bene resolved using `1.0.69, CR: 70.0.3538.110`:

![screenshot_20181123-133855](https://user-images.githubusercontent.com/2602313/48957238-67da7a80-ef25-11e8-8999-27807bb4b5f4.png)
