### ISSUE TITLE
Brave Rewards panel is very slow to load

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#899]
**Description:**
Brave Rewards panel is very slow to load

**Device Details:**
   - Install Type: x86
   - Device: any older devices
   - Android Version: any
    
**Brave Version:**
Beta versions with BR

**Steps to reproduce:**
    1. Press the BR icon on the top URL bar
   
**Actual Behavior**
Panel takes 3 or 4 seconds to load

**Expected Behavior**
Panel should load in a fraction of a second

![brave rewards](https://user-images.githubusercontent.com/7606853/49122342-e2c6cc80-f268-11e8-9adb-4f3576042499.gif)

**Comment by ryanml** [comment]
Closing as we will now be using the native panel UI
