### ISSUE TITLE
Shields doesn't work when Chrome Duet is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#900]
**Description of the issue:** 
Reported via [community](https://community.brave.com/t/bug-the-brave-menu-can-t-pop-up-if-chrome-duet-is-enabled/38353) 
> The brave menu can‘t pop up if Chrome Duet is enabled. 

**Steps to Reproduce (add as many as necessary):** 
1. Go to chrome://flags and enable Chrome Duet
2. Restart brave
3. Click the brave icon near address bar

**Actual Result (gifs and screenshots are welcome!):** 
![image](https://discourse-cdn-sjc1.com/business4/uploads/brave/original/2X/8/82c17e20cb1ab621355f90768ea4475545b27eda.gif)

**Expected result:**
The brave menu can pop up when Chrome Duet is enabled. 

**Reproduces how often:** 
Always

**Brave Version(about:brave):**
Brave 1.0.70

**Mobile Device details**
Mobile: Xiaomi Mi 6 
ROM: MIUI10

**Android/iOS Version**
Android 8.0.0

**Additional Information:**

**Comment by Brave-Matt** [comment]
Can repo so +1 from me. 
We should get this resolved asap - users have been requesting "bottom address bar" forever.

Now it looks like we have a solution for free dropped in our laps here. If we can get Shields up and running we can advise users to set the flag if they want bottom address bar, and get #620 closed.

**Comment by thanuj10** [comment]
+1 here too.

**Comment by Brave-Matt** [comment]
+1 from zendesk:
![image](https://user-images.githubusercontent.com/3299098/51144574-4a7bab80-1806-11e9-9951-fe0fd1882269.png)

**Comment by whezzel** [comment]
This is working in the latest test build with Brave Rewards
![screenshot_20190119-074431](https://user-images.githubusercontent.com/340386/51427500-3ea13800-1bbe-11e9-86ee-a091cb52a2c6.png)

**Comment by sangeet** [comment]
I am still facing this issue on Brave 1.0.77 Chromium 71.0.3578.99.

I am also unable to open links in New tab in the same version for which I've logged a community ticket at https://community.brave.com/t/unable-to-open-any-link-in-a-new-tab-in-brave-for-android/44711

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/brave-shields-icon-not-working-with-duet-enabled/44845?u=eljuno

**Comment by srirambv** [comment]
+1 from @MisterGlasses via #813

**Comment by Brave-Matt** [comment]
+1 from zendesk: 
![image](https://user-images.githubusercontent.com/3299098/54313645-005d3f00-4597-11e9-833e-4952fa26dd3f.png)

**Comment by tomlowenthal** [comment]
We have our own bottom-bar; we don't support Chrome Duet.
