### ISSUE TITLE
Redesign and relocate forward button

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#911]
**Did you search for similar issues before submitting this one?**

**Description:**
Redesign and relocate forward button. More details here https://bravesoftware.slack.com/archives/C07HD31EZ/p1543788487004000

**Device Details:**
   - Install Type(ARM, x86): All
   - Device(Phone, Tablet, Phablet): Phone's
   - Android Version: All
    
**Brave Version:**
All

**Actual Behavior**
![screenshot_20181202-170827](https://user-images.githubusercontent.com/17010094/49348041-fdfe6580-f6c8-11e8-9918-6b9277b1a2d8.png)

**Expected Behavior**
Should have a better design and be in a better location

**Is this an issue in the currently released version?**
Yes

**Any related issues:**

**Comment by SergeyZhukovsky** [comment]
Done here https://github.com/brave/browser-android-tabs/pull/1735

**Comment by LaurenWags** [comment]
Verified passed with 1.0.99rc1 using Asus Zenfone (x86). Encountered and logged https://github.com/brave/browser-android-tabs/issues/1748.
