### ISSUE TITLE
Main Brave Rewards switch is not aligned

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#914]
It is under the text when I switch on Russian language for example
![issue](https://user-images.githubusercontent.com/12011303/49487689-9bfd4780-f811-11e8-9eed-9a8a63c17c8c.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/ab2ab1a5b463f0bb6665ad32e67c41872c5052bf
