### ISSUE TITLE
ANR when re-enabling sync

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#919]
**Did you search for similar issues before submitting this one?**
Yes, https://github.com/brave/browser-android-tabs/issues/913 does look similar.

**Description:**
After several enable/disable/ sync iteration the application hangs with `Brave isn't responding` popup.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.1.2 
    
**Brave Version:**
1.0.71(sync2)(1140)

**Steps to reproduce:**
    1. Enable sync on desktop
    2. Connect Android to chain with QR code
    3. Delete Brave profile on computer
    4. On Android delete all devices from chain and delete this device
    5. Connect Android to Desktop with QR shown on desktop
    6. At this point I caught ANRs, even restart of the browser hadn't help

**Actual Behavior**
ANR

**Expected Behavior**
no ANR

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Not sure, tried once

**Any related issues:**
Maybe https://github.com/brave/browser-android-tabs/issues/913 

Log from monitor
[AndroidMonitor.log](https://github.com/brave/browser-android-tabs/files/2653676/AndroidMonitor.log)

File from /data/anr/traces.txt
[traces.txt](https://github.com/brave/browser-android-tabs/files/2653679/traces.txt)

**Comment by AlexeyBarabash** [comment]
Looked on desktop browser, see
![image](https://user-images.githubusercontent.com/24739341/49593847-3cbc4600-f97d-11e8-8bd4-1fe397fe407f.png)
looks Android tried to add itself into the chain each time I force stopped and tried to relaunch.

**Comment by AlexeyBarabash** [comment]
[Brave-Core_.txt](https://github.com/brave/browser-android-tabs/files/2653730/Brave-Core_.txt)
The log from brave-core just in case. Object id for each device is different 
```
[18483:18483:1206/173809.662520:INFO:CONSOLE(264)] ""resolved-sync-records" categoryName="PREFERENCES" records=[

{"action":0,"deviceId":{"0":0},"objectId":{"0":0,"1":81,"2":243,"3":42,"4":144,"5":143,"6":114,"7":60,"8":156,"9":171,"10":251,"11":54,"12":223,"13":121,"14":219,"15":57},
"device":{"name":"BC-A"},"objectData":"device","syncTimestamp":1544107152307},

{"action":0,"deviceId":{"0":1},"objectId":{"0":75,"1":173,"2":18,"3":247,"4":93,"5":123,"6":43,"7":101,"8":11,"9":179,"10":41,"11":172,"12":218,"13":99,"14":134,"15":107},
"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544107399310},

{"action":0,"deviceId":{"0":1},"objectId":{"0":0,"1":60,"2":64,"3":37,"4":200,"5":196,"6":208,"7":251,"8":110,"9":3,"10":210,"11":93,"12":71,"13":201,"14":212,"15":238},"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544107654875},

{"action":0,"deviceId":{"0":1},"objectId":{"0":52,"1":249,"2":192,"3":16,"4":14,"5":17,"6":173,"7":236,"8":19,"9":255,"10":154,"11":89,"12":254,"13":146,"14":16,"15":115},"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544107701074},

{"action":0,"deviceId":{"0":1},"objectId":{"0":47,"1":12,"2":249,"3":134,"4":101,"5":125,"6":52,"7":191,"8":196,"9":50,"10":148,"11":125,"12":150,"13":51,"14":134,"15":95},"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544108791323},

{"action":0,"deviceId":{"0":1},"objectId":{"0":109,"1":229,"2":146,"3":106,"4":83,"5":215,"6":25,"7":219,"8":115,"9":41,"10":102,"11":117,"12":220,"13":222,"14":23,"15":43},"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544108894011},

{"action":0,"deviceId":{"0":1},"objectId":{"0":39,"1":244,"2":149,"3":18,"4":26,"5":49,"6":62,"7":0,"8":196,"9":193,"10":136,"11":180,"12":61,"13":216,"14":106,"15":96},"device":{"name":"mi4c"},"objectData":"device","syncTimestamp":1544109122511}]", source: chrome-extension://nomlkjnggnifocmealianaaiobmebgil/extension/background.js (264)
```

**Comment by AlexeyBarabash** [comment]
Fixed by https://github.com/brave/browser-android-tabs/pull/934 .

**Comment by LaurenWags** [comment]
Verified passed with 1.0.72(sync1)

**Comment by btlechowski** [comment]
Verification passed on Samsung s7 (ARM), Brave 1.0.75.
