### ISSUE TITLE
All bookmarks never gets sync'd to Android device

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#925]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
All bookmarks never gets sync'd to Android device

## Devices
Device 1: 0.58.11 (sync chain creator)
Device 2: Samsung Tab (1.0.71(sync2))
    
**Steps to reproduce:**
    1. Create sync chain on desktop
    2. Import bookmarks using this file( [brave_sorted_1000.zip](https://github.com/brave/browser-android-tabs/files/2667527/brave_sorted_1000.zip))
    3. Add the Android device to sync chain
    4. Wait for bookmarks to sync
    5. Keep waiting for bookmarks to sync completely
    6. Take a nap and then see if bookmarks is completely sync'd

**Actual Behavior**
Full sync  doesn't happen on Android
Desktop sync code
![screenshot from 2018-12-11 18-01-59](https://user-images.githubusercontent.com/17010094/49800968-e0876680-fd6e-11e8-976b-8e990d16072d.png)
Andriod sync code
![screenshot_20181211-073222_brave](https://user-images.githubusercontent.com/17010094/49801038-0f054180-fd6f-11e8-9db6-05e6f83f497d.jpg)
bc folder structure for bookmarks
![screenshot from 2018-12-11 17-58-00](https://user-images.githubusercontent.com/17010094/49801063-25ab9880-fd6f-11e8-92c7-bf6c70653934.png)
bc with Mobile bookmarks syncd
![screenshot from 2018-12-11 17-58-00](https://user-images.githubusercontent.com/17010094/49801084-352ae180-fd6f-11e8-929b-f82df436832f.png)
Android bookmarks after sync
![screenshot_20181211-072623_brave](https://user-images.githubusercontent.com/17010094/49801117-48d64800-fd6f-11e8-9d11-9457ff5f22d7.jpg)

**Expected Behavior**
All boookmarks should be imported to Android device

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
NA

**Can this issue be consistently reproduced?**
Yes

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Any related issues:**
cc: @brave/legacy_qa @rebron @brave/android

**Comment by kjozwiak** [comment]
@LaurenWags just wondering, this is the issue where you mentioned that only 600/1k of the bookmarks were actually synced correct?

**Comment by GeetaSarvadnya** [comment]
All the bookmarks from brave core 0.59.13  are imported in Android 1.0.72(sync1).

BC - 0.59.13
![image](https://user-images.githubusercontent.com/38657976/50538418-99cea480-0b95-11e9-8e60-158eadb818ec.png)
Android 1.0.72(sync1)
![screenshot_2018-12-29-18-12-45](https://user-images.githubusercontent.com/38657976/50538453-1bbecd80-0b96-11e9-9611-1660a1ca381c.png)
![screenshot_2018-12-29-18-13-09](https://user-images.githubusercontent.com/38657976/50538454-1bbecd80-0b96-11e9-90b0-c7228dfa711d.png)
![screenshot_2018-12-29-18-16-27](https://user-images.githubusercontent.com/38657976/50538455-1c576400-0b96-11e9-861b-f05d6f648537.png)
