### ISSUE TITLE
Connections to Google Servers

### ISSUE THREAD

**Issue by binarious** [brave/browser-android-tabs#932]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
I've analyzed network connections of my apps and saw that brave connects to 1e100.net all the time. Even when no tabs are opened. 1e100.net is a [Google-owned domain](https://support.google.com/faqs/answer/174717?hl=en). Is there something I have to disable? I've disabled things like suggestions on navigation errors or autocompletion of search results, etc.
I primarily wanted to use Brave to remove my Google footprint.

**Device Details:**
   - Install Type(ARM, x86): 🤷‍♂️ 
   - Device(Phone, Tablet, Phablet): OnePlus 5T
   - Android Version: 8.1.0 (LineageOS 15.1, w/o GApps)
    
**Brave Version:** 1.0.70

**Steps to reproduce:**
    1. Start [Net Monitor](https://f-droid.org/packages/org.secuso.privacyfriendlynetmonitor/)
    2. Start Brave

**Actual Behavior**
See connections to 1e100.net.

**Expected Behavior**
No connections to Google.

**Is this an issue with Beta build?**
No

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Comment by binarious** [comment]
nvm, had "Tap to search" active which states it sends data to Google servers. Disabled that and the connections went away.

**Comment by anthonypkeane** [comment]
Reopening as it seems like we have a bug here

https://bravesoftware.slack.com/archives/G2KN13Z8C/p1559322258003800

**Comment by tomlowenthal** [comment]
Closing in favor of #1871

**Comment by srirambv** [comment]
Moving out of 1.20 milestone as issue is closed in favour of #1871 which is not part of this milestone
