### ISSUE TITLE
Brave hangs on Android when try to re-sync with Desktop

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#933]
**Did you search for similar issues before submitting this one?**

**Description:**
Brave hangs on Android when try to re-sync with Desktop

**Device Details:**
   - Install Type(ARM, x86): ARM 
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
    
**Devices:**
Device1 : Desktop Windows 10 - Bravebeta `0.59.8`
Device2: Android 5.1- Brave `1.0.71 (sync2)`

**Brave Version:**
1.0.71 (sync2)

**Steps to reproduce:**
    1. Sync Desktop and Android through QR code
    2. Make sure sync is established b/n devices
    3. Remove Android from desktop
    4. Again re-sync Android with desktop

**Actual Behavior**
When user tries to re-sync with desktop, android keeps shwoing the message as `Loading devices....` After sometimes browser hangs, unable to use it until we un-install

**Expected Behavior**
Should not be any browser hang

**Is this an issue with Beta build?**

**Is this an issue in the currently released version?** NA

**Can this issue be consistently reproduced?** Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

**Any related issues:**

**Comment by AlexeyBarabash** [comment]
@srirambv looks like a dup, but I am not sure until fix for one issue will cure another issue.

**Comment by AlexeyBarabash** [comment]
Closing this as fixed with https://github.com/brave/browser-android-tabs/pull/934. As https://github.com/brave/brave-core/pull/1125 does not affect on release build.

**Comment by btlechowski** [comment]
Verification passed on Samsung s7 (ARM), Brave 1.0.75.
