### ISSUE TITLE
Default Browser logic

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#938]
**Description:**
Implement a feature that makes it easier for a user to set Brave as their default Browser. 

**Spec**
https://docs.google.com/document/d/1QlfBbG4uQXGHOJgI34V6J1ywWfZuXnzOPf2TGCIpC7I/edit#heading=h.6a5emqz1cz0

**Comment by yachtcaptain23** [comment]
Functionality is enabled.
