### ISSUE TITLE
Need chrome://rewards/#add-funds for Android BR site similar to Desktop

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#969]
The Android version of BR has no way to deeplink into add funds. Need an anchor similar to desktop chrome://rewards/#add-funds to deep link to add-funds.

Please reassign to @SergeyZhukovsky when completed.

**Comment by ryanml** [comment]
Issue completed via: https://github.com/brave/browser-android-tabs/commit/814af3c4eda2321205dc5c8a8dcc55e3902fe0a2
