### ISSUE TITLE
Not all strings are being localized correctly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-android-tabs#976]
There's currently a bug in the string fingerprint calculations that Android code base does here:

https://github.com/brave/browser-android-tabs/blob/b4d565f0748c0b3ea189c71d76222144d2823507/tools/grit/grit/extern/rebrand_to_brave.py

For any of the 3 lines with `0x7fffffffffffffffL` it should look more like this:

```
-    return FP.FingerPrint(string_to_hash) & 0x7fffffffffffffffL
+    fp = FP.FingerPrint(string_to_hash)
+    meaning = (message_tag.get('meaning') if 'meaning' in message_tag.attrib
+               else None)
+    if meaning:
+        # combine the fingerprints of message and meaning
+        fp2 = FP.FingerPrint(meaning)
+        if fp < 0:
+          fp = fp2 + (fp << 1) + 1
+        else:
+          fp = fp2 + (fp << 1)
+    # To avoid negative ids we strip the high-order bit
+    return str(fp & 0x7fffffffffffffffL)
```

It combines the `meaning` attribute value if it exists with the fingerprint according to the above logic.

You can see how Chromium calculates the fingerprint ID here:
https://github.com/brave/browser-android-tabs/blob/master/tools/grit/grit/extern/tclib.py#L35

**Comment by bbondy** [comment]
To verify if you want to test you can use these string ids:

```ui/strings/translations/ui_strings_en-GB.xtb:<translation id="5076340679995252485">&amp;Paste</translation>```

```
chrome/app/resources/generated_resources_en-GB.xtb:<translation id="5233736638227740678">&amp;Paste</translation>
chrome/app/resources/generated_resources_en-GB.xtb:<translation id="8248050856337841185">&amp;Paste</translation>
chrome/app/resources/generated_resources_en-GB.xtb:<translation id="9033857511263905942">&amp;Paste</translation>
```


The way that these are generated right now on Android it will always give `5076340679995252485` but the various cases above have different `meaning` attributes which alter the correct value.

**Comment by samartnik** [comment]
Fixed here https://github.com/brave/browser-android-tabs/commit/efb69bb27cef97848c3cbd6ccfb6253e790a7e74
Thanks @bbondy
