### ISSUE TITLE
Add a Brave Rewards menu item 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#977]
Add a Brave Rewards menu item so users can access rewards from the menu

@jamesmudgett can you please provide a design and reassign to @SergeyZhukovsky once uploaded here

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett @anthonypkeane any update on that?

**Comment by anthonypkeane** [comment]
Hi @SergeyZhukovsky 

Please place a Brave Rewards menu item above settings 

![menu-br](https://user-images.githubusercontent.com/7606853/52224064-f2abef80-285b-11e9-980b-d0c2b7e8cdaf.jpg)

**Comment by SergeyZhukovsky** [comment]
It's done here https://github.com/brave/browser-android-tabs/commit/9e08a8d653c65395d21db81d6d9703fd66b89410
