### ISSUE TITLE
Add a new setting that allows Brave Rewards icon to be hidden when inactive

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#978]
We need to follow the Desktop implementation for this, please see: 
https://github.com/brave/brave-browser/issues/2975

**Comment by rebron** [comment]
cc: me @rebron

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane where should it be placed on Android?

**Comment by jamesmudgett** [comment]
See anything wrong with doing it like this?

In settings we will need a top level row for "Brave Rewards"

Sub settings after tapping "Brave Rewards":

1) Settings (opens Brave Rewards settings)
2) Hide Icon when disabled (yes / no)

@SergeyZhukovsky @anthonypkeane

**Comment by anthonypkeane** [comment]
Below is the design for this.

The user can decide whether or not to have the BR icon on or off, even if Rewards is enabled or not

The default is On (BR icon is shown)


![br settings settings](https://user-images.githubusercontent.com/7606853/53589232-ba8a8a80-3b43-11e9-9986-2584dc065965.jpg)

**Comment by anthonypkeane** [comment]
**Update**: _(and apologies for any confusion)_

The behaviour on desktop is different and we should align. 

See: https://github.com/brave/brave-browser/issues/1475

From the above design the text will change as follows: 

Display -> Appearance 
Show Brave Rewards Icon -> Hide Brave Rewards Icon

Under Hide Brave Rewards Icon add the following sub text
Hides the Brave Rewards Icon when Brave Rewards is not enabled

Default is Off meaning the Rewards Icon is displayed

Note: Hide Brave Rewards Icon will be greyed out when Brave Rewards is enabled as hiding the icon on the URL bar is not possible in this case.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/af145970250cb44bf5382d08e268b9572813c865

**Comment by btlechowski** [comment]
Verification passed on Samsung s7, BraveMonoarm v1.0.90-rc.2

![Screenshot_20190408-175018_Brave](https://user-images.githubusercontent.com/34715963/55738412-6074c300-5a27-11e9-9696-84e114b81851.jpg)

**Comment by GeetaSarvadnya** [comment]
@anthonypkeane On Clean profile, Navigate to settings ->Display->Appearence, turn ON/OFF `Hide Brave Rewards Icon` asks for Browser `RELAUNCH NOW` and `LATER` options, Is this expected? as this behavior is not same in BC.

**Comment by srirambv** [comment]
@GeetaSarvadnya  that is expected. @SergeyZhukovsky  confirmed it
