### ISSUE TITLE
adding a way to stop `Loading Devices` phase if stuck

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#979]
## Description 

I got into a situation where I scanned the QR code from a desktop machine on my android device and got stuck during the `Loading Devices` phase. The android device appeared on the other machines but never got past `Loading Devices`. I waited ~25min and it never recovered. Attempted to restart the application several times and was eventually forced to reinstall.

## Steps to Reproduce

   1. Computer A: Using 0.59.24 Chromium: 72.0.3626.53, start a sync chain via `brave://sync`
   2. Add `1.0.72 (sync 2), CR: 71.0.3578.99` by scanning the QA code on the machine above

Sometimes the android device gets stuck on `Loading Devices` even though it's appearing under Computer A.

## Actual result:

![screenshot_20190116-193219](https://user-images.githubusercontent.com/2602313/51294574-8d45ab00-19e1-11e9-8784-7dd5ee8e9b62.png)

## Expected result:

Users should be able to stop the creation the of the `sync chain` during the `Loading Devices`.

## Reproduces how often: 

I'm not 100% sure as I've only seen this happen twice. It's pretty rare but when it happens, you're basically stuck.

## Brave version (brave://version info)

`1.0.72 (sync 2), CR: 71.0.3578.99`

**Comment by anthonypkeane** [comment]
I've seen this on Desktop but not on Android @kjozwiak 
After 30-45 seconds, or if I press Cancel, the chain still got created. 

In your case @kjozwiak , did the chain get created and Bookmarks sync?

**Comment by anthonypkeane** [comment]
I suggest after ~20 seconds we display a Cancel button which can we positioned above "add another device"

20 seconds should be enough time for the chain to be created.

Pressing Cancel should remove the device from the chain, clear the UI and allow the user to start setting up the chain again.

**Comment by kjozwiak** [comment]
> In your case @kjozwiak , did the chain get created and Bookmarks sync?

Nope, in this particular case, I left the device running for ~1hr and it was still stuck in that stage. I've had this happen to be twice so it's not super common. I believe @srirambv mentioned that he's run into the above once before as well.

> I suggest after ~20 seconds we display a Cancel button which can we positioned above "add another device"
> 
> 20 seconds should be enough time for the chain to be created.
> 
> Pressing Cancel should remove the device from the chain, clear the UI and allow the user to start setting up the chain again.

Agreed 👍 Sounds like a fair solution.

**Comment by AlexeyBarabash** [comment]
Created PR for this issue https://github.com/brave/browser-android-tabs/pull/1040 .

**Comment by AlexeyBarabash** [comment]
Fixed with https://github.com/brave/browser-android-tabs/pull/1040 PR.
