### ISSUE TITLE
Update toolbar for Brave Rewards release

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#980]
![home](https://user-images.githubusercontent.com/318119/51355980-b1e76480-1a6d-11e9-9d45-cce430612605.png)

[toolbar.zip](https://github.com/brave/browser-android-tabs/files/2771002/toolbar.zip)

* Removes history from rewards beta builds

**Comment by jamesmudgett** [comment]
@anthonypkeane @yachtcaptain23 Since there are issues with changing chromium icon weight please update our bookmarks and home buttons to match the chromium icon weight. Attached new home and bookmarks icons.
[home and bookmarks.zip](https://github.com/brave/browser-android-tabs/files/2958329/home.and.bookmarks.zip)

**Comment by jamesmudgett** [comment]
[search.zip](https://github.com/brave/browser-android-tabs/files/2958446/search.zip)

**Comment by jamesmudgett** [comment]
Replace + with search

**Comment by jamesmudgett** [comment]
New toolbar design update: 
![Screen Shot 2019-03-14 at 5 29 25 PM (1)](https://user-images.githubusercontent.com/318119/54565705-f5dae500-499c-11e9-813b-81975651a6c4.png)

- Replace Bookmarks button with Search: URL bar to focus when tapping search icon.
- Home button should be hidden if Homepage toggle is disabled in settings.
- Tapping + will create new tab and focus URL bar.

**Comment by anthonypkeane** [comment]
@jamesmudgett can you update this screenshot to the correct one? ^^

**Comment by anthonypkeane** [comment]
@jamesmudgett pls confirm this is the correct screen

![device-2019-03-21-141412](https://user-images.githubusercontent.com/7606853/54852628-9e918900-4caa-11e9-9b88-93e18c7e14a5.png)


https://bravesoftware.slack.com/archives/GEW5B9WRZ/p1553192429205200

**Comment by SergeyZhukovsky** [comment]
That is done in 1.0.89 milestone

**Comment by LaurenWags** [comment]
Verified passed with 1.0.90rc3 on Asus Zenfone (x86) - verified bottom toolbar displays as per https://github.com/brave/browser-android-tabs/issues/980#issuecomment-475780961
