### ISSUE TITLE
Brave rewards grant expire in the past

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#981]
## Description 
Brave rewards grant expire in the past

## Steps to Reproduce 

   1. Install rewards build
   2. Enable rewards and wait for grant token notification
   3. Expiry shows 1970, Google how to build time machine to back in time

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/51423299-014fa100-1be4-11e9-9505-0a19fa3f4b07.png)

## Expected result:
Should be in a month and stop yourself from buying/building  a time machine

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version? N/A
   - Beta build? Rewards build

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version:9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @ryanml

**Comment by SergeyZhukovsky** [comment]
@ryanml it's probably something with error handle that we mentioned earlier. Could you please take a look on it?

**Comment by srirambv** [comment]
On Samsung Tab I see expiry date goes back one more year to 1969

**Comment by ryanml** [comment]
Fixed here: ed5b6e33432c63bb2990bcdea09bcdb8fa2ade04

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
![screenshot_2019-02-27-22-32-00](https://user-images.githubusercontent.com/38657976/53508350-9301d680-3adf-11e9-975a-b22438b8b0c6.png)
