### ISSUE TITLE
Add funds modal should fit in view 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#984]
## Description 
Add funds modal should fit in view. The bottom part of the modal is out of focus or hides behind the bottom snackbar (see screenshot)

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/51423439-26ddaa00-1be6-11e9-861f-c7ebb490f681.png)

## Expected result:
Entire modal should be responsive to fit in view

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version:9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @ryanml

**Comment by ryanml** [comment]
So as it is, the modal window is responsive and says within the document viewport height. The issue seems to be the bottom Android toolbar covers the bottom of the modal. cc: @petemill if you have any ideas. cc: @SergeyZhukovsky

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/browser-android-tabs/commit/43a533b951fdc142fec32be71bd7d2698e522a8c

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
