### ISSUE TITLE
Text duplicated on manage wallet screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#985]
## Description 
Text duplicated on manage wallet screen

## Steps to Reproduce 

   1. Enable rewards
   2. Go to settings to manage wallet
   3. Click on Advanced options. The info text is duplicated (see screenshot)

## Actual result: 
![screenshot_20190119-122710](https://user-images.githubusercontent.com/17010094/51423472-b2573b00-1be6-11e9-8610-eb494f2a2b2f.png)

## Expected result:
Should not duplicate

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @NejcZdovc @SergeyZhukovsky @ryanml 
This is also an issue on B-c Linux https://github.com/brave/brave-browser/issues/2446

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74
![985](https://user-images.githubusercontent.com/34715963/51506140-003c9080-1deb-11e9-971a-1ab412f44846.jpg)

**Comment by ryanml** [comment]
Fixed via upstream changes

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`

![screenshot_2019-02-27-22-55-58](https://user-images.githubusercontent.com/38657976/53509990-fa6d5580-3ae2-11e9-9bfc-6ab51e437d83.png)
