### ISSUE TITLE
Duplicate text in restore wallet modal 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#986]
## Steps to Reproduce 

   1. Open advance settings in rewards
   2. Switch to restore
   3. Enter your recovery code or is duplicated below the text input area

## Actual result: 
![screenshot_20190119-122716](https://user-images.githubusercontent.com/17010094/51423494-0c580080-1be7-11e9-8f83-d4437049b2f0.png)

## Expected result:
Should have proper text

## Issue reproduces how often: 
Easy 

## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @NejcZdovc @SergeyZhukovsky @ryanml . This is an issue on b-c Linux as well https://github.com/brave/brave-browser/issues/2481

**Comment by btlechowski** [comment]
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74
![986](https://user-images.githubusercontent.com/34715963/51506199-65908180-1deb-11e9-9f51-bf538c3084c6.jpg)

**Comment by ryanml** [comment]
Fixed via upstream changes

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
![screenshot_2019-02-27-22-51-02](https://user-images.githubusercontent.com/38657976/53509649-33f19100-3ae2-11e9-9227-06d431501b40.png)
