### ISSUE TITLE
Import key isn't responsive

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#987]
## Description 
Import key isn't responsive

## Steps to Reproduce 

   1. Enable rewards and go to advance
   2. Restore wallet
   3. Click on import and navigate to import the recovery code text file
   4. No response feedback after selecting the file

## Actual result: 
Import key isn't responsive

## Expected result:
Should show the code words in the text box or error out if the file is invalid

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version? No
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @NejcZdovc @SergeyZhukovsky @ryanml

**Comment by SergeyZhukovsky** [comment]
@ryanml it could be a problem outside HTML, but could you please let us know what calls are missed there?

**Comment by ryanml** [comment]
@SergeyZhukovsky JS logic was missing, fixed here: https://github.com/brave/browser-android-tabs/commit/a8e172cb03d8226d515110a6e524b04b57c4e6a4

**Comment by ryanml** [comment]
Just like desktop, error will show if bad file is uploaded, and rewards will proceed to recover if a good file is provided.

![screenshot_20190305-181048_brave - debug](https://user-images.githubusercontent.com/8732757/53848565-aee6fb80-3f69-11e9-9232-e07a89f3f448.jpg)
