### ISSUE TITLE
Rewards tab needs a favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#988]
## Description 
New tab and Rewards tab need favicons

## Steps to Reproduce 

   1. Open rewards page
   2. Open a new tab page
   3. Go to tabs overview, both tabs have generic page icon

## Actual result: 
![screenshot_20190119-124703](https://user-images.githubusercontent.com/17010094/51423593-9c4a7a00-1be8-11e9-9439-9b719b598a4d.png)

## Expected result:
both tabs should have its own favicon

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@jamesmudgett @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
New tab page it is expected as no icon there. @ryanml is it possible to have an icon on `chrome://rewards`. @srirambv I don't see any icon on desktop rewards settings page btw.

**Comment by srirambv** [comment]
There's an issue logged for desktop as well to implement favicons for all custom brave pages https://github.com/brave/brave-browser/issues/1278

**Comment by ryanml** [comment]
@SergeyZhukovsky I can update the favicon for that page

**Comment by jamesmudgett** [comment]
Use BAT icon.

**Comment by jamesmudgett** [comment]
@ryanml page title for Brave Rewards screen should be "Brave Rewards" not just "Rewards", we should also add the TM character as well.

**Comment by ryanml** [comment]
Favicon added to `chrome://rewards` here: https://github.com/brave/browser-android-tabs/commit/676244778dd647c59b6a3474e48a556392274585

(Note that new tab is not being updated for this issue)

@jamesmudgett title updated: https://github.com/brave/browser-android-tabs/commit/2f15f65430070fbb9b1076f4fcf0addec168f1ff

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on 1.0.83
