### ISSUE TITLE
Rewards build doesn't install over an existing install

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#989]
## Description 
Rewards build doesn't install over an existing install

## Steps to Reproduce 

   1. Install playstore build
   2. Download 1.0.74 from releases page
   3. Try to install the downloaded file, installation fails
   4. Uninstall existing playstore build and reinstall downloaded file, installation successful

## Actual result: 
Installation fails on existing appstore build

## Expected result:
Should install over existing install as an upgrade

## Issue reproduces how often: 
Easy 

## Issue happens on: 
   - Current Playstore version? NO
   - Beta build?Yes

## Device Details:
   - Install Type(ARM, x86): ARM 
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @samartnik

**Comment by SergeyZhukovsky** [comment]
That's will be resolved. The problem is the current Brave Rewards version is on chromium 70 and the current play store version is on chromium 71. We are going to rebase next week.

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Android ARM - Samsung Galaxy J3 - version 5.1` - Tested on Brave version `1.0.83`
