### ISSUE TITLE
Broken favicons in a-c list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#990]
## Description 
Broken favicons in a-c list

## Steps to Reproduce 

   1. Enable rewards
   2. Visit a non-verified pub site wait for 10 secs
   3. Site gets added to a-c list, but site shows broken icon

## Actual result: 
![screenshot_20190119-125722](https://user-images.githubusercontent.com/17010094/51423721-28a96c80-1bea-11e9-8e0e-c735690417d5.png)

## Expected result:
Should show proper favicon

## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM 
   - Device(Phone, Tablet, Phablet): Pixel 3XL
   - Android Version:9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@ryanml @NejcZdovc @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on 1.0.83
