### ISSUE TITLE
Padding needed on Tip Screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#995]
May need to add some padding on the tip screen.

Jenn pls confirm? 

If Yes, please provide Ryan with the info needed

![screenshot (2).jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/3e3edc7a-420d-46a2-955b-b618f794dbef)

**Comment by ryanml** [comment]
@anthonypkeane reassigning this to @SergeyZhukovsky as panel is now native

**Comment by SergeyZhukovsky** [comment]
Padding issue is addressed here https://github.com/brave/browser-android-tabs/issues/1126
