### ISSUE TITLE
BR icon flickering when navigating to an old Tab

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#996]
The BR icon is flickering when navigating to an existing tab

![BR Icon Flicker.gif](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/5dd86cb8-8d11-4902-89f9-4a855423b9d5)

**Comment by srirambv** [comment]
This happens on swipe navigation as well either via bottom bar or on the urlbar
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/17010094/51459929-17926400-1d80-11e9-992d-e3620c39f3cb.gif)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/ba80562aeb65c2e6dd3f63209c4a9f1b240c338a
