### ISSUE TITLE
Favicon on YT is pixelated

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#997]
YouTube favicon is pixelated

(BTW, we shouldn't be displaying YT here, we should be displaying the publisher)

![screenshot.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/6f707ba7-fb24-46c9-a601-761e06d4848f)

**Comment by jamesmudgett** [comment]
Fallback favicon should be used for these cases 
[Favicon Spec.pdf](https://github.com/brave/browser-android-tabs/files/2788920/Favicon.Spec.pdf)

**Comment by gdregalo** [comment]
Fixed in:
https://github.com/brave/browser-android-tabs/commit/23175f66aed1bd9fed68b5e8746d10555247b0b0
