### ISSUE TITLE
Displaying the YT favicon instead of the Pub's favicon on the Panel

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#998]
Linked to #997

We should be displaying the publisher's favicon not YouTube's favicon on the panel.

I was watching a YouTube video from fullychargedshow (Fully Charged) yet the YT favicon was displayed 

@mandar-brave pls confirm? 

![screenshot.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/5e2caa5c-7717-46cb-b225-82ba5298e5d4)

**Comment by srirambv** [comment]
On Desktop only verified pubs favicon is shown for YT. Non-verified pubs will have YT logo. 

cc: @NejcZdovc

**Comment by srirambv** [comment]
Verified pub shows up favicon. 
![screenshot_20190121-074524](https://user-images.githubusercontent.com/17010094/51449116-996a9900-1d50-11e9-9ef9-f91f82a3ee43.png)

**Comment by anthonypkeane** [comment]
![screenshot 2](https://user-images.githubusercontent.com/7606853/51449724-3510f080-1ce2-11e9-9527-a794f24f6b96.jpg)

I'm guessing FullyCharged is not verified yet the favicon is displaying.

**Comment by anthonypkeane** [comment]
Ok

There still is a bug here and we don’t do this consistently

**Comment by jamesmudgett** [comment]
Fallback favicon should be used for cases where icon is pixelated or missing. Also, all BR related panels will display favicon displayed as a circle.
[Favicon Spec.pdf](https://github.com/brave/browser-android-tabs/files/2788924/Favicon.Spec.pdf)

**Comment by SergeyZhukovsky** [comment]
The original issue with general YT icon for non verified creators is done. The pixelated icon issue will be addressed here https://github.com/brave/browser-android-tabs/issues/997
